.TH "sources Directory Reference" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBqcomplexnumber\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqfouriercalculator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqfourierfixedcalculator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqfouriertransformer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqfouriervariablecalculator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqwindowfunction\&.cpp\fP"
.br
.in -1c
