.TH "headers Directory Reference" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBqcomplexnumber\&.h\fP"
.br
.ti -1c
.RI "file \fBqfouriercalculator\&.h\fP"
.br
.ti -1c
.RI "file \fBqfourierfixedcalculator\&.h\fP"
.br
.ti -1c
.RI "file \fBqfouriertransformer\&.h\fP"
.br
.ti -1c
.RI "file \fBqfouriervariablecalculator\&.h\fP"
.br
.ti -1c
.RI "file \fBqwindowfunction\&.h\fP"
.br
.in -1c
