.TH "cmd_sensor.cpp" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmd_sensor.cpp \- 
\&.\&.\&.\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include 'form\&.h'\fP
.br
\fC#include 'record_preview\&.h'\fP
.br

.SH "Detailed Description"
.PP 
\&.\&.\&.\&. 


.PP
Definition in file \fBcmd_sensor\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
