.TH "console.h" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
console.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QPlainTextEdit>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConsole\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
