Console
NAME
Console -
SYNOPSIS
#include <console.h>
Inherits QPlainTextEdit.
Signals
void getData (const QByteArray &data)
Public Member Functions
Console (QWidget *parent=0)
void putData (const QByteArray &data)
void setLocalEchoEnabled (bool set)
QString uint8_to_str (quint8 val)
Public Attributes
QPalette p
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *e)
virtual void mousePressEvent (QMouseEvent *e)
virtual void mouseDoubleClickEvent (QMouseEvent *e)
virtual void contextMenuEvent (QContextMenuEvent *e)
Detailed Description
Definition at line 48 of file console.h.
Constructor & Destructor Documentation
Console::Console (QWidget *parent = 0) [explicit]
Definition at line 49 of file console.cpp.
References p.
    : QPlainTextEdit(parent)
    , localEchoEnabled(false)
{
    document()->setMaximumBlockCount(100);
    p = palette();
    p.setColor(QPalette::Base, Qt::black);
    p.setColor(QPalette::Text, Qt::green);
    setPalette(p);
}
Member Function Documentation
void Console::contextMenuEvent (QContextMenuEvent *e) [protected], [virtual]
Definition at line 110 of file console.cpp.
{
    Q_UNUSED(e)
}
void Console::getData (const QByteArray &data) [signal]
Definition at line 120 of file moc_console.cpp.
Referenced by keyPressEvent().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 0, _a);
}
void Console::keyPressEvent (QKeyEvent *e) [protected], [virtual]
Definition at line 82 of file console.cpp.
References getData().
{
    switch (e->key()) {
    case Qt::Key_Backspace:
    case Qt::Key_Left:
    case Qt::Key_Right:
    case Qt::Key_Up:
    case Qt::Key_Down:
        // skip processing
        break;
    default:
        if (localEchoEnabled)
            QPlainTextEdit::keyPressEvent(e);
        emit getData(e->text().toLocal8Bit());
    }
}
void Console::mouseDoubleClickEvent (QMouseEvent *e) [protected], [virtual]
Definition at line 105 of file console.cpp.
{
    Q_UNUSED(e)
}
void Console::mousePressEvent (QMouseEvent *e) [protected], [virtual]
Definition at line 99 of file console.cpp.
{
    Q_UNUSED(e)
    setFocus();
}
void Console::putData (const QByteArray &data)
Definition at line 61 of file console.cpp.
References uint8_to_str().
{
    QString str;
    for(int ii =0;ii<data.length();ii++)
        str.append(uint8_to_str((quint8)data.at(ii)));
    insertPlainText(QString(data));
    QScrollBar *bar = verticalScrollBar();
    bar->setValue(bar->maximum());
}
void Console::setLocalEchoEnabled (boolset)
Definition at line 77 of file console.cpp.
{
    localEchoEnabled = set;
}
QString Console::uint8_to_str (quint8val)
Definition at line 116 of file console.cpp.
Referenced by putData().
{
    const char cnv[] = "0123456789ABCDEF";
    return QString(cnv[(val>>4)&0x0F]) + QString(cnv[(val>>0)&0x0F]);
}
Member Data Documentation
QPalette Console::p
Definition at line 64 of file console.h.
Referenced by Console().
Author
Generated automatically by Doxygen for AQ0X from the source code.