.TH "def.h" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
def.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBffft\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBffft_FORCEINLINE\fP   inline"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fBffft::PI\fP = 3\&.1415926535897932384626433832795"
.br
.ti -1c
.RI "const double \fBffft::SQRT2\fP = 1\&.41421356237309514547462185873883"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ffft_FORCEINLINE   inline"

.PP
Definition at line 46 of file def\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
