.TH "emu_data_editor.cpp" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emu_data_editor.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'emu_data_editor\&.h'\fP
.br
\fC#include 'ui_emu_data_editor\&.h'\fP
.br
\fC#include 'slider\&.h'\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QDesktopServices>\fP
.br
\fC#include <QDateTime>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QKeyEvent>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
