.TH "emu_data_editor.h" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emu_data_editor.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include 'typedef\&.h'\fP
.br
\fC#include 'define\&.h'\fP
.br
\fC#include 'console\&.h'\fP
.br
\fC#include '\&.\&./fft/headers/qfouriertransformer\&.h'\fP
.br
\fC#include <QVector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBemu_data_editor\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNO_OF_SLIDERS\fP   100"
.br
.ti -1c
.RI "#define \fBFFT_SIZE\fP   256"
.br
.ti -1c
.RI "#define \fBMAX_SPECTRUM_MAGNITUDE\fP   100"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FFT_SIZE   256"

.PP
Definition at line 12 of file emu_data_editor\&.h\&.
.PP
Referenced by emu_data_editor::emu_data_editor(), and emu_data_editor::update_curve()\&.
.SS "#define MAX_SPECTRUM_MAGNITUDE   100"

.PP
Definition at line 13 of file emu_data_editor\&.h\&.
.SS "#define NO_OF_SLIDERS   100"

.PP
Definition at line 11 of file emu_data_editor\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
