ffft::FFTReal< DT >
NAME
ffft::FFTReal< DT > -
SYNOPSIS
#include <FFTReal.h>
Public Types
enum { MAX_BIT_DEPTH = 30 }
typedef DT DataType
Public Member Functions
FFTReal (long length)
virtual ~FFTReal ()
long get_length () const
void do_fft (DataType f[], const DataType x[]) const
void do_ifft (const DataType f[], DataType x[]) const
void rescale (DataType x[]) const
DataType * use_buffer () const
Detailed Description
template<class DT>class ffft::FFTReal< DT >
Definition at line 42 of file FFTReal.h.
Member Typedef Documentation
template<class DT> typedef DT ffft::FFTReal< DT >::DataType
Definition at line 51 of file FFTReal.h.
Member Enumeration Documentation
template<class DT> anonymous enum
Enumerator
MAX_BIT_DEPTH
Definition at line 49 of file FFTReal.h.
{ MAX_BIT_DEPTH = 30 }; // So length can be represented as long int
Constructor & Destructor Documentation
template<class DT > ffft::FFTReal< DT >::FFTReal (longlength) [explicit]
Definition at line 90 of file FFTReal.hpp.
: _length (length)
, _nbr_bits (FFTReal_get_next_pow2 (length))
, _br_lut ()
, _trigo_lut ()
, _buffer (length)
, _trigo_osc ()
{
    assert (FFTReal_is_pow2 (length));
    assert (_nbr_bits <= MAX_BIT_DEPTH);
    init_br_lut ();
    init_trigo_lut ();
    init_trigo_osc ();
}
template<class DT> virtual ffft::FFTReal< DT >::~FFTReal () [inline], [virtual]
Definition at line 54 of file FFTReal.h.
{}
Member Function Documentation
template<class DT > void ffft::FFTReal< DT >::do_fft (DataTypef[], const DataTypex[]) const
Definition at line 143 of file FFTReal.hpp.
Referenced by QFourierVariableCalculator::forward().
{
    assert (f != 0);
    assert (f != use_buffer ());
    assert (x != 0);
    assert (x != use_buffer ());
    assert (x != f);
    // General case
    if (_nbr_bits > 2)
    {
        compute_fft_general (f, x);
    }
    // 4-point FFT
    else if (_nbr_bits == 2)
    {
        f [1] = x [0] - x [2];
        f [3] = x [1] - x [3];
        const DataType b_0 = x [0] + x [2];
        const DataType b_2 = x [1] + x [3];
        
        f [0] = b_0 + b_2;
        f [2] = b_0 - b_2;
    }
    // 2-point FFT
    else if (_nbr_bits == 1)
    {
        f [0] = x [0] + x [1];
        f [1] = x [0] - x [1];
    }
    // 1-point FFT
    else
    {
        f [0] = x [0];
    }
}
template<class DT > void ffft::FFTReal< DT >::do_ifft (const DataTypef[], DataTypex[]) const
Definition at line 204 of file FFTReal.hpp.
Referenced by QFourierVariableCalculator::inverse().
{
    assert (f != 0);
    assert (f != use_buffer ());
    assert (x != 0);
    assert (x != use_buffer ());
    assert (x != f);
    // General case
    if (_nbr_bits > 2)
    {
        compute_ifft_general (f, x);
    }
    // 4-point IFFT
    else if (_nbr_bits == 2)
    {
        const DataType b_0 = f [0] + f [2];
        const DataType b_2 = f [0] - f [2];
        x [0] = b_0 + f [1] * 2;
        x [2] = b_0 - f [1] * 2;
        x [1] = b_2 + f [3] * 2;
        x [3] = b_2 - f [3] * 2;
    }
    // 2-point IFFT
    else if (_nbr_bits == 1)
    {
        x [0] = f [0] + f [1];
        x [1] = f [0] - f [1];
    }
    // 1-point IFFT
    else
    {
        x [0] = f [0];
    }
}
template<class DT > long ffft::FFTReal< DT >::get_length () const
Definition at line 119 of file FFTReal.hpp.
Referenced by QFourierVariableCalculator::setSize().
{
    return (_length);
}
template<class DT > void ffft::FFTReal< DT >::rescale (DataTypex[]) const
Definition at line 259 of file FFTReal.hpp.
Referenced by QFourierVariableCalculator::rescale().
{
    const DataType mul = DataType (1.0 / _length);
    if (_length < 4)
    {
        long i = _length - 1;
        do
        {
            x [i] *= mul;
            --i;
        }
        while (i >= 0);
    }
    else
    {
        assert ((_length & 3) == 0);
        // Could be optimized with SIMD instruction sets (needs alignment check)
        long i = _length - 4;
        do
        {
            x [i + 0] *= mul;
            x [i + 1] *= mul;
            x [i + 2] *= mul;
            x [i + 3] *= mul;
            i -= 4;
        }
        while (i >= 0);
    }
}
template<class DT > FFTReal< DT >::DataType * ffft::FFTReal< DT >::use_buffer () const
Definition at line 310 of file FFTReal.hpp.
{
    return (&_buffer [0]);
}
Author
Generated automatically by Doxygen for AQ0X from the source code.