.TH "ffft" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ffft \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArray\fP"
.br
.ti -1c
.RI "class \fBDynArray\fP"
.br
.ti -1c
.RI "class \fBFFTReal\fP"
.br
.ti -1c
.RI "class \fBFFTRealFixLen\fP"
.br
.ti -1c
.RI "class \fBFFTRealFixLenParam\fP"
.br
.ti -1c
.RI "class \fBFFTRealPassDirect\fP"
.br
.ti -1c
.RI "class \fBFFTRealPassInverse\fP"
.br
.ti -1c
.RI "class \fBFFTRealSelect\fP"
.br
.ti -1c
.RI "class \fBFFTRealUseTrigo\fP"
.br
.ti -1c
.RI "class \fBOscSinCos\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fBPI\fP = 3\&.1415926535897932384626433832795"
.br
.ti -1c
.RI "const double \fBSQRT2\fP = 1\&.41421356237309514547462185873883"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const double ffft::PI = 3\&.1415926535897932384626433832795"

.PP
Definition at line 37 of file def\&.h\&.
.SS "const double ffft::SQRT2 = 1\&.41421356237309514547462185873883"

.PP
Definition at line 38 of file def\&.h\&.
.PP
Referenced by ffft::FFTRealPassDirect< PASS >::process(), and ffft::FFTRealPassInverse< PASS >::process_internal()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
