.TH "ffft::FFTRealFixLenParam" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ffft::FFTRealFixLenParam \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FFTRealFixLenParam\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBTRIGO_BD_LIMIT\fP = 12 }"
.br
.ti -1c
.RI "typedef float \fBDataType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file FFTRealFixLenParam\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef float \fBffft::FFTRealFixLenParam::DataType\fP"

.PP
Definition at line 47 of file FFTRealFixLenParam\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITRIGO_BD_LIMIT \fP\fP
.PP
Definition at line 45 of file FFTRealFixLenParam\&.h\&.
.PP
.nf
45 {         TRIGO_BD_LIMIT    = 12  };
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
