.TH "FFTRealPassDirect.hpp" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FFTRealPassDirect.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'FFTRealUseTrigo\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBffft\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBffft_FFTRealPassDirect_CURRENT_CODEHEADER\fP"
.br
.ti -1c
.RI "#define \fBffft_FFTRealPassDirect_CODEHEADER_INCLUDED\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ffft_FFTRealPassDirect_CODEHEADER_INCLUDED"

.PP
Definition at line 24 of file FFTRealPassDirect\&.hpp\&.
.SS "#define ffft_FFTRealPassDirect_CURRENT_CODEHEADER"

.PP
Definition at line 21 of file FFTRealPassDirect\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
