.TH "FFTRealFixLen.hpp" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FFTRealFixLen.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'def\&.h'\fP
.br
\fC#include 'FFTRealPassDirect\&.h'\fP
.br
\fC#include 'FFTRealPassInverse\&.h'\fP
.br
\fC#include 'FFTRealSelect\&.h'\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBstd\fP"
.br
.ti -1c
.RI " \fBffft\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBffft_FFTRealFixLen_CURRENT_CODEHEADER\fP"
.br
.ti -1c
.RI "#define \fBffft_FFTRealFixLen_CODEHEADER_INCLUDED\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ffft_FFTRealFixLen_CODEHEADER_INCLUDED"

.PP
Definition at line 24 of file FFTRealFixLen\&.hpp\&.
.SS "#define ffft_FFTRealFixLen_CURRENT_CODEHEADER"

.PP
Definition at line 21 of file FFTRealFixLen\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
