.TH "FFTRealSelect.hpp" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FFTRealSelect.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBffft\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBffft_FFTRealSelect_CURRENT_CODEHEADER\fP"
.br
.ti -1c
.RI "#define \fBffft_FFTRealSelect_CODEHEADER_INCLUDED\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ffft_FFTRealSelect_CODEHEADER_INCLUDED"

.PP
Definition at line 24 of file FFTRealSelect\&.hpp\&.
.SS "#define ffft_FFTRealSelect_CURRENT_CODEHEADER"

.PP
Definition at line 21 of file FFTRealSelect\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
