.TH "mainwindow.h" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainwindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QtGlobal>\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include <QtSerialPort/QSerialPort>\fP
.br
\fC#include <QStringListModel>\fP
.br
\fC#include <QTreeWidgetItem>\fP
.br
\fC#include 'typedef\&.h'\fP
.br
\fC#include 'emu_data_editor\&.h'\fP
.br
\fC#include 'storage_structure\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPRESSURE_DATA_INDEX\fP   104"
.br
.ti -1c
.RI "#define \fBDATA_END_INDEX\fP   204"
.br
.ti -1c
.RI "#define \fBDATA_SIZE\fP   100"
.br
.ti -1c
.RI "#define \fBRESOLUTION_MAPING_FACTOR\fP   (5\&.0/255\&.0)"
.br
.ti -1c
.RI "#define \fBDEFAULT_DIR\fP   '\&.\&./DEFAULT_DIR/'"
.br
.ti -1c
.RI "#define \fBEVENT_RECORD_FILE\fP   'event_records\&.txt'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DATA_END_INDEX   204"

.PP
Definition at line 17 of file mainwindow\&.h\&.
.SS "#define DATA_SIZE   100"

.PP
Definition at line 18 of file mainwindow\&.h\&.
.SS "#define DEFAULT_DIR   '\&.\&./DEFAULT_DIR/'"

.PP
Definition at line 20 of file mainwindow\&.h\&.
.PP
Referenced by MainWindow::MainWindow()\&.
.SS "#define EVENT_RECORD_FILE   'event_records\&.txt'"

.PP
Definition at line 21 of file mainwindow\&.h\&.
.SS "#define PRESSURE_DATA_INDEX   104"

.PP
Definition at line 16 of file mainwindow\&.h\&.
.SS "#define RESOLUTION_MAPING_FACTOR   (5\&.0/255\&.0)"

.PP
Definition at line 19 of file mainwindow\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
