MainWindow
NAME
MainWindow -
SYNOPSIS
#include <mainwindow.h>
Inherits QMainWindow.
Public Slots
void data_open (bool checked)
void srv_cmds_data_download_msg_handler (QString data)
void srv_cmds_data_transfer_msg_handler (QString data)
void srv_cmds_general_msg_handler (QString data)
Signals
void response_ready (QString)
Public Member Functions
MainWindow (QWidget *parent=0)
~MainWindow ()
void msg (Uint16 type, QString msg)
QString uint8_to_str (Uint8 val)
void ListFiles ()
qint8 make8 (QString buf, Uint16 idx)
qint16 make16 (QString buf, Uint16 idx)
Uint16 crc16 (Uint8 *puchMsg, Uint16 usDataLen)
void set_emu_data (emu_data_editor *editor, Uint16 *data, Uint16 size)
QString save_to_file (QString dir, QString type, Uint16 offset, QVector< double > *data1, QVector< double > *data2=NULL, QVector< double > *data3=NULL)
Public Attributes
QString eventRecoredList
QString dir_default
Protected Slots
bool eventFilter (QObject *object, QEvent *event)
Detailed Description
Definition at line 34 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (QWidget *parent = 0) [explicit]
Definition at line 24 of file mainwindow.cpp.
References Ui_MainWindow::actionClear, Ui_MainWindow::actionConfigure, Ui_MainWindow::actionConnect, Ui_MainWindow::actionDisconnect, Ui_MainWindow::actionQuit, Ui_MainWindow::centralWidget, DEFAULT_DIR, dir_default, Ui_MainWindow::dock_central, Ui_MainWindow::dockWidget, serial_msg_t::listener_slot, serial_msg_t::processed, and Ui_MainWindow::setupUi().
                                      :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);
    this->move(QApplication::desktop()->rect().x() + 10,this->y()+2);
        console = new Console;
        console->setEnabled(false);
        serial = new QSerialPort(this);
        settings = new SettingsDialog;
          ui->actionConnect->setEnabled(true);
          ui->actionDisconnect->setEnabled(false);
          ui->actionQuit->setEnabled(true);
          ui->actionConfigure->setEnabled(true);
          initActionsConnections();
            connect(serial, SIGNAL(error(QSerialPort::SerialPortError)), this,
            SLOT(handleError(QSerialPort::SerialPortError)));
            connect(serial, SIGNAL(readyRead()), this, SLOT(incoming_data_listener()));
           ui->dockWidget->setVisible(false);
           ui->centralWidget->setVisible(false);
           ui->actionClear->setVisible(false);
          this->addDockWidget(Qt::RightDockWidgetArea,ui->dock_central);
          last_cmd.listener_slot = NULL;
          //serial rc buffer start frash
          last_cmd.processed=true;
          rc_buffer.clear();
          cmd_line_separator="\n>> ";
          dir_default = DEFAULT_DIR;
          QDir dir;
          if(!dir.exists(dir.toNativeSeparators(dir_default)))
              dir.mkdir(dir.toNativeSeparators(dir_default));
          map_keys();
          installEventFilter(this);
}
MainWindow::~MainWindow ()
Definition at line 94 of file mainwindow.cpp.
{
    delete ui;
}
Member Function Documentation
Uint16 MainWindow::crc16 (Uint8 *puchMsg, Uint16usDataLen)
Definition at line 298 of file srv_serial.cpp.
{
    Uint8 crc_hi = 0xFF ; /* high byte of CRC initialized */
    Uint8 crc_lo = 0xFF ; /* low byte of CRC initialized */
    Uint16 table_index ; /* index into CRC lookup table */
    while (usDataLen--)
    {
        table_index = crc_hi ^ *puchMsg++ ; /* calculate the CRC */
        crc_hi = crc_lo ^ table_crc_hi[table_index] ;
        crc_lo = table_crc_lo[table_index] ;
    }
    return (crc_hi << 8 | crc_lo) ;
}
void MainWindow::data_open (boolchecked) [slot]
Definition at line 450 of file srv_commands.cpp.
                                      {
    for (int var = 0; var < multi_cmds.length(); ++var)
        if(multi_cmds[var].gui.btn->isChecked())
            loadFile(multi_cmds[var].data_file_name);
    for (int var = 0; var < multi_cmds.length(); ++var)
        multi_cmds[var].gui.btn->setChecked(false);
}
bool MainWindow::eventFilter (QObject *object, QEvent *event) [protected], [slot]
Definition at line 100 of file mainwindow.cpp.
References Ui_MainWindow::dockWidget_sen_cmd.
{
    if (event->type() == QEvent::FocusOut)
    {
        if (object == this)
        {
        }
    }
    if (event->type() == QEvent::FocusIn)
    {
        if (object == ui->dockWidget_sen_cmd)
        {
        }
    }
    return false;
}
void MainWindow::ListFiles ()
Definition at line 308 of file mainwindow.cpp.
References dir_default, msg(), and MSG_ERROR.
                          {
    QStringList nameFilter("*.csv");
    QDir directory;
    directory.setPath(directory.toNativeSeparators(dir_default));
    if(!directory.exists()){
        if(!directory.mkdir(directory.toNativeSeparators(dir_default))){
            msg(MSG_ERROR,"Couldn't open the Directory " + directory.absolutePath() + "for reading");
        return;
        }
    }
    QStringList eventFiles = directory.entryList(nameFilter);
    model->setStringList(eventFiles);
}
Int16 MainWindow::make16 (QStringbuf, Uint16idx)
Definition at line 13 of file srv_miscellaneous.cpp.
References HEX2VAL.
{
    qint16 result = ((HEX2VAL((qint16)buf[idx+0].toLatin1())<<12)|
            (HEX2VAL((qint16)buf[idx+1].toLatin1())<<8)|
            (HEX2VAL((qint16)buf[idx+2].toLatin1())<<4)|
            (HEX2VAL((qint16)buf[idx+3].toLatin1())<<0));
    return result;
}
Int8 MainWindow::make8 (QStringbuf, Uint16idx)
Definition at line 5 of file srv_miscellaneous.cpp.
References HEX2VAL.
{
    qint8 result;
    result = ((HEX2VAL((qint8)buf[idx+0].toLatin1())<<4)|(HEX2VAL((qint8)buf[idx+1].toLatin1()))<<0);
    return result;
}
void MainWindow::msg (Uint16type, QStringmsg)
Definition at line 145 of file mainwindow.cpp.
References MSG_ERROR, and MSG_INFO.
Referenced by ListFiles(), and set_emu_data().
{
    QString title;
    QMessageBox msgBox;
    msgBox.setWindowIcon(QMainWindow::windowIcon());
    msgBox.setWindowTitle(QMainWindow::windowTitle());
    switch (type) {
    case MSG_ERROR:
        msgBox.setText(tr("Error"));
        msgBox.setIcon(QMessageBox::Critical);
        break;
    case MSG_INFO:
        msgBox.setText(tr("Information"));
        msgBox.setIcon(QMessageBox::Information);
    default:
        break;
    }
 msgBox.setInformativeText(msg);
 msgBox.exec();
}
void MainWindow::response_ready (QString_t1) [signal]
Definition at line 289 of file moc_mainwindow.cpp.
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 0, _a);
}
QString MainWindow::save_to_file (QStringdir, QStringtype, Uint16offset, QVector< double > *data1, QVector< double > *data2 = NULL, QVector< double > *data3 = NULL)
Definition at line 706 of file mainwindow.cpp.
References PRE_ACT_RECORD_BUFF_SIZE.
{
    bool disturbance_record = (data1->length() == PRE_ACT_RECORD_BUFF_SIZE)?false:true;
    QString file_name = type;
    file_name.replace(':',"-").replace(' ',"_").replace(',',"").replace('.',"_");
    file_name = dir + file_name + ".csv";
    if (file_name.isEmpty()) return NULL;
    else {
        QFile file(file_name);
        if (!file.open(QIODevice::WriteOnly)) {
            QMessageBox::information(this, tr("Unable to open file"), file.errorString());
            return NULL;
        }
        QTextStream stream(&file);
        stream << "Title,"+type+"\n";
        stream << "Record length,"+QString::number(data1->length())+"\n";
        if(disturbance_record){
        stream << "Event offset,"+QString::number(offset)+"\n";
        stream << "TIME, MEASURED DATA,EVENT_AMP,EVENT_DFDT\n";
        }else
        stream << "TIME, DATA\n";
        for(int ii=0;ii< data1->length();ii++)
           stream << QString::number(ii) +","+QString::number(data1->value(ii))
                     +
                     ((disturbance_record)?(
                     ","+ QString::number(data2->value(ii))
                     + ","+ QString::number(data3->value(ii))
                     ):"")
                     +"\n";
        file.flush();
     }
    return file_name;
}
void MainWindow::set_emu_data (emu_data_editor *editor, Uint16 *data, Uint16size)
Definition at line 606 of file srv_commands.cpp.
References ACTIVE, Ui_MainWindow::btn_set_emu_data, Ui_MainWindow::dockWidget_sen_cmd, msg(), and MSG_INFO.
{
    if(editor != this->emu_data_buffer.current_editor){
      msg(MSG_INFO,
          QString("The selected editor is not valid.")+
          QString("\nYou must save the data to a file" )+
          QString(" to open it again with a new editor"));
        return;//this is zambi editor
    }
    memmove(this->emu_data_buffer.data,data,size);
    this->emu_data_buffer.processed = false;
    this->emu_data_buffer.valid = false;
    this->emu_data_buffer.current_editor = editor;
    ui->btn_set_emu_data->setStyleSheet(ACTIVE);
    ui->btn_set_emu_data->setText("Edit Data");
    this->show();
    this->raise();
    this->activateWindow();
    ui->dockWidget_sen_cmd->setWindowFlags(Qt::Window);
    ui->dockWidget_sen_cmd->show();
    ui->dockWidget_sen_cmd->raise();
    ui->dockWidget_sen_cmd->activateWindow();
}
void MainWindow::srv_cmds_data_download_msg_handler (QStringdata) [slot]
TODO: clean up procedure
TODO: clean up procedure
Definition at line 588 of file srv_protocol.cpp.
References serial_msg_t::arg, serial_msg_t::data_download, MAX_ATTACHMENT_LENGTH, serial_msg_t::multi_address, PBAR_FAILURE, serial_msg_t::processed, Ui_MainWindow::terminal, and serial_msg_t::vPos.
                                                               {
    
    uint channel = 0;
    uint sensor_id = 0;
    uint arg = 0;
    uint copied_data_length = 0;
    char attachment[2*MAX_ATTACHMENT_LENGTH];
    memset(attachment,0,sizeof(attachment));
        if(data.contains("#Error"))
        {
             bool repeat = true;
             QString result = QString("\n#Error: data verification error \n ");
             ui->terminal->textCursor().insertText(result+"\n"+data);
             QString Question =
                     QString("The response from the selected sensor (SEN address = ")
                     +QString::number(last_cmd.arg[1])
                     +QString(") contains error .\n")
                     +QString("Do you want to run the command again ?");
             QMessageBox msgBox;
             msgBox.setWindowIcon(QMainWindow::windowIcon());
             msgBox.setWindowTitle(QMainWindow::windowTitle());
             msgBox.setText(Question);
             msgBox.setStandardButtons(QMessageBox::Yes|QMessageBox::No);
             if(msgBox.exec() == QMessageBox::No)
                      repeat = false;
                 if(last_cmd.multi_address){
                     if(!repeat){
                     last_cmd.processed = true;
                     multi_cmds[last_cmd.vPos].varified = true;
                     multi_cmds[last_cmd.vPos].gui.pBar->setStyleSheet(PBAR_FAILURE);
                     
                     last_cmd.arg[2]=0;//reset offset to zero for new data transmission
                       
                     last_cmd.data_download.total_size.copied = 0;
                     
                     last_cmd.data_download.offset = 0;
                     
                     last_cmd.arg[3]
                             = ((MAX_ATTACHMENT_LENGTH-(last_cmd.data_download.total_size.expected))<0)?
                                 MAX_ATTACHMENT_LENGTH:last_cmd.data_download.total_size.expected;
                     
                     if((last_cmd.vPos < (multi_cmds.length() - 1)))
                         last_cmd.vPos++;
                     else{
                         return;
                      }
                     }
                     last_cmd.arg[1] = multi_cmds[last_cmd.vPos].address;
                     multi_cmds[last_cmd.vPos].gui.pBar->setValue(20);
                     srv_cmds_execute(last_cmd/*now current cmd*/);
                 }else{
                     if(repeat){
                        //simply repeat the previous command
                        srv_cmds_execute(last_cmd/*now current cmd*/);
                        return;
                     }
                     last_cmd.processed = true;
                 }
            return;
         }
        if((data.length() == 8) && sscanf(data.toLatin1(),"%02X%02X%04X",&channel,&sensor_id,&arg) == 3)
        {
            srv_cmds_general_msg_handler(data);
            return;
        }
       
        
        if(sscanf(data.toLatin1(),"%02X%02X%04X%04X%s",&channel,&sensor_id,&arg,&copied_data_length,attachment) == 5)
        {
            //TODO:
           /*
           if(copied_data_length != sizeof(attachment)){
               retransmission("#Error: Received data validation ");
               return;
           }*/
           if(arg == ACK){
               if(copied_data_length-last_cmd.data_download.offset == last_cmd.arg[3]/*requested data length*/)
               {
               if(msg_to_mem(
                      attachment,
                      (((Uint8 *)last_cmd.data_download.storage_location)+last_cmd.data_download.offset),
                      last_cmd.arg[3]
                          )){
                   last_cmd.data_download.total_size.copied = copied_data_length;
                  }else
                  if(last_cmd.data_download.total_size.copied+last_cmd.arg[3] != copied_data_length){
                    Failure();
                  }else{
                   
                   qCritical() <<"Unable to copy received data to memory "
                               <<"in MainWindow::srv_cmds_data_download_msg_handler";
                
                   exit(1);
                   
                  }
               }else{
                   
                  retransmission("#Error: Received data validation ");
                  return;
               }
               
               if(copied_data_length == last_cmd.data_download.total_size.expected){
                   last_cmd.processed = true;
                   QString result = QString("Command execution verified\n");
                   ui->terminal->textCursor().insertText(result);
                   
                   record_preview(last_cmd);
                   
                   if(last_cmd.multi_address){
                        multi_cmds[last_cmd.vPos].gui.pBar->setValue(100);
                        multi_cmds[last_cmd.vPos].varified = true;
                    if(last_cmd.vPos < (multi_cmds.length()-1)){
                       last_cmd.vPos++;
                       last_cmd.arg[1] = multi_cmds[last_cmd.vPos].address;
                       last_cmd.arg[2] = 0;//data transfer starts fresh
                       
                       last_cmd.data_download.total_size.copied = 0;
                       
                       last_cmd.data_download.offset = 0;
                       
                       last_cmd.arg[3]
                               = ((MAX_ATTACHMENT_LENGTH-(last_cmd.data_download.total_size.expected))<0)?
                                   MAX_ATTACHMENT_LENGTH:last_cmd.data_download.total_size.expected;
                       srv_cmds_execute(last_cmd/*now current cmd*/);
                   }else
                       ui->btn_execute_cmd->setEnabled(true);
                   }
               }else if(copied_data_length < last_cmd.data_download.total_size.expected){
                   Uint16 remaining_data_length
                           = last_cmd.data_download.total_size.expected
                           - last_cmd.data_download.total_size.copied;
                   last_cmd.data_download.offset = last_cmd.data_download.total_size.copied;
                   last_cmd.arg[2] = last_cmd.data_download.offset; //sets current offset
                   last_cmd.arg[3] = ((MAX_ATTACHMENT_LENGTH-remaining_data_length)<0)?
                                          MAX_ATTACHMENT_LENGTH:remaining_data_length;
                   srv_cmds_execute(last_cmd/*now current cmd*/);
               }else{
                   
                   qWarning() <<"Unexpected result, considered as data transfer error"
                              <<"in MainWindow::srv_cmds_data_transfer_msg_handler";
                   
                   
                   retransmission("#Error: Received data validation");
                   return;
               }
           }else{
               qWarning() <<"Unexpected argument received, considered as data transfer error"
                          <<"in MainWindow::srv_cmds_data_transfer_msg_handler";
               
               
               retransmission("#Error: Received data validation");
               return;
           }
         }
    
}
void MainWindow::srv_cmds_data_transfer_msg_handler (QStringdata) [slot]
TODO: clean up procedure
Definition at line 437 of file srv_protocol.cpp.
References serial_msg_t::arg, serial_msg_t::attachment_length, MAX_ATTACHMENT_LENGTH, serial_msg_t::multi_address, PBAR_FAILURE, serial_msg_t::processed, Ui_MainWindow::terminal, and serial_msg_t::vPos.
                                                               {
    unsigned int channel = 0;
    unsigned int sensor_id = 0;
    unsigned int arg = 0;
    unsigned int copied_data_length = 0;
        if(data.contains("#Error"))
        {
             bool repeat = true;
             QString result = QString("\n#Error: data verification error \n ");
             ui->terminal->textCursor().insertText(result+"\n"+data);
             QString Question =
                     QString("The response from the selected sensor (SEN address = ")
                     +QString::number(last_cmd.arg[1])
                     +QString(") contains error .\n")
                     +QString("Do you want to run the command again ?");
             QMessageBox msgBox;
             msgBox.setWindowIcon(QMainWindow::windowIcon());
             msgBox.setWindowTitle(QMainWindow::windowTitle());
             msgBox.setText(Question);
             msgBox.setStandardButtons(QMessageBox::Yes|QMessageBox::No);
             if(msgBox.exec() == QMessageBox::No)
                      repeat = false;
                 if(last_cmd.multi_address){
                     if(!repeat){
                     last_cmd.processed = true;
                     multi_cmds[last_cmd.vPos].varified = true;
                     multi_cmds[last_cmd.vPos].gui.pBar->setStyleSheet(PBAR_FAILURE);
                     last_cmd.arg[2]=0;//reset offset to zero for new data transmission
                     last_cmd.arg[3]= ((MAX_ATTACHMENT_LENGTH-(last_cmd.attachment_length))<0)?
                                          MAX_ATTACHMENT_LENGTH:last_cmd.attachment_length;
                     if((last_cmd.vPos < (multi_cmds.length() - 1)))
                         last_cmd.vPos++;
                     else{
                         return;
                      }
                     }
                     last_cmd.arg[1] = multi_cmds[last_cmd.vPos].address;
                     multi_cmds[last_cmd.vPos].gui.pBar->setValue(20);
                     srv_cmds_execute(last_cmd/*now current cmd*/);
                 }else{
                     if(repeat){
                        //simply repeat the previous command
                        srv_cmds_execute(last_cmd/*now current cmd*/);
                        return;
                     }
                     last_cmd.processed = true;
                 }
            return;
         }
        if(data.length() == 8 && sscanf(data.toLatin1(),"%02X%02X%04X",&channel,&sensor_id,&arg) == 3)
        {
            srv_cmds_general_msg_handler(data);
            return;
        }
        if(sscanf(data.toLatin1(),"%02X%02X%04X%04X",&channel,&sensor_id,&arg,&copied_data_length) == 4)
        {
           if(arg == ACK){
               if(copied_data_length == last_cmd.attachment_length){
                   last_cmd.processed = true;
                   QString result = QString("Command execution verified\n");
                   ui->terminal->textCursor().insertText(result);
                   if(last_cmd.multi_address){
                        multi_cmds[last_cmd.vPos].gui.pBar->setValue(100);
                        multi_cmds[last_cmd.vPos].varified = true;
                    if(last_cmd.vPos < (multi_cmds.length()-1)){
                       last_cmd.vPos++;
                       last_cmd.arg[1] = multi_cmds[last_cmd.vPos].address;
                       last_cmd.arg[2] = 0;//data transfer starts fresh
                       last_cmd.arg[3]= ((MAX_ATTACHMENT_LENGTH-(last_cmd.attachment_length))<0)?
                                          MAX_ATTACHMENT_LENGTH:last_cmd.attachment_length;
                       srv_cmds_execute(last_cmd/*now current cmd*/);
                   }else
                       ui->btn_execute_cmd->setEnabled(true);
                   }
               }else if(copied_data_length < last_cmd.attachment_length){
                   Uint16 remaining_data_length = last_cmd.attachment_length - copied_data_length;
                   QString result = QString("data transfer verification\n");
                   ui->terminal->textCursor().insertText(result);
                   result = QString("Copied data length :"+QString::number(copied_data_length)+" byte\n");
                   ui->terminal->textCursor().insertText(result);
                   result = QString("Remaining data length "+QString::number(remaining_data_length)+" byte\n");
                   ui->terminal->textCursor().insertText(result);
                   //TODO: check copid data length is valid (very important)
                   last_cmd.arg[2] = copied_data_length; //sets current offset
                   last_cmd.arg[3] = ((MAX_ATTACHMENT_LENGTH-remaining_data_length)<0)?
                                          MAX_ATTACHMENT_LENGTH:remaining_data_length;
                   srv_cmds_execute(last_cmd/*now current cmd*/);
               }else{
                   qWarning() <<"Unexpected result, considered as data transfer error"
                              <<"in MainWindow::srv_cmds_data_transfer_msg_handler";
               }
           }else{
               qWarning() <<"Unexpected argument received, considered as data transfer error"
                          <<"in MainWindow::srv_cmds_data_transfer_msg_handler";
           }
         }
}
void MainWindow::srv_cmds_general_msg_handler (QStringdata) [slot]
Definition at line 293 of file srv_protocol.cpp.
References serial_msg_t::arg, serial_msg_t::multi_address, PBAR_FAILURE, serial_msg_t::processed, Ui_MainWindow::terminal, and serial_msg_t::vPos.
                                                         {
uint channel = 0;
uint sensor_id = 0;
uint arg = 0;
    if(data.contains("#Error"))
    {
         QString result = QString("\n#Error: data verification error \n ");
         ui->terminal->textCursor().insertText(result+"\n"+data);
             if(last_cmd.multi_address){
                 QString Question =
                         QString("The response from the selected sensor (SEN address = ")
                         +QString::number(last_cmd.arg[1])
                         +QString(") contains error .\n")
                         +QString("Do you want to run the command again ?");
                 QMessageBox msgBox;
                 msgBox.setWindowIcon(QMainWindow::windowIcon());
                 msgBox.setWindowTitle(QMainWindow::windowTitle());
                 msgBox.setText(Question);
                 msgBox.setStandardButtons(QMessageBox::Yes|QMessageBox::No);
                 if(msgBox.exec() == QMessageBox::No){
                 last_cmd.processed = true;
                 multi_cmds[last_cmd.vPos].varified = true;
                 multi_cmds[last_cmd.vPos].gui.pBar->setStyleSheet(PBAR_FAILURE);
                 if((last_cmd.vPos < (multi_cmds.length() - 1)))
                     last_cmd.vPos++;
                 else{
                     return;
                  }
                 }
                 last_cmd.arg[1] = multi_cmds[last_cmd.vPos].address;
                 multi_cmds[last_cmd.vPos].gui.pBar->setValue(20);
                 srv_cmds_execute(last_cmd/*now current cmd*/);
             }else{
                 last_cmd.processed = true;
             }
             return;
     }
    if(sscanf(data.toLatin1(),"%02X%02X%04X",&channel,&sensor_id,&arg) == 3){
       if(arg == ACK){
                    last_cmd.processed = true;
                    QString result = QString("Command execution verified\n");
                    ui->terminal->textCursor().insertText(result);
                    if(last_cmd.multi_address){
                         multi_cmds[last_cmd.vPos].gui.pBar->setValue(100);
                         multi_cmds[last_cmd.vPos].varified = true;
                     if(last_cmd.vPos < (multi_cmds.length()-1)){
                        last_cmd.vPos++;
                        last_cmd.arg[1] = multi_cmds[last_cmd.vPos].address;
                        srv_cmds_execute(last_cmd/*now current cmd*/);
                    }else
                        ui->btn_execute_cmd->setEnabled(true);
                    }
       }
       else if(arg == ARG_PROCESSING_CMD_WAIT_MSG)
       {
                QString result = QString("Processing command, Please Wait ...\n ");
                ui->terminal->textCursor().insertText(result);
       }
       if(arg == ARG_SEN_COMM_ERROR_NO_RESPONSE)
       {
            QString result = QString("#Communication Error, Sensor not responding\n ");
            ui->terminal->textCursor().insertText(result);
                if(last_cmd.multi_address){
                    QString Question =
                            QString("Communication error, the selected sensor (SEN address = ")
                            +QString::number(multi_cmds[last_cmd.vPos].address)
                            +QString(") is not responding.\n")
                            +QString("Do you want to try again ?");
                    QMessageBox msgBox;
                    msgBox.setWindowIcon(QMainWindow::windowIcon());
                    msgBox.setWindowTitle(QMainWindow::windowTitle());
                    msgBox.setText(Question);
                    msgBox.setStandardButtons(QMessageBox::Yes|QMessageBox::No);
                    if(msgBox.exec() == QMessageBox::No){
                    last_cmd.processed = true;
                    multi_cmds[last_cmd.vPos].varified = true;
                    multi_cmds[last_cmd.vPos].gui.pBar->setStyleSheet(PBAR_FAILURE);
                    if((last_cmd.vPos < (multi_cmds.length() - 1)))
                        last_cmd.vPos++;
                    else{
                        return;
                     }
                    }
                    last_cmd.arg[1] = multi_cmds[last_cmd.vPos].address;
                    multi_cmds[last_cmd.vPos].gui.pBar->setValue(20);
                    srv_cmds_execute(last_cmd/*now current cmd*/);
                }else{
                    last_cmd.processed = true;
                }
        }
     }
}
QString MainWindow::uint8_to_str (Uint8val)
Definition at line 174 of file mainwindow.cpp.
{
    const char cnv[] = "0123456789ABCDEF";
    return QString(cnv[(val>>4)&0x0F]) + QString(cnv[(val>>0)&0x0F]);
}
Member Data Documentation
QString MainWindow::dir_default
Definition at line 63 of file mainwindow.h.
Referenced by ListFiles(), and MainWindow().
QString MainWindow::eventRecoredList
Definition at line 61 of file mainwindow.h.
Author
Generated automatically by Doxygen for AQ0X from the source code.