.TH "moc_mainwindow.cpp" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moc_mainwindow.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./mainwindow\&.h'\fP
.br
\fC#include <QtCore/qbytearray\&.h>\fP
.br
\fC#include <QtCore/qmetatype\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBqt_meta_stringdata_MainWindow_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQT_MOC_LITERAL\fP(idx, ofs, len)"
.br
.in -1c
.SH "Class Documentation"
.PP 
.SH "struct qt_meta_stringdata_MainWindow_t"
.PP 
Definition at line 21 of file moc_mainwindow\&.cpp\&.
.PP
\fBClass Members:\fP
.RS 4
QByteArrayData \fIdata[44]\fP 
.br
.PP
char \fIstringdata[937]\fP 
.br
.PP
.RE
.PP
.SH "Macro Definition Documentation"
.PP 
.SS "#define QT_MOC_LITERAL(idx, ofs, len)"
\fBValue:\fP
.PP
.nf
Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_MainWindow_t, stringdata) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
.fi
.PP
Definition at line 25 of file moc_mainwindow\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
