.TH "OscSinCos.h" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OscSinCos.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'def\&.h'\fP
.br
\fC#include 'OscSinCos\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBffft::OscSinCos< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBffft\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
