.TH "qcomplexnumber.h" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qcomplexnumber.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQComplexNumber< T >\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBQComplexNumber\fP< float > \fBQComplexFloat\fP"
.br
.ti -1c
.RI "typedef \fBQComplexNumber\fP< double > \fBQComplexDouble\fP"
.br
.ti -1c
.RI "typedef \fBQComplexNumber\fP< int > \fBQComplexInteger\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBQComplexNumber\fP<double> \fBQComplexDouble\fP"

.PP
Definition at line 78 of file qcomplexnumber\&.h\&.
.SS "typedef \fBQComplexNumber\fP<float> \fBQComplexFloat\fP"

.PP
Definition at line 77 of file qcomplexnumber\&.h\&.
.SS "typedef \fBQComplexNumber\fP<int> \fBQComplexInteger\fP"

.PP
Definition at line 79 of file qcomplexnumber\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
