QComplexNumber< T >
NAME
QComplexNumber< T > -
SYNOPSIS
#include <qcomplexnumber.h>
Public Member Functions
QComplexNumber ()
QComplexNumber (T real, T imaginary)
void setReal (T real)
void setImaginary (T imaginary)
void set (T real, T imaginary)
void set (QComplexNumber complex)
T real ()
T imaginary ()
QComplexNumber< T > & operator+= (const QComplexNumber< T > &number)
QComplexNumber< T > & operator-= (const QComplexNumber< T > &number)
QComplexNumber< T > & operator/= (const QComplexNumber< T > &number)
QComplexNumber< T > & operator*= (const QComplexNumber< T > &number)
QComplexNumber< T > & operator/= (const T &value)
QComplexNumber< T > & operator*= (const T &value)
Detailed Description
template<typename T>class QComplexNumber< T >
Definition at line 46 of file qcomplexnumber.h.
Constructor & Destructor Documentation
template<typename T > QComplexNumber< T >::QComplexNumber ()
Definition at line 45 of file qcomplexnumber.cpp.
{
    mReal = 0;
    mImaginary = 0;
}
template<typename T > QComplexNumber< T >::QComplexNumber (Treal, Timaginary)
Definition at line 52 of file qcomplexnumber.cpp.
{
    mReal = real;
    mImaginary = imaginary;
}
Member Function Documentation
template<typename T > T QComplexNumber< T >::imaginary ()
Definition at line 91 of file qcomplexnumber.cpp.
Referenced by QComplexNumber< T >::set().
{
    return mImaginary;
}
template<typename T > QComplexNumber< T > & QComplexNumber< T >::operator*= (const QComplexNumber< T > &number)
Definition at line 121 of file qcomplexnumber.cpp.
{
    mReal *= number.mReal;
    mImaginary *= number.mImaginary;
    return *this;
}
template<typename T > QComplexNumber< T > & QComplexNumber< T >::operator*= (const T &value)
Definition at line 137 of file qcomplexnumber.cpp.
References value.
{
    mReal *= value;
    mImaginary *= value;
    return *this;
}
template<typename T > QComplexNumber< T > & QComplexNumber< T >::operator+= (const QComplexNumber< T > &number)
Definition at line 97 of file qcomplexnumber.cpp.
{
    mReal += number.mReal;
    mImaginary += number.mImaginary;
    return *this;
}
template<typename T > QComplexNumber< T > & QComplexNumber< T >::operator-= (const QComplexNumber< T > &number)
Definition at line 105 of file qcomplexnumber.cpp.
{
    mReal -= number.mReal;
    mImaginary -= number.mImaginary;
    return *this;
}
template<typename T > QComplexNumber< T > & QComplexNumber< T >::operator/= (const QComplexNumber< T > &number)
Definition at line 113 of file qcomplexnumber.cpp.
{
    mReal /= number.mReal;
    mImaginary /= number.mImaginary;
    return *this;
}
template<typename T > QComplexNumber< T > & QComplexNumber< T >::operator/= (const T &value)
Definition at line 129 of file qcomplexnumber.cpp.
References value.
{
    mReal /= value;
    mImaginary /= value;
    return *this;
}
template<typename T > T QComplexNumber< T >::real ()
Definition at line 85 of file qcomplexnumber.cpp.
Referenced by QComplexNumber< T >::set().
{
    return mReal;
}
template<typename T > void QComplexNumber< T >::set (Treal, Timaginary)
Definition at line 71 of file qcomplexnumber.cpp.
{
    mReal = real;
    mImaginary = imaginary;
}
template<typename T > void QComplexNumber< T >::set (QComplexNumber< T >complex)
Definition at line 78 of file qcomplexnumber.cpp.
References QComplexNumber< T >::imaginary(), and QComplexNumber< T >::real().
{
    mReal = complex.real();
    mImaginary = complex.imaginary();
}
template<typename T > void QComplexNumber< T >::setImaginary (Timaginary)
Definition at line 65 of file qcomplexnumber.cpp.
{
    mImaginary = imaginary;
}
template<typename T > void QComplexNumber< T >::setReal (Treal)
Definition at line 59 of file qcomplexnumber.cpp.
{
    mReal = real;
}
Author
Generated automatically by Doxygen for AQ0X from the source code.