.TH "QCP" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCP \- 
.PP
The \fBQCP\fP Namespace contains general enums and QFlags\&.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBScatterStyle\fP { \fBssNone\fP, \fBssDot\fP, \fBssCross\fP, \fBssPlus\fP, \fBssCircle\fP, \fBssDisc\fP, \fBssSquare\fP, \fBssDiamond\fP, \fBssStar\fP, \fBssTriangle\fP, \fBssTriangleInverted\fP, \fBssCrossSquare\fP, \fBssPlusSquare\fP, \fBssCrossCircle\fP, \fBssPlusCircle\fP, \fBssPeace\fP, \fBssPixmap\fP }"
.br
.RI "\fIDefines the symbol used for scatter points\&. \fP"
.ti -1c
.RI "enum \fBAntialiasedElement\fP { \fBaeAxes\fP = 0x0001, \fBaeGrid\fP = 0x0002, \fBaeSubGrid\fP = 0x0004, \fBaeLegend\fP = 0x0008, \fBaeLegendItems\fP = 0x0010, \fBaePlottables\fP = 0x0020, \fBaeItems\fP = 0x0040, \fBaeScatters\fP = 0x0080, \fBaeErrorBars\fP = 0x0100, \fBaeFills\fP = 0x0200, \fBaeZeroLine\fP = 0x0400, \fBaeAll\fP = 0xFFFF, \fBaeNone\fP = 0x0000 }"
.br
.RI "\fIDefines what elements of a plot can be forcibly drawn antialiased/not antialiased\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBQ_DECLARE_FLAGS\fP (AntialiasedElements, \fBAntialiasedElement\fP) enum PlottingHint"
.br
.RI "\fIDefines plotting hints that control various aspects of the quality and speed of plotting\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBQCP\fP Namespace contains general enums and QFlags\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBQCP::AntialiasedElement\fP"

.PP
Defines what elements of a plot can be forcibly drawn antialiased/not antialiased\&. If an element is neither forcibly drawn antialiased nor forcibly drawn not antialiased, it is up to the respective element how it is drawn\&. Typically it provides a \fIsetAntialiased\fP function for this\&.
.PP
\fCAntialiasedElements\fP is a flag of or-combined elements of this enum type\&.
.PP
\fBSee also:\fP
.RS 4
QCustomPlot::setAntialiasedElements, QCustomPlot::setNotAntialiasedElements 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIaeAxes \fP\fP
\fC0x0001\fP Axis base line and tick marks 
.TP
\fB\fIaeGrid \fP\fP
\fC0x0002\fP Grid lines 
.TP
\fB\fIaeSubGrid \fP\fP
\fC0x0004\fP Sub grid lines 
.TP
\fB\fIaeLegend \fP\fP
\fC0x0008\fP Legend box 
.TP
\fB\fIaeLegendItems \fP\fP
\fC0x0010\fP Legend items 
.TP
\fB\fIaePlottables \fP\fP
\fC0x0020\fP Main lines of plottables (excluding error bars, see element \fBaeErrorBars\fP) 
.TP
\fB\fIaeItems \fP\fP
\fC0x0040\fP Main lines of items 
.TP
\fB\fIaeScatters \fP\fP
\fC0x0080\fP Scatter symbols of plottables (excluding scatter symbols of type ssPixmap) 
.TP
\fB\fIaeErrorBars \fP\fP
\fC0x0100\fP Error bars 
.TP
\fB\fIaeFills \fP\fP
\fC0x0200\fP Borders of fills (e\&.g\&. under or between graphs) 
.TP
\fB\fIaeZeroLine \fP\fP
\fC0x0400\fP Zero-lines, see \fBQCPAxis::setZeroLinePen\fP 
.TP
\fB\fIaeAll \fP\fP
\fC0xFFFF\fP All elements 
.TP
\fB\fIaeNone \fP\fP
\fC0x0000\fP No elements 
.PP
Definition at line 108 of file qcustomplot\&.h\&.
.PP
.nf
108                         { aeAxes           = 0x0001 
109                           ,aeGrid          = 0x0002 
110                           ,aeSubGrid       = 0x0004 
111                           ,aeLegend        = 0x0008 
112                           ,aeLegendItems   = 0x0010 
113                           ,aePlottables    = 0x0020 
114                           ,aeItems         = 0x0040 
115                           ,aeScatters      = 0x0080 
116                           ,aeErrorBars     = 0x0100 
117                           ,aeFills         = 0x0200 
118                           ,aeZeroLine      = 0x0400 
119                           ,aeAll           = 0xFFFF 
120                           ,aeNone          = 0x0000 
121                         }; 
.fi
.SS "enum \fBQCP::ScatterStyle\fP"

.PP
Defines the symbol used for scatter points\&. On plottables/items that draw scatters, the sizes of these visualizations (with exception of \fBQCP::ssDot\fP and \fBQCP::ssPixmap\fP) can be controlled with a \fIsetScatterSize\fP function\&. Scatters are in general drawn with the main pen set on the plottable/item\&.
.PP
\fBSee also:\fP
.RS 4
\fBQCPGraph::setScatterStyle\fP, \fBQCPStatisticalBox::setOutlierStyle\fP 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIssNone \fP\fP
no scatter symbols are drawn (e\&.g\&. in \fBQCPGraph\fP, data only represented with lines) 
.TP
\fB\fIssDot \fP\fP
a single pixel 
.TP
\fB\fIssCross \fP\fP
a cross (x) 
.TP
\fB\fIssPlus \fP\fP
a plus (+) 
.TP
\fB\fIssCircle \fP\fP
a circle which is not filled 
.TP
\fB\fIssDisc \fP\fP
a circle which is filled with the color of the pen (not the brush!) 
.TP
\fB\fIssSquare \fP\fP
a square which is not filled 
.TP
\fB\fIssDiamond \fP\fP
a diamond which is not filled 
.TP
\fB\fIssStar \fP\fP
a star with eight arms, i\&.e\&. a combination of cross and plus 
.TP
\fB\fIssTriangle \fP\fP
an equilateral triangle which is not filled, standing on baseline 
.TP
\fB\fIssTriangleInverted \fP\fP
an equilateral triangle which is not filled, standing on corner 
.TP
\fB\fIssCrossSquare \fP\fP
a square which is not filled, with a cross inside 
.TP
\fB\fIssPlusSquare \fP\fP
a square which is not filled, with a plus inside 
.TP
\fB\fIssCrossCircle \fP\fP
a circle which is not filled, with a cross inside 
.TP
\fB\fIssPlusCircle \fP\fP
a circle which is not filled, with a plus inside 
.TP
\fB\fIssPeace \fP\fP
a circle which is not filled, with one vertical and two downward diagonal lines 
.TP
\fB\fIssPixmap \fP\fP
a custom pixmap specified by setScatterPixmap, centered on the data point coordinates 
.PP
Definition at line 79 of file qcustomplot\&.h\&.
.PP
.nf
79                   { ssNone       
80                     ,ssDot       
81                     ,ssCross     
82                     ,ssPlus      
83                     ,ssCircle    
84                     ,ssDisc      
85                     ,ssSquare    
86                     ,ssDiamond   
87                     ,ssStar      
88                     ,ssTriangle  
89                     ,ssTriangleInverted 
90                     ,ssCrossSquare      
91                     ,ssPlusSquare       
92                     ,ssCrossCircle      
93                     ,ssPlusCircle       
94                     ,ssPeace     
95                     ,ssPixmap    
96                   };
.fi
.SH "Function Documentation"
.PP 
.SS "QCP::Q_DECLARE_FLAGS (AntialiasedElements, AntialiasedElement)"

.PP
Defines plotting hints that control various aspects of the quality and speed of plotting\&. 
.PP
\fBSee also:\fP
.RS 4
QCustomPlot::setPlottingHints 
.RE
.PP
< \fC0x000\fP No hints are set
.PP
< \fC0x001\fP Graph/Curve lines are drawn with a faster method\&. This reduces the quality < especially of the line segment joins\&. (Only used for solid line pens\&.)
.PP
< \fC0x002\fP causes an immediate repaint() instead of a soft update() when QCustomPlot::replot() is called\&. This is set by default < on Windows-Systems to prevent the plot from freezing on fast consecutive replots (e\&.g\&. user drags ranges with mouse)\&. 
.PP
Definition at line 122 of file qcustomplot\&.h\&.
.PP
.nf
128                   { phNone            = 0x000 
129                     ,phFastPolylines  = 0x001 
130                     ,phForceRepaint   = 0x002 
132                   };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
