QCPAxis
NAME
QCPAxis -
Manages a single axis inside a QCustomPlot.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPLayerable.
Public Types
enum AxisType { atLeft, atRight, atTop, atBottom }
Defines at which side of the axis rect the axis will appear.
Public Slots
void setRange (const QCPRange &range)
Sets the range of the axis.
void setSelectable (const QCPAxis::SelectableParts &selectable)
Sets whether the user can (de-)select the parts in selectable by clicking on the QCustomPlot surface.
void setSelected (const QCPAxis::SelectableParts &selected)
Sets the selected state of the respective axis parts described by SelectablePart.
Signals
void ticksRequest ()
This signal is emitted when setAutoTicks is false and the axis is about to generate tick labels and replot itself.
void rangeChanged (const QCPRange &newRange)
This signal is emitted when the range of this axis has changed.
void selectionChanged (QCPAxis::SelectableParts selection)
This signal is emitted when the selection state of this axis has changed, either by user interaction or by a direct call to setSelected.
Public Member Functions
Q_ENUMS (AxisType) enum LabelType
When automatic tick label generation is enabled (setAutoTickLabels), defines how the numerical value (coordinate) of the tick position is translated into a string that will be drawn at the tick position.
Q_ENUMS (LabelType) enum ScaleType
Defines the scale of an axis.
Q_ENUMS (ScaleType) enum SelectablePart
Defines the selectable parts of an axis.
Q_ENUMS (SelectablePart) Q_DECLARE_FLAGS(SelectableParts
SelectablePart QCPAxis (QCustomPlot *parentPlot, AxisType type)
Constructs an Axis instance of Type type inside parentPlot.
virtual ~QCPAxis ()
AxisType axisType () const
QRect axisRect () const
ScaleType scaleType () const
double scaleLogBase () const
const QCPRange range () const
bool rangeReversed () const
bool antialiasedGrid () const
bool antialiasedSubGrid () const
bool antialiasedZeroLine () const
bool grid () const
bool subGrid () const
bool autoTicks () const
int autoTickCount () const
bool autoTickLabels () const
bool autoTickStep () const
bool autoSubTicks () const
bool ticks () const
bool tickLabels () const
int tickLabelPadding () const
LabelType tickLabelType () const
QFont tickLabelFont () const
QColor tickLabelColor () const
double tickLabelRotation () const
QString dateTimeFormat () const
QString numberFormat () const
int numberPrecision () const
double tickStep () const
QVector< double > tickVector () const
QVector< QString > tickVectorLabels () const
int tickLengthIn () const
int tickLengthOut () const
int subTickCount () const
int subTickLengthIn () const
int subTickLengthOut () const
QPen basePen () const
QPen gridPen () const
QPen subGridPen () const
QPen zeroLinePen () const
QPen tickPen () const
QPen subTickPen () const
QFont labelFont () const
QColor labelColor () const
QString label () const
int labelPadding () const
int padding () const
SelectableParts selected () const
SelectableParts selectable () const
QFont selectedTickLabelFont () const
QFont selectedLabelFont () const
QColor selectedTickLabelColor () const
QColor selectedLabelColor () const
QPen selectedBasePen () const
QPen selectedTickPen () const
QPen selectedSubTickPen () const
void setScaleType (ScaleType type)
Sets whether the axis uses a linear scale or a logarithmic scale.
void setScaleLogBase (double base)
If setScaleType is set to stLogarithmic, base will be the logarithm base of the scaling.
void setRange (double lower, double upper)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets the lower and upper bound of the axis range.
void setRange (double position, double size, Qt::AlignmentFlag alignment)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets the range of the axis.
void setRangeLower (double lower)
Sets the lower bound of the axis range, independently of the upper bound.
void setRangeUpper (double upper)
Sets the upper bound of the axis range, independently of the lower bound.
void setRangeReversed (bool reversed)
Sets whether the axis range (direction) is displayed reversed.
void setAntialiasedGrid (bool enabled)
Sets whether the grid of this axis is drawn antialiased or not.
void setAntialiasedSubGrid (bool enabled)
Sets whether the sub grid of this axis is drawn antialiased or not.
void setAntialiasedZeroLine (bool enabled)
Sets whether the zero line of this axis is drawn antialiased or not.
void setGrid (bool show)
Sets whether the grid lines are visible.
void setSubGrid (bool show)
Sets whether the sub grid lines are visible.
void setAutoTicks (bool on)
Sets whether the tick positions should be calculated automatically (either from an automatically generated tick step or a tick step provided manually via setTickStep, see setAutoTickStep).
void setAutoTickCount (int approximateCount)
When setAutoTickStep is true, approximateCount determines how many ticks should be generated in the visible range approximately.
void setAutoTickLabels (bool on)
Sets whether the tick labels are generated automatically depending on the tick label type (ltNumber or ltDateTime).
void setAutoTickStep (bool on)
Sets whether the tick step, i.e.
void setAutoSubTicks (bool on)
Sets whether the number of sub ticks in one tick interval is determined automatically.
void setTicks (bool show)
Sets whether tick marks are displayed.
void setTickLabels (bool show)
Sets whether tick labels are displayed.
void setTickLabelPadding (int padding)
Sets the distance between the axis base line (or any tick marks pointing outward) and the tick labels.
void setTickLabelType (LabelType type)
Sets whether the tick labels display numbers or dates/times.
void setTickLabelFont (const QFont &font)
Sets the font of the tick labels, i.e.
void setTickLabelColor (const QColor &color)
Sets the color of the tick labels, i.e.
void setTickLabelRotation (double degrees)
Sets the rotation of the tick labels, i.e.
void setDateTimeFormat (const QString &format)
Sets the format in which dates and times are displayed as tick labels, if setTickLabelType is ltDateTime.
void setNumberFormat (const QString &formatCode)
Sets the number format for the numbers drawn as tick labels (if tick label type is ltNumber).
void setNumberPrecision (int precision)
Sets the precision of the numbers drawn as tick labels.
void setTickStep (double step)
If setAutoTickStep is set to false, use this function to set the tick step manually.
void setTickVector (const QVector< double > &vec)
If you want full control over what ticks (and possibly labels) the axes show, this function is used to set the coordinates at which ticks will appear.
void setTickVectorLabels (const QVector< QString > &vec)
If you want full control over what ticks and labels the axes show, this function is used to set a number of QStrings that will be displayed at the tick positions which you need to provide with setTickVector.
void setTickLength (int inside, int outside=0)
Sets the length of the ticks in pixels.
void setSubTickCount (int count)
Sets the number of sub ticks in one (major) tick step.
void setSubTickLength (int inside, int outside=0)
Sets the length of the subticks in pixels.
void setBasePen (const QPen &pen)
Sets the pen, the axis base line is drawn with.
void setGridPen (const QPen &pen)
Sets the pen, grid lines are drawn with.
void setSubGridPen (const QPen &pen)
Sets the pen, the sub grid lines are drawn with.
void setZeroLinePen (const QPen &pen)
Sets the pen with which a single grid-like line will be drawn at value position zero.
void setTickPen (const QPen &pen)
Sets the pen, tick marks will be drawn with.
void setSubTickPen (const QPen &pen)
Sets the pen, subtick marks will be drawn with.
void setLabelFont (const QFont &font)
Sets the font of the axis label.
void setLabelColor (const QColor &color)
Sets the color of the axis label.
void setLabel (const QString &str)
Sets the axis label that will be shown below/above or next to the axis, depending on its orientation.
void setLabelPadding (int padding)
Sets the distance between the tick labels and the axis label.
void setPadding (int padding)
Sets the padding of the axis.
void setSelectedTickLabelFont (const QFont &font)
Sets the font that is used for tick labels when they are selected.
void setSelectedLabelFont (const QFont &font)
Sets the font that is used for the axis label when it is selected.
void setSelectedTickLabelColor (const QColor &color)
Sets the color that is used for tick labels when they are selected.
void setSelectedLabelColor (const QColor &color)
Sets the color that is used for the axis label when it is selected.
void setSelectedBasePen (const QPen &pen)
Sets the pen that is used to draw the axis base line when selected.
void setSelectedTickPen (const QPen &pen)
Sets the pen that is used to draw the (major) ticks when selected.
void setSelectedSubTickPen (const QPen &pen)
Sets the pen that is used to draw the subticks when selected.
Qt::Orientation orientation () const
Returns the orientation of the axis.
void moveRange (double diff)
If the scale type (setScaleType) is stLinear, diff is added to the lower and upper bounds of the range.
void scaleRange (double factor, double center)
Scales the range of this axis by factor around the coordinate center.
void setScaleRatio (const QCPAxis *otherAxis, double ratio=1.0)
Sets the range of this axis to have a certain scale ratio to otherAxis.
double pixelToCoord (double value) const
Transforms value (in pixel coordinates of the QCustomPlot widget) to axis coordinates.
double coordToPixel (double value) const
Transforms value (in coordinates of the axis) to pixel coordinates of the QCustomPlot widget.
SelectablePart selectTest (const QPointF &pos) const
Returns the part of the axis that is hit by pos (in pixels).
Protected Member Functions
void setAxisType (AxisType type)
void setAxisRect (const QRect &rect)
virtual void setupTickVectors ()
virtual void generateAutoTicks ()
virtual int calculateAutoSubTickCount (double tickStep) const
virtual int calculateMargin () const
virtual bool handleAxisSelection (QMouseEvent *event, bool additiveSelection, bool &modified)
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void draw (QCPPainter *painter)
virtual void drawTickLabel (QCPPainter *painter, double position, int distanceToAxis, const QString &text, QSize *tickLabelsSize)
virtual void getMaxTickLabelSize (const QFont &font, const QString &text, QSize *tickLabelsSize) const
void visibleTickBounds (int &lowIndex, int &highIndex) const
double baseLog (double value) const
double basePow (double value) const
QPen getBasePen () const
QPen getTickPen () const
QPen getSubTickPen () const
QFont getTickLabelFont () const
QFont getLabelFont () const
QColor getTickLabelColor () const
QColor getLabelColor () const
Protected Attributes
QVector< double > mTickVector
QVector< QString > mTickVectorLabels
QCPRange mRange
QString mDateTimeFormat
QString mLabel
QRect mAxisRect
QPen mBasePen
QPen mTickPen
QPen mSubTickPen
QFont mTickLabelFont
QFont mLabelFont
QColor mTickLabelColor
QColor mLabelColor
LabelType mTickLabelType
ScaleType mScaleType
AxisType mAxisType
double mTickStep
double mScaleLogBase
double mScaleLogBaseLogInv
int mSubTickCount
int mTickLengthIn
int mTickLengthOut
int mSubTickLengthIn
int mSubTickLengthOut
int mAutoTickCount
int mTickLabelPadding
int mLabelPadding
int mPadding
double mTickLabelRotation
bool mTicks
bool mTickLabels
bool mAutoTicks
bool mAutoTickLabels
bool mAutoTickStep
bool mAutoSubTicks
bool mRangeReversed
SelectableParts mSelectable
SelectableParts mSelected
QFont mSelectedTickLabelFont
QFont mSelectedLabelFont
QColor mSelectedTickLabelColor
QColor mSelectedLabelColor
QPen mSelectedBasePen
QPen mSelectedTickPen
QPen mSelectedSubTickPen
QRect mAxisSelectionBox
QRect mTickLabelsSelectionBox
QRect mLabelSelectionBox
QCPGrid * mGrid
QVector< double > mSubTickVector
QChar mExponentialChar
QChar mPositiveSignChar
int mNumberPrecision
char mNumberFormatChar
bool mNumberBeautifulPowers
bool mNumberMultiplyCross
Qt::Orientation mOrientation
int mLowestVisibleTick
int mHighestVisibleTick
Friends
class QCPGrid
Detailed Description
Manages a single axis inside a QCustomPlot.
Usually doesn't need to be instantiated externally. Access QCustomPlot's axes via QCustomPlot::xAxis (bottom), QCustomPlot::yAxis (left), QCustomPlot::xAxis2 (top) and QCustomPlot::yAxis2 (right).
Definition at line 1618 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPAxis::AxisType
Defines at which side of the axis rect the axis will appear. This also affects how the tick marks are drawn, on which side the labels are placed etc.
See also:
setAxisType
Enumerator
atLeft
Axis is vertical and on the left side of the axis rect of the parent QCustomPlot.
atRight
Axis is vertical and on the right side of the axis rect of the parent QCustomPlot.
atTop
Axis is horizontal and on the top side of the axis rect of the parent QCustomPlot.
atBottom
Axis is horizontal and on the bottom side of the axis rect of the parent QCustomPlot.
Definition at line 1661 of file qcustomplot.h.
                { atLeft
                  ,atRight
                  ,atTop
                  ,atBottom
                };
Constructor & Destructor Documentation
QCPAxis::QCPAxis (QCustomPlot *parentPlot, AxisTypetype) [explicit]
Constructs an Axis instance of Type type inside parentPlot.
Definition at line 3521 of file qcustomplot.cpp.
References atBottom, atLeft, atRight, atTop, labelFont(), mGrid, mHighestVisibleTick, mLowestVisibleTick, QCPGrid, QCPLayerable::setAntialiased(), setAutoSubTicks(), setAutoTickCount(), setAutoTickLabels(), setAutoTicks(), setAutoTickStep(), setAxisRect(), setAxisType(), setBasePen(), setDateTimeFormat(), setLabel(), setLabelColor(), setLabelFont(), setLabelPadding(), setNumberFormat(), setNumberPrecision(), setPadding(), setRange(), setRangeReversed(), setScaleLogBase(), setScaleType(), setSelectable(), setSelected(), setSelectedBasePen(), setSelectedLabelColor(), setSelectedLabelFont(), setSelectedSubTickPen(), setSelectedTickLabelColor(), setSelectedTickLabelFont(), setSelectedTickPen(), setSubTickCount(), setSubTickLength(), setSubTickPen(), setTickLabelColor(), setTickLabelFont(), setTickLabelPadding(), setTickLabelRotation(), setTickLabels(), setTickLabelType(), setTickLength(), setTickPen(), setTicks(), setTickStep(), and tickLabelFont().
                                                       :
  QCPLayerable(parentPlot)
{
  mLowestVisibleTick = 0;
  mHighestVisibleTick = -1;
  mGrid = new QCPGrid(this);
  setAxisType(type);
  setAxisRect(parentPlot->axisRect());
  setScaleType(stLinear);
  setScaleLogBase(10);
  
  setAntialiased(false);
  setRange(0, 5);
  setRangeReversed(false);
  
  setTicks(true);
  setTickStep(1);
  setAutoTickCount(6);
  setAutoTicks(true);
  setAutoTickLabels(true);
  setAutoTickStep(true);
  setTickLabelFont(parentPlot->font());
  setTickLabelColor(Qt::black);
  setTickLength(5);
  setTickPen(QPen(Qt::black, 0, Qt::SolidLine, Qt::SquareCap));
  setTickLabels(true);
  setTickLabelType(ltNumber);
  setTickLabelRotation(0);
  setDateTimeFormat("hh:mm:ss\ndd.MM.yy");
  setNumberFormat("gbd");
  setNumberPrecision(6);
  setLabel("");
  setLabelFont(parentPlot->font());
  setLabelColor(Qt::black);
  
  setAutoSubTicks(true);
  setSubTickCount(4);
  setSubTickLength(2);
  setSubTickPen(QPen(Qt::black, 0, Qt::SolidLine, Qt::SquareCap));
  setBasePen(QPen(Qt::black, 0, Qt::SolidLine, Qt::SquareCap));
  
  setSelected(spNone);
  setSelectable(spAxis | spTickLabels | spAxisLabel);
  QFont selTickLabelFont = tickLabelFont();
  selTickLabelFont.setBold(true);
  setSelectedTickLabelFont(selTickLabelFont);
  QFont selLabelFont = labelFont();
  selLabelFont.setBold(true);
  setSelectedLabelFont(selLabelFont);
  setSelectedTickLabelColor(Qt::blue);
  setSelectedLabelColor(Qt::blue);
  QPen blueThickPen(Qt::blue, 2);
  setSelectedBasePen(blueThickPen);
  setSelectedTickPen(blueThickPen);
  setSelectedSubTickPen(blueThickPen);
  
  setPadding(0);
  if (type == atTop)
  {
    setTickLabelPadding(3);
    setLabelPadding(6);
  } else if (type == atRight)
  {
    setTickLabelPadding(7);
    setLabelPadding(12);
  } else if (type == atBottom)
  {
    setTickLabelPadding(3);
    setLabelPadding(3);
  } else if (type == atLeft)
  {
    setTickLabelPadding(5);
    setLabelPadding(10);
  }
}
QCPAxis::~QCPAxis () [virtual]
Definition at line 3597 of file qcustomplot.cpp.
References mGrid.
{
  delete mGrid;
}
Member Function Documentation
bool QCPAxis::antialiasedGrid () const [inline]
Definition at line 1707 of file qcustomplot.h.
{ return mGrid->antialiased(); }
bool QCPAxis::antialiasedSubGrid () const [inline]
Definition at line 1708 of file qcustomplot.h.
{ return mGrid->antialiasedSubGrid(); }
bool QCPAxis::antialiasedZeroLine () const [inline]
Definition at line 1709 of file qcustomplot.h.
{ return mGrid->antialiasedZeroLine(); }
void QCPAxis::applyDefaultAntialiasingHint (QCPPainter *painter) const [protected], [virtual]
A convenience function to easily set the QPainter::Antialiased hint on the provided painter before drawing axis lines.
This is the antialiasing state the painter passed to the draw method is in by default.
This function takes into account the local setting of the antialiasing flag as well as the overrides set e.g. with QCustomPlot::setNotAntialiasedElements.
See also:
setAntialiased
Implements QCPLayerable.
Definition at line 5358 of file qcustomplot.cpp.
References QCP::aeAxes, QCPLayerable::applyAntialiasingHint(), and QCPLayerable::mAntialiased.
{
  applyAntialiasingHint(painter, mAntialiased, QCP::aeAxes);
}
bool QCPAxis::autoSubTicks () const [inline]
Definition at line 1716 of file qcustomplot.h.
Referenced by setupFullAxesBox().
{ return mAutoSubTicks; }
int QCPAxis::autoTickCount () const [inline]
Definition at line 1713 of file qcustomplot.h.
Referenced by setupFullAxesBox().
{ return mAutoTickCount; }
bool QCPAxis::autoTickLabels () const [inline]
Definition at line 1714 of file qcustomplot.h.
{ return mAutoTickLabels; }
bool QCPAxis::autoTicks () const [inline]
Definition at line 1712 of file qcustomplot.h.
{ return mAutoTicks; }
bool QCPAxis::autoTickStep () const [inline]
Definition at line 1715 of file qcustomplot.h.
Referenced by setupFullAxesBox().
{ return mAutoTickStep; }
QRect QCPAxis::axisRect () const [inline]
Definition at line 1702 of file qcustomplot.h.
References mAxisRect.
Referenced by QCPAbstractPlottable::clipRect(), QCPAbstractItem::clipRect(), QCPGraph::lowerFillBasePoint(), QCPCurve::outsideCoordsToPixels(), plottableAt(), and QCPGraph::upperFillBasePoint().
{ return mAxisRect; }
AxisType QCPAxis::axisType () const [inline]
Definition at line 1701 of file qcustomplot.h.
Referenced by QCPGraph::lowerFillBasePoint(), and QCPGraph::upperFillBasePoint().
{ return mAxisType; }
double QCPAxis::baseLog (doublevalue) const [protected]
A log function with the base mScaleLogBase, used mostly for coordinate transforms in logarithmic scales with arbitrary log base. Uses the buffered mScaleLogBaseLogInv for faster calculation. This is set to 1.0/qLn(mScaleLogBase) in setScaleLogBase.
See also:
basePow, setScaleLogBase, setScaleType
Definition at line 5398 of file qcustomplot.cpp.
References mScaleLogBaseLogInv.
Referenced by coordToPixel(), and generateAutoTicks().
{
  return qLn(value)*mScaleLogBaseLogInv;
}
QPen QCPAxis::basePen () const [inline]
Definition at line 1735 of file qcustomplot.h.
{ return mBasePen; }
double QCPAxis::basePow (doublevalue) const [protected]
A power function with the base mScaleLogBase, used mostly for coordinate transforms in logarithmic scales with arbitrary log base.
See also:
baseLog, setScaleLogBase, setScaleType
Definition at line 5410 of file qcustomplot.cpp.
References mScaleLogBase.
Referenced by generateAutoTicks().
{
  return qPow(mScaleLogBase, value);
}
int QCPAxis::calculateAutoSubTickCount (doubletickStep) const [protected], [virtual]
Called by generateAutoTicks when setAutoSubTicks is set to true. Depending on the tickStep between two major ticks on the axis, a different number of sub ticks is appropriate. For Example taking 4 sub ticks for a tickStep of 1 makes more sense than taking 5 sub ticks, because this corresponds to a sub tick step of 0.2, instead of the less intuitive 0.16666. Note that a subtick count of 4 means dividing the major tick step into 5 sections.
This is implemented by a hand made lookup for integer tick steps as well as fractional tick steps with a fractional part of (approximately) 0.5. If a tick step is different (i.e. has no fractional part close to 0.5), the currently set sub tick count (setSubTickCount) is returned.
Definition at line 4782 of file qcustomplot.cpp.
References mSubTickCount.
Referenced by generateAutoTicks().
{
  int result = mSubTickCount; // default to current setting, if no proper value can be found
  
  // get mantissa of tickstep:
  double magnitudeFactor = qPow(10.0, qFloor(qLn(tickStep)/qLn(10.0))); // get magnitude factor e.g. 0.01, 1, 10, 1000 etc.
  double tickStepMantissa = tickStep/magnitudeFactor;
  
  // separate integer and fractional part of mantissa:
  double epsilon = 0.01;
  double intPartf;
  int intPart;
  double fracPart = modf(tickStepMantissa, &intPartf);
  intPart = intPartf;
  
  // handle cases with (almost) integer mantissa:
  if (fracPart < epsilon || 1.0-fracPart < epsilon)
  {
    if (1.0-fracPart < epsilon)
      intPart++;
    switch (intPart)
    {
      case 1: result = 4; break; // 1.0 -> 0.2 substep
      case 2: result = 3; break; // 2.0 -> 0.5 substep
      case 3: result = 2; break; // 3.0 -> 1.0 substep
      case 4: result = 3; break; // 4.0 -> 1.0 substep
      case 5: result = 4; break; // 5.0 -> 1.0 substep
      case 6: result = 2; break; // 6.0 -> 2.0 substep
      case 7: result = 6; break; // 7.0 -> 1.0 substep
      case 8: result = 3; break; // 8.0 -> 2.0 substep
      case 9: result = 2; break; // 9.0 -> 3.0 substep
    }
  } else
  {
    // handle cases with significantly fractional mantissa:
    if (qAbs(fracPart-0.5) < epsilon) // *.5 mantissa
    {
      switch (intPart)
      {
        case 1: result = 2; break; // 1.5 -> 0.5 substep
        case 2: result = 4; break; // 2.5 -> 0.5 substep
        case 3: result = 4; break; // 3.5 -> 0.7 substep
        case 4: result = 2; break; // 4.5 -> 1.5 substep
        case 5: result = 4; break; // 5.5 -> 1.1 substep (won't occur with autoTickStep from here on)
        case 6: result = 4; break; // 6.5 -> 1.3 substep
        case 7: result = 2; break; // 7.5 -> 2.5 substep
        case 8: result = 4; break; // 8.5 -> 1.7 substep
        case 9: result = 4; break; // 9.5 -> 1.9 substep
      }
    }
    // if mantissa fraction isnt 0.0 or 0.5, don't bother finding good sub tick marks, leave default
  }
  
  return result;
}
int QCPAxis::calculateMargin () const [protected], [virtual]
Simulates the steps of draw by calculating all appearing text bounding boxes. From this information, the appropriate margin for this axis is determined, so nothing is drawn beyond the widget border in the actual draw function (if QCustomPlot::setAutoMargin is set to true).
The margin consists of: tick label padding, tick label size, label padding, label size. The return value is the calculated margin for this axis. Thus, an axis with axis type atLeft will return an appropriate left margin, atBottom will return an appropriate bottom margin and so forth.
Warning:
if anything is changed in this function, make sure it's synchronized with the actual drawing function draw.
Definition at line 5500 of file qcustomplot.cpp.
References getMaxTickLabelSize(), mLabel, mLabelFont, mLabelPadding, mPadding, mSubTickLengthOut, mTickLabelFont, mTickLabelPadding, mTickLabels, mTickLengthOut, mTickVectorLabels, QCPLayerable::mVisible, orientation(), and visibleTickBounds().
{
  // run through similar steps as QCPAxis::draw, and caluclate margin needed to fit axis and its labels
  int margin = 0;
  
  if (mVisible)
  {
    int lowTick, highTick;
    visibleTickBounds(lowTick, highTick);
    // get length of tick marks reaching outside axis rect:
    margin += qMax(0, qMax(mTickLengthOut, mSubTickLengthOut));
    // calculate size of tick labels:
    QSize tickLabelsSize(0, 0);
    if (mTickLabels)
    {
      for (int i=lowTick; i <= highTick; ++i)
      {
        getMaxTickLabelSize(mTickLabelFont, mTickVectorLabels.at(i), &tickLabelsSize); // don't use getTickLabelFont() because we don't want margin to possibly change on selection
      }
      if (orientation() == Qt::Horizontal)
        margin += tickLabelsSize.height() + mTickLabelPadding;
      else
        margin += tickLabelsSize.width() + mTickLabelPadding;
    }
    // calculate size of axis label (only height needed, because left/right labels are rotated by 90 degrees):
    if (!mLabel.isEmpty())
    {
      QFontMetrics fontMetrics(mLabelFont); // don't use getLabelFont() because we don't want margin to possibly change on selection
      QRect bounds;
      bounds = fontMetrics.boundingRect(0, 0, 0, 0, Qt::TextDontClip | Qt::AlignHCenter | Qt::AlignVCenter, mLabel);
      margin += bounds.height() + mLabelPadding;
    }
  }
  margin += mPadding;
  
  if (margin < 15) // need a bit of margin if no axis text is shown at all (i.e. only baseline and tick lines, or no axis at all)
    margin = 15;
  return margin;
}
double QCPAxis::coordToPixel (doublevalue) const
Transforms value (in coordinates of the axis) to pixel coordinates of the QCustomPlot widget.
Definition at line 4531 of file qcustomplot.cpp.
References baseLog(), QCPRange::lower, mAxisRect, mRange, mRangeReversed, mScaleType, orientation(), QCPRange::size(), QCPRange::upper, and value.
Referenced by QCPAbstractPlottable::coordsToPixels(), draw(), QCPGraph::drawError(), drawGridLines(), QCPGraph::drawScatterPlot(), drawSubGridLines(), QCPGraph::getImpulsePlotData(), QCPGraph::getLinePlotData(), QCPGraph::getStepCenterPlotData(), QCPGraph::getStepLeftPlotData(), QCPGraph::getStepRightPlotData(), QCPGraph::lowerFillBasePoint(), QCPItemPosition::pixelPoint(), QCPStatisticalBox::selectTest(), and QCPGraph::upperFillBasePoint().
{
  if (orientation() == Qt::Horizontal)
  {
    if (mScaleType == stLinear)
    {
      if (!mRangeReversed)
        return (value-mRange.lower)/mRange.size()*mAxisRect.width()+mAxisRect.left();
      else
        return (mRange.upper-value)/mRange.size()*mAxisRect.width()+mAxisRect.left();
    } else // mScaleType == stLogarithmic
    {
      if (value >= 0 && mRange.upper < 0) // invalid value for logarithmic scale, just draw it outside visible range
        return !mRangeReversed ? mAxisRect.right()+200 : mAxisRect.left()-200;
      else if (value <= 0 && mRange.upper > 0) // invalid value for logarithmic scale, just draw it outside visible range
        return !mRangeReversed ? mAxisRect.left()-200 : mAxisRect.right()+200;
      else
      {
        if (!mRangeReversed)
          return baseLog(value/mRange.lower)/baseLog(mRange.upper/mRange.lower)*mAxisRect.width()+mAxisRect.left();
        else
          return baseLog(mRange.upper/value)/baseLog(mRange.upper/mRange.lower)*mAxisRect.width()+mAxisRect.left();
      }
    }
  } else // orientation() == Qt::Vertical
  {
    if (mScaleType == stLinear)
    {
      if (!mRangeReversed)
        return mAxisRect.bottom()-(value-mRange.lower)/mRange.size()*mAxisRect.height();
      else
        return mAxisRect.bottom()-(mRange.upper-value)/mRange.size()*mAxisRect.height();
    } else // mScaleType == stLogarithmic
    {
      if (value >= 0 && mRange.upper < 0) // invalid value for logarithmic scale, just draw it outside visible range
        return !mRangeReversed ? mAxisRect.top()-200 : mAxisRect.bottom()+200;
      else if (value <= 0 && mRange.upper > 0) // invalid value for logarithmic scale, just draw it outside visible range
        return !mRangeReversed ? mAxisRect.bottom()+200 : mAxisRect.top()-200;
      else
      {
        if (!mRangeReversed)
          return mAxisRect.bottom()-baseLog(value/mRange.lower)/baseLog(mRange.upper/mRange.lower)*mAxisRect.height();
        else
          return mAxisRect.bottom()-baseLog(mRange.upper/value)/baseLog(mRange.upper/mRange.lower)*mAxisRect.height();
      }
    }
  }
}
QString QCPAxis::dateTimeFormat () const [inline]
Definition at line 1724 of file qcustomplot.h.
{ return mDateTimeFormat; }
void QCPAxis::draw (QCPPainter *painter) [protected], [virtual]
The main draw function of an axis, called by QCustomPlot::draw for each axis. Draws axis baseline, major ticks, subticks, tick labels and axis label.
The selection boxes (mAxisSelectionBox, mTickLabelsSelectionBox, mLabelSelectionBox) are set here, too.
Implements QCPLayerable.
Definition at line 4846 of file qcustomplot.cpp.
References atBottom, atLeft, atRight, atTop, coordToPixel(), QCPPainter::drawLine(), drawTickLabel(), getBasePen(), getLabelColor(), getLabelFont(), getSubTickPen(), getTickLabelColor(), getTickLabelFont(), getTickPen(), mAxisRect, mAxisSelectionBox, mAxisType, mHighestVisibleTick, mLabel, mLabelPadding, mLabelSelectionBox, mLowestVisibleTick, QCPLayerable::mParentPlot, mSubTickCount, mSubTickLengthIn, mSubTickLengthOut, mSubTickVector, mTickLabelPadding, mTickLabels, mTickLabelsSelectionBox, mTickLengthIn, mTickLengthOut, mTicks, mTickVector, mTickVectorLabels, orientation(), and QCPPainter::setPen().
{
  QPoint origin;
  if (mAxisType == atLeft)
    origin = mAxisRect.bottomLeft();
  else if (mAxisType == atRight)
    origin = mAxisRect.bottomRight();
  else if (mAxisType == atTop)
    origin = mAxisRect.topLeft();
  else if (mAxisType == atBottom)
    origin = mAxisRect.bottomLeft();
  
  double xCor = 0, yCor = 0; // paint system correction, for pixel exact matches (affects baselines and ticks of top/right axes)
  switch (mAxisType)
  {
    case atTop: yCor = -1; break;
    case atRight: xCor = 1; break;
    default: break;
  }
  
  int margin = 0;
  int lowTick = mLowestVisibleTick;
  int highTick = mHighestVisibleTick;
  double t; // helper variable, result of coordinate-to-pixel transforms
  // draw baseline:
  painter->setPen(getBasePen());
  if (orientation() == Qt::Horizontal)
    painter->drawLine(QLineF(origin+QPointF(xCor, yCor), origin+QPointF(mAxisRect.width()+xCor, yCor)));
  else
    painter->drawLine(QLineF(origin+QPointF(xCor, yCor), origin+QPointF(xCor, -mAxisRect.height()+yCor)));
  
  // draw ticks:
  if (mTicks)
  {
    painter->setPen(getTickPen());
    // direction of ticks ("inward" is right for left axis and left for right axis)
    int tickDir = (mAxisType == atBottom || mAxisType == atRight) ? -1 : 1;
    if (orientation() == Qt::Horizontal)
    {
      for (int i=lowTick; i <= highTick; ++i)
      {
        t = coordToPixel(mTickVector.at(i)); // x
        painter->drawLine(QLineF(t+xCor, origin.y()-mTickLengthOut*tickDir+yCor, t+xCor, origin.y()+mTickLengthIn*tickDir+yCor));
      }
    } else
    {
      for (int i=lowTick; i <= highTick; ++i)
      {
        t = coordToPixel(mTickVector.at(i)); // y
        painter->drawLine(QLineF(origin.x()-mTickLengthOut*tickDir+xCor, t+yCor, origin.x()+mTickLengthIn*tickDir+xCor, t+yCor));
      }
    }
  }
  
  // draw subticks:
  if (mTicks && mSubTickCount > 0)
  {
    painter->setPen(getSubTickPen());
    // direction of ticks ("inward" is right for left axis and left for right axis)
    int tickDir = (mAxisType == atBottom || mAxisType == atRight) ? -1 : 1;
    if (orientation() == Qt::Horizontal)
    {
      for (int i=0; i<mSubTickVector.size(); ++i) // no need to check bounds because subticks are always only created inside current mRange
      {
        t = coordToPixel(mSubTickVector.at(i));
        painter->drawLine(QLineF(t+xCor, origin.y()-mSubTickLengthOut*tickDir+yCor, t+xCor, origin.y()+mSubTickLengthIn*tickDir+yCor));
      }
    } else
    {
      for (int i=0; i<mSubTickVector.size(); ++i)
      {
        t = coordToPixel(mSubTickVector.at(i));
        painter->drawLine(QLineF(origin.x()-mSubTickLengthOut*tickDir+xCor, t+yCor, origin.x()+mSubTickLengthIn*tickDir+xCor, t+yCor));
      }
    }
  }
  margin += qMax(0, qMax(mTickLengthOut, mSubTickLengthOut));
  
  // tick labels:
  QSize tickLabelsSize(0, 0); // size of largest tick label, for offset calculation of axis label
  if (mTickLabels)
  {
    margin += mTickLabelPadding;
    painter->setFont(getTickLabelFont());
    painter->setPen(QPen(getTickLabelColor()));
    for (int i=lowTick; i <= highTick; ++i)
    {
      t = coordToPixel(mTickVector.at(i));
      drawTickLabel(painter, t, margin, mTickVectorLabels.at(i), &tickLabelsSize);
    }
  }
  if (orientation() == Qt::Horizontal)
    margin += tickLabelsSize.height();
  else
    margin += tickLabelsSize.width();
  // axis label:
  QRect labelBounds;
  if (!mLabel.isEmpty())
  {
    margin += mLabelPadding;
    painter->setFont(getLabelFont());
    painter->setPen(QPen(getLabelColor()));
    labelBounds = painter->fontMetrics().boundingRect(0, 0, 0, 0, Qt::TextDontClip, mLabel);
    if (mAxisType == atLeft)
    {
      QTransform oldTransform = painter->transform();
      painter->translate((origin.x()-margin-labelBounds.height()), origin.y());
      painter->rotate(-90);
      painter->drawText(0, 0, mAxisRect.height(), labelBounds.height(), Qt::TextDontClip | Qt::AlignCenter, mLabel);
      painter->setTransform(oldTransform);
    }
    else if (mAxisType == atRight)
    {
      QTransform oldTransform = painter->transform();
      painter->translate((origin.x()+margin+labelBounds.height()), origin.y()-mAxisRect.height());
      painter->rotate(90);
      painter->drawText(0, 0, mAxisRect.height(), labelBounds.height(), Qt::TextDontClip | Qt::AlignCenter, mLabel);
      painter->setTransform(oldTransform);
    }
    else if (mAxisType == atTop)
      painter->drawText(origin.x(), origin.y()-margin-labelBounds.height(), mAxisRect.width(), labelBounds.height(), Qt::TextDontClip | Qt::AlignCenter, mLabel);
    else if (mAxisType == atBottom)
      painter->drawText(origin.x(), origin.y()+margin, mAxisRect.width(), labelBounds.height(), Qt::TextDontClip | Qt::AlignCenter, mLabel);
  }
  
  // set selection boxes:
  int selAxisOutSize = qMax(qMax(mTickLengthOut, mSubTickLengthOut), mParentPlot->selectionTolerance());
  int selAxisInSize = mParentPlot->selectionTolerance();
  int selTickLabelSize = (orientation()==Qt::Horizontal ? tickLabelsSize.height() : tickLabelsSize.width());
  int selTickLabelOffset = qMax(mTickLengthOut, mSubTickLengthOut)+mTickLabelPadding;
  int selLabelSize = labelBounds.height();
  int selLabelOffset = selTickLabelOffset+selTickLabelSize+mLabelPadding;
  if (mAxisType == atLeft)
  {
    mAxisSelectionBox.setCoords(mAxisRect.left()-selAxisOutSize, mAxisRect.top(), mAxisRect.left()+selAxisInSize, mAxisRect.bottom());
    mTickLabelsSelectionBox.setCoords(mAxisRect.left()-selTickLabelOffset-selTickLabelSize, mAxisRect.top(), mAxisRect.left()-selTickLabelOffset, mAxisRect.bottom());
    mLabelSelectionBox.setCoords(mAxisRect.left()-selLabelOffset-selLabelSize, mAxisRect.top(), mAxisRect.left()-selLabelOffset, mAxisRect.bottom());
  } else if (mAxisType == atRight)
  {
    mAxisSelectionBox.setCoords(mAxisRect.right()-selAxisInSize, mAxisRect.top(), mAxisRect.right()+selAxisOutSize, mAxisRect.bottom());
    mTickLabelsSelectionBox.setCoords(mAxisRect.right()+selTickLabelOffset+selTickLabelSize, mAxisRect.top(), mAxisRect.right()+selTickLabelOffset, mAxisRect.bottom());
    mLabelSelectionBox.setCoords(mAxisRect.right()+selLabelOffset+selLabelSize, mAxisRect.top(), mAxisRect.right()+selLabelOffset, mAxisRect.bottom());
  } else if (mAxisType == atTop)
  {
    mAxisSelectionBox.setCoords(mAxisRect.left(), mAxisRect.top()-selAxisOutSize, mAxisRect.right(), mAxisRect.top()+selAxisInSize);
    mTickLabelsSelectionBox.setCoords(mAxisRect.left(), mAxisRect.top()-selTickLabelOffset-selTickLabelSize, mAxisRect.right(), mAxisRect.top()-selTickLabelOffset);
    mLabelSelectionBox.setCoords(mAxisRect.left(), mAxisRect.top()-selLabelOffset-selLabelSize, mAxisRect.right(), mAxisRect.top()-selLabelOffset);
  } else if (mAxisType == atBottom)
  {
    mAxisSelectionBox.setCoords(mAxisRect.left(), mAxisRect.bottom()-selAxisInSize, mAxisRect.right(), mAxisRect.bottom()+selAxisOutSize);
    mTickLabelsSelectionBox.setCoords(mAxisRect.left(), mAxisRect.bottom()+selTickLabelOffset+selTickLabelSize, mAxisRect.right(), mAxisRect.bottom()+selTickLabelOffset);
    mLabelSelectionBox.setCoords(mAxisRect.left(), mAxisRect.bottom()+selLabelOffset+selLabelSize, mAxisRect.right(), mAxisRect.bottom()+selLabelOffset);
  }
  // draw hitboxes for debug purposes:
  //painter->drawRects(QVector<QRect>() << mAxisSelectionBox << mTickLabelsSelectionBox << mLabelSelectionBox);
}
void QCPAxis::drawTickLabel (QCPPainter *painter, doubleposition, intdistanceToAxis, const QString &text, QSize *tickLabelsSize) [protected], [virtual]
Draws a single tick label with the provided painter. The tick label is always bound to an axis in one direction (distance to axis in that direction is however controllable via distanceToAxis in pixels). The position in the other direction is passed in the position parameter. Hence for the bottom axis, position would indicate the horizontal pixel position (not coordinate!), at which the label should be drawn.
In order to draw the axis label after all the tick labels in a position, that doesn't overlap with the tick labels, we need to know the largest tick label size. This is done by passing a tickLabelsSize to all drawTickLabel calls during the process of drawing all tick labels of one axis. tickLabelSize is only expanded, if the drawn label exceeds the value tickLabelsSize currently holds.
This function is also responsible for turning ugly exponential numbers '5.5e9' into a more beautifully typeset format '5.5 [multiplication sign] 10 [superscript] 9'. This feature is controlled with setNumberFormat.
The label is drawn with the font and pen that are currently set on the painter. To draw superscripted powers, the font is temporarily made smaller by a fixed factor.
Definition at line 5026 of file qcustomplot.cpp.
References atBottom, atLeft, atRight, atTop, mAutoTickLabels, mAxisRect, mAxisType, mNumberBeautifulPowers, mNumberMultiplyCross, QCPLayerable::mParentPlot, mPositiveSignChar, mScaleType, mTickLabelRotation, mTickLabelType, and orientation().
Referenced by draw().
{
  // warning: if you change anything here, also adapt getMaxTickLabelSize() accordingly!
  
  // determine whether beautiful decimal powers should be used
  bool useBeautifulPowers = false;
  int ePos = -1;
  if (mAutoTickLabels && mNumberBeautifulPowers && mTickLabelType == ltNumber)
  {
    ePos = text.indexOf('e');
    if (ePos > -1)
      useBeautifulPowers = true;
  }
  
  // calculate text bounding rects and do string preparation for beautiful decimal powers:
  QRect bounds, baseBounds, expBounds;
  QString basePart, expPart;
  QFont bugFixFont(painter->font());
  bugFixFont.setPointSizeF(bugFixFont.pointSizeF()+0.05); // QFontMetrics.boundingRect has a bug for exact point sizes that make the results oscillate due to internal rounding
  QFont expFont;
  if (useBeautifulPowers)
  {
    // split string parts for part of number/symbol that will be drawn normally and part that will be drawn as exponent:
    basePart = text.left(ePos);
    // in log scaling, we want to turn "1*10^n" into "10^n", else add multiplication sign and decimal base:
    if (mScaleType == stLogarithmic && basePart == "1")
      basePart = "10";
    else
      basePart += (mNumberMultiplyCross ? QString(QChar(215)) : QString(QChar(183))) + "10";
    expPart = text.mid(ePos+1);
    // clip "+" and leading zeros off expPart:
    while (expPart.at(1) == '0' && expPart.length() > 2) // length > 2 so we leave one zero when numberFormatChar is 'e'
      expPart.remove(1, 1);
    if (expPart.at(0) == mPositiveSignChar)
      expPart.remove(0, 1);
    // prepare smaller font for exponent:
    expFont = painter->font();
    expFont.setPointSize(expFont.pointSize()*0.75);
    // calculate bounding rects of base part, exponent part and total one:
    QFontMetrics fontMetrics(bugFixFont);
    baseBounds = fontMetrics.boundingRect(0, 0, 0, 0, Qt::TextDontClip, basePart);
    QFontMetrics expFontMetrics(expFont);
    expBounds = expFontMetrics.boundingRect(0, 0, 0, 0, Qt::TextDontClip, expPart);
    bounds = baseBounds.adjusted(0, 0, expBounds.width(), 0);
  } else // useBeautifulPowers == false
  {
    QFontMetrics fontMetrics(bugFixFont);
    bounds = fontMetrics.boundingRect(0, 0, 0, 0, Qt::TextDontClip | Qt::AlignHCenter, text);
  }
  
  // if using rotated tick labels, transform bounding rect, too:
  QRect rotatedBounds = bounds;
  if (!qFuzzyIsNull(mTickLabelRotation))
  {
    QTransform transform;
    transform.rotate(mTickLabelRotation);
    rotatedBounds = transform.mapRect(bounds);
  }
  // expand passed tickLabelsSize if current tick label is larger:
  if (rotatedBounds.width() > tickLabelsSize->width())
    tickLabelsSize->setWidth(rotatedBounds.width());
  if (rotatedBounds.height() > tickLabelsSize->height())
    tickLabelsSize->setHeight(rotatedBounds.height());
  
  /*
    calculate coordinates (non-trivial, for best visual appearance): short explanation for bottom
    axis: The anchor, i.e. the point in the label that is placed horizontally under the
    corresponding tick is always on the label side that is closer to the axis (e.g. the left side
    of the text when we're rotating clockwise). On that side, the height is halved and the
    resulting point is defined the anchor. This way, a 90 degree rotated text will be centered
    under the tick (i.e. displaced horizontally by half its height). At the same time, a 45 degree
    rotated text will "point toward" its tick, as is typical for rotated tick labels.
  */
  bool doRotation = !qFuzzyIsNull(mTickLabelRotation);
  double radians = mTickLabelRotation/180.0*M_PI;
  int x=0,y=0;
  if (mAxisType == atLeft)
  {
    if (doRotation)
    {
      if (mTickLabelRotation > 0)
      {
        x = mAxisRect.left()-qCos(radians)*bounds.width()-distanceToAxis;
        y = position-qSin(radians)*bounds.width()-qCos(radians)*bounds.height()/2.0;
      } else
      {
        x = mAxisRect.left()-qCos(-radians)*bounds.width()-qSin(-radians)*bounds.height()-distanceToAxis;
        y = position+qSin(-radians)*bounds.width()-qCos(-radians)*bounds.height()/2.0;
      }
    } else
    {
      x = mAxisRect.left()-bounds.width()-distanceToAxis;
      y = position-bounds.height()/2.0;
    }
  } else if (mAxisType == atRight)
  {
    if (doRotation)
    {
      if (mTickLabelRotation > 0)
      {
        x = mAxisRect.right()+qSin(radians)*bounds.height()+distanceToAxis;
        y = position-qCos(radians)*bounds.height()/2.0;
      } else
      {
        x = mAxisRect.right()+distanceToAxis;
        y = position-qCos(-radians)*bounds.height()/2.0;
      }
    } else
    {
      x = mAxisRect.right()+distanceToAxis;
      y = position-bounds.height()/2.0;
    }
  } else if (mAxisType == atTop)
  {
    if (doRotation)
    {
      if (mTickLabelRotation > 0)
      {
        x = position-qCos(radians)*bounds.width()+qSin(radians)*bounds.height()/2.0;
        y = mAxisRect.top()-qSin(radians)*bounds.width()-qCos(radians)*bounds.height()-distanceToAxis;
      } else
      {
        x = position-qSin(-radians)*bounds.height()/2.0;
        y = mAxisRect.top()-qCos(-radians)*bounds.height()-distanceToAxis;
      }
    } else
    {
      x = position-bounds.width()/2.0;
      y = mAxisRect.top()-bounds.height()-distanceToAxis;
    }
  } else if (mAxisType == atBottom)
  {
    if (doRotation)
    {
      if (mTickLabelRotation > 0)
      {
        x = position+qSin(radians)*bounds.height()/2.0;
        y = mAxisRect.bottom()+distanceToAxis;
      } else
      {
        x = position-qCos(-radians)*bounds.width()-qSin(-radians)*bounds.height()/2.0;
        y = mAxisRect.bottom()+qSin(-radians)*bounds.width()+distanceToAxis;
      }
    } else
    {
      x = position-bounds.width()/2.0;
      y = mAxisRect.bottom()+distanceToAxis;
    }
  }
  
  // if label would be partly clipped by widget border on sides, don't draw it:
  if (orientation() == Qt::Horizontal)
  {
    if (x+bounds.width() > mParentPlot->mViewport.right() ||
        x < mParentPlot->mViewport.left())
      return;
  } else
  {
    if (y+bounds.height() > mParentPlot->mViewport.bottom() ||
        y < mParentPlot->mViewport.top())
      return;
  }
  
  // transform painter to position/rotation:
  QTransform oldTransform = painter->transform();
  painter->translate(x, y);
  if (doRotation)
    painter->rotate(mTickLabelRotation);
  // draw text:
  if (useBeautifulPowers)
  {
    // draw base:
    painter->drawText(0, 0, 0, 0, Qt::TextDontClip, basePart);
    // draw exponent:
    QFont normalFont = painter->font();
    painter->setFont(expFont);
    painter->drawText(baseBounds.width()+1, 0, expBounds.width(), expBounds.height(), Qt::TextDontClip, expPart);
    painter->setFont(normalFont);
  } else // useBeautifulPowers == false
  {
    painter->drawText(0, 0, bounds.width(), bounds.height(), Qt::TextDontClip | Qt::AlignHCenter, text);
  }
  
  // reset rotation/translation transform to what it was before:
  painter->setTransform(oldTransform);
}
void QCPAxis::generateAutoTicks () [protected], [virtual]
If setAutoTicks is set to true, this function is called by setupTickVectors to generate reasonable tick positions (and subtick count). The algorithm tries to create approximately mAutoTickCount ticks (set via setAutoTickCount), taking into account, that tick mantissas that are divisable by two or end in .5 are nice to look at and practical in linear scales. If the scale is logarithmic, one tick is generated at every power of the current logarithm base, set via setScaleLogBase.
Definition at line 4704 of file qcustomplot.cpp.
References baseLog(), basePow(), calculateAutoSubTickCount(), QCPRange::lower, mAutoSubTicks, mAutoTickCount, mAutoTickStep, mRange, mScaleLogBase, mScaleType, mSubTickCount, mTickStep, mTickVector, QCPRange::size(), and QCPRange::upper.
Referenced by setupTickVectors().
{
  if (mScaleType == stLinear)
  {
    if (mAutoTickStep)
    {
      // Generate tick positions according to linear scaling:
      mTickStep = mRange.size()/(double)(mAutoTickCount+1e-10); // mAutoTickCount ticks on average, the small addition is to prevent jitter on exact integers
      double magnitudeFactor = qPow(10.0, qFloor(qLn(mTickStep)/qLn(10.0))); // get magnitude factor e.g. 0.01, 1, 10, 1000 etc.
      double tickStepMantissa = mTickStep/magnitudeFactor;
      if (tickStepMantissa < 5)
      {
        // round digit after decimal point to 0.5
        mTickStep = (int)(tickStepMantissa*2)/2.0*magnitudeFactor;
      } else
      {
        // round to first digit in multiples of 2
        mTickStep = (int)((tickStepMantissa/10.0)*5)/5.0*10*magnitudeFactor;
      }
    }
    if (mAutoSubTicks)
      mSubTickCount = calculateAutoSubTickCount(mTickStep);
    // Generate tick positions according to mTickStep:
    int firstStep = floor(mRange.lower/mTickStep);
    int lastStep = ceil(mRange.upper/mTickStep);
    int tickcount = lastStep-firstStep+1;
    if (tickcount < 0) tickcount = 0;
    mTickVector.resize(tickcount);
    for (int i=0; i<tickcount; ++i)
    {
      mTickVector[i] = (firstStep+i)*mTickStep;
    }
  } else // mScaleType == stLogarithmic
  {
    // Generate tick positions according to logbase scaling:
    if (mRange.lower > 0 && mRange.upper > 0) // positive range
    {
      double lowerMag = basePow((int)floor(baseLog(mRange.lower)));
      double currentMag = lowerMag;
      mTickVector.clear();
      mTickVector.append(currentMag);
      while (currentMag < mRange.upper && currentMag > 0) // currentMag might be zero for ranges ~1e-300, just cancel in that case
      {
        currentMag *= mScaleLogBase;
        mTickVector.append(currentMag);
      }
    } else if (mRange.lower < 0 && mRange.upper < 0) // negative range
    {
      double lowerMag = -basePow((int)ceil(baseLog(-mRange.lower)));
      double currentMag = lowerMag;
      mTickVector.clear();
      mTickVector.append(currentMag);
      while (currentMag < mRange.upper && currentMag < 0) // currentMag might be zero for ranges ~1e-300, just cancel in that case
      {
        currentMag /= mScaleLogBase;
        mTickVector.append(currentMag);
      }
    } else // invalid range for logarithmic scale, because lower and upper have different sign
    {
      mTickVector.clear();
      qDebug() << Q_FUNC_INFO << "Invalid range for logarithmic plot: " << mRange.lower << "-" << mRange.upper;
    }
  }
}
QPen QCPAxis::getBasePen () const [protected]
Returns the pen that is used to draw the axis base line. Depending on the selection state, this is either mSelectedBasePen or mBasePen.
Definition at line 5420 of file qcustomplot.cpp.
References mBasePen, mSelected, and mSelectedBasePen.
Referenced by draw().
{
  return mSelected.testFlag(spAxis) ? mSelectedBasePen : mBasePen;
}
QColor QCPAxis::getLabelColor () const [protected]
Returns the color that is used to draw the axis label. Depending on the selection state, this is either mSelectedLabelColor or mLabelColor.
Definition at line 5480 of file qcustomplot.cpp.
References mLabelColor, mSelected, and mSelectedLabelColor.
Referenced by draw().
{
  return mSelected.testFlag(spAxisLabel) ? mSelectedLabelColor : mLabelColor;
}
QFont QCPAxis::getLabelFont () const [protected]
Returns the font that is used to draw the axis label. Depending on the selection state, this is either mSelectedLabelFont or mLabelFont.
Definition at line 5460 of file qcustomplot.cpp.
References mLabelFont, mSelected, and mSelectedLabelFont.
Referenced by draw().
{
  return mSelected.testFlag(spAxisLabel) ? mSelectedLabelFont : mLabelFont;
}
void QCPAxis::getMaxTickLabelSize (const QFont &font, const QString &text, QSize *tickLabelsSize) const [protected], [virtual]
Simulates the steps done by drawTickLabel by calculating bounding boxes of the text label to be drawn, depending on number format etc. Since we only want the largest tick label for the margin calculation, the passed tickLabelsSize isn't overridden with the calculated label size, but it's only expanded, if it's currently set to a smaller width/height.
Definition at line 5220 of file qcustomplot.cpp.
References mAutoTickLabels, mExponentialChar, mNumberBeautifulPowers, mNumberMultiplyCross, mPositiveSignChar, mScaleType, mTickLabelRotation, and mTickLabelType.
Referenced by calculateMargin().
{
  // This function does the same as drawTickLabel but omits the actual drawing
  // changes involve creating extra QFontMetrics instances for font, since painter->fontMetrics() isn't available
  
  // determine whether beautiful powers should be used
  bool useBeautifulPowers = false;
  int ePos=-1;
  if (mAutoTickLabels && mNumberBeautifulPowers && mTickLabelType == ltNumber)
  {
    ePos = text.indexOf(mExponentialChar);
    if (ePos > -1)
      useBeautifulPowers = true;
  }
  
  // calculate and draw text, depending on whether beautiful powers are applicable or not:
  QRect bounds, baseBounds, expBounds;
  QString basePart, expPart;
  QFont bugFixFont(font);
  bugFixFont.setPointSizeF(bugFixFont.pointSizeF()+0.05); // QFontMetrics.boundingRect has a bug for exact point sizes that make the results oscillate due to internal rounding
  QFont expFont;
  if (useBeautifulPowers)
  {
    // split string parts for part of number/symbol that will be drawn normally and part that will be drawn as exponent:
    basePart = text.left(ePos);
    // in log scaling, we want to turn "1*10^n" into "10^n", else add multiplication sign and decimal base:
    if (mScaleType == stLogarithmic && basePart == "1")
      basePart = "10";
    else
      basePart += (mNumberMultiplyCross ? QString(QChar(215)) : QString(QChar(183))) + "10";
    expPart = text.mid(ePos+1);
    // clip "+" and leading zeros off expPart:
    while (expPart.at(1) == '0' && expPart.length() > 2) // length > 2 so we leave one zero when numberFormatChar is 'e'
      expPart.remove(1, 1);
    if (expPart.at(0) == mPositiveSignChar)
      expPart.remove(0, 1);
    // prepare smaller font for exponent:
    expFont = font;
    expFont.setPointSize(expFont.pointSize()*0.75);
    // calculate bounding rects of base part, exponent part and total one:
    QFontMetrics baseFontMetrics(bugFixFont);
    baseBounds = baseFontMetrics.boundingRect(0, 0, 0, 0, Qt::TextDontClip, basePart);
    QFontMetrics expFontMetrics(expFont);
    expBounds = expFontMetrics.boundingRect(0, 0, 0, 0, Qt::TextDontClip, expPart);
    bounds = baseBounds.adjusted(0, 0, expBounds.width(), 0);
  } else // useBeautifulPowers == false
  {
    QFontMetrics fontMetrics(bugFixFont);
    bounds = fontMetrics.boundingRect(0, 0, 0, 0, Qt::TextDontClip | Qt::AlignHCenter, text);
  }
  
  // if rotated tick labels, transform bounding rect, too:
  QRect rotatedBounds = bounds;
  if (!qFuzzyIsNull(mTickLabelRotation))
  {
    QTransform transform;
    transform.rotate(mTickLabelRotation);
    rotatedBounds = transform.mapRect(bounds);
  }
  
  // expand passed tickLabelsSize if current tick label is larger:
  if (rotatedBounds.width() > tickLabelsSize->width())
    tickLabelsSize->setWidth(rotatedBounds.width());
  if (rotatedBounds.height() > tickLabelsSize->height())
    tickLabelsSize->setHeight(rotatedBounds.height());
}
QPen QCPAxis::getSubTickPen () const [protected]
Returns the pen that is used to draw the subticks. Depending on the selection state, this is either mSelectedSubTickPen or mSubTickPen.
Definition at line 5440 of file qcustomplot.cpp.
References mSelected, mSelectedSubTickPen, and mSubTickPen.
Referenced by draw().
{
  return mSelected.testFlag(spAxis) ? mSelectedSubTickPen : mSubTickPen;
}
QColor QCPAxis::getTickLabelColor () const [protected]
Returns the color that is used to draw the tick labels. Depending on the selection state, this is either mSelectedTickLabelColor or mTickLabelColor.
Definition at line 5470 of file qcustomplot.cpp.
References mSelected, mSelectedTickLabelColor, and mTickLabelColor.
Referenced by draw().
{
  return mSelected.testFlag(spTickLabels) ? mSelectedTickLabelColor : mTickLabelColor;
}
QFont QCPAxis::getTickLabelFont () const [protected]
Returns the font that is used to draw the tick labels. Depending on the selection state, this is either mSelectedTickLabelFont or mTickLabelFont.
Definition at line 5450 of file qcustomplot.cpp.
References mSelected, mSelectedTickLabelFont, and mTickLabelFont.
Referenced by draw().
{
  return mSelected.testFlag(spTickLabels) ? mSelectedTickLabelFont : mTickLabelFont;
}
QPen QCPAxis::getTickPen () const [protected]
Returns the pen that is used to draw the (major) ticks. Depending on the selection state, this is either mSelectedTickPen or mTickPen.
Definition at line 5430 of file qcustomplot.cpp.
References mSelected, mSelectedTickPen, and mTickPen.
Referenced by draw().
{
  return mSelected.testFlag(spAxis) ? mSelectedTickPen : mTickPen;
}
bool QCPAxis::grid () const [inline]
Definition at line 1710 of file qcustomplot.h.
{ return mGrid->visible(); }
QPen QCPAxis::gridPen () const [inline]
Definition at line 1736 of file qcustomplot.h.
{ return mGrid->pen(); }
bool QCPAxis::handleAxisSelection (QMouseEvent *event, booladditiveSelection, bool &modified) [protected], [virtual]
Handles the selection event and returns true when the selection event hit any parts of the axis. If the selection state of any parts of the axis was changed, the output parameter modified is set to true.
When additiveSelecton is true, any new selections become selected in addition to the recent selections. The recent selections are not cleared. Further, clicking on one object multiple times in additive selection mode, toggles the selection of that object on and off.
To indicate that an event deselects the axis (i.e. the parts that are deselectable by the user, see setSelectable), pass 0 as event.
Definition at line 5300 of file qcustomplot.cpp.
References selectable(), selected(), selectTest(), and setSelected().
{
  bool selectionFound = false;
  if (event)
  {
    SelectablePart selectedAxisPart = selectTest(event->pos());
    if (selectedAxisPart == spNone || !selectable().testFlag(selectedAxisPart))
    {
      // deselect parts that are changeable (selectable):
      SelectableParts newState = selected() & ~selectable();
      if (newState != selected() && !additiveSelection)
      {
        modified = true;
        setSelected(newState);
      }
    } else
    {
      selectionFound = true;
      if (additiveSelection)
      {
        // additive selection, so toggle selected part:
        setSelected(selected() ^ selectedAxisPart);
        modified = true;
      } else
      {
        // not additive selection, so select part and deselect all others that are changeable (selectable):
        SelectableParts newState = (selected() & ~selectable()) | selectedAxisPart;
        if (newState != selected())
        {
          modified = true;
          setSelected(newState);
        }
      }
    }
  } else // event == 0, so deselect all changeable parts
  {
    SelectableParts newState = selected() & ~selectable();
    if (newState != selected())
    {
      modified = true;
      setSelected(newState);
    }
  }
  return selectionFound;
}
QString QCPAxis::label () const [inline]
Definition at line 1743 of file qcustomplot.h.
{ return mLabel; }
QColor QCPAxis::labelColor () const [inline]
Definition at line 1742 of file qcustomplot.h.
{ return mLabelColor; }
QFont QCPAxis::labelFont () const [inline]
Definition at line 1741 of file qcustomplot.h.
Referenced by QCPAxis().
{ return mLabelFont; }
int QCPAxis::labelPadding () const [inline]
Definition at line 1744 of file qcustomplot.h.
{ return mLabelPadding; }
void QCPAxis::moveRange (doublediff)
If the scale type (setScaleType) is stLinear, diff is added to the lower and upper bounds of the range. The range is simply moved by diff.
If the scale type is stLogarithmic, the range bounds are multiplied by diff. This corresponds to an apparent 'linear' move in logarithmic scaling by a distance of log(diff).
Definition at line 4419 of file qcustomplot.cpp.
References QCPRange::lower, mRange, mScaleType, rangeChanged(), and QCPRange::upper.
{
  if (mScaleType == stLinear)
  {
    mRange.lower += diff;
    mRange.upper += diff;
  } else // mScaleType == stLogarithmic
  {
    mRange.lower *= diff;
    mRange.upper *= diff;
  }
  emit rangeChanged(mRange);
}
QString QCPAxis::numberFormat () const
Definition at line 3603 of file qcustomplot.cpp.
References mNumberBeautifulPowers, mNumberFormatChar, and mNumberMultiplyCross.
{
  QString result;
  result.append(mNumberFormatChar);
  if (mNumberBeautifulPowers)
  {
    result.append("b");
    if (mNumberMultiplyCross)
      result.append("c");
  }
  return result;
}
int QCPAxis::numberPrecision () const [inline]
Definition at line 1726 of file qcustomplot.h.
{ return mNumberPrecision; }
Qt::Orientation QCPAxis::orientation () const [inline]
Returns the orientation of the axis. The axis orientation (horizontal or vertical) is deduced from the axis type (left, top, right or bottom).
Definition at line 1810 of file qcustomplot.h.
Referenced by QCPGraph::addFillBasePoints(), calculateMargin(), QCPAbstractPlottable::coordsToPixels(), coordToPixel(), draw(), QCPGraph::drawError(), drawGridLines(), QCPGraph::drawScatterPlot(), drawSubGridLines(), drawTickLabel(), QCPGraph::getChannelFillPolygon(), QCPGraph::getImpulsePlotData(), QCPGraph::getLinePlotData(), QCPGraph::getScatterPlotData(), QCPGraph::getStepCenterPlotData(), QCPGraph::getStepLeftPlotData(), QCPGraph::getStepRightPlotData(), QCPGraph::lowerFillBasePoint(), QCPItemPosition::pixelPoint(), QCPAbstractPlottable::pixelsToCoords(), pixelToCoord(), QCPAbstractPlottable::QCPAbstractPlottable(), QCPItemPosition::setPixelPoint(), setScaleRatio(), and QCPGraph::upperFillBasePoint().
{ return mOrientation; }
int QCPAxis::padding () const [inline]
Definition at line 1745 of file qcustomplot.h.
Referenced by setLabelPadding(), setPadding(), and setTickLabelPadding().
{ return mPadding; }
double QCPAxis::pixelToCoord (doublevalue) const
Transforms value (in pixel coordinates of the QCustomPlot widget) to axis coordinates.
Definition at line 4493 of file qcustomplot.cpp.
References QCPRange::lower, mAxisRect, mRange, mRangeReversed, mScaleType, orientation(), QCPRange::size(), QCPRange::upper, and value.
Referenced by mouseMoveEvent(), QCPAbstractPlottable::pixelsToCoords(), QCPItemPosition::setPixelPoint(), and wheelEvent().
{
  if (orientation() == Qt::Horizontal)
  {
    if (mScaleType == stLinear)
    {
      if (!mRangeReversed)
        return (value-mAxisRect.left())/(double)mAxisRect.width()*mRange.size()+mRange.lower;
      else
        return -(value-mAxisRect.left())/(double)mAxisRect.width()*mRange.size()+mRange.upper;
    } else // mScaleType == stLogarithmic
    {
      if (!mRangeReversed)
        return pow(mRange.upper/mRange.lower, (value-mAxisRect.left())/(double)mAxisRect.width())*mRange.lower;
      else
        return pow(mRange.upper/mRange.lower, (mAxisRect.left()-value)/(double)mAxisRect.width())*mRange.upper;
    }
  } else // orientation() == Qt::Vertical
  {
    if (mScaleType == stLinear)
    {
      if (!mRangeReversed)
        return (mAxisRect.bottom()-value)/(double)mAxisRect.height()*mRange.size()+mRange.lower;
      else
        return -(mAxisRect.bottom()-value)/(double)mAxisRect.height()*mRange.size()+mRange.upper;
    } else // mScaleType == stLogarithmic
    {
      if (!mRangeReversed)
        return pow(mRange.upper/mRange.lower, (mAxisRect.bottom()-value)/(double)mAxisRect.height())*mRange.lower;
      else
        return pow(mRange.upper/mRange.lower, (value-mAxisRect.bottom())/(double)mAxisRect.height())*mRange.upper;
    }
  }
}
QCPAxis::Q_ENUMS (AxisType) [inline]
When automatic tick label generation is enabled (setAutoTickLabels), defines how the numerical value (coordinate) of the tick position is translated into a string that will be drawn at the tick position.
See also:
setTickLabelType
< Tick coordinate is regarded as normal number and will be displayed as such. (see setNumberFormat)
< Tick coordinate is regarded as a date/time (seconds since 1970-01-01T00:00:00 UTC, see QDateTime::toTime_t) and will be displayed and formatted as such. (see setDateTimeFormat)
Definition at line 1666 of file qcustomplot.h.
                 { ltNumber
                   ,ltDateTime
                 };
QCPAxis::Q_ENUMS (LabelType) [inline]
Defines the scale of an axis.
See also:
setScaleType
< Normal linear scaling
< Logarithmic scaling with correspondingly transformed plots and (major) tick marks at every base power (see setScaleLogBase).
Definition at line 1676 of file qcustomplot.h.
                 { stLinear
                   ,stLogarithmic
                 };
QCPAxis::Q_ENUMS (ScaleType) [inline]
Defines the selectable parts of an axis.
See also:
setSelectable, setSelected
< None of the selectable parts
< The axis backbone and tick marks
< Tick labels (numbers) of this axis (as a whole, not individually)
< The axis label
Definition at line 1684 of file qcustomplot.h.
                      { spNone = 0
                        ,spAxis = 0x001
                        ,spTickLabels = 0x002
                        ,spAxisLabel = 0x004
                      };
QCPAxis::Q_ENUMS (SelectablePart)
const QCPRange QCPAxis::range () const [inline]
Definition at line 1705 of file qcustomplot.h.
Referenced by QCPGraph::draw(), QCPBars::draw(), drawGridLines(), QCPCurve::getCurveData(), QCPGraph::getVisibleDataBounds(), QCPGraph::lowerFillBasePoint(), QCPAbstractPlottable::rescaleKeyAxis(), QCPGraph::rescaleKeyAxis(), QCPAbstractPlottable::rescaleValueAxis(), QCPGraph::rescaleValueAxis(), setScaleRatio(), setupFullAxesBox(), and QCPGraph::upperFillBasePoint().
{ return mRange; }
void QCPAxis::rangeChanged (const QCPRange &newRange) [signal]
This signal is emitted when the range of this axis has changed. You can connect it to the setRange slot of another axis to communicate the new range to the other axis, in order for it to be synchronized.
Definition at line 1971 of file moc_qcustomplot.cpp.
Referenced by moveRange(), scaleRange(), setRange(), setRangeLower(), and setRangeUpper().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 1, _a);
}
bool QCPAxis::rangeReversed () const [inline]
Definition at line 1706 of file qcustomplot.h.
Referenced by QCPGraph::drawError(), QCPGraph::lowerFillBasePoint(), setupFullAxesBox(), and QCPGraph::upperFillBasePoint().
{ return mRangeReversed; }
double QCPAxis::scaleLogBase () const [inline]
Definition at line 1704 of file qcustomplot.h.
Referenced by setupFullAxesBox().
{ return mScaleLogBase; }
void QCPAxis::scaleRange (doublefactor, doublecenter)
Scales the range of this axis by factor around the coordinate center. For example, if factor is 2.0, center is 1.0, then the axis range will double its size, and the point at coordinate 1.0 won't have changed its position in the QCustomPlot widget (i.e. coordinates around 1.0 will have moved symmetrically closer to 1.0).
Definition at line 4439 of file qcustomplot.cpp.
References QCPRange::lower, mRange, mScaleType, rangeChanged(), QCPRange::sanitizedForLinScale(), QCPRange::sanitizedForLogScale(), QCPRange::upper, and QCPRange::validRange().
Referenced by wheelEvent().
{
  
  if (mScaleType == stLinear)
  {
    QCPRange newRange;
    newRange.lower = (mRange.lower-center)*factor + center;
    newRange.upper = (mRange.upper-center)*factor + center;
    if (QCPRange::validRange(newRange))
      mRange = newRange.sanitizedForLinScale();
  } else // mScaleType == stLogarithmic
  {
    if ((mRange.upper < 0 && center < 0) || (mRange.upper > 0 && center > 0)) // make sure center has same sign as range
    {
      QCPRange newRange;
      newRange.lower = pow(mRange.lower/center, factor)*center;
      newRange.upper = pow(mRange.upper/center, factor)*center;
      if (QCPRange::validRange(newRange))
        mRange = newRange.sanitizedForLogScale();
    } else
      qDebug() << Q_FUNC_INFO << "center of scaling operation doesn't lie in same logarithmic sign domain as range:" << center;
  }
  emit rangeChanged(mRange);
}
ScaleType QCPAxis::scaleType () const [inline]
Definition at line 1703 of file qcustomplot.h.
Referenced by QCPGraph::lowerFillBasePoint(), QCPAbstractPlottable::rescaleKeyAxis(), QCPGraph::rescaleKeyAxis(), QCPAbstractPlottable::rescaleValueAxis(), QCPGraph::rescaleValueAxis(), setupFullAxesBox(), and QCPGraph::upperFillBasePoint().
{ return mScaleType; }
SelectableParts QCPAxis::selectable () const [inline]
Definition at line 1747 of file qcustomplot.h.
Referenced by handleAxisSelection(), and setSelectable().
{ return mSelectable; }
SelectableParts QCPAxis::selected () const [inline]
Definition at line 1746 of file qcustomplot.h.
Referenced by handleAxisSelection(), and setSelected().
{ return mSelected; }
QPen QCPAxis::selectedBasePen () const [inline]
Definition at line 1752 of file qcustomplot.h.
{ return mSelectedBasePen; }
QColor QCPAxis::selectedLabelColor () const [inline]
Definition at line 1751 of file qcustomplot.h.
{ return mSelectedLabelColor; }
QFont QCPAxis::selectedLabelFont () const [inline]
Definition at line 1749 of file qcustomplot.h.
{ return mSelectedLabelFont; }
QPen QCPAxis::selectedSubTickPen () const [inline]
Definition at line 1754 of file qcustomplot.h.
{ return mSelectedSubTickPen; }
QColor QCPAxis::selectedTickLabelColor () const [inline]
Definition at line 1750 of file qcustomplot.h.
{ return mSelectedTickLabelColor; }
QFont QCPAxis::selectedTickLabelFont () const [inline]
Definition at line 1748 of file qcustomplot.h.
{ return mSelectedTickLabelFont; }
QPen QCPAxis::selectedTickPen () const [inline]
Definition at line 1753 of file qcustomplot.h.
{ return mSelectedTickPen; }
void QCPAxis::selectionChanged (QCPAxis::SelectablePartsselection) [signal]
This signal is emitted when the selection state of this axis has changed, either by user interaction or by a direct call to setSelected.
Definition at line 1978 of file moc_qcustomplot.cpp.
Referenced by setSelected().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 2, _a);
}
QCPAxis::SelectablePart QCPAxis::selectTest (const QPointF &pos) const
Returns the part of the axis that is hit by pos (in pixels). The return value of this function is independent of the user-selectable parts defined with setSelectable. Further, this function does not change the current selection state of the axis.
If the axis is not visible (setVisible), this function always returns spNone.
See also:
setSelected, setSelectable, QCustomPlot::setInteractions
Definition at line 4589 of file qcustomplot.cpp.
References mAxisSelectionBox, mLabelSelectionBox, mTickLabelsSelectionBox, and QCPLayerable::mVisible.
Referenced by handleAxisSelection(), and mouseReleaseEvent().
{
  if (!mVisible)
    return spNone;
  
  if (mAxisSelectionBox.contains(pos.toPoint()))
    return spAxis;
  else if (mTickLabelsSelectionBox.contains(pos.toPoint()))
    return spTickLabels;
  else if (mLabelSelectionBox.contains(pos.toPoint()))
    return spAxisLabel;
  else
    return spNone;
}
void QCPAxis::setAntialiasedGrid (boolenabled)
Sets whether the grid of this axis is drawn antialiased or not. Note that this setting may be overridden by QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements.
Definition at line 3848 of file qcustomplot.cpp.
References mGrid.
{
  mGrid->setAntialiased(enabled);
}
void QCPAxis::setAntialiasedSubGrid (boolenabled)
Sets whether the sub grid of this axis is drawn antialiased or not. Note that this setting may be overridden by QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements.
Definition at line 3859 of file qcustomplot.cpp.
References mGrid.
{
  mGrid->setAntialiasedSubGrid(enabled);
}
void QCPAxis::setAntialiasedZeroLine (boolenabled)
Sets whether the zero line of this axis is drawn antialiased or not. Note that this setting may be overridden by QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements.
Definition at line 3870 of file qcustomplot.cpp.
References mGrid.
{
  mGrid->setAntialiasedZeroLine(enabled);
}
void QCPAxis::setAutoSubTicks (boolon)
Sets whether the number of sub ticks in one tick interval is determined automatically. This works, as long as the tick step mantissa is a multiple of 0.5 (which it is, when setAutoTickStep is enabled).
When on is set to false, you may set the sub tick count with setSubTickCount manually.
Definition at line 3957 of file qcustomplot.cpp.
References mAutoSubTicks.
Referenced by QCPAxis(), and setupFullAxesBox().
{
  mAutoSubTicks = on;
}
void QCPAxis::setAutoTickCount (intapproximateCount)
When setAutoTickStep is true, approximateCount determines how many ticks should be generated in the visible range approximately.
Definition at line 3914 of file qcustomplot.cpp.
References mAutoTickCount.
Referenced by QCPAxis(), and setupFullAxesBox().
{
  mAutoTickCount = approximateCount;
}
void QCPAxis::setAutoTickLabels (boolon)
Sets whether the tick labels are generated automatically depending on the tick label type (ltNumber or ltDateTime). If on is set to false, you should provide the tick labels via setTickVectorLabels. This is usually used in a combination with setAutoTicks set to false for complete control over tick positions and labels, e.g. when the ticks should be at multiples of pi and show '2pi', '3pi' etc. as tick labels.
If you need dynamically calculated tick vectors (and possibly tick label vectors), set the vectors in a slot connected to the ticksRequest signal.
Definition at line 3931 of file qcustomplot.cpp.
References mAutoTickLabels.
Referenced by QCPAxis().
{
  mAutoTickLabels = on;
}
void QCPAxis::setAutoTicks (boolon)
Sets whether the tick positions should be calculated automatically (either from an automatically generated tick step or a tick step provided manually via setTickStep, see setAutoTickStep). If on is set to false, you must provide the tick positions manually via setTickVector. For these manual ticks you may let QCPAxis generate the appropriate labels automatically by setting/leaving setAutoTickLabels true. If you also wish to control the displayed labels manually, set setAutoTickLabels to false and provide the label strings with setTickVectorLabels.
If you need dynamically calculated tick vectors (and possibly tick label vectors), set the vectors in a slot connected to the ticksRequest signal.
Definition at line 3905 of file qcustomplot.cpp.
References mAutoTicks.
Referenced by QCPAxis().
{
  mAutoTicks = on;
}
void QCPAxis::setAutoTickStep (boolon)
Sets whether the tick step, i.e. the interval between two (major) ticks, is calculated automatically. If on is set to true, the axis finds a tick step that is reasonable for human readable plots. This means the tick step mantissa is chosen such that it's either a multiple of two or ends in 0.5. The number of ticks the algorithm aims for within the visible range can be set with setAutoTickCount. It's not guaranteed that this number of ticks is met exactly, but approximately within a tolerance of two or three.
If on is set to false, you may set the tick step manually with setTickStep.
Definition at line 3946 of file qcustomplot.cpp.
References mAutoTickStep.
Referenced by QCPAxis(), and setupFullAxesBox().
{
  mAutoTickStep = on;
}
void QCPAxis::setAxisRect (const QRect &rect) [protected]
Sets the axis rect. The axis uses this rect to position itself within the plot, together with the information of its type (setAxisType). Theoretically it's possible to give a plot's axes different axis rects (e.g. for gaps between them), however, they are currently all synchronized by the QCustomPlot::setAxisRect function.
Definition at line 3635 of file qcustomplot.cpp.
References mAxisRect.
Referenced by QCPAxis(), and updateAxisRect().
{
  mAxisRect = rect;
}
void QCPAxis::setAxisType (AxisTypetype) [protected]
Sets the axis type. This determines the orientation and together with the current axis rect (see setAxisRect), the position of the axis. Depending on type, ticks, tick labels, and label are drawn on corresponding sides of the axis base line.
Definition at line 3622 of file qcustomplot.cpp.
References atBottom, atTop, mAxisType, and mOrientation.
Referenced by QCPAxis().
{
  mAxisType = type;
  mOrientation = (type == atBottom || type == atTop) ? Qt::Horizontal : Qt::Vertical;
}
void QCPAxis::setBasePen (const QPen &pen)
Sets the pen, the axis base line is drawn with.
See also:
setTickPen, setSubTickPen
Definition at line 4233 of file qcustomplot.cpp.
References mBasePen, and pen().
Referenced by QCPAxis().
{
  mBasePen = pen;
}
void QCPAxis::setDateTimeFormat (const QString &format)
Sets the format in which dates and times are displayed as tick labels, if setTickLabelType is ltDateTime. for details about the format string, see the documentation of QDateTime::toString(). Newlines can be inserted with '\n'.
Definition at line 4038 of file qcustomplot.cpp.
References mDateTimeFormat.
Referenced by QCPAxis().
{
  mDateTimeFormat = format;
}
void QCPAxis::setGrid (boolshow)
Sets whether the grid lines are visible.
See also:
setSubGrid, setGridPen, setZeroLinePen
Definition at line 3879 of file qcustomplot.cpp.
References mGrid.
{
  mGrid->setVisible(show);
}
void QCPAxis::setGridPen (const QPen &pen)
Sets the pen, grid lines are drawn with.
See also:
setSubGridPen, setZeroLinePen
Definition at line 4242 of file qcustomplot.cpp.
References mGrid.
{
  mGrid->setPen(pen);
}
void QCPAxis::setLabel (const QString &str)
Sets the axis label that will be shown below/above or next to the axis, depending on its orientation.
Definition at line 4310 of file qcustomplot.cpp.
References mLabel.
Referenced by QCPAxis().
{
  mLabel = str;
}
void QCPAxis::setLabelColor (const QColor &color)
Sets the color of the axis label.
See also:
setLabelFont
Definition at line 4302 of file qcustomplot.cpp.
References color(), and mLabelColor.
Referenced by QCPAxis().
{
  mLabelColor = color;
}
void QCPAxis::setLabelFont (const QFont &font)
Sets the font of the axis label.
See also:
setLabelColor
Definition at line 4292 of file qcustomplot.cpp.
References mLabelFont.
Referenced by QCPAxis().
{
  mLabelFont = font;
}
void QCPAxis::setLabelPadding (intpadding)
Sets the distance between the tick labels and the axis label.
See also:
setTickLabelPadding, setPadding
Definition at line 4319 of file qcustomplot.cpp.
References mLabelPadding, and padding().
Referenced by QCPAxis().
{
  mLabelPadding = padding;
}
void QCPAxis::setNumberFormat (const QString &formatCode)
Sets the number format for the numbers drawn as tick labels (if tick label type is ltNumber). This formatCode is an extended version of the format code used e.g. by QString::number() and QLocale::toString(). For reference about that, see the 'Argument Formats' section in the detailed description of the QString class. formatCode is a string of one, two or three characters. The first character is identical to the normal format code used by Qt. In short, this means: 'e'/'E' scientific format, 'f' fixed format, 'g'/'G' scientific or fixed, whichever is shorter.
The second and third characters are optional and specific to QCustomPlot:
If the first char was 'e' or 'g', numbers are/might be displayed in the scientific format, e.g. '5.5e9', which is ugly in a plot. So when the second char of formatCode is set to 'b' (for 'beautiful'), those exponential numbers are formatted in a more natural way, i.e. '5.5
[multiplication sign] 10 [superscript] 9'. By default, the multiplication sign is a centered dot. If instead a cross should be shown (as is usual in the USA), the third char of formatCode can be set to 'c'. The inserted multiplication signs are the UTF-8 characters 215 (0xD7) for the cross and 183 (0xB7) for the dot.
If the scale type (setScaleType) is stLogarithmic and the formatCode uses the 'b' option (beautifully typeset decimal powers), the display usually is '1 [multiplication sign] 10
[superscript] n', which looks unnatural for logarithmic scaling (the '1 [multiplication sign]' part). To only display the decimal power, set the number precision to zero with setNumberPrecision.
Examples for formatCode:
g normal format code behaviour. If number is small, fixed format is used, if number is large, normal scientific format is used
gb If number is small, fixed format is used, if number is large, scientific format is used with beautifully typeset decimal powers and a dot as multiplication sign
ebc All numbers are in scientific format with beautifully typeset decimal power and a cross as multiplication sign
fb illegal format code, since fixed format doesn't support (or need) beautifully typeset decimal powers. Format code will be reduced to 'f'.
hello illegal format code, since first char is not 'e', 'E', 'f', 'g' or 'G'. Current format code will not be changed.
Definition at line 4079 of file qcustomplot.cpp.
References mNumberBeautifulPowers, mNumberFormatChar, and mNumberMultiplyCross.
Referenced by QCPAxis().
{
  if (formatCode.length() < 1) return;
  
  // interpret first char as number format char:
  QString allowedFormatChars = "eEfgG";
  if (allowedFormatChars.contains(formatCode.at(0)))
  {
  // mNumberFormatChar = formatCode.at(0).toAscii();
    mNumberFormatChar = formatCode.at(0).toLatin1();
  } else
  {
    qDebug() << Q_FUNC_INFO << "Invalid number format code (first char not in 'eEfgG'):" << formatCode;
    return;
  }
  if (formatCode.length() < 2)
  {
    mNumberBeautifulPowers = false;
    mNumberMultiplyCross = false;
    return;
  }
  
  // interpret second char as indicator for beautiful decimal powers:
  if (formatCode.at(1) == 'b' && (mNumberFormatChar == 'e' || mNumberFormatChar == 'g'))
  {
    mNumberBeautifulPowers = true;
  } else
  {
    qDebug() << Q_FUNC_INFO << "Invalid number format code (second char not 'b' or first char neither 'e' nor 'g'):" << formatCode;
    return;
  }
  if (formatCode.length() < 3)
  {
    mNumberMultiplyCross = false;
    return;
  }
  
  // interpret third char as indicator for dot or cross multiplication symbol:
  if (formatCode.at(2) == 'c')
  {
    mNumberMultiplyCross = true;
  } else if (formatCode.at(2) == 'd')
  {
    mNumberMultiplyCross = false;
  } else
  {
    qDebug() << Q_FUNC_INFO << "Invalid number format code (third char neither 'c' nor 'd'):" << formatCode;
    return;
  }
}
void QCPAxis::setNumberPrecision (intprecision)
Sets the precision of the numbers drawn as tick labels. See QLocale::toString(double i, char f, int prec) for details. The effect of precisions are most notably for number Formats starting with 'e', see setNumberFormat
If the scale type (setScaleType) is stLogarithmic and the number format (setNumberFormat) uses the 'b' format code (beautifully typeset decimal powers), the display usually is '1 [multiplication sign] 10 [superscript] n', which looks unnatural for logarithmic scaling (the '1 [multiplication sign]' part). To only display the decimal power, set precision to zero.
Definition at line 4141 of file qcustomplot.cpp.
References mNumberPrecision.
Referenced by QCPAxis().
{
  mNumberPrecision = precision;
}
void QCPAxis::setPadding (intpadding)
Sets the padding of the axis. When QCustomPlot::setAutoMargin is enabled, the padding is the additional distance to the respective widget border, that is left blank. If padding is zero (default), the auto margin mechanism will find a margin that the axis label (or tick label, if no axis label is set) barely fits inside the QCustomPlot widget. To give the label closest to the border some freedom, increase padding.
The axis padding has no meaning if QCustomPlot::setAutoMargin is disabled.
See also:
setLabelPadding, setTickLabelPadding
Definition at line 4337 of file qcustomplot.cpp.
References mPadding, and padding().
Referenced by QCPAxis().
{
  mPadding = padding;
}
void QCPAxis::setRange (doublelower, doubleupper)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets the lower and upper bound of the axis range. To invert the direction of an axis range, use setRangeReversed.
There is also a slot to set a range, see setRange(const QCPRange &range).
Definition at line 3749 of file qcustomplot.cpp.
References QCPRange::lower, mRange, mScaleType, rangeChanged(), QCPRange::sanitizedForLinScale(), QCPRange::sanitizedForLogScale(), QCPRange::upper, and QCPRange::validRange().
Referenced by mouseMoveEvent(), QCPAxis(), QCPAbstractPlottable::rescaleKeyAxis(), QCPGraph::rescaleKeyAxis(), QCPAbstractPlottable::rescaleValueAxis(), QCPGraph::rescaleValueAxis(), setRange(), setScaleRatio(), and setupFullAxesBox().
{
  if (lower == mRange.lower && upper == mRange.upper)
    return;
  
  if (!QCPRange::validRange(lower, upper)) return;
  mRange.lower = lower;
  mRange.upper = upper;
  if (mScaleType == stLogarithmic)
  {
    mRange = mRange.sanitizedForLogScale();
  } else
  {
    mRange = mRange.sanitizedForLinScale();
  }
  emit rangeChanged(mRange);
}
void QCPAxis::setRange (doubleposition, doublesize, Qt::AlignmentFlagalignment)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets the range of the axis.
Parameters:
position the position coordinate indicates together with the alignment parameter, where the new range will be positioned.
size defines the size (upper-lower) of the new axis range.
alignment determines how position is to be interpreted.
If alignment is Qt::AlignLeft, position will be the lower bound of the range.
If alignment is Qt::AlignRight, position will be the upper bound of the range.
If alignment is Qt::AlignCenter, the new range will be centered around position.
Any other values for alignment will default to Qt::AlignCenter.
Definition at line 3780 of file qcustomplot.cpp.
References setRange().
{
  if (alignment == Qt::AlignLeft)
    setRange(position, position+size);
  else if (alignment == Qt::AlignRight)
    setRange(position-size, position);
  else // alignment == Qt::AlignCenter
    setRange(position-size/2.0, position+size/2.0);
}
void QCPAxis::setRange (const QCPRange &range) [slot]
Sets the range of the axis. This slot may be connected with the rangeChanged signal of another axis so this axis is always synchronized with the other axis range, when it changes.
To invert the direction of an axis range, use setRangeReversed.
Definition at line 3685 of file qcustomplot.cpp.
References QCPRange::lower, mRange, mScaleType, rangeChanged(), QCPRange::sanitizedForLinScale(), QCPRange::sanitizedForLogScale(), QCPRange::upper, and QCPRange::validRange().
{
  if (range.lower == mRange.lower && range.upper == mRange.upper)
    return;
  
  if (!QCPRange::validRange(range)) return;
  if (mScaleType == stLogarithmic)
  {
    mRange = range.sanitizedForLogScale();
  } else
  {
    mRange = range.sanitizedForLinScale();
  }
  emit rangeChanged(mRange);
}
void QCPAxis::setRangeLower (doublelower)
Sets the lower bound of the axis range, independently of the upper bound.
See also:
setRange
Definition at line 3794 of file qcustomplot.cpp.
References QCPRange::lower, mRange, mScaleType, rangeChanged(), QCPRange::sanitizedForLinScale(), and QCPRange::sanitizedForLogScale().
{
  if (mRange.lower == lower)
    return;
  
  mRange.lower = lower;
  if (mScaleType == stLogarithmic)
  {
    mRange = mRange.sanitizedForLogScale();
  } else
  {
    mRange = mRange.sanitizedForLinScale();
  }
  emit rangeChanged(mRange);
}
void QCPAxis::setRangeReversed (boolreversed)
Sets whether the axis range (direction) is displayed reversed. Normally, the values on horizontal axes increase left to right, on vertical axes bottom to top. When reversed is set to true, the direction of increasing values is inverted. Note that the range and data interface stays the same for reversed axes, e.g. the lower part of the setRange interface will still reference the mathematically smaller number than the upper part.
Definition at line 3837 of file qcustomplot.cpp.
References mRangeReversed.
Referenced by QCPAxis(), and setupFullAxesBox().
{
  mRangeReversed = reversed;
}
void QCPAxis::setRangeUpper (doubleupper)
Sets the upper bound of the axis range, independently of the lower bound.
See also:
setRange
Definition at line 3814 of file qcustomplot.cpp.
References mRange, mScaleType, rangeChanged(), QCPRange::sanitizedForLinScale(), QCPRange::sanitizedForLogScale(), and QCPRange::upper.
{
  if (mRange.upper == upper)
    return;
  
  mRange.upper = upper;
  if (mScaleType == stLogarithmic)
  {
    mRange = mRange.sanitizedForLogScale();
  } else
  {
    mRange = mRange.sanitizedForLinScale();
  }
  emit rangeChanged(mRange);
}
void QCPAxis::setScaleLogBase (doublebase)
If setScaleType is set to stLogarithmic, base will be the logarithm base of the scaling. In logarithmic axis scaling, major tick marks appear at all powers of base.
Properties like tick step (setTickStep) don't apply in logarithmic scaling. If you wish a decimal base but less major ticks, consider choosing base 100, 1000 or even higher.
Definition at line 3667 of file qcustomplot.cpp.
References mScaleLogBase, and mScaleLogBaseLogInv.
Referenced by QCPAxis(), and setupFullAxesBox().
{
  if (base > 1)
  {
    mScaleLogBase = base;
    mScaleLogBaseLogInv = 1.0/qLn(mScaleLogBase); // buffer for faster baseLog() calculation
  } else
    qDebug() << Q_FUNC_INFO << "Invalid logarithmic scale base (must be greater 1):" << base;
}
void QCPAxis::setScaleRatio (const QCPAxis *otherAxis, doubleratio = 1.0)
Sets the range of this axis to have a certain scale ratio to otherAxis. For example, if ratio is 1, this axis is the yAxis and otherAxis is xAxis, graphs plotted with those axes will appear in a 1:1 ratio, independent of the aspect ratio the axis rect has. This is an operation that changes the range of this axis once, it doesn't fix the scale ratio indefinitely. Consequently calling this function in the constructor won't have the desired effect, since the widget's dimensions aren't defined yet, and a resizeEvent will follow.
Definition at line 4472 of file qcustomplot.cpp.
References mAxisRect, mRange, orientation(), range(), setRange(), and QCPRange::size().
{
  int otherPixelSize, ownPixelSize;
  
  if (otherAxis->orientation() == Qt::Horizontal)
    otherPixelSize = otherAxis->mAxisRect.width();
  else
    otherPixelSize = otherAxis->mAxisRect.height();
  
  if (orientation() == Qt::Horizontal)
    ownPixelSize = mAxisRect.width();
  else
    ownPixelSize = mAxisRect.height();
  
  double newRangeSize = ratio*otherAxis->mRange.size()*ownPixelSize/(double)otherPixelSize;
  setRange(range().center(), newRangeSize, Qt::AlignCenter);
}
void QCPAxis::setScaleType (ScaleTypetype)
Sets whether the axis uses a linear scale or a logarithmic scale. If type is set to stLogarithmic, the logarithm base can be set with setScaleLogBase. In logarithmic axis scaling, major tick marks appear at all powers of the logarithm base. Properties like tick step (setTickStep) don't apply in logarithmic scaling. If you wish a decimal base but less major ticks, consider choosing a logarithm base of 100, 1000 or even higher.
If type is stLogarithmic and the number format (setNumberFormat) uses the 'b' option (beautifully typeset decimal powers), the display usually is '1 [multiplication sign] 10
[superscript] n', which looks unnatural for logarithmic scaling (the '1 [multiplication sign]' part). To only display the decimal power, set the number precision to zero with setNumberPrecision.
Definition at line 3653 of file qcustomplot.cpp.
References mRange, mScaleType, and QCPRange::sanitizedForLogScale().
Referenced by QCPAxis(), and setupFullAxesBox().
{
  mScaleType = type;
  if (mScaleType == stLogarithmic)
    mRange = mRange.sanitizedForLogScale();
}
void QCPAxis::setSelectable (const QCPAxis::SelectableParts &selectable) [slot]
Sets whether the user can (de-)select the parts in selectable by clicking on the QCustomPlot surface. (When QCustomPlot::setInteractions contains iSelectAxes.)
However, even when selectable is set to a value not allowing the selection of a specific part, it is still possible to set the selection of this part manually, by calling setSelected directly.
See also:
SelectablePart, setSelected
Definition at line 3711 of file qcustomplot.cpp.
References mSelectable, and selectable().
Referenced by QCPAxis().
{
  mSelectable = selectable;
}
void QCPAxis::setSelected (const QCPAxis::SelectableParts &selected) [slot]
Sets the selected state of the respective axis parts described by SelectablePart. When a part is selected, it uses a different pen/font.
The entire selection mechanism for axes is handled automatically when QCustomPlot::setInteractions contains iSelectAxes. You only need to call this function when you wish to change the selection state manually.
This function can change the selection state of a part even when setSelectable was set to a value that actually excludes the part.
emits the selectionChanged signal when selected is different from the previous selection state.
See also:
SelectablePart, setSelectable, selectTest, setSelectedBasePen, setSelectedTickPen, setSelectedSubTickPen, setSelectedTickLabelFont, setSelectedLabelFont, setSelectedTickLabelColor, setSelectedLabelColor
Definition at line 3732 of file qcustomplot.cpp.
References mSelected, selected(), and selectionChanged().
Referenced by handleAxisSelection(), and QCPAxis().
{
  if (mSelected != selected)
  {
    mSelected = selected;
    emit selectionChanged(mSelected);
  }
}
void QCPAxis::setSelectedBasePen (const QPen &pen)
Sets the pen that is used to draw the axis base line when selected.
See also:
setBasePen, setSelectable, setSelected, QCustomPlot::setInteractions
Definition at line 4387 of file qcustomplot.cpp.
References mSelectedBasePen, and pen().
Referenced by QCPAxis().
{
  mSelectedBasePen = pen;
}
void QCPAxis::setSelectedLabelColor (const QColor &color)
Sets the color that is used for the axis label when it is selected.
See also:
setLabelColor, setSelectable, setSelected, QCustomPlot::setInteractions
Definition at line 4377 of file qcustomplot.cpp.
References color(), and mSelectedLabelColor.
Referenced by QCPAxis().
{
  mSelectedLabelColor = color;
}
void QCPAxis::setSelectedLabelFont (const QFont &font)
Sets the font that is used for the axis label when it is selected.
See also:
setLabelFont, setSelectable, setSelected, QCustomPlot::setInteractions
Definition at line 4357 of file qcustomplot.cpp.
References mSelectedLabelFont.
Referenced by QCPAxis().
{
  mSelectedLabelFont = font;
}
void QCPAxis::setSelectedSubTickPen (const QPen &pen)
Sets the pen that is used to draw the subticks when selected.
See also:
setSubTickPen, setSelectable, setSelected, QCustomPlot::setInteractions
Definition at line 4407 of file qcustomplot.cpp.
References mSelectedSubTickPen, and pen().
Referenced by QCPAxis().
{
  mSelectedSubTickPen = pen;
}
void QCPAxis::setSelectedTickLabelColor (const QColor &color)
Sets the color that is used for tick labels when they are selected.
See also:
setTickLabelColor, setSelectable, setSelected, QCustomPlot::setInteractions
Definition at line 4367 of file qcustomplot.cpp.
References color(), and mSelectedTickLabelColor.
Referenced by QCPAxis().
{
  mSelectedTickLabelColor = color;
}
void QCPAxis::setSelectedTickLabelFont (const QFont &font)
Sets the font that is used for tick labels when they are selected.
See also:
setTickLabelFont, setSelectable, setSelected, QCustomPlot::setInteractions
Definition at line 4347 of file qcustomplot.cpp.
References mSelectedTickLabelFont.
Referenced by QCPAxis().
{
  mSelectedTickLabelFont = font;
}
void QCPAxis::setSelectedTickPen (const QPen &pen)
Sets the pen that is used to draw the (major) ticks when selected.
See also:
setTickPen, setSelectable, setSelected, QCustomPlot::setInteractions
Definition at line 4397 of file qcustomplot.cpp.
References mSelectedTickPen, and pen().
Referenced by QCPAxis().
{
  mSelectedTickPen = pen;
}
void QCPAxis::setSubGrid (boolshow)
Sets whether the sub grid lines are visible.
See also:
setGrid, setSubGridPen, setZeroLinePen
Definition at line 3888 of file qcustomplot.cpp.
References mGrid.
{
  mGrid->setSubGridVisible(show);
}
void QCPAxis::setSubGridPen (const QPen &pen)
Sets the pen, the sub grid lines are drawn with. (By default, subgrid drawing needs to be enabled first with setSubGrid.)
See also:
setGridPen, setZeroLinePen
Definition at line 4252 of file qcustomplot.cpp.
References mGrid.
{
  mGrid->setSubGridPen(pen);
}
void QCPAxis::setSubTickCount (intcount)
Sets the number of sub ticks in one (major) tick step. A sub tick count of three for example, divides the tick intervals in four sub intervals.
By default, the number of sub ticks is chosen automatically in a reasonable manner as long as the mantissa of the tick step is a multiple of 0.5 (which it is, when setAutoTickStep is enabled). If you want to disable automatic sub ticks and use this function to set the count manually, see setAutoSubTicks.
Definition at line 4210 of file qcustomplot.cpp.
References mSubTickCount.
Referenced by QCPAxis(), and setupFullAxesBox().
{
  mSubTickCount = count;
}
void QCPAxis::setSubTickLength (intinside, intoutside = 0)
Sets the length of the subticks in pixels. inside is the length the subticks will reach inside the plot and outside is the length they will reach outside the plot. If outside is greater than zero, the tick labels will increase their distance to the axis accordingly, so they won't collide with the ticks.
See also:
setTickLength
Definition at line 4222 of file qcustomplot.cpp.
References mSubTickLengthIn, and mSubTickLengthOut.
Referenced by QCPAxis().
{
  mSubTickLengthIn = inside;
  mSubTickLengthOut = outside;
}
void QCPAxis::setSubTickPen (const QPen &pen)
Sets the pen, subtick marks will be drawn with.
See also:
setSubTickCount, setSubTickLength, setBasePen
Definition at line 4282 of file qcustomplot.cpp.
References mSubTickPen, and pen().
Referenced by QCPAxis().
{
  mSubTickPen = pen;
}
void QCPAxis::setTickLabelColor (const QColor &color)
Sets the color of the tick labels, i.e. the numbers drawn next to tick marks.
See also:
setTickLabelFont
Definition at line 4018 of file qcustomplot.cpp.
References color(), and mTickLabelColor.
Referenced by QCPAxis().
{
  mTickLabelColor = color;
}
void QCPAxis::setTickLabelFont (const QFont &font)
Sets the font of the tick labels, i.e. the numbers drawn next to tick marks.
See also:
setTickLabelColor
Definition at line 4008 of file qcustomplot.cpp.
References mTickLabelFont.
Referenced by QCPAxis().
{
  mTickLabelFont = font;
}
void QCPAxis::setTickLabelPadding (intpadding)
Sets the distance between the axis base line (or any tick marks pointing outward) and the tick labels.
See also:
setLabelPadding, setPadding
Definition at line 3983 of file qcustomplot.cpp.
References mTickLabelPadding, and padding().
Referenced by QCPAxis().
{
  mTickLabelPadding = padding;
}
void QCPAxis::setTickLabelRotation (doubledegrees)
Sets the rotation of the tick labels, i.e. the numbers drawn next to tick marks. If degrees is zero, the labels are drawn normally. Else, the tick labels are drawn rotated by degrees clockwise. The specified angle is bound to values from -90 to 90 degrees.
Definition at line 4028 of file qcustomplot.cpp.
References mTickLabelRotation.
Referenced by QCPAxis().
{
  mTickLabelRotation = qBound(-90.0, degrees, 90.0);
}
void QCPAxis::setTickLabels (boolshow)
Sets whether tick labels are displayed.
Definition at line 3974 of file qcustomplot.cpp.
References mTickLabels.
Referenced by QCPAxis(), and setupFullAxesBox().
{
  mTickLabels = show;
}
void QCPAxis::setTickLabelType (LabelTypetype)
Sets whether the tick labels display numbers or dates/times.
If type is set to ltNumber, the format specifications of setNumberFormat apply.
If type is set to ltDateTime, the format specifications of setDateTimeFormat apply.
In QCustomPlot, date/time coordinates are double numbers representing the seconds since 1970-01-01T00:00:00 UTC. This format can be retrieved from QDateTime objects with the QDateTime::toTime_t() function. Since this only gives a resolution of one second, there is also the QDateTime::toMSecsSinceEpoch() function which returns the timespan described above in milliseconds. Divide its return value by 1000.0 to get a value with the format needed for date/time plotting, this time with a resolution of one millisecond.
Definition at line 3998 of file qcustomplot.cpp.
References mTickLabelType.
Referenced by QCPAxis().
{
  mTickLabelType = type;
}
void QCPAxis::setTickLength (intinside, intoutside = 0)
Sets the length of the ticks in pixels. inside is the length the ticks will reach inside the plot and outside is the length they will reach outside the plot. If outside is greater than zero, the tick labels will increase their distance to the axis accordingly, so they won't collide with the ticks.
See also:
setSubTickLength
Definition at line 4195 of file qcustomplot.cpp.
References mTickLengthIn, and mTickLengthOut.
Referenced by QCPAxis().
{
  mTickLengthIn = inside;
  mTickLengthOut = outside;
}
void QCPAxis::setTickPen (const QPen &pen)
Sets the pen, tick marks will be drawn with.
See also:
setTickLength, setBasePen
Definition at line 4273 of file qcustomplot.cpp.
References mTickPen, and pen().
Referenced by QCPAxis().
{
  mTickPen = pen;
}
void QCPAxis::setTicks (boolshow)
Sets whether tick marks are displayed. Setting show to false does not imply, that tick labels are invisible, too. To achieve that, see setTickLabels.
Definition at line 3966 of file qcustomplot.cpp.
References mTicks.
Referenced by QCPAxis(), and setupFullAxesBox().
{
  mTicks = show;
}
void QCPAxis::setTickStep (doublestep)
If setAutoTickStep is set to false, use this function to set the tick step manually. The tick step is the interval between (major) ticks, in plot coordinates.
See also:
setSubTickCount
Definition at line 4151 of file qcustomplot.cpp.
References mTickStep.
Referenced by QCPAxis(), and setupFullAxesBox().
{
  mTickStep = step;
}
void QCPAxis::setTickVector (const QVector< double > &vec)
If you want full control over what ticks (and possibly labels) the axes show, this function is used to set the coordinates at which ticks will appear. setAutoTicks must be disabled, else the provided tick vector will be overwritten with automatically generated tick coordinates. The labels of the ticks can either be generated automatically when setAutoTickLabels is left enabled, or be set manually with setTickVectorLabels, when setAutoTickLabels is disabled.
vec is a vector containing the positions of the ticks.
See also:
setTickVectorLabels
Definition at line 4168 of file qcustomplot.cpp.
References mTickVector.
{
  mTickVector = vec;
}
void QCPAxis::setTickVectorLabels (const QVector< QString > &vec)
If you want full control over what ticks and labels the axes show, this function is used to set a number of QStrings that will be displayed at the tick positions which you need to provide with setTickVector. These two vectors should have the same size. (Note that you need to disable setAutoTicks and setAutoTickLabels first.)
vec is a vector containing the labels of the ticks.
See also:
setTickVector
Definition at line 4183 of file qcustomplot.cpp.
References mTickVectorLabels.
{
  mTickVectorLabels = vec;
}
void QCPAxis::setupTickVectors () [protected], [virtual]
This function is called before the grid and axis is drawn, in order to prepare the tick vector, sub tick vector and tick label vector. If setAutoTicks is set to true, appropriate tick values are determined automatically via generateAutoTicks. If it's set to false, the signal ticksRequest is emitted, which can be used to provide external tick positions. Then the sub tick vectors and tick label vectors are created.
Definition at line 4612 of file qcustomplot.cpp.
References generateAutoTicks(), QCPRange::lower, mAutoTickLabels, mAutoTicks, mDateTimeFormat, mExponentialChar, mGrid, mHighestVisibleTick, mLowestVisibleTick, mNumberFormatChar, mNumberPrecision, QCPLayerable::mParentPlot, mPositiveSignChar, mRange, mSubTickCount, mSubTickVector, mTickLabels, mTickLabelType, mTicks, mTickVector, mTickVectorLabels, QCPRange::size(), ticksRequest(), QCPRange::upper, and visibleTickBounds().
{
  if ((!mTicks && !mTickLabels && !mGrid->visible()) || mRange.size() <= 0) return;
  
  // fill tick vectors, either by auto generating or by notifying user to fill the vectors himself
  if (mAutoTicks)
  {
    generateAutoTicks();
  } else
  {
    emit ticksRequest();
  }
  
  visibleTickBounds(mLowestVisibleTick, mHighestVisibleTick);
  if (mTickVector.isEmpty())
  {
    mSubTickVector.clear();
    return;
  }
  
  // generate subticks between ticks:
  mSubTickVector.resize((mTickVector.size()-1)*mSubTickCount);
  if (mSubTickCount > 0)
  {
    double subTickStep = 0;
    double subTickPosition = 0;
    int subTickIndex = 0;
    bool done = false;
    for (int i=1; i<mTickVector.size(); ++i)
    {
      subTickStep = (mTickVector.at(i)-mTickVector.at(i-1))/(double)(mSubTickCount+1);
      for (int k=1; k<=mSubTickCount; ++k)
      {
        subTickPosition = mTickVector.at(i-1) + k*subTickStep;
        if (subTickPosition < mRange.lower)
          continue;
        if (subTickPosition > mRange.upper)
        {
          done = true;
          break;
        }
        mSubTickVector[subTickIndex] = subTickPosition;
        subTickIndex++;
      }
      if (done) break;
    }
    mSubTickVector.resize(subTickIndex);
  }
  // generate tick labels according to tick positions:
  mExponentialChar = mParentPlot->locale().exponential(); // will be needed when drawing the numbers generated here, in drawTickLabel()
  mPositiveSignChar = mParentPlot->locale().positiveSign(); // will be needed when drawing the numbers generated here, in drawTickLabel()
  if (mAutoTickLabels)
  {
    int vecsize = mTickVector.size();
    mTickVectorLabels.resize(vecsize);
    if (mTickLabelType == ltNumber)
    {
      for (int i=0; i<vecsize; ++i)
        mTickVectorLabels[i] = mParentPlot->locale().toString(mTickVector.at(i), mNumberFormatChar, mNumberPrecision);
    } else if (mTickLabelType == ltDateTime)
    {
      for (int i=0; i<vecsize; ++i)
      {
#if QT_VERSION < QT_VERSION_CHECK(4, 7, 0) // use fromMSecsSinceEpoch function if available, to gain sub-second accuracy on tick labels (e.g. for format "hh:mm:ss:zzz")
        mTickVectorLabels[i] = mParentPlot->locale().toString(QDateTime::fromTime_t(mTickVector.at(i)), mDateTimeFormat);
#else
        mTickVectorLabels[i] = mParentPlot->locale().toString(QDateTime::fromMSecsSinceEpoch(mTickVector.at(i)*1000), mDateTimeFormat);
#endif
      }
    }
  } else // mAutoTickLabels == false
  {
    if (mAutoTicks) // ticks generated automatically, but not ticklabels, so emit ticksRequest here for labels
    {
      emit ticksRequest();
    }
    // make sure provided tick label vector has correct (minimal) length:
    if (mTickVectorLabels.size() < mTickVector.size())
      mTickVectorLabels.resize(mTickVector.size());
  }
}
void QCPAxis::setZeroLinePen (const QPen &pen)
Sets the pen with which a single grid-like line will be drawn at value position zero. The line will be drawn instead of a grid line at that position, and not on top. To disable the drawing of a zero-line, set pen to Qt::NoPen. Then, if setGrid is enabled, a grid line will be drawn instead.
See also:
setGrid, setGridPen
Definition at line 4264 of file qcustomplot.cpp.
References mGrid.
{
  mGrid->setZeroLinePen(pen);
}
bool QCPAxis::subGrid () const [inline]
Definition at line 1711 of file qcustomplot.h.
{ return mGrid->subGridVisible(); }
QPen QCPAxis::subGridPen () const [inline]
Definition at line 1737 of file qcustomplot.h.
{ return mGrid->subGridPen(); }
int QCPAxis::subTickCount () const [inline]
Definition at line 1732 of file qcustomplot.h.
Referenced by setupFullAxesBox().
{ return mSubTickCount; }
int QCPAxis::subTickLengthIn () const [inline]
Definition at line 1733 of file qcustomplot.h.
{ return mSubTickLengthIn; }
int QCPAxis::subTickLengthOut () const [inline]
Definition at line 1734 of file qcustomplot.h.
{ return mSubTickLengthOut; }
QPen QCPAxis::subTickPen () const [inline]
Definition at line 1740 of file qcustomplot.h.
{ return mSubTickPen; }
QColor QCPAxis::tickLabelColor () const [inline]
Definition at line 1722 of file qcustomplot.h.
{ return mTickLabelColor; }
QFont QCPAxis::tickLabelFont () const [inline]
Definition at line 1721 of file qcustomplot.h.
Referenced by QCPAxis().
{ return mTickLabelFont; }
int QCPAxis::tickLabelPadding () const [inline]
Definition at line 1719 of file qcustomplot.h.
{ return mTickLabelPadding; }
double QCPAxis::tickLabelRotation () const [inline]
Definition at line 1723 of file qcustomplot.h.
{ return mTickLabelRotation; }
bool QCPAxis::tickLabels () const [inline]
Definition at line 1718 of file qcustomplot.h.
{ return mTickLabels; }
LabelType QCPAxis::tickLabelType () const [inline]
Definition at line 1720 of file qcustomplot.h.
{ return mTickLabelType; }
int QCPAxis::tickLengthIn () const [inline]
Definition at line 1730 of file qcustomplot.h.
{ return mTickLengthIn; }
int QCPAxis::tickLengthOut () const [inline]
Definition at line 1731 of file qcustomplot.h.
{ return mTickLengthOut; }
QPen QCPAxis::tickPen () const [inline]
Definition at line 1739 of file qcustomplot.h.
{ return mTickPen; }
bool QCPAxis::ticks () const [inline]
Definition at line 1717 of file qcustomplot.h.
Referenced by setupFullAxesBox().
{ return mTicks; }
void QCPAxis::ticksRequest () [signal]
This signal is emitted when setAutoTicks is false and the axis is about to generate tick labels and replot itself. Modifying the tick positions can be done with setTickVector. If you also want to control the tick labels, set setAutoTickLabels to false and also provide the labels with setTickVectorLabels.
If you only want static ticks you probably don't need this signal, since you can just set the tick vector (and possibly tick label vector) once. However, if you want to provide ticks (and maybe labels) dynamically, e.g. depending on the current axis range, connect a slot to this signal and set the vector/vectors there.
Definition at line 1965 of file moc_qcustomplot.cpp.
Referenced by setupTickVectors().
{
    QMetaObject::activate(this, &staticMetaObject, 0, 0);
}
double QCPAxis::tickStep () const [inline]
Definition at line 1727 of file qcustomplot.h.
Referenced by setupFullAxesBox().
{ return mTickStep; }
QVector<double> QCPAxis::tickVector () const [inline]
Definition at line 1728 of file qcustomplot.h.
{ return mTickVector; }
QVector<QString> QCPAxis::tickVectorLabels () const [inline]
Definition at line 1729 of file qcustomplot.h.
{ return mTickVectorLabels; }
void QCPAxis::visibleTickBounds (int &lowIndex, int &highIndex) const [protected]
Returns via lowIndex and highIndex, which ticks in the current tick vector are visible in the current range. The return values are indices of the tick vector, not the positions of the ticks themselves.
The actual use of this function is when we have an externally provided tick vector, which might exceed far beyond the currently displayed range, and would cause unnecessary calculations e.g. of subticks.
Definition at line 5373 of file qcustomplot.cpp.
References QCPRange::lower, mRange, mTickVector, and QCPRange::upper.
Referenced by calculateMargin(), and setupTickVectors().
{
  lowIndex = 0;
  highIndex = -1;
  // make sure only ticks that are in visible range are returned
  for (int i=0; i < mTickVector.size(); ++i)
  {
    lowIndex = i;
    if (mTickVector.at(i) >= mRange.lower) break;
  }
  for (int i=mTickVector.size()-1; i >= 0; --i)
  {
    highIndex = i;
    if (mTickVector.at(i) <= mRange.upper) break;
  }
}
QPen QCPAxis::zeroLinePen () const [inline]
Definition at line 1738 of file qcustomplot.h.
{ return mGrid->zeroLinePen(); }
Friends And Related Function Documentation
friend class QCPGrid [friend]
Definition at line 1902 of file qcustomplot.h.
Referenced by QCPAxis().
Member Data Documentation
bool QCPAxis::mAutoSubTicks [protected]
Definition at line 1849 of file qcustomplot.h.
Referenced by generateAutoTicks(), and setAutoSubTicks().
int QCPAxis::mAutoTickCount [protected]
Definition at line 1846 of file qcustomplot.h.
Referenced by generateAutoTicks(), and setAutoTickCount().
bool QCPAxis::mAutoTickLabels [protected]
Definition at line 1849 of file qcustomplot.h.
Referenced by drawTickLabel(), getMaxTickLabelSize(), setAutoTickLabels(), and setupTickVectors().
bool QCPAxis::mAutoTicks [protected]
Definition at line 1849 of file qcustomplot.h.
Referenced by setAutoTicks(), and setupTickVectors().
bool QCPAxis::mAutoTickStep [protected]
Definition at line 1849 of file qcustomplot.h.
Referenced by generateAutoTicks(), and setAutoTickStep().
QRect QCPAxis::mAxisRect [protected]
Definition at line 1836 of file qcustomplot.h.
Referenced by coordToPixel(), draw(), drawGridLines(), drawSubGridLines(), drawTickLabel(), pixelToCoord(), setAxisRect(), and setScaleRatio().
QRect QCPAxis::mAxisSelectionBox [protected]
Definition at line 1855 of file qcustomplot.h.
Referenced by draw(), and selectTest().
AxisType QCPAxis::mAxisType [protected]
Definition at line 1842 of file qcustomplot.h.
Referenced by draw(), drawTickLabel(), and setAxisType().
QPen QCPAxis::mBasePen [protected]
Definition at line 1837 of file qcustomplot.h.
Referenced by getBasePen(), and setBasePen().
QString QCPAxis::mDateTimeFormat [protected]
Definition at line 1834 of file qcustomplot.h.
Referenced by setDateTimeFormat(), and setupTickVectors().
QChar QCPAxis::mExponentialChar [protected]
Definition at line 1860 of file qcustomplot.h.
Referenced by getMaxTickLabelSize(), and setupTickVectors().
QCPGrid* QCPAxis::mGrid [protected]
Definition at line 1858 of file qcustomplot.h.
Referenced by QCPAxis(), setAntialiasedGrid(), setAntialiasedSubGrid(), setAntialiasedZeroLine(), setGrid(), setGridPen(), setSubGrid(), setSubGridPen(), setupTickVectors(), setZeroLinePen(), and ~QCPAxis().
int QCPAxis::mHighestVisibleTick [protected]
Definition at line 1865 of file qcustomplot.h.
Referenced by draw(), drawGridLines(), QCPAxis(), and setupTickVectors().
QString QCPAxis::mLabel [protected]
Definition at line 1835 of file qcustomplot.h.
Referenced by calculateMargin(), draw(), and setLabel().
QColor QCPAxis::mLabelColor [protected]
Definition at line 1839 of file qcustomplot.h.
Referenced by getLabelColor(), and setLabelColor().
QFont QCPAxis::mLabelFont [protected]
Definition at line 1838 of file qcustomplot.h.
Referenced by calculateMargin(), getLabelFont(), and setLabelFont().
int QCPAxis::mLabelPadding [protected]
Definition at line 1847 of file qcustomplot.h.
Referenced by calculateMargin(), draw(), and setLabelPadding().
QRect QCPAxis::mLabelSelectionBox [protected]
Definition at line 1855 of file qcustomplot.h.
Referenced by draw(), and selectTest().
int QCPAxis::mLowestVisibleTick [protected]
Definition at line 1865 of file qcustomplot.h.
Referenced by draw(), drawGridLines(), QCPAxis(), and setupTickVectors().
bool QCPAxis::mNumberBeautifulPowers [protected]
Definition at line 1863 of file qcustomplot.h.
Referenced by drawTickLabel(), getMaxTickLabelSize(), numberFormat(), and setNumberFormat().
char QCPAxis::mNumberFormatChar [protected]
Definition at line 1862 of file qcustomplot.h.
Referenced by numberFormat(), setNumberFormat(), and setupTickVectors().
bool QCPAxis::mNumberMultiplyCross [protected]
Definition at line 1863 of file qcustomplot.h.
Referenced by drawTickLabel(), getMaxTickLabelSize(), numberFormat(), and setNumberFormat().
int QCPAxis::mNumberPrecision [protected]
Definition at line 1861 of file qcustomplot.h.
Referenced by setNumberPrecision(), and setupTickVectors().
Qt::Orientation QCPAxis::mOrientation [protected]
Definition at line 1864 of file qcustomplot.h.
Referenced by setAxisType().
int QCPAxis::mPadding [protected]
Definition at line 1847 of file qcustomplot.h.
Referenced by calculateMargin(), and setPadding().
QChar QCPAxis::mPositiveSignChar [protected]
Definition at line 1860 of file qcustomplot.h.
Referenced by drawTickLabel(), getMaxTickLabelSize(), and setupTickVectors().
QCPRange QCPAxis::mRange [protected]
Definition at line 1833 of file qcustomplot.h.
Referenced by coordToPixel(), drawGridLines(), generateAutoTicks(), moveRange(), pixelToCoord(), scaleRange(), setRange(), setRangeLower(), setRangeUpper(), setScaleRatio(), setScaleType(), setupTickVectors(), and visibleTickBounds().
bool QCPAxis::mRangeReversed [protected]
Definition at line 1850 of file qcustomplot.h.
Referenced by coordToPixel(), pixelToCoord(), and setRangeReversed().
double QCPAxis::mScaleLogBase [protected]
Definition at line 1844 of file qcustomplot.h.
Referenced by basePow(), generateAutoTicks(), and setScaleLogBase().
double QCPAxis::mScaleLogBaseLogInv [protected]
Definition at line 1844 of file qcustomplot.h.
Referenced by baseLog(), and setScaleLogBase().
ScaleType QCPAxis::mScaleType [protected]
Definition at line 1841 of file qcustomplot.h.
Referenced by coordToPixel(), drawTickLabel(), generateAutoTicks(), getMaxTickLabelSize(), mouseMoveEvent(), moveRange(), pixelToCoord(), scaleRange(), setRange(), setRangeLower(), setRangeUpper(), and setScaleType().
SelectableParts QCPAxis::mSelectable [protected]
Definition at line 1851 of file qcustomplot.h.
Referenced by setSelectable().
SelectableParts QCPAxis::mSelected [protected]
Definition at line 1851 of file qcustomplot.h.
Referenced by getBasePen(), getLabelColor(), getLabelFont(), getSubTickPen(), getTickLabelColor(), getTickLabelFont(), getTickPen(), and setSelected().
QPen QCPAxis::mSelectedBasePen [protected]
Definition at line 1854 of file qcustomplot.h.
Referenced by getBasePen(), and setSelectedBasePen().
QColor QCPAxis::mSelectedLabelColor [protected]
Definition at line 1853 of file qcustomplot.h.
Referenced by getLabelColor(), and setSelectedLabelColor().
QFont QCPAxis::mSelectedLabelFont [protected]
Definition at line 1852 of file qcustomplot.h.
Referenced by getLabelFont(), and setSelectedLabelFont().
QPen QCPAxis::mSelectedSubTickPen [protected]
Definition at line 1854 of file qcustomplot.h.
Referenced by getSubTickPen(), and setSelectedSubTickPen().
QColor QCPAxis::mSelectedTickLabelColor [protected]
Definition at line 1853 of file qcustomplot.h.
Referenced by getTickLabelColor(), and setSelectedTickLabelColor().
QFont QCPAxis::mSelectedTickLabelFont [protected]
Definition at line 1852 of file qcustomplot.h.
Referenced by getTickLabelFont(), and setSelectedTickLabelFont().
QPen QCPAxis::mSelectedTickPen [protected]
Definition at line 1854 of file qcustomplot.h.
Referenced by getTickPen(), and setSelectedTickPen().
int QCPAxis::mSubTickCount [protected]
Definition at line 1845 of file qcustomplot.h.
Referenced by calculateAutoSubTickCount(), draw(), generateAutoTicks(), setSubTickCount(), and setupTickVectors().
int QCPAxis::mSubTickLengthIn [protected]
Definition at line 1845 of file qcustomplot.h.
Referenced by draw(), and setSubTickLength().
int QCPAxis::mSubTickLengthOut [protected]
Definition at line 1845 of file qcustomplot.h.
Referenced by calculateMargin(), draw(), and setSubTickLength().
QPen QCPAxis::mSubTickPen [protected]
Definition at line 1837 of file qcustomplot.h.
Referenced by getSubTickPen(), and setSubTickPen().
QVector<double> QCPAxis::mSubTickVector [protected]
Definition at line 1859 of file qcustomplot.h.
Referenced by draw(), drawSubGridLines(), and setupTickVectors().
QColor QCPAxis::mTickLabelColor [protected]
Definition at line 1839 of file qcustomplot.h.
Referenced by getTickLabelColor(), and setTickLabelColor().
QFont QCPAxis::mTickLabelFont [protected]
Definition at line 1838 of file qcustomplot.h.
Referenced by calculateMargin(), getTickLabelFont(), and setTickLabelFont().
int QCPAxis::mTickLabelPadding [protected]
Definition at line 1847 of file qcustomplot.h.
Referenced by calculateMargin(), draw(), and setTickLabelPadding().
double QCPAxis::mTickLabelRotation [protected]
Definition at line 1848 of file qcustomplot.h.
Referenced by drawTickLabel(), getMaxTickLabelSize(), and setTickLabelRotation().
bool QCPAxis::mTickLabels [protected]
Definition at line 1849 of file qcustomplot.h.
Referenced by calculateMargin(), draw(), setTickLabels(), and setupTickVectors().
QRect QCPAxis::mTickLabelsSelectionBox [protected]
Definition at line 1855 of file qcustomplot.h.
Referenced by draw(), and selectTest().
LabelType QCPAxis::mTickLabelType [protected]
Definition at line 1840 of file qcustomplot.h.
Referenced by drawTickLabel(), getMaxTickLabelSize(), setTickLabelType(), and setupTickVectors().
int QCPAxis::mTickLengthIn [protected]
Definition at line 1845 of file qcustomplot.h.
Referenced by draw(), and setTickLength().
int QCPAxis::mTickLengthOut [protected]
Definition at line 1845 of file qcustomplot.h.
Referenced by calculateMargin(), draw(), and setTickLength().
QPen QCPAxis::mTickPen [protected]
Definition at line 1837 of file qcustomplot.h.
Referenced by getTickPen(), and setTickPen().
bool QCPAxis::mTicks [protected]
Definition at line 1849 of file qcustomplot.h.
Referenced by draw(), setTicks(), and setupTickVectors().
double QCPAxis::mTickStep [protected]
Definition at line 1843 of file qcustomplot.h.
Referenced by generateAutoTicks(), and setTickStep().
QVector<double> QCPAxis::mTickVector [protected]
Definition at line 1831 of file qcustomplot.h.
Referenced by draw(), drawGridLines(), generateAutoTicks(), setTickVector(), setupTickVectors(), and visibleTickBounds().
QVector<QString> QCPAxis::mTickVectorLabels [protected]
Definition at line 1832 of file qcustomplot.h.
Referenced by calculateMargin(), draw(), setTickVectorLabels(), and setupTickVectors().
Author
Generated automatically by Doxygen for AQ0X from the source code.