QCPAbstractLegendItem
NAME
QCPAbstractLegendItem -
The abstract base class for all items in a QCPLegend.
SYNOPSIS
#include <qcustomplot.h>
Inherits QObject.
Inherited by QCPPlottableLegendItem.
Signals
void selectionChanged (bool selected)
This signal is emitted when the selection state of this legend item has changed, either by user interaction or by a direct call to setSelected.
Public Member Functions
QCPAbstractLegendItem (QCPLegend *parent)
Constructs a QCPAbstractLegendItem and associates it with the QCPLegend parent.
virtual ~QCPAbstractLegendItem ()
bool antialiased () const
QFont font () const
QColor textColor () const
QFont selectedFont () const
QColor selectedTextColor () const
bool selectable () const
bool selected () const
void setAntialiased (bool enabled)
Sets whether this legend item is drawn antialiased or not.
void setFont (const QFont &font)
Sets the default font of this specific legend item to font.
void setTextColor (const QColor &color)
Sets the default text color of this specific legend item to color.
void setSelectedFont (const QFont &font)
When this legend item is selected, font is used to draw generic text, instead of the normal font set with setFont.
void setSelectedTextColor (const QColor &color)
When this legend item is selected, color is used to draw generic text, instead of the normal color set with setTextColor.
void setSelectable (bool selectable)
Sets whether this specific legend item is selectable.
void setSelected (bool selected)
Sets whether this specific legend item is selected.
Protected Member Functions
virtual void draw (QCPPainter *painter, const QRect &rect) const =0
Draws this legend item with painter inside the specified rect.
virtual QSize size (const QSize &targetSize) const =0
Returns the size this item occupies in the legend.
void applyAntialiasingHint (QCPPainter *painter) const
Protected Attributes
QCPLegend * mParentLegend
bool mAntialiased
QFont mFont
QColor mTextColor
QFont mSelectedFont
QColor mSelectedTextColor
bool mSelectable
bool mSelected
Detailed Description
The abstract base class for all items in a QCPLegend.
It defines a very basic interface to items in a QCPLegend. For representing plottables in the legend, the subclass QCPPlottableLegendItem is more suitable.
Only derive directly from this class when you need absolute freedom (i.e. a legend item that's not associated with a plottable).
You must implement the following pure virtual functions:
draw
size
You inherit the following members you may use: QCPLegend *mParentLegend A pointer to the parent QCPLegend. QFont mFont The generic font of the item. You should use this font for all or at least the most prominent text of the item.
Definition at line 1348 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPAbstractLegendItem::QCPAbstractLegendItem (QCPLegend *parent)
Constructs a QCPAbstractLegendItem and associates it with the QCPLegend parent. This does not cause the item to be added to parent, so QCPLegend::addItem must be called separately.
Definition at line 8895 of file qcustomplot.cpp.
                                                              :
  QObject(parent),
  mParentLegend(parent),
  mAntialiased(false),
  mFont(parent->font()),
  mTextColor(parent->textColor()),
  mSelectedFont(parent->selectedFont()),
  mSelectedTextColor(parent->selectedTextColor()),
  mSelectable(true),
  mSelected(false)
{
}
virtual QCPAbstractLegendItem::~QCPAbstractLegendItem () [inline], [virtual]
Definition at line 1353 of file qcustomplot.h.
{}
Member Function Documentation
bool QCPAbstractLegendItem::antialiased () const [inline]
Definition at line 1356 of file qcustomplot.h.
{ return mAntialiased; }
void QCPAbstractLegendItem::applyAntialiasingHint (QCPPainter *painter) const [protected]
Sets the QPainter::Antialiasing render hint on the provided painter, depending on the setAntialiased state of this legend item as well as the overrides QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements.
Definition at line 8996 of file qcustomplot.cpp.
References QCP::aeLegendItems, mAntialiased, mParentLegend, QCPLayerable::mParentPlot, and QCPPainter::setAntialiasing().
{
  if (mParentLegend->mParentPlot->notAntialiasedElements().testFlag(QCP::aeLegendItems))
    painter->setAntialiasing(false);
  else if (mParentLegend->mParentPlot->antialiasedElements().testFlag(QCP::aeLegendItems))
    painter->setAntialiasing(true);
  else
    painter->setAntialiasing(mAntialiased);
}
void QCPAbstractLegendItem::draw (QCPPainter *painter, const QRect &rect) const [protected], [pure virtual]
Draws this legend item with painter inside the specified rect. The rect typically has the size which was returned from a preceding size call.
Implemented in QCPPlottableLegendItem.
QFont QCPAbstractLegendItem::font () const [inline]
Definition at line 1357 of file qcustomplot.h.
Referenced by setFont(), and setSelectedFont().
{ return mFont; }
bool QCPAbstractLegendItem::selectable () const [inline]
Definition at line 1361 of file qcustomplot.h.
Referenced by QCPLegend::handleLegendSelection(), and setSelectable().
{ return mSelectable; }
bool QCPAbstractLegendItem::selected () const [inline]
Definition at line 1362 of file qcustomplot.h.
Referenced by QCPLegend::handleLegendSelection(), and setSelected().
{ return mSelected; }
QFont QCPAbstractLegendItem::selectedFont () const [inline]
Definition at line 1359 of file qcustomplot.h.
{ return mSelectedFont; }
QColor QCPAbstractLegendItem::selectedTextColor () const [inline]
Definition at line 1360 of file qcustomplot.h.
{ return mSelectedTextColor; }
void QCPAbstractLegendItem::selectionChanged (boolselected) [signal]
This signal is emitted when the selection state of this legend item has changed, either by user interaction or by a direct call to setSelected.
Definition at line 1318 of file moc_qcustomplot.cpp.
Referenced by setSelected().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 0, _a);
}
void QCPAbstractLegendItem::setAntialiased (boolenabled)
Sets whether this legend item is drawn antialiased or not. Note that this setting may be overridden by QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements.
Definition at line 8914 of file qcustomplot.cpp.
References mAntialiased.
{
  mAntialiased = enabled;
}
void QCPAbstractLegendItem::setFont (const QFont &font)
Sets the default font of this specific legend item to font.
See also:
setTextColor, QCPLegend::setFont
Definition at line 8924 of file qcustomplot.cpp.
References font(), and mFont.
{
  mFont = font;
}
void QCPAbstractLegendItem::setSelectable (boolselectable)
Sets whether this specific legend item is selectable.
See also:
setSelected, QCustomPlot::setInteractions
Definition at line 8966 of file qcustomplot.cpp.
References mSelectable, and selectable().
{
  mSelectable = selectable;
}
void QCPAbstractLegendItem::setSelected (boolselected)
Sets whether this specific legend item is selected. The selection state of the parent QCPLegend is updated correspondingly.
It is possible to set the selection state of this item by calling this function directly, even if setSelectable is set to false.
See also:
setSelectable, QCustomPlot::setInteractions
Definition at line 8980 of file qcustomplot.cpp.
References mParentLegend, mSelected, selected(), selectionChanged(), and QCPLegend::updateSelectionState().
Referenced by QCPLegend::handleLegendSelection().
{
  if (mSelected != selected)
  {
    mSelected = selected;
    emit selectionChanged(mSelected);
    mParentLegend->updateSelectionState();
  }
}
void QCPAbstractLegendItem::setSelectedFont (const QFont &font)
When this legend item is selected, font is used to draw generic text, instead of the normal font set with setFont.
See also:
setFont, QCPLegend::setSelectedFont
Definition at line 8945 of file qcustomplot.cpp.
References font(), and mSelectedFont.
{
  mSelectedFont = font;
}
void QCPAbstractLegendItem::setSelectedTextColor (const QColor &color)
When this legend item is selected, color is used to draw generic text, instead of the normal color set with setTextColor.
See also:
setTextColor, QCPLegend::setSelectedTextColor
Definition at line 8956 of file qcustomplot.cpp.
References color(), and mSelectedTextColor.
{
  mSelectedTextColor = color;
}
void QCPAbstractLegendItem::setTextColor (const QColor &color)
Sets the default text color of this specific legend item to color.
See also:
setFont, QCPLegend::setTextColor
Definition at line 8934 of file qcustomplot.cpp.
References color(), and mTextColor.
{
  mTextColor = color;
}
QSize QCPAbstractLegendItem::size (const QSize &targetSize) const [protected], [pure virtual]
Returns the size this item occupies in the legend. The legend will adapt its layout with the help of this function. If this legend item can have a variable width (e.g. auto-wrapping text), this function tries to find a size with a width close to the width of targetSize. The height of targetSize only may have meaning in specific sublasses. Typically, it's ignored.
Implemented in QCPPlottableLegendItem.
QColor QCPAbstractLegendItem::textColor () const [inline]
Definition at line 1358 of file qcustomplot.h.
{ return mTextColor; }
Member Data Documentation
bool QCPAbstractLegendItem::mAntialiased [protected]
Definition at line 1378 of file qcustomplot.h.
Referenced by applyAntialiasingHint(), and setAntialiased().
QFont QCPAbstractLegendItem::mFont [protected]
Definition at line 1379 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getFont(), and setFont().
QCPLegend* QCPAbstractLegendItem::mParentLegend [protected]
Definition at line 1377 of file qcustomplot.h.
Referenced by applyAntialiasingHint(), QCPPlottableLegendItem::draw(), QCPPlottableLegendItem::getIconBorderPen(), setSelected(), and QCPPlottableLegendItem::size().
bool QCPAbstractLegendItem::mSelectable [protected]
Definition at line 1383 of file qcustomplot.h.
Referenced by setSelectable().
bool QCPAbstractLegendItem::mSelected [protected]
Definition at line 1383 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getFont(), QCPPlottableLegendItem::getIconBorderPen(), QCPPlottableLegendItem::getTextColor(), and setSelected().
QFont QCPAbstractLegendItem::mSelectedFont [protected]
Definition at line 1381 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getFont(), and setSelectedFont().
QColor QCPAbstractLegendItem::mSelectedTextColor [protected]
Definition at line 1382 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getTextColor(), and setSelectedTextColor().
QColor QCPAbstractLegendItem::mTextColor [protected]
Definition at line 1380 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getTextColor(), and setTextColor().
Author
Generated automatically by Doxygen for AQ0X from the source code.