QCPAbstractItem
NAME
QCPAbstractItem -
The abstract base class for all items in a plot.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPLayerable.
Inherited by QCPItemBracket, QCPItemCurve, QCPItemEllipse, QCPItemLine, QCPItemPixmap, QCPItemRect, QCPItemStraightLine, QCPItemText, and QCPItemTracer.
Signals
void selectionChanged (bool selected)
This signal is emitted when the selection state of this item has changed, either by user interaction or by a direct call to setSelected.
Public Member Functions
QCPAbstractItem (QCustomPlot *parentPlot)
Base class constructor which initializes base class members.
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxis * clipKeyAxis () const
QCPAxis * clipValueAxis () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
Sets whether the item shall be clipped to the axis rect or whether it shall be visible on the entire QCustomPlot.
void setClipAxes (QCPAxis *keyAxis, QCPAxis *valueAxis)
Sets both clip axes.
void setClipKeyAxis (QCPAxis *axis)
Sets the clip key axis.
void setClipValueAxis (QCPAxis *axis)
Sets the clip value axis.
void setSelectable (bool selectable)
Sets whether the user can (de-)select this item by clicking on the QCustomPlot surface.
void setSelected (bool selected)
Sets whether this item is selected or not.
virtual double selectTest (const QPointF &pos) const =0
This function is used to decide whether a click hits an item or not.
QList< QCPItemPosition * > positions () const
Returns all positions of the item in a list.
QList< QCPItemAnchor * > anchors () const
Returns all anchors of the item in a list.
QCPItemPosition * position (const QString &name) const
Returns the QCPItemPosition with the specified name.
QCPItemAnchor * anchor (const QString &name) const
Returns the QCPItemAnchor with the specified name.
bool hasAnchor (const QString &name) const
Returns whether this item has an anchor with the specified name.
Protected Member Functions
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void draw (QCPPainter *painter)=0
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
double rectSelectTest (const QRectF &rect, const QPointF &pos, bool filledRect) const
virtual QPointF anchorPixelPoint (int anchorId) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
Protected Attributes
bool mClipToAxisRect
QCPAxis * mClipKeyAxis
QCPAxis * mClipValueAxis
bool mSelectable
bool mSelected
QList< QCPItemPosition * > mPositions
QList< QCPItemAnchor * > mAnchors
Friends
class QCPItemAnchor
Detailed Description
The abstract base class for all items in a plot.
In QCustomPlot, items are supplemental graphical elements that are neither plottables (QCPAbstractPlottable) nor axes (QCPAxis). While plottables are always tied to two axes and thus plot coordinates, items can also be placed in absolute coordinates independent of any axes. Each specific item has at least one QCPItemPosition member which controls the positioning. Some items are defined by more than one coordinate and thus have two or more QCPItemPosition members (For example, QCPItemRect has topLeft and bottomRight).
This abstract base class defines a very basic interface like visibility and clipping. Since this class is abstract, it can't be instantiated. Use one of the subclasses or create a subclass yourself to create new items.
The built-in items are: QCPItemLineA line defined by a start and an end point. May have different ending styles on each side (e.g. arrows). QCPItemStraightLineA straight line defined by a start and a direction point. Unlike QCPItemLine, the straight line is infinitely long and has no endings. QCPItemCurveA curve defined by start, end and two intermediate control points. May have different ending styles on each side (e.g. arrows). QCPItemRectA rectangle QCPItemEllipseAn ellipse QCPItemPixmapAn arbitrary pixmap QCPItemTextA text label QCPItemBracketA bracket which may be used to reference/highlight certain parts in the plot. QCPItemTracerAn item that can be attached to a QCPGraph and sticks to its data points, given a key coordinate.
Using items
First you instantiate the item you want to use and add it to the plot:
QCPItemLine *line = new QCPItemLine(customPlot);
customPlot->addItem(line);
 by default, the positions of the item are bound to the x- and y-Axis of the plot. So we can just set the plot coordinates where the line should start/end:
line->start->setCoords(-0.1, 0.8);
line->end->setCoords(1.1, 0.2);
 If we wanted the line to be positioned not in plot coordinates but a different coordinate system, e.g. absolute pixel positions on the QCustomPlot surface, we would have changed the position type like this:
line->start->setType(QCPItemPosition::ptAbsolute);
line->end->setType(QCPItemPosition::ptAbsolute);
 Then we can set the coordinates, this time in pixels:
line->start->setCoords(100, 200);
line->end->setCoords(450, 320);
Creating own items
To create an own item, you implement a subclass of QCPAbstractItem. These are the pure virtual functions, you must implement:
selectTest
draw
See the documentation of those functions for what they need to do.
Allowing the item to be positioned
As mentioned, item positions are represented by QCPItemPosition members. Let's assume the new item shall have only one coordinate as its position (as opposed to two like a rect or multiple like a polygon). You then add a public member of type QCPItemPosition like so:
QCPItemPosition * const myPosition;
the const makes sure the pointer itself can't be modified from the user of your new item (the QCPItemPosition instance it points to, can be modified, of course). The initialization of this pointer is made easy with the createPosition function. Just assign the return value of this function to each QCPItemPosition in the constructor of your item. createPosition takes a string which is the name of the position, typically this is identical to the variable name. For example, the constructor of QCPItemExample could look like this:
QCPItemExample::QCPItemExample(QCustomPlot *parentPlot) :
  QCPAbstractItem(parentPlot),
  myPosition(createPosition("myPosition"))
{
  // other constructor code
}
The draw function
Your implementation of the draw function should check whether the item is visible (mVisible) and then draw the item. You can retrieve its position in pixel coordinates from the position member(s) via QCPItemPosition::pixelPoint.
To optimize performance you should calculate a bounding rect first (don't forget to take the pen width into account), check whether it intersects the clipRect, and only draw the item at all if this is the case.
The selectTest function
Your implementation of the selectTest function may use the helpers distSqrToLine and rectSelectTest. With these, the implementation of the selection test becomes significantly simpler for most items.
Providing anchors
Providing anchors (QCPItemAnchor) starts off like adding a position. First you create a public member, e.g.
QCPItemAnchor * const bottom;
and create it in the constructor with the createAnchor function, assigning it a name and an anchor id (an integer enumerating all anchors on the item, you may create an own enum for this). Since anchors can be placed anywhere, relative to the item's position(s), your item needs to provide the position of every anchor with the reimplementation of the anchorPixelPoint(int anchorId) function.
In essence the QCPItemAnchor is merely an intermediary that itself asks your item for the pixel position when anything attached to the anchor needs to know the coordinates.
Definition at line 842 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPAbstractItem::QCPAbstractItem (QCustomPlot *parentPlot)
Base class constructor which initializes base class members.
Definition at line 11024 of file qcustomplot.cpp.
                                                        :
  QCPLayerable(parentPlot),
  mClipToAxisRect(true),
  mClipKeyAxis(parentPlot->xAxis),
  mClipValueAxis(parentPlot->yAxis),
  mSelectable(true),
  mSelected(false)
{
}
QCPAbstractItem::~QCPAbstractItem () [virtual]
Definition at line 11034 of file qcustomplot.cpp.
References mAnchors.
{
  // don't delete mPositions because every position is also an anchor and thus in mAnchors
  qDeleteAll(mAnchors);
}
Member Function Documentation
QCPItemAnchor * QCPAbstractItem::anchor (const QString &name) const
Returns the QCPItemAnchor with the specified name. If this item doesn't have an anchor by that name, returns 0.
This function provides an alternative way to access item anchors. Normally, you access anchors direcly by their member pointers (which typically have the same variable name as name).
See also:
anchors, position
Definition at line 11152 of file qcustomplot.cpp.
References mAnchors.
{
  for (int i=0; i<mAnchors.size(); ++i)
  {
    if (mAnchors.at(i)->name() == name)
      return mAnchors.at(i);
  }
  qDebug() << Q_FUNC_INFO << "anchor with name not found:" << name;
  return 0;
}
QPointF QCPAbstractItem::anchorPixelPoint (intanchorId) const [protected], [virtual]
Returns the pixel position of the anchor with Id anchorId. This function must be reimplemented in item subclasses if they want to provide anchors (QCPItemAnchor).
For example, if the item has two anchors with id 0 and 1, this function takes one of these anchor ids and returns the respective pixel points of the specified anchor.
See also:
createAnchor
Reimplemented in QCPItemBracket, QCPItemText, QCPItemPixmap, QCPItemRect, and QCPItemEllipse.
Definition at line 11308 of file qcustomplot.cpp.
Referenced by QCPItemAnchor::pixelPoint().
{
  qDebug() << Q_FUNC_INFO << "called on item which shouldn't have any anchors (anchorPixelPos not reimplemented). anchorId" << anchorId;
  return QPointF();
}
QList< QCPItemAnchor * > QCPAbstractItem::anchors () const [inline]
Returns all anchors of the item in a list. Note that since a position (QCPItemPosition) is always also an anchor, the list will also contain the positions of this item.
See also:
positions, anchor
Definition at line 867 of file qcustomplot.h.
{ return mAnchors; }
void QCPAbstractItem::applyDefaultAntialiasingHint (QCPPainter *painter) const [protected], [virtual]
A convenience function to easily set the QPainter::Antialiased hint on the provided painter before drawing item lines.
This is the antialiasing state the painter passed to the draw method is in by default.
This function takes into account the local setting of the antialiasing flag as well as the overrides set e.g. with QCustomPlot::setNotAntialiasedElements.
See also:
setAntialiased
Implements QCPLayerable.
Definition at line 11217 of file qcustomplot.cpp.
References QCP::aeItems, QCPLayerable::applyAntialiasingHint(), and QCPLayerable::mAntialiased.
{
  applyAntialiasingHint(painter, mAntialiased, QCP::aeItems);
}
QCPAxis* QCPAbstractItem::clipKeyAxis () const [inline]
Definition at line 851 of file qcustomplot.h.
{ return mClipKeyAxis; }
QRect QCPAbstractItem::clipRect () const [protected], [virtual]
Returns the rect the visual representation of this item is clipped to. This depends on the current setting of setClipToAxisRect aswell as the clip axes set with setClipAxes.
If the item is not clipped to an axis rect, the QCustomPlot::viewport rect is returned.
See also:
draw
Reimplemented from QCPLayerable.
Definition at line 11190 of file qcustomplot.cpp.
References QCPAxis::axisRect(), mClipKeyAxis, mClipToAxisRect, mClipValueAxis, and QCPLayerable::mParentPlot.
Referenced by QCPItemStraightLine::draw(), QCPItemLine::draw(), QCPItemEllipse::draw(), QCPItemRect::draw(), QCPItemPixmap::draw(), QCPItemText::draw(), QCPItemCurve::draw(), QCPItemBracket::draw(), QCPItemTracer::draw(), itemAt(), and QCPItemTracer::selectTest().
{
  if (mClipToAxisRect)
  {
    if (mClipKeyAxis && mClipValueAxis)
      return mClipKeyAxis->axisRect() | mClipValueAxis->axisRect();
    else if (mClipKeyAxis)
      return mClipKeyAxis->axisRect();
    else if (mClipValueAxis)
      return mClipValueAxis->axisRect();
  }
  
  return mParentPlot->viewport();
}
bool QCPAbstractItem::clipToAxisRect () const [inline]
Definition at line 850 of file qcustomplot.h.
Referenced by itemAt().
{ return mClipToAxisRect; }
QCPAxis* QCPAbstractItem::clipValueAxis () const [inline]
Definition at line 852 of file qcustomplot.h.
{ return mClipValueAxis; }
QCPItemAnchor * QCPAbstractItem::createAnchor (const QString &name, intanchorId) [protected]
Creates a QCPItemAnchor, registers it with this item and returns a pointer to it. The specified name must be a unique string that is usually identical to the variable name of the anchor member (This is needed to provide the name based anchor access to anchors).
The anchorId must be a number identifying the created anchor. It is recommended to create an enum (e.g. 'AnchorIndex') for this on each item that uses anchors. This id is used by the anchor to identify itself when it calls QCPAbstractItem::anchorPixelPoint. That function then returns the correct pixel coordinates for the passed anchor id.
Don't delete anchors created by this function manually, as the item will take care of it.
Use this function in the constructor (initialization list) of the specific item subclass to create each anchor member. Don't create QCPItemAnchors with new yourself, because then they won't be registered with the item properly.
See also:
createPosition
Definition at line 11360 of file qcustomplot.cpp.
References hasAnchor(), mAnchors, QCPLayerable::mParentPlot, and QCPItemAnchor.
{
  if (hasAnchor(name))
    qDebug() << Q_FUNC_INFO << "anchor/position with name exists already:" << name;
  QCPItemAnchor *newAnchor = new QCPItemAnchor(mParentPlot, this, name, anchorId);
  mAnchors.append(newAnchor);
  return newAnchor;
}
QCPItemPosition * QCPAbstractItem::createPosition (const QString &name) [protected]
Creates a QCPItemPosition, registers it with this item and returns a pointer to it. The specified name must be a unique string that is usually identical to the variable name of the position member (This is needed to provide the name based position access to positions).
Don't delete positions created by this function manually, as the item will take care of it.
Use this function in the constructor (initialization list) of the specific item subclass to create each position member. Don't create QCPItemPositions with new yourself, because they won't be registered with the item properly.
See also:
createAnchor
Definition at line 11328 of file qcustomplot.cpp.
References hasAnchor(), mAnchors, QCPLayerable::mParentPlot, mPositions, QCPItemPosition::ptPlotCoords, QCPItemPosition::setAxes(), QCPItemPosition::setCoords(), and QCPItemPosition::setType().
{
  if (hasAnchor(name))
    qDebug() << Q_FUNC_INFO << "anchor/position with name exists already:" << name;
  QCPItemPosition *newPosition = new QCPItemPosition(mParentPlot, this, name);
  mPositions.append(newPosition);
  mAnchors.append(newPosition); // every position is also an anchor
  newPosition->setType(QCPItemPosition::ptPlotCoords);
  newPosition->setAxes(mParentPlot->xAxis, mParentPlot->yAxis);
  newPosition->setCoords(0, 0);
  return newPosition;
}
double QCPAbstractItem::distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const [protected]
Finds the shortest squared distance of point to the line segment defined by start and end.
This function may be used to help with the implementation of the selectTest function for specific items.
Note:
This function is identical to QCPAbstractPlottable::distSqrToLine
See also:
rectSelectTest
Definition at line 11234 of file qcustomplot.cpp.
Referenced by rectSelectTest(), QCPItemLine::selectTest(), QCPItemCurve::selectTest(), QCPItemBracket::selectTest(), and QCPItemTracer::selectTest().
{
  QVector2D a(start);
  QVector2D b(end);
  QVector2D p(point);
  QVector2D v(b-a);
  
  double vLengthSqr = v.lengthSquared();
  if (!qFuzzyIsNull(vLengthSqr))
  {
    double mu = QVector2D::dotProduct(p-a, v)/vLengthSqr;
    if (mu < 0)
      return (a-p).lengthSquared();
    else if (mu > 1)
      return (b-p).lengthSquared();
    else
      return ((a + mu*v)-p).lengthSquared();
  } else
    return (a-p).lengthSquared();
}
void QCPAbstractItem::draw (QCPPainter *painter) [protected], [pure virtual]
Draws this item with the provided painter. Called by QCustomPlot::draw on all its visible items.
The cliprect of the provided painter is set to the rect returned by clipRect before this function is called. For items this depends on the clipping settings defined by setClipToAxisRect, setClipKeyAxis and setClipValueAxis.
Implements QCPLayerable.
Implemented in QCPItemTracer, QCPItemBracket, QCPItemCurve, QCPItemText, QCPItemPixmap, QCPItemRect, QCPItemEllipse, QCPItemLine, and QCPItemStraightLine.
bool QCPAbstractItem::hasAnchor (const QString &name) const
Returns whether this item has an anchor with the specified name. Note that you can check for positions with this function, too, because every position is also an anchor (QCPItemPosition inherits from QCPItemAnchor).
See also:
anchor, position
Definition at line 11171 of file qcustomplot.cpp.
References mAnchors.
Referenced by createAnchor(), and createPosition().
{
  for (int i=0; i<mAnchors.size(); ++i)
  {
    if (mAnchors.at(i)->name() == name)
      return true;
  }
  return false;
}
QCPItemPosition * QCPAbstractItem::position (const QString &name) const
Returns the QCPItemPosition with the specified name. If this item doesn't have a position by that name, returns 0.
This function provides an alternative way to access item positions. Normally, you access positions direcly by their member pointers (which typically have the same variable name as name).
See also:
positions, anchor
Definition at line 11131 of file qcustomplot.cpp.
References mPositions.
{
  for (int i=0; i<mPositions.size(); ++i)
  {
    if (mPositions.at(i)->name() == name)
      return mPositions.at(i);
  }
  qDebug() << Q_FUNC_INFO << "position with name not found:" << name;
  return 0;
}
QList< QCPItemPosition * > QCPAbstractItem::positions () const [inline]
Returns all positions of the item in a list.
See also:
anchors, position
Definition at line 866 of file qcustomplot.h.
{ return mPositions; }
double QCPAbstractItem::rectSelectTest (const QRectF &rect, const QPointF &pos, boolfilledRect) const [protected]
A convenience function which returns the selectTest value for a specified rect and a specified click position pos. filledRect defines whether a click inside the rect should also be considered a hit or whether only the rect border is sensitive to hits.
This function may be used to help with the implementation of the selectTest function for specific items.
For example, if your item consists of four rects, call this function four times, once for each rect, in your selectTest reimplementation. Finally, return the minimum of all four returned values which were greater or equal to zero. (Because this function may return -1.0 when pos doesn't hit rect at all). If all calls returned -1.0, return -1.0, too, because your item wasn't hit.
See also:
distSqrToLine
Definition at line 11272 of file qcustomplot.cpp.
References distSqrToLine(), and QCPLayerable::mParentPlot.
Referenced by QCPItemRect::selectTest(), QCPItemPixmap::selectTest(), QCPItemText::selectTest(), and QCPItemTracer::selectTest().
{
  double result = -1;
  // distance to border:
  QList<QLineF> lines;
  lines << QLineF(rect.topLeft(), rect.topRight()) << QLineF(rect.bottomLeft(), rect.bottomRight())
        << QLineF(rect.topLeft(), rect.bottomLeft()) << QLineF(rect.topRight(), rect.bottomRight());
  double minDistSqr = std::numeric_limits<double>::max();
  for (int i=0; i<lines.size(); ++i)
  {
    double distSqr = distSqrToLine(lines.at(i).p1(), lines.at(i).p2(), pos);
    if (distSqr < minDistSqr)
      minDistSqr = distSqr;
  }
  result = qSqrt(minDistSqr);
  
  // filled rect, allow click inside to count as hit:
  if (filledRect && result > mParentPlot->selectionTolerance()*0.99)
  {
    if (rect.contains(pos))
      result = mParentPlot->selectionTolerance()*0.99;
  }
  return result;
}
bool QCPAbstractItem::selectable () const [inline]
Definition at line 853 of file qcustomplot.h.
Referenced by itemAt(), and setSelectable().
{ return mSelectable; }
bool QCPAbstractItem::selected () const [inline]
Definition at line 854 of file qcustomplot.h.
Referenced by handleItemSelection(), and setSelected().
{ return mSelected; }
void QCPAbstractItem::selectionChanged (boolselected) [signal]
This signal is emitted when the selection state of this item has changed, either by user interaction or by a direct call to setSelected.
Definition at line 593 of file moc_qcustomplot.cpp.
Referenced by setSelected().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 0, _a);
}
double QCPAbstractItem::selectTest (const QPointF &pos) const [pure virtual]
This function is used to decide whether a click hits an item or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the item. If the item is either invisible or the distance couldn't be determined, -1.0 is returned. setSelectable has no influence on the return value of this function.
If the item is represented not by single lines but by an area like QCPItemRect or QCPItemText, a click inside the area returns a constant value greater zero (typically 99% of the selectionTolerance of the parent QCustomPlot). If the click lies outside the area, this function returns -1.0.
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs.
See also:
setSelected, QCustomPlot::setInteractions
Implemented in QCPItemTracer, QCPItemBracket, QCPItemCurve, QCPItemText, QCPItemPixmap, QCPItemRect, QCPItemEllipse, QCPItemLine, and QCPItemStraightLine.
Referenced by itemAt().
void QCPAbstractItem::setClipAxes (QCPAxis *keyAxis, QCPAxis *valueAxis)
Sets both clip axes. Together they define the axis rect that will be used to clip the item when setClipToAxisRect is set to true.
See also:
setClipToAxisRect, setClipKeyAxis, setClipValueAxis
Definition at line 11056 of file qcustomplot.cpp.
References mClipKeyAxis, and mClipValueAxis.
{
  mClipKeyAxis = keyAxis;
  mClipValueAxis = valueAxis;
}
void QCPAbstractItem::setClipKeyAxis (QCPAxis *axis)
Sets the clip key axis. Together with the clip value axis it defines the axis rect that will be used to clip the item when setClipToAxisRect is set to true.
See also:
setClipToAxisRect, setClipAxes, setClipValueAxis
Definition at line 11068 of file qcustomplot.cpp.
References mClipKeyAxis.
{
  mClipKeyAxis = axis;
}
void QCPAbstractItem::setClipToAxisRect (boolclip)
Sets whether the item shall be clipped to the axis rect or whether it shall be visible on the entire QCustomPlot. The axis rect is defined by the clip axes which can be set via setClipAxes or individually with setClipKeyAxis and setClipValueAxis.
Definition at line 11045 of file qcustomplot.cpp.
References mClipToAxisRect.
{
  mClipToAxisRect = clip;
}
void QCPAbstractItem::setClipValueAxis (QCPAxis *axis)
Sets the clip value axis. Together with the clip key axis it defines the axis rect that will be used to clip the item when setClipToAxisRect is set to true.
See also:
setClipToAxisRect, setClipAxes, setClipKeyAxis
Definition at line 11079 of file qcustomplot.cpp.
References mClipValueAxis.
{
  mClipValueAxis = axis;
}
void QCPAbstractItem::setSelectable (boolselectable)
Sets whether the user can (de-)select this item by clicking on the QCustomPlot surface. (When QCustomPlot::setInteractions contains QCustomPlot::iSelectItems.)
However, even when selectable was set to false, it is possible to set the selection manually, by calling setSelected directly.
See also:
QCustomPlot::setInteractions, setSelected
Definition at line 11093 of file qcustomplot.cpp.
References mSelectable, and selectable().
{
  mSelectable = selectable;
}
void QCPAbstractItem::setSelected (boolselected)
Sets whether this item is selected or not. When selected, it might use a different visual appearance (e.g. pen and brush), this depends on the specific item, though.
The entire selection mechanism for items is handled automatically when QCustomPlot::setInteractions contains QCustomPlot::iSelectItems. You only need to call this function when you wish to change the selection state manually.
This function can change the selection state even when setSelectable was set to false.
emits the selectionChanged signal when selected is different from the previous selection state.
See also:
selectTest
Definition at line 11112 of file qcustomplot.cpp.
References mSelected, selected(), and selectionChanged().
Referenced by handleItemSelection().
{
  if (mSelected != selected)
  {
    mSelected = selected;
    emit selectionChanged(mSelected);
  }
}
Friends And Related Function Documentation
friend class QCPItemAnchor [friend]
Definition at line 899 of file qcustomplot.h.
Referenced by createAnchor().
Member Data Documentation
QList<QCPItemAnchor*> QCPAbstractItem::mAnchors [protected]
Definition at line 877 of file qcustomplot.h.
Referenced by anchor(), createAnchor(), createPosition(), hasAnchor(), and ~QCPAbstractItem().
QCPAxis* QCPAbstractItem::mClipKeyAxis [protected]
Definition at line 874 of file qcustomplot.h.
Referenced by clipRect(), setClipAxes(), and setClipKeyAxis().
bool QCPAbstractItem::mClipToAxisRect [protected]
Definition at line 873 of file qcustomplot.h.
Referenced by clipRect(), and setClipToAxisRect().
QCPAxis * QCPAbstractItem::mClipValueAxis [protected]
Definition at line 874 of file qcustomplot.h.
Referenced by clipRect(), setClipAxes(), and setClipValueAxis().
QList<QCPItemPosition*> QCPAbstractItem::mPositions [protected]
Definition at line 876 of file qcustomplot.h.
Referenced by createPosition(), and position().
bool QCPAbstractItem::mSelectable [protected]
Definition at line 875 of file qcustomplot.h.
Referenced by setSelectable().
bool QCPAbstractItem::mSelected [protected]
Definition at line 875 of file qcustomplot.h.
Referenced by QCPItemEllipse::mainBrush(), QCPItemRect::mainBrush(), QCPItemText::mainBrush(), QCPItemTracer::mainBrush(), QCPItemText::mainColor(), QCPItemText::mainFont(), QCPItemStraightLine::mainPen(), QCPItemLine::mainPen(), QCPItemEllipse::mainPen(), QCPItemRect::mainPen(), QCPItemPixmap::mainPen(), QCPItemText::mainPen(), QCPItemCurve::mainPen(), QCPItemBracket::mainPen(), QCPItemTracer::mainPen(), and setSelected().
Author
Generated automatically by Doxygen for AQ0X from the source code.