QCPAbstractPlottable
NAME
QCPAbstractPlottable -
The abstract base class for all data representing objects in a plot.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPLayerable.
Inherited by QCPBars, QCPCurve, QCPGraph, and QCPStatisticalBox.
Signals
void selectionChanged (bool selected)
This signal is emitted when the selection state of this plottable has changed, either by user interaction or by a direct call to setSelected.
Public Member Functions
QCPAbstractPlottable (QCPAxis *keyAxis, QCPAxis *valueAxis)
Constructs an abstract plottable which uses keyAxis as its key axis ('x') and valueAxis as its value axis ('y').
virtual ~QCPAbstractPlottable ()
QString name () const
bool antialiasedFill () const
bool antialiasedScatters () const
bool antialiasedErrorBars () const
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
QCPAxis * keyAxis () const
QCPAxis * valueAxis () const
bool selectable () const
bool selected () const
void setName (const QString &name)
The name is the textual representation of this plottable as it is displayed in the QCPLegend of the parent QCustomPlot.
void setAntialiasedFill (bool enabled)
Sets whether fills of this plottable is drawn antialiased or not.
void setAntialiasedScatters (bool enabled)
Sets whether the scatter symbols of this plottable are drawn antialiased or not.
void setAntialiasedErrorBars (bool enabled)
Sets whether the error bars of this plottable are drawn antialiased or not.
void setPen (const QPen &pen)
The pen is used to draw basic lines that make up the plottable representation in the plot.
void setSelectedPen (const QPen &pen)
When the plottable is selected, this pen is used to draw basic lines instead of the normal pen set via setPen.
void setBrush (const QBrush &brush)
The brush is used to draw basic fills of the plottable representation in the plot.
void setSelectedBrush (const QBrush &brush)
When the plottable is selected, this brush is used to draw fills instead of the normal brush set via setBrush.
void setKeyAxis (QCPAxis *axis)
The key axis of a plottable can be set to any axis of a QCustomPlot, as long as it is orthogonal to the plottable's value axis.
void setValueAxis (QCPAxis *axis)
The value axis of a plottable can be set to any axis of a QCustomPlot, as long as it is orthogonal to the plottable's key axis.
void setSelectable (bool selectable)
Sets whether the user can (de-)select this plottable by clicking on the QCustomPlot surface.
void setSelected (bool selected)
Sets whether this plottable is selected or not.
void rescaleAxes (bool onlyEnlarge=false) const
Rescales the key and value axes associated with this plottable to contain all displayed data, so the whole plottable is visible.
void rescaleKeyAxis (bool onlyEnlarge=false) const
Rescales the key axis of the plottable so the whole plottable is visible.
void rescaleValueAxis (bool onlyEnlarge=false) const
Rescales the value axis of the plottable so the whole plottable is visible.
virtual void clearData ()=0
Clears all data in the plottable.
virtual double selectTest (const QPointF &pos) const =0
This function is used to decide whether a click hits a plottable or not.
virtual bool addToLegend ()
Adds this plottable to the legend of the parent QCustomPlot.
virtual bool removeFromLegend () const
Removes the plottable from the legend of the parent QCustomPlot.
Protected Types
enum SignDomain { sdNegative, sdBoth, sdPositive }
Represents negative and positive sign domain for passing to getKeyRange and getValueRange.
Protected Member Functions
virtual QRect clipRect () const
virtual void draw (QCPPainter *painter)=0
virtual void drawLegendIcon (QCPPainter *painter, const QRect &rect) const =0
virtual QCPRange getKeyRange (bool &validRange, SignDomain inSignDomain=sdBoth) const =0
virtual QCPRange getValueRange (bool &validRange, SignDomain inSignDomain=sdBoth) const =0
void coordsToPixels (double key, double value, double &x, double &y) const
const QPointF coordsToPixels (double key, double value) const
void pixelsToCoords (double x, double y, double &key, double &value) const
void pixelsToCoords (const QPointF &pixelPos, double &key, double &value) const
QPen mainPen () const
QBrush mainBrush () const
void applyDefaultAntialiasingHint (QCPPainter *painter) const
void applyFillAntialiasingHint (QCPPainter *painter) const
void applyScattersAntialiasingHint (QCPPainter *painter) const
void applyErrorBarsAntialiasingHint (QCPPainter *painter) const
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
Protected Attributes
QString mName
bool mAntialiasedFill
bool mAntialiasedScatters
bool mAntialiasedErrorBars
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
QCPAxis * mKeyAxis
QCPAxis * mValueAxis
bool mSelected
bool mSelectable
Friends
class QCPPlottableLegendItem
Detailed Description
The abstract base class for all data representing objects in a plot.
It defines a very basic interface like name, pen, brush, visibility etc. Since this class is abstract, it can't be instantiated. Use one of the subclasses or create a subclass yourself (see below), to create new ways of displaying data.
All further specifics are in the subclasses, for example:
A normal graph with possibly a line, scatter points and error bars is displayed by QCPGraph (typically created with QCustomPlot::addGraph).
A parametric curve can be displayed with QCPCurve.
A stackable bar chart can be achieved with QCPBars.
A box of a statistical box plot is created with QCPStatisticalBox.
Creating own plottables
To create an own plottable, you implement a subclass of QCPAbstractPlottable. These are the pure virtual functions, you must implement:
clearData
selectTest
draw
drawLegendIcon
getKeyRange
getValueRange
See the documentation of those functions for what they need to do.
For drawing your plot, you can use the coordsToPixels functions to translate a point in plot coordinates to pixel coordinates. This function is quite convenient, because it takes the orientation of the key and value axes into account for you (x and y are swapped when the key axis is vertical and the value axis horizontal). If you are worried about performance (i.e. you need to translate many points in a loop like QCPGraph), you can directly use QCPAxis::coordToPixel. However, you must then take care about the orientation of the axis yourself.
From QCPAbstractPlottable you inherit the following members you may use: QCustomPlot *mParentPlot A pointer to the parent QCustomPlot instance. This is adopted from the axes that are passed in the constructor. QString mName The name of the plottable. bool mVisible Whether the plot is visible or not. When this is false, you shouldn't draw the data in the draw function (draw is always called, no matter what mVisible is). QPen mPen The generic pen of the plottable. You should use this pen for the most prominent data representing lines in the plottable (e.g QCPGraph uses this pen for its graph lines and scatters) QPen mSelectedPen The generic pen that should be used when the plottable is selected (hint: mainPen gives you the right pen, depending on selection state). QBrush mBrush The generic brush of the plottable. You should use this brush for the most prominent fillable structures in the plottable (e.g. QCPGraph uses this brush to control filling under the graph) QBrush mSelectedBrush The generic brush that should be used when the plottable is selected (hint: mainBrush gives you the right brush, depending on selection state). QCPAxis *mKeyAxis, *mValueAxis The key and value axes this plottable is attached to. Call their QCPAxis::coordToPixel functions to translate coordinates to pixels in either the key or value dimension. bool mSelected indicates whether the plottable is selected or not.
Definition at line 359 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPAbstractPlottable::SignDomain [protected]
Represents negative and positive sign domain for passing to getKeyRange and getValueRange.
Enumerator
sdNegative
The negative sign domain, i.e. numbers smaller than zero.
sdBoth
Both sign domains, including zero, i.e. all (rational) numbers.
sdPositive
The positive sign domain, i.e. numbers greater than zero.
Definition at line 410 of file qcustomplot.h.
                  { sdNegative
                    ,sdBoth
                    ,sdPositive
                  };
Constructor & Destructor Documentation
QCPAbstractPlottable::QCPAbstractPlottable (QCPAxis *keyAxis, QCPAxis *valueAxis)
Constructs an abstract plottable which uses keyAxis as its key axis ('x') and valueAxis as its value axis ('y'). keyAxis and valueAxis must reside in the same QCustomPlot instance and not have the same orientation. If either of these restrictions is violated, a corresponding message is printed to the debug output (qDebug), the construction is not aborted, though.
Since QCPAbstractPlottable is an abstract class that defines the basic interface to plottables (i.e. any form of data representation inside a plot, like graphs, curves etc.), it can't be directly instantiated.
You probably want one of the subclasses like QCPGraph and QCPCurve instead.
See also:
setKeyAxis, setValueAxis
Definition at line 8353 of file qcustomplot.cpp.
References QCPAxis::orientation(), and QCPLayerable::parentPlot().
                                                                               :
  QCPLayerable(keyAxis->parentPlot()),
  mName(""),
  mAntialiasedFill(true),
  mAntialiasedScatters(true),
  mAntialiasedErrorBars(false),
  mPen(Qt::black),
  mSelectedPen(Qt::black),
  mBrush(Qt::NoBrush),
  mSelectedBrush(Qt::NoBrush),
  mKeyAxis(keyAxis),
  mValueAxis(valueAxis),
  mSelected(false),
  mSelectable(true)
{
  if (keyAxis->parentPlot() != valueAxis->parentPlot())
    qDebug() << Q_FUNC_INFO << "Parent plot of keyAxis is not the same as that of valueAxis.";
  if (keyAxis->orientation() == valueAxis->orientation())
    qDebug() << Q_FUNC_INFO << "keyAxis and valueAxis must be orthogonal to each other.";
}
virtual QCPAbstractPlottable::~QCPAbstractPlottable () [inline], [virtual]
Definition at line 364 of file qcustomplot.h.
{}
Member Function Documentation
bool QCPAbstractPlottable::addToLegend () [virtual]
Adds this plottable to the legend of the parent QCustomPlot. Normally, a QCPPlottableLegendItem is created and inserted into the legend. If the plottable needs a more specialized representation in the plot, this function will take this into account and instead create the specialized subclass of QCPAbstractLegendItem.
Returns true on success, i.e. when a legend item associated with this plottable isn't already in the legend.
See also:
removeFromLegend, QCPLegend::addItem
Definition at line 8618 of file qcustomplot.cpp.
References QCPLayerable::mParentPlot, and QCPPlottableLegendItem.
Referenced by addPlottable().
{
  if (!mParentPlot->legend->hasItemWithPlottable(this))
  {
    mParentPlot->legend->addItem(new QCPPlottableLegendItem(mParentPlot->legend, this));
    return true;
  } else
    return false;
}
bool QCPAbstractPlottable::antialiasedErrorBars () const [inline]
Definition at line 370 of file qcustomplot.h.
{ return mAntialiasedErrorBars; }
bool QCPAbstractPlottable::antialiasedFill () const [inline]
Definition at line 368 of file qcustomplot.h.
{ return mAntialiasedFill; }
bool QCPAbstractPlottable::antialiasedScatters () const [inline]
Definition at line 369 of file qcustomplot.h.
{ return mAntialiasedScatters; }
void QCPAbstractPlottable::applyDefaultAntialiasingHint (QCPPainter *painter) const [protected], [virtual]
A convenience function to easily set the QPainter::Antialiased hint on the provided painter before drawing plottable lines.
This is the antialiasing state the painter passed to the draw method is in by default.
This function takes into account the local setting of the antialiasing flag as well as the overrides set e.g. with QCustomPlot::setNotAntialiasedElements.
See also:
setAntialiased, applyFillAntialiasingHint, applyScattersAntialiasingHint, applyErrorBarsAntialiasingHint
Implements QCPLayerable.
Definition at line 8753 of file qcustomplot.cpp.
References QCP::aePlottables, QCPLayerable::applyAntialiasingHint(), and QCPLayerable::mAntialiased.
Referenced by QCPCurve::draw(), QCPBars::draw(), QCPGraph::drawImpulsePlot(), QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPBars::drawLegendIcon(), QCPStatisticalBox::drawLegendIcon(), QCPGraph::drawLinePlot(), QCPStatisticalBox::drawMedian(), and QCPStatisticalBox::drawQuartileBox().
{
  applyAntialiasingHint(painter, mAntialiased, QCP::aePlottables);
}
void QCPAbstractPlottable::applyErrorBarsAntialiasingHint (QCPPainter *painter) const [protected]
A convenience function to easily set the QPainter::Antialiased hint on the provided painter before drawing plottable error bars.
This function takes into account the local setting of the error bars antialiasing flag as well as the overrides set e.g. with QCustomPlot::setNotAntialiasedElements.
See also:
setAntialiased, applyFillAntialiasingHint, applyScattersAntialiasingHint, applyDefaultAntialiasingHint
Definition at line 8798 of file qcustomplot.cpp.
References QCP::aeErrorBars, QCPLayerable::applyAntialiasingHint(), and mAntialiasedErrorBars.
Referenced by QCPGraph::drawScatterPlot(), and QCPStatisticalBox::drawWhiskers().
{
  applyAntialiasingHint(painter, mAntialiasedErrorBars, QCP::aeErrorBars);
}
void QCPAbstractPlottable::applyFillAntialiasingHint (QCPPainter *painter) const [protected]
A convenience function to easily set the QPainter::Antialiased hint on the provided painter before drawing plottable fills.
This function takes into account the local setting of the fill antialiasing flag as well as the overrides set e.g. with QCustomPlot::setNotAntialiasedElements.
See also:
setAntialiased, applyDefaultAntialiasingHint, applyScattersAntialiasingHint, applyErrorBarsAntialiasingHint
Definition at line 8768 of file qcustomplot.cpp.
References QCP::aeFills, QCPLayerable::applyAntialiasingHint(), and mAntialiasedFill.
Referenced by QCPCurve::draw(), QCPBars::draw(), QCPGraph::drawFill(), QCPGraph::drawLegendIcon(), and QCPCurve::drawLegendIcon().
{
  applyAntialiasingHint(painter, mAntialiasedFill, QCP::aeFills);
}
void QCPAbstractPlottable::applyScattersAntialiasingHint (QCPPainter *painter) const [protected]
A convenience function to easily set the QPainter::Antialiased hint on the provided painter before drawing plottable scatter points.
This function takes into account the local setting of the scatters antialiasing flag as well as the overrides set e.g. with QCustomPlot::setNotAntialiasedElements.
See also:
setAntialiased, applyFillAntialiasingHint, applyDefaultAntialiasingHint, applyErrorBarsAntialiasingHint
Definition at line 8783 of file qcustomplot.cpp.
References QCP::aeScatters, QCPLayerable::applyAntialiasingHint(), and mAntialiasedScatters.
Referenced by QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPStatisticalBox::drawOutliers(), QCPGraph::drawScatterPlot(), and QCPCurve::drawScatterPlot().
{
  applyAntialiasingHint(painter, mAntialiasedScatters, QCP::aeScatters);
}
QBrush QCPAbstractPlottable::brush () const [inline]
Definition at line 373 of file qcustomplot.h.
Referenced by setBrush(), and setSelectedBrush().
{ return mBrush; }
void QCPAbstractPlottable::clearData () [pure virtual]
Clears all data in the plottable.
Implemented in QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
QRect QCPAbstractPlottable::clipRect () const [protected], [virtual]
Returns the clipping rectangle of this layerable object. By default, this is the viewport of the parent QCustomPlot. Specific subclasses may reimplement this function to provide different clipping rects.
The returned clipping rect is set on the painter before the draw function of the respective object is called.
Reimplemented from QCPLayerable.
Definition at line 8647 of file qcustomplot.cpp.
References QCPAxis::axisRect(), mKeyAxis, and mValueAxis.
{
  return mKeyAxis->axisRect() | mValueAxis->axisRect();
}
void QCPAbstractPlottable::coordsToPixels (doublekey, doublevalue, double &x, double &y) const [protected]
Convenience function for transforming a key/value pair to pixels on the QCustomPlot surface, taking the orientations of the axes associated with this plottable into account (e.g. whether key represents x or y).
key and value are transformed to the coodinates in pixels and are written to x and y.
See also:
pixelsToCoords, QCPAxis::coordToPixel
Definition at line 8662 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), mKeyAxis, mValueAxis, and QCPAxis::orientation().
Referenced by QCPStatisticalBox::drawMedian(), QCPStatisticalBox::drawOutliers(), QCPStatisticalBox::drawQuartileBox(), QCPStatisticalBox::drawWhiskers(), QCPBars::getBarPolygon(), QCPCurve::getCurveData(), QCPCurve::outsideCoordsToPixels(), QCPGraph::pointDistance(), and QCPCurve::pointDistance().
{
  if (mKeyAxis->orientation() == Qt::Horizontal)
  {
    x = mKeyAxis->coordToPixel(key);
    y = mValueAxis->coordToPixel(value);
  } else
  {
    y = mKeyAxis->coordToPixel(key);
    x = mValueAxis->coordToPixel(value);
  }
}
const QPointF QCPAbstractPlottable::coordsToPixels (doublekey, doublevalue) const [protected]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns the input as pixel coordinates in a QPointF.
Definition at line 8680 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), mKeyAxis, mValueAxis, and QCPAxis::orientation().
{
  if (mKeyAxis->orientation() == Qt::Horizontal)
    return QPointF(mKeyAxis->coordToPixel(key), mValueAxis->coordToPixel(value));
  else
    return QPointF(mValueAxis->coordToPixel(value), mKeyAxis->coordToPixel(key));
}
double QCPAbstractPlottable::distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const [protected]
Finds the shortest squared distance of point to the line segment defined by start and end.
This function may be used to help with the implementation of the selectTest function for specific plottables.
Note:
This function is identical to QCPAbstractItem::distSqrToLine
Definition at line 8813 of file qcustomplot.cpp.
Referenced by QCPGraph::pointDistance(), and QCPCurve::pointDistance().
{
  QVector2D a(start);
  QVector2D b(end);
  QVector2D p(point);
  QVector2D v(b-a);
  
  double vLengthSqr = v.lengthSquared();
  if (!qFuzzyIsNull(vLengthSqr))
  {
    double mu = QVector2D::dotProduct(p-a, v)/vLengthSqr;
    if (mu < 0)
      return (a-p).lengthSquared();
    else if (mu > 1)
      return (b-p).lengthSquared();
    else
      return ((a + mu*v)-p).lengthSquared();
  } else
    return (a-p).lengthSquared();
}
void QCPAbstractPlottable::draw (QCPPainter *painter) [protected], [pure virtual]
Draws this plottable with the provided painter. Called by QCustomPlot::draw on all its visible plottables.
The cliprect of the provided painter is set to the axis rect of the key/value axis of this plottable (what clipRect returns), before this function is called.
Implements QCPLayerable.
Implemented in QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
void QCPAbstractPlottable::drawLegendIcon (QCPPainter *painter, const QRect &rect) const [protected], [pure virtual]
called by QCPLegend::draw (via QCPPlottableLegendItem::draw) to create a graphical representation of this plottable inside rect, next to the plottable name.
Implemented in QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
Referenced by QCPPlottableLegendItem::draw().
QCPRange QCPAbstractPlottable::getKeyRange (bool &validRange, SignDomaininSignDomain = sdBoth) const [protected], [pure virtual]
called by rescaleAxes functions to get the full data key bounds. For logarithmic plots, one can set inSignDomain to either sdNegative or sdPositive in order to restrict the returned range to that sign domain. E.g. when only negative range is wanted, set inSignDomain to sdNegative and all positive points will be ignored for range calculation. For no restriction, just set inSignDomain to sdBoth (default). validRange is an output parameter that indicates whether a proper range could be found or not. If this is false, you shouldn't use the returned range (e.g. no points in data).
See also:
rescaleAxes, getValueRange
Implemented in QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
Referenced by rescaleKeyAxis().
QCPRange QCPAbstractPlottable::getValueRange (bool &validRange, SignDomaininSignDomain = sdBoth) const [protected], [pure virtual]
called by rescaleAxes functions to get the full data value bounds. For logarithmic plots, one can set inSignDomain to either sdNegative or sdPositive in order to restrict the returned range to that sign domain. E.g. when only negative range is wanted, set inSignDomain to sdNegative and all positive points will be ignored for range calculation. For no restriction, just set inSignDomain to sdBoth (default). validRange is an output parameter that indicates whether a proper range could be found or not. If this is false, you shouldn't use the returned range (e.g. no points in data).
See also:
rescaleAxes, getKeyRange
Implemented in QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
Referenced by rescaleValueAxis().
QCPAxis* QCPAbstractPlottable::keyAxis () const [inline]
Definition at line 375 of file qcustomplot.h.
Referenced by QCPBars::moveAbove(), QCPBars::moveBelow(), plottableAt(), and QCPItemTracer::setGraph().
{ return mKeyAxis; }
QBrush QCPAbstractPlottable::mainBrush () const [protected]
Returns the brush that should be used for drawing fills of the plottable. Returns mBrush when the graph is not selected and mSelectedBrush when it is.
Definition at line 8736 of file qcustomplot.cpp.
References mBrush, mSelected, and mSelectedBrush.
Referenced by QCPCurve::draw(), QCPBars::draw(), QCPGraph::drawFill(), QCPStatisticalBox::drawQuartileBox(), QCPGraph::drawScatterPlot(), and QCPCurve::drawScatterPlot().
{
  return mSelected ? mSelectedBrush : mBrush;
}
QPen QCPAbstractPlottable::mainPen () const [protected]
Returns the pen that should be used for drawing lines of the plottable. Returns mPen when the graph is not selected and mSelectedPen when it is.
Definition at line 8726 of file qcustomplot.cpp.
References mPen, mSelected, and mSelectedPen.
Referenced by QCPCurve::draw(), QCPBars::draw(), QCPGraph::drawImpulsePlot(), QCPGraph::drawLinePlot(), QCPStatisticalBox::drawQuartileBox(), QCPGraph::drawScatterPlot(), and QCPCurve::drawScatterPlot().
{
  return mSelected ? mSelectedPen : mPen;
}
QString QCPAbstractPlottable::name () const [inline]
Definition at line 367 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::draw(), setName(), and QCPPlottableLegendItem::size().
{ return mName; }
QPen QCPAbstractPlottable::pen () const [inline]
Definition at line 371 of file qcustomplot.h.
References mPen.
Referenced by QCPGraph::drawImpulsePlot(), QCPGraph::setErrorPen(), QCPStatisticalBox::setMedianPen(), QCPStatisticalBox::setOutlierPen(), setPen(), setSelectedPen(), QCPStatisticalBox::setWhiskerBarPen(), and QCPStatisticalBox::setWhiskerPen().
{ return mPen; }
void QCPAbstractPlottable::pixelsToCoords (doublex, doubley, double &key, double &value) const [protected]
Convenience function for transforming a x/y pixel pair on the QCustomPlot surface to plot coordinates, taking the orientations of the axes associated with this plottable into account (e.g. whether key represents x or y).
x and y are transformed to the plot coodinates and are written to key and value.
See also:
coordsToPixels, QCPAxis::coordToPixel
Definition at line 8698 of file qcustomplot.cpp.
References mKeyAxis, mValueAxis, QCPAxis::orientation(), and QCPAxis::pixelToCoord().
Referenced by pixelsToCoords(), QCPBars::selectTest(), and QCPStatisticalBox::selectTest().
{
  if (mKeyAxis->orientation() == Qt::Horizontal)
  {
    key = mKeyAxis->pixelToCoord(x);
    value = mValueAxis->pixelToCoord(y);
  } else
  {
    key = mKeyAxis->pixelToCoord(y);
    value = mValueAxis->pixelToCoord(x);
  }
}
void QCPAbstractPlottable::pixelsToCoords (const QPointF &pixelPos, double &key, double &value) const [protected]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns the pixel input pixelPos as plot coordinates key and value.
Definition at line 8716 of file qcustomplot.cpp.
References key, pixelsToCoords(), and value.
{
  pixelsToCoords(pixelPos.x(), pixelPos.y(), key, value);
}
bool QCPAbstractPlottable::removeFromLegend () const [virtual]
Removes the plottable from the legend of the parent QCustomPlot. This means the QCPAbstractLegendItem (usually a QCPPlottableLegendItem) that is associated with this plottable is removed.
Returns true on success, i.e. if a legend item associated with this plottable was found and removed from the legend.
See also:
addToLegend, QCPLegend::removeItem
Definition at line 8638 of file qcustomplot.cpp.
References QCPLayerable::mParentPlot.
Referenced by removePlottable().
{
  if (QCPPlottableLegendItem *lip = mParentPlot->legend->itemWithPlottable(this))
    return mParentPlot->legend->removeItem(lip);
  else
    return false;
}
void QCPAbstractPlottable::rescaleAxes (boolonlyEnlarge = false) const
Rescales the key and value axes associated with this plottable to contain all displayed data, so the whole plottable is visible. If the scaling of an axis is logarithmic, rescaleAxes will make sure not to rescale to an illegal range i.e. a range containing different signs and/or zero. Instead it will stay in the current sign domain and ignore all parts of the plottable that lie outside of that domain.
onlyEnlarge makes sure the ranges are only expanded, never reduced. So it's possible to show multiple plottables in their entirety by multiple calls to rescaleAxes where the first call has onlyEnlarge set to false (the default), and all subsequent set to true.
Definition at line 8547 of file qcustomplot.cpp.
References rescaleKeyAxis(), and rescaleValueAxis().
{
  rescaleKeyAxis(onlyEnlarge);
  rescaleValueAxis(onlyEnlarge);
}
void QCPAbstractPlottable::rescaleKeyAxis (boolonlyEnlarge = false) const
Rescales the key axis of the plottable so the whole plottable is visible. See rescaleAxes for detailed behaviour.
Definition at line 8558 of file qcustomplot.cpp.
References getKeyRange(), QCPRange::lower, mKeyAxis, QCPAxis::range(), QCPAxis::scaleType(), sdBoth, sdNegative, sdPositive, QCPAxis::setRange(), and QCPRange::upper.
Referenced by rescaleAxes().
{
  SignDomain signDomain = sdBoth;
  if (mKeyAxis->scaleType() == QCPAxis::stLogarithmic)
    signDomain = (mKeyAxis->range().upper < 0 ? sdNegative : sdPositive);
  
  bool validRange;
  QCPRange newRange = getKeyRange(validRange, signDomain);
  if (validRange)
  {
    if (onlyEnlarge)
    {
      if (mKeyAxis->range().lower < newRange.lower)
        newRange.lower = mKeyAxis->range().lower;
      if (mKeyAxis->range().upper > newRange.upper)
        newRange.upper = mKeyAxis->range().upper;
    }
    mKeyAxis->setRange(newRange);
  }
}
void QCPAbstractPlottable::rescaleValueAxis (boolonlyEnlarge = false) const
Rescales the value axis of the plottable so the whole plottable is visible. See rescaleAxes for detailed behaviour.
Definition at line 8584 of file qcustomplot.cpp.
References getValueRange(), QCPRange::lower, mValueAxis, QCPAxis::range(), QCPAxis::scaleType(), sdBoth, sdNegative, sdPositive, QCPAxis::setRange(), and QCPRange::upper.
Referenced by rescaleAxes().
{
  SignDomain signDomain = sdBoth;
  if (mValueAxis->scaleType() == QCPAxis::stLogarithmic)
    signDomain = (mValueAxis->range().upper < 0 ? sdNegative : sdPositive);
  
  bool validRange;
  QCPRange newRange = getValueRange(validRange, signDomain);
  
  if (validRange)
  {
    if (onlyEnlarge)
    {
      if (mValueAxis->range().lower < newRange.lower)
        newRange.lower = mValueAxis->range().lower;
      if (mValueAxis->range().upper > newRange.upper)
        newRange.upper = mValueAxis->range().upper;
    }
    mValueAxis->setRange(newRange);
  }
}
bool QCPAbstractPlottable::selectable () const [inline]
Definition at line 377 of file qcustomplot.h.
Referenced by plottableAt(), and setSelectable().
{ return mSelectable; }
bool QCPAbstractPlottable::selected () const [inline]
Definition at line 378 of file qcustomplot.h.
Referenced by handlePlottableSelection(), and setSelected().
{ return mSelected; }
QBrush QCPAbstractPlottable::selectedBrush () const [inline]
Definition at line 374 of file qcustomplot.h.
{ return mSelectedBrush; }
QPen QCPAbstractPlottable::selectedPen () const [inline]
Definition at line 372 of file qcustomplot.h.
{ return mSelectedPen; }
void QCPAbstractPlottable::selectionChanged (boolselected) [signal]
This signal is emitted when the selection state of this plottable has changed, either by user interaction or by a direct call to setSelected.
Definition at line 189 of file moc_qcustomplot.cpp.
Referenced by setSelected().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 0, _a);
}
double QCPAbstractPlottable::selectTest (const QPointF &pos) const [pure virtual]
This function is used to decide whether a click hits a plottable or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the plottable (e.g. to the scatters/lines of a graph). If the plottable is either invisible, contains no data or the distance couldn't be determined, -1.0 is returned. setSelectable has no influence on the return value of this function.
If the plottable is represented not by single lines but by an area like QCPBars or QCPStatisticalBox, a click inside the area returns a constant value greater zero (typically 99% of the selectionTolerance of the parent QCustomPlot). If the click lies outside the area, this function returns -1.0.
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs.
See also:
setSelected, QCustomPlot::setInteractions
Implemented in QCPStatisticalBox, QCPBars, QCPCurve, and QCPGraph.
Referenced by plottableAt().
void QCPAbstractPlottable::setAntialiasedErrorBars (boolenabled)
Sets whether the error bars of this plottable are drawn antialiased or not. Note that this setting may be overridden by QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements.
Definition at line 8411 of file qcustomplot.cpp.
References mAntialiasedErrorBars.
{
  mAntialiasedErrorBars = enabled;
}
void QCPAbstractPlottable::setAntialiasedFill (boolenabled)
Sets whether fills of this plottable is drawn antialiased or not. Note that this setting may be overridden by QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements.
Definition at line 8389 of file qcustomplot.cpp.
References mAntialiasedFill.
{
  mAntialiasedFill = enabled;
}
void QCPAbstractPlottable::setAntialiasedScatters (boolenabled)
Sets whether the scatter symbols of this plottable are drawn antialiased or not. Note that this setting may be overridden by QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements.
Definition at line 8400 of file qcustomplot.cpp.
References mAntialiasedScatters.
{
  mAntialiasedScatters = enabled;
}
void QCPAbstractPlottable::setBrush (const QBrush &brush)
The brush is used to draw basic fills of the plottable representation in the plot. The Fill can be a color, gradient or texture, see the usage of QBrush.
For example, the QCPGraph subclass draws the fill under the graph with this brush, when it's not set to Qt::NoBrush.
See also:
setPen
Definition at line 8451 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by QCPStatisticalBox::QCPStatisticalBox().
{
  mBrush = brush;
}
void QCPAbstractPlottable::setKeyAxis (QCPAxis *axis)
The key axis of a plottable can be set to any axis of a QCustomPlot, as long as it is orthogonal to the plottable's value axis. This function performs no checks to make sure this is the case. The typical mathematical choice is to use the x-axis (QCustomPlot::xAxis) as key axis and the y-axis (QCustomPlot::yAxis) as value axis.
Normally, the key and value axes are set in the constructor of the plottable (or QCustomPlot::addGraph when working with QCPGraphs through the dedicated graph interface).
See also:
setValueAxis
Definition at line 8478 of file qcustomplot.cpp.
References mKeyAxis.
{
  mKeyAxis = axis;
}
void QCPAbstractPlottable::setName (const QString &name)
The name is the textual representation of this plottable as it is displayed in the QCPLegend of the parent QCustomPlot. It may contain any utf-8 characters, including newlines.
Definition at line 8378 of file qcustomplot.cpp.
References mName, and name().
Referenced by addGraph().
{
  mName = name;
}
void QCPAbstractPlottable::setPen (const QPen &pen)
The pen is used to draw basic lines that make up the plottable representation in the plot. For example, the QCPGraph subclass draws its graph lines and scatter points with this pen.
See also:
setBrush
Definition at line 8426 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPStatisticalBox::QCPStatisticalBox().
{
  mPen = pen;
}
void QCPAbstractPlottable::setSelectable (boolselectable)
Sets whether the user can (de-)select this plottable by clicking on the QCustomPlot surface. (When QCustomPlot::setInteractions contains iSelectPlottables.)
However, even when selectable was set to false, it is possible to set the selection manually, by calling setSelected directly.
See also:
setSelected
Definition at line 8508 of file qcustomplot.cpp.
References mSelectable, and selectable().
{
  mSelectable = selectable;
}
void QCPAbstractPlottable::setSelected (boolselected)
Sets whether this plottable is selected or not. When selected, it uses a different pen and brush to draw its lines and fills, see setSelectedPen and setSelectedBrush.
The entire selection mechanism for plottables is handled automatically when QCustomPlot::setInteractions contains iSelectPlottables. You only need to call this function when you wish to change the selection state manually.
This function can change the selection state even when setSelectable was set to false.
emits the selectionChanged signal when selected is different from the previous selection state.
See also:
selectTest
Definition at line 8527 of file qcustomplot.cpp.
References mSelected, selected(), and selectionChanged().
Referenced by handlePlottableSelection().
{
  if (mSelected != selected)
  {
    mSelected = selected;
    emit selectionChanged(mSelected);
  }
}
void QCPAbstractPlottable::setSelectedBrush (const QBrush &brush)
When the plottable is selected, this brush is used to draw fills instead of the normal brush set via setBrush.
See also:
setSelected, setSelectable, setSelectedPen, selectTest
Definition at line 8462 of file qcustomplot.cpp.
References brush(), and mSelectedBrush.
Referenced by QCPStatisticalBox::QCPStatisticalBox().
{
  mSelectedBrush = brush;
}
void QCPAbstractPlottable::setSelectedPen (const QPen &pen)
When the plottable is selected, this pen is used to draw basic lines instead of the normal pen set via setPen.
See also:
setSelected, setSelectable, setSelectedBrush, selectTest
Definition at line 8437 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPStatisticalBox::QCPStatisticalBox().
{
  mSelectedPen = pen;
}
void QCPAbstractPlottable::setValueAxis (QCPAxis *axis)
The value axis of a plottable can be set to any axis of a QCustomPlot, as long as it is orthogonal to the plottable's key axis. This function performs no checks to make sure this is the case. The typical mathematical choice is to use the x-axis (QCustomPlot::xAxis) as key axis and the y-axis (QCustomPlot::yAxis) as value axis.
Normally, the key and value axes are set in the constructor of the plottable (or QCustomPlot::addGraph when working with QCPGraphs through the dedicated graph interface).
See also:
setKeyAxis
Definition at line 8494 of file qcustomplot.cpp.
References mValueAxis.
{
  mValueAxis = axis;
}
QCPAxis* QCPAbstractPlottable::valueAxis () const [inline]
Definition at line 376 of file qcustomplot.h.
Referenced by QCPBars::moveAbove(), QCPBars::moveBelow(), and plottableAt().
{ return mValueAxis; }
Friends And Related Function Documentation
friend class QCPPlottableLegendItem [friend]
Definition at line 446 of file qcustomplot.h.
Referenced by addToLegend().
Member Data Documentation
bool QCPAbstractPlottable::mAntialiasedErrorBars [protected]
Definition at line 415 of file qcustomplot.h.
Referenced by applyErrorBarsAntialiasingHint(), and setAntialiasedErrorBars().
bool QCPAbstractPlottable::mAntialiasedFill [protected]
Definition at line 415 of file qcustomplot.h.
Referenced by applyFillAntialiasingHint(), and setAntialiasedFill().
bool QCPAbstractPlottable::mAntialiasedScatters [protected]
Definition at line 415 of file qcustomplot.h.
Referenced by applyScattersAntialiasingHint(), and setAntialiasedScatters().
QBrush QCPAbstractPlottable::mBrush [protected]
Definition at line 417 of file qcustomplot.h.
Referenced by QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPBars::drawLegendIcon(), QCPStatisticalBox::drawLegendIcon(), QCPCurve::getCurveData(), mainBrush(), QCPBars::QCPBars(), QCPCurve::QCPCurve(), and setBrush().
QCPAxis* QCPAbstractPlottable::mKeyAxis [protected]
Definition at line 418 of file qcustomplot.h.
Referenced by QCPGraph::addFillBasePoints(), clipRect(), coordsToPixels(), QCPGraph::draw(), QCPBars::draw(), QCPGraph::drawError(), QCPGraph::drawScatterPlot(), QCPGraph::getChannelFillPolygon(), QCPCurve::getCurveData(), QCPGraph::getImpulsePlotData(), QCPGraph::getLinePlotData(), QCPGraph::getScatterPlotData(), QCPGraph::getStepCenterPlotData(), QCPGraph::getStepLeftPlotData(), QCPGraph::getStepRightPlotData(), QCPGraph::getVisibleDataBounds(), QCPGraph::lowerFillBasePoint(), QCPBars::moveAbove(), QCPBars::moveBelow(), QCPCurve::outsideCoordsToPixels(), pixelsToCoords(), rescaleKeyAxis(), QCPGraph::rescaleKeyAxis(), QCPStatisticalBox::selectTest(), setKeyAxis(), and QCPGraph::upperFillBasePoint().
QString QCPAbstractPlottable::mName [protected]
Definition at line 414 of file qcustomplot.h.
Referenced by QCPGraph::pointDistance(), QCPCurve::pointDistance(), and setName().
QPen QCPAbstractPlottable::mPen [protected]
Definition at line 416 of file qcustomplot.h.
Referenced by QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPBars::drawLegendIcon(), QCPStatisticalBox::drawLegendIcon(), mainPen(), QCPBars::QCPBars(), QCPCurve::QCPCurve(), and setPen().
bool QCPAbstractPlottable::mSelectable [protected]
Definition at line 419 of file qcustomplot.h.
Referenced by setSelectable().
bool QCPAbstractPlottable::mSelected [protected]
Definition at line 419 of file qcustomplot.h.
Referenced by mainBrush(), mainPen(), and setSelected().
QBrush QCPAbstractPlottable::mSelectedBrush [protected]
Definition at line 417 of file qcustomplot.h.
Referenced by mainBrush(), QCPBars::QCPBars(), QCPCurve::QCPCurve(), and setSelectedBrush().
QPen QCPAbstractPlottable::mSelectedPen [protected]
Definition at line 416 of file qcustomplot.h.
Referenced by mainPen(), QCPBars::QCPBars(), QCPCurve::QCPCurve(), and setSelectedPen().
QCPAxis * QCPAbstractPlottable::mValueAxis [protected]
Definition at line 418 of file qcustomplot.h.
Referenced by clipRect(), coordsToPixels(), QCPGraph::drawError(), QCPGraph::drawScatterPlot(), QCPCurve::getCurveData(), QCPGraph::getImpulsePlotData(), QCPGraph::getLinePlotData(), QCPGraph::getStepCenterPlotData(), QCPGraph::getStepLeftPlotData(), QCPGraph::getStepRightPlotData(), QCPGraph::lowerFillBasePoint(), QCPBars::moveAbove(), QCPBars::moveBelow(), QCPCurve::outsideCoordsToPixels(), pixelsToCoords(), rescaleValueAxis(), QCPGraph::rescaleValueAxis(), setValueAxis(), and QCPGraph::upperFillBasePoint().
Author
Generated automatically by Doxygen for AQ0X from the source code.