.TH "QCPBarData" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCPBarData \- 
.PP
Holds the data of one single data point (one bar) for \fBQCPBars\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qcustomplot\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQCPBarData\fP ()"
.br
.RI "\fIConstructs a bar data point with key and value set to zero\&. \fP"
.ti -1c
.RI "\fBQCPBarData\fP (double \fBkey\fP, double \fBvalue\fP)"
.br
.RI "\fIConstructs a bar data point with the specified \fIkey\fP and \fIvalue\fP\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBkey\fP"
.br
.ti -1c
.RI "double \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds the data of one single data point (one bar) for \fBQCPBars\fP\&. 

The stored data is: 
.PD 0

.IP "\(bu" 2
\fIkey:\fP coordinate on the key axis of this bar 
.IP "\(bu" 2
\fIvalue:\fP height coordinate on the value axis of this bar
.PP
\fBSee also:\fP
.RS 4
QCPBarDataaMap 
.RE
.PP

.PP
Definition at line 183 of file qcustomplot\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QCPBarData::QCPBarData ()"

.PP
Constructs a bar data point with key and value set to zero\&. 
.PP
Definition at line 276 of file qcustomplot\&.cpp\&.
.PP
.nf
276                        :
277   key(0),
278   value(0)
279 {
280 }
.fi
.SS "QCPBarData::QCPBarData (doublekey, doublevalue)"

.PP
Constructs a bar data point with the specified \fIkey\fP and \fIvalue\fP\&. 
.PP
Definition at line 285 of file qcustomplot\&.cpp\&.
.PP
.nf
285                                                :
286   key(key),
287   value(value)
288 {
289 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "double QCPBarData::key"

.PP
Definition at line 188 of file qcustomplot\&.h\&.
.PP
Referenced by QCPBars::addData(), and QCPBars::setData()\&.
.SS "double QCPBarData::value"

.PP
Definition at line 188 of file qcustomplot\&.h\&.
.PP
Referenced by QCPBars::addData()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
