QCPBars
NAME
QCPBars -
A plottable representing a bar chart in a plot.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPAbstractPlottable.
Public Member Functions
QCPBars (QCPAxis *keyAxis, QCPAxis *valueAxis)
Constructs a bar chart which uses keyAxis as its key axis ('x') and valueAxis as its value axis ('y').
virtual ~QCPBars ()
double width () const
QCPBars * barBelow () const
Returns the bars plottable that is directly below this bars plottable.
QCPBars * barAbove () const
Returns the bars plottable that is directly above this bars plottable.
const QCPBarDataMap * data () const
void setWidth (double width)
Sets the width of the bars in plot (key) coordinates.
void setData (QCPBarDataMap *data, bool copy=false)
Replaces the current data with the provided data.
void setData (const QVector< double > &key, const QVector< double > &value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided points in key and value tuples. "
void moveBelow (QCPBars *bars)
Moves this bars plottable below bars.
void moveAbove (QCPBars *bars)
Moves this bars plottable above bars.
void addData (const QCPBarDataMap &dataMap)
Adds the provided data points in dataMap to the current data.
void addData (const QCPBarData &data)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point in data to the current data.
void addData (double key, double value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point as key and value tuple to the current data.
void addData (const QVector< double > &keys, const QVector< double > &values)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided data points as key and value tuples to the current data.
void removeDataBefore (double key)
Removes all data points with key smaller than key.
void removeDataAfter (double key)
Removes all data points with key greater than key.
void removeData (double fromKey, double toKey)
Removes all data points with key between fromKey and toKey.
void removeData (double key)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes a single data point at key. "
virtual void clearData ()
Removes all data points.
virtual double selectTest (const QPointF &pos) const
This function is used to decide whether a click hits a plottable or not.
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual void drawLegendIcon (QCPPainter *painter, const QRect &rect) const
QPolygonF getBarPolygon (double key, double value) const
double getBaseValue (double key, bool positive) const
virtual QCPRange getKeyRange (bool &validRange, SignDomain inSignDomain=sdBoth) const
virtual QCPRange getValueRange (bool &validRange, SignDomain inSignDomain=sdBoth) const
Static Protected Member Functions
static void connectBars (QCPBars *lower, QCPBars *upper)
Protected Attributes
QCPBarDataMap * mData
double mWidth
QCPBars * mBarBelow
QCPBars * mBarAbove
Friends
class QCustomPlot
class QCPLegend
Additional Inherited Members
Detailed Description
A plottable representing a bar chart in a plot.
To plot data, assign it with the setData or addData functions.
Changing the appearance
The appearance of the bars is determined by the pen and the brush (setPen, setBrush).
Bar charts are stackable. This means, Two QCPBars plottables can be placed on top of each other (see QCPBars::moveAbove). Then, when two bars are at the same key position, they will appear stacked.
Usage
Like all data representing objects in QCustomPlot, the QCPBars is a plottable (QCPAbstractPlottable). So the plottable-interface of QCustomPlot applies (QCustomPlot::plottable, QCustomPlot::addPlottable, QCustomPlot::removePlottable, etc.)
Usually, you first create an instance:
QCPBars *newBars = new QCPBars(customPlot->xAxis, customPlot->yAxis);
 add it to the customPlot with QCustomPlot::addPlottable:
customPlot->addPlottable(newBars);
 and then modify the properties of the newly created plottable, e.g.:
newBars->setName("Country population");
newBars->setData(xData, yData);
Definition at line 650 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPBars::QCPBars (QCPAxis *keyAxis, QCPAxis *valueAxis) [explicit]
Constructs a bar chart which uses keyAxis as its key axis ('x') and valueAxis as its value axis ('y'). keyAxis and valueAxis must reside in the same QCustomPlot instance and not have the same orientation. If either of these restrictions is violated, a corresponding message is printed to the debug output (qDebug), the construction is not aborted, though.
The constructed QCPBars can be added to the plot with QCustomPlot::addPlottable, QCustomPlot then takes ownership of the bar chart.
Definition at line 9889 of file qcustomplot.cpp.
References QCPAbstractPlottable::mBrush, mData, QCPAbstractPlottable::mPen, QCPAbstractPlottable::mSelectedBrush, QCPAbstractPlottable::mSelectedPen, and mWidth.
                                                     :
  QCPAbstractPlottable(keyAxis, valueAxis),
  mBarBelow(0),
  mBarAbove(0)
{
  mData = new QCPBarDataMap;
  mPen.setColor(Qt::blue);
  mPen.setStyle(Qt::SolidLine);
  mBrush.setColor(QColor(40, 50, 255, 30));
  mBrush.setStyle(Qt::SolidPattern);
  mSelectedPen = mPen;
  mSelectedPen.setWidthF(2.5);
  mSelectedPen.setColor(QColor(80, 80, 255)); // lighter than Qt::blue of mPen
  mSelectedBrush = mBrush;
  
  mWidth = 0.75;
}
QCPBars::~QCPBars () [virtual]
Definition at line 9907 of file qcustomplot.cpp.
References connectBars(), mBarAbove, mBarBelow, and mData.
{
  if (mBarBelow || mBarAbove)
    connectBars(mBarBelow, mBarAbove); // take this bar out of any stacking
  delete mData;
}
Member Function Documentation
void QCPBars::addData (const QCPBarDataMap &dataMap)
Adds the provided data points in dataMap to the current data.
See also:
removeData
Definition at line 10031 of file qcustomplot.cpp.
References mData.
{
  mData->unite(dataMap);
}
void QCPBars::addData (const QCPBarData &data)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point in data to the current data.
See also:
removeData
Definition at line 10040 of file qcustomplot.cpp.
References QCPBarData::key, and mData.
{
  mData->insertMulti(data.key, data);
}
void QCPBars::addData (doublekey, doublevalue)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point as key and value tuple to the current data.
See also:
removeData
Definition at line 10049 of file qcustomplot.cpp.
References key, QCPBarData::key, mData, value, and QCPBarData::value.
{
  QCPBarData newData;
  newData.key = key;
  newData.value = value;
  mData->insertMulti(newData.key, newData);
}
void QCPBars::addData (const QVector< double > &keys, const QVector< double > &values)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided data points as key and value tuples to the current data.
See also:
removeData
Definition at line 10061 of file qcustomplot.cpp.
References QCPBarData::key, and mData.
{
  int n = keys.size();
  n = qMin(n, values.size());
  QCPBarData newData;
  for (int i=0; i<n; ++i)
  {
    newData.key = keys[i];
    newData.value = values[i];
    mData->insertMulti(newData.key, newData);
  }
}
QCPBars * QCPBars::barAbove () const [inline]
Returns the bars plottable that is directly above this bars plottable. If there is no such plottable, returns 0.
See also:
barBelow, moveBelow, moveAbove
Definition at line 660 of file qcustomplot.h.
{ return mBarAbove; }
QCPBars * QCPBars::barBelow () const [inline]
Returns the bars plottable that is directly below this bars plottable. If there is no such plottable, returns 0.
See also:
barAbove, moveBelow, moveAbove
Definition at line 659 of file qcustomplot.h.
{ return mBarBelow; }
void QCPBars::clearData () [virtual]
Removes all data points.
See also:
removeData, removeDataAfter, removeDataBefore
Implements QCPAbstractPlottable.
Definition at line 10130 of file qcustomplot.cpp.
References mData.
{
  mData->clear();
}
void QCPBars::connectBars (QCPBars *lower, QCPBars *upper) [static], [protected]
Connects below and above to each other via their mBarAbove/mBarBelow properties. The bar(s) currently below lower and upper will become disconnected to lower/upper.
If lower is zero, upper will be disconnected at the bottom. If upper is zero, lower will be disconnected at the top.
Definition at line 10248 of file qcustomplot.cpp.
References mBarAbove, and mBarBelow.
Referenced by moveAbove(), moveBelow(), and ~QCPBars().
{
  if (!lower && !upper) return;
  
  if (!lower) // disconnect upper at bottom
  {
    // disconnect old bar below upper:
    if (upper->mBarBelow && upper->mBarBelow->mBarAbove == upper)
      upper->mBarBelow->mBarAbove = 0;
    upper->mBarBelow = 0;
  } else if (!upper) // disconnect lower at top
  {
    // disconnect old bar above lower:
    if (lower->mBarAbove && lower->mBarAbove->mBarBelow == lower)
      lower->mBarAbove->mBarBelow = 0;
    lower->mBarAbove = 0;
  } else // connect lower and upper
  {
    // disconnect old bar above lower:
    if (lower->mBarAbove && lower->mBarAbove->mBarBelow == lower)
      lower->mBarAbove->mBarBelow = 0;
    // disconnect old bar below upper:
    if (upper->mBarBelow && upper->mBarBelow->mBarAbove == upper)
      upper->mBarBelow->mBarAbove = 0;
    lower->mBarAbove = upper;
    upper->mBarBelow = lower;
  }
}
const QCPBarDataMap* QCPBars::data () const [inline]
Definition at line 661 of file qcustomplot.h.
Referenced by setData().
{ return mData; }
void QCPBars::draw (QCPPainter *painter) [protected], [virtual]
Draws this plottable with the provided painter. Called by QCustomPlot::draw on all its visible plottables.
The cliprect of the provided painter is set to the axis rect of the key/value axis of this plottable (what clipRect returns), before this function is called.
Implements QCPAbstractPlottable.
Definition at line 10153 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::applyFillAntialiasingHint(), color(), getBarPolygon(), QCPRange::lower, QCPAbstractPlottable::mainBrush(), QCPAbstractPlottable::mainPen(), mData, QCPAbstractPlottable::mKeyAxis, mWidth, QCPAxis::range(), QCPPainter::setPen(), and QCPRange::upper.
{
  if (mData->isEmpty()) return;
  
  QCPBarDataMap::const_iterator it;
  for (it = mData->constBegin(); it != mData->constEnd(); ++it)
  {
    if (it.key()+mWidth*0.5 < mKeyAxis->range().lower || it.key()-mWidth*0.5 > mKeyAxis->range().upper)
      continue;
    QPolygonF barPolygon = getBarPolygon(it.key(), it.value().value);
    // draw bar fill:
    if (mainBrush().style() != Qt::NoBrush && mainBrush().color().alpha() != 0)
    {
      applyFillAntialiasingHint(painter);
      painter->setPen(Qt::NoPen);
      painter->setBrush(mainBrush());
      painter->drawPolygon(barPolygon);
    }
    // draw bar line:
    if (mainPen().style() != Qt::NoPen && mainPen().color().alpha() != 0)
    {
      applyDefaultAntialiasingHint(painter);
      painter->setPen(mainPen());
      painter->setBrush(Qt::NoBrush);
      painter->drawPolyline(barPolygon);
    }
  }
}
void QCPBars::drawLegendIcon (QCPPainter *painter, const QRect &rect) const [protected], [virtual]
called by QCPLegend::draw (via QCPPlottableLegendItem::draw) to create a graphical representation of this plottable inside rect, next to the plottable name.
Implements QCPAbstractPlottable.
Definition at line 10183 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::mBrush, QCPAbstractPlottable::mPen, and QCPPainter::setPen().
{
  // draw filled rect:
  applyDefaultAntialiasingHint(painter);
  painter->setBrush(mBrush);
  painter->setPen(mPen);
  QRectF r = QRectF(0, 0, rect.width()*0.67, rect.height()*0.67);
  r.moveCenter(rect.center());
  painter->drawRect(r);
}
QPolygonF QCPBars::getBarPolygon (doublekey, doublevalue) const [protected]
Returns the polygon of a single bar with key and value. The Polygon is open at the bottom and shifted according to the bar stacking (see moveAbove).
Definition at line 10199 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels(), getBaseValue(), and mWidth.
Referenced by draw().
{
  QPolygonF result;
  double baseValue = getBaseValue(key, value >= 0);
  result << coordsToPixels(key-mWidth*0.5, baseValue);
  result << coordsToPixels(key-mWidth*0.5, baseValue+value);
  result << coordsToPixels(key+mWidth*0.5, baseValue+value);
  result << coordsToPixels(key+mWidth*0.5, baseValue);
  return result;
}
double QCPBars::getBaseValue (doublekey, boolpositive) const [protected]
This function is called to find at which value to start drawing the base of a bar at key, when it is stacked on top of another QCPBars (e.g. with moveAbove).
positive and negative bars are separated per stack (positive are stacked above 0-value upwards, negative are stacked below 0-value downwards). This can be indicated with positive. So if the bar for which we need the base value is negative, set positive to false.
Definition at line 10219 of file qcustomplot.cpp.
References getBaseValue(), mBarBelow, mData, and mWidth.
Referenced by getBarPolygon(), getBaseValue(), getValueRange(), and selectTest().
{
  if (mBarBelow)
  {
    double max = 0;
    // find bars of mBarBelow that are approximately at key and find largest one:
    QCPBarDataMap::const_iterator it = mBarBelow->mData->lowerBound(key-mWidth*0.1);
    QCPBarDataMap::const_iterator itEnd = mBarBelow->mData->upperBound(key+mWidth*0.1);
    while (it != itEnd)
    {
      if ((positive && it.value().value > max) ||
          (!positive && it.value().value < max))
        max = it.value().value;
      ++it;
    }
    // recurse down the bar-stack to find the total height:
    return max + mBarBelow->getBaseValue(key, positive);
  } else
    return 0;
}
QCPRange QCPBars::getKeyRange (bool &validRange, SignDomaininSignDomain = sdBoth) const [protected], [virtual]
called by rescaleAxes functions to get the full data key bounds. For logarithmic plots, one can set inSignDomain to either sdNegative or sdPositive in order to restrict the returned range to that sign domain. E.g. when only negative range is wanted, set inSignDomain to sdNegative and all positive points will be ignored for range calculation. For no restriction, just set inSignDomain to sdBoth (default). validRange is an output parameter that indicates whether a proper range could be found or not. If this is false, you shouldn't use the returned range (e.g. no points in data).
See also:
rescaleAxes, getValueRange
Implements QCPAbstractPlottable.
Definition at line 10278 of file qcustomplot.cpp.
References QCPRange::lower, mData, mWidth, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
{
  QCPRange range;
  bool haveLower = false;
  bool haveUpper = false;
  
  double current;
  double barWidthHalf = mWidth*0.5;
  QCPBarDataMap::const_iterator it = mData->constBegin();
  while (it != mData->constEnd())
  {
    current = it.value().key;
    if (inSignDomain == sdBoth || (inSignDomain == sdNegative && current+barWidthHalf < 0) || (inSignDomain == sdPositive && current-barWidthHalf > 0))
    {
      if (current-barWidthHalf < range.lower || !haveLower)
      {
        range.lower = current-barWidthHalf;
        haveLower = true;
      }
      if (current+barWidthHalf > range.upper || !haveUpper)
      {
        range.upper = current+barWidthHalf;
        haveUpper = true;
      }
    }
    ++it;
  }
  
  validRange = haveLower && haveUpper;
  return range;
}
QCPRange QCPBars::getValueRange (bool &validRange, SignDomaininSignDomain = sdBoth) const [protected], [virtual]
called by rescaleAxes functions to get the full data value bounds. For logarithmic plots, one can set inSignDomain to either sdNegative or sdPositive in order to restrict the returned range to that sign domain. E.g. when only negative range is wanted, set inSignDomain to sdNegative and all positive points will be ignored for range calculation. For no restriction, just set inSignDomain to sdBoth (default). validRange is an output parameter that indicates whether a proper range could be found or not. If this is false, you shouldn't use the returned range (e.g. no points in data).
See also:
rescaleAxes, getKeyRange
Implements QCPAbstractPlottable.
Definition at line 10311 of file qcustomplot.cpp.
References getBaseValue(), QCPRange::lower, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
{
  QCPRange range;
  bool haveLower = true; // set to true, because 0 should always be visible in bar charts
  bool haveUpper = true; // set to true, because 0 should always be visible in bar charts
  
  double current;
  
  QCPBarDataMap::const_iterator it = mData->constBegin();
  while (it != mData->constEnd())
  {
    current = it.value().value + getBaseValue(it.value().key, it.value().value >= 0);
    if (inSignDomain == sdBoth || (inSignDomain == sdNegative && current < 0) || (inSignDomain == sdPositive && current > 0))
    {
      if (current < range.lower || !haveLower)
      {
        range.lower = current;
        haveLower = true;
      }
      if (current > range.upper || !haveUpper)
      {
        range.upper = current;
        haveUpper = true;
      }
    }
    ++it;
  }
  
  validRange = range.lower < range.upper;
  return range;
}
void QCPBars::moveAbove (QCPBars *bars)
Moves this bars plottable above bars. In other words, the bars of this plottable will appear above the bars of bars. The move target bars must use the same key and value axis as this plottable.
Inserting into and removing from existing bar stacking is handled gracefully. If bars already has a bars object below itself, this bars object is inserted between the two. If this bars object is already between two other bars, the two other bars will be stacked on top of each other after the operation.
To remove this bars plottable from any stacking, set bars to 0.
See also:
moveBelow, barBelow, barAbove
Definition at line 10008 of file qcustomplot.cpp.
References connectBars(), QCPAbstractPlottable::keyAxis(), mBarAbove, mBarBelow, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, and QCPAbstractPlottable::valueAxis().
{
  if (bars == this) return;
  if (bars && (bars->keyAxis() != mKeyAxis || bars->valueAxis() != mValueAxis))
  {
    qDebug() << Q_FUNC_INFO << "passed QCPBars* doesn't have same key and value axis as this QCPBars";
    return;
  }
  // remove from stacking:
  connectBars(mBarBelow, mBarAbove); // Note: also works if one (or both) of them is 0
  // if new bar given, insert this bar above it:
  if (bars)
  {
    if (bars->mBarAbove)
      connectBars(this, bars->mBarAbove);
    connectBars(bars, this);
  }
}
void QCPBars::moveBelow (QCPBars *bars)
Moves this bars plottable below bars. In other words, the bars of this plottable will appear below the bars of bars. The move target bars must use the same key and value axis as this plottable.
Inserting into and removing from existing bar stacking is handled gracefully. If bars already has a bars object below itself, this bars object is inserted between the two. If this bars object is already between two other bars, the two other bars will be stacked on top of each other after the operation.
To remove this bars plottable from any stacking, set bars to 0.
See also:
moveBelow, barAbove, barBelow
Definition at line 9975 of file qcustomplot.cpp.
References connectBars(), QCPAbstractPlottable::keyAxis(), mBarAbove, mBarBelow, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, and QCPAbstractPlottable::valueAxis().
{
  if (bars == this) return;
  if (bars->keyAxis() != mKeyAxis || bars->valueAxis() != mValueAxis)
  {
    qDebug() << Q_FUNC_INFO << "passed QCPBars* doesn't have same key and value axis as this QCPBars";
    return;
  }
  // remove from stacking:
  connectBars(mBarBelow, mBarAbove); // Note: also works if one (or both) of them is 0
  // if new bar given, insert this bar below it:
  if (bars)
  {
    if (bars->mBarBelow)
      connectBars(bars->mBarBelow, this);
    connectBars(this, bars);
  }
}
void QCPBars::removeData (doublefromKey, doubletoKey)
Removes all data points with key between fromKey and toKey. if fromKey is greater or equal to toKey, the function does nothing. To remove a single data point with known key, use removeData(double key).
See also:
addData, clearData
Definition at line 10104 of file qcustomplot.cpp.
References mData.
{
  if (fromKey >= toKey || mData->isEmpty()) return;
  QCPBarDataMap::iterator it = mData->upperBound(fromKey);
  QCPBarDataMap::iterator itEnd = mData->upperBound(toKey);
  while (it != itEnd)
    it = mData->erase(it);
}
void QCPBars::removeData (doublekey)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes a single data point at key. If the position is not known with absolute precision, consider using removeData(double fromKey, double toKey) with a small fuzziness interval around the suspected position, depeding on the precision with which the key is known.
See also:
addData, clearData
Definition at line 10121 of file qcustomplot.cpp.
References mData.
{
  mData->remove(key);
}
void QCPBars::removeDataAfter (doublekey)
Removes all data points with key greater than key.
See also:
addData, clearData
Definition at line 10089 of file qcustomplot.cpp.
References mData.
{
  if (mData->isEmpty()) return;
  QCPBarDataMap::iterator it = mData->upperBound(key);
  while (it != mData->end())
    it = mData->erase(it);
}
void QCPBars::removeDataBefore (doublekey)
Removes all data points with key smaller than key.
See also:
addData, clearData
Definition at line 10078 of file qcustomplot.cpp.
References key, and mData.
{
  QCPBarDataMap::iterator it = mData->begin();
  while (it != mData->end() && it.key() < key)
    it = mData->erase(it);
}
double QCPBars::selectTest (const QPointF &pos) const [virtual]
This function is used to decide whether a click hits a plottable or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the plottable (e.g. to the scatters/lines of a graph). If the plottable is either invisible, contains no data or the distance couldn't be determined, -1.0 is returned. setSelectable has no influence on the return value of this function.
If the plottable is represented not by single lines but by an area like QCPBars or QCPStatisticalBox, a click inside the area returns a constant value greater zero (typically 99% of the selectionTolerance of the parent QCustomPlot). If the click lies outside the area, this function returns -1.0.
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs.
See also:
setSelected, QCustomPlot::setInteractions
Implements QCPAbstractPlottable.
Definition at line 10136 of file qcustomplot.cpp.
References getBaseValue(), mData, QCPLayerable::mParentPlot, mWidth, and QCPAbstractPlottable::pixelsToCoords().
{
  QCPBarDataMap::ConstIterator it;
  double posKey, posValue;
  pixelsToCoords(pos, posKey, posValue);
  for (it = mData->constBegin(); it != mData->constEnd(); ++it)
  {
    double baseValue = getBaseValue(it.key(), it.value().value >=0);
    QCPRange keyRange(it.key()-mWidth*0.5, it.key()+mWidth*0.5);
    QCPRange valueRange(baseValue, baseValue+it.value().value);
    if (keyRange.contains(posKey) && valueRange.contains(posValue))
      return mParentPlot->selectionTolerance()*0.99;
  }
  return -1;
}
void QCPBars::setData (QCPBarDataMap *data, boolcopy = false)
Replaces the current data with the provided data. If copy is set to true, data points in data will only be copied. if false, the plottable takes ownership of the passed data and replaces the internal data pointer with it. This is significantly faster than copying for large datasets.
Definition at line 9929 of file qcustomplot.cpp.
References data(), and mData.
{
  if (copy)
  {
    *mData = *data;
  } else
  {
    delete mData;
    mData = data;
  }
}
void QCPBars::setData (const QVector< double > &key, const QVector< double > &value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided points in key and value tuples. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
Definition at line 9947 of file qcustomplot.cpp.
References QCPBarData::key, and mData.
{
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  QCPBarData newData;
  for (int i=0; i<n; ++i)
  {
    newData.key = key[i];
    newData.value = value[i];
    mData->insertMulti(newData.key, newData);
  }
}
void QCPBars::setWidth (doublewidth)
Sets the width of the bars in plot (key) coordinates.
Definition at line 9917 of file qcustomplot.cpp.
References mWidth, and width().
{
  mWidth = width;
}
double QCPBars::width () const [inline]
Definition at line 658 of file qcustomplot.h.
Referenced by setWidth().
{ return mWidth; }
Friends And Related Function Documentation
friend class QCPLegend [friend]
Definition at line 697 of file qcustomplot.h.
friend class QCustomPlot [friend]
Definition at line 696 of file qcustomplot.h.
Member Data Documentation
QCPBars * QCPBars::mBarAbove [protected]
Definition at line 685 of file qcustomplot.h.
Referenced by connectBars(), moveAbove(), moveBelow(), and ~QCPBars().
QCPBars* QCPBars::mBarBelow [protected]
Definition at line 685 of file qcustomplot.h.
Referenced by connectBars(), getBaseValue(), moveAbove(), moveBelow(), and ~QCPBars().
QCPBarDataMap* QCPBars::mData [protected]
Definition at line 683 of file qcustomplot.h.
Referenced by addData(), clearData(), draw(), getBaseValue(), getKeyRange(), getValueRange(), QCPBars(), removeData(), removeDataAfter(), removeDataBefore(), selectTest(), setData(), and ~QCPBars().
double QCPBars::mWidth [protected]
Definition at line 684 of file qcustomplot.h.
Referenced by draw(), getBarPolygon(), getBaseValue(), getKeyRange(), QCPBars(), selectTest(), and setWidth().
Author
Generated automatically by Doxygen for AQ0X from the source code.