.TH "QCPCurveData" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCPCurveData \- 
.PP
Holds the data of one single data point for \fBQCPCurve\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qcustomplot\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQCPCurveData\fP ()"
.br
.RI "\fIConstructs a curve data point with t, key and value set to zero\&. \fP"
.ti -1c
.RI "\fBQCPCurveData\fP (double \fBt\fP, double \fBkey\fP, double \fBvalue\fP)"
.br
.RI "\fIConstructs a curve data point with the specified \fIt\fP, \fIkey\fP and \fIvalue\fP\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBt\fP"
.br
.ti -1c
.RI "double \fBkey\fP"
.br
.ti -1c
.RI "double \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds the data of one single data point for \fBQCPCurve\fP\&. 

The stored data is: 
.PD 0

.IP "\(bu" 2
\fIt:\fP the free parameter of the curve at this curve point (cp\&. the mathematical vector \fI(x(t), y(t))\fP) 
.IP "\(bu" 2
\fIkey:\fP coordinate on the key axis of this curve point 
.IP "\(bu" 2
\fIvalue:\fP coordinate on the value axis of this curve point
.PP
\fBSee also:\fP
.RS 4
\fBQCPCurveDataMap\fP 
.RE
.PP

.PP
Definition at line 162 of file qcustomplot\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QCPCurveData::QCPCurveData ()"

.PP
Constructs a curve data point with t, key and value set to zero\&. 
.PP
Definition at line 241 of file qcustomplot\&.cpp\&.
.PP
.nf
241                            :
242   t(0),
243   key(0),
244   value(0)
245 {
246 }
.fi
.SS "QCPCurveData::QCPCurveData (doublet, doublekey, doublevalue)"

.PP
Constructs a curve data point with the specified \fIt\fP, \fIkey\fP and \fIvalue\fP\&. 
.PP
Definition at line 251 of file qcustomplot\&.cpp\&.
.PP
.nf
251                                                              :
252   t(t),
253   key(key),
254   value(value)
255 {
256 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "double QCPCurveData::key"

.PP
Definition at line 167 of file qcustomplot\&.h\&.
.PP
Referenced by QCPCurve::addData()\&.
.SS "double QCPCurveData::t"

.PP
Definition at line 167 of file qcustomplot\&.h\&.
.PP
Referenced by QCPCurve::addData(), and QCPCurve::setData()\&.
.SS "double QCPCurveData::value"

.PP
Definition at line 167 of file qcustomplot\&.h\&.
.PP
Referenced by QCPCurve::addData()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
