QCPCurve
NAME
QCPCurve -
A plottable representing a parametric curve in a plot.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPAbstractPlottable.
Public Types
enum LineStyle { lsNone, lsLine }
Defines how the curve's line is represented visually in the plot.
Public Member Functions
QCPCurve (QCPAxis *keyAxis, QCPAxis *valueAxis)
Constructs a curve which uses keyAxis as its key axis ('x') and valueAxis as its value axis ('y').
virtual ~QCPCurve ()
const QCPCurveDataMap * data () const
QCP::ScatterStyle scatterStyle () const
double scatterSize () const
QPixmap scatterPixmap () const
LineStyle lineStyle () const
void setData (QCPCurveDataMap *data, bool copy=false)
Replaces the current data with the provided data.
void setData (const QVector< double > &t, const QVector< double > &key, const QVector< double > &value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided points in t, key and value tuples. "
void setData (const QVector< double > &key, const QVector< double > &value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided key and value pairs. "
void setScatterStyle (QCP::ScatterStyle style)
Sets the visual appearance of single data points in the plot.
void setScatterSize (double size)
This defines how big (in pixels) single scatters are drawn, if scatter style (setScatterStyle) isn't QCP::ssNone, QCP::ssDot or QCP::ssPixmap.
void setScatterPixmap (const QPixmap &pixmap)
If the scatter style (setScatterStyle) is set to ssPixmap, this function defines the QPixmap that will be drawn centered on the data point coordinate.
void setLineStyle (LineStyle style)
Sets how the single data points are connected in the plot or how they are represented visually apart from the scatter symbol.
void addData (const QCPCurveDataMap &dataMap)
Adds the provided data points in dataMap to the current data.
void addData (const QCPCurveData &data)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point in data to the current data.
void addData (double t, double key, double value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point as t, key and value tuple to the current data.
void addData (double key, double value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Adds the provided single data point as key and value pair to the current data The t parameter of the data point is set to the t of the last data point plus 1. "
void addData (const QVector< double > &ts, const QVector< double > &keys, const QVector< double > &values)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided data points as t, key and value tuples to the current data.
void removeDataBefore (double t)
Removes all data points with curve parameter t smaller than t.
void removeDataAfter (double t)
Removes all data points with curve parameter t greater than t.
void removeData (double fromt, double tot)
Removes all data points with curve parameter t between fromt and tot.
void removeData (double t)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes a single data point at curve parameter t. "
virtual void clearData ()
Removes all data points.
virtual double selectTest (const QPointF &pos) const
This function is used to decide whether a click hits a plottable or not.
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual void drawLegendIcon (QCPPainter *painter, const QRect &rect) const
virtual void drawScatterPlot (QCPPainter *painter, const QVector< QPointF > *pointData) const
void getCurveData (QVector< QPointF > *lineData) const
double pointDistance (const QPointF &pixelPoint) const
QPointF outsideCoordsToPixels (double key, double value, int region) const
virtual QCPRange getKeyRange (bool &validRange, SignDomain inSignDomain=sdBoth) const
virtual QCPRange getValueRange (bool &validRange, SignDomain inSignDomain=sdBoth) const
Protected Attributes
QCPCurveDataMap * mData
QCP::ScatterStyle mScatterStyle
double mScatterSize
QPixmap mScatterPixmap
LineStyle mLineStyle
Friends
class QCustomPlot
class QCPLegend
Additional Inherited Members
Detailed Description
A plottable representing a parametric curve in a plot.
To plot data, assign it with the setData or addData functions.
Changing the appearance
The appearance of the curve is determined by the pen and the brush (setPen, setBrush).
Usage
Like all data representing objects in QCustomPlot, the QCPCurve is a plottable (QCPAbstractPlottable). So the plottable-interface of QCustomPlot applies (QCustomPlot::plottable, QCustomPlot::addPlottable, QCustomPlot::removePlottable, etc.)
Usually, you first create an instance:
QCPCurve *newCurve = new QCPCurve(customPlot->xAxis, customPlot->yAxis);
 add it to the customPlot with QCustomPlot::addPlottable:
customPlot->addPlottable(newCurve);
 and then modify the properties of the newly created plottable, e.g.:
newCurve->setName("Fermat's Spiral");
newCurve->setData(tData, xData, yData);
Definition at line 582 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPCurve::LineStyle
Defines how the curve's line is represented visually in the plot. The line is drawn with the current pen of the curve (setPen).
See also:
setLineStyle
Enumerator
lsNone
No line is drawn between data points (e.g. only scatters)
lsLine
Data points are connected with a straight line.
Definition at line 591 of file qcustomplot.h.
                 { lsNone,
                   lsLine
                 };
Constructor & Destructor Documentation
QCPCurve::QCPCurve (QCPAxis *keyAxis, QCPAxis *valueAxis) [explicit]
Constructs a curve which uses keyAxis as its key axis ('x') and valueAxis as its value axis ('y'). keyAxis and valueAxis must reside in the same QCustomPlot instance and not have the same orientation. If either of these restrictions is violated, a corresponding message is printed to the debug output (qDebug), the construction is not aborted, though.
The constructed QCPCurve can be added to the plot with QCustomPlot::addPlottable, QCustomPlot then takes ownership of the graph.
Definition at line 9216 of file qcustomplot.cpp.
References lsLine, QCPAbstractPlottable::mBrush, mData, QCPAbstractPlottable::mPen, QCPAbstractPlottable::mSelectedBrush, QCPAbstractPlottable::mSelectedPen, setLineStyle(), setScatterSize(), setScatterStyle(), and QCP::ssNone.
                                                       :
  QCPAbstractPlottable(keyAxis, valueAxis)
{
  mData = new QCPCurveDataMap;
  mPen.setColor(Qt::blue);
  mPen.setStyle(Qt::SolidLine);
  mBrush.setColor(Qt::blue);
  mBrush.setStyle(Qt::NoBrush);
  mSelectedPen = mPen;
  mSelectedPen.setWidthF(2.5);
  mSelectedPen.setColor(QColor(80, 80, 255)); // lighter than Qt::blue of mPen
  mSelectedBrush = mBrush;
  
  setScatterSize(6);
  setScatterStyle(QCP::ssNone);
  setLineStyle(lsLine);
}
QCPCurve::~QCPCurve () [virtual]
Definition at line 9234 of file qcustomplot.cpp.
References mData.
{
  delete mData;
}
Member Function Documentation
void QCPCurve::addData (const QCPCurveDataMap &dataMap)
Adds the provided data points in dataMap to the current data.
See also:
removeData
Definition at line 9349 of file qcustomplot.cpp.
References mData.
{
  mData->unite(dataMap);
}
void QCPCurve::addData (const QCPCurveData &data)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point in data to the current data.
See also:
removeData
Definition at line 9358 of file qcustomplot.cpp.
References mData, and QCPCurveData::t.
{
  mData->insertMulti(data.t, data);
}
void QCPCurve::addData (doublet, doublekey, doublevalue)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point as t, key and value tuple to the current data.
See also:
removeData
Definition at line 9367 of file qcustomplot.cpp.
References key, QCPCurveData::key, mData, QCPCurveData::t, value, and QCPCurveData::value.
{
  QCPCurveData newData;
  newData.t = t;
  newData.key = key;
  newData.value = value;
  mData->insertMulti(newData.t, newData);
}
void QCPCurve::addData (doublekey, doublevalue)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Adds the provided single data point as key and value pair to the current data The t parameter of the data point is set to the t of the last data point plus 1. If there is no last data point, t will be set to 0.
See also:
removeData
Definition at line 9384 of file qcustomplot.cpp.
References key, QCPCurveData::key, mData, QCPCurveData::t, value, and QCPCurveData::value.
{
  QCPCurveData newData;
  if (!mData->isEmpty())
    newData.t = (mData->constEnd()-1).key()+1;
  else
    newData.t = 0;
  newData.key = key;
  newData.value = value;
  mData->insertMulti(newData.t, newData);
}
void QCPCurve::addData (const QVector< double > &ts, const QVector< double > &keys, const QVector< double > &values)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided data points as t, key and value tuples to the current data.
See also:
removeData
Definition at line 9400 of file qcustomplot.cpp.
References mData, and QCPCurveData::t.
{
  int n = ts.size();
  n = qMin(n, keys.size());
  n = qMin(n, values.size());
  QCPCurveData newData;
  for (int i=0; i<n; ++i)
  {
    newData.t = ts[i];
    newData.key = keys[i];
    newData.value = values[i];
    mData->insertMulti(newData.t, newData);
  }
}
void QCPCurve::clearData () [virtual]
Removes all data points.
See also:
removeData, removeDataAfter, removeDataBefore
Implements QCPAbstractPlottable.
Definition at line 9472 of file qcustomplot.cpp.
References mData.
{
  mData->clear();
}
const QCPCurveDataMap* QCPCurve::data () const [inline]
Definition at line 598 of file qcustomplot.h.
Referenced by setData().
{ return mData; }
void QCPCurve::draw (QCPPainter *painter) [protected], [virtual]
Draws this plottable with the provided painter. Called by QCustomPlot::draw on all its visible plottables.
The cliprect of the provided painter is set to the axis rect of the key/value axis of this plottable (what clipRect returns), before this function is called.
Implements QCPAbstractPlottable.
Definition at line 9487 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::applyFillAntialiasingHint(), color(), QCPPainter::drawLine(), drawScatterPlot(), getCurveData(), lsNone, QCPAbstractPlottable::mainBrush(), QCPAbstractPlottable::mainPen(), mData, mLineStyle, QCPLayerable::mParentPlot, mScatterStyle, QCPPainter::pdfExportMode(), QCPPainter::setPen(), and QCP::ssNone.
{
  if (mData->isEmpty()) return;
  
  // allocate line vector:
  QVector<QPointF> *lineData = new QVector<QPointF>;
  // fill with curve data:
  getCurveData(lineData);
  // draw curve fill:
  if (mainBrush().style() != Qt::NoBrush && mainBrush().color().alpha() != 0)
  {
    applyFillAntialiasingHint(painter);
    painter->setPen(Qt::NoPen);
    painter->setBrush(mainBrush());
    painter->drawPolygon(QPolygonF(*lineData));
  }
  // draw curve line:
  if (mLineStyle != lsNone && mainPen().style() != Qt::NoPen && mainPen().color().alpha() != 0)
  {
    applyDefaultAntialiasingHint(painter);
    painter->setPen(mainPen());
    painter->setBrush(Qt::NoBrush);
    // if drawing solid line and not in PDF, use much faster line drawing instead of polyline:
    if (mParentPlot->plottingHints().testFlag(QCP::phFastPolylines) &&
        painter->pen().style() == Qt::SolidLine &&
        !painter->pdfExportMode())
    {
      for (int i=1; i<lineData->size(); ++i)
        painter->drawLine(lineData->at(i-1), lineData->at(i));
    } else
    {
      painter->drawPolyline(QPolygonF(*lineData));
    }
  }
  // draw scatters:
  if (mScatterStyle != QCP::ssNone)
    drawScatterPlot(painter, lineData);
  // free allocated line data:
  delete lineData;
}
void QCPCurve::drawLegendIcon (QCPPainter *painter, const QRect &rect) const [protected], [virtual]
called by QCPLegend::draw (via QCPPlottableLegendItem::draw) to create a graphical representation of this plottable inside rect, next to the plottable name.
Implements QCPAbstractPlottable.
Definition at line 9529 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::applyFillAntialiasingHint(), QCPAbstractPlottable::applyScattersAntialiasingHint(), QCPPainter::drawLine(), QCPPainter::drawScatter(), lsNone, QCPAbstractPlottable::mBrush, mLineStyle, QCPAbstractPlottable::mPen, mScatterPixmap, mScatterSize, mScatterStyle, QCPPainter::setPen(), QCP::ssNone, and QCP::ssPixmap.
{
  // draw fill:
  if (mBrush.style() != Qt::NoBrush)
  {
    applyFillAntialiasingHint(painter);
    painter->fillRect(QRectF(rect.left(), rect.top()+rect.height()/2.0, rect.width(), rect.height()/3.0), mBrush);
  }
  // draw line vertically centered:
  if (mLineStyle != lsNone)
  {
    applyDefaultAntialiasingHint(painter);
    painter->setPen(mPen);
    painter->drawLine(QLineF(rect.left(), rect.top()+rect.height()/2.0, rect.right()+5, rect.top()+rect.height()/2.0)); // +5 on x2 else last segment is missing from dashed/dotted pens
  }
  // draw scatter symbol:
  if (mScatterStyle != QCP::ssNone)
  {
    if (mScatterStyle == QCP::ssPixmap && (mScatterPixmap.size().width() > rect.width() || mScatterPixmap.size().height() > rect.height()))
    {
      // handle pixmap scatters that are larger than legend icon rect separately.
      // We resize them and draw them manually, instead of calling drawScatter:
      QSize newSize = mScatterPixmap.size();
      newSize.scale(rect.size(), Qt::KeepAspectRatio);
      QRect targetRect;
      targetRect.setSize(newSize);
      targetRect.moveCenter(rect.center());
      bool smoothBackup = painter->testRenderHint(QPainter::SmoothPixmapTransform);
      painter->setRenderHint(QPainter::SmoothPixmapTransform, true);
      painter->drawPixmap(targetRect, mScatterPixmap);
      painter->setRenderHint(QPainter::SmoothPixmapTransform, smoothBackup);
    } else
    {
      applyScattersAntialiasingHint(painter);
      painter->setPen(mPen);
      painter->drawScatter(QRectF(rect).center().x(), QRectF(rect).center().y(), mScatterSize, mScatterStyle);
    }
  }
}
void QCPCurve::drawScatterPlot (QCPPainter *painter, const QVector< QPointF > *pointData) const [protected], [virtual]
Draws scatter symbols at every data point passed in pointData. scatter symbols are independent of the line style and are always drawn if scatter style is not QCP::ssNone.
Definition at line 9574 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyScattersAntialiasingHint(), QCPPainter::drawScatter(), QCPAbstractPlottable::mainBrush(), QCPAbstractPlottable::mainPen(), mScatterPixmap, mScatterSize, mScatterStyle, QCPPainter::setPen(), and QCPPainter::setScatterPixmap().
Referenced by draw().
{
  // draw scatter point symbols:
  applyScattersAntialiasingHint(painter);
  painter->setPen(mainPen());
  painter->setBrush(mainBrush());
  painter->setScatterPixmap(mScatterPixmap);
  for (int i=0; i<pointData->size(); ++i)
    painter->drawScatter(pointData->at(i).x(), pointData->at(i).y(), mScatterSize, mScatterStyle);
}
void QCPCurve::getCurveData (QVector< QPointF > *lineData) const [protected]
called by QCPCurve::draw to generate a point vector (pixels) which represents the line of the curve. Line segments that aren't visible in the current axis rect are handled in an optimized way.
Definition at line 9591 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels(), key, QCPRange::lower, QCPAbstractPlottable::mBrush, mData, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, outsideCoordsToPixels(), QCPAxis::range(), QCPRange::upper, and value.
Referenced by draw(), and pointDistance().
{
  /* Extended sides of axis rect R divide space into 9 regions:
     1__|_4_|__7
     2__|_R_|__8
     3 | 6 | 9
     General idea: If the two points of a line segment are in the same region (that is not R), the line segment corner is removed.
     Curves outside R become straight lines closely outside of R which greatly reduces drawing time, yet keeps the look of lines and
     fills inside R consistent.
     The region R has index 5.
  */
  lineData->reserve(mData->size());
  QCPCurveDataMap::const_iterator it;
  int lastRegion = 5;
  int currentRegion = 5;
  double RLeft = mKeyAxis->range().lower;
  double RRight = mKeyAxis->range().upper;
  double RBottom = mValueAxis->range().lower;
  double RTop = mValueAxis->range().upper;
  double x, y; // current key/value
  bool addedLastAlready = true;
  bool firstPoint = true; // first point must always be drawn, to make sure fill works correctly
  for (it = mData->constBegin(); it != mData->constEnd(); ++it)
  {
    x = it.value().key;
    y = it.value().value;
    // determine current region:
    if (x < RLeft) // region 123
    {
      if (y > RTop)
        currentRegion = 1;
      else if (y < RBottom)
        currentRegion = 3;
      else
        currentRegion = 2;
    } else if (x > RRight) // region 789
    {
      if (y > RTop)
        currentRegion = 7;
      else if (y < RBottom)
        currentRegion = 9;
      else
        currentRegion = 8;
    } else // region 456
    {
      if (y > RTop)
        currentRegion = 4;
      else if (y < RBottom)
        currentRegion = 6;
      else
        currentRegion = 5;
    }
    
    /*
      Watch out, the next part is very tricky. It modifies the curve such that it seems like the
      whole thing is still drawn, but actually the points outside the axisRect are simplified
      ("optimized") greatly. There are some subtle special cases when line segments are large and
      thereby each subsequent point may be in a different region or even skip some.
    */
    // determine whether to keep current point:
    if (currentRegion == 5 || (firstPoint && mBrush.style() != Qt::NoBrush)) // current is in R, add current and last if it wasn't added already
    {
      if (!addedLastAlready) // in case curve just entered R, make sure the last point outside R is also drawn correctly
        lineData->append(coordsToPixels((it-1).value().key, (it-1).value().value)); // add last point to vector
      else if (lastRegion != 5) // added last already. If that's the case, we probably added it at optimized position. So go back and make sure it's at original position (else the angle changes under which this segment enters R)
      {
        if (!firstPoint) // because on firstPoint, currentRegion is 5 and addedLastAlready is true, although there is no last point
          lineData->replace(lineData->size()-1, coordsToPixels((it-1).value().key, (it-1).value().value));
      }
      lineData->append(coordsToPixels(it.value().key, it.value().value)); // add current point to vector
      addedLastAlready = true; // so in next iteration, we don't add this point twice
    } else if (currentRegion != lastRegion) // changed region, add current and last if not added already
    {
      // using outsideCoordsToPixels instead of coorsToPixels for optimized point placement (places points just outside axisRect instead of potentially far away)
      
      // if we're coming from R or we skip diagonally over the corner regions (so line might still be visible in R), we can't place points optimized
      if (lastRegion == 5 || // coming from R
          ((lastRegion==2 && currentRegion==4) || (lastRegion==4 && currentRegion==2)) || // skip top left diagonal
          ((lastRegion==4 && currentRegion==8) || (lastRegion==8 && currentRegion==4)) || // skip top right diagonal
          ((lastRegion==8 && currentRegion==6) || (lastRegion==6 && currentRegion==8)) || // skip bottom right diagonal
          ((lastRegion==6 && currentRegion==2) || (lastRegion==2 && currentRegion==6)) // skip bottom left diagonal
          )
      {
        // always add last point if not added already, original:
        if (!addedLastAlready)
          lineData->append(coordsToPixels((it-1).value().key, (it-1).value().value));
        // add current point, original:
        lineData->append(coordsToPixels(it.value().key, it.value().value));
      } else // no special case that forbids optimized point placement, so do it:
      {
        // always add last point if not added already, optimized:
        if (!addedLastAlready)
          lineData->append(outsideCoordsToPixels((it-1).value().key, (it-1).value().value, currentRegion));
        // add current point, optimized:
        lineData->append(outsideCoordsToPixels(it.value().key, it.value().value, currentRegion));
      }
      addedLastAlready = true; // so that if next point enters 5, or crosses another region boundary, we don't add this point twice
    } else // neither in R, nor crossed a region boundary, skip current point
    {
      addedLastAlready = false;
    }
    lastRegion = currentRegion;
    firstPoint = false;
  }
  // If curve ends outside R, we want to add very last point so the fill looks like it should when the curve started inside R:
  if (lastRegion != 5 && mBrush.style() != Qt::NoBrush && !mData->isEmpty())
    lineData->append(coordsToPixels((mData->constEnd()-1).value().key, (mData->constEnd()-1).value().value));
}
QCPRange QCPCurve::getKeyRange (bool &validRange, SignDomaininSignDomain = sdBoth) const [protected], [virtual]
called by rescaleAxes functions to get the full data key bounds. For logarithmic plots, one can set inSignDomain to either sdNegative or sdPositive in order to restrict the returned range to that sign domain. E.g. when only negative range is wanted, set inSignDomain to sdNegative and all positive points will be ignored for range calculation. For no restriction, just set inSignDomain to sdBoth (default). validRange is an output parameter that indicates whether a proper range could be found or not. If this is false, you shouldn't use the returned range (e.g. no points in data).
See also:
rescaleAxes, getValueRange
Implements QCPAbstractPlottable.
Definition at line 9767 of file qcustomplot.cpp.
References QCPRange::lower, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
{
  QCPRange range;
  bool haveLower = false;
  bool haveUpper = false;
  
  double current;
  
  QCPCurveDataMap::const_iterator it = mData->constBegin();
  while (it != mData->constEnd())
  {
    current = it.value().key;
    if (inSignDomain == sdBoth || (inSignDomain == sdNegative && current < 0) || (inSignDomain == sdPositive && current > 0))
    {
      if (current < range.lower || !haveLower)
      {
        range.lower = current;
        haveLower = true;
      }
      if (current > range.upper || !haveUpper)
      {
        range.upper = current;
        haveUpper = true;
      }
    }
    ++it;
  }
  
  validRange = haveLower && haveUpper;
  return range;
}
QCPRange QCPCurve::getValueRange (bool &validRange, SignDomaininSignDomain = sdBoth) const [protected], [virtual]
called by rescaleAxes functions to get the full data value bounds. For logarithmic plots, one can set inSignDomain to either sdNegative or sdPositive in order to restrict the returned range to that sign domain. E.g. when only negative range is wanted, set inSignDomain to sdNegative and all positive points will be ignored for range calculation. For no restriction, just set inSignDomain to sdBoth (default). validRange is an output parameter that indicates whether a proper range could be found or not. If this is false, you shouldn't use the returned range (e.g. no points in data).
See also:
rescaleAxes, getKeyRange
Implements QCPAbstractPlottable.
Definition at line 9800 of file qcustomplot.cpp.
References QCPRange::lower, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
{
  QCPRange range;
  bool haveLower = false;
  bool haveUpper = false;
  
  double current;
  
  QCPCurveDataMap::const_iterator it = mData->constBegin();
  while (it != mData->constEnd())
  {
    current = it.value().value;
    if (inSignDomain == sdBoth || (inSignDomain == sdNegative && current < 0) || (inSignDomain == sdPositive && current > 0))
    {
      if (current < range.lower || !haveLower)
      {
        range.lower = current;
        haveLower = true;
      }
      if (current > range.upper || !haveUpper)
      {
        range.upper = current;
        haveUpper = true;
      }
    }
    ++it;
  }
  
  validRange = haveLower && haveUpper;
  return range;
}
LineStyle QCPCurve::lineStyle () const [inline]
Definition at line 602 of file qcustomplot.h.
{ return mLineStyle; }
QPointF QCPCurve::outsideCoordsToPixels (doublekey, doublevalue, intregion) const [protected]
This is a specialized coordsToPixels function for points that are outside the visible axisRect and just crossing a boundary (since getCurveData reduces non-visible curve segments to those line segments that cross region boundaries, see documentation there). It only uses the coordinate parallel to the region boundary of the axisRect. The other coordinate is picked 10 pixels outside the axisRect. Together with the optimization in getCurveData this improves performance for large curves (or zoomed in ones) significantly while keeping the illusion the whole curve and its filling is still being drawn for the viewer.
Definition at line 9743 of file qcustomplot.cpp.
References QCPAxis::axisRect(), axisRect(), QCPAbstractPlottable::coordsToPixels(), QCPAbstractPlottable::mKeyAxis, and QCPAbstractPlottable::mValueAxis.
Referenced by getCurveData().
{
  int margin = 10;
  QRect axisRect = mKeyAxis->axisRect() | mValueAxis->axisRect();
  QPointF result = coordsToPixels(key, value);
  switch (region)
  {
    case 2: result.setX(axisRect.left()-margin); break; // left
    case 8: result.setX(axisRect.right()+margin); break; // right
    case 4: result.setY(axisRect.top()-margin); break; // top
    case 6: result.setY(axisRect.bottom()+margin); break; // bottom
    case 1: result.setX(axisRect.left()-margin);
            result.setY(axisRect.top()-margin); break; // top left
    case 7: result.setX(axisRect.right()+margin);
            result.setY(axisRect.top()-margin); break; // top right
    case 9: result.setX(axisRect.right()+margin);
            result.setY(axisRect.bottom()+margin); break; // bottom right
    case 3: result.setX(axisRect.left()-margin);
            result.setY(axisRect.bottom()+margin); break; // bottom left
  }
  return result;
}
double QCPCurve::pointDistance (const QPointF &pixelPoint) const [protected]
Calculates the (minimum) distance (in pixels) the curve's representation has from the given pixelPoint in pixels. This is used to determine whether the curve was clicked or not, e.g. in selectTest.
Definition at line 9706 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels(), QCPAbstractPlottable::distSqrToLine(), getCurveData(), mData, and QCPAbstractPlottable::mName.
Referenced by selectTest().
{
  if (mData->isEmpty())
  {
    qDebug() << Q_FUNC_INFO << "requested point distance on curve" << mName << "without data";
    return 500;
  }
  if (mData->size() == 1)
  {
    QPointF dataPoint = coordsToPixels(mData->constBegin().key(), mData->constBegin().value().value);
    return QVector2D(dataPoint-pixelPoint).length();
  }
  
  // calculate minimum distance to line segments:
  QVector<QPointF> *lineData = new QVector<QPointF>;
  getCurveData(lineData);
  double minDistSqr = std::numeric_limits<double>::max();
  for (int i=0; i<lineData->size()-1; ++i)
  {
    double currentDistSqr = distSqrToLine(lineData->at(i), lineData->at(i+1), pixelPoint);
    if (currentDistSqr < minDistSqr)
      minDistSqr = currentDistSqr;
  }
  delete lineData;
  return sqrt(minDistSqr);
}
void QCPCurve::removeData (doublefromt, doubletot)
Removes all data points with curve parameter t between fromt and tot. if fromt is greater or equal to tot, the function does nothing. To remove a single data point with known t, use removeData(double t).
See also:
addData, clearData
Definition at line 9445 of file qcustomplot.cpp.
References mData.
{
  if (fromt >= tot || mData->isEmpty()) return;
  QCPCurveDataMap::iterator it = mData->upperBound(fromt);
  QCPCurveDataMap::iterator itEnd = mData->upperBound(tot);
  while (it != itEnd)
    it = mData->erase(it);
}
void QCPCurve::removeData (doublet)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes a single data point at curve parameter t. If the position is not known with absolute precision, consider using removeData(double fromt, double tot) with a small fuzziness interval around the suspected position, depeding on the precision with which the curve parameter is known.
See also:
addData, clearData
Definition at line 9463 of file qcustomplot.cpp.
References mData.
{
  mData->remove(t);
}
void QCPCurve::removeDataAfter (doublet)
Removes all data points with curve parameter t greater than t.
See also:
addData, clearData
Definition at line 9430 of file qcustomplot.cpp.
References mData.
{
  if (mData->isEmpty()) return;
  QCPCurveDataMap::iterator it = mData->upperBound(t);
  while (it != mData->end())
    it = mData->erase(it);
}
void QCPCurve::removeDataBefore (doublet)
Removes all data points with curve parameter t smaller than t.
See also:
addData, clearData
Definition at line 9419 of file qcustomplot.cpp.
References mData.
{
  QCPCurveDataMap::iterator it = mData->begin();
  while (it != mData->end() && it.key() < t)
    it = mData->erase(it);
}
QPixmap QCPCurve::scatterPixmap () const [inline]
Definition at line 601 of file qcustomplot.h.
{ return mScatterPixmap; }
double QCPCurve::scatterSize () const [inline]
Definition at line 600 of file qcustomplot.h.
{ return mScatterSize; }
QCP::ScatterStyle QCPCurve::scatterStyle () const [inline]
Definition at line 599 of file qcustomplot.h.
{ return mScatterStyle; }
double QCPCurve::selectTest (const QPointF &pos) const [virtual]
This function is used to decide whether a click hits a plottable or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the plottable (e.g. to the scatters/lines of a graph). If the plottable is either invisible, contains no data or the distance couldn't be determined, -1.0 is returned. setSelectable has no influence on the return value of this function.
If the plottable is represented not by single lines but by an area like QCPBars or QCPStatisticalBox, a click inside the area returns a constant value greater zero (typically 99% of the selectionTolerance of the parent QCustomPlot). If the click lies outside the area, this function returns -1.0.
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs.
See also:
setSelected, QCustomPlot::setInteractions
Implements QCPAbstractPlottable.
Definition at line 9478 of file qcustomplot.cpp.
References mData, QCPLayerable::mVisible, and pointDistance().
{
  if (mData->isEmpty() || !mVisible)
    return -1;
  
  return pointDistance(pos);
}
void QCPCurve::setData (QCPCurveDataMap *data, boolcopy = false)
Replaces the current data with the provided data. If copy is set to true, data points in data will only be copied. if false, the plottable takes ownership of the passed data and replaces the internal data pointer with it. This is significantly faster than copying for large datasets.
Definition at line 9246 of file qcustomplot.cpp.
References data(), and mData.
{
  if (copy)
  {
    *mData = *data;
  } else
  {
    delete mData;
    mData = data;
  }
}
void QCPCurve::setData (const QVector< double > &t, const QVector< double > &key, const QVector< double > &value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided points in t, key and value tuples. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
Definition at line 9264 of file qcustomplot.cpp.
References mData, and QCPCurveData::t.
{
  mData->clear();
  int n = t.size();
  n = qMin(n, key.size());
  n = qMin(n, value.size());
  QCPCurveData newData;
  for (int i=0; i<n; ++i)
  {
    newData.t = t[i];
    newData.key = key[i];
    newData.value = value[i];
    mData->insertMulti(newData.t, newData);
  }
}
void QCPCurve::setData (const QVector< double > &key, const QVector< double > &value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided key and value pairs. The t parameter of each data point will be set to the integer index of the respective key/value pair.
Definition at line 9285 of file qcustomplot.cpp.
References mData, and QCPCurveData::t.
{
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  QCPCurveData newData;
  for (int i=0; i<n; ++i)
  {
    newData.t = i; // no t vector given, so we assign t the index of the key/value pair
    newData.key = key[i];
    newData.value = value[i];
    mData->insertMulti(newData.t, newData);
  }
}
void QCPCurve::setLineStyle (QCPCurve::LineStylestyle)
Sets how the single data points are connected in the plot or how they are represented visually apart from the scatter symbol. For scatter-only plots, set style to lsNone and setScatterStyle to the desired scatter style.
See also:
setScatterStyle
Definition at line 9340 of file qcustomplot.cpp.
References mLineStyle.
Referenced by QCPCurve().
{
  mLineStyle = style;
}
void QCPCurve::setScatterPixmap (const QPixmap &pixmap)
If the scatter style (setScatterStyle) is set to ssPixmap, this function defines the QPixmap that will be drawn centered on the data point coordinate.
See also:
ScatterStyle
Definition at line 9328 of file qcustomplot.cpp.
References mScatterPixmap.
{
  mScatterPixmap = pixmap;
}
void QCPCurve::setScatterSize (doublesize)
This defines how big (in pixels) single scatters are drawn, if scatter style (setScatterStyle) isn't QCP::ssNone, QCP::ssDot or QCP::ssPixmap. Floating point values are allowed for fine grained control over optical appearance with antialiased painting.
See also:
ScatterStyle
Definition at line 9317 of file qcustomplot.cpp.
References mScatterSize.
Referenced by QCPCurve().
{
  mScatterSize = size;
}
void QCPCurve::setScatterStyle (QCP::ScatterStylestyle)
Sets the visual appearance of single data points in the plot. If set to QCP::ssNone, no scatter points are drawn (e.g. for line-only-plots with appropriate line style).
See also:
ScatterStyle, setLineStyle
Definition at line 9305 of file qcustomplot.cpp.
References mScatterStyle.
Referenced by QCPCurve().
{
  mScatterStyle = style;
}
Friends And Related Function Documentation
friend class QCPLegend [friend]
Definition at line 647 of file qcustomplot.h.
friend class QCustomPlot [friend]
Definition at line 646 of file qcustomplot.h.
Member Data Documentation
QCPCurveDataMap* QCPCurve::mData [protected]
Definition at line 627 of file qcustomplot.h.
Referenced by addData(), clearData(), draw(), getCurveData(), getKeyRange(), getValueRange(), pointDistance(), QCPCurve(), removeData(), removeDataAfter(), removeDataBefore(), selectTest(), setData(), and ~QCPCurve().
LineStyle QCPCurve::mLineStyle [protected]
Definition at line 631 of file qcustomplot.h.
Referenced by draw(), drawLegendIcon(), and setLineStyle().
QPixmap QCPCurve::mScatterPixmap [protected]
Definition at line 630 of file qcustomplot.h.
Referenced by drawLegendIcon(), drawScatterPlot(), and setScatterPixmap().
double QCPCurve::mScatterSize [protected]
Definition at line 629 of file qcustomplot.h.
Referenced by drawLegendIcon(), drawScatterPlot(), and setScatterSize().
QCP::ScatterStyle QCPCurve::mScatterStyle [protected]
Definition at line 628 of file qcustomplot.h.
Referenced by draw(), drawLegendIcon(), drawScatterPlot(), and setScatterStyle().
Author
Generated automatically by Doxygen for AQ0X from the source code.