QCPGraph
NAME
QCPGraph -
A plottable representing a graph in a plot.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPAbstractPlottable.
Public Types
enum LineStyle { lsNone, lsLine, lsStepLeft, lsStepRight, lsStepCenter, lsImpulse }
Defines how the graph's line is represented visually in the plot.
Public Member Functions
Q_ENUMS (LineStyle) enum ErrorType
Defines what kind of error bars are drawn for each data point.
Q_ENUMS (ErrorType) explicit QCPGraph(QCPAxis *keyAxis
virtual ~QCPGraph ()
const QCPDataMap * data () const
LineStyle lineStyle () const
QCP::ScatterStyle scatterStyle () const
double scatterSize () const
const QPixmap scatterPixmap () const
ErrorType errorType () const
QPen errorPen () const
double errorBarSize () const
bool errorBarSkipSymbol () const
QCPGraph * channelFillGraph () const
void setData (QCPDataMap *data, bool copy=false)
Replaces the current data with the provided data.
void setData (const QVector< double > &key, const QVector< double > &value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided points in key and value pairs. "
void setDataKeyError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &keyError)
Replaces the current data with the provided points in key and value pairs.
void setDataKeyError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &keyErrorMinus, const QVector< double > &keyErrorPlus)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Replaces the current data with the provided points in key and value pairs.
void setDataValueError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &valueError)
Replaces the current data with the provided points in key and value pairs.
void setDataValueError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &valueErrorMinus, const QVector< double > &valueErrorPlus)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Replaces the current data with the provided points in key and value pairs.
void setDataBothError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &keyError, const QVector< double > &valueError)
Replaces the current data with the provided points in key and value pairs.
void setDataBothError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &keyErrorMinus, const QVector< double > &keyErrorPlus, const QVector< double > &valueErrorMinus, const QVector< double > &valueErrorPlus)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Replaces the current data with the provided points in key and value pairs.
void setLineStyle (LineStyle ls)
Sets how the single data points are connected in the plot or how they are represented visually apart from the scatter symbol.
void setScatterStyle (QCP::ScatterStyle ss)
Sets the visual appearance of single data points in the plot.
void setScatterSize (double size)
This defines how big (in pixels) single scatters are drawn, if scatter style (setScatterStyle) isn't QCP::ssNone, QCP::ssDot or QCP::ssPixmap.
void setScatterPixmap (const QPixmap &pixmap)
If the scatter style (setScatterStyle) is set to ssPixmap, this function defines the QPixmap that will be drawn centered on the data point coordinate.
void setErrorType (ErrorType errorType)
Sets which kind of error bars (Key Error, Value Error or both) should be drawn on each data point.
void setErrorPen (const QPen &pen)
Sets the pen with which the error bars will be drawn.
void setErrorBarSize (double size)
Sets the width of the handles at both ends of an error bar in pixels.
void setErrorBarSkipSymbol (bool enabled)
If enabled is set to true, the error bar will not be drawn as a solid line under the scatter symbol but leave some free space around the symbol.
void setChannelFillGraph (QCPGraph *targetGraph)
Sets the target graph for filling the area between this graph and targetGraph with the current brush (setBrush).
void addData (const QCPDataMap &dataMap)
Adds the provided data points in dataMap to the current data.
void addData (const QCPData &data)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point in data to the current data.
void addData (double key, double value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point as key and value pair to the current data.
void addData (const QVector< double > &keys, const QVector< double > &values)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided data points as key and value pairs to the current data.
void removeDataBefore (double key)
Removes all data points with keys smaller than key.
void removeDataAfter (double key)
Removes all data points with keys greater than key.
void removeData (double fromKey, double toKey)
Removes all data points with keys between fromKey and toKey.
void removeData (double key)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes a single data point at key. "
virtual void clearData ()
Removes all data points.
virtual double selectTest (const QPointF &pos) const
This function is used to decide whether a click hits a plottable or not.
virtual void rescaleAxes (bool onlyEnlarge, bool includeErrorBars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows to define whether error bars are taken into consideration when determining the new axis range. "
virtual void rescaleKeyAxis (bool onlyEnlarge, bool includeErrorBars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows to define whether error bars (of kind QCPGraph::etKey) are taken into consideration when determining the new axis range. "
virtual void rescaleValueAxis (bool onlyEnlarge, bool includeErrorBars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows to define whether error bars (of kind QCPGraph::etValue) are taken into consideration when determining the new axis range. "
Public Attributes
QCPAxis * valueAxis
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual void drawLegendIcon (QCPPainter *painter, const QRect &rect) const
void getPlotData (QVector< QPointF > *lineData, QVector< QCPData > *pointData) const
void getScatterPlotData (QVector< QCPData > *pointData) const
void getLinePlotData (QVector< QPointF > *lineData, QVector< QCPData > *pointData) const
void getStepLeftPlotData (QVector< QPointF > *lineData, QVector< QCPData > *pointData) const
void getStepRightPlotData (QVector< QPointF > *lineData, QVector< QCPData > *pointData) const
void getStepCenterPlotData (QVector< QPointF > *lineData, QVector< QCPData > *pointData) const
void getImpulsePlotData (QVector< QPointF > *lineData, QVector< QCPData > *pointData) const
void drawFill (QCPPainter *painter, QVector< QPointF > *lineData) const
void drawScatterPlot (QCPPainter *painter, QVector< QCPData > *pointData) const
void drawLinePlot (QCPPainter *painter, QVector< QPointF > *lineData) const
void drawImpulsePlot (QCPPainter *painter, QVector< QPointF > *lineData) const
void drawError (QCPPainter *painter, double x, double y, const QCPData &data) const
void getVisibleDataBounds (QCPDataMap::const_iterator &lower, QCPDataMap::const_iterator &upper, int &count) const
void addFillBasePoints (QVector< QPointF > *lineData) const
void removeFillBasePoints (QVector< QPointF > *lineData) const
QPointF lowerFillBasePoint (double lowerKey) const
QPointF upperFillBasePoint (double upperKey) const
const QPolygonF getChannelFillPolygon (const QVector< QPointF > *lineData) const
int findIndexBelowX (const QVector< QPointF > *data, double x) const
int findIndexAboveX (const QVector< QPointF > *data, double x) const
int findIndexBelowY (const QVector< QPointF > *data, double y) const
int findIndexAboveY (const QVector< QPointF > *data, double y) const
double pointDistance (const QPointF &pixelPoint) const
virtual QCPRange getKeyRange (bool &validRange, SignDomain inSignDomain=sdBoth) const
virtual QCPRange getValueRange (bool &validRange, SignDomain inSignDomain=sdBoth) const
virtual QCPRange getKeyRange (bool &validRange, SignDomain inSignDomain, bool includeErrors) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Allows to specify whether the error bars should be included in the range calculation.
virtual QCPRange getValueRange (bool &validRange, SignDomain inSignDomain, bool includeErrors) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Allows to specify whether the error bars should be included in the range calculation.
Protected Attributes
QCPDataMap * mData
QPen mErrorPen
LineStyle mLineStyle
QCP::ScatterStyle mScatterStyle
double mScatterSize
QPixmap mScatterPixmap
ErrorType mErrorType
double mErrorBarSize
bool mErrorBarSkipSymbol
QCPGraph * mChannelFillGraph
Friends
class QCustomPlot
class QCPLegend
Additional Inherited Members
Detailed Description
A plottable representing a graph in a plot.
Usually QCustomPlot creates it internally via QCustomPlot::addGraph and the resulting instance is accessed via QCustomPlot::graph.
To plot data, assign it with the setData or addData functions.
Changing the appearance
The appearance of the graph is mainly determined by the line style, scatter style, brush and pen of the graph (setLineStyle, setScatterStyle, setBrush, setPen).
Filling under or between graphs
QCPGraph knows two types of fills: Normal graph fills towards the zero-value-line parallel to the key axis of the graph, and fills between two graphs, called channel fills. To enable a fill, just set a brush with setBrush which is neither Qt::NoBrush nor fully transparent.
By default, a normal fill towards the zero-value-line will be drawn. To set up a channel fill between this graph and another one, call setChannelFillGraph with the other graph as parameter.
See also:
QCustomPlot::addGraph, QCustomPlot::graph, QCPLegend::addGraph
Definition at line 449 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPGraph::LineStyle
Defines how the graph's line is represented visually in the plot. The line is drawn with the current pen of the graph (setPen).
See also:
setLineStyle
Enumerator
lsNone
data points are not connected with any lines (e.g. data only represented < with symbols according to the scatter style, see setScatterStyle)
lsLine
data points are connected by a straight line
lsStepLeft
line is drawn as steps where the step height is the value of the left data point
lsStepRight
line is drawn as steps where the step height is the value of the right data point
lsStepCenter
line is drawn as steps where the step is in between two data points
lsImpulse
each data point is represented by a line parallel to the value axis, which reaches from the data point to the zero-value-line
Definition at line 458 of file qcustomplot.h.
                 { lsNone
                  ,lsLine
                  ,lsStepLeft
                  ,lsStepRight
                  ,lsStepCenter
                  ,lsImpulse
                 };
Constructor & Destructor Documentation
QCPGraph::~QCPGraph () [virtual]
Definition at line 352 of file qcustomplot.cpp.
References mData, and QCPLayerable::mParentPlot.
{
  if (mParentPlot)
  {
    // if another graph has a channel fill towards this graph, set it to zero
    for (int i=0; i<mParentPlot->graphCount(); ++i)
    {
      if (mParentPlot->graph(i)->channelFillGraph() == this)
        mParentPlot->graph(i)->setChannelFillGraph(0);
    }
  }
  delete mData;
}
Member Function Documentation
void QCPGraph::addData (const QCPDataMap &dataMap)
Adds the provided data points in dataMap to the current data.
See also:
removeData
Definition at line 695 of file qcustomplot.cpp.
References mData.
{
  mData->unite(dataMap);
}
void QCPGraph::addData (const QCPData &data)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point in data to the current data.
See also:
removeData
Definition at line 704 of file qcustomplot.cpp.
References mData.
{
  mData->insertMulti(data.key, data);
}
void QCPGraph::addData (doublekey, doublevalue)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point as key and value pair to the current data.
See also:
removeData
Definition at line 713 of file qcustomplot.cpp.
References key, mData, and value.
{
  QCPData newData;
  newData.key = key;
  newData.value = value;
  mData->insertMulti(newData.key, newData);
}
void QCPGraph::addData (const QVector< double > &keys, const QVector< double > &values)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided data points as key and value pairs to the current data.
See also:
removeData
Definition at line 725 of file qcustomplot.cpp.
References mData.
{
  int n = qMin(keys.size(), values.size());
  QCPData newData;
  for (int i=0; i<n; ++i)
  {
    newData.key = keys[i];
    newData.value = values[i];
    mData->insertMulti(newData.key, newData);
  }
}
void QCPGraph::addFillBasePoints (QVector< QPointF > *lineData) const [protected]
The line data vector generated by e.g. getLinePlotData contains only the line that connects the data points. If the graph needs to be filled, two additional points need to be added at the value-zero-line in the lower and upper key positions, the graph reaches. This function calculates these points and adds them to the end of lineData. Since the fill is typically drawn before the line stroke, these added points need to be removed again after the fill is done, with the removeFillBasePoints function.
The expanding of lineData by two points will not cause unnecessary memory reallocations, because the data vector generation functions (getLinePlotData etc.) reserve two extra points when they allocate memory for lineData.
See also:
removeFillBasePoints, lowerFillBasePoint, upperFillBasePoint
Definition at line 1696 of file qcustomplot.cpp.
References lowerFillBasePoint(), QCPAbstractPlottable::mKeyAxis, QCPAxis::orientation(), and upperFillBasePoint().
Referenced by drawFill().
{
  // append points that close the polygon fill at the key axis:
  if (mKeyAxis->orientation() == Qt::Vertical)
  {
    *lineData << upperFillBasePoint(lineData->last().y());
    *lineData << lowerFillBasePoint(lineData->first().y());
  } else
  {
    *lineData << upperFillBasePoint(lineData->last().x());
    *lineData << lowerFillBasePoint(lineData->first().x());
  }
}
QCPGraph* QCPGraph::channelFillGraph () const [inline]
Definition at line 490 of file qcustomplot.h.
{ return mChannelFillGraph; }
void QCPGraph::clearData () [virtual]
Removes all data points.
See also:
removeData, removeDataAfter, removeDataBefore
Implements QCPAbstractPlottable.
Definition at line 793 of file qcustomplot.cpp.
References mData.
{
  mData->clear();
}
const QCPDataMap* QCPGraph::data () const [inline]
Definition at line 481 of file qcustomplot.h.
Referenced by setData(), and QCPItemTracer::updatePosition().
{ return mData; }
void QCPGraph::draw (QCPPainter *painter) [protected], [virtual]
Draws this plottable with the provided painter. Called by QCustomPlot::draw on all its visible plottables.
The cliprect of the provided painter is set to the axis rect of the key/value axis of this plottable (what clipRect returns), before this function is called.
Implements QCPAbstractPlottable.
Definition at line 881 of file qcustomplot.cpp.
References drawFill(), drawImpulsePlot(), drawLinePlot(), drawScatterPlot(), getPlotData(), lsImpulse, lsNone, mData, QCPAbstractPlottable::mKeyAxis, mLineStyle, mScatterStyle, QCPAxis::range(), QCPRange::size(), and QCP::ssNone.
{
  if (mKeyAxis->range().size() <= 0 || mData->isEmpty()) return;
  if (mLineStyle == lsNone && mScatterStyle == QCP::ssNone) return;
  
  // allocate line and (if necessary) point vectors:
  QVector<QPointF> *lineData = new QVector<QPointF>;
  QVector<QCPData> *pointData = 0;
  if (mScatterStyle != QCP::ssNone)
    pointData = new QVector<QCPData>;
  
  // fill vectors with data appropriate to plot style:
  getPlotData(lineData, pointData);
  // draw fill of graph:
  drawFill(painter, lineData);
  
  // draw line:
  if (mLineStyle == lsImpulse)
    drawImpulsePlot(painter, lineData);
  else if (mLineStyle != lsNone)
    drawLinePlot(painter, lineData); // also step plots can be drawn as a line plot
  
  // draw scatters:
  if (pointData)
    drawScatterPlot(painter, pointData);
  
  // free allocated line and point vectors:
  delete lineData;
  if (pointData)
    delete pointData;
}
void QCPGraph::drawError (QCPPainter *painter, doublex, doubley, const QCPData &data) const [protected]
called by the scatter drawing function (drawScatterPlot) to draw the error bars on one data point. x and y pixel positions of the data point are passed since they are already known in pixel coordinates in the drawing function, so we save some extra coordToPixel transforms here. data is therefore only used for the errors, not key and value.
Definition at line 1558 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), QCPPainter::drawLine(), mErrorBarSize, mErrorBarSkipSymbol, mErrorType, QCPAbstractPlottable::mKeyAxis, mScatterSize, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), and QCPAxis::rangeReversed().
Referenced by drawScatterPlot().
{
  double a, b; // positions of error bar bounds in pixels
  double barWidthHalf = mErrorBarSize*0.5;
  double skipSymbolMargin = mScatterSize*1.25; // pixels left blank per side, when mErrorBarSkipSymbol is true
  if (mKeyAxis->orientation() == Qt::Vertical)
  {
    // draw key error vertically and value error horizontally
    if (mErrorType == etKey || mErrorType == etBoth)
    {
      a = mKeyAxis->coordToPixel(data.key-data.keyErrorMinus);
      b = mKeyAxis->coordToPixel(data.key+data.keyErrorPlus);
      if (mKeyAxis->rangeReversed())
        qSwap(a,b);
      // draw spine:
      if (mErrorBarSkipSymbol)
      {
        if (a-y > skipSymbolMargin) // don't draw spine if error is so small it's within skipSymbolmargin
          painter->drawLine(QLineF(x, a, x, y+skipSymbolMargin));
        if (y-b > skipSymbolMargin)
          painter->drawLine(QLineF(x, y-skipSymbolMargin, x, b));
      } else
        painter->drawLine(QLineF(x, a, x, b));
      // draw handles:
      painter->drawLine(QLineF(x-barWidthHalf, a, x+barWidthHalf, a));
      painter->drawLine(QLineF(x-barWidthHalf, b, x+barWidthHalf, b));
    }
    if (mErrorType == etValue || mErrorType == etBoth)
    {
      a = mValueAxis->coordToPixel(data.value-data.valueErrorMinus);
      b = mValueAxis->coordToPixel(data.value+data.valueErrorPlus);
      if (mValueAxis->rangeReversed())
        qSwap(a,b);
      // draw spine:
      if (mErrorBarSkipSymbol)
      {
        if (x-a > skipSymbolMargin) // don't draw spine if error is so small it's within skipSymbolmargin
          painter->drawLine(QLineF(a, y, x-skipSymbolMargin, y));
        if (b-x > skipSymbolMargin)
          painter->drawLine(QLineF(x+skipSymbolMargin, y, b, y));
      } else
        painter->drawLine(QLineF(a, y, b, y));
      // draw handles:
      painter->drawLine(QLineF(a, y-barWidthHalf, a, y+barWidthHalf));
      painter->drawLine(QLineF(b, y-barWidthHalf, b, y+barWidthHalf));
    }
  } else // mKeyAxis->orientation() is Qt::Horizontal
  {
    // draw value error vertically and key error horizontally
    if (mErrorType == etKey || mErrorType == etBoth)
    {
      a = mKeyAxis->coordToPixel(data.key-data.keyErrorMinus);
      b = mKeyAxis->coordToPixel(data.key+data.keyErrorPlus);
      if (mKeyAxis->rangeReversed())
        qSwap(a,b);
      // draw spine:
      if (mErrorBarSkipSymbol)
      {
        if (x-a > skipSymbolMargin) // don't draw spine if error is so small it's within skipSymbolmargin
          painter->drawLine(QLineF(a, y, x-skipSymbolMargin, y));
        if (b-x > skipSymbolMargin)
          painter->drawLine(QLineF(x+skipSymbolMargin, y, b, y));
      } else
        painter->drawLine(QLineF(a, y, b, y));
      // draw handles:
      painter->drawLine(QLineF(a, y-barWidthHalf, a, y+barWidthHalf));
      painter->drawLine(QLineF(b, y-barWidthHalf, b, y+barWidthHalf));
    }
    if (mErrorType == etValue || mErrorType == etBoth)
    {
      a = mValueAxis->coordToPixel(data.value-data.valueErrorMinus);
      b = mValueAxis->coordToPixel(data.value+data.valueErrorPlus);
      if (mValueAxis->rangeReversed())
        qSwap(a,b);
      // draw spine:
      if (mErrorBarSkipSymbol)
      {
        if (a-y > skipSymbolMargin) // don't draw spine if error is so small it's within skipSymbolmargin
          painter->drawLine(QLineF(x, a, x, y+skipSymbolMargin));
        if (y-b > skipSymbolMargin)
          painter->drawLine(QLineF(x, y-skipSymbolMargin, x, b));
      } else
        painter->drawLine(QLineF(x, a, x, b));
      // draw handles:
      painter->drawLine(QLineF(x-barWidthHalf, a, x+barWidthHalf, a));
      painter->drawLine(QLineF(x-barWidthHalf, b, x+barWidthHalf, b));
    }
  }
}
void QCPGraph::drawFill (QCPPainter *painter, QVector< QPointF > *lineData) const [protected]
Draws the fill of the graph with the specified brush. If the fill is a normal 'base' fill, i.e. under the graph toward the zero-value-line, only the lineData is required (and two extra points at the zero-value-line, which are added by addFillBasePoints and removed by removeFillBasePoints after the fill drawing is done).
If the fill is a channel fill between this graph and another graph (mChannelFillGraph), the more complex polygon is calculated with the getChannelFillPolygon function.
See also:
drawLinePlot
Definition at line 1421 of file qcustomplot.cpp.
References addFillBasePoints(), QCPAbstractPlottable::applyFillAntialiasingHint(), color(), getChannelFillPolygon(), lsImpulse, QCPAbstractPlottable::mainBrush(), mChannelFillGraph, mLineStyle, removeFillBasePoints(), and QCPPainter::setPen().
Referenced by draw().
{
  if (mLineStyle == lsImpulse) return; // fill doesn't make sense for impulse plot
  if (mainBrush().style() == Qt::NoBrush || mainBrush().color().alpha() == 0) return;
  
  applyFillAntialiasingHint(painter);
  if (!mChannelFillGraph)
  {
    // draw base fill under graph, fill goes all the way to the zero-value-line:
    addFillBasePoints(lineData);
    painter->setPen(Qt::NoPen);
    painter->setBrush(mainBrush());
    painter->drawPolygon(QPolygonF(*lineData));
    removeFillBasePoints(lineData);
  } else
  {
    // draw channel fill between this graph and mChannelFillGraph:
    painter->setPen(Qt::NoPen);
    painter->setBrush(mainBrush());
    painter->drawPolygon(getChannelFillPolygon(lineData));
  }
}
void QCPGraph::drawImpulsePlot (QCPPainter *painter, QVector< QPointF > *lineData) const [protected]
Draws impulses graphs from the provided data, i.e. it connects all line pairs in lineData, which was created by getImpulsePlotData.
See also:
drawScatterPlot, drawLinePlot
Definition at line 1537 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), color(), QCPAbstractPlottable::mainPen(), QCPAbstractPlottable::pen(), and QCPPainter::setPen().
Referenced by draw().
{
  // draw impulses:
  if (mainPen().style() != Qt::NoPen && mainPen().color().alpha() != 0)
  {
    applyDefaultAntialiasingHint(painter);
    QPen pen = mainPen();
    pen.setCapStyle(Qt::FlatCap); // so impulse line doesn't reach beyond zero-line
    painter->setPen(pen);
    painter->setBrush(Qt::NoBrush);
    painter->drawLines(*lineData);
  }
}
void QCPGraph::drawLegendIcon (QCPPainter *painter, const QRect &rect) const [protected], [virtual]
called by QCPLegend::draw (via QCPPlottableLegendItem::draw) to create a graphical representation of this plottable inside rect, next to the plottable name.
Implements QCPAbstractPlottable.
Definition at line 915 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::applyFillAntialiasingHint(), QCPAbstractPlottable::applyScattersAntialiasingHint(), QCPPainter::drawLine(), QCPPainter::drawScatter(), lsNone, QCPAbstractPlottable::mBrush, mLineStyle, QCPAbstractPlottable::mPen, mScatterPixmap, mScatterSize, mScatterStyle, QCPPainter::setPen(), QCP::ssNone, and QCP::ssPixmap.
{
  // draw fill:
  if (mBrush.style() != Qt::NoBrush)
  {
    applyFillAntialiasingHint(painter);
    painter->fillRect(QRectF(rect.left(), rect.top()+rect.height()/2.0, rect.width(), rect.height()/3.0), mBrush);
  }
  // draw line vertically centered:
  if (mLineStyle != lsNone)
  {
    applyDefaultAntialiasingHint(painter);
    painter->setPen(mPen);
    painter->drawLine(QLineF(rect.left(), rect.top()+rect.height()/2.0, rect.right()+5, rect.top()+rect.height()/2.0)); // +5 on x2 else last segment is missing from dashed/dotted pens
  }
  // draw scatter symbol:
  if (mScatterStyle != QCP::ssNone)
  {
    if (mScatterStyle == QCP::ssPixmap && (mScatterPixmap.size().width() > rect.width() || mScatterPixmap.size().height() > rect.height()))
    {
      // handle pixmap scatters that are larger than legend icon rect separately.
      // We resize them and draw them manually, instead of calling drawScatter:
      QSize newSize = mScatterPixmap.size();
      newSize.scale(rect.size(), Qt::KeepAspectRatio);
      QRect targetRect;
      targetRect.setSize(newSize);
      targetRect.moveCenter(rect.center());
      bool smoothBackup = painter->testRenderHint(QPainter::SmoothPixmapTransform);
      painter->setRenderHint(QPainter::SmoothPixmapTransform, true);
      painter->drawPixmap(targetRect, mScatterPixmap);
      painter->setRenderHint(QPainter::SmoothPixmapTransform, smoothBackup);
    } else
    {
      applyScattersAntialiasingHint(painter);
      painter->setPen(mPen);
      painter->drawScatter(QRectF(rect).center().x(), QRectF(rect).center().y(), mScatterSize, mScatterStyle);
    }
  }
}
void QCPGraph::drawLinePlot (QCPPainter *painter, QVector< QPointF > *lineData) const [protected]
Draws line graphs from the provided data. It connects all points in lineData, which was created by one of the 'get(...)PlotData' functions for line styles that require simple line connections between the point vector they create. These are for example getLinePlotData, getStepLeftPlotData, getStepRightPlotData and getStepCenterPlotData.
See also:
drawScatterPlot, drawImpulsePlot
Definition at line 1493 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), color(), QCPPainter::drawLine(), QCPAbstractPlottable::mainPen(), QCPLayerable::mParentPlot, QCPPainter::pdfExportMode(), and QCPPainter::setPen().
Referenced by draw().
{
  // draw line of graph:
  if (mainPen().style() != Qt::NoPen && mainPen().color().alpha() != 0)
  {
    applyDefaultAntialiasingHint(painter);
    painter->setPen(mainPen());
    painter->setBrush(Qt::NoBrush);
    
    /* Draws polyline in batches, currently not used:
    int p = 0;
    while (p < lineData->size())
    {
      int batch = qMin(25, lineData->size()-p);
      if (p != 0)
      {
        ++batch;
        --p; // to draw the connection lines between two batches
      }
      painter->drawPolyline(lineData->constData()+p, batch);
      p += batch;
    }
    */
    
    // if drawing solid line and not in PDF, use much faster line drawing instead of polyline:
    if (mParentPlot->plottingHints().testFlag(QCP::phFastPolylines) &&
        painter->pen().style() == Qt::SolidLine &&
        !painter->pdfExportMode())
    {
      for (int i=1; i<lineData->size(); ++i)
        painter->drawLine(lineData->at(i-1), lineData->at(i));
    } else
    {
      painter->drawPolyline(QPolygonF(*lineData));
    }
  }
}
void QCPGraph::drawScatterPlot (QCPPainter *painter, QVector< QCPData > *pointData) const [protected]
Draws scatter symbols at every data point passed in pointData. scatter symbols are independent of the line style and are always drawn if scatter style is not QCP::ssNone. Hence, the pointData vector is outputted by all 'get(...)PlotData' functions, together with the (line style dependent) line data.
See also:
drawLinePlot, drawImpulsePlot
Definition at line 1451 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyErrorBarsAntialiasingHint(), QCPAbstractPlottable::applyScattersAntialiasingHint(), QCPAxis::coordToPixel(), drawError(), QCPPainter::drawScatter(), QCPAbstractPlottable::mainBrush(), QCPAbstractPlottable::mainPen(), mErrorPen, mErrorType, QCPAbstractPlottable::mKeyAxis, mScatterPixmap, mScatterSize, mScatterStyle, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), QCPPainter::setPen(), and QCPPainter::setScatterPixmap().
Referenced by draw().
{
  // draw error bars:
  if (mErrorType != etNone)
  {
    applyErrorBarsAntialiasingHint(painter);
    painter->setPen(mErrorPen);
    if (mKeyAxis->orientation() == Qt::Vertical)
    {
      for (int i=0; i<pointData->size(); ++i)
        drawError(painter, mValueAxis->coordToPixel(pointData->at(i).value), mKeyAxis->coordToPixel(pointData->at(i).key), pointData->at(i));
    } else
    {
      for (int i=0; i<pointData->size(); ++i)
        drawError(painter, mKeyAxis->coordToPixel(pointData->at(i).key), mValueAxis->coordToPixel(pointData->at(i).value), pointData->at(i));
    }
  }
  
  // draw scatter point symbols:
  applyScattersAntialiasingHint(painter);
  painter->setPen(mainPen());
  painter->setBrush(mainBrush());
  painter->setScatterPixmap(mScatterPixmap);
  if (mKeyAxis->orientation() == Qt::Vertical)
  {
    for (int i=0; i<pointData->size(); ++i)
      painter->drawScatter(mValueAxis->coordToPixel(pointData->at(i).value), mKeyAxis->coordToPixel(pointData->at(i).key), mScatterSize, mScatterStyle);
  } else
  {
    for (int i=0; i<pointData->size(); ++i)
      painter->drawScatter(mKeyAxis->coordToPixel(pointData->at(i).key), mValueAxis->coordToPixel(pointData->at(i).value), mScatterSize, mScatterStyle);
  }
}
double QCPGraph::errorBarSize () const [inline]
Definition at line 488 of file qcustomplot.h.
{ return mErrorBarSize; }
bool QCPGraph::errorBarSkipSymbol () const [inline]
Definition at line 489 of file qcustomplot.h.
{ return mErrorBarSkipSymbol; }
QPen QCPGraph::errorPen () const [inline]
Definition at line 487 of file qcustomplot.h.
{ return mErrorPen; }
ErrorType QCPGraph::errorType () const [inline]
Definition at line 486 of file qcustomplot.h.
Referenced by setErrorType().
{ return mErrorType; }
int QCPGraph::findIndexAboveX (const QVector< QPointF > *data, doublex) const [protected]
Finds the smallest index of data, whose points x value is just above x. Assumes x values in data points are ordered ascending, as is the case when plotting with horizontal key axis. Used to calculate the channel fill polygon, see getChannelFillPolygon.
Definition at line 1983 of file qcustomplot.cpp.
Referenced by getChannelFillPolygon().
{
  for (int i=data->size()-1; i>=0; --i)
  {
    if (data->at(i).x() < x)
    {
      if (i<data->size()-1)
        return i+1;
      else
        return data->size()-1;
    }
  }
  return -1;
}
int QCPGraph::findIndexAboveY (const QVector< QPointF > *data, doubley) const [protected]
Finds the smallest index of data, whose points y value is just above y. Assumes y values in data points are ordered descending, as is the case when plotting with vertical key axis. Used to calculate the channel fill polygon, see getChannelFillPolygon.
Definition at line 2027 of file qcustomplot.cpp.
Referenced by getChannelFillPolygon().
{
  for (int i=0; i<data->size(); ++i)
  {
    if (data->at(i).y() < y)
    {
      if (i>0)
        return i-1;
      else
        return 0;
    }
  }
  return -1;
}
int QCPGraph::findIndexBelowX (const QVector< QPointF > *data, doublex) const [protected]
Finds the greatest index of data, whose points x value is just below x. Assumes x values in data points are ordered ascending, as is the case when plotting with horizontal key axis. Used to calculate the channel fill polygon, see getChannelFillPolygon.
Definition at line 2005 of file qcustomplot.cpp.
Referenced by getChannelFillPolygon().
{
  for (int i=0; i<data->size(); ++i)
  {
    if (data->at(i).x() > x)
    {
      if (i>0)
        return i-1;
      else
        return 0;
    }
  }
  return -1;
}
int QCPGraph::findIndexBelowY (const QVector< QPointF > *data, doubley) const [protected]
Finds the greatest index of data, whose points y value is just below y. Assumes y values in data points are ordered descending, as is the case when plotting with vertical key axis (since keys are ordered ascending). Used to calculate the channel fill polygon, see getChannelFillPolygon.
Definition at line 2120 of file qcustomplot.cpp.
Referenced by getChannelFillPolygon().
{
  for (int i=data->size()-1; i>=0; --i)
  {
    if (data->at(i).y() > y)
    {
      if (i<data->size()-1)
        return i+1;
      else
        return data->size()-1;
    }
  }
  return -1;
}
const QPolygonF QCPGraph::getChannelFillPolygon (const QVector< QPointF > *lineData) const [protected]
Generates the polygon needed for drawing channel fills between this graph (data passed via lineData) and the graph specified by mChannelFillGraph (data generated by calling its getPlotData function). May return an empty polygon if the key ranges have no overlap or fill target graph and this graph don't have same orientation (i.e. both key axes horizontal or both key axes vertical). For increased performance (due to implicit sharing), keep the returned QPolygonF const.
Definition at line 1849 of file qcustomplot.cpp.
References findIndexAboveX(), findIndexAboveY(), findIndexBelowX(), findIndexBelowY(), getPlotData(), mChannelFillGraph, QCPAbstractPlottable::mKeyAxis, and QCPAxis::orientation().
Referenced by drawFill().
{
  if (mChannelFillGraph->mKeyAxis->orientation() != mKeyAxis->orientation())
    return QPolygonF(); // don't have same axis orientation, can't fill that (Note: if keyAxis fits, valueAxis will fit too, because it's always orthogonal to keyAxis)
  
  if (lineData->isEmpty()) return QPolygonF();
  QVector<QPointF> otherData;
  mChannelFillGraph->getPlotData(&otherData, 0);
  if (otherData.isEmpty()) return QPolygonF();
  QVector<QPointF> thisData;
  thisData.reserve(lineData->size()+otherData.size()); // because we will join both vectors at end of this function
  for (int i=0; i<lineData->size(); ++i) // don't use the vector<<(vector), it squeezes internally, which ruins the performance tuning with reserve()
    thisData << lineData->at(i);
  
  // pointers to be able to swap them, depending which data range needs cropping:
  QVector<QPointF> *staticData = &thisData;
  QVector<QPointF> *croppedData = &otherData;
  
  // crop both vectors to ranges in which the keys overlap (which coord is key, depends on axisType):
  if (mKeyAxis->orientation() == Qt::Horizontal)
  {
    // x is key
    // if an axis range is reversed, the data point keys will be descending. Reverse them, since following algorithm assumes ascending keys:
    if (staticData->first().x() > staticData->last().x())
    {
      int size = staticData->size();
      for (int i=0; i<size/2; ++i)
        qSwap((*staticData)[i], (*staticData)[size-1-i]);
    }
    if (croppedData->first().x() > croppedData->last().x())
    {
      int size = croppedData->size();
      for (int i=0; i<size/2; ++i)
        qSwap((*croppedData)[i], (*croppedData)[size-1-i]);
    }
    // crop lower bound:
    if (staticData->first().x() < croppedData->first().x()) // other one must be cropped
      qSwap(staticData, croppedData);
    int lowBound = findIndexBelowX(croppedData, staticData->first().x());
    if (lowBound == -1) return QPolygonF(); // key ranges have no overlap
    croppedData->remove(0, lowBound);
    // set lowest point of cropped data to fit exactly key position of first static data
    // point via linear interpolation:
    if (croppedData->size() < 2) return QPolygonF(); // need at least two points for interpolation
    double slope;
    if (croppedData->at(1).x()-croppedData->at(0).x() != 0)
      slope = (croppedData->at(1).y()-croppedData->at(0).y())/(croppedData->at(1).x()-croppedData->at(0).x());
    else
      slope = 0;
    (*croppedData)[0].setY(croppedData->at(0).y()+slope*(staticData->first().x()-croppedData->at(0).x()));
    (*croppedData)[0].setX(staticData->first().x());
    
    // crop upper bound:
    if (staticData->last().x() > croppedData->last().x()) // other one must be cropped
      qSwap(staticData, croppedData);
    int highBound = findIndexAboveX(croppedData, staticData->last().x());
    if (highBound == -1) return QPolygonF(); // key ranges have no overlap
    croppedData->remove(highBound+1, croppedData->size()-(highBound+1));
    // set highest point of cropped data to fit exactly key position of last static data
    // point via linear interpolation:
    if (croppedData->size() < 2) return QPolygonF(); // need at least two points for interpolation
    int li = croppedData->size()-1; // last index
    if (croppedData->at(li).x()-croppedData->at(li-1).x() != 0)
      slope = (croppedData->at(li).y()-croppedData->at(li-1).y())/(croppedData->at(li).x()-croppedData->at(li-1).x());
    else
      slope = 0;
    (*croppedData)[li].setY(croppedData->at(li-1).y()+slope*(staticData->last().x()-croppedData->at(li-1).x()));
    (*croppedData)[li].setX(staticData->last().x());
  } else // mKeyAxis->orientation() == Qt::Vertical
  {
    // y is key
    // similar to "x is key" but switched x,y. Further, lower/upper meaning is inverted compared to x,
    // because in pixel coordinates, y increases from top to bottom, not bottom to top like data coordinate.
    // if an axis range is reversed, the data point keys will be descending. Reverse them, since following algorithm assumes ascending keys:
    if (staticData->first().y() < staticData->last().y())
    {
      int size = staticData->size();
      for (int i=0; i<size/2; ++i)
        qSwap((*staticData)[i], (*staticData)[size-1-i]);
    }
    if (croppedData->first().y() < croppedData->last().y())
    {
      int size = croppedData->size();
      for (int i=0; i<size/2; ++i)
        qSwap((*croppedData)[i], (*croppedData)[size-1-i]);
    }
    // crop lower bound:
    if (staticData->first().y() > croppedData->first().y()) // other one must be cropped
      qSwap(staticData, croppedData);
    int lowBound = findIndexAboveY(croppedData, staticData->first().y());
    if (lowBound == -1) return QPolygonF(); // key ranges have no overlap
    croppedData->remove(0, lowBound);
    // set lowest point of cropped data to fit exactly key position of first static data
    // point via linear interpolation:
    if (croppedData->size() < 2) return QPolygonF(); // need at least two points for interpolation
    double slope;
    if (croppedData->at(1).y()-croppedData->at(0).y() != 0) // avoid division by zero in step plots
      slope = (croppedData->at(1).x()-croppedData->at(0).x())/(croppedData->at(1).y()-croppedData->at(0).y());
    else
      slope = 0;
    (*croppedData)[0].setX(croppedData->at(0).x()+slope*(staticData->first().y()-croppedData->at(0).y()));
    (*croppedData)[0].setY(staticData->first().y());
    
    // crop upper bound:
    if (staticData->last().y() < croppedData->last().y()) // other one must be cropped
      qSwap(staticData, croppedData);
    int highBound = findIndexBelowY(croppedData, staticData->last().y());
    if (highBound == -1) return QPolygonF(); // key ranges have no overlap
    croppedData->remove(highBound+1, croppedData->size()-(highBound+1));
    // set highest point of cropped data to fit exactly key position of last static data
    // point via linear interpolation:
    if (croppedData->size() < 2) return QPolygonF(); // need at least two points for interpolation
    int li = croppedData->size()-1; // last index
    if (croppedData->at(li).y()-croppedData->at(li-1).y() != 0) // avoid division by zero in step plots
      slope = (croppedData->at(li).x()-croppedData->at(li-1).x())/(croppedData->at(li).y()-croppedData->at(li-1).y());
    else
      slope = 0;
    (*croppedData)[li].setX(croppedData->at(li-1).x()+slope*(staticData->last().y()-croppedData->at(li-1).y()));
    (*croppedData)[li].setY(staticData->last().y());
  }
  
  // return joined:
  for (int i=otherData.size()-1; i>=0; --i) // insert reversed, otherwise the polygon will be twisted
    thisData << otherData.at(i);
  return QPolygonF(thisData);
}
void QCPGraph::getImpulsePlotData (QVector< QPointF > *lineData, QVector< QCPData > *pointData) const [protected]
Places the raw data points needed for an impulse plot in lineData.
As for all plot data retrieval functions, pointData just contains all unaltered data (scatter) points that are visible, for drawing scatter points, if necessary. If drawing scatter points is disabled (i.e. scatter style QCP::ssNone), pass 0 as pointData, and the function will skip filling the vector.
See also:
drawImpulsePlot
Definition at line 1347 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), getVisibleDataBounds(), key, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, and QCPAxis::orientation().
Referenced by getPlotData().
{
  // get visible data range:
  QCPDataMap::const_iterator lower, upper;
  int dataCount;
  getVisibleDataBounds(lower, upper, dataCount);
  // prepare vectors:
  if (lineData)
  {
    // no need to reserve 2 extra points, because there is no fill for impulse plot
    lineData->resize(dataCount*2);
  }
  if (pointData)
    pointData->resize(dataCount);
  
  // position data points:
  QCPDataMap::const_iterator it = lower;
  QCPDataMap::const_iterator upperEnd = upper+1;
  int i = 0;
  int ipoint = 0;
  if (mKeyAxis->orientation() == Qt::Vertical)
  {
    double zeroPointX = mValueAxis->coordToPixel(0);
    double key;
    while (it != upperEnd)
    {
      if (pointData)
      {
        (*pointData)[ipoint] = it.value();
        ++ipoint;
      }
      key = mKeyAxis->coordToPixel(it.key());
      (*lineData)[i].setX(zeroPointX);
      (*lineData)[i].setY(key);
      ++i;
      (*lineData)[i].setX(mValueAxis->coordToPixel(it.value().value));
      (*lineData)[i].setY(key);
      ++i;
      ++it;
    }
  } else // key axis is horizontal
  {
    double zeroPointY = mValueAxis->coordToPixel(0);
    double key;
    while (it != upperEnd)
    {
      if (pointData)
      {
        (*pointData)[ipoint] = it.value();
        ++ipoint;
      }
      key = mKeyAxis->coordToPixel(it.key());
      (*lineData)[i].setX(key);
      (*lineData)[i].setY(zeroPointY);
      ++i;
      (*lineData)[i].setX(key);
      (*lineData)[i].setY(mValueAxis->coordToPixel(it.value().value));
      ++i;
      ++it;
    }
  }
}
QCPRange QCPGraph::getKeyRange (bool &validRange, SignDomaininSignDomain = sdBoth) const [protected], [virtual]
called by rescaleAxes functions to get the full data key bounds. For logarithmic plots, one can set inSignDomain to either sdNegative or sdPositive in order to restrict the returned range to that sign domain. E.g. when only negative range is wanted, set inSignDomain to sdNegative and all positive points will be ignored for range calculation. For no restriction, just set inSignDomain to sdBoth (default). validRange is an output parameter that indicates whether a proper range could be found or not. If this is false, you shouldn't use the returned range (e.g. no points in data).
See also:
rescaleAxes, getValueRange
Implements QCPAbstractPlottable.
Definition at line 2136 of file qcustomplot.cpp.
Referenced by rescaleKeyAxis().
{
  // just call the specialized version which takes an additional argument whether error bars
  // should also be taken into consideration for range calculation. We set this to true here.
  return getKeyRange(validRange, inSignDomain, true);
}
QCPRange QCPGraph::getKeyRange (bool &validRange, SignDomaininSignDomain, boolincludeErrors) const [protected], [virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Allows to specify whether the error bars should be included in the range calculation.
See also:
getKeyRange(bool &validRange, SignDomain inSignDomain)
Definition at line 2156 of file qcustomplot.cpp.
References QCPRange::lower, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
{
  QCPRange range;
  bool haveLower = false;
  bool haveUpper = false;
  
  double current, currentErrorMinus, currentErrorPlus;
  
  if (inSignDomain == sdBoth) // range may be anywhere
  {
    QCPDataMap::const_iterator it = mData->constBegin();
    while (it != mData->constEnd())
    {
      current = it.value().key;
      currentErrorMinus = (includeErrors ? it.value().keyErrorMinus : 0);
      currentErrorPlus = (includeErrors ? it.value().keyErrorPlus : 0);
      if (current-currentErrorMinus < range.lower || !haveLower)
      {
        range.lower = current-currentErrorMinus;
        haveLower = true;
      }
      if (current+currentErrorPlus > range.upper || !haveUpper)
      {
        range.upper = current+currentErrorPlus;
        haveUpper = true;
      }
      ++it;
    }
  } else if (inSignDomain == sdNegative) // range may only be in the negative sign domain
  {
    QCPDataMap::const_iterator it = mData->constBegin();
    while (it != mData->constEnd())
    {
      current = it.value().key;
      currentErrorMinus = (includeErrors ? it.value().keyErrorMinus : 0);
      currentErrorPlus = (includeErrors ? it.value().keyErrorPlus : 0);
      if ((current-currentErrorMinus < range.lower || !haveLower) && current-currentErrorMinus < 0)
      {
        range.lower = current-currentErrorMinus;
        haveLower = true;
      }
      if ((current+currentErrorPlus > range.upper || !haveUpper) && current+currentErrorPlus < 0)
      {
        range.upper = current+currentErrorPlus;
        haveUpper = true;
      }
      if (includeErrors) // in case point is in valid sign domain but errobars stretch beyond it, we still want to geht that point.
      {
        if ((current < range.lower || !haveLower) && current < 0)
        {
          range.lower = current;
          haveLower = true;
        }
        if ((current > range.upper || !haveUpper) && current < 0)
        {
          range.upper = current;
          haveUpper = true;
        }
      }
      ++it;
    }
  } else if (inSignDomain == sdPositive) // range may only be in the positive sign domain
  {
    QCPDataMap::const_iterator it = mData->constBegin();
    while (it != mData->constEnd())
    {
      current = it.value().key;
      currentErrorMinus = (includeErrors ? it.value().keyErrorMinus : 0);
      currentErrorPlus = (includeErrors ? it.value().keyErrorPlus : 0);
      if ((current-currentErrorMinus < range.lower || !haveLower) && current-currentErrorMinus > 0)
      {
        range.lower = current-currentErrorMinus;
        haveLower = true;
      }
      if ((current+currentErrorPlus > range.upper || !haveUpper) && current+currentErrorPlus > 0)
      {
        range.upper = current+currentErrorPlus;
        haveUpper = true;
      }
      if (includeErrors) // in case point is in valid sign domain but errobars stretch beyond it, we still want to get that point.
      {
        if ((current < range.lower || !haveLower) && current > 0)
        {
          range.lower = current;
          haveLower = true;
        }
        if ((current > range.upper || !haveUpper) && current > 0)
        {
          range.upper = current;
          haveUpper = true;
        }
      }
      ++it;
    }
  }
  
  validRange = haveLower && haveUpper;
  return range;
}
void QCPGraph::getLinePlotData (QVector< QPointF > *lineData, QVector< QCPData > *pointData) const [protected]
Places the raw data points needed for a normal linearly connected plot in lineData.
As for all plot data retrieval functions, pointData just contains all unaltered data (scatter) points that are visible, for drawing scatter points, if necessary. If drawing scatter points is disabled (i.e. scatter style QCP::ssNone), pass 0 as pointData, and the function will skip filling the vector.
See also:
drawLinePlot
Definition at line 1035 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), getVisibleDataBounds(), QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, and QCPAxis::orientation().
Referenced by getPlotData().
{
  // get visible data range:
  QCPDataMap::const_iterator lower, upper;
  int dataCount;
  getVisibleDataBounds(lower, upper, dataCount);
  // prepare vectors:
  if (lineData)
  {
    // added 2 to reserve memory for lower/upper fill base points that might be needed for fill
    lineData->reserve(dataCount+2);
    lineData->resize(dataCount);
  }
  if (pointData)
    pointData->resize(dataCount);
  // position data points:
  QCPDataMap::const_iterator it = lower;
  QCPDataMap::const_iterator upperEnd = upper+1;
  int i = 0;
  if (mKeyAxis->orientation() == Qt::Vertical)
  {
    while (it != upperEnd)
    {
      if (pointData)
        (*pointData)[i] = it.value();
      (*lineData)[i].setX(mValueAxis->coordToPixel(it.value().value));
      (*lineData)[i].setY(mKeyAxis->coordToPixel(it.key()));
      ++i;
      ++it;
    }
  } else // key axis is horizontal
  {
    while (it != upperEnd)
    {
      if (pointData)
        (*pointData)[i] = it.value();
      (*lineData)[i].setX(mKeyAxis->coordToPixel(it.key()));
      (*lineData)[i].setY(mValueAxis->coordToPixel(it.value().value));
      ++i;
      ++it;
    }
  }
}
void QCPGraph::getPlotData (QVector< QPointF > *lineData, QVector< QCPData > *pointData) const [protected]
This function branches out to the line style specific 'get(...)PlotData' functions, according to the line style of the graph.
Parameters:
lineData will be filled with raw points that will be drawn with the according draw functions, e.g. drawLinePlot and drawImpulsePlot. These aren't necessarily the original data points, since for step plots for example, additional points are needed for drawing lines that make up steps. If the line style of the graph is lsNone, the lineData vector will be left untouched.
pointData will be filled with the original data points so drawScatterPlot can draw the scatter symbols accordingly. If no scatters need to be drawn, i.e. scatter style is QCP::ssNone, pass 0 as pointData, and this step will be skipped.
See also:
getScatterPlotData, getLinePlotData, getStepLeftPlotData, getStepRightPlotData, getStepCenterPlotData, getImpulsePlotData
Definition at line 967 of file qcustomplot.cpp.
References getImpulsePlotData(), getLinePlotData(), getScatterPlotData(), getStepCenterPlotData(), getStepLeftPlotData(), getStepRightPlotData(), lsImpulse, lsLine, lsNone, lsStepCenter, lsStepLeft, lsStepRight, and mLineStyle.
Referenced by draw(), getChannelFillPolygon(), and pointDistance().
{
  switch(mLineStyle)
  {
    case lsNone: getScatterPlotData(pointData); break;
    case lsLine: getLinePlotData(lineData, pointData); break;
    case lsStepLeft: getStepLeftPlotData(lineData, pointData); break;
    case lsStepRight: getStepRightPlotData(lineData, pointData); break;
    case lsStepCenter: getStepCenterPlotData(lineData, pointData); break;
    case lsImpulse: getImpulsePlotData(lineData, pointData); break;
  }
}
void QCPGraph::getScatterPlotData (QVector< QCPData > *pointData) const [protected]
If line style is lsNone and scatter style is not QCP::ssNone, this function serves at providing the visible data points in pointData, so the drawScatterPlot function can draw the scatter points accordingly.
If line style is not lsNone, this function is not called and the data for the scatter points are (if needed) calculated inside the corresponding other 'get(...)PlotData' functions.
See also:
drawScatterPlot
Definition at line 990 of file qcustomplot.cpp.
References getVisibleDataBounds(), QCPAbstractPlottable::mKeyAxis, and QCPAxis::orientation().
Referenced by getPlotData(), and pointDistance().
{
  if (!pointData) return;
  
  // get visible data range:
  QCPDataMap::const_iterator lower, upper;
  int dataCount;
  getVisibleDataBounds(lower, upper, dataCount);
  // prepare vectors:
  if (pointData)
    pointData->resize(dataCount);
  // position data points:
  QCPDataMap::const_iterator it = lower;
  QCPDataMap::const_iterator upperEnd = upper+1;
  int i = 0;
  if (mKeyAxis->orientation() == Qt::Vertical)
  {
    while (it != upperEnd)
    {
      (*pointData)[i] = it.value();
      ++i;
      ++it;
    }
  } else // key axis is horizontal
  {
    while (it != upperEnd)
    {
      (*pointData)[i] = it.value();
      ++i;
      ++it;
    }
  }
}
void QCPGraph::getStepCenterPlotData (QVector< QPointF > *lineData, QVector< QCPData > *pointData) const [protected]
Places the raw data points needed for a step plot with centered steps in lineData.
As for all plot data retrieval functions, pointData just contains all unaltered data (scatter) points that are visible, for drawing scatter points, if necessary. If drawing scatter points is disabled (i.e. scatter style QCP::ssNone), pass 0 as pointData, and the function will skip filling the vector.
See also:
drawLinePlot
Definition at line 1244 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), getVisibleDataBounds(), key, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, and QCPAxis::orientation().
Referenced by getPlotData().
{
  // get visible data range:
  QCPDataMap::const_iterator lower, upper;
  int dataCount;
  getVisibleDataBounds(lower, upper, dataCount);
  // prepare vectors:
  if (lineData)
  {
    // added 2 to reserve memory for lower/upper fill base points that might be needed for base fill
    // multiplied by 2 because step plot needs two polyline points per one actual data point
    lineData->reserve(dataCount*2+2);
    lineData->resize(dataCount*2);
  }
  if (pointData)
    pointData->resize(dataCount);
  
  // position points:
  QCPDataMap::const_iterator it = lower;
  QCPDataMap::const_iterator upperEnd = upper+1;
  int i = 0;
  int ipoint = 0;
  if (mKeyAxis->orientation() == Qt::Vertical)
  {
    double lastKey = mKeyAxis->coordToPixel(it.key());
    double lastValue = mValueAxis->coordToPixel(it.value().value);
    double key;
    if (pointData)
    {
      (*pointData)[ipoint] = it.value();
      ++ipoint;
    }
    (*lineData)[i].setX(lastValue);
    (*lineData)[i].setY(lastKey);
    ++it;
    ++i;
    while (it != upperEnd)
    {
      if (pointData)
      {
        (*pointData)[ipoint] = it.value();
        ++ipoint;
      }
      key = (mKeyAxis->coordToPixel(it.key())-lastKey)*0.5 + lastKey;
      (*lineData)[i].setX(lastValue);
      (*lineData)[i].setY(key);
      ++i;
      lastValue = mValueAxis->coordToPixel(it.value().value);
      lastKey = mKeyAxis->coordToPixel(it.key());
      (*lineData)[i].setX(lastValue);
      (*lineData)[i].setY(key);
      ++it;
      ++i;
    }
    (*lineData)[i].setX(lastValue);
    (*lineData)[i].setY(lastKey);
  } else // key axis is horizontal
  {
    double lastKey = mKeyAxis->coordToPixel(it.key());
    double lastValue = mValueAxis->coordToPixel(it.value().value);
    double key;
    if (pointData)
    {
      (*pointData)[ipoint] = it.value();
      ++ipoint;
    }
    (*lineData)[i].setX(lastKey);
    (*lineData)[i].setY(lastValue);
    ++it;
    ++i;
    while (it != upperEnd)
    {
      if (pointData)
      {
        (*pointData)[ipoint] = it.value();
        ++ipoint;
      }
      key = (mKeyAxis->coordToPixel(it.key())-lastKey)*0.5 + lastKey;
      (*lineData)[i].setX(key);
      (*lineData)[i].setY(lastValue);
      ++i;
      lastValue = mValueAxis->coordToPixel(it.value().value);
      lastKey = mKeyAxis->coordToPixel(it.key());
      (*lineData)[i].setX(key);
      (*lineData)[i].setY(lastValue);
      ++it;
      ++i;
    }
    (*lineData)[i].setX(lastKey);
    (*lineData)[i].setY(lastValue);
  }
}
void QCPGraph::getStepLeftPlotData (QVector< QPointF > *lineData, QVector< QCPData > *pointData) const [protected]
Places the raw data points needed for a step plot with left oriented steps in lineData.
As for all plot data retrieval functions, pointData just contains all unaltered data (scatter) points that are visible, for drawing scatter points, if necessary. If drawing scatter points is disabled (i.e. scatter style QCP::ssNone), pass 0 as pointData, and the function will skip filling the vector.
See also:
drawLinePlot
Definition at line 1090 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), getVisibleDataBounds(), key, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, and QCPAxis::orientation().
Referenced by getPlotData().
{
  // get visible data range:
  QCPDataMap::const_iterator lower, upper;
  int dataCount;
  getVisibleDataBounds(lower, upper, dataCount);
  // prepare vectors:
  if (lineData)
  {
    // added 2 to reserve memory for lower/upper fill base points that might be needed for fill
    // multiplied by 2 because step plot needs two polyline points per one actual data point
    lineData->reserve(dataCount*2+2);
    lineData->resize(dataCount*2);
  }
  if (pointData)
    pointData->resize(dataCount);
  
  // position data points:
  QCPDataMap::const_iterator it = lower;
  QCPDataMap::const_iterator upperEnd = upper+1;
  int i = 0;
  int ipoint = 0;
  if (mKeyAxis->orientation() == Qt::Vertical)
  {
    double lastValue = mValueAxis->coordToPixel(it.value().value);
    double key;
    while (it != upperEnd)
    {
      if (pointData)
      {
        (*pointData)[ipoint] = it.value();
        ++ipoint;
      }
      key = mKeyAxis->coordToPixel(it.key());
      (*lineData)[i].setX(lastValue);
      (*lineData)[i].setY(key);
      ++i;
      lastValue = mValueAxis->coordToPixel(it.value().value);
      (*lineData)[i].setX(lastValue);
      (*lineData)[i].setY(key);
      ++i;
      ++it;
    }
  } else // key axis is horizontal
  {
    double lastValue = mValueAxis->coordToPixel(it.value().value);
    double key;
    while (it != upperEnd)
    {
      if (pointData)
      {
        (*pointData)[ipoint] = it.value();
        ++ipoint;
      }
      key = mKeyAxis->coordToPixel(it.key());
      (*lineData)[i].setX(key);
      (*lineData)[i].setY(lastValue);
      ++i;
      lastValue = mValueAxis->coordToPixel(it.value().value);
      (*lineData)[i].setX(key);
      (*lineData)[i].setY(lastValue);
      ++i;
      ++it;
    }
  }
}
void QCPGraph::getStepRightPlotData (QVector< QPointF > *lineData, QVector< QCPData > *pointData) const [protected]
Places the raw data points needed for a step plot with right oriented steps in lineData.
As for all plot data retrieval functions, pointData just contains all unaltered data (scatter) points that are visible, for drawing scatter points, if necessary. If drawing scatter points is disabled (i.e. scatter style QCP::ssNone), pass 0 as pointData, and the function will skip filling the vector.
See also:
drawLinePlot
Definition at line 1167 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), getVisibleDataBounds(), QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), and value.
Referenced by getPlotData().
{
  // get visible data range:
  QCPDataMap::const_iterator lower, upper;
  int dataCount;
  getVisibleDataBounds(lower, upper, dataCount);
  // prepare vectors:
  if (lineData)
  {
    // added 2 to reserve memory for lower/upper fill base points that might be needed for fill
    // multiplied by 2 because step plot needs two polyline points per one actual data point
    lineData->reserve(dataCount*2+2);
    lineData->resize(dataCount*2);
  }
  if (pointData)
    pointData->resize(dataCount);
  
  // position points:
  QCPDataMap::const_iterator it = lower;
  QCPDataMap::const_iterator upperEnd = upper+1;
  int i = 0;
  int ipoint = 0;
  if (mKeyAxis->orientation() == Qt::Vertical)
  {
    double lastKey = mKeyAxis->coordToPixel(it.key());
    double value;
    while (it != upperEnd)
    {
      if (pointData)
      {
        (*pointData)[ipoint] = it.value();
        ++ipoint;
      }
      value = mValueAxis->coordToPixel(it.value().value);
      (*lineData)[i].setX(value);
      (*lineData)[i].setY(lastKey);
      ++i;
      lastKey = mKeyAxis->coordToPixel(it.key());
      (*lineData)[i].setX(value);
      (*lineData)[i].setY(lastKey);
      ++i;
      ++it;
    }
  } else // key axis is horizontal
  {
    double lastKey = mKeyAxis->coordToPixel(it.key());
    double value;
    while (it != upperEnd)
    {
      if (pointData)
      {
        (*pointData)[ipoint] = it.value();
        ++ipoint;
      }
      value = mValueAxis->coordToPixel(it.value().value);
      (*lineData)[i].setX(lastKey);
      (*lineData)[i].setY(value);
      ++i;
      lastKey = mKeyAxis->coordToPixel(it.key());
      (*lineData)[i].setX(lastKey);
      (*lineData)[i].setY(value);
      ++i;
      ++it;
    }
  }
}
QCPRange QCPGraph::getValueRange (bool &validRange, SignDomaininSignDomain = sdBoth) const [protected], [virtual]
called by rescaleAxes functions to get the full data value bounds. For logarithmic plots, one can set inSignDomain to either sdNegative or sdPositive in order to restrict the returned range to that sign domain. E.g. when only negative range is wanted, set inSignDomain to sdNegative and all positive points will be ignored for range calculation. For no restriction, just set inSignDomain to sdBoth (default). validRange is an output parameter that indicates whether a proper range could be found or not. If this is false, you shouldn't use the returned range (e.g. no points in data).
See also:
rescaleAxes, getKeyRange
Implements QCPAbstractPlottable.
Definition at line 2144 of file qcustomplot.cpp.
Referenced by rescaleValueAxis().
{
  // just call the specialized version which takes an additional argument whether error bars
  // should also be taken into consideration for range calculation. We set this to true here.
  return getValueRange(validRange, inSignDomain, true);
}
QCPRange QCPGraph::getValueRange (bool &validRange, SignDomaininSignDomain, boolincludeErrors) const [protected], [virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Allows to specify whether the error bars should be included in the range calculation.
See also:
getValueRange(bool &validRange, SignDomain inSignDomain)
Definition at line 2261 of file qcustomplot.cpp.
References QCPRange::lower, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
{
  QCPRange range;
  bool haveLower = false;
  bool haveUpper = false;
  
  double current, currentErrorMinus, currentErrorPlus;
  
  if (inSignDomain == sdBoth) // range may be anywhere
  {
    QCPDataMap::const_iterator it = mData->constBegin();
    while (it != mData->constEnd())
    {
      current = it.value().value;
      currentErrorMinus = (includeErrors ? it.value().valueErrorMinus : 0);
      currentErrorPlus = (includeErrors ? it.value().valueErrorPlus : 0);
      if (current-currentErrorMinus < range.lower || !haveLower)
      {
        range.lower = current-currentErrorMinus;
        haveLower = true;
      }
      if (current+currentErrorPlus > range.upper || !haveUpper)
      {
        range.upper = current+currentErrorPlus;
        haveUpper = true;
      }
      ++it;
    }
  } else if (inSignDomain == sdNegative) // range may only be in the negative sign domain
  {
    QCPDataMap::const_iterator it = mData->constBegin();
    while (it != mData->constEnd())
    {
      current = it.value().value;
      currentErrorMinus = (includeErrors ? it.value().valueErrorMinus : 0);
      currentErrorPlus = (includeErrors ? it.value().valueErrorPlus : 0);
      if ((current-currentErrorMinus < range.lower || !haveLower) && current-currentErrorMinus < 0)
      {
        range.lower = current-currentErrorMinus;
        haveLower = true;
      }
      if ((current+currentErrorPlus > range.upper || !haveUpper) && current+currentErrorPlus < 0)
      {
        range.upper = current+currentErrorPlus;
        haveUpper = true;
      }
      if (includeErrors) // in case point is in valid sign domain but errobars stretch beyond it, we still want to get that point.
      {
        if ((current < range.lower || !haveLower) && current < 0)
        {
          range.lower = current;
          haveLower = true;
        }
        if ((current > range.upper || !haveUpper) && current < 0)
        {
          range.upper = current;
          haveUpper = true;
        }
      }
      ++it;
    }
  } else if (inSignDomain == sdPositive) // range may only be in the positive sign domain
  {
    QCPDataMap::const_iterator it = mData->constBegin();
    while (it != mData->constEnd())
    {
      current = it.value().value;
      currentErrorMinus = (includeErrors ? it.value().valueErrorMinus : 0);
      currentErrorPlus = (includeErrors ? it.value().valueErrorPlus : 0);
      if ((current-currentErrorMinus < range.lower || !haveLower) && current-currentErrorMinus > 0)
      {
        range.lower = current-currentErrorMinus;
        haveLower = true;
      }
      if ((current+currentErrorPlus > range.upper || !haveUpper) && current+currentErrorPlus > 0)
      {
        range.upper = current+currentErrorPlus;
        haveUpper = true;
      }
      if (includeErrors) // in case point is in valid sign domain but errobars stretch beyond it, we still want to geht that point.
      {
        if ((current < range.lower || !haveLower) && current > 0)
        {
          range.lower = current;
          haveLower = true;
        }
        if ((current > range.upper || !haveUpper) && current > 0)
        {
          range.upper = current;
          haveUpper = true;
        }
      }
      ++it;
    }
  }
  
  validRange = haveLower && haveUpper;
  return range;
}
void QCPGraph::getVisibleDataBounds (QCPDataMap::const_iterator &lower, QCPDataMap::const_iterator &upper, int &count) const [protected]
called by the specific plot data generating functions 'get(...)PlotData' to determine which data range is visible, so only that needs to be processed.
Parameters:
lower returns an iterator to the lowest data point that needs to be taken into account when plotting. Note that in order to get a clean plot all the way to the edge of the axes, lower may still be outside the visible range.
upper returns an iterator to the highest data point. Same as before, upper may also lie outside of the visible range.
count number of data points that need plotting, i.e. points between lower and upper, including them. This is useful for allocating the array of QPointFs in the specific drawing functions.
Definition at line 1662 of file qcustomplot.cpp.
References QCPRange::lower, mData, QCPAbstractPlottable::mKeyAxis, QCPAxis::range(), and QCPRange::upper.
Referenced by getImpulsePlotData(), getLinePlotData(), getScatterPlotData(), getStepCenterPlotData(), getStepLeftPlotData(), and getStepRightPlotData().
{
  // get visible data range as QMap iterators
  QCPDataMap::const_iterator lbound = mData->lowerBound(mKeyAxis->range().lower);
  QCPDataMap::const_iterator ubound = mData->upperBound(mKeyAxis->range().upper)-1;
  bool lowoutlier = lbound != mData->constBegin(); // indicates whether there exist points below axis range
  bool highoutlier = ubound+1 != mData->constEnd(); // indicates whether there exist points above axis range
  lower = (lowoutlier ? lbound-1 : lbound); // data pointrange that will be actually drawn
  upper = (highoutlier ? ubound+1 : ubound); // data pointrange that will be actually drawn
  
  // count number of points in range lower to upper (including them), so we can allocate array for them in draw functions:
  QCPDataMap::const_iterator it = lower;
  count = 1;
  while (it != upper)
  {
    ++it;
    ++count;
  }
}
LineStyle QCPGraph::lineStyle () const [inline]
Definition at line 482 of file qcustomplot.h.
{ return mLineStyle; }
QPointF QCPGraph::lowerFillBasePoint (doublelowerKey) const [protected]
called by addFillBasePoints to conveniently assign the point which closes the fill polygon on the lower side of the zero-value-line parallel to the key axis. The logarithmic axis scale case is a bit special, since the zero-value-line in pixel coordinates is in positive or negative infinity. So this case is handled separately by just closing the fill polygon on the axis which lies in the direction towards the zero value.
Parameters:
lowerKey pixel position of the lower key of the point. Depending on whether the key axis is horizontal or vertical, lowerKey will end up as the x or y value of the returned point, respectively.
See also:
upperFillBasePoint, addFillBasePoints
Definition at line 1733 of file qcustomplot.cpp.
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxis::axisRect(), QCPAxis::axisType(), QCPAxis::coordToPixel(), QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), QCPAxis::range(), QCPAxis::rangeReversed(), QCPAxis::scaleType(), and QCPRange::upper.
Referenced by addFillBasePoints().
{
  QPointF point;
  if (mValueAxis->scaleType() == QCPAxis::stLinear)
  {
    if (mKeyAxis->axisType() == QCPAxis::atLeft)
    {
      point.setX(mValueAxis->coordToPixel(0));
      point.setY(lowerKey);
    } else if (mKeyAxis->axisType() == QCPAxis::atRight)
    {
      point.setX(mValueAxis->coordToPixel(0));
      point.setY(lowerKey);
    } else if (mKeyAxis->axisType() == QCPAxis::atTop)
    {
      point.setX(lowerKey);
      point.setY(mValueAxis->coordToPixel(0));
    } else if (mKeyAxis->axisType() == QCPAxis::atBottom)
    {
      point.setX(lowerKey);
      point.setY(mValueAxis->coordToPixel(0));
    }
  } else // mValueAxis->mScaleType == QCPAxis::stLogarithmic
  {
    // In logarithmic scaling we can't just draw to value zero so we just fill all the way
    // to the axis which is in the direction towards zero
    if (mKeyAxis->orientation() == Qt::Vertical)
    {
      if ((mValueAxis->range().upper < 0 && !mValueAxis->rangeReversed()) ||
          (mValueAxis->range().upper > 0 && mValueAxis->rangeReversed())) // if range is negative, zero is on opposite side of key axis
        point.setX(mKeyAxis->axisRect().right());
      else
        point.setX(mKeyAxis->axisRect().left());
      point.setY(lowerKey);
    } else if (mKeyAxis->axisType() == QCPAxis::atTop || mKeyAxis->axisType() == QCPAxis::atBottom)
    {
      point.setX(lowerKey);
      if ((mValueAxis->range().upper < 0 && !mValueAxis->rangeReversed()) ||
          (mValueAxis->range().upper > 0 && mValueAxis->rangeReversed())) // if range is negative, zero is on opposite side of key axis
        point.setY(mKeyAxis->axisRect().top());
      else
        point.setY(mKeyAxis->axisRect().bottom());
    }
  }
  return point;
}
double QCPGraph::pointDistance (const QPointF &pixelPoint) const [protected]
Calculates the (minimum) distance (in pixels) the graph's representation has from the given pixelPoint in pixels. This is used to determine whether the graph was clicked or not, e.g. in selectTest.
Definition at line 2048 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels(), QCPAbstractPlottable::distSqrToLine(), getPlotData(), getScatterPlotData(), lsImpulse, lsNone, mData, mLineStyle, QCPAbstractPlottable::mName, mScatterStyle, and QCP::ssNone.
Referenced by selectTest().
{
  if (mData->isEmpty())
  {
    qDebug() << Q_FUNC_INFO << "requested point distance on graph" << mName << "without data";
    return 500;
  }
  if (mData->size() == 1)
  {
    QPointF dataPoint = coordsToPixels(mData->constBegin().key(), mData->constBegin().value().value);
    return QVector2D(dataPoint-pixelPoint).length();
  }
  
  if (mLineStyle == lsNone && mScatterStyle == QCP::ssNone)
    return 500;
  
  // calculate minimum distances to graph representation:
  if (mLineStyle == lsNone)
  {
    // no line displayed, only calculate distance to scatter points:
    QVector<QCPData> *pointData = new QVector<QCPData>;
    getScatterPlotData(pointData);
    double minDistSqr = std::numeric_limits<double>::max();
    QPointF ptA;
    QPointF ptB = coordsToPixels(pointData->at(0).key, pointData->at(0).value); // getScatterPlotData returns in plot coordinates, so transform to pixels
    for (int i=1; i<pointData->size(); ++i)
    {
      ptA = ptB;
      ptB = coordsToPixels(pointData->at(i).key, pointData->at(i).value);
      double currentDistSqr = distSqrToLine(ptA, ptB, pixelPoint);
      if (currentDistSqr < minDistSqr)
        minDistSqr = currentDistSqr;
    }
    delete pointData;
    return sqrt(minDistSqr);
  } else
  {
    // line displayed calculate distance to line segments:
    QVector<QPointF> *lineData = new QVector<QPointF>;
    getPlotData(lineData, 0); // unlike with getScatterPlotData we get pixel coordinates here
    double minDistSqr = std::numeric_limits<double>::max();
    if (mLineStyle == lsImpulse)
    {
      // impulse plot differs from other line styles in that the lineData points are only pairwise connected:
      for (int i=0; i<lineData->size()-1; i+=2) // iterate pairs
      {
        double currentDistSqr = distSqrToLine(lineData->at(i), lineData->at(i+1), pixelPoint);
        if (currentDistSqr < minDistSqr)
          minDistSqr = currentDistSqr;
      }
    } else
    {
      // all other line plots (line and step) connect points directly:
      for (int i=0; i<lineData->size()-1; ++i)
      {
        double currentDistSqr = distSqrToLine(lineData->at(i), lineData->at(i+1), pixelPoint);
        if (currentDistSqr < minDistSqr)
          minDistSqr = currentDistSqr;
      }
    }
    delete lineData;
    return sqrt(minDistSqr);
  }
}
QCPGraph::Q_ENUMS (LineStyle) [inline]
Defines what kind of error bars are drawn for each data point. < No error bars are shown
< Error bars for the key dimension of the data point are shown
< Error bars for the value dimension of the data point are shown
< Error bars for both key and value dimensions of the data point are shown
Definition at line 466 of file qcustomplot.h.
                 { etNone
                  ,etKey
                  ,etValue
                  ,etBoth
                 };
QCPGraph::Q_ENUMS (ErrorType)
void QCPGraph::removeData (doublefromKey, doubletoKey)
Removes all data points with keys between fromKey and toKey. if fromKey is greater or equal to toKey, the function does nothing. To remove a single data point with known key, use removeData(double key).
See also:
addData, clearData
Definition at line 767 of file qcustomplot.cpp.
References mData.
{
  if (fromKey >= toKey || mData->isEmpty()) return;
  QCPDataMap::iterator it = mData->upperBound(fromKey);
  QCPDataMap::iterator itEnd = mData->upperBound(toKey);
  while (it != itEnd)
    it = mData->erase(it);
}
void QCPGraph::removeData (doublekey)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes a single data point at key. If the position is not known with absolute precision, consider using removeData(double fromKey, double toKey) with a small fuzziness interval around the suspected position, depeding on the precision with which the key is known.
See also:
addData, clearData
Definition at line 784 of file qcustomplot.cpp.
References mData.
{
  mData->remove(key);
}
void QCPGraph::removeDataAfter (doublekey)
Removes all data points with keys greater than key.
See also:
addData, clearData
Definition at line 752 of file qcustomplot.cpp.
References mData.
{
  if (mData->isEmpty()) return;
  QCPDataMap::iterator it = mData->upperBound(key);
  while (it != mData->end())
    it = mData->erase(it);
}
void QCPGraph::removeDataBefore (doublekey)
Removes all data points with keys smaller than key.
See also:
addData, clearData
Definition at line 741 of file qcustomplot.cpp.
References key, and mData.
{
  QCPDataMap::iterator it = mData->begin();
  while (it != mData->end() && it.key() < key)
    it = mData->erase(it);
}
void QCPGraph::removeFillBasePoints (QVector< QPointF > *lineData) const [protected]
removes the two points from lineData that were added by addFillBasePoints.
See also:
addFillBasePoints, lowerFillBasePoint, upperFillBasePoint
Definition at line 1715 of file qcustomplot.cpp.
Referenced by drawFill().
{
  lineData->remove(lineData->size()-2, 2);
}
void QCPGraph::rescaleAxes (boolonlyEnlarge, boolincludeErrorBars) const [virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows to define whether error bars are taken into consideration when determining the new axis range.
Definition at line 812 of file qcustomplot.cpp.
References rescaleKeyAxis(), and rescaleValueAxis().
{
  rescaleKeyAxis(onlyEnlarge, includeErrorBars);
  rescaleValueAxis(onlyEnlarge, includeErrorBars);
}
void QCPGraph::rescaleKeyAxis (boolonlyEnlarge, boolincludeErrorBars) const [virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows to define whether error bars (of kind QCPGraph::etKey) are taken into consideration when determining the new axis range.
Definition at line 823 of file qcustomplot.cpp.
References getKeyRange(), QCPRange::lower, mData, QCPAbstractPlottable::mKeyAxis, QCPAxis::range(), QCPAxis::scaleType(), QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, QCPAxis::setRange(), and QCPRange::upper.
Referenced by rescaleAxes().
{
  // this code is a copy of QCPAbstractPlottable::rescaleKeyAxis with the only change
  // that getKeyRange is passed the includeErrorBars value.
  if (mData->isEmpty()) return;
  SignDomain signDomain = sdBoth;
  if (mKeyAxis->scaleType() == QCPAxis::stLogarithmic)
    signDomain = (mKeyAxis->range().upper < 0 ? sdNegative : sdPositive);
  
  bool validRange;
  QCPRange newRange = getKeyRange(validRange, signDomain, includeErrorBars);
  
  if (validRange)
  {
    if (onlyEnlarge)
    {
      if (mKeyAxis->range().lower < newRange.lower)
        newRange.lower = mKeyAxis->range().lower;
      if (mKeyAxis->range().upper > newRange.upper)
        newRange.upper = mKeyAxis->range().upper;
    }
    mKeyAxis->setRange(newRange);
  }
}
void QCPGraph::rescaleValueAxis (boolonlyEnlarge, boolincludeErrorBars) const [virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows to define whether error bars (of kind QCPGraph::etValue) are taken into consideration when determining the new axis range.
Definition at line 854 of file qcustomplot.cpp.
References getValueRange(), QCPRange::lower, mData, QCPAbstractPlottable::mValueAxis, QCPAxis::range(), QCPAxis::scaleType(), QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, QCPAxis::setRange(), and QCPRange::upper.
Referenced by rescaleAxes().
{
  // this code is a copy of QCPAbstractPlottable::rescaleValueAxis with the only change
  // is that getValueRange is passed the includeErrorBars value.
  if (mData->isEmpty()) return;
  SignDomain signDomain = sdBoth;
  if (mValueAxis->scaleType() == QCPAxis::stLogarithmic)
    signDomain = (mValueAxis->range().upper < 0 ? sdNegative : sdPositive);
  
  bool validRange;
  QCPRange newRange = getValueRange(validRange, signDomain, includeErrorBars);
  
  if (validRange)
  {
    if (onlyEnlarge)
    {
      if (mValueAxis->range().lower < newRange.lower)
        newRange.lower = mValueAxis->range().lower;
      if (mValueAxis->range().upper > newRange.upper)
        newRange.upper = mValueAxis->range().upper;
    }
    mValueAxis->setRange(newRange);
  }
}
const QPixmap QCPGraph::scatterPixmap () const [inline]
Definition at line 485 of file qcustomplot.h.
{ return mScatterPixmap; }
double QCPGraph::scatterSize () const [inline]
Definition at line 484 of file qcustomplot.h.
{ return mScatterSize; }
QCP::ScatterStyle QCPGraph::scatterStyle () const [inline]
Definition at line 483 of file qcustomplot.h.
{ return mScatterStyle; }
double QCPGraph::selectTest (const QPointF &pos) const [virtual]
This function is used to decide whether a click hits a plottable or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the plottable (e.g. to the scatters/lines of a graph). If the plottable is either invisible, contains no data or the distance couldn't be determined, -1.0 is returned. setSelectable has no influence on the return value of this function.
If the plottable is represented not by single lines but by an area like QCPBars or QCPStatisticalBox, a click inside the area returns a constant value greater zero (typically 99% of the selectionTolerance of the parent QCustomPlot). If the click lies outside the area, this function returns -1.0.
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs.
See also:
setSelected, QCustomPlot::setInteractions
Implements QCPAbstractPlottable.
Definition at line 799 of file qcustomplot.cpp.
References mData, QCPLayerable::mVisible, and pointDistance().
{
  if (mData->isEmpty() || !mVisible)
    return -1;
  
  return pointDistance(pos);
}
void QCPGraph::setChannelFillGraph (QCPGraph *targetGraph)
Sets the target graph for filling the area between this graph and targetGraph with the current brush (setBrush). When targetGraph is set to 0, a normal graph fill will be produced. This means, when the brush is not Qt::NoBrush or fully transparent, a fill all the way to the zero-value-line parallel to the key axis of this graph will be drawn. To disable any filling, set the brush to Qt::NoBrush.
See also:
setBrush
Definition at line 671 of file qcustomplot.cpp.
References mChannelFillGraph, and QCPLayerable::mParentPlot.
{
  // prevent setting channel target to this graph itself:
  if (targetGraph == this)
  {
    qDebug() << Q_FUNC_INFO << "targetGraph is this graph itself";
    mChannelFillGraph = 0;
    return;
  }
  // prevent setting channel target to a graph not in the plot:
  if (targetGraph && targetGraph->mParentPlot != mParentPlot)
  {
    qDebug() << Q_FUNC_INFO << "targetGraph not in same plot";
    mChannelFillGraph = 0;
    return;
  }
  
  mChannelFillGraph = targetGraph;
}
void QCPGraph::setData (QCPDataMap *data, boolcopy = false)
Replaces the current data with the provided data. If copy is set to true, data points in data will only be copied. if false, the graph takes ownership of the passed data and replaces the internal data pointer with it. This is significantly faster than copying for large datasets.
Definition at line 373 of file qcustomplot.cpp.
References data(), and mData.
{
  if (copy)
  {
    *mData = *data;
  } else
  {
    delete mData;
    mData = data;
  }
}
void QCPGraph::setData (const QVector< double > &key, const QVector< double > &value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided points in key and value pairs. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
Definition at line 391 of file qcustomplot.cpp.
References mData.
{
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  QCPData newData;
  for (int i=0; i<n; ++i)
  {
    newData.key = key[i];
    newData.value = value[i];
    mData->insertMulti(newData.key, newData);
  }
}
void QCPGraph::setDataBothError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &keyError, const QVector< double > &valueError)
Replaces the current data with the provided points in key and value pairs. Additionally the symmetrical key and value errors of the data points are set to the values in keyError and valueError. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
For asymmetrical errors (plus different from minus), see the overloaded version of this function.
Definition at line 520 of file qcustomplot.cpp.
References mData.
{
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  n = qMin(n, valueError.size());
  n = qMin(n, keyError.size());
  QCPData newData;
  for (int i=0; i<n; ++i)
  {
    newData.key = key[i];
    newData.value = value[i];
    newData.keyErrorMinus = keyError[i];
    newData.keyErrorPlus = keyError[i];
    newData.valueErrorMinus = valueError[i];
    newData.valueErrorPlus = valueError[i];
    mData->insertMulti(key[i], newData);
  }
}
void QCPGraph::setDataBothError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &keyErrorMinus, const QVector< double > &keyErrorPlus, const QVector< double > &valueErrorMinus, const QVector< double > &valueErrorPlus)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Replaces the current data with the provided points in key and value pairs. Additionally the negative key and value errors of the data points are set to the values in keyErrorMinus and valueErrorMinus. The positive key and value errors are set to the values in keyErrorPlus valueErrorPlus. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
Definition at line 549 of file qcustomplot.cpp.
References mData.
{
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  n = qMin(n, valueErrorMinus.size());
  n = qMin(n, valueErrorPlus.size());
  n = qMin(n, keyErrorMinus.size());
  n = qMin(n, keyErrorPlus.size());
  QCPData newData;
  for (int i=0; i<n; ++i)
  {
    newData.key = key[i];
    newData.value = value[i];
    newData.keyErrorMinus = keyErrorMinus[i];
    newData.keyErrorPlus = keyErrorPlus[i];
    newData.valueErrorMinus = valueErrorMinus[i];
    newData.valueErrorPlus = valueErrorPlus[i];
    mData->insertMulti(key[i], newData);
  }
}
void QCPGraph::setDataKeyError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &keyError)
Replaces the current data with the provided points in key and value pairs. Additionally the symmetrical key error of the data points are set to the values in keyError. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
For asymmetrical errors (plus different from minus), see the overloaded version of this function.
Definition at line 467 of file qcustomplot.cpp.
References mData.
{
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  n = qMin(n, keyError.size());
  QCPData newData;
  for (int i=0; i<n; ++i)
  {
    newData.key = key[i];
    newData.value = value[i];
    newData.keyErrorMinus = keyError[i];
    newData.keyErrorPlus = keyError[i];
    mData->insertMulti(key[i], newData);
  }
}
void QCPGraph::setDataKeyError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &keyErrorMinus, const QVector< double > &keyErrorPlus)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Replaces the current data with the provided points in key and value pairs. Additionally the negative key error of the data points are set to the values in keyErrorMinus, the positive key error to keyErrorPlus. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
Definition at line 493 of file qcustomplot.cpp.
References mData.
{
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  n = qMin(n, keyErrorMinus.size());
  n = qMin(n, keyErrorPlus.size());
  QCPData newData;
  for (int i=0; i<n; ++i)
  {
    newData.key = key[i];
    newData.value = value[i];
    newData.keyErrorMinus = keyErrorMinus[i];
    newData.keyErrorPlus = keyErrorPlus[i];
    mData->insertMulti(key[i], newData);
  }
}
void QCPGraph::setDataValueError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &valueError)
Replaces the current data with the provided points in key and value pairs. Additionally the symmetrical value error of the data points are set to the values in valueError. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
For asymmetrical errors (plus different from minus), see the overloaded version of this function.
Definition at line 414 of file qcustomplot.cpp.
References mData.
{
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  n = qMin(n, valueError.size());
  QCPData newData;
  for (int i=0; i<n; ++i)
  {
    newData.key = key[i];
    newData.value = value[i];
    newData.valueErrorMinus = valueError[i];
    newData.valueErrorPlus = valueError[i];
    mData->insertMulti(key[i], newData);
  }
}
void QCPGraph::setDataValueError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &valueErrorMinus, const QVector< double > &valueErrorPlus)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Replaces the current data with the provided points in key and value pairs. Additionally the negative value error of the data points are set to the values in valueErrorMinus, the positive value error to valueErrorPlus. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
Definition at line 440 of file qcustomplot.cpp.
References mData.
{
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  n = qMin(n, valueErrorMinus.size());
  n = qMin(n, valueErrorPlus.size());
  QCPData newData;
  for (int i=0; i<n; ++i)
  {
    newData.key = key[i];
    newData.value = value[i];
    newData.valueErrorMinus = valueErrorMinus[i];
    newData.valueErrorPlus = valueErrorPlus[i];
    mData->insertMulti(key[i], newData);
  }
}
void QCPGraph::setErrorBarSize (doublesize)
Sets the width of the handles at both ends of an error bar in pixels.
Definition at line 643 of file qcustomplot.cpp.
References mErrorBarSize.
{
  mErrorBarSize = size;
}
void QCPGraph::setErrorBarSkipSymbol (boolenabled)
If enabled is set to true, the error bar will not be drawn as a solid line under the scatter symbol but leave some free space around the symbol. This feature uses the current scatter size (setScatterSize) to determine the size of the area to leave blank. So when drawing Pixmaps as scatter points (QCP::ssPixmap), the scatter size must be set manually to a value corresponding to the size of the Pixmap, if the error bars should leave gaps to its boundaries.
Definition at line 657 of file qcustomplot.cpp.
References mErrorBarSkipSymbol.
{
  mErrorBarSkipSymbol = enabled;
}
void QCPGraph::setErrorPen (const QPen &pen)
Sets the pen with which the error bars will be drawn.
See also:
setErrorBarSize, setErrorType
Definition at line 635 of file qcustomplot.cpp.
References mErrorPen, and QCPAbstractPlottable::pen().
{
  mErrorPen = pen;
}
void QCPGraph::setErrorType (ErrorTypeerrorType)
Sets which kind of error bars (Key Error, Value Error or both) should be drawn on each data point. If you set errorType to something other than etNone, make sure to actually pass error data via the specific setData functions along with the data points (e.g. setDataValueError, setDataKeyError, setDataBothError).
See also:
ErrorType
Definition at line 626 of file qcustomplot.cpp.
References errorType(), and mErrorType.
{
  mErrorType = errorType;
}
void QCPGraph::setLineStyle (LineStylels)
Sets how the single data points are connected in the plot or how they are represented visually apart from the scatter symbol. For scatter-only plots, set ls to lsNone and setScatterStyle to the desired scatter style.
See also:
setScatterStyle
Definition at line 579 of file qcustomplot.cpp.
References mLineStyle.
{
  mLineStyle = ls;
}
void QCPGraph::setScatterPixmap (const QPixmap &pixmap)
If the scatter style (setScatterStyle) is set to ssPixmap, this function defines the QPixmap that will be drawn centered on the data point coordinate.
See also:
ScatterStyle
Definition at line 613 of file qcustomplot.cpp.
References mScatterPixmap.
{
  mScatterPixmap = pixmap;
}
void QCPGraph::setScatterSize (doublesize)
This defines how big (in pixels) single scatters are drawn, if scatter style (setScatterStyle) isn't QCP::ssNone, QCP::ssDot or QCP::ssPixmap. Floating point values are allowed for fine grained control over optical appearance with antialiased painting.
See also:
ScatterStyle
Definition at line 602 of file qcustomplot.cpp.
References mScatterSize.
{
  mScatterSize = size;
}
void QCPGraph::setScatterStyle (QCP::ScatterStyless)
Sets the visual appearance of single data points in the plot. If set to QCP::ssNone, no scatter points are drawn (e.g. for line-only-plots with appropriate line style).
See also:
ScatterStyle, setLineStyle
Definition at line 590 of file qcustomplot.cpp.
References mScatterStyle.
{
  mScatterStyle = ss;
}
QPointF QCPGraph::upperFillBasePoint (doubleupperKey) const [protected]
called by addFillBasePoints to conveniently assign the point which closes the fill polygon on the upper side of the zero-value-line parallel to the key axis. The logarithmic axis scale case is a bit special, since the zero-value-line in pixel coordinates is in positive or negative infinity. So this case is handled separately by just closing the fill polygon on the axis which lies in the direction towards the zero value.
Parameters:
upperKey pixel position of the upper key of the point. Depending on whether the key axis is horizontal or vertical, upperKey will end up as the x or y value of the returned point, respectively.
See also:
lowerFillBasePoint, addFillBasePoints
Definition at line 1793 of file qcustomplot.cpp.
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxis::axisRect(), QCPAxis::axisType(), QCPAxis::coordToPixel(), QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), QCPAxis::range(), QCPAxis::rangeReversed(), QCPAxis::scaleType(), and QCPRange::upper.
Referenced by addFillBasePoints().
{
  QPointF point;
  if (mValueAxis->scaleType() == QCPAxis::stLinear)
  {
    if (mKeyAxis->axisType() == QCPAxis::atLeft)
    {
      point.setX(mValueAxis->coordToPixel(0));
      point.setY(upperKey);
    } else if (mKeyAxis->axisType() == QCPAxis::atRight)
    {
      point.setX(mValueAxis->coordToPixel(0));
      point.setY(upperKey);
    } else if (mKeyAxis->axisType() == QCPAxis::atTop)
    {
      point.setX(upperKey);
      point.setY(mValueAxis->coordToPixel(0));
    } else if (mKeyAxis->axisType() == QCPAxis::atBottom)
    {
      point.setX(upperKey);
      point.setY(mValueAxis->coordToPixel(0));
    }
  } else // mValueAxis->mScaleType == QCPAxis::stLogarithmic
  {
    // In logarithmic scaling we can't just draw to value 0 so we just fill all the way
    // to the axis which is in the direction towards 0
    if (mKeyAxis->orientation() == Qt::Vertical)
    {
      if ((mValueAxis->range().upper < 0 && !mValueAxis->rangeReversed()) ||
          (mValueAxis->range().upper > 0 && mValueAxis->rangeReversed())) // if range is negative, zero is on opposite side of key axis
        point.setX(mKeyAxis->axisRect().right());
      else
        point.setX(mKeyAxis->axisRect().left());
      point.setY(upperKey);
    } else if (mKeyAxis->axisType() == QCPAxis::atTop || mKeyAxis->axisType() == QCPAxis::atBottom)
    {
      point.setX(upperKey);
      if ((mValueAxis->range().upper < 0 && !mValueAxis->rangeReversed()) ||
          (mValueAxis->range().upper > 0 && mValueAxis->rangeReversed())) // if range is negative, zero is on opposite side of key axis
        point.setY(mKeyAxis->axisRect().top());
      else
        point.setY(mKeyAxis->axisRect().bottom());
    }
  }
  return point;
}
Friends And Related Function Documentation
friend class QCPLegend [friend]
Definition at line 579 of file qcustomplot.h.
friend class QCustomPlot [friend]
Definition at line 578 of file qcustomplot.h.
Member Data Documentation
QCPGraph* QCPGraph::mChannelFillGraph [protected]
Definition at line 539 of file qcustomplot.h.
Referenced by drawFill(), getChannelFillPolygon(), and setChannelFillGraph().
QCPDataMap* QCPGraph::mData [protected]
Definition at line 530 of file qcustomplot.h.
Referenced by addData(), clearData(), draw(), getKeyRange(), getValueRange(), getVisibleDataBounds(), pointDistance(), removeData(), removeDataAfter(), removeDataBefore(), rescaleKeyAxis(), rescaleValueAxis(), selectTest(), setData(), setDataBothError(), setDataKeyError(), setDataValueError(), and ~QCPGraph().
double QCPGraph::mErrorBarSize [protected]
Definition at line 537 of file qcustomplot.h.
Referenced by drawError(), and setErrorBarSize().
bool QCPGraph::mErrorBarSkipSymbol [protected]
Definition at line 538 of file qcustomplot.h.
Referenced by drawError(), and setErrorBarSkipSymbol().
QPen QCPGraph::mErrorPen [protected]
Definition at line 531 of file qcustomplot.h.
Referenced by drawScatterPlot(), and setErrorPen().
ErrorType QCPGraph::mErrorType [protected]
Definition at line 536 of file qcustomplot.h.
Referenced by drawError(), drawScatterPlot(), and setErrorType().
LineStyle QCPGraph::mLineStyle [protected]
Definition at line 532 of file qcustomplot.h.
Referenced by draw(), drawFill(), drawLegendIcon(), getPlotData(), pointDistance(), and setLineStyle().
QPixmap QCPGraph::mScatterPixmap [protected]
Definition at line 535 of file qcustomplot.h.
Referenced by drawLegendIcon(), drawScatterPlot(), and setScatterPixmap().
double QCPGraph::mScatterSize [protected]
Definition at line 534 of file qcustomplot.h.
Referenced by drawError(), drawLegendIcon(), drawScatterPlot(), and setScatterSize().
QCP::ScatterStyle QCPGraph::mScatterStyle [protected]
Definition at line 533 of file qcustomplot.h.
Referenced by draw(), drawLegendIcon(), drawScatterPlot(), pointDistance(), and setScatterStyle().
QCPAxis* QCPGraph::valueAxis
Definition at line 477 of file qcustomplot.h.
Referenced by QCPItemTracer::setGraph().
Author
Generated automatically by Doxygen for AQ0X from the source code.