QCPItemPosition
NAME
QCPItemPosition -
Manages the position of an item.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPItemAnchor.
Public Types
enum PositionType { ptAbsolute, ptViewportRatio, ptAxisRectRatio, ptPlotCoords }
Defines the ways an item position can be specified.
Public Member Functions
QCPItemPosition (QCustomPlot *parentPlot, QCPAbstractItem *parentItem, const QString name)
Creates a new QCPItemPosition.
virtual ~QCPItemPosition ()
PositionType type () const
QCPItemAnchor * parentAnchor () const
double key () const
double value () const
QPointF coords () const
QCPAxis * keyAxis () const
QCPAxis * valueAxis () const
virtual QPointF pixelPoint () const
Returns the final absolute pixel position of the QCPItemPosition on the QCustomPlot surface.
void setType (PositionType type)
Sets the type of the position.
bool setParentAnchor (QCPItemAnchor *parentAnchor, bool keepPixelPosition=false)
Sets the parent of this QCPItemPosition to parentAnchor.
void setCoords (double key, double value)
Sets the coordinates of this QCPItemPosition.
void setCoords (const QPointF &coords)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the coordinates as a QPointF pos where pos.x has the meaning of key and pos.y the meaning of value of the setCoords(double key, double value) function. "
void setAxes (QCPAxis *keyAxis, QCPAxis *valueAxis)
When setType is ptPlotCoords, this function may be used to specify the axes the coordinates set with setCoords relate to.
void setPixelPoint (const QPointF &pixelPoint)
Sets the apparent pixel position.
Protected Attributes
PositionType mPositionType
QCPAxis * mKeyAxis
QCPAxis * mValueAxis
double mKey
double mValue
QCPItemAnchor * mParentAnchor
Additional Inherited Members
Detailed Description
Manages the position of an item.
Every item has at least one public QCPItemPosition member pointer which provides ways to position the item on the QCustomPlot surface. Some items have multiple positions, for example QCPItemRect has two: topLeft and bottomRight.
QCPItemPosition has a type (PositionType) that can be set with setType. This type defines how coordinates passed to setCoords are to be interpreted, e.g. as absolute pixel coordinates, as plot coordinates of certain axes, etc.
Further, QCPItemPosition may have a parent QCPItemAnchor, see setParentAnchor. (Note that every QCPItemPosition inherits from QCPItemAnchor and thus can itself be used as parent anchor for other positions.) This way you can tie multiple items together. If the QCPItemPosition has a parent, the coordinates set with setCoords are considered to be absolute values in the reference frame of the parent anchor, where (0, 0) means directly ontop of the parent anchor. For example, You could attach the start position of a QCPItemLine to the bottom anchor of a QCPItemText to make the starting point of the line always be centered under the text label, no matter where the text is moved to, or is itself tied to.
To set the apparent pixel position on the QCustomPlot surface directly, use setPixelPoint. This works no matter what type this QCPItemPosition is or what parent-child situation it is in, as setPixelPoint transforms the coordinates appropriately, to make the position appear at the specified pixel values.
Definition at line 795 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPItemPosition::PositionType
Defines the ways an item position can be specified. Thus it defines what the numbers passed to setCoords actually mean.
See also:
setType
Enumerator
ptAbsolute
Static positioning in pixels, starting from the top left corner of the viewport/widget.
ptViewportRatio
Static positioning given by a ratio of the current viewport (coordinates 0 to 1).
ptAxisRectRatio
Static positioning given by a ratio of the current axis rect (coordinates 0 to 1).
ptPlotCoords
Dynamic positioning at a plot coordinate defined by two axes (see setAxes).
Definition at line 804 of file qcustomplot.h.
                    { ptAbsolute
                      ,ptViewportRatio
                      ,ptAxisRectRatio
                      ,ptPlotCoords
                    };
Constructor & Destructor Documentation
QCPItemPosition::QCPItemPosition (QCustomPlot *parentPlot, QCPAbstractItem *parentItem, const QStringname)
Creates a new QCPItemPosition. You shouldn't create QCPItemPosition instances directly, even if you want to make a new item subclass. Use QCPAbstractItem::createPosition instead, as explained in the subclassing section of the QCPAbstractItem documentation.
Definition at line 11405 of file qcustomplot.cpp.
                                                                                                         :
  QCPItemAnchor(parentPlot, parentItem, name),
  mPositionType(ptAbsolute),
  mKeyAxis(0),
  mValueAxis(0),
  mKey(0),
  mValue(0),
  mParentAnchor(0)
{
}
QCPItemPosition::~QCPItemPosition () [virtual]
Definition at line 11416 of file qcustomplot.cpp.
References QCPItemAnchor::mChildren, mParentAnchor, and QCPItemAnchor::removeChild().
{
  // unregister as parent at children:
  // Note: this is done in ~QCPItemAnchor again, but it's important QCPItemPosition does it itself, because only then
  // the setParentAnchor(0) call the correct QCPItemPosition::pixelPos function instead of QCPItemAnchor::pixelPos
  QList<QCPItemPosition*> currentChildren(mChildren.toList());
  for (int i=0; i<currentChildren.size(); ++i)
    currentChildren.at(i)->setParentAnchor(0); // this acts back on this anchor and child removes itself from mChildren
  // unregister as child in parent:
  if (mParentAnchor)
    mParentAnchor->removeChild(this);
}
Member Function Documentation
QPointF QCPItemPosition::coords () const [inline]
Definition at line 818 of file qcustomplot.h.
{ return QPointF(mKey, mValue); }
double QCPItemPosition::key () const [inline]
Definition at line 816 of file qcustomplot.h.
Referenced by setCoords().
{ return mKey; }
QCPAxis* QCPItemPosition::keyAxis () const [inline]
Definition at line 819 of file qcustomplot.h.
Referenced by setAxes().
{ return mKeyAxis; }
QCPItemAnchor* QCPItemPosition::parentAnchor () const [inline]
Definition at line 815 of file qcustomplot.h.
Referenced by setParentAnchor().
{ return mParentAnchor; }
QPointF QCPItemPosition::pixelPoint () const [virtual]
Returns the final absolute pixel position of the QCPItemPosition on the QCustomPlot surface. It includes all effects of type (setType) and possible parent anchors (setParentAnchor).
See also:
setPixelPoint
Reimplemented from QCPItemAnchor.
Definition at line 11564 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), mKey, mKeyAxis, mParentAnchor, QCPItemAnchor::mParentPlot, mPositionType, mValue, mValueAxis, QCPAxis::orientation(), QCPItemAnchor::pixelPoint(), ptAbsolute, ptAxisRectRatio, ptPlotCoords, and ptViewportRatio.
Referenced by QCPItemEllipse::anchorPixelPoint(), QCPItemRect::anchorPixelPoint(), QCPItemText::anchorPixelPoint(), QCPItemBracket::anchorPixelPoint(), QCPItemStraightLine::draw(), QCPItemLine::draw(), QCPItemEllipse::draw(), QCPItemRect::draw(), QCPItemText::draw(), QCPItemCurve::draw(), QCPItemBracket::draw(), QCPItemTracer::draw(), QCPItemPixmap::getFinalRect(), QCPItemStraightLine::selectTest(), QCPItemLine::selectTest(), QCPItemEllipse::selectTest(), QCPItemRect::selectTest(), QCPItemText::selectTest(), QCPItemCurve::selectTest(), QCPItemBracket::selectTest(), QCPItemTracer::selectTest(), setParentAnchor(), and setType().
{
  switch (mPositionType)
  {
    case ptAbsolute:
    {
      if (mParentAnchor)
        return QPointF(mKey, mValue) + mParentAnchor->pixelPoint();
      else
        return QPointF(mKey, mValue);
    }
    
    case ptViewportRatio:
    {
      if (mParentAnchor)
      {
        return QPointF(mKey*mParentPlot->viewport().width(),
                       mValue*mParentPlot->viewport().height()) + mParentAnchor->pixelPoint();
      } else
      {
        return QPointF(mKey*mParentPlot->viewport().width(),
                       mValue*mParentPlot->viewport().height()) + mParentPlot->viewport().topLeft();
      }
    }
      
    case ptAxisRectRatio:
    {
      if (mParentAnchor)
      {
        return QPointF(mKey*mParentPlot->axisRect().width(),
                       mValue*mParentPlot->axisRect().height()) + mParentAnchor->pixelPoint();
      } else
      {
        return QPointF(mKey*mParentPlot->axisRect().width(),
                       mValue*mParentPlot->axisRect().height()) + mParentPlot->axisRect().topLeft();
      }
    }
    
    case ptPlotCoords:
    {
      double x, y;
      if (mKeyAxis && mValueAxis)
      {
        // both key and value axis are given, translate key/value to x/y coordinates:
        if (mKeyAxis->orientation() == Qt::Horizontal)
        {
          x = mKeyAxis->coordToPixel(mKey);
          y = mValueAxis->coordToPixel(mValue);
        } else
        {
          y = mKeyAxis->coordToPixel(mKey);
          x = mValueAxis->coordToPixel(mValue);
        }
      } else if (mKeyAxis)
      {
        // only key axis is given, depending on orientation only transform x or y to key coordinate, other stays pixel:
        if (mKeyAxis->orientation() == Qt::Horizontal)
        {
          x = mKeyAxis->coordToPixel(mKey);
          y = mValue;
        } else
        {
          y = mKeyAxis->coordToPixel(mKey);
          x = mValue;
        }
      } else if (mValueAxis)
      {
        // only value axis is given, depending on orientation only transform x or y to value coordinate, other stays pixel:
        if (mValueAxis->orientation() == Qt::Horizontal)
        {
          x = mValueAxis->coordToPixel(mValue);
          y = mKey;
        } else
        {
          y = mValueAxis->coordToPixel(mValue);
          x = mKey;
        }
      } else
      {
        // no axis given, basically the same as if mAnchorType were atNone
        x = mKey;
        y = mValue;
      }
      return QPointF(x, y);
    }
  }
  return QPointF();
}
void QCPItemPosition::setAxes (QCPAxis *keyAxis, QCPAxis *valueAxis)
When setType is ptPlotCoords, this function may be used to specify the axes the coordinates set with setCoords relate to.
Definition at line 11657 of file qcustomplot.cpp.
References keyAxis(), mKeyAxis, mValueAxis, and valueAxis().
Referenced by QCPAbstractItem::createPosition(), and QCPItemTracer::setGraph().
{
  mKeyAxis = keyAxis;
  mValueAxis = valueAxis;
}
void QCPItemPosition::setCoords (doublekey, doublevalue)
Sets the coordinates of this QCPItemPosition. What the coordinates mean, is defined by the type (setType).
For example, if the type is ptAbsolute, key and value mean the x and y pixel position on the QCustomPlot surface where the origin (0, 0) is in the top left corner of the QCustomPlot viewport. If the type is ptPlotCoords, key and value mean a point in the plot coordinate system defined by the axes set by setAxes. (By default the QCustomPlot's x- and yAxis.)
See also:
setPixelPoint
Definition at line 11542 of file qcustomplot.cpp.
References key(), mKey, mValue, and value().
Referenced by QCPAbstractItem::createPosition(), QCPItemBracket::QCPItemBracket(), QCPItemCurve::QCPItemCurve(), QCPItemEllipse::QCPItemEllipse(), QCPItemLine::QCPItemLine(), QCPItemPixmap::QCPItemPixmap(), QCPItemRect::QCPItemRect(), QCPItemStraightLine::QCPItemStraightLine(), QCPItemText::QCPItemText(), setCoords(), setParentAnchor(), setPixelPoint(), and QCPItemTracer::updatePosition().
{
  mKey = key;
  mValue = value;
}
void QCPItemPosition::setCoords (const QPointF &coords)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the coordinates as a QPointF pos where pos.x has the meaning of key and pos.y the meaning of value of the setCoords(double key, double value) function.
Definition at line 11553 of file qcustomplot.cpp.
References setCoords().
{
  setCoords(pos.x(), pos.y());
}
bool QCPItemPosition::setParentAnchor (QCPItemAnchor *parentAnchor, boolkeepPixelPosition = false)
Sets the parent of this QCPItemPosition to parentAnchor. This means the position will now follow any position changes of the anchor. The local coordinate system of positions with a parent anchor always is absolute with (0, 0) being exactly on top of the parent anchor. (Hence the type shouldn't be ptPlotCoords for positions with parent anchors.)
if keepPixelPosition is true, the current pixel position of the QCPItemPosition is preserved during reparenting. If it's set to false, the coordinates are set to (0, 0), i.e. the position will be exactly on top of the parent anchor.
To remove this QCPItemPosition from any parent anchor, set parentAnchor to 0.
Note:
If the QCPItemPosition previously had no parent and the type is ptPlotCoords, the type is set to ptAbsolute, to keep the position in a valid state.
Definition at line 11474 of file qcustomplot.cpp.
References QCPItemAnchor::addChild(), mParentAnchor, QCPItemAnchor::mParentItem, mPositionType, parentAnchor(), pixelPoint(), ptAbsolute, ptPlotCoords, QCPItemAnchor::removeChild(), setCoords(), setPixelPoint(), and setType().
{
  // make sure self is not assigned as parent:
  if (parentAnchor == this)
  {
    qDebug() << Q_FUNC_INFO << "can't set self as parent anchor" << reinterpret_cast<quintptr>(parentAnchor);
    return false;
  }
  // make sure no recursive parent-child-relationships are created:
  QCPItemAnchor *currentParent = parentAnchor;
  while (currentParent)
  {
    if (QCPItemPosition *currentParentPos = dynamic_cast<QCPItemPosition*>(currentParent))
    {
      // is a QCPItemPosition, might have further parent, so keep iterating
      if (currentParentPos == this)
      {
        qDebug() << Q_FUNC_INFO << "can't create recursive parent-child-relationship" << reinterpret_cast<quintptr>(parentAnchor);
        return false;
      }
      currentParent = currentParentPos->mParentAnchor;
    } else
    {
      // is a QCPItemAnchor, can't have further parent, so just compare parent items
      if (currentParent->mParentItem == mParentItem)
      {
        qDebug() << Q_FUNC_INFO << "can't create recursive parent-child-relationship" << reinterpret_cast<quintptr>(parentAnchor);
        return false;
      }
      break;
    }
  }
  
  // if previously no parent set and PosType is still ptPlotCoords, set to ptAbsolute:
  if (!mParentAnchor && mPositionType == ptPlotCoords)
    setType(ptAbsolute);
  
  // save pixel position:
  QPointF pixelP;
  if (keepPixelPosition)
    pixelP = pixelPoint();
  // unregister at current parent anchor:
  if (mParentAnchor)
    mParentAnchor->removeChild(this);
  // register at new parent anchor:
  if (parentAnchor)
    parentAnchor->addChild(this);
  mParentAnchor = parentAnchor;
  // restore pixel position under new parent:
  if (keepPixelPosition)
    setPixelPoint(pixelP);
  else
    setCoords(0, 0);
  return true;
}
void QCPItemPosition::setPixelPoint (const QPointF &pixelPoint)
Sets the apparent pixel position. This works no matter what type this QCPItemPosition is or what parent-child situation it is in, as setPixelPoint transforms the coordinates appropriately, to make the position appear at the specified pixel values.
Only if the type is ptAbsolute and no parent anchor is set, this function is identical to setCoords.
See also:
setCoords
Definition at line 11673 of file qcustomplot.cpp.
References mKeyAxis, mParentAnchor, QCPItemAnchor::mParentPlot, mPositionType, mValueAxis, QCPAxis::orientation(), QCPItemAnchor::pixelPoint(), QCPAxis::pixelToCoord(), ptAbsolute, ptAxisRectRatio, ptPlotCoords, ptViewportRatio, and setCoords().
Referenced by setParentAnchor(), and setType().
{
  switch (mPositionType)
  {
    case ptAbsolute:
    {
      if (mParentAnchor)
        setCoords(pixelPoint-mParentAnchor->pixelPoint());
      else
        setCoords(pixelPoint);
      break;
    }
      
    case ptViewportRatio:
    {
      if (mParentAnchor)
      {
        QPointF p(pixelPoint-mParentAnchor->pixelPoint());
        p.rx() /= (double)mParentPlot->viewport().width();
        p.ry() /= (double)mParentPlot->viewport().height();
        setCoords(p);
      } else
      {
        QPointF p(pixelPoint-mParentPlot->viewport().topLeft());
        p.rx() /= (double)mParentPlot->viewport().width();
        p.ry() /= (double)mParentPlot->viewport().height();
        setCoords(p);
      }
      break;
    }
      
    case ptAxisRectRatio:
    {
      if (mParentAnchor)
      {
        QPointF p(pixelPoint-mParentAnchor->pixelPoint());
        p.rx() /= (double)mParentPlot->axisRect().width();
        p.ry() /= (double)mParentPlot->axisRect().height();
        setCoords(p);
      } else
      {
        QPointF p(pixelPoint-mParentPlot->axisRect().topLeft());
        p.rx() /= (double)mParentPlot->axisRect().width();
        p.ry() /= (double)mParentPlot->axisRect().height();
        setCoords(p);
      }
      break;
    }
      
    case ptPlotCoords:
    {
      double newKey, newValue;
      if (mKeyAxis && mValueAxis)
      {
        // both key and value axis are given, translate point to key/value coordinates:
        if (mKeyAxis->orientation() == Qt::Horizontal)
        {
          newKey = mKeyAxis->pixelToCoord(pixelPoint.x());
          newValue = mValueAxis->pixelToCoord(pixelPoint.y());
        } else
        {
          newKey = mKeyAxis->pixelToCoord(pixelPoint.y());
          newValue = mValueAxis->pixelToCoord(pixelPoint.x());
        }
      } else if (mKeyAxis)
      {
        // only key axis is given, depending on orientation only transform x or y to key coordinate, other stays pixel:
        if (mKeyAxis->orientation() == Qt::Horizontal)
        {
          newKey = mKeyAxis->pixelToCoord(pixelPoint.x());
          newValue = pixelPoint.y();
        } else
        {
          newKey = mKeyAxis->pixelToCoord(pixelPoint.y());
          newValue = pixelPoint.x();
        }
      } else if (mValueAxis)
      {
        // only value axis is given, depending on orientation only transform x or y to value coordinate, other stays pixel:
        if (mValueAxis->orientation() == Qt::Horizontal)
        {
          newKey = pixelPoint.y();
          newValue = mValueAxis->pixelToCoord(pixelPoint.x());
        } else
        {
          newKey = pixelPoint.x();
          newValue = mValueAxis->pixelToCoord(pixelPoint.y());
        }
      } else
      {
        // no axis given, basically the same as if mAnchorType were atNone
        newKey = pixelPoint.x();
        newValue = pixelPoint.y();
      }
      setCoords(newKey, newValue);
      break;
    }
  }
}
void QCPItemPosition::setType (QCPItemPosition::PositionTypetype)
Sets the type of the position. The type defines how the coordinates passed to setCoords should be handled and how the QCPItemPosition should behave in the plot. Note that the position type ptPlotCoords is only available (and sensible) when the position has no parent anchor (setParentAnchor).
The possible values for type can be separated in two main categories:
The position is regarded as a point in plot coordinates. This corresponds to ptPlotCoords and requires two axes that define the plot coordinate system. They can be specified with setAxes. By default, the QCustomPlot's x- and yAxis are used.
The position is fixed on the QCustomPlot surface, i.e. independant of axis ranges. This corresponds to all other types, i.e. ptAbsolute, ptViewportRatio and ptAxisRectRatio. They differ only in the way the absolute position is described, see the documentation of PositionType for details.
Note:
If the type is changed, the apparent pixel position on the plot is preserved. This means the coordinates as retrieved with coords() and set with setCoords may change in the process.
Definition at line 11449 of file qcustomplot.cpp.
References mPositionType, pixelPoint(), setPixelPoint(), and type().
Referenced by QCPAbstractItem::createPosition(), QCPItemTracer::setGraph(), and setParentAnchor().
{
  if (mPositionType != type)
  {
    QPointF pixelP = pixelPoint();
    mPositionType = type;
    setPixelPoint(pixelP);
  }
}
PositionType QCPItemPosition::type () const [inline]
Definition at line 814 of file qcustomplot.h.
Referenced by setType().
{ return mPositionType; }
double QCPItemPosition::value () const [inline]
Definition at line 817 of file qcustomplot.h.
Referenced by setCoords().
{ return mValue; }
QCPAxis* QCPItemPosition::valueAxis () const [inline]
Definition at line 820 of file qcustomplot.h.
Referenced by setAxes().
{ return mValueAxis; }
Member Data Documentation
double QCPItemPosition::mKey [protected]
Definition at line 834 of file qcustomplot.h.
Referenced by pixelPoint(), and setCoords().
QCPAxis* QCPItemPosition::mKeyAxis [protected]
Definition at line 833 of file qcustomplot.h.
Referenced by pixelPoint(), setAxes(), and setPixelPoint().
QCPItemAnchor* QCPItemPosition::mParentAnchor [protected]
Definition at line 835 of file qcustomplot.h.
Referenced by pixelPoint(), setParentAnchor(), setPixelPoint(), and ~QCPItemPosition().
PositionType QCPItemPosition::mPositionType [protected]
Definition at line 832 of file qcustomplot.h.
Referenced by pixelPoint(), setParentAnchor(), setPixelPoint(), and setType().
double QCPItemPosition::mValue [protected]
Definition at line 834 of file qcustomplot.h.
Referenced by pixelPoint(), and setCoords().
QCPAxis * QCPItemPosition::mValueAxis [protected]
Definition at line 833 of file qcustomplot.h.
Referenced by pixelPoint(), setAxes(), and setPixelPoint().
Author
Generated automatically by Doxygen for AQ0X from the source code.