QCPItemPixmap
NAME
QCPItemPixmap -
An arbitrary pixmap.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPAbstractItem.
Public Member Functions
QCPItemPixmap (QCustomPlot *parentPlot)
Creates a rectangle item and sets default values.
virtual ~QCPItemPixmap ()
QPixmap pixmap () const
bool scaled () const
Qt::AspectRatioMode aspectRatioMode () const
QPen pen () const
QPen selectedPen () const
void setPixmap (const QPixmap &pixmap)
Sets the pixmap that will be displayed.
void setScaled (bool scaled, Qt::AspectRatioMode aspectRatioMode=Qt::KeepAspectRatio)
Sets whether the pixmap will be scaled to fit the rectangle defined by the topLeft and bottomRight positions.
void setPen (const QPen &pen)
Sets the pen that will be used to draw a border around the pixmap.
void setSelectedPen (const QPen &pen)
Sets the pen that will be used to draw a border around the pixmap when selected.
virtual double selectTest (const QPointF &pos) const
This function is used to decide whether a click hits an item or not.
Public Attributes
QCPItemPosition *const topLeft
QCPItemPosition *const bottomRight
QCPItemAnchor *const top
QCPItemAnchor *const topRight
QCPItemAnchor *const right
QCPItemAnchor *const bottom
QCPItemAnchor *const bottomLeft
QCPItemAnchor *const left
Protected Types
enum AnchorIndex { aiTop, aiTopRight, aiRight, aiBottom, aiBottomLeft, aiLeft }
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
void updateScaledPixmap (QRect finalRect=QRect(), bool flipHorz=false, bool flipVert=false)
QRect getFinalRect (bool *flippedHorz=0, bool *flippedVert=0) const
QPen mainPen () const
Protected Attributes
QPixmap mPixmap
QPixmap mScaledPixmap
bool mScaled
Qt::AspectRatioMode mAspectRatioMode
QPen mPen
QPen mSelectedPen
Additional Inherited Members
Detailed Description
An arbitrary pixmap.
Pixmap example. Blue dotted circles are anchors, solid blue discs are positions. It has two positions, topLeft and bottomRight, which define the rectangle the pixmap will be drawn in. Depending on the scale setting (setScaled), the pixmap will be either scaled to fit the rectangle or be drawn aligned to the topLeft position.
If scaling is enabled and topLeft is further to the bottom/right than bottomRight (as shown on the right side of the example image), the pixmap will be flipped in the respective orientations.
Definition at line 1060 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPItemPixmap::AnchorIndex [protected]
Enumerator
aiTop
aiTopRight
aiRight
aiBottom
aiBottomLeft
aiLeft
Definition at line 1093 of file qcustomplot.h.
{aiTop, aiTopRight, aiRight, aiBottom, aiBottomLeft, aiLeft};
Constructor & Destructor Documentation
QCPItemPixmap::QCPItemPixmap (QCustomPlot *parentPlot)
Creates a rectangle item and sets default values. The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 12534 of file qcustomplot.cpp.
References bottomRight, QCPItemPosition::setCoords(), setPen(), setScaled(), setSelectedPen(), and topLeft.
                                                    :
  QCPAbstractItem(parentPlot),
  topLeft(createPosition("topLeft")),
  bottomRight(createPosition("bottomRight")),
  top(createAnchor("top", aiTop)),
  topRight(createAnchor("topRight", aiTopRight)),
  right(createAnchor("right", aiRight)),
  bottom(createAnchor("bottom", aiBottom)),
  bottomLeft(createAnchor("bottomLeft", aiBottomLeft)),
  left(createAnchor("left", aiLeft))
{
  topLeft->setCoords(0, 1);
  bottomRight->setCoords(1, 0);
  
  setPen(Qt::NoPen);
  setSelectedPen(QPen(Qt::blue));
  setScaled(false, Qt::KeepAspectRatio);
}
QCPItemPixmap::~QCPItemPixmap () [virtual]
Definition at line 12553 of file qcustomplot.cpp.
{
}
Member Function Documentation
QPointF QCPItemPixmap::anchorPixelPoint (intanchorId) const [protected], [virtual]
Returns the pixel position of the anchor with Id anchorId. This function must be reimplemented in item subclasses if they want to provide anchors (QCPItemAnchor).
For example, if the item has two anchors with id 0 and 1, this function takes one of these anchor ids and returns the respective pixel points of the specified anchor.
See also:
createAnchor
Reimplemented from QCPAbstractItem.
Definition at line 12628 of file qcustomplot.cpp.
References aiBottom, aiBottomLeft, aiLeft, aiRight, aiTop, aiTopRight, and getFinalRect().
{
  bool flipHorz;
  bool flipVert;
  QRect rect = getFinalRect(&flipHorz, &flipVert);
  // we actually want denormal rects (negative width/height) here, so restore
  // the flipped state:
  if (flipHorz)
    rect.adjust(rect.width(), 0, -rect.width(), 0);
  if (flipVert)
    rect.adjust(0, rect.height(), 0, -rect.height());
  
  switch (anchorId)
  {
    case aiTop: return (rect.topLeft()+rect.topRight())*0.5;
    case aiTopRight: return rect.topRight();
    case aiRight: return (rect.topRight()+rect.bottomRight())*0.5;
    case aiBottom: return (rect.bottomLeft()+rect.bottomRight())*0.5;
    case aiBottomLeft: return rect.bottomLeft();
    case aiLeft: return (rect.topLeft()+rect.bottomLeft())*0.5;;
  }
  
  qDebug() << Q_FUNC_INFO << "invalid anchorId" << anchorId;
  return QPointF();
}
Qt::AspectRatioMode QCPItemPixmap::aspectRatioMode () const [inline]
Definition at line 1070 of file qcustomplot.h.
Referenced by setScaled().
{ return mAspectRatioMode; }
void QCPItemPixmap::draw (QCPPainter *painter) [protected], [virtual]
Draws this item with the provided painter. Called by QCustomPlot::draw on all its visible items.
The cliprect of the provided painter is set to the rect returned by clipRect before this function is called. For items this depends on the clipping settings defined by setClipToAxisRect, setClipKeyAxis and setClipValueAxis.
Implements QCPAbstractItem.
Definition at line 12606 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), getFinalRect(), mainPen(), mPixmap, mScaled, mScaledPixmap, pen(), QCPPainter::setPen(), and updateScaledPixmap().
{
  bool flipHorz = false;
  bool flipVert = false;
  QRect rect = getFinalRect(&flipHorz, &flipVert);
  double clipPad = mainPen().style() == Qt::NoPen ? 0 : mainPen().widthF();
  QRect boundingRect = rect.adjusted(-clipPad, -clipPad, clipPad, clipPad);
  if (boundingRect.intersects(clipRect()))
  {
    updateScaledPixmap(rect, flipHorz, flipVert);
    painter->drawPixmap(rect.topLeft(), mScaled ? mScaledPixmap : mPixmap);
    QPen pen = mainPen();
    if (pen.style() != Qt::NoPen)
    {
      painter->setPen(pen);
      painter->setBrush(Qt::NoBrush);
      painter->drawRect(rect);
    }
  }
}
QRect QCPItemPixmap::getFinalRect (bool *flippedHorz = 0, bool *flippedVert = 0) const [protected]
Returns the final (tight) rect the pixmap is drawn in, depending on the current item positions and scaling settings.
The output parameters flippedHorz and flippedVert return whether the pixmap should be drawn flipped horizontally or vertically in the returned rect. (The returned rect itself is always normalized, i.e. the top left corner of the rect is actually further to the top/left than the bottom right corner). This is the case when the item position topLeft is further to the bottom/right than bottomRight.
If scaling is disabled, returns a rect with size of the original pixmap and the top left corner aligned with the item position topLeft. The position bottomRight is ignored.
Definition at line 12697 of file qcustomplot.cpp.
References bottomRight, mAspectRatioMode, mPixmap, mScaled, QCPItemPosition::pixelPoint(), and topLeft.
Referenced by anchorPixelPoint(), draw(), selectTest(), and updateScaledPixmap().
{
  QRect result;
  bool flipHorz = false;
  bool flipVert = false;
  QPoint p1 = topLeft->pixelPoint().toPoint();
  QPoint p2 = bottomRight->pixelPoint().toPoint();
  if (p1 == p2)
    return QRect(p1, QSize(0, 0));
  if (mScaled)
  {
    QSize newSize = QSize(p2.x()-p1.x(), p2.y()-p1.y());
    QPoint topLeft = p1;
    if (newSize.width() < 0)
    {
      flipHorz = true;
      newSize.rwidth() *= -1;
      topLeft.setX(p2.x());
    }
    if (newSize.height() < 0)
    {
      flipVert = true;
      newSize.rheight() *= -1;
      topLeft.setY(p2.y());
    }
    QSize scaledSize = mPixmap.size();
    scaledSize.scale(newSize, mAspectRatioMode);
    result = QRect(topLeft, scaledSize);
  } else
  {
    result = QRect(p1, mPixmap.size());
  }
  if (flippedHorz)
    *flippedHorz = flipHorz;
  if (flippedVert)
    *flippedVert = flipVert;
  return result;
}
QPen QCPItemPixmap::mainPen () const [protected]
Returns the pen that should be used for drawing lines. Returns mPen when the item is not selected and mSelectedPen when it is.
Definition at line 12741 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
{
  return mSelected ? mSelectedPen : mPen;
}
QPen QCPItemPixmap::pen () const [inline]
Definition at line 1071 of file qcustomplot.h.
References mPen.
Referenced by draw(), setPen(), and setSelectedPen().
{ return mPen; }
QPixmap QCPItemPixmap::pixmap () const [inline]
Definition at line 1068 of file qcustomplot.h.
Referenced by setPixmap().
{ return mPixmap; }
bool QCPItemPixmap::scaled () const [inline]
Definition at line 1069 of file qcustomplot.h.
Referenced by setScaled().
{ return mScaled; }
QPen QCPItemPixmap::selectedPen () const [inline]
Definition at line 1072 of file qcustomplot.h.
{ return mSelectedPen; }
double QCPItemPixmap::selectTest (const QPointF &pos) const [virtual]
This function is used to decide whether a click hits an item or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the item. If the item is either invisible or the distance couldn't be determined, -1.0 is returned. setSelectable has no influence on the return value of this function.
If the item is represented not by single lines but by an area like QCPItemRect or QCPItemText, a click inside the area returns a constant value greater zero (typically 99% of the selectionTolerance of the parent QCustomPlot). If the click lies outside the area, this function returns -1.0.
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs.
See also:
setSelected, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 12597 of file qcustomplot.cpp.
References getFinalRect(), QCPLayerable::mVisible, and QCPAbstractItem::rectSelectTest().
{
  if (!mVisible)
    return -1;
  
  return rectSelectTest(getFinalRect(), pos, true);
}
void QCPItemPixmap::setPen (const QPen &pen)
Sets the pen that will be used to draw a border around the pixmap.
See also:
setSelectedPen, setBrush
Definition at line 12581 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemPixmap().
{
  mPen = pen;
}
void QCPItemPixmap::setPixmap (const QPixmap &pixmap)
Sets the pixmap that will be displayed.
Definition at line 12560 of file qcustomplot.cpp.
References mPixmap, and pixmap().
{
  mPixmap = pixmap;
}
void QCPItemPixmap::setScaled (boolscaled, Qt::AspectRatioModeaspectRatioMode = Qt::KeepAspectRatio)
Sets whether the pixmap will be scaled to fit the rectangle defined by the topLeft and bottomRight positions.
Definition at line 12569 of file qcustomplot.cpp.
References aspectRatioMode(), mAspectRatioMode, mScaled, scaled(), and updateScaledPixmap().
Referenced by QCPItemPixmap().
{
  mScaled = scaled;
  mAspectRatioMode = aspectRatioMode;
  updateScaledPixmap();
}
void QCPItemPixmap::setSelectedPen (const QPen &pen)
Sets the pen that will be used to draw a border around the pixmap when selected.
See also:
setPen, setSelected
Definition at line 12591 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemPixmap().
{
  mSelectedPen = pen;
}
void QCPItemPixmap::updateScaledPixmap (QRectfinalRect = QRect(), boolflipHorz = false, boolflipVert = false) [protected]
Creates the buffered scaled image (mScaledPixmap) to fit the specified finalRect. The parameters flipHorz and flipVert control whether the resulting image shall be flipped horizontally or vertically. (This is used when topLeft is further to the bottom/right than bottomRight.)
This function only creates the scaled pixmap when the buffered pixmap has a different size than the expected result, so calling this function repeatedly, e.g. in the draw function, does not cause expensive rescaling every time.
If scaling is disabled, sets mScaledPixmap to a null QPixmap.
Definition at line 12667 of file qcustomplot.cpp.
References getFinalRect(), mAspectRatioMode, mPixmap, mScaled, and mScaledPixmap.
Referenced by draw(), and setScaled().
{
  if (mScaled)
  {
    if (finalRect.isNull())
      finalRect = getFinalRect(&flipHorz, &flipVert);
    if (finalRect.size() != mScaledPixmap.size())
    {
      mScaledPixmap = mPixmap.scaled(finalRect.size(), mAspectRatioMode, Qt::SmoothTransformation);
      if (flipHorz || flipVert)
        mScaledPixmap = QPixmap::fromImage(mScaledPixmap.toImage().mirrored(flipHorz, flipVert));
    }
  } else if (!mScaledPixmap.isNull())
    mScaledPixmap = QPixmap();
}
Member Data Documentation
QCPItemAnchor* const QCPItemPixmap::bottom
Definition at line 1088 of file qcustomplot.h.
QCPItemAnchor* const QCPItemPixmap::bottomLeft
Definition at line 1089 of file qcustomplot.h.
QCPItemPosition* const QCPItemPixmap::bottomRight
Definition at line 1084 of file qcustomplot.h.
Referenced by getFinalRect(), and QCPItemPixmap().
QCPItemAnchor* const QCPItemPixmap::left
Definition at line 1090 of file qcustomplot.h.
Qt::AspectRatioMode QCPItemPixmap::mAspectRatioMode [protected]
Definition at line 1097 of file qcustomplot.h.
Referenced by getFinalRect(), setScaled(), and updateScaledPixmap().
QPen QCPItemPixmap::mPen [protected]
Definition at line 1098 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
QPixmap QCPItemPixmap::mPixmap [protected]
Definition at line 1094 of file qcustomplot.h.
Referenced by draw(), getFinalRect(), setPixmap(), and updateScaledPixmap().
bool QCPItemPixmap::mScaled [protected]
Definition at line 1096 of file qcustomplot.h.
Referenced by draw(), getFinalRect(), setScaled(), and updateScaledPixmap().
QPixmap QCPItemPixmap::mScaledPixmap [protected]
Definition at line 1095 of file qcustomplot.h.
Referenced by draw(), and updateScaledPixmap().
QPen QCPItemPixmap::mSelectedPen [protected]
Definition at line 1098 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
QCPItemAnchor* const QCPItemPixmap::right
Definition at line 1087 of file qcustomplot.h.
QCPItemAnchor* const QCPItemPixmap::top
Definition at line 1085 of file qcustomplot.h.
QCPItemPosition* const QCPItemPixmap::topLeft
Definition at line 1083 of file qcustomplot.h.
Referenced by getFinalRect(), and QCPItemPixmap().
QCPItemAnchor* const QCPItemPixmap::topRight
Definition at line 1086 of file qcustomplot.h.
Author
Generated automatically by Doxygen for AQ0X from the source code.