QCPItemBracket
NAME
QCPItemBracket -
A bracket for referencing/highlighting certain parts in the plot.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPAbstractItem.
Public Types
enum BracketStyle { bsSquare, bsRound, bsCurly, bsCalligraphic }
Public Member Functions
QCPItemBracket (QCustomPlot *parentPlot)
Creates a bracket item and sets default values.
virtual ~QCPItemBracket ()
QPen pen () const
QPen selectedPen () const
double length () const
BracketStyle style () const
void setPen (const QPen &pen)
Sets the pen that will be used to draw the bracket.
void setSelectedPen (const QPen &pen)
Sets the pen that will be used to draw the bracket when selected.
void setLength (double length)
Sets the length in pixels how far the bracket extends in the direction towards the embraced span of the bracket (i.e.
void setStyle (BracketStyle style)
Sets the style of the bracket, i.e.
virtual double selectTest (const QPointF &pos) const
This function is used to decide whether a click hits an item or not.
Public Attributes
QCPItemPosition *const left
QCPItemPosition *const right
QCPItemAnchor *const center
Protected Types
enum AnchorIndex { aiCenter }
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
QPen mainPen () const
Protected Attributes
QPen mPen
QPen mSelectedPen
double mLength
BracketStyle mStyle
Additional Inherited Members
Detailed Description
A bracket for referencing/highlighting certain parts in the plot.
Bracket example. Blue dotted circles are anchors, solid blue discs are positions. It has two positions, left and right, which define the span of the bracket. If left is actually farther to the left than right, the bracket is opened to the bottom, as shown in the example image.
The bracket supports multiple styles via setStyle. The length, i.e. how far the bracket stretches away from the embraced span, can be controlled with setLength.
 Demonstrating the effect of different values for setLength, for styles bsCalligraphic and bsSquare. Anchors and positions are displayed for reference.
It provides an anchor center, to allow connection of other items, e.g. an arrow (QCPItemLine or QCPItemCurve) or a text label (QCPItemText), to the bracket.
Definition at line 1219 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPItemBracket::AnchorIndex [protected]
Enumerator
aiCenter
Definition at line 1252 of file qcustomplot.h.
{aiCenter};
enum QCPItemBracket::BracketStyle
Enumerator
bsSquare
A brace with angled edges.
bsRound
A brace with round edges.
bsCurly
A curly brace.
bsCalligraphic
A curly brace with varying stroke width giving a calligraphic impression.
Definition at line 1223 of file qcustomplot.h.
                    { bsSquare
                      ,bsRound
                      ,bsCurly
                      ,bsCalligraphic
  };
Constructor & Destructor Documentation
QCPItemBracket::QCPItemBracket (QCustomPlot *parentPlot)
Creates a bracket item and sets default values. The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 14482 of file qcustomplot.cpp.
References bsCalligraphic, left, right, QCPItemPosition::setCoords(), setLength(), setPen(), setSelectedPen(), and setStyle().
                                                      :
  QCPAbstractItem(parentPlot),
  left(createPosition("left")),
  right(createPosition("right")),
  center(createAnchor("center", aiCenter))
{
  left->setCoords(0, 0);
  right->setCoords(1, 1);
  
  setPen(QPen(Qt::black));
  setSelectedPen(QPen(Qt::blue, 2));
  setLength(8);
  setStyle(bsCalligraphic);
}
QCPItemBracket::~QCPItemBracket () [virtual]
Definition at line 14497 of file qcustomplot.cpp.
{
}
Member Function Documentation
QPointF QCPItemBracket::anchorPixelPoint (intanchorId) const [protected], [virtual]
Returns the pixel position of the anchor with Id anchorId. This function must be reimplemented in item subclasses if they want to provide anchors (QCPItemAnchor).
For example, if the item has two anchors with id 0 and 1, this function takes one of these anchor ids and returns the respective pixel points of the specified anchor.
See also:
createAnchor
Reimplemented from QCPAbstractItem.
Definition at line 14637 of file qcustomplot.cpp.
References aiCenter, left, mLength, QCPItemPosition::pixelPoint(), and right.
{
  QVector2D leftVec(left->pixelPoint());
  QVector2D rightVec(right->pixelPoint());
  if (leftVec.toPoint() == rightVec.toPoint())
    return leftVec.toPointF();
  
  QVector2D widthVec = (rightVec-leftVec)*0.5;
  QVector2D lengthVec(-widthVec.y(), widthVec.x());
  lengthVec = lengthVec.normalized()*mLength;
  QVector2D centerVec = (rightVec+leftVec)*0.5-lengthVec;
  
  switch (anchorId)
  {
    case aiCenter:
      return centerVec.toPointF();
  }
  qDebug() << Q_FUNC_INFO << "invalid anchorId" << anchorId;
  return QPointF();
}
void QCPItemBracket::draw (QCPPainter *painter) [protected], [virtual]
Draws this item with the provided painter. Called by QCustomPlot::draw on all its visible items.
The cliprect of the provided painter is set to the rect returned by clipRect before this function is called. For items this depends on the clipping settings defined by setClipToAxisRect, setClipKeyAxis and setClipValueAxis.
Implements QCPAbstractItem.
Definition at line 14568 of file qcustomplot.cpp.
References bsCalligraphic, bsCurly, bsRound, bsSquare, QCPAbstractItem::clipRect(), color(), QCPPainter::drawLine(), left, mainPen(), mLength, mStyle, QCPItemPosition::pixelPoint(), right, and QCPPainter::setPen().
{
  QVector2D leftVec(left->pixelPoint());
  QVector2D rightVec(right->pixelPoint());
  if (leftVec.toPoint() == rightVec.toPoint())
    return;
  
  QVector2D widthVec = (rightVec-leftVec)*0.5;
  QVector2D lengthVec(-widthVec.y(), widthVec.x());
  lengthVec = lengthVec.normalized()*mLength;
  QVector2D centerVec = (rightVec+leftVec)*0.5-lengthVec;
  QPolygon boundingPoly;
  boundingPoly << leftVec.toPoint() << rightVec.toPoint()
               << (rightVec-lengthVec).toPoint() << (leftVec-lengthVec).toPoint();
  QRect clip = clipRect().adjusted(-mainPen().widthF(), -mainPen().widthF(), mainPen().widthF(), mainPen().widthF());
  if (clip.intersects(boundingPoly.boundingRect()))
  {
    painter->setPen(mainPen());
    switch (mStyle)
    {
      case bsSquare:
      {
        painter->drawLine((centerVec+widthVec).toPointF(), (centerVec-widthVec).toPointF());
        painter->drawLine((centerVec+widthVec).toPointF(), (centerVec+widthVec+lengthVec).toPointF());
        painter->drawLine((centerVec-widthVec).toPointF(), (centerVec-widthVec+lengthVec).toPointF());
        break;
      }
      case bsRound:
      {
        painter->setBrush(Qt::NoBrush);
        QPainterPath path;
        path.moveTo((centerVec+widthVec+lengthVec).toPointF());
        path.cubicTo((centerVec+widthVec).toPointF(), (centerVec+widthVec).toPointF(), centerVec.toPointF());
        path.cubicTo((centerVec-widthVec).toPointF(), (centerVec-widthVec).toPointF(), (centerVec-widthVec+lengthVec).toPointF());
        painter->drawPath(path);
        break;
      }
      case bsCurly:
      {
        painter->setBrush(Qt::NoBrush);
        QPainterPath path;
        path.moveTo((centerVec+widthVec+lengthVec).toPointF());
        path.cubicTo((centerVec+widthVec*1-lengthVec*0.8).toPointF(), (centerVec+0.4*widthVec+1*lengthVec).toPointF(), centerVec.toPointF());
        path.cubicTo((centerVec-0.4*widthVec+1*lengthVec).toPointF(), (centerVec-widthVec*1-lengthVec*0.8).toPointF(), (centerVec-widthVec+lengthVec).toPointF());
        painter->drawPath(path);
        break;
      }
      case bsCalligraphic:
      {
        painter->setPen(Qt::NoPen);
        painter->setBrush(QBrush(mainPen().color()));
        QPainterPath path;
        path.moveTo((centerVec+widthVec+lengthVec).toPointF());
        
        path.cubicTo((centerVec+widthVec*1-lengthVec*0.8).toPointF(), (centerVec+0.4*widthVec+0.8*lengthVec).toPointF(), centerVec.toPointF());
        path.cubicTo((centerVec-0.4*widthVec+0.8*lengthVec).toPointF(), (centerVec-widthVec*1-lengthVec*0.8).toPointF(), (centerVec-widthVec+lengthVec).toPointF());
        
        path.cubicTo((centerVec-widthVec*1-lengthVec*0.5).toPointF(), (centerVec-0.2*widthVec+1.2*lengthVec).toPointF(), (centerVec+lengthVec*0.2).toPointF());
        path.cubicTo((centerVec+0.2*widthVec+1.2*lengthVec).toPointF(), (centerVec+widthVec*1-lengthVec*0.5).toPointF(), (centerVec+widthVec+lengthVec).toPointF());
        
        painter->drawPath(path);
        break;
      }
    }
  }
}
double QCPItemBracket::length () const [inline]
Definition at line 1235 of file qcustomplot.h.
Referenced by setLength().
{ return mLength; }
QPen QCPItemBracket::mainPen () const [protected]
Returns the pen that should be used for drawing lines. Returns mPen when the item is not selected and mSelectedPen when it is.
Definition at line 14663 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
{
    return mSelected ? mSelectedPen : mPen;
}
QPen QCPItemBracket::pen () const [inline]
Definition at line 1233 of file qcustomplot.h.
References mPen.
Referenced by setPen(), and setSelectedPen().
{ return mPen; }
QPen QCPItemBracket::selectedPen () const [inline]
Definition at line 1234 of file qcustomplot.h.
{ return mSelectedPen; }
double QCPItemBracket::selectTest (const QPointF &pos) const [virtual]
This function is used to decide whether a click hits an item or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the item. If the item is either invisible or the distance couldn't be determined, -1.0 is returned. setSelectable has no influence on the return value of this function.
If the item is represented not by single lines but by an area like QCPItemRect or QCPItemText, a click inside the area returns a constant value greater zero (typically 99% of the selectionTolerance of the parent QCustomPlot). If the click lies outside the area, this function returns -1.0.
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs.
See also:
setSelected, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 14549 of file qcustomplot.cpp.
References QCPAbstractItem::distSqrToLine(), left, mLength, QCPLayerable::mVisible, QCPItemPosition::pixelPoint(), and right.
{
  if (!mVisible)
    return -1;
  
  QVector2D leftVec(left->pixelPoint());
  QVector2D rightVec(right->pixelPoint());
  if (leftVec.toPoint() == rightVec.toPoint())
    return -1;
  
  QVector2D widthVec = (rightVec-leftVec)*0.5;
  QVector2D lengthVec(-widthVec.y(), widthVec.x());
  lengthVec = lengthVec.normalized()*mLength;
  QVector2D centerVec = (rightVec+leftVec)*0.5-lengthVec;
  
  return qSqrt(distSqrToLine((centerVec-widthVec).toPointF(), (centerVec+widthVec).toPointF(), pos));
}
void QCPItemBracket::setLength (doublelength)
Sets the length in pixels how far the bracket extends in the direction towards the embraced span of the bracket (i.e. perpendicular to the left-right-direction)
 Demonstrating the effect of different values for setLength, for styles bsCalligraphic and bsSquare. Anchors and positions are displayed for reference.
Definition at line 14533 of file qcustomplot.cpp.
References length(), and mLength.
Referenced by QCPItemBracket().
{
  mLength = length;
}
void QCPItemBracket::setPen (const QPen &pen)
Sets the pen that will be used to draw the bracket. Note that when the style is bsCalligraphic, only the color will be taken from the pen, the stroke and width are ignored. To change the apparent stroke width of a calligraphic bracket, use setLength, which has a similar effect.
See also:
setSelectedPen
Definition at line 14510 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemBracket().
{
  mPen = pen;
}
void QCPItemBracket::setSelectedPen (const QPen &pen)
Sets the pen that will be used to draw the bracket when selected.
See also:
setPen, setSelected
Definition at line 14520 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemBracket().
{
  mSelectedPen = pen;
}
void QCPItemBracket::setStyle (QCPItemBracket::BracketStylestyle)
Sets the style of the bracket, i.e. the shape/visual appearance.
See also:
setPen
Definition at line 14543 of file qcustomplot.cpp.
References mStyle, and style().
Referenced by QCPItemBracket().
{
  mStyle = style;
}
BracketStyle QCPItemBracket::style () const [inline]
Definition at line 1236 of file qcustomplot.h.
Referenced by setStyle().
{ return mStyle; }
Member Data Documentation
QCPItemAnchor* const QCPItemBracket::center
Definition at line 1249 of file qcustomplot.h.
QCPItemPosition* const QCPItemBracket::left
Definition at line 1247 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), QCPItemBracket(), and selectTest().
double QCPItemBracket::mLength [protected]
Definition at line 1254 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setLength().
QPen QCPItemBracket::mPen [protected]
Definition at line 1253 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
QPen QCPItemBracket::mSelectedPen [protected]
Definition at line 1253 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
BracketStyle QCPItemBracket::mStyle [protected]
Definition at line 1255 of file qcustomplot.h.
Referenced by draw(), and setStyle().
QCPItemPosition* const QCPItemBracket::right
Definition at line 1248 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), QCPItemBracket(), and selectTest().
Author
Generated automatically by Doxygen for AQ0X from the source code.