QCPItemAnchor
NAME
QCPItemAnchor -
An anchor of an item to which positions can be attached to.
SYNOPSIS
#include <qcustomplot.h>
Inherited by QCPItemPosition.
Public Member Functions
QCPItemAnchor (QCustomPlot *parentPlot, QCPAbstractItem *parentItem, const QString name, int anchorId=-1)
Creates a new QCPItemAnchor.
virtual ~QCPItemAnchor ()
QString name () const
virtual QPointF pixelPoint () const
Returns the final absolute pixel position of the QCPItemAnchor on the QCustomPlot surface.
Protected Member Functions
void addChild (QCPItemPosition *pos)
void removeChild (QCPItemPosition *pos)
Protected Attributes
QCustomPlot * mParentPlot
QCPAbstractItem * mParentItem
int mAnchorId
QString mName
QSet< QCPItemPosition * > mChildren
Detailed Description
An anchor of an item to which positions can be attached to.
An item (QCPAbstractItem) may have one or more anchors. Unlike QCPItemPosition, an anchor doesn't control anything on its item, but provides a way to tie other items via their positions to the anchor.
For example, a QCPItemRect is defined by its positions topLeft and bottomRight. Additionally it has various anchors like top, topRight or bottomLeft etc. So you can attach the start (which is a QCPItemPosition) of a QCPItemLine to one of the anchors by calling QCPItemPosition::setParentAnchor on start, passing the wanted anchor of the QCPItemRect. This way the start of the line will now always follow the respective anchor location on the rect item.
Note that QCPItemPosition derives from QCPItemAnchor, so every position can also serve as an anchor to other positions.
To learn how to provide anchors in your own item subclasses, see the subclassing section of the QCPAbstractItem documentation.
Definition at line 769 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPItemAnchor::QCPItemAnchor (QCustomPlot *parentPlot, QCPAbstractItem *parentItem, const QStringname, intanchorId = -1)
Creates a new QCPItemAnchor. You shouldn't create QCPItemAnchor instances directly, even if you want to make a new item subclass. Use QCPAbstractItem::createAnchor instead, as explained in the subclassing section of the QCPAbstractItem documentation.
Definition at line 14384 of file qcustomplot.cpp.
                                                                                                                   :
  mParentPlot(parentPlot),
  mParentItem(parentItem),
  mAnchorId(anchorId),
  mName(name)
{
}
QCPItemAnchor::~QCPItemAnchor () [virtual]
Definition at line 14392 of file qcustomplot.cpp.
References mChildren.
{
  // unregister as parent at children:
  QList<QCPItemPosition*> currentChildren(mChildren.toList());
  for (int i=0; i<currentChildren.size(); ++i)
    currentChildren.at(i)->setParentAnchor(0); // this acts back on this anchor and child removes itself from mChildren
}
Member Function Documentation
void QCPItemAnchor::addChild (QCPItemPosition *pos) [protected]
Adds pos to the child list of this anchor. This is necessary to notify the children prior to destruction of the anchor.
Note that this function does not change the parent setting in pos.
Definition at line 14432 of file qcustomplot.cpp.
References mChildren.
Referenced by QCPItemPosition::setParentAnchor().
{
  if (!mChildren.contains(pos))
    mChildren.insert(pos);
  else
    qDebug() << Q_FUNC_INFO << "provided pos is child already" << reinterpret_cast<quintptr>(pos);
}
QString QCPItemAnchor::name () const [inline]
Definition at line 775 of file qcustomplot.h.
{ return mName; }
QPointF QCPItemAnchor::pixelPoint () const [virtual]
Returns the final absolute pixel position of the QCPItemAnchor on the QCustomPlot surface. The pixel information is internally retrieved via QCPAbstractItem::anchorPixelPosition of the parent item, QCPItemAnchor is just an intermediary.
Reimplemented in QCPItemPosition.
Definition at line 14406 of file qcustomplot.cpp.
References QCPAbstractItem::anchorPixelPoint(), mAnchorId, and mParentItem.
Referenced by QCPItemPosition::pixelPoint(), and QCPItemPosition::setPixelPoint().
{
  if (mParentItem)
  {
    if (mAnchorId > -1)
    {
      return mParentItem->anchorPixelPoint(mAnchorId);
    } else
    {
      qDebug() << Q_FUNC_INFO << "no valid anchor id set:" << mAnchorId;
      return QPointF();
    }
  } else
  {
    qDebug() << Q_FUNC_INFO << "no parent item set";
    return QPointF();
  }
}
void QCPItemAnchor::removeChild (QCPItemPosition *pos) [protected]
Removes pos from the child list of this anchor.
Note that this function does not change the parent setting in pos.
Definition at line 14446 of file qcustomplot.cpp.
References mChildren.
Referenced by QCPItemPosition::setParentAnchor(), and QCPItemPosition::~QCPItemPosition().
{
  if (!mChildren.remove(pos))
    qDebug() << Q_FUNC_INFO << "provided pos isn't child" << reinterpret_cast<quintptr>(pos);
}
Member Data Documentation
int QCPItemAnchor::mAnchorId [protected]
Definition at line 781 of file qcustomplot.h.
Referenced by pixelPoint().
QSet<QCPItemPosition*> QCPItemAnchor::mChildren [protected]
Definition at line 784 of file qcustomplot.h.
Referenced by addChild(), removeChild(), ~QCPItemAnchor(), and QCPItemPosition::~QCPItemPosition().
QString QCPItemAnchor::mName [protected]
Definition at line 782 of file qcustomplot.h.
QCPAbstractItem* QCPItemAnchor::mParentItem [protected]
Definition at line 780 of file qcustomplot.h.
Referenced by pixelPoint(), and QCPItemPosition::setParentAnchor().
QCustomPlot* QCPItemAnchor::mParentPlot [protected]
Definition at line 779 of file qcustomplot.h.
Referenced by QCPItemPosition::pixelPoint(), and QCPItemPosition::setPixelPoint().
Author
Generated automatically by Doxygen for AQ0X from the source code.