QCPItemRect
NAME
QCPItemRect -
A rectangle.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPAbstractItem.
Public Member Functions
QCPItemRect (QCustomPlot *parentPlot)
Creates a rectangle item and sets default values.
virtual ~QCPItemRect ()
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
void setPen (const QPen &pen)
Sets the pen that will be used to draw the line of the rectangle.
void setSelectedPen (const QPen &pen)
Sets the pen that will be used to draw the line of the rectangle when selected.
void setBrush (const QBrush &brush)
Sets the brush that will be used to fill the rectangle.
void setSelectedBrush (const QBrush &brush)
Sets the brush that will be used to fill the rectangle when selected.
virtual double selectTest (const QPointF &pos) const
This function is used to decide whether a click hits an item or not.
Public Attributes
QCPItemPosition *const topLeft
QCPItemPosition *const bottomRight
QCPItemAnchor *const top
QCPItemAnchor *const topRight
QCPItemAnchor *const right
QCPItemAnchor *const bottom
QCPItemAnchor *const bottomLeft
QCPItemAnchor *const left
Protected Types
enum AnchorIndex { aiTop, aiTopRight, aiRight, aiBottom, aiBottomLeft, aiLeft }
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
QPen mainPen () const
QBrush mainBrush () const
Protected Attributes
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
Additional Inherited Members
Detailed Description
A rectangle.
Rectangle example. Blue dotted circles are anchors, solid blue discs are positions. It has two positions, topLeft and bottomRight, which define the rectangle.
Definition at line 1016 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPItemRect::AnchorIndex [protected]
Enumerator
aiTop
aiTopRight
aiRight
aiBottom
aiBottomLeft
aiLeft
Definition at line 1048 of file qcustomplot.h.
{aiTop, aiTopRight, aiRight, aiBottom, aiBottomLeft, aiLeft};
Constructor & Destructor Documentation
QCPItemRect::QCPItemRect (QCustomPlot *parentPlot)
Creates a rectangle item and sets default values. The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 12377 of file qcustomplot.cpp.
References bottomRight, setBrush(), QCPItemPosition::setCoords(), setPen(), setSelectedBrush(), setSelectedPen(), and topLeft.
                                                :
  QCPAbstractItem(parentPlot),
  topLeft(createPosition("topLeft")),
  bottomRight(createPosition("bottomRight")),
  top(createAnchor("top", aiTop)),
  topRight(createAnchor("topRight", aiTopRight)),
  right(createAnchor("right", aiRight)),
  bottom(createAnchor("bottom", aiBottom)),
  bottomLeft(createAnchor("bottomLeft", aiBottomLeft)),
  left(createAnchor("left", aiLeft))
{
  topLeft->setCoords(0, 1);
  bottomRight->setCoords(1, 0);
  
  setPen(QPen(Qt::black));
  setSelectedPen(QPen(Qt::blue,2));
  setBrush(Qt::NoBrush);
  setSelectedBrush(Qt::NoBrush);
}
QCPItemRect::~QCPItemRect () [virtual]
Definition at line 12397 of file qcustomplot.cpp.
{
}
Member Function Documentation
QPointF QCPItemRect::anchorPixelPoint (intanchorId) const [protected], [virtual]
Returns the pixel position of the anchor with Id anchorId. This function must be reimplemented in item subclasses if they want to provide anchors (QCPItemAnchor).
For example, if the item has two anchors with id 0 and 1, this function takes one of these anchor ids and returns the respective pixel points of the specified anchor.
See also:
createAnchor
Reimplemented from QCPAbstractItem.
Definition at line 12473 of file qcustomplot.cpp.
References aiBottom, aiBottomLeft, aiLeft, aiRight, aiTop, aiTopRight, bottomRight, QCPItemPosition::pixelPoint(), and topLeft.
{
  QRectF rect = QRectF(topLeft->pixelPoint(), bottomRight->pixelPoint());
  switch (anchorId)
  {
    case aiTop: return (rect.topLeft()+rect.topRight())*0.5;
    case aiTopRight: return rect.topRight();
    case aiRight: return (rect.topRight()+rect.bottomRight())*0.5;
    case aiBottom: return (rect.bottomLeft()+rect.bottomRight())*0.5;
    case aiBottomLeft: return rect.bottomLeft();
    case aiLeft: return (rect.topLeft()+rect.bottomLeft())*0.5;;
  }
  
  qDebug() << Q_FUNC_INFO << "invalid anchorId" << anchorId;
  return QPointF();
}
QBrush QCPItemRect::brush () const [inline]
Definition at line 1026 of file qcustomplot.h.
Referenced by setBrush(), and setSelectedBrush().
{ return mBrush; }
void QCPItemRect::draw (QCPPainter *painter) [protected], [virtual]
Draws this item with the provided painter. Called by QCustomPlot::draw on all its visible items.
The cliprect of the provided painter is set to the rect returned by clipRect before this function is called. For items this depends on the clipping settings defined by setClipToAxisRect, setClipKeyAxis and setClipValueAxis.
Implements QCPAbstractItem.
Definition at line 12455 of file qcustomplot.cpp.
References bottomRight, QCPAbstractItem::clipRect(), mainBrush(), mainPen(), QCPItemPosition::pixelPoint(), QCPPainter::setPen(), and topLeft.
{
  QPointF p1 = topLeft->pixelPoint();
  QPointF p2 = bottomRight->pixelPoint();
  if (p1.toPoint() == p2.toPoint())
    return;
  QRectF rect = QRectF(p1, p2).normalized();
  double clipPad = mainPen().widthF();
  QRectF boundingRect = rect.adjusted(-clipPad, -clipPad, clipPad, clipPad);
  if (boundingRect.intersects(clipRect())) // only draw if bounding rect of rect item is visible in cliprect
  {
    painter->setPen(mainPen());
    painter->setBrush(mainBrush());
    painter->drawRect(rect);
  }
}
QBrush QCPItemRect::mainBrush () const [protected]
Returns the brush that should be used for drawing fills of the item. Returns mBrush when the item is not selected and mSelectedBrush when it is.
Definition at line 12505 of file qcustomplot.cpp.
References mBrush, QCPAbstractItem::mSelected, and mSelectedBrush.
Referenced by draw().
{
  return mSelected ? mSelectedBrush : mBrush;
}
QPen QCPItemRect::mainPen () const [protected]
Returns the pen that should be used for drawing lines. Returns mPen when the item is not selected and mSelectedPen when it is.
Definition at line 12495 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
{
  return mSelected ? mSelectedPen : mPen;
}
QPen QCPItemRect::pen () const [inline]
Definition at line 1024 of file qcustomplot.h.
References mPen.
Referenced by setPen(), and setSelectedPen().
{ return mPen; }
QBrush QCPItemRect::selectedBrush () const [inline]
Definition at line 1027 of file qcustomplot.h.
{ return mSelectedBrush; }
QPen QCPItemRect::selectedPen () const [inline]
Definition at line 1025 of file qcustomplot.h.
{ return mSelectedPen; }
double QCPItemRect::selectTest (const QPointF &pos) const [virtual]
This function is used to decide whether a click hits an item or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the item. If the item is either invisible or the distance couldn't be determined, -1.0 is returned. setSelectable has no influence on the return value of this function.
If the item is represented not by single lines but by an area like QCPItemRect or QCPItemText, a click inside the area returns a constant value greater zero (typically 99% of the selectionTolerance of the parent QCustomPlot). If the click lies outside the area, this function returns -1.0.
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs.
See also:
setSelected, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 12444 of file qcustomplot.cpp.
References bottomRight, mBrush, QCPLayerable::mVisible, QCPItemPosition::pixelPoint(), QCPAbstractItem::rectSelectTest(), and topLeft.
{
  if (!mVisible)
    return -1;
  
  QRectF rect = QRectF(topLeft->pixelPoint(), bottomRight->pixelPoint()).normalized();
  bool filledRect = mBrush.style() != Qt::NoBrush && mBrush.color().alpha() != 0;
  return rectSelectTest(rect, pos, filledRect);
}
void QCPItemRect::setBrush (const QBrush &brush)
Sets the brush that will be used to fill the rectangle. To disable filling, set brush to Qt::NoBrush.
See also:
setSelectedBrush, setPen
Definition at line 12427 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by QCPItemRect().
{
  mBrush = brush;
}
void QCPItemRect::setPen (const QPen &pen)
Sets the pen that will be used to draw the line of the rectangle.
See also:
setSelectedPen, setBrush
Definition at line 12406 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemRect().
{
  mPen = pen;
}
void QCPItemRect::setSelectedBrush (const QBrush &brush)
Sets the brush that will be used to fill the rectangle when selected. To disable filling, set brush to Qt::NoBrush.
See also:
setBrush
Definition at line 12438 of file qcustomplot.cpp.
References brush(), and mSelectedBrush.
Referenced by QCPItemRect().
{
  mSelectedBrush = brush;
}
void QCPItemRect::setSelectedPen (const QPen &pen)
Sets the pen that will be used to draw the line of the rectangle when selected.
See also:
setPen, setSelected
Definition at line 12416 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemRect().
{
  mSelectedPen = pen;
}
Member Data Documentation
QCPItemAnchor* const QCPItemRect::bottom
Definition at line 1043 of file qcustomplot.h.
QCPItemAnchor* const QCPItemRect::bottomLeft
Definition at line 1044 of file qcustomplot.h.
QCPItemPosition* const QCPItemRect::bottomRight
Definition at line 1039 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), QCPItemRect(), and selectTest().
QCPItemAnchor* const QCPItemRect::left
Definition at line 1045 of file qcustomplot.h.
QBrush QCPItemRect::mBrush [protected]
Definition at line 1050 of file qcustomplot.h.
Referenced by mainBrush(), selectTest(), and setBrush().
QPen QCPItemRect::mPen [protected]
Definition at line 1049 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
QBrush QCPItemRect::mSelectedBrush [protected]
Definition at line 1050 of file qcustomplot.h.
Referenced by mainBrush(), and setSelectedBrush().
QPen QCPItemRect::mSelectedPen [protected]
Definition at line 1049 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
QCPItemAnchor* const QCPItemRect::right
Definition at line 1042 of file qcustomplot.h.
QCPItemAnchor* const QCPItemRect::top
Definition at line 1040 of file qcustomplot.h.
QCPItemPosition* const QCPItemRect::topLeft
Definition at line 1038 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), QCPItemRect(), and selectTest().
QCPItemAnchor* const QCPItemRect::topRight
Definition at line 1041 of file qcustomplot.h.
Author
Generated automatically by Doxygen for AQ0X from the source code.