QCPItemText
NAME
QCPItemText -
A text label.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPAbstractItem.
Public Member Functions
QCPItemText (QCustomPlot *parentPlot)
Creates a text item and sets default values.
virtual ~QCPItemText ()
QColor color () const
QColor selectedColor () const
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
QFont font () const
QFont selectedFont () const
QString text () const
Qt::Alignment positionAlignment () const
Qt::Alignment textAlignment () const
double rotation () const
QMargins padding () const
void setColor (const QColor &color)
Sets the color of the text.
void setSelectedColor (const QColor &color)
Sets the color of the text that will be used when the item is selected.
void setPen (const QPen &pen)
Sets the pen that will be used do draw a rectangular border around the text.
void setSelectedPen (const QPen &pen)
Sets the pen that will be used do draw a rectangular border around the text, when the item is selected.
void setBrush (const QBrush &brush)
Sets the brush that will be used do fill the background of the text.
void setSelectedBrush (const QBrush &brush)
Sets the brush that will be used do fill the background of the text, when the item is selected.
void setFont (const QFont &font)
Sets the font of the text.
void setSelectedFont (const QFont &font)
Sets the font of the text that will be used when the item is selected.
void setText (const QString &text)
Sets the text that will be displayed.
void setPositionAlignment (Qt::Alignment alignment)
Sets which point of the text rect shall be aligned with position.
void setTextAlignment (Qt::Alignment alignment)
Controls how (multi-lined) text is aligned inside the text rect (typically Qt::AlignLeft, Qt::AlignCenter or Qt::AlignRight).
void setRotation (double degrees)
Sets the angle in degrees by which the text (and the text rectangle, if visible) will be rotated around position.
void setPadding (const QMargins &padding)
Sets the distance between the border of the text rectangle and the text.
virtual double selectTest (const QPointF &pos) const
This function is used to decide whether a click hits an item or not.
Public Attributes
QCPItemPosition *const position
QCPItemAnchor *const topLeft
QCPItemAnchor *const top
QCPItemAnchor *const topRight
QCPItemAnchor *const right
QCPItemAnchor *const bottomRight
QCPItemAnchor *const bottom
QCPItemAnchor *const bottomLeft
QCPItemAnchor *const left
Protected Types
enum AnchorIndex { aiTopLeft, aiTop, aiTopRight, aiRight, aiBottomRight, aiBottom, aiBottomLeft, aiLeft }
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
QPointF getTextDrawPoint (const QPointF &pos, const QRectF &rect, Qt::Alignment positionAlignment) const
QFont mainFont () const
QColor mainColor () const
QPen mainPen () const
QBrush mainBrush () const
Protected Attributes
QColor mColor
QColor mSelectedColor
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
QFont mFont
QFont mSelectedFont
QString mText
Qt::Alignment mPositionAlignment
Qt::Alignment mTextAlignment
double mRotation
QMargins mPadding
Additional Inherited Members
Detailed Description
A text label.
Text example. Blue dotted circles are anchors, solid blue discs are positions. Its position is defined by the member position and the setting of setPositionAlignment. The latter controls which part of the text rect shall be aligned with position.
The text alignment itself (i.e. left, center, right) can be controlled with setTextAlignment.
The text may be rotated around the position point with setRotation.
Definition at line 1109 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPItemText::AnchorIndex [protected]
Enumerator
aiTopLeft
aiTop
aiTopRight
aiRight
aiBottomRight
aiBottom
aiBottomLeft
aiLeft
Definition at line 1160 of file qcustomplot.h.
{aiTopLeft, aiTop, aiTopRight, aiRight, aiBottomRight, aiBottom, aiBottomLeft, aiLeft};
Constructor & Destructor Documentation
QCPItemText::QCPItemText (QCustomPlot *parentPlot)
Creates a text item and sets default values. The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 12770 of file qcustomplot.cpp.
References position, setBrush(), setColor(), QCPItemPosition::setCoords(), setPen(), setPositionAlignment(), setRotation(), setSelectedBrush(), setSelectedColor(), setSelectedPen(), setText(), and setTextAlignment().
                                                :
  QCPAbstractItem(parentPlot),
  position(createPosition("position")),
  topLeft(createAnchor("topLeft", aiTopLeft)),
  top(createAnchor("top", aiTop)),
  topRight(createAnchor("topRight", aiTopRight)),
  right(createAnchor("right", aiRight)),
  bottomRight(createAnchor("bottomRight", aiBottomRight)),
  bottom(createAnchor("bottom", aiBottom)),
  bottomLeft(createAnchor("bottomLeft", aiBottomLeft)),
  left(createAnchor("left", aiLeft))
{
  position->setCoords(0, 0);
  
  setRotation(0);
  setTextAlignment(Qt::AlignTop|Qt::AlignHCenter);
  setPositionAlignment(Qt::AlignCenter);
  setText("text");
  
  setPen(Qt::NoPen);
  setSelectedPen(Qt::NoPen);
  setBrush(Qt::NoBrush);
  setSelectedBrush(Qt::NoBrush);
  setColor(Qt::black);
  setSelectedColor(Qt::blue);
}
QCPItemText::~QCPItemText () [virtual]
Definition at line 12797 of file qcustomplot.cpp.
{
}
Member Function Documentation
QPointF QCPItemText::anchorPixelPoint (intanchorId) const [protected], [virtual]
Returns the pixel position of the anchor with Id anchorId. This function must be reimplemented in item subclasses if they want to provide anchors (QCPItemAnchor).
For example, if the item has two anchors with id 0 and 1, this function takes one of these anchor ids and returns the respective pixel points of the specified anchor.
See also:
createAnchor
Reimplemented from QCPAbstractItem.
Definition at line 12991 of file qcustomplot.cpp.
References aiBottom, aiBottomLeft, aiBottomRight, aiLeft, aiRight, aiTop, aiTopLeft, aiTopRight, getTextDrawPoint(), mainFont(), mPadding, mPositionAlignment, mRotation, mText, mTextAlignment, QCPItemPosition::pixelPoint(), and position.
{
  // get actual rect points (pretty much copied from draw function):
  QPointF pos(position->pixelPoint());
  QTransform transform;
  transform.translate(pos.x(), pos.y());
  if (!qFuzzyIsNull(mRotation))
    transform.rotate(mRotation);
  QFontMetrics fontMetrics(mainFont());
  QRect textRect = fontMetrics.boundingRect(0, 0, 0, 0, Qt::TextDontClip|mTextAlignment, mText);
  QRectF textBoxRect = textRect.adjusted(-mPadding.left(), -mPadding.top(), mPadding.right(), mPadding.bottom());
  QPointF textPos = getTextDrawPoint(QPointF(0, 0), textBoxRect, mPositionAlignment); // 0, 0 because the transform does the translation
  textBoxRect.moveTopLeft(textPos.toPoint());
  QPolygonF rectPoly = transform.map(QPolygonF(textBoxRect));
  
  switch (anchorId)
  {
    case aiTopLeft: return rectPoly.at(0);
    case aiTop: return (rectPoly.at(0)+rectPoly.at(1))*0.5;
    case aiTopRight: return rectPoly.at(1);
    case aiRight: return (rectPoly.at(1)+rectPoly.at(2))*0.5;
    case aiBottomRight: return rectPoly.at(2);
    case aiBottom: return (rectPoly.at(2)+rectPoly.at(3))*0.5;
    case aiBottomLeft: return rectPoly.at(3);
    case aiLeft: return (rectPoly.at(3)+rectPoly.at(0))*0.5;
  }
  
  qDebug() << Q_FUNC_INFO << "invalid anchorId" << anchorId;
  return QPointF();
}
QBrush QCPItemText::brush () const [inline]
Definition at line 1121 of file qcustomplot.h.
Referenced by setBrush(), and setSelectedBrush().
{ return mBrush; }
QColor QCPItemText::color () const [inline]
Definition at line 1117 of file qcustomplot.h.
References mColor.
Referenced by draw(), setColor(), and setSelectedColor().
{ return mColor; }
void QCPItemText::draw (QCPPainter *painter) [protected], [virtual]
Draws this item with the provided painter. Called by QCustomPlot::draw on all its visible items.
The cliprect of the provided painter is set to the rect returned by clipRect before this function is called. For items this depends on the clipping settings defined by setClipToAxisRect, setClipKeyAxis and setClipValueAxis.
Implements QCPAbstractItem.
Definition at line 12959 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), color(), getTextDrawPoint(), mainBrush(), mainColor(), mainFont(), mainPen(), mPadding, mPositionAlignment, mRotation, mText, mTextAlignment, QCPItemPosition::pixelPoint(), position, and QCPPainter::setPen().
{
  QPointF pos(position->pixelPoint());
  QTransform transform;
  transform.translate(pos.x(), pos.y());
  if (!qFuzzyIsNull(mRotation))
    transform.rotate(mRotation);
  painter->setFont(mainFont());
  QRect textRect = painter->fontMetrics().boundingRect(0, 0, 0, 0, Qt::TextDontClip|mTextAlignment, mText);
  QRect textBoxRect = textRect.adjusted(-mPadding.left(), -mPadding.top(), mPadding.right(), mPadding.bottom());
  QPointF textPos = getTextDrawPoint(QPointF(0, 0), textBoxRect, mPositionAlignment); // 0, 0 because the transform does the translation
  textRect.moveTopLeft(textPos.toPoint()+QPoint(mPadding.left(), mPadding.top()));
  textBoxRect.moveTopLeft(textPos.toPoint());
  double clipPad = mainPen().widthF();
  QRect boundingRect = textBoxRect.adjusted(-clipPad, -clipPad, clipPad, clipPad);
  if (transform.mapRect(boundingRect).intersects(clipRect()))
  {
    painter->setTransform(transform);
    if ((mainBrush().style() != Qt::NoBrush && mainBrush().color().alpha() != 0) ||
        (mainPen().style() != Qt::NoPen && mainPen().color().alpha() != 0))
    {
      painter->setPen(mainPen());
      painter->setBrush(mainBrush());
      painter->drawRect(textBoxRect);
    }
    painter->setBrush(Qt::NoBrush);
    painter->setPen(QPen(mainColor()));
    painter->drawText(textRect, Qt::TextDontClip|mTextAlignment, mText);
  }
}
QFont QCPItemText::font () const [inline]
Definition at line 1123 of file qcustomplot.h.
Referenced by setFont(), and setSelectedFont().
{ return mFont; }
QPointF QCPItemText::getTextDrawPoint (const QPointF &pos, const QRectF &rect, Qt::AlignmentpositionAlignment) const [protected]
Returns the point that must be given to the QPainter::drawText function (which expects the top left point of the text rect), according to the position pos, the text bounding box rect and the requested positionAlignment.
For example, if positionAlignment is Qt::AlignLeft | Qt::AlignBottom the returned point will be shifted upward by the height of rect, starting from pos. So if the text is finally drawn at that point, the lower left corner of the resulting text rect is at pos.
Definition at line 13032 of file qcustomplot.cpp.
Referenced by anchorPixelPoint(), draw(), and selectTest().
{
  if (positionAlignment == 0 || positionAlignment == (Qt::AlignLeft|Qt::AlignTop))
    return pos;
  
  QPointF result = pos; // start at top left
  if (positionAlignment.testFlag(Qt::AlignHCenter))
    result.rx() -= rect.width()/2.0;
  else if (positionAlignment.testFlag(Qt::AlignRight))
    result.rx() -= rect.width();
  if (positionAlignment.testFlag(Qt::AlignVCenter))
    result.ry() -= rect.height()/2.0;
  else if (positionAlignment.testFlag(Qt::AlignBottom))
    result.ry() -= rect.height();
  return result;
}
QBrush QCPItemText::mainBrush () const [protected]
Returns the brush that should be used for drawing fills of the item. Returns mBrush when the item is not selected and mSelectedBrush when it is.
Definition at line 13084 of file qcustomplot.cpp.
References mBrush, QCPAbstractItem::mSelected, and mSelectedBrush.
Referenced by draw().
{
  return mSelected ? mSelectedBrush : mBrush;
}
QColor QCPItemText::mainColor () const [protected]
Returns the color that should be used for drawing text. Returns mColor when the item is not selected and mSelectedColor when it is.
Definition at line 13064 of file qcustomplot.cpp.
References mColor, QCPAbstractItem::mSelected, and mSelectedColor.
Referenced by draw().
{
  return mSelected ? mSelectedColor : mColor;
}
QFont QCPItemText::mainFont () const [protected]
Returns the font that should be used for drawing text. Returns mFont when the item is not selected and mSelectedFont when it is.
Definition at line 13054 of file qcustomplot.cpp.
References mFont, QCPAbstractItem::mSelected, and mSelectedFont.
Referenced by anchorPixelPoint(), and draw().
{
  return mSelected ? mSelectedFont : mFont;
}
QPen QCPItemText::mainPen () const [protected]
Returns the pen that should be used for drawing lines. Returns mPen when the item is not selected and mSelectedPen when it is.
Definition at line 13074 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
{
  return mSelected ? mSelectedPen : mPen;
}
QMargins QCPItemText::padding () const [inline]
Definition at line 1129 of file qcustomplot.h.
Referenced by setPadding().
{ return mPadding; }
QPen QCPItemText::pen () const [inline]
Definition at line 1119 of file qcustomplot.h.
References mPen.
Referenced by setPen(), and setSelectedPen().
{ return mPen; }
Qt::Alignment QCPItemText::positionAlignment () const [inline]
Definition at line 1126 of file qcustomplot.h.
{ return mPositionAlignment; }
double QCPItemText::rotation () const [inline]
Definition at line 1128 of file qcustomplot.h.
{ return mRotation; }
QBrush QCPItemText::selectedBrush () const [inline]
Definition at line 1122 of file qcustomplot.h.
{ return mSelectedBrush; }
QColor QCPItemText::selectedColor () const [inline]
Definition at line 1118 of file qcustomplot.h.
{ return mSelectedColor; }
QFont QCPItemText::selectedFont () const [inline]
Definition at line 1124 of file qcustomplot.h.
{ return mSelectedFont; }
QPen QCPItemText::selectedPen () const [inline]
Definition at line 1120 of file qcustomplot.h.
{ return mSelectedPen; }
double QCPItemText::selectTest (const QPointF &pos) const [virtual]
This function is used to decide whether a click hits an item or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the item. If the item is either invisible or the distance couldn't be determined, -1.0 is returned. setSelectable has no influence on the return value of this function.
If the item is represented not by single lines but by an area like QCPItemRect or QCPItemText, a click inside the area returns a constant value greater zero (typically 99% of the selectionTolerance of the parent QCustomPlot). If the click lies outside the area, this function returns -1.0.
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs.
See also:
setSelected, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 12936 of file qcustomplot.cpp.
References getTextDrawPoint(), mFont, mPadding, mPositionAlignment, mRotation, mText, mTextAlignment, QCPLayerable::mVisible, QCPItemPosition::pixelPoint(), position, and QCPAbstractItem::rectSelectTest().
{
  if (!mVisible)
    return -1;
  
  // The rect may be rotated, so we transform the actual clicked pos to the rotated
  // coordinate system, wo we can use the normal rectSelectTest function for non-rotated rects:
  QPointF positionPixels(position->pixelPoint());
  QTransform inputTransform;
  inputTransform.translate(positionPixels.x(), positionPixels.y());
  inputTransform.rotate(-mRotation);
  inputTransform.translate(-positionPixels.x(), -positionPixels.y());
  QPointF rotatedPos = inputTransform.map(pos);
  QFontMetrics fontMetrics(mFont);
  QRect textRect = fontMetrics.boundingRect(0, 0, 0, 0, Qt::TextDontClip|mTextAlignment, mText);
  QRect textBoxRect = textRect.adjusted(-mPadding.left(), -mPadding.top(), mPadding.right(), mPadding.bottom());
  QPointF textPos = getTextDrawPoint(positionPixels, textBoxRect, mPositionAlignment);
  textBoxRect.moveTopLeft(textPos.toPoint());
  return rectSelectTest(textBoxRect, rotatedPos, true);
}
void QCPItemText::setBrush (const QBrush &brush)
Sets the brush that will be used do fill the background of the text. To disable the background, set brush to Qt::NoBrush.
See also:
setSelectedBrush, setPen, setPadding
Definition at line 12845 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by QCPItemText().
{
  mBrush = brush;
}
void QCPItemText::setColor (const QColor &color)
Sets the color of the text.
Definition at line 12804 of file qcustomplot.cpp.
References color(), and mColor.
Referenced by QCPItemText().
{
  mColor = color;
}
void QCPItemText::setFont (const QFont &font)
Sets the font of the text.
See also:
setSelectedFont, setColor
Definition at line 12866 of file qcustomplot.cpp.
References font(), and mFont.
{
  mFont = font;
}
void QCPItemText::setPadding (const QMargins &padding)
Sets the distance between the border of the text rectangle and the text. The appearance (and visibility) of the text rectangle can be controlled with setPen and setBrush.
Definition at line 12930 of file qcustomplot.cpp.
References mPadding, and padding().
{
  mPadding = padding;
}
void QCPItemText::setPen (const QPen &pen)
Sets the pen that will be used do draw a rectangular border around the text. To disable the border, set pen to Qt::NoPen.
See also:
setSelectedPen, setBrush, setPadding
Definition at line 12823 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemText().
{
  mPen = pen;
}
void QCPItemText::setPositionAlignment (Qt::Alignmentalignment)
Sets which point of the text rect shall be aligned with position. Examples:
If alignment is Qt::AlignHCenter | Qt::AlignTop, the text will be positioned such that the top of the text rect will be horizontally centered on position.
If alignment is Qt::AlignLeft | Qt::AlignBottom, position will indicate the bottom left corner of the text rect.
If you want to control the alignment of (multi-lined) text within the text rect, use setTextAlignment.
Definition at line 12904 of file qcustomplot.cpp.
References mPositionAlignment.
Referenced by QCPItemText().
{
  mPositionAlignment = alignment;
}
void QCPItemText::setRotation (doubledegrees)
Sets the angle in degrees by which the text (and the text rectangle, if visible) will be rotated around position.
Definition at line 12921 of file qcustomplot.cpp.
References mRotation.
Referenced by QCPItemText().
{
  mRotation = degrees;
}
void QCPItemText::setSelectedBrush (const QBrush &brush)
Sets the brush that will be used do fill the background of the text, when the item is selected. To disable the background, set brush to Qt::NoBrush.
See also:
setBrush
Definition at line 12856 of file qcustomplot.cpp.
References brush(), and mSelectedBrush.
Referenced by QCPItemText().
{
  mSelectedBrush = brush;
}
void QCPItemText::setSelectedColor (const QColor &color)
Sets the color of the text that will be used when the item is selected.
Definition at line 12812 of file qcustomplot.cpp.
References color(), and mSelectedColor.
Referenced by QCPItemText().
{
  mSelectedColor = color;
}
void QCPItemText::setSelectedFont (const QFont &font)
Sets the font of the text that will be used when the item is selected.
See also:
setFont
Definition at line 12876 of file qcustomplot.cpp.
References font(), and mSelectedFont.
{
  mSelectedFont = font;
}
void QCPItemText::setSelectedPen (const QPen &pen)
Sets the pen that will be used do draw a rectangular border around the text, when the item is selected. To disable the border, set pen to Qt::NoPen.
See also:
setPen
Definition at line 12834 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemText().
{
  mSelectedPen = pen;
}
void QCPItemText::setText (const QString &text)
Sets the text that will be displayed. Multi-line texts are supported by inserting a line break character, e.g. '
'.
See also:
setFont, setColor, setTextAlignment
Definition at line 12887 of file qcustomplot.cpp.
References mText, and text().
Referenced by QCPItemText().
{
  mText = text;
}
void QCPItemText::setTextAlignment (Qt::Alignmentalignment)
Controls how (multi-lined) text is aligned inside the text rect (typically Qt::AlignLeft, Qt::AlignCenter or Qt::AlignRight).
Definition at line 12912 of file qcustomplot.cpp.
References mTextAlignment.
Referenced by QCPItemText().
{
  mTextAlignment = alignment;
}
QString QCPItemText::text () const [inline]
Definition at line 1125 of file qcustomplot.h.
Referenced by setText().
{ return mText; }
Qt::Alignment QCPItemText::textAlignment () const [inline]
Definition at line 1127 of file qcustomplot.h.
{ return mTextAlignment; }
Member Data Documentation
QCPItemAnchor* const QCPItemText::bottom
Definition at line 1155 of file qcustomplot.h.
QCPItemAnchor* const QCPItemText::bottomLeft
Definition at line 1156 of file qcustomplot.h.
QCPItemAnchor* const QCPItemText::bottomRight
Definition at line 1154 of file qcustomplot.h.
QCPItemAnchor* const QCPItemText::left
Definition at line 1157 of file qcustomplot.h.
QBrush QCPItemText::mBrush [protected]
Definition at line 1163 of file qcustomplot.h.
Referenced by mainBrush(), and setBrush().
QColor QCPItemText::mColor [protected]
Definition at line 1161 of file qcustomplot.h.
Referenced by mainColor(), and setColor().
QFont QCPItemText::mFont [protected]
Definition at line 1164 of file qcustomplot.h.
Referenced by mainFont(), selectTest(), and setFont().
QMargins QCPItemText::mPadding [protected]
Definition at line 1169 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setPadding().
QPen QCPItemText::mPen [protected]
Definition at line 1162 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
Qt::Alignment QCPItemText::mPositionAlignment [protected]
Definition at line 1166 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setPositionAlignment().
double QCPItemText::mRotation [protected]
Definition at line 1168 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setRotation().
QBrush QCPItemText::mSelectedBrush [protected]
Definition at line 1163 of file qcustomplot.h.
Referenced by mainBrush(), and setSelectedBrush().
QColor QCPItemText::mSelectedColor [protected]
Definition at line 1161 of file qcustomplot.h.
Referenced by mainColor(), and setSelectedColor().
QFont QCPItemText::mSelectedFont [protected]
Definition at line 1164 of file qcustomplot.h.
Referenced by mainFont(), and setSelectedFont().
QPen QCPItemText::mSelectedPen [protected]
Definition at line 1162 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
QString QCPItemText::mText [protected]
Definition at line 1165 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setText().
Qt::Alignment QCPItemText::mTextAlignment [protected]
Definition at line 1167 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setTextAlignment().
QCPItemPosition* const QCPItemText::position
Definition at line 1149 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), QCPItemText(), and selectTest().
QCPItemAnchor* const QCPItemText::right
Definition at line 1153 of file qcustomplot.h.
QCPItemAnchor* const QCPItemText::top
Definition at line 1151 of file qcustomplot.h.
QCPItemAnchor* const QCPItemText::topLeft
Definition at line 1150 of file qcustomplot.h.
QCPItemAnchor* const QCPItemText::topRight
Definition at line 1152 of file qcustomplot.h.
Author
Generated automatically by Doxygen for AQ0X from the source code.