QCPItemLine
NAME
QCPItemLine -
A line from one point to another.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPAbstractItem.
Public Member Functions
QCPItemLine (QCustomPlot *parentPlot)
Creates a line item and sets default values.
virtual ~QCPItemLine ()
QPen pen () const
QPen selectedPen () const
QCPLineEnding head () const
QCPLineEnding tail () const
void setPen (const QPen &pen)
Sets the pen that will be used to draw the line.
void setSelectedPen (const QPen &pen)
Sets the pen that will be used to draw the line when selected.
void setHead (const QCPLineEnding &head)
Sets the line ending style of the head.
void setTail (const QCPLineEnding &tail)
Sets the line ending style of the tail.
virtual double selectTest (const QPointF &pos) const
This function is used to decide whether a click hits an item or not.
Public Attributes
QCPItemPosition *const start
QCPItemPosition *const end
Protected Member Functions
virtual void draw (QCPPainter *painter)
QLineF getRectClippedLine (const QVector2D &start, const QVector2D &end, const QRect &rect) const
QPen mainPen () const
Protected Attributes
QPen mPen
QPen mSelectedPen
QCPLineEnding mHead
QCPLineEnding mTail
Additional Inherited Members
Detailed Description
A line from one point to another.
Line example. Blue dotted circles are anchors, solid blue discs are positions. It has two positions, start and end, which define the end points of the line.
With setHead and setTail you may set different line ending styles, e.g. to create an arrow.
Definition at line 934 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPItemLine::QCPItemLine (QCustomPlot *parentPlot)
Creates a line item and sets default values. The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 11980 of file qcustomplot.cpp.
References end, QCPItemPosition::setCoords(), setPen(), setSelectedPen(), and start.
                                                :
  QCPAbstractItem(parentPlot),
  start(createPosition("start")),
  end(createPosition("end"))
{
  start->setCoords(0, 0);
  end->setCoords(1, 1);
  
  setPen(QPen(Qt::black));
  setSelectedPen(QPen(Qt::blue,2));
}
QCPItemLine::~QCPItemLine () [virtual]
Definition at line 11992 of file qcustomplot.cpp.
{
}
Member Function Documentation
void QCPItemLine::draw (QCPPainter *painter) [protected], [virtual]
Draws this item with the provided painter. Called by QCustomPlot::draw on all its visible items.
The cliprect of the provided painter is set to the rect returned by clipRect before this function is called. For items this depends on the clipping settings defined by setClipToAxisRect, setClipKeyAxis and setClipValueAxis.
Implements QCPAbstractItem.
Definition at line 12052 of file qcustomplot.cpp.
References QCPLineEnding::boundingDistance(), QCPAbstractItem::clipRect(), QCPLineEnding::draw(), QCPPainter::drawLine(), end, QCPLineEnding::esNone, getRectClippedLine(), mainPen(), mHead, mTail, QCPItemPosition::pixelPoint(), QCPPainter::setPen(), start, and QCPLineEnding::style().
{
  QVector2D startVec(start->pixelPoint());
  QVector2D endVec(end->pixelPoint());
  if (startVec.toPoint() == endVec.toPoint())
    return;
  // get visible segment of straight line inside clipRect:
  double clipPad = qMax(mHead.boundingDistance(), mTail.boundingDistance());
  clipPad = qMax(clipPad, mainPen().widthF());
  QLineF line = getRectClippedLine(startVec, endVec, clipRect().adjusted(-clipPad, -clipPad, clipPad, clipPad));
  // paint visible segment, if existent:
  if (!line.isNull())
  {
    painter->setPen(mainPen());
    painter->drawLine(line);
    painter->setBrush(Qt::SolidPattern);
    if (mTail.style() != QCPLineEnding::esNone)
      mTail.draw(painter, startVec, startVec-endVec);
    if (mHead.style() != QCPLineEnding::esNone)
      mHead.draw(painter, endVec, endVec-startVec);
  }
}
QLineF QCPItemLine::getRectClippedLine (const QVector2D &start, const QVector2D &end, const QRect &rect) const [protected]
Returns the section of the line defined by start and end, that is visible in the specified rect.
This is a helper function for draw.
Definition at line 12082 of file qcustomplot.cpp.
References start.
Referenced by draw().
{
  bool containsStart = rect.contains(start.x(), start.y());
  bool containsEnd = rect.contains(end.x(), end.y());
  if (containsStart && containsEnd)
    return QLineF(start.toPointF(), end.toPointF());
  
  QVector2D base = start;
  QVector2D vec = end-start;
  double bx, by;
  double gamma, mu;
  QLineF result;
  QList<QVector2D> pointVectors;
  if (!qFuzzyIsNull(vec.y())) // line is not horizontal
  {
    // check top of rect:
    bx = rect.left();
    by = rect.top();
    mu = (by-base.y())/vec.y();
    if (mu >= 0 && mu <= 1)
    {
      gamma = base.x()-bx + mu*vec.x();
      if (gamma >= 0 && gamma <= rect.width())
        pointVectors.append(QVector2D(bx+gamma, by));
    }
    // check bottom of rect:
    bx = rect.left();
    by = rect.bottom();
    mu = (by-base.y())/vec.y();
    if (mu >= 0 && mu <= 1)
    {
      gamma = base.x()-bx + mu*vec.x();
      if (gamma >= 0 && gamma <= rect.width())
        pointVectors.append(QVector2D(bx+gamma, by));
    }
  }
  if (!qFuzzyIsNull(vec.x())) // line is not vertical
  {
    // check left of rect:
    bx = rect.left();
    by = rect.top();
    mu = (bx-base.x())/vec.x();
    if (mu >= 0 && mu <= 1)
    {
      gamma = base.y()-by + mu*vec.y();
      if (gamma >= 0 && gamma <= rect.height())
        pointVectors.append(QVector2D(bx, by+gamma));
    }
    // check right of rect:
    bx = rect.right();
    by = rect.top();
    mu = (bx-base.x())/vec.x();
    if (mu >= 0 && mu <= 1)
    {
      gamma = base.y()-by + mu*vec.y();
      if (gamma >= 0 && gamma <= rect.height())
        pointVectors.append(QVector2D(bx, by+gamma));
    }
  }
  
  if (containsStart)
    pointVectors.append(start);
  if (containsEnd)
    pointVectors.append(end);
  
  // evaluate points:
  if (pointVectors.size() == 2)
  {
    result.setPoints(pointVectors.at(0).toPointF(), pointVectors.at(1).toPointF());
  } else if (pointVectors.size() > 2)
  {
    // line probably goes through corner of rect, and we got two points there. single out the point pair with greatest distance:
    double distSqrMax = 0;
    QVector2D pv1, pv2;
    for (int i=0; i<pointVectors.size()-1; ++i)
    {
      for (int k=i+1; k<pointVectors.size(); ++k)
      {
        double distSqr = (pointVectors.at(i)-pointVectors.at(k)).lengthSquared();
        if (distSqr > distSqrMax)
        {
          pv1 = pointVectors.at(i);
          pv2 = pointVectors.at(k);
          distSqrMax = distSqr;
        }
      }
    }
    result.setPoints(pv1.toPointF(), pv2.toPointF());
  }
  return result;
}
QCPLineEnding QCPItemLine::head () const [inline]
Definition at line 944 of file qcustomplot.h.
Referenced by setHead().
{ return mHead; }
QPen QCPItemLine::mainPen () const [protected]
Returns the pen that should be used for drawing lines. Returns mPen when the item is not selected and mSelectedPen when it is.
Definition at line 12180 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
{
  return mSelected ? mSelectedPen : mPen;
}
QPen QCPItemLine::pen () const [inline]
Definition at line 942 of file qcustomplot.h.
References mPen.
Referenced by setPen(), and setSelectedPen().
{ return mPen; }
QPen QCPItemLine::selectedPen () const [inline]
Definition at line 943 of file qcustomplot.h.
{ return mSelectedPen; }
double QCPItemLine::selectTest (const QPointF &pos) const [virtual]
This function is used to decide whether a click hits an item or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the item. If the item is either invisible or the distance couldn't be determined, -1.0 is returned. setSelectable has no influence on the return value of this function.
If the item is represented not by single lines but by an area like QCPItemRect or QCPItemText, a click inside the area returns a constant value greater zero (typically 99% of the selectionTolerance of the parent QCustomPlot). If the click lies outside the area, this function returns -1.0.
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs.
See also:
setSelected, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 12043 of file qcustomplot.cpp.
References QCPAbstractItem::distSqrToLine(), end, QCPLayerable::mVisible, QCPItemPosition::pixelPoint(), and start.
{
  if (!mVisible)
    return -1;
  
  return qSqrt(distSqrToLine(start->pixelPoint(), end->pixelPoint(), pos));
}
void QCPItemLine::setHead (const QCPLineEnding &head)
Sets the line ending style of the head. The head corresponds to the end position.
Note that due to the overloaded QCPLineEnding constructor, you may directly specify a QCPLineEnding::EndingStyle here, e.g.
setHead(QCPLineEnding::esSpikeArrow)
See also:
setTail
Definition at line 12024 of file qcustomplot.cpp.
References head(), and mHead.
{
  mHead = head;
}
void QCPItemLine::setPen (const QPen &pen)
Sets the pen that will be used to draw the line.
See also:
setSelectedPen
Definition at line 12001 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemLine().
{
  mPen = pen;
}
void QCPItemLine::setSelectedPen (const QPen &pen)
Sets the pen that will be used to draw the line when selected.
See also:
setPen, setSelected
Definition at line 12011 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemLine().
{
  mSelectedPen = pen;
}
void QCPItemLine::setTail (const QCPLineEnding &tail)
Sets the line ending style of the tail. The tail corresponds to the start position.
Note that due to the overloaded QCPLineEnding constructor, you may directly specify a QCPLineEnding::EndingStyle here, e.g.
setTail(QCPLineEnding::esSpikeArrow)
See also:
setHead
Definition at line 12037 of file qcustomplot.cpp.
References mTail, and tail().
{
  mTail = tail;
}
QCPLineEnding QCPItemLine::tail () const [inline]
Definition at line 945 of file qcustomplot.h.
Referenced by setTail().
{ return mTail; }
Member Data Documentation
QCPItemPosition* const QCPItemLine::end
Definition at line 957 of file qcustomplot.h.
Referenced by draw(), QCPItemLine(), and selectTest().
QCPLineEnding QCPItemLine::mHead [protected]
Definition at line 961 of file qcustomplot.h.
Referenced by draw(), and setHead().
QPen QCPItemLine::mPen [protected]
Definition at line 960 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
QPen QCPItemLine::mSelectedPen [protected]
Definition at line 960 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
QCPLineEnding QCPItemLine::mTail [protected]
Definition at line 961 of file qcustomplot.h.
Referenced by draw(), and setTail().
QCPItemPosition* const QCPItemLine::start
Definition at line 956 of file qcustomplot.h.
Referenced by draw(), getRectClippedLine(), QCPItemLine(), and selectTest().
Author
Generated automatically by Doxygen for AQ0X from the source code.