QCPItemEllipse
NAME
QCPItemEllipse -
An ellipse.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPAbstractItem.
Public Member Functions
QCPItemEllipse (QCustomPlot *parentPlot)
Creates an ellipse item and sets default values.
virtual ~QCPItemEllipse ()
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
void setPen (const QPen &pen)
Sets the pen that will be used to draw the line of the ellipse.
void setSelectedPen (const QPen &pen)
Sets the pen that will be used to draw the line of the ellipse when selected.
void setBrush (const QBrush &brush)
Sets the brush that will be used to fill the ellipse.
void setSelectedBrush (const QBrush &brush)
Sets the brush that will be used to fill the ellipse when selected.
virtual double selectTest (const QPointF &pos) const
This function is used to decide whether a click hits an item or not.
Public Attributes
QCPItemPosition *const topLeft
QCPItemPosition *const bottomRight
QCPItemAnchor *const topLeftRim
QCPItemAnchor *const top
QCPItemAnchor *const topRightRim
QCPItemAnchor *const right
QCPItemAnchor *const bottomRightRim
QCPItemAnchor *const bottom
QCPItemAnchor *const bottomLeftRim
QCPItemAnchor *const left
Protected Types
enum AnchorIndex { aiTopLeftRim, aiTop, aiTopRightRim, aiRight, aiBottomRightRim, aiBottom, aiBottomLeftRim, aiLeft }
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
QPen mainPen () const
QBrush mainBrush () const
Protected Attributes
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
Additional Inherited Members
Detailed Description
An ellipse.
Ellipse example. Blue dotted circles are anchors, solid blue discs are positions. It has two positions, topLeft and bottomRight, which define the rect the ellipse will be drawn in.
Definition at line 970 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPItemEllipse::AnchorIndex [protected]
Enumerator
aiTopLeftRim
aiTop
aiTopRightRim
aiRight
aiBottomRightRim
aiBottom
aiBottomLeftRim
aiLeft
Definition at line 1004 of file qcustomplot.h.
{aiTopLeftRim, aiTop, aiTopRightRim, aiRight, aiBottomRightRim, aiBottom, aiBottomLeftRim, aiLeft};
Constructor & Destructor Documentation
QCPItemEllipse::QCPItemEllipse (QCustomPlot *parentPlot)
Creates an ellipse item and sets default values. The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 12203 of file qcustomplot.cpp.
References bottomRight, setBrush(), QCPItemPosition::setCoords(), setPen(), setSelectedBrush(), setSelectedPen(), and topLeft.
                                                      :
  QCPAbstractItem(parentPlot),
  topLeft(createPosition("topLeft")),
  bottomRight(createPosition("bottomRight")),
  topLeftRim(createAnchor("topLeftRim", aiTopLeftRim)),
  top(createAnchor("top", aiTop)),
  topRightRim(createAnchor("topRightRim", aiTopRightRim)),
  right(createAnchor("right", aiRight)),
  bottomRightRim(createAnchor("bottomRightRim", aiBottomRightRim)),
  bottom(createAnchor("bottom", aiBottom)),
  bottomLeftRim(createAnchor("bottomLeftRim", aiBottomLeftRim)),
  left(createAnchor("left", aiLeft))
{
  topLeft->setCoords(0, 1);
  bottomRight->setCoords(1, 0);
  
  setPen(QPen(Qt::black));
  setSelectedPen(QPen(Qt::blue, 2));
  setBrush(Qt::NoBrush);
  setSelectedBrush(Qt::NoBrush);
}
QCPItemEllipse::~QCPItemEllipse () [virtual]
Definition at line 12225 of file qcustomplot.cpp.
{
}
Member Function Documentation
QPointF QCPItemEllipse::anchorPixelPoint (intanchorId) const [protected], [virtual]
Returns the pixel position of the anchor with Id anchorId. This function must be reimplemented in item subclasses if they want to provide anchors (QCPItemAnchor).
For example, if the item has two anchors with id 0 and 1, this function takes one of these anchor ids and returns the respective pixel points of the specified anchor.
See also:
createAnchor
Reimplemented from QCPAbstractItem.
Definition at line 12320 of file qcustomplot.cpp.
References aiBottom, aiBottomLeftRim, aiBottomRightRim, aiLeft, aiRight, aiTop, aiTopLeftRim, aiTopRightRim, bottomRight, QCPItemPosition::pixelPoint(), and topLeft.
{
  QRectF rect = QRectF(topLeft->pixelPoint(), bottomRight->pixelPoint());
  switch (anchorId)
  {
    case aiTopLeftRim: return rect.center()+(rect.topLeft()-rect.center())*1/qSqrt(2);
    case aiTop: return (rect.topLeft()+rect.topRight())*0.5;
    case aiTopRightRim: return rect.center()+(rect.topRight()-rect.center())*1/qSqrt(2);
    case aiRight: return (rect.topRight()+rect.bottomRight())*0.5;
    case aiBottomRightRim: return rect.center()+(rect.bottomRight()-rect.center())*1/qSqrt(2);
    case aiBottom: return (rect.bottomLeft()+rect.bottomRight())*0.5;
    case aiBottomLeftRim: return rect.center()+(rect.bottomLeft()-rect.center())*1/qSqrt(2);
    case aiLeft: return (rect.topLeft()+rect.bottomLeft())*0.5;;
  }
  
  qDebug() << Q_FUNC_INFO << "invalid anchorId" << anchorId;
  return QPointF();
}
QBrush QCPItemEllipse::brush () const [inline]
Definition at line 980 of file qcustomplot.h.
Referenced by setBrush(), and setSelectedBrush().
{ return mBrush; }
void QCPItemEllipse::draw (QCPPainter *painter) [protected], [virtual]
Draws this item with the provided painter. Called by QCustomPlot::draw on all its visible items.
The cliprect of the provided painter is set to the rect returned by clipRect before this function is called. For items this depends on the clipping settings defined by setClipToAxisRect, setClipKeyAxis and setClipValueAxis.
Implements QCPAbstractItem.
Definition at line 12296 of file qcustomplot.cpp.
References bottomRight, QCPAbstractItem::clipRect(), mainBrush(), mainPen(), QCPItemPosition::pixelPoint(), QCPPainter::setPen(), QCPLayerable::setVisible(), and topLeft.
{
  QPointF p1 = topLeft->pixelPoint();
  QPointF p2 = bottomRight->pixelPoint();
  if (p1.toPoint() == p2.toPoint())
    return;
  QRectF ellipseRect = QRectF(p1, p2).normalized();
  QRect clip = clipRect().adjusted(-mainPen().widthF(), -mainPen().widthF(), mainPen().widthF(), mainPen().widthF());
  if (ellipseRect.intersects(clip)) // only draw if bounding rect of ellipse is visible in cliprect
  {
    painter->setPen(mainPen());
    painter->setBrush(mainBrush());
    try
    {
      painter->drawEllipse(ellipseRect);
    } catch (...)
    {
      qDebug() << Q_FUNC_INFO << "Item too large for memory, setting invisible";
      setVisible(false);
    }
  }
}
QBrush QCPItemEllipse::mainBrush () const [protected]
Returns the brush that should be used for drawing fills of the item. Returns mBrush when the item is not selected and mSelectedBrush when it is.
Definition at line 12354 of file qcustomplot.cpp.
References mBrush, QCPAbstractItem::mSelected, and mSelectedBrush.
Referenced by draw().
{
  return mSelected ? mSelectedBrush : mBrush;
}
QPen QCPItemEllipse::mainPen () const [protected]
Returns the pen that should be used for drawing lines. Returns mPen when the item is not selected and mSelectedPen when it is.
Definition at line 12344 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
{
  return mSelected ? mSelectedPen : mPen;
}
QPen QCPItemEllipse::pen () const [inline]
Definition at line 978 of file qcustomplot.h.
References mPen.
Referenced by setPen(), and setSelectedPen().
{ return mPen; }
QBrush QCPItemEllipse::selectedBrush () const [inline]
Definition at line 981 of file qcustomplot.h.
{ return mSelectedBrush; }
QPen QCPItemEllipse::selectedPen () const [inline]
Definition at line 979 of file qcustomplot.h.
{ return mSelectedPen; }
double QCPItemEllipse::selectTest (const QPointF &pos) const [virtual]
This function is used to decide whether a click hits an item or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the item. If the item is either invisible or the distance couldn't be determined, -1.0 is returned. setSelectable has no influence on the return value of this function.
If the item is represented not by single lines but by an area like QCPItemRect or QCPItemText, a click inside the area returns a constant value greater zero (typically 99% of the selectionTolerance of the parent QCustomPlot). If the click lies outside the area, this function returns -1.0.
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs.
See also:
setSelected, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 12272 of file qcustomplot.cpp.
References bottomRight, mBrush, QCPLayerable::mParentPlot, QCPItemPosition::pixelPoint(), and topLeft.
{
  double result = -1;
  QPointF p1 = topLeft->pixelPoint();
  QPointF p2 = bottomRight->pixelPoint();
  QPointF center((p1+p2)/2.0);
  double a = qAbs(p1.x()-p2.x())/2.0;
  double b = qAbs(p1.y()-p2.y())/2.0;
  double x = pos.x()-center.x();
  double y = pos.y()-center.y();
  
  // distance to border:
  double c = 1.0/qSqrt(x*x/(a*a)+y*y/(b*b));
  result = qAbs(c-1)*qSqrt(x*x+y*y);
  // filled ellipse, allow click inside to count as hit:
  if (result > mParentPlot->selectionTolerance()*0.99 && mBrush.style() != Qt::NoBrush && mBrush.color().alpha() != 0)
  {
    if (x*x/(a*a) + y*y/(b*b) <= 1)
      result = mParentPlot->selectionTolerance()*0.99;
  }
  return result;
}
void QCPItemEllipse::setBrush (const QBrush &brush)
Sets the brush that will be used to fill the ellipse. To disable filling, set brush to Qt::NoBrush.
See also:
setSelectedBrush, setPen
Definition at line 12255 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by QCPItemEllipse().
{
  mBrush = brush;
}
void QCPItemEllipse::setPen (const QPen &pen)
Sets the pen that will be used to draw the line of the ellipse.
See also:
setSelectedPen, setBrush
Definition at line 12234 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemEllipse().
{
  mPen = pen;
}
void QCPItemEllipse::setSelectedBrush (const QBrush &brush)
Sets the brush that will be used to fill the ellipse when selected. To disable filling, set brush to Qt::NoBrush.
See also:
setBrush
Definition at line 12266 of file qcustomplot.cpp.
References brush(), and mSelectedBrush.
Referenced by QCPItemEllipse().
{
  mSelectedBrush = brush;
}
void QCPItemEllipse::setSelectedPen (const QPen &pen)
Sets the pen that will be used to draw the line of the ellipse when selected.
See also:
setPen, setSelected
Definition at line 12244 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemEllipse().
{
  mSelectedPen = pen;
}
Member Data Documentation
QCPItemAnchor* const QCPItemEllipse::bottom
Definition at line 999 of file qcustomplot.h.
QCPItemAnchor* const QCPItemEllipse::bottomLeftRim
Definition at line 1000 of file qcustomplot.h.
QCPItemPosition* const QCPItemEllipse::bottomRight
Definition at line 993 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), QCPItemEllipse(), and selectTest().
QCPItemAnchor* const QCPItemEllipse::bottomRightRim
Definition at line 998 of file qcustomplot.h.
QCPItemAnchor* const QCPItemEllipse::left
Definition at line 1001 of file qcustomplot.h.
QBrush QCPItemEllipse::mBrush [protected]
Definition at line 1006 of file qcustomplot.h.
Referenced by mainBrush(), selectTest(), and setBrush().
QPen QCPItemEllipse::mPen [protected]
Definition at line 1005 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
QBrush QCPItemEllipse::mSelectedBrush [protected]
Definition at line 1006 of file qcustomplot.h.
Referenced by mainBrush(), and setSelectedBrush().
QPen QCPItemEllipse::mSelectedPen [protected]
Definition at line 1005 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
QCPItemAnchor* const QCPItemEllipse::right
Definition at line 997 of file qcustomplot.h.
QCPItemAnchor* const QCPItemEllipse::top
Definition at line 995 of file qcustomplot.h.
QCPItemPosition* const QCPItemEllipse::topLeft
Definition at line 992 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), QCPItemEllipse(), and selectTest().
QCPItemAnchor* const QCPItemEllipse::topLeftRim
Definition at line 994 of file qcustomplot.h.
QCPItemAnchor* const QCPItemEllipse::topRightRim
Definition at line 996 of file qcustomplot.h.
Author
Generated automatically by Doxygen for AQ0X from the source code.