QCPItemCurve
NAME
QCPItemCurve -
A curved line from one point to another.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPAbstractItem.
Public Member Functions
QCPItemCurve (QCustomPlot *parentPlot)
Creates a curve item and sets default values.
virtual ~QCPItemCurve ()
QPen pen () const
QPen selectedPen () const
QCPLineEnding head () const
QCPLineEnding tail () const
void setPen (const QPen &pen)
Sets the pen that will be used to draw the line.
void setSelectedPen (const QPen &pen)
Sets the pen that will be used to draw the line when selected.
void setHead (const QCPLineEnding &head)
Sets the line ending style of the head.
void setTail (const QCPLineEnding &tail)
Sets the line ending style of the tail.
virtual double selectTest (const QPointF &pos) const
This function is used to decide whether a click hits an item or not.
Public Attributes
QCPItemPosition *const start
QCPItemPosition *const startDir
QCPItemPosition *const endDir
QCPItemPosition *const end
Protected Member Functions
virtual void draw (QCPPainter *painter)
QPen mainPen () const
Protected Attributes
QPen mPen
QPen mSelectedPen
QCPLineEnding mHead
QCPLineEnding mTail
Additional Inherited Members
Detailed Description
A curved line from one point to another.
Curve example. Blue dotted circles are anchors, solid blue discs are positions. It has four positions, start and end, which define the end points of the line, and two control points which define the direction the line exits from the start and the direction from which it approaches the end: startDir and endDir.
With setHead and setTail you may set different line ending styles, e.g. to create an arrow.
Often it is desirable for the control points to stay at fixed relative positions to the start/end point. This can be achieved by setting the parent anchor e.g. of startDir simply to start, and then specify the desired pixel offset with QCPItemPosition::setCoords on startDir.
Definition at line 1182 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPItemCurve::QCPItemCurve (QCustomPlot *parentPlot)
Creates a curve item and sets default values. The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 13672 of file qcustomplot.cpp.
References end, endDir, QCPItemPosition::setCoords(), setPen(), setSelectedPen(), start, and startDir.
                                                  :
  QCPAbstractItem(parentPlot),
  start(createPosition("start")),
  startDir(createPosition("startDir")),
  endDir(createPosition("endDir")),
  end(createPosition("end"))
{
  start->setCoords(0, 0);
  startDir->setCoords(0.5, 0);
  endDir->setCoords(0, 0.5);
  end->setCoords(1, 1);
  
  setPen(QPen(Qt::black));
  setSelectedPen(QPen(Qt::blue,2));
}
QCPItemCurve::~QCPItemCurve () [virtual]
Definition at line 13688 of file qcustomplot.cpp.
{
}
Member Function Documentation
void QCPItemCurve::draw (QCPPainter *painter) [protected], [virtual]
Draws this item with the provided painter. Called by QCustomPlot::draw on all its visible items.
The cliprect of the provided painter is set to the rect returned by clipRect before this function is called. For items this depends on the clipping settings defined by setClipToAxisRect, setClipKeyAxis and setClipValueAxis.
Implements QCPAbstractItem.
Definition at line 13764 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), QCPLineEnding::draw(), end, endDir, QCPLineEnding::esNone, mainPen(), mHead, mTail, QCPItemPosition::pixelPoint(), QCPPainter::setPen(), start, startDir, and QCPLineEnding::style().
{
  QPointF startVec(start->pixelPoint());
  QPointF startDirVec(startDir->pixelPoint());
  QPointF endDirVec(endDir->pixelPoint());
  QPointF endVec(end->pixelPoint());
  if (QVector2D(endVec-startVec).length() > 1e10) // too large curves cause crash
    return;
  QPainterPath cubicPath(startVec);
  cubicPath.cubicTo(startDirVec, endDirVec, endVec);
  // paint visible segment, if existent:
  QRect clip = clipRect().adjusted(-mainPen().widthF(), -mainPen().widthF(), mainPen().widthF(), mainPen().widthF());
  QRect cubicRect = cubicPath.controlPointRect().toRect();
  if (cubicRect.isEmpty()) // may happen when start and end exactly on same x or y position
    cubicRect.adjust(0, 0, 1, 1);
  if (clip.intersects(cubicRect))
  {
    painter->setPen(mainPen());
    painter->drawPath(cubicPath);
    painter->setBrush(Qt::SolidPattern);
    if (mTail.style() != QCPLineEnding::esNone)
      mTail.draw(painter, QVector2D(startVec), M_PI-cubicPath.angleAtPercent(0)/180.0*M_PI);
    if (mHead.style() != QCPLineEnding::esNone)
      mHead.draw(painter, QVector2D(endVec), -cubicPath.angleAtPercent(1)/180.0*M_PI);
  }
}
QCPLineEnding QCPItemCurve::head () const [inline]
Definition at line 1192 of file qcustomplot.h.
Referenced by setHead().
{ return mHead; }
QPen QCPItemCurve::mainPen () const [protected]
Returns the pen that should be used for drawing lines. Returns mPen when the item is not selected and mSelectedPen when it is.
Definition at line 13798 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
{
  return mSelected ? mSelectedPen : mPen;
}
QPen QCPItemCurve::pen () const [inline]
Definition at line 1190 of file qcustomplot.h.
References mPen.
Referenced by setPen(), and setSelectedPen().
{ return mPen; }
QPen QCPItemCurve::selectedPen () const [inline]
Definition at line 1191 of file qcustomplot.h.
{ return mSelectedPen; }
double QCPItemCurve::selectTest (const QPointF &pos) const [virtual]
This function is used to decide whether a click hits an item or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the item. If the item is either invisible or the distance couldn't be determined, -1.0 is returned. setSelectable has no influence on the return value of this function.
If the item is represented not by single lines but by an area like QCPItemRect or QCPItemText, a click inside the area returns a constant value greater zero (typically 99% of the selectionTolerance of the parent QCustomPlot). If the click lies outside the area, this function returns -1.0.
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs.
See also:
setSelected, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 13739 of file qcustomplot.cpp.
References QCPAbstractItem::distSqrToLine(), end, endDir, QCPLayerable::mVisible, QCPItemPosition::pixelPoint(), start, and startDir.
{
  if (!mVisible)
    return -1;
  
  QPointF startVec(start->pixelPoint());
  QPointF startDirVec(startDir->pixelPoint());
  QPointF endDirVec(endDir->pixelPoint());
  QPointF endVec(end->pixelPoint());
  QPainterPath cubicPath(startVec);
  cubicPath.cubicTo(startDirVec, endDirVec, endVec);
  
  QPolygonF polygon = cubicPath.toSubpathPolygons().first();
  double minDistSqr = std::numeric_limits<double>::max();
  for (int i=1; i<polygon.size(); ++i)
  {
    double distSqr = distSqrToLine(polygon.at(i-1), polygon.at(i), pos);
    if (distSqr < minDistSqr)
      minDistSqr = distSqr;
  }
  return qSqrt(minDistSqr);
}
void QCPItemCurve::setHead (const QCPLineEnding &head)
Sets the line ending style of the head. The head corresponds to the end position.
Note that due to the overloaded QCPLineEnding constructor, you may directly specify a QCPLineEnding::EndingStyle here, e.g.
setHead(QCPLineEnding::esSpikeArrow)
See also:
setTail
Definition at line 13720 of file qcustomplot.cpp.
References head(), and mHead.
{
  mHead = head;
}
void QCPItemCurve::setPen (const QPen &pen)
Sets the pen that will be used to draw the line.
See also:
setSelectedPen
Definition at line 13697 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemCurve().
{
  mPen = pen;
}
void QCPItemCurve::setSelectedPen (const QPen &pen)
Sets the pen that will be used to draw the line when selected.
See also:
setPen, setSelected
Definition at line 13707 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemCurve().
{
  mSelectedPen = pen;
}
void QCPItemCurve::setTail (const QCPLineEnding &tail)
Sets the line ending style of the tail. The tail corresponds to the start position.
Note that due to the overloaded QCPLineEnding constructor, you may directly specify a QCPLineEnding::EndingStyle here, e.g.
setTail(QCPLineEnding::esSpikeArrow)
See also:
setHead
Definition at line 13733 of file qcustomplot.cpp.
References mTail, and tail().
{
  mTail = tail;
}
QCPLineEnding QCPItemCurve::tail () const [inline]
Definition at line 1193 of file qcustomplot.h.
Referenced by setTail().
{ return mTail; }
Member Data Documentation
QCPItemPosition* const QCPItemCurve::end
Definition at line 1207 of file qcustomplot.h.
Referenced by draw(), QCPItemCurve(), and selectTest().
QCPItemPosition* const QCPItemCurve::endDir
Definition at line 1206 of file qcustomplot.h.
Referenced by draw(), QCPItemCurve(), and selectTest().
QCPLineEnding QCPItemCurve::mHead [protected]
Definition at line 1211 of file qcustomplot.h.
Referenced by draw(), and setHead().
QPen QCPItemCurve::mPen [protected]
Definition at line 1210 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
QPen QCPItemCurve::mSelectedPen [protected]
Definition at line 1210 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
QCPLineEnding QCPItemCurve::mTail [protected]
Definition at line 1211 of file qcustomplot.h.
Referenced by draw(), and setTail().
QCPItemPosition* const QCPItemCurve::start
Definition at line 1204 of file qcustomplot.h.
Referenced by draw(), QCPItemCurve(), and selectTest().
QCPItemPosition* const QCPItemCurve::startDir
Definition at line 1205 of file qcustomplot.h.
Referenced by draw(), QCPItemCurve(), and selectTest().
Author
Generated automatically by Doxygen for AQ0X from the source code.