QCPItemStraightLine
NAME
QCPItemStraightLine -
A straight line that spans infinitely in both directions.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPAbstractItem.
Public Member Functions
QCPItemStraightLine (QCustomPlot *parentPlot)
Creates a straight line item and sets default values.
virtual ~QCPItemStraightLine ()
QPen pen () const
QPen selectedPen () const
void setPen (const QPen &pen)
Sets the pen that will be used to draw the line.
void setSelectedPen (const QPen &pen)
Sets the pen that will be used to draw the line when selected.
virtual double selectTest (const QPointF &pos) const
This function is used to decide whether a click hits an item or not.
Public Attributes
QCPItemPosition *const point1
QCPItemPosition *const point2
Protected Member Functions
virtual void draw (QCPPainter *painter)
double distToStraightLine (const QVector2D &point1, const QVector2D &vec, const QVector2D &point) const
QLineF getRectClippedStraightLine (const QVector2D &point1, const QVector2D &vec, const QRect &rect) const
QPen mainPen () const
Protected Attributes
QPen mPen
QPen mSelectedPen
Additional Inherited Members
Detailed Description
A straight line that spans infinitely in both directions.
Straight line example. Blue dotted circles are anchors, solid blue discs are positions. It has two positions, point1 and point2, which define the straight line.
Definition at line 902 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPItemStraightLine::QCPItemStraightLine (QCustomPlot *parentPlot)
Creates a straight line item and sets default values. The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 11791 of file qcustomplot.cpp.
References point1, point2, QCPItemPosition::setCoords(), setPen(), and setSelectedPen().
                                                                :
  QCPAbstractItem(parentPlot),
  point1(createPosition("point1")),
  point2(createPosition("point2"))
{
  point1->setCoords(0, 0);
  point2->setCoords(1, 1);
  
  setPen(QPen(Qt::black));
  setSelectedPen(QPen(Qt::blue,2));
}
QCPItemStraightLine::~QCPItemStraightLine () [virtual]
Definition at line 11803 of file qcustomplot.cpp.
{
}
Member Function Documentation
double QCPItemStraightLine::distToStraightLine (const QVector2D &base, const QVector2D &vec, const QVector2D &point) const [protected]
finds the shortest distance of point to the straight line defined by the base point base and the direction vector vec.
This is a helper function for selectTest.
Definition at line 11859 of file qcustomplot.cpp.
Referenced by selectTest().
{
  return qAbs((base.y()-point.y())*vec.x()-(base.x()-point.x())*vec.y())/vec.length();
}
void QCPItemStraightLine::draw (QCPPainter *painter) [protected], [virtual]
Draws this item with the provided painter. Called by QCustomPlot::draw on all its visible items.
The cliprect of the provided painter is set to the rect returned by clipRect before this function is called. For items this depends on the clipping settings defined by setClipToAxisRect, setClipKeyAxis and setClipValueAxis.
Implements QCPAbstractItem.
Definition at line 11837 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), QCPPainter::drawLine(), getRectClippedStraightLine(), mainPen(), QCPItemPosition::pixelPoint(), point1, point2, and QCPPainter::setPen().
{
  QVector2D start(point1->pixelPoint());
  QVector2D end(point2->pixelPoint());
  // get visible segment of straight line inside clipRect:
  double clipPad = mainPen().widthF();
  QLineF line = getRectClippedStraightLine(start, end-start, clipRect().adjusted(-clipPad, -clipPad, clipPad, clipPad));
  // paint visible segment, if existent:
  if (!line.isNull())
  {
    painter->setPen(mainPen());
    painter->drawLine(line);
  }
}
QLineF QCPItemStraightLine::getRectClippedStraightLine (const QVector2D &base, const QVector2D &vec, const QRect &rect) const [protected]
Returns the section of the straight line defined by base and direction vector vec, that is visible in the specified rect.
This is a helper function for draw.
Definition at line 11871 of file qcustomplot.cpp.
Referenced by draw().
{
  double bx, by;
  double gamma;
  QLineF result;
  if (vec.x() == 0 && vec.y() == 0)
    return result;
  if (qFuzzyIsNull(vec.x())) // line is vertical
  {
    // check top of rect:
    bx = rect.left();
    by = rect.top();
    gamma = base.x()-bx + (by-base.y())*vec.x()/vec.y();
    if (gamma >= 0 && gamma <= rect.width())
      result.setLine(bx+gamma, rect.top(), bx+gamma, rect.bottom()); // no need to check bottom because we know line is vertical
  } else if (qFuzzyIsNull(vec.y())) // line is horizontal
  {
    // check left of rect:
    bx = rect.left();
    by = rect.top();
    gamma = base.y()-by + (bx-base.x())*vec.y()/vec.x();
    if (gamma >= 0 && gamma <= rect.height())
      result.setLine(rect.left(), by+gamma, rect.right(), by+gamma); // no need to check right because we know line is horizontal
  } else // line is skewed
  {
    QList<QVector2D> pointVectors;
    // check top of rect:
    bx = rect.left();
    by = rect.top();
    gamma = base.x()-bx + (by-base.y())*vec.x()/vec.y();
    if (gamma >= 0 && gamma <= rect.width())
      pointVectors.append(QVector2D(bx+gamma, by));
    // check bottom of rect:
    bx = rect.left();
    by = rect.bottom();
    gamma = base.x()-bx + (by-base.y())*vec.x()/vec.y();
    if (gamma >= 0 && gamma <= rect.width())
      pointVectors.append(QVector2D(bx+gamma, by));
    // check left of rect:
    bx = rect.left();
    by = rect.top();
    gamma = base.y()-by + (bx-base.x())*vec.y()/vec.x();
    if (gamma >= 0 && gamma <= rect.height())
      pointVectors.append(QVector2D(bx, by+gamma));
    // check right of rect:
    bx = rect.right();
    by = rect.top();
    gamma = base.y()-by + (bx-base.x())*vec.y()/vec.x();
    if (gamma >= 0 && gamma <= rect.height())
      pointVectors.append(QVector2D(bx, by+gamma));
    
    // evaluate points:
    if (pointVectors.size() == 2)
    {
      result.setPoints(pointVectors.at(0).toPointF(), pointVectors.at(1).toPointF());
    } else if (pointVectors.size() > 2)
    {
      // line probably goes through corner of rect, and we got two points there. single out the point pair with greatest distance:
      double distSqrMax = 0;
      QVector2D pv1, pv2;
      for (int i=0; i<pointVectors.size()-1; ++i)
      {
        for (int k=i+1; k<pointVectors.size(); ++k)
        {
          double distSqr = (pointVectors.at(i)-pointVectors.at(k)).lengthSquared();
          if (distSqr > distSqrMax)
          {
            pv1 = pointVectors.at(i);
            pv2 = pointVectors.at(k);
            distSqrMax = distSqr;
          }
        }
      }
      result.setPoints(pv1.toPointF(), pv2.toPointF());
    }
  }
  return result;
}
QPen QCPItemStraightLine::mainPen () const [protected]
Returns the pen that should be used for drawing lines. Returns mPen when the item is not selected and mSelectedPen when it is.
Definition at line 11955 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
{
  return mSelected ? mSelectedPen : mPen;
}
QPen QCPItemStraightLine::pen () const [inline]
Definition at line 910 of file qcustomplot.h.
References mPen.
Referenced by setPen(), and setSelectedPen().
{ return mPen; }
QPen QCPItemStraightLine::selectedPen () const [inline]
Definition at line 911 of file qcustomplot.h.
{ return mSelectedPen; }
double QCPItemStraightLine::selectTest (const QPointF &pos) const [virtual]
This function is used to decide whether a click hits an item or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the item. If the item is either invisible or the distance couldn't be determined, -1.0 is returned. setSelectable has no influence on the return value of this function.
If the item is represented not by single lines but by an area like QCPItemRect or QCPItemText, a click inside the area returns a constant value greater zero (typically 99% of the selectionTolerance of the parent QCustomPlot). If the click lies outside the area, this function returns -1.0.
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs.
See also:
setSelected, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 11828 of file qcustomplot.cpp.
References distToStraightLine(), QCPLayerable::mVisible, QCPItemPosition::pixelPoint(), point1, and point2.
{
  if (!mVisible)
    return -1;
  
  return distToStraightLine(QVector2D(point1->pixelPoint()), QVector2D(point2->pixelPoint()-point1->pixelPoint()), QVector2D(pos));
}
void QCPItemStraightLine::setPen (const QPen &pen)
Sets the pen that will be used to draw the line.
See also:
setSelectedPen
Definition at line 11812 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemStraightLine().
{
  mPen = pen;
}
void QCPItemStraightLine::setSelectedPen (const QPen &pen)
Sets the pen that will be used to draw the line when selected.
See also:
setPen, setSelected
Definition at line 11822 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemStraightLine().
{
  mSelectedPen = pen;
}
Member Data Documentation
QPen QCPItemStraightLine::mPen [protected]
Definition at line 924 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
QPen QCPItemStraightLine::mSelectedPen [protected]
Definition at line 924 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
QCPItemPosition* const QCPItemStraightLine::point1
Definition at line 920 of file qcustomplot.h.
Referenced by draw(), QCPItemStraightLine(), and selectTest().
QCPItemPosition* const QCPItemStraightLine::point2
Definition at line 921 of file qcustomplot.h.
Referenced by draw(), QCPItemStraightLine(), and selectTest().
Author
Generated automatically by Doxygen for AQ0X from the source code.