QCPLayerable
NAME
QCPLayerable -
Base class for all objects that can be placed on layers.
SYNOPSIS
#include <qcustomplot.h>
Inherits QObject.
Inherited by QCPAbstractItem, QCPAbstractPlottable, QCPAxis, and QCPLegend.
Public Member Functions
QCPLayerable (QCustomPlot *parentPlot)
Creates a new QCPLayerable instance.
~QCPLayerable ()
bool visible () const
QCustomPlot * parentPlot () const
QCPLayer * layer () const
bool antialiased () const
void setVisible (bool on)
Sets the visibility of this layerable object.
bool setLayer (QCPLayer *layer)
Sets the layer of this layerable object.
bool setLayer (const QString &layerName)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets the layer of this layerable object by name.
void setAntialiased (bool enabled)
Sets whether this object will be drawn antialiased or not.
Protected Member Functions
bool moveToLayer (QCPLayer *layer, bool prepend)
void applyAntialiasingHint (QCPPainter *painter, bool localAntialiased, QCP::AntialiasedElement overrideElement) const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const =0
virtual QRect clipRect () const
virtual void draw (QCPPainter *painter)=0
Protected Attributes
bool mVisible
QCustomPlot * mParentPlot
QCPLayer * mLayer
bool mAntialiased
Detailed Description
Base class for all objects that can be placed on layers.
This is the abstract base class most visible objects derive from, e.g. plottables, axes, grid etc.
Every layerable is on a layer (QCPLayer) which allows controlling the rendering order by stacking the layers accordingly.
For details about the layering mechanism, see the QCPLayer documentation.
Definition at line 320 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPLayerable::QCPLayerable (QCustomPlot *parentPlot)
Creates a new QCPLayerable instance. Since QCPLayerable is an abstract base class, it can't be instantiated directly. Use one of the derived classes.
Definition at line 13992 of file qcustomplot.cpp.
References mParentPlot, and setLayer().
                                                  :
  QObject(0), // rather not bind to parentPlot, incase we want to allow moving of objects between customplots some day
  mVisible(true),
  mParentPlot(parentPlot),
  mLayer(0),
  mAntialiased(true)
{
  if (mParentPlot)
    setLayer(mParentPlot->currentLayer());
}
QCPLayerable::~QCPLayerable ()
Definition at line 14003 of file qcustomplot.cpp.
References mLayer, and QCPLayer::removeChild().
{
  if (mLayer)
  {
    mLayer->removeChild(this);
    mLayer = 0;
  }
}
Member Function Documentation
bool QCPLayerable::antialiased () const [inline]
Definition at line 331 of file qcustomplot.h.
{ return mAntialiased; }
void QCPLayerable::applyAntialiasingHint (QCPPainter *painter, boollocalAntialiased, QCP::AntialiasedElementoverrideElement) const [protected]
Sets the QPainter::Antialiasing render hint on the provided painter, depending on the localAntialiased value as well as the overrides QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements. Which override enum this function takes into account is controlled via overrideElement.
Definition at line 14101 of file qcustomplot.cpp.
References mParentPlot, and QCPPainter::setAntialiasing().
Referenced by QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractItem::applyDefaultAntialiasingHint(), QCPLegend::applyDefaultAntialiasingHint(), QCPAxis::applyDefaultAntialiasingHint(), QCPAbstractPlottable::applyErrorBarsAntialiasingHint(), QCPAbstractPlottable::applyFillAntialiasingHint(), and QCPAbstractPlottable::applyScattersAntialiasingHint().
{
  if (mParentPlot && mParentPlot->notAntialiasedElements().testFlag(overrideElement))
    painter->setAntialiasing(false);
  else if (mParentPlot && mParentPlot->antialiasedElements().testFlag(overrideElement))
    painter->setAntialiasing(true);
  else
    painter->setAntialiasing(localAntialiased);
}
void QCPLayerable::applyDefaultAntialiasingHint (QCPPainter *painter) const [protected], [pure virtual]
This function applies the default antialiasing setting to the specified painter, using the function applyAntialiasingHint. This is the antialiasing state the painter is in, when draw is called on the layerable. If the layerable has multiple entities whose antialiasing setting may be specified individually, this function should set the antialiasing state of the most prominent entity. In this case however, the draw function usually calls the specialized versions of this function before drawing each entity, effectively overriding the setting of the default antialiasing hint.
First example: QCPGraph has multiple entities that have an antialiasing setting: The graph line, fills, scatters and error bars. Those can be configured via QCPGraph::setAntialiased, QCPGraph::setAntialiasedFill, QCPGraph::setAntialiasedScatters etc. Consequently, there isn't only the QCPGraph::applyDefaultAntialiasingHint function (which corresponds to the graph line's antialiasing), but specialized ones like QCPGraph::applyFillAntialiasingHint and QCPGraph::applyScattersAntialiasingHint. So before drawing one of those entities, QCPGraph::draw calls the respective specialized applyAntialiasingHint function.
Second example: QCPItemLine consists only of a line so there is only one antialiasing setting which can be controlled with QCPItemLine::setAntialiased. (This function is inherited by all layerables. The specialized functions, as seen on QCPGraph, must be added explicitly to the respective layerable subclass.) Consequently it only has the normal QCPItemLine::applyDefaultAntialiasingHint. The QCPItemLine::draw function doesn't need to care about setting any antialiasing states, because the default antialiasing hint is already set on the painter when the draw function is called, and that's the state it wants to draw the line with.
Implemented in QCPAxis, QCPLegend, QCPAbstractItem, and QCPAbstractPlottable.
QRect QCPLayerable::clipRect () const [protected], [virtual]
Returns the clipping rectangle of this layerable object. By default, this is the viewport of the parent QCustomPlot. Specific subclasses may reimplement this function to provide different clipping rects.
The returned clipping rect is set on the painter before the draw function of the respective object is called.
Reimplemented in QCPAbstractItem, and QCPAbstractPlottable.
Definition at line 14119 of file qcustomplot.cpp.
References mParentPlot.
{
  if (mParentPlot)
    return mParentPlot->viewport();
  else
    return QRect();
}
void QCPLayerable::draw (QCPPainter *painter) [protected], [pure virtual]
This function draws the layerable to the specified painter.
Before this function is called, the painter's antialiasing state is set via applyDefaultAntialiasingHint, see the documentation there. Further, its clipping rectangle was set to clipRect.
Implemented in QCPAxis, QCPLegend, QCPItemTracer, QCPItemBracket, QCPItemCurve, QCPItemText, QCPItemPixmap, QCPItemRect, QCPItemEllipse, QCPItemLine, QCPItemStraightLine, QCPAbstractItem, QCPStatisticalBox, QCPBars, QCPCurve, QCPGraph, and QCPAbstractPlottable.
QCPLayer* QCPLayerable::layer () const [inline]
Definition at line 330 of file qcustomplot.h.
Referenced by addPlottable(), and moveToLayer().
{ return mLayer; }
bool QCPLayerable::moveToLayer (QCPLayer *layer, boolprepend) [protected]
Moves this layerable object to layer. If prepend is true, this object will be prepended to the new layer's list, i.e. it will be drawn below the objects already on the layer. If it is false, the object will be appended.
Returns true on success, i.e. if layer is a valid layer.
Definition at line 14073 of file qcustomplot.cpp.
References QCPLayer::addChild(), layer(), mLayer, mParentPlot, QCPLayer::name(), QCPLayer::parentPlot(), and QCPLayer::removeChild().
Referenced by setLayer().
{
  if (!mParentPlot)
  {
    qDebug() << Q_FUNC_INFO << "no parent QCustomPlot set";
    return false;
  }
  if (layer && layer->parentPlot() != mParentPlot)
  {
    qDebug() << Q_FUNC_INFO << "layer" << layer->name() << "is not in same QCustomPlot as this layerable";
    return false;
  }
  
  if (mLayer)
    mLayer->removeChild(this);
  mLayer = layer;
  if (mLayer)
    mLayer->addChild(this, prepend);
  return true;
}
QCustomPlot* QCPLayerable::parentPlot () const [inline]
Definition at line 329 of file qcustomplot.h.
Referenced by addGraph(), addPlottable(), QCPAbstractPlottable::QCPAbstractPlottable(), and QCPItemTracer::setGraph().
{ return mParentPlot; }
void QCPLayerable::setAntialiased (boolenabled)
Sets whether this object will be drawn antialiased or not. Note that antialiasing settings may be overridden by QCustomPlot::setAntialiasedElements and QCustomPlot::setNotAntialiasedElements.
Definition at line 14060 of file qcustomplot.cpp.
References mAntialiased.
Referenced by QCPAxis::QCPAxis(), and QCPLegend::QCPLegend().
{
  mAntialiased = enabled;
}
bool QCPLayerable::setLayer (QCPLayer *layer)
Sets the layer of this layerable object. The object will be placed on top of the other objects already on layer.
Returns true on success, i.e. if layer is a valid layer.
Definition at line 14027 of file qcustomplot.cpp.
References moveToLayer().
Referenced by addPlottable(), QCPLayerable(), and setLayer().
{
  return moveToLayer(layer, false);
}
bool QCPLayerable::setLayer (const QString &layerName)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets the layer of this layerable object by name. Returns true on success, i.e. if layerName is a valid layer name.
Definition at line 14037 of file qcustomplot.cpp.
References mParentPlot, and setLayer().
{
  if (!mParentPlot)
  {
    qDebug() << Q_FUNC_INFO << "no parent QCustomPlot set";
    return false;
  }
  if (QCPLayer *layer = mParentPlot->layer(layerName))
  {
    return setLayer(layer);
  } else
  {
    qDebug() << Q_FUNC_INFO << "there is no layer with name" << layerName;
    return false;
  }
}
void QCPLayerable::setVisible (boolon)
Sets the visibility of this layerable object. If an object is not visible, it will not be drawn on the QCustomPlot surface, and user interaction with it (e.g. click/selection) is not possible.
Definition at line 14016 of file qcustomplot.cpp.
References mVisible.
Referenced by QCPItemEllipse::draw(), and setupFullAxesBox().
{
  mVisible = on;
}
bool QCPLayerable::visible () const [inline]
Definition at line 328 of file qcustomplot.h.
{ return mVisible; }
Member Data Documentation
bool QCPLayerable::mAntialiased [protected]
Definition at line 343 of file qcustomplot.h.
Referenced by QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractItem::applyDefaultAntialiasingHint(), QCPLegend::applyDefaultAntialiasingHint(), QCPAxis::applyDefaultAntialiasingHint(), and setAntialiased().
QCPLayer* QCPLayerable::mLayer [protected]
Definition at line 342 of file qcustomplot.h.
Referenced by moveToLayer(), and ~QCPLayerable().
QCustomPlot* QCPLayerable::mParentPlot [protected]
Definition at line 341 of file qcustomplot.h.
Referenced by QCPAbstractPlottable::addToLegend(), applyAntialiasingHint(), QCPAbstractLegendItem::applyAntialiasingHint(), QCPLegend::calculateAutoPosition(), clipRect(), QCPAbstractItem::clipRect(), QCPAbstractItem::createAnchor(), QCPAbstractItem::createPosition(), QCPCurve::draw(), QCPAxis::draw(), QCPGraph::drawLinePlot(), QCPAxis::drawTickLabel(), moveToLayer(), QCPLayerable(), QCPAbstractItem::rectSelectTest(), QCPAbstractPlottable::removeFromLegend(), QCPBars::selectTest(), QCPStatisticalBox::selectTest(), QCPItemEllipse::selectTest(), QCPItemTracer::selectTest(), QCPGraph::setChannelFillGraph(), QCPItemTracer::setGraph(), setLayer(), QCPAxis::setupTickVectors(), QCPItemTracer::updatePosition(), and QCPGraph::~QCPGraph().
bool QCPLayerable::mVisible [protected]
Definition at line 340 of file qcustomplot.h.
Referenced by QCPAxis::calculateMargin(), QCPGraph::selectTest(), QCPCurve::selectTest(), QCPItemStraightLine::selectTest(), QCPItemLine::selectTest(), QCPItemRect::selectTest(), QCPItemPixmap::selectTest(), QCPItemText::selectTest(), QCPItemCurve::selectTest(), QCPItemBracket::selectTest(), QCPItemTracer::selectTest(), QCPAxis::selectTest(), and setVisible().
Author
Generated automatically by Doxygen for AQ0X from the source code.