QCPLegend
NAME
QCPLegend -
Manages a legend inside a QCustomPlot.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPLayerable.
Public Types
enum PositionStyle { psManual, psTopLeft, psTop, psTopRight, psRight, psBottomRight, psBottom, psBottomLeft, psLeft }
Defines where the legend is positioned inside the QCustomPlot axis rect.
Signals
void selectionChanged (QCPLegend::SelectableParts selection)
This signal is emitted when the selection state of this legend has changed.
Public Member Functions
Q_ENUMS (PositionStyle) enum SelectablePart
Defines the selectable parts of a legend.
Q_ENUMS (SelectablePart) Q_DECLARE_FLAGS(SelectableParts
SelectablePart QCPLegend (QCustomPlot *parentPlot)
Constructs a new QCPLegend instance with parentPlot as the containing plot and default values.
virtual ~QCPLegend ()
QPen borderPen () const
QBrush brush () const
QFont font () const
QColor textColor () const
PositionStyle positionStyle () const
QPoint position () const
bool autoSize () const
QSize size () const
QSize minimumSize () const
int paddingLeft () const
int paddingRight () const
int paddingTop () const
int paddingBottom () const
int marginLeft () const
int marginRight () const
int marginTop () const
int marginBottom () const
int itemSpacing () const
QSize iconSize () const
int iconTextPadding () const
QPen iconBorderPen () const
SelectableParts selectable () const
SelectableParts selected () const
QPen selectedBorderPen () const
QPen selectedIconBorderPen () const
QBrush selectedBrush () const
QFont selectedFont () const
QColor selectedTextColor () const
void setBorderPen (const QPen &pen)
Sets the pen, the border of the entire legend is drawn with.
void setBrush (const QBrush &brush)
Sets the brush of the legend background.
void setFont (const QFont &font)
Sets the default font of legend text.
void setTextColor (const QColor &color)
Sets the default color of legend text.
void setPositionStyle (PositionStyle legendPositionStyle)
Sets the position style of the legend.
void setPosition (const QPoint &pixelPosition)
Sets the exact pixel Position of the legend inside the QCustomPlot widget, if setPositionStyle is set to psManual.
void setAutoSize (bool on)
Sets whether the size of the legend should be calculated automatically to fit all the content (plus padding), or whether the size must be specified manually with setSize.
void setSize (const QSize &size)
Sets the size of the legend.
void setSize (int width, int height)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void setMinimumSize (const QSize &size)
Sets the minimum size of the legend when setAutoSize is enabled.
void setMinimumSize (int width, int height)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void setPaddingLeft (int padding)
Sets the left padding of the legend.
void setPaddingRight (int padding)
Sets the right padding of the legend.
void setPaddingTop (int padding)
Sets the top padding of the legend.
void setPaddingBottom (int padding)
Sets the bottom padding of the legend.
void setPadding (int left, int right, int top, int bottom)
Sets the padding of the legend.
void setMarginLeft (int margin)
Sets the left margin of the legend.
void setMarginRight (int margin)
Sets the right margin of the legend.
void setMarginTop (int margin)
Sets the top margin of the legend.
void setMarginBottom (int margin)
Sets the bottom margin of the legend.
void setMargin (int left, int right, int top, int bottom)
Sets the margin of the legend.
void setItemSpacing (int spacing)
Sets the vertical space between two legend items in the legend.
void setIconSize (const QSize &size)
Sets the size of legend icons.
void setIconSize (int width, int height)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void setIconTextPadding (int padding)
Sets the horizontal space in pixels between the legend icon and the text next to it.
void setIconBorderPen (const QPen &pen)
Sets the pen used to draw a border around each legend icon.
void setSelectable (const SelectableParts &selectable)
Sets whether the user can (de-)select the parts in selectable by clicking on the QCustomPlot surface.
void setSelected (const SelectableParts &selected)
Sets the selected state of the respective legend parts described by SelectablePart.
void setSelectedBorderPen (const QPen &pen)
When the legend box is selected, this pen is used to draw the border instead of the normal pen set via setBorderPen.
void setSelectedIconBorderPen (const QPen &pen)
Sets the pen legend items will use to draw their icon borders, when they are selected.
void setSelectedBrush (const QBrush &brush)
When the legend box is selected, this brush is used to draw the legend background instead of the normal brush set via setBrush.
void setSelectedFont (const QFont &font)
Sets the default font that is used by legend items when they are selected.
void setSelectedTextColor (const QColor &color)
Sets the default text color that is used by legend items when they are selected.
QCPAbstractLegendItem * item (int index) const
Returns the item with index i.
QCPPlottableLegendItem * itemWithPlottable (const QCPAbstractPlottable *plottable) const
Returns the QCPPlottableLegendItem which is associated with plottable (e.g.
int itemCount () const
Returns the number of items currently in the legend.
bool hasItem (QCPAbstractLegendItem *item) const
Returns whether the legend contains item.
bool hasItemWithPlottable (const QCPAbstractPlottable *plottable) const
Returns whether the legend contains a QCPPlottableLegendItem which is associated with plottable (e.g.
bool addItem (QCPAbstractLegendItem *item)
Adds item to the legend, if it's not present already.
bool removeItem (int index)
Removes the item with index index from the legend.
bool removeItem (QCPAbstractLegendItem *item)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes item from the legend. "
void clearItems ()
Removes all items from the legend.
QList< QCPAbstractLegendItem * > selectedItems () const
Returns the legend items that are currently selected.
void reArrange ()
If setAutoSize is true, the size needed to fit all legend contents is calculated and applied.
bool selectTestLegend (const QPointF &pos) const
Returns whether the point pos in pixels hits the legend rect.
QCPAbstractLegendItem * selectTestItem (const QPoint pos) const
When the point pos in pixels hits a legend item, the item is returned.
Protected Member Functions
virtual void updateSelectionState ()
virtual bool handleLegendSelection (QMouseEvent *event, bool additiveSelection, bool &modified)
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void draw (QCPPainter *painter)
virtual void calculateAutoSize ()
virtual void calculateAutoPosition ()
QPen getBorderPen () const
QBrush getBrush () const
Protected Attributes
QPen mBorderPen
QPen mIconBorderPen
QBrush mBrush
QFont mFont
QColor mTextColor
QPoint mPosition
QSize mSize
QSize mMinimumSize
QSize mIconSize
PositionStyle mPositionStyle
bool mAutoSize
int mPaddingLeft
int mPaddingRight
int mPaddingTop
int mPaddingBottom
int mMarginLeft
int mMarginRight
int mMarginTop
int mMarginBottom
int mItemSpacing
int mIconTextPadding
SelectableParts mSelected
SelectableParts mSelectable
QPen mSelectedBorderPen
QPen mSelectedIconBorderPen
QBrush mSelectedBrush
QFont mSelectedFont
QColor mSelectedTextColor
QList< QCPAbstractLegendItem * > mItems
QMap< QCPAbstractLegendItem
*, QRect > mItemBoundingBoxes"
Friends
class QCPAbstractLegendItem
Detailed Description
Manages a legend inside a QCustomPlot.
Doesn't need to be instantiated externally, rather access QCustomPlot::legend
Definition at line 1421 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPLegend::PositionStyle
Defines where the legend is positioned inside the QCustomPlot axis rect.
Enumerator
psManual
Position is not changed automatically. Set manually via setPosition.
psTopLeft
Legend is positioned in the top left corner of the axis rect with distance to the border corresponding to the currently set top and left margins.
psTop
Legend is horizontally centered at the top of the axis rect with distance to the border corresponding to the currently set top margin.
psTopRight
Legend is positioned in the top right corner of the axis rect with distance to the border corresponding to the currently set top and right margins.
psRight
Legend is vertically centered at the right of the axis rect with distance to the border corresponding to the currently set right margin.
psBottomRight
Legend is positioned in the bottom right corner of the axis rect with distance to the border corresponding to the currently set bottom and right margins.
psBottom
Legend is horizontally centered at the bottom of the axis rect with distance to the border corresponding to the currently set bottom margin.
psBottomLeft
Legend is positioned in the bottom left corner of the axis rect with distance to the border corresponding to the currently set bottom and left margins.
psLeft
Legend is vertically centered at the left of the axis rect with distance to the border corresponding to the currently set left margin.
Definition at line 1428 of file qcustomplot.h.
                     { psManual
                      ,psTopLeft
                      ,psTop
                      ,psTopRight
                      ,psRight
                      ,psBottomRight
                      ,psBottom
                      ,psBottomLeft
                      ,psLeft
                     };
Constructor & Destructor Documentation
QCPLegend::QCPLegend (QCustomPlot *parentPlot) [explicit]
Constructs a new QCPLegend instance with parentPlot as the containing plot and default values. Under normal usage, QCPLegend needn't be instantiated outside of QCustomPlot. Access QCustomPlot::legend to modify the legend (set to invisible by default, see setVisible).
Definition at line 2589 of file qcustomplot.cpp.
References psTopRight, QCPLayerable::setAntialiased(), setAutoSize(), setBorderPen(), setBrush(), setFont(), setIconBorderPen(), setIconSize(), setIconTextPadding(), setItemSpacing(), setMargin(), setMinimumSize(), setPadding(), setPositionStyle(), setSelectable(), setSelected(), setSelectedBorderPen(), setSelectedBrush(), setSelectedFont(), setSelectedIconBorderPen(), setSelectedTextColor(), setSize(), and setTextColor().
                                            :
  QCPLayerable(parentPlot)
{
  setAntialiased(false);
  setPositionStyle(psTopRight);
  setSize(100, 28);
  setMinimumSize(100, 0);
  setIconSize(32, 18);
  setAutoSize(true);
  
  setMargin(12, 12, 12, 12);
  setPadding(8, 8, 3, 3);
  setItemSpacing(3);
  setIconTextPadding(7);
  
  setSelectable(spLegendBox | spItems);
  setSelected(spNone);
  
  setBorderPen(QPen(Qt::black));
  setSelectedBorderPen(QPen(Qt::blue, 2));
  setIconBorderPen(Qt::NoPen);
  setSelectedIconBorderPen(QPen(Qt::blue, 2));
  setBrush(Qt::white);
  setSelectedBrush(Qt::white);
  setFont(parentPlot->font());
  setSelectedFont(parentPlot->font());
  setTextColor(Qt::black);
  setSelectedTextColor(Qt::blue);
}
QCPLegend::~QCPLegend () [virtual]
Definition at line 2619 of file qcustomplot.cpp.
References clearItems().
{
  clearItems();
}
Member Function Documentation
bool QCPLegend::addItem (QCPAbstractLegendItem *item)
Adds item to the legend, if it's not present already. Returns true on sucess, i.e. if the item wasn't in the list already and has been successfuly added.
The legend takes ownership of the item.
Definition at line 3083 of file qcustomplot.cpp.
References mItems.
{
  if (!mItems.contains(item))
  {
    mItems.append(item);
    return true;
  } else
    return false;
}
void QCPLegend::applyDefaultAntialiasingHint (QCPPainter *painter) const [protected], [virtual]
A convenience function to easily set the QPainter::Antialiased hint on the provided painter before drawing main legend elements.
This is the antialiasing state the painter passed to the draw method is in by default.
This function takes into account the local setting of the antialiasing flag as well as the overrides set e.g. with QCustomPlot::setNotAntialiasedElements.
See also:
setAntialiased
Implements QCPLayerable.
Definition at line 3341 of file qcustomplot.cpp.
References QCP::aeLegend, QCPLayerable::applyAntialiasingHint(), and QCPLayerable::mAntialiased.
{
  applyAntialiasingHint(painter, mAntialiased, QCP::aeLegend);
}
bool QCPLegend::autoSize () const [inline]
Definition at line 1460 of file qcustomplot.h.
{ return mAutoSize; }
QPen QCPLegend::borderPen () const [inline]
Definition at line 1454 of file qcustomplot.h.
{ return mBorderPen; }
QBrush QCPLegend::brush () const [inline]
Definition at line 1455 of file qcustomplot.h.
Referenced by setBrush(), and setSelectedBrush().
{ return mBrush; }
void QCPLegend::calculateAutoPosition () [protected], [virtual]
Sets the position dependant on the setPositionStyle setting and the margins.
Definition at line 3440 of file qcustomplot.cpp.
References mMarginBottom, mMarginLeft, mMarginRight, mMarginTop, QCPLayerable::mParentPlot, mPosition, mPositionStyle, mSize, psBottom, psBottomLeft, psBottomRight, psLeft, psManual, psRight, psTop, psTopLeft, and psTopRight.
Referenced by reArrange().
{
  switch (mPositionStyle)
  {
    case psTopLeft:
      mPosition = mParentPlot->mAxisRect.topLeft() + QPoint(mMarginLeft, mMarginTop); break;
    case psTop:
      mPosition = mParentPlot->mAxisRect.topLeft() + QPoint(mParentPlot->mAxisRect.width()/2.0-mSize.width()/2.0, mMarginTop); break;
    case psTopRight:
      mPosition = mParentPlot->mAxisRect.topRight() + QPoint(-mMarginRight-mSize.width(), mMarginTop); break;
    case psRight:
      mPosition = mParentPlot->mAxisRect.topRight() + QPoint(-mMarginRight-mSize.width(), mParentPlot->mAxisRect.height()/2.0-mSize.height()/2.0); break;
    case psBottomRight:
      mPosition = mParentPlot->mAxisRect.bottomRight() + QPoint(-mMarginRight-mSize.width(), -mMarginBottom-mSize.height()); break;
    case psBottom:
      mPosition = mParentPlot->mAxisRect.bottomLeft() + QPoint(mParentPlot->mAxisRect.width()/2.0-mSize.width()/2.0, -mMarginBottom-mSize.height()); break;
    case psBottomLeft:
      mPosition = mParentPlot->mAxisRect.bottomLeft() + QPoint(mMarginLeft, -mMarginBottom-mSize.height()); break;
    case psLeft:
      mPosition = mParentPlot->mAxisRect.topLeft() + QPoint(mMarginLeft, mParentPlot->mAxisRect.height()/2.0-mSize.height()/2.0); break;
    case psManual: break;
  }
}
void QCPLegend::calculateAutoSize () [protected], [virtual]
Goes through similar steps as draw and calculates the width and height needed to fit all items and padding in the legend. The new calculated size is then applied to the mSize of this legend.
Definition at line 3400 of file qcustomplot.cpp.
References mItems, mItemSpacing, mMinimumSize, mPaddingBottom, mPaddingLeft, mPaddingRight, mPaddingTop, and mSize.
Referenced by reArrange().
{
  int width = mMinimumSize.width()-mPaddingLeft-mPaddingRight; // start with minimum width and only expand from there
  int currentTop;
  bool repeat = true;
  int repeatCount = 0;
  while (repeat && repeatCount < 3) // repeat until we find self-consistent width (usually 2 runs)
  {
    repeat = false;
    currentTop = mPaddingTop;
    for (int i=0; i<mItems.size(); ++i)
    {
      QSize s = mItems.at(i)->size(QSize(width, 0));
      currentTop += s.height();
      if (i < mItems.size()-1) // vertical spacer for all but last item
        currentTop += mItemSpacing;
      if (width < s.width())
      {
        width = s.width();
        repeat = true; // changed width, so need a new run with new width to let other items adapt their height to that new width
      }
    }
    repeatCount++;
  }
  if (repeat)
    qDebug() << Q_FUNC_INFO << "hit repeat limit for iterative width calculation";
  currentTop += mPaddingBottom;
  width += mPaddingLeft+mPaddingRight;
  
  mSize.setWidth(width);
  if (currentTop > mMinimumSize.height())
    mSize.setHeight(currentTop);
  else
    mSize.setHeight(mMinimumSize.height());
}
void QCPLegend::clearItems ()
Removes all items from the legend.
Definition at line 3128 of file qcustomplot.cpp.
References mItemBoundingBoxes, and mItems.
Referenced by ~QCPLegend().
{
  qDeleteAll(mItems);
  mItems.clear();
  mItemBoundingBoxes.clear();
}
void QCPLegend::draw (QCPPainter *painter) [protected], [virtual]
Draws the legend with the provided painter.
Implements QCPLayerable.
Definition at line 3370 of file qcustomplot.cpp.
References getBorderPen(), getBrush(), mItemBoundingBoxes, mItems, mItemSpacing, mPaddingLeft, mPaddingTop, mPosition, mSize, QCPPainter::restore(), QCPPainter::save(), and QCPPainter::setPen().
{
  painter->setBrush(getBrush());
  painter->setPen(getBorderPen());
  // draw background rect:
  painter->drawRect(QRect(mPosition, mSize));
  // draw legend items:
  painter->setClipRect(QRect(mPosition, mSize).adjusted(1, 1, 0, 0));
  painter->setPen(QPen());
  painter->setBrush(Qt::NoBrush);
  int currentTop = mPosition.y()+mPaddingTop;
  for (int i=0; i<mItems.size(); ++i)
  {
    QSize itemSize = mItems.at(i)->size(QSize(mSize.width(), 0));
    QRect itemRect = QRect(QPoint(mPosition.x()+mPaddingLeft, currentTop), itemSize);
    mItemBoundingBoxes.insert(mItems.at(i), itemRect);
    painter->save();
    mItems.at(i)->applyAntialiasingHint(painter);
    mItems.at(i)->draw(painter, itemRect);
    painter->restore();
    currentTop += itemSize.height()+mItemSpacing;
  }
}
QFont QCPLegend::font () const [inline]
Definition at line 1456 of file qcustomplot.h.
Referenced by setFont(), and setSelectedFont().
{ return mFont; }
QPen QCPLegend::getBorderPen () const [protected]
Returns the pen used to paint the border of the legend, taking into account the selection state of the legend box.
Definition at line 3351 of file qcustomplot.cpp.
References mBorderPen, mSelected, and mSelectedBorderPen.
Referenced by draw().
{
  return mSelected.testFlag(spLegendBox) ? mSelectedBorderPen : mBorderPen;
}
QBrush QCPLegend::getBrush () const [protected]
Returns the brush used to paint the background of the legend, taking into account the selection state of the legend box.
Definition at line 3361 of file qcustomplot.cpp.
References mBrush, mSelected, and mSelectedBrush.
Referenced by draw().
{
  return mSelected.testFlag(spLegendBox) ? mSelectedBrush : mBrush;
}
bool QCPLegend::handleLegendSelection (QMouseEvent *event, booladditiveSelection, bool &modified) [protected], [virtual]
Handles the selection event and returns true when the selection event hit any parts of the legend. If the selection state of any parts of the legend was changed, the output parameter modified is set to true.
When additiveSelecton is true, any new selections become selected in addition to the recent selections. The recent selections are not cleared. Further, clicking on one object multiple times in additive selection mode, toggles the selection of that object on and off.
To indicate that an event deselects the legend (i.e. the parts that are deselectable by the user, see setSelectable), pass 0 as event.
Definition at line 3244 of file qcustomplot.cpp.
References item(), itemCount(), QCPAbstractLegendItem::selectable(), selectable(), QCPAbstractLegendItem::selected(), selected(), selectTestItem(), selectTestLegend(), QCPAbstractLegendItem::setSelected(), and setSelected().
Referenced by mouseReleaseEvent().
{
  modified = false;
  bool selectionFound = false;
  
  if (event && selectTestLegend(event->pos())) // clicked inside legend somewhere
  {
    QCPAbstractLegendItem *ali = selectTestItem(event->pos());
    if (selectable().testFlag(QCPLegend::spItems) && ali && ali->selectable()) // items shall be selectable and item ali was clicked
    {
      selectionFound = true;
      // deselect legend box:
      if (!additiveSelection && selected().testFlag(QCPLegend::spLegendBox) && selectable().testFlag(QCPLegend::spLegendBox))
        setSelected(selected() & ~QCPLegend::spLegendBox);
      // first select clicked item:
      if (!ali->selected() || additiveSelection) // if additive selection, we toggle selection on and off per click
      {
        modified = true;
        ali->setSelected(!ali->selected());
      }
      // finally, deselect all other items (if we had deselected all first, the selectionChanged signal of QCPLegend might have been emitted twice):
      if (!additiveSelection)
      {
        for (int i=0; i<itemCount(); ++i)
        {
          if (item(i) != ali && item(i)->selected() && item(i)->selectable())
          {
            modified = true;
            item(i)->setSelected(false);
          }
        }
      }
    } else // no specific item clicked or items not selectable
    {
      // if items actually were selectable, this means none were clicked, deselect them:
      if (selectable().testFlag(QCPLegend::spItems) && selected().testFlag(QCPLegend::spItems) && !additiveSelection)
      {
        for (int i=0; i<itemCount(); ++i)
        {
          if (item(i)->selectable())
            item(i)->setSelected(false);
        }
        modified = true;
      }
      // if legend box is selectable, select it:
      if (selectable().testFlag(QCPLegend::spLegendBox))
      {
        if (!selected().testFlag(QCPLegend::spLegendBox) || additiveSelection)
        {
          selectionFound = true;
          setSelected(selected() ^ QCPLegend::spLegendBox); // xor because we always toggle
          modified = true;
        }
      }
    }
  } else if (selected() != QCPLegend::spNone && selectable() != QCPLegend::spNone && !additiveSelection) // legend not clicked, deselect it if selectable allows that (and all child items)
  {
    // only deselect parts that are allowed to be changed by user according to selectable()
    // deselect child items (and automatically removes spItems from selected state of legend, if last item gets deselected):
    if (selectable().testFlag(spItems))
    {
      for (int i=0; i<itemCount(); ++i)
      {
        if (item(i)->selected() && item(i)->selectable())
        {
          item(i)->setSelected(false);
          modified = true;
        }
      }
    }
    // only deselect parts that are allowed to be changed (are selectable). Don't forcibly remove
    // spItems, because some selected items might not be selectable, i.e. allowed to be deselected
    // by user interaction. If that's not the case, spItems will have been removed from selected()
    // state in previous loop by individual setSelected(false) calls on the items anyway.
    QCPLegend::SelectableParts newState = selected() & ~(selectable()&~spItems);
    if (newState != selected())
    {
      setSelected(newState);
      modified = true;
    }
  }
  
  return selectionFound;
}
bool QCPLegend::hasItem (QCPAbstractLegendItem *item) const
Returns whether the legend contains item.
Definition at line 3060 of file qcustomplot.cpp.
References mItems.
{
  return mItems.contains(item);
}
bool QCPLegend::hasItemWithPlottable (const QCPAbstractPlottable *plottable) const
Returns whether the legend contains a QCPPlottableLegendItem which is associated with plottable (e.g. a QCPGraph*). If such an item isn't in the legend, returns false.
See also:
itemWithPlottable
Definition at line 3071 of file qcustomplot.cpp.
References itemWithPlottable().
{
  return itemWithPlottable(plottable);
}
QPen QCPLegend::iconBorderPen () const [inline]
Definition at line 1474 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getIconBorderPen().
{ return mIconBorderPen; }
QSize QCPLegend::iconSize () const [inline]
Definition at line 1472 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::draw(), and QCPPlottableLegendItem::size().
{ return mIconSize; }
int QCPLegend::iconTextPadding () const [inline]
Definition at line 1473 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::draw(), and QCPPlottableLegendItem::size().
{ return mIconTextPadding; }
QCPAbstractLegendItem * QCPLegend::item (intindex) const
Returns the item with index i.
See also:
itemCount
Definition at line 3021 of file qcustomplot.cpp.
References mItems.
Referenced by handleLegendSelection().
{
  if (index >= 0 && index < mItems.size())
    return mItems[index];
  else
    return 0;
}
int QCPLegend::itemCount () const
Returns the number of items currently in the legend.
See also:
item
Definition at line 3052 of file qcustomplot.cpp.
References mItems.
Referenced by handleLegendSelection().
{
  return mItems.size();
}
int QCPLegend::itemSpacing () const [inline]
Definition at line 1471 of file qcustomplot.h.
{ return mItemSpacing; }
QCPPlottableLegendItem * QCPLegend::itemWithPlottable (const QCPAbstractPlottable *plottable) const
Returns the QCPPlottableLegendItem which is associated with plottable (e.g. a QCPGraph*). If such an item isn't in the legend, returns 0.
See also:
hasItemWithPlottable
Definition at line 3035 of file qcustomplot.cpp.
References mItems, and plottable().
Referenced by hasItemWithPlottable().
{
  for (int i=0; i<mItems.size(); ++i)
  {
    if (QCPPlottableLegendItem *pli = qobject_cast<QCPPlottableLegendItem*>(mItems.at(i)))
    {
      if (pli->plottable() == plottable)
        return pli;
    }
  }
  return 0;
}
int QCPLegend::marginBottom () const [inline]
Definition at line 1470 of file qcustomplot.h.
References mMarginBottom.
{ return mMarginBottom; }
int QCPLegend::marginLeft () const [inline]
Definition at line 1467 of file qcustomplot.h.
References mMarginLeft.
{ return mMarginLeft; }
int QCPLegend::marginRight () const [inline]
Definition at line 1468 of file qcustomplot.h.
References mMarginRight.
{ return mMarginRight; }
int QCPLegend::marginTop () const [inline]
Definition at line 1469 of file qcustomplot.h.
References mMarginTop.
{ return mMarginTop; }
QSize QCPLegend::minimumSize () const [inline]
Definition at line 1462 of file qcustomplot.h.
{ return mMinimumSize; }
int QCPLegend::paddingBottom () const [inline]
Definition at line 1466 of file qcustomplot.h.
{ return mPaddingBottom; }
int QCPLegend::paddingLeft () const [inline]
Definition at line 1463 of file qcustomplot.h.
{ return mPaddingLeft; }
int QCPLegend::paddingRight () const [inline]
Definition at line 1464 of file qcustomplot.h.
{ return mPaddingRight; }
int QCPLegend::paddingTop () const [inline]
Definition at line 1465 of file qcustomplot.h.
{ return mPaddingTop; }
QPoint QCPLegend::position () const [inline]
Definition at line 1459 of file qcustomplot.h.
{ return mPosition; }
PositionStyle QCPLegend::positionStyle () const [inline]
Definition at line 1458 of file qcustomplot.h.
{ return mPositionStyle; }
QCPLegend::Q_ENUMS (PositionStyle) [inline]
Defines the selectable parts of a legend. < None
< The legend box (frame)
< Legend items individually (see selectedItems)
Definition at line 1438 of file qcustomplot.h.
                      { spNone = 0
                       ,spLegendBox = 0x001
                       ,spItems = 0x002
                      };
QCPLegend::Q_ENUMS (SelectablePart)
void QCPLegend::reArrange ()
If setAutoSize is true, the size needed to fit all legend contents is calculated and applied. Finally, the automatic positioning of the legend is performed, depending on the setPositionStyle setting.
Definition at line 3158 of file qcustomplot.cpp.
References calculateAutoPosition(), calculateAutoSize(), and mAutoSize.
{
  if (mAutoSize)
  {
    calculateAutoSize();
  }
  calculateAutoPosition();
}
bool QCPLegend::removeItem (intindex)
Removes the item with index index from the legend. Returns true, if successful.
See also:
itemCount, clearItems
Definition at line 3100 of file qcustomplot.cpp.
References mItemBoundingBoxes, and mItems.
Referenced by removeItem().
{
  if (index >= 0 && index < mItems.size())
  {
    mItemBoundingBoxes.remove(mItems.at(index));
    delete mItems.at(index);
    mItems.removeAt(index);
    return true;
  } else
    return false;
}
bool QCPLegend::removeItem (QCPAbstractLegendItem *item)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes item from the legend. Returns true, if successful.
See also:
clearItems
Definition at line 3120 of file qcustomplot.cpp.
References mItems, and removeItem().
{
  return removeItem(mItems.indexOf(item));
}
SelectableParts QCPLegend::selectable () const [inline]
Definition at line 1475 of file qcustomplot.h.
Referenced by handleLegendSelection(), and setSelectable().
{ return mSelectable; }
SelectableParts QCPLegend::selected () const [inline]
Definition at line 1476 of file qcustomplot.h.
Referenced by handleLegendSelection(), selectedLegends(), and setSelected().
{ return mSelected; }
QPen QCPLegend::selectedBorderPen () const [inline]
Definition at line 1477 of file qcustomplot.h.
{ return mSelectedBorderPen; }
QBrush QCPLegend::selectedBrush () const [inline]
Definition at line 1479 of file qcustomplot.h.
{ return mSelectedBrush; }
QFont QCPLegend::selectedFont () const [inline]
Definition at line 1480 of file qcustomplot.h.
{ return mSelectedFont; }
QPen QCPLegend::selectedIconBorderPen () const [inline]
Definition at line 1478 of file qcustomplot.h.
Referenced by QCPPlottableLegendItem::getIconBorderPen().
{ return mSelectedIconBorderPen; }
QList< QCPAbstractLegendItem * > QCPLegend::selectedItems () const
Returns the legend items that are currently selected. If no items are selected, the list is empty.
See also:
QCPAbstractLegendItem::setSelected, setSelectable
Definition at line 3142 of file qcustomplot.cpp.
References mItems.
{
  QList<QCPAbstractLegendItem*> result;
  for (int i=0; i<mItems.size(); ++i)
  {
    if (mItems.at(i)->selected())
      result.append(mItems.at(i));
  }
  return result;
}
QColor QCPLegend::selectedTextColor () const [inline]
Definition at line 1481 of file qcustomplot.h.
{ return mSelectedTextColor; }
void QCPLegend::selectionChanged (QCPLegend::SelectablePartsselection) [signal]
This signal is emitted when the selection state of this legend has changed.
See also:
setSelected, setSelectable
Definition at line 1528 of file moc_qcustomplot.cpp.
Referenced by setSelected(), and updateSelectionState().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 0, _a);
}
QCPAbstractLegendItem * QCPLegend::selectTestItem (const QPointpos) const
When the point pos in pixels hits a legend item, the item is returned. If no item is hit, 0 is returned.
See also:
selectTestLegend
Definition at line 3183 of file qcustomplot.cpp.
References mItemBoundingBoxes, and mItems.
Referenced by handleLegendSelection(), and mouseReleaseEvent().
{
  QMap<QCPAbstractLegendItem*, QRect>::const_iterator it;
  for (it = mItemBoundingBoxes.constBegin(); it != mItemBoundingBoxes.constEnd(); ++it)
  {
    if (it.value().contains(pos) && mItems.contains(it.key()))
      return it.key();
  }
  return 0;
}
bool QCPLegend::selectTestLegend (const QPointF &pos) const
Returns whether the point pos in pixels hits the legend rect.
See also:
selectTestItem
Definition at line 3172 of file qcustomplot.cpp.
References mPosition, and mSize.
Referenced by handleLegendSelection(), and mouseReleaseEvent().
{
  return QRect(mPosition, mSize).contains(pos.toPoint());
}
void QCPLegend::setAutoSize (boolon)
Sets whether the size of the legend should be calculated automatically to fit all the content (plus padding), or whether the size must be specified manually with setSize. If the autoSize mechanism is enabled, the legend will have the smallest possible size to still display all its content. For items with text wrapping (QCPPlottableLegendItem::setTextWrap) this means, they would become very compressed, i.e. wrapped at every word. To prevent this, set a reasonable setMinimumSize width.
Definition at line 2702 of file qcustomplot.cpp.
References mAutoSize.
Referenced by QCPLegend().
{
  mAutoSize = on;
}
void QCPLegend::setBorderPen (const QPen &pen)
Sets the pen, the border of the entire legend is drawn with.
Definition at line 2627 of file qcustomplot.cpp.
References mBorderPen, and pen().
Referenced by QCPLegend().
{
  mBorderPen = pen;
}
void QCPLegend::setBrush (const QBrush &brush)
Sets the brush of the legend background.
Definition at line 2635 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by QCPLegend().
{
  mBrush = brush;
}
void QCPLegend::setFont (const QFont &font)
Sets the default font of legend text. Legend items that draw text (e.g. the name of a graph) will use this font by default. However, a different font can be specified on a per-item-basis by accessing the specific legend item.
This function will also set font on all already existing legend items.
See also:
QCPAbstractLegendItem::setFont
Definition at line 2649 of file qcustomplot.cpp.
References font(), mFont, and mItems.
Referenced by QCPLegend().
{
  mFont = font;
  for (int i=0; i<mItems.size(); ++i)
    mItems.at(i)->setFont(mFont);
}
void QCPLegend::setIconBorderPen (const QPen &pen)
Sets the pen used to draw a border around each legend icon. Legend items that draw an icon (e.g. a visual representation of the graph) will use this pen by default.
If no border is wanted, set this to Qt::NoPen.
Definition at line 2897 of file qcustomplot.cpp.
References mIconBorderPen, and pen().
Referenced by QCPLegend().
{
  mIconBorderPen = pen;
}
void QCPLegend::setIconSize (const QSize &size)
Sets the size of legend icons. Legend items that draw an icon (e.g. a visual representation of the graph) will use this size by default.
Definition at line 2866 of file qcustomplot.cpp.
References mIconSize, and size().
Referenced by QCPLegend().
{
  mIconSize = size;
}
void QCPLegend::setIconSize (intwidth, intheight)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2873 of file qcustomplot.cpp.
References mIconSize.
{
  mIconSize.setWidth(width);
  mIconSize.setHeight(height);
}
void QCPLegend::setIconTextPadding (intpadding)
Sets the horizontal space in pixels between the legend icon and the text next to it. Legend items that draw an icon (e.g. a visual representation of the graph) and text (e.g. the name of the graph) will use this space by default.
See also:
setItemSpacing
Definition at line 2886 of file qcustomplot.cpp.
References mIconTextPadding.
Referenced by QCPLegend().
{
  mIconTextPadding = padding;
}
void QCPLegend::setItemSpacing (intspacing)
Sets the vertical space between two legend items in the legend.
See also:
setIconTextPadding, setPadding
Definition at line 2857 of file qcustomplot.cpp.
References mItemSpacing.
Referenced by QCPLegend().
{
  mItemSpacing = spacing;
}
void QCPLegend::setMargin (intleft, intright, inttop, intbottom)
Sets the margin of the legend. Margins are the distances the legend will keep to the axis rect, when setPositionStyle is not psManual.
Definition at line 2844 of file qcustomplot.cpp.
References mMarginBottom, mMarginLeft, mMarginRight, and mMarginTop.
Referenced by QCPLegend().
{
  mMarginLeft = left;
  mMarginRight = right;
  mMarginTop = top;
  mMarginBottom = bottom;
}
void QCPLegend::setMarginBottom (intmargin)
Sets the bottom margin of the legend. Margins are the distances the legend will keep to the axis rect, when setPositionStyle is not psManual.
Definition at line 2835 of file qcustomplot.cpp.
References mMarginBottom.
{
  mMarginBottom = margin;
}
void QCPLegend::setMarginLeft (intmargin)
Sets the left margin of the legend. Margins are the distances the legend will keep to the axis rect, when setPositionStyle is not psManual.
Definition at line 2808 of file qcustomplot.cpp.
References mMarginLeft.
{
  mMarginLeft = margin;
}
void QCPLegend::setMarginRight (intmargin)
Sets the right margin of the legend. Margins are the distances the legend will keep to the axis rect, when setPositionStyle is not psManual.
Definition at line 2817 of file qcustomplot.cpp.
References mMarginRight.
{
  mMarginRight = margin;
}
void QCPLegend::setMarginTop (intmargin)
Sets the top margin of the legend. Margins are the distances the legend will keep to the axis rect, when setPositionStyle is not psManual.
Definition at line 2826 of file qcustomplot.cpp.
References mMarginTop.
{
  mMarginTop = margin;
}
void QCPLegend::setMinimumSize (const QSize &size)
Sets the minimum size of the legend when setAutoSize is enabled. If text wrapping is enabled in the legend items (e.g. QCPPlottableLegendItem::setTextWrap), this minimum size defines the width at which the wrapping will occur. Note that the wrapping will happen only at word boundaries, so the actual size might still be bigger than the size given here, but not smaller.
If setAutoSize is not enabled, the minimum size is ignored. Setting a smaller legend size with setSize manually, is not prevented.
See also:
setAutoSize, setSize, QCPPlottableLegendItem::setTextWrap
Definition at line 2739 of file qcustomplot.cpp.
References mMinimumSize, and size().
Referenced by QCPLegend().
{
  mMinimumSize = size;
}
void QCPLegend::setMinimumSize (intwidth, intheight)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2746 of file qcustomplot.cpp.
References mMinimumSize.
{
  mMinimumSize = QSize(width, height);
}
void QCPLegend::setPadding (intleft, intright, inttop, intbottom)
Sets the padding of the legend. Padding is the space by what the legend box is made larger than minimally needed for the content to fit. I.e. it's the space left blank on each side inside the legend.
Definition at line 2796 of file qcustomplot.cpp.
References mPaddingBottom, mPaddingLeft, mPaddingRight, and mPaddingTop.
Referenced by QCPLegend().
{
  mPaddingLeft = left;
  mPaddingRight = right;
  mPaddingTop = top;
  mPaddingBottom = bottom;
}
void QCPLegend::setPaddingBottom (intpadding)
Sets the bottom padding of the legend. Padding is the space by what the legend box is made larger than minimally needed for the content to fit. I.e. it's the space left blank on each side inside the legend.
Definition at line 2786 of file qcustomplot.cpp.
References mPaddingBottom.
{
  mPaddingBottom = padding;
}
void QCPLegend::setPaddingLeft (intpadding)
Sets the left padding of the legend. Padding is the space by what the legend box is made larger than minimally needed for the content to fit. I.e. it's the space left blank on each side inside the legend.
Definition at line 2756 of file qcustomplot.cpp.
References mPaddingLeft.
{
  mPaddingLeft = padding;
}
void QCPLegend::setPaddingRight (intpadding)
Sets the right padding of the legend. Padding is the space by what the legend box is made larger than minimally needed for the content to fit. I.e. it's the space left blank on each side inside the legend.
Definition at line 2766 of file qcustomplot.cpp.
References mPaddingRight.
{
  mPaddingRight = padding;
}
void QCPLegend::setPaddingTop (intpadding)
Sets the top padding of the legend. Padding is the space by what the legend box is made larger than minimally needed for the content to fit. I.e. it's the space left blank on each side inside the legend.
Definition at line 2776 of file qcustomplot.cpp.
References mPaddingTop.
{
  mPaddingTop = padding;
}
void QCPLegend::setPosition (const QPoint &pixelPosition)
Sets the exact pixel Position of the legend inside the QCustomPlot widget, if setPositionStyle is set to psManual. Margins have no effect in that case.
Definition at line 2688 of file qcustomplot.cpp.
References mPosition.
{
  mPosition = pixelPosition;
}
void QCPLegend::setPositionStyle (PositionStylelegendPositionStyle)
Sets the position style of the legend. If the legendPositionStyle is not psManual, the position is found automatically depending on the specific legendPositionStyle and the legend margins. If legendPositionStyle is psManual, the exact pixel position of the legend must be specified via setPosition. Margins have no effect in that case.
See also:
setMargin
Definition at line 2679 of file qcustomplot.cpp.
References mPositionStyle.
Referenced by QCPLegend().
{
  mPositionStyle = legendPositionStyle;
}
void QCPLegend::setSelectable (const SelectableParts &selectable)
Sets whether the user can (de-)select the parts in selectable by clicking on the QCustomPlot surface. (When QCustomPlot::setInteractions contains iSelectLegend.)
However, even when selectable is set to a value not allowing the selection of a specific part, it is still possible to set the selection of this part manually, by calling setSelected directly.
See also:
SelectablePart, setSelected
Definition at line 2912 of file qcustomplot.cpp.
References mSelectable, and selectable().
Referenced by QCPLegend().
{
  mSelectable = selectable;
}
void QCPLegend::setSelected (const SelectableParts &selected)
Sets the selected state of the respective legend parts described by SelectablePart. When a part is selected, it uses a different pen/font and brush. If some legend items are selected and selected doesn't contain spItems, those items become deselected.
The entire selection mechanism is handled automatically when QCustomPlot::setInteractions contains iSelectLegend. You only need to call this function when you wish to change the selection state manually.
This function can change the selection state of a part even when setSelectable was set to a value that actually excludes the part.
emits the selectionChanged signal when selected is different from the previous selection state.
Note that it doesn't make sense to set the selected state spItems here when it wasn't set before, because there's no way to specify which exact items to newly select. Do this by calling QCPAbstractLegendItem::setSelected directly on the legend item you wish to select.
See also:
SelectablePart, setSelectable, selectTest, setSelectedBorderPen, setSelectedIconBorderPen, setSelectedBrush, setSelectedFont
Definition at line 2938 of file qcustomplot.cpp.
References mItems, mSelected, selected(), and selectionChanged().
Referenced by deselectAll(), handleLegendSelection(), and QCPLegend().
{
  if (mSelected != selected)
  {
    if (!selected.testFlag(spItems) && mSelected.testFlag(spItems)) // some items are selected, but new selection state doesn't contain spItems, so deselect them
    {
      for (int i=0; i<mItems.size(); ++i)
        mItems.at(i)->setSelected(false);
      mSelected = selected;
      // not necessary to emit selectionChanged here because this will have happened for the last setSelected(false) on mItems already, via updateSelectionState()
    } else
    {
      mSelected = selected;
      emit selectionChanged(mSelected);
    }
  }
}
void QCPLegend::setSelectedBorderPen (const QPen &pen)
When the legend box is selected, this pen is used to draw the border instead of the normal pen set via setBorderPen.
See also:
setSelected, setSelectable, setSelectedBrush
Definition at line 2962 of file qcustomplot.cpp.
References mSelectedBorderPen, and pen().
Referenced by QCPLegend().
{
  mSelectedBorderPen = pen;
}
void QCPLegend::setSelectedBrush (const QBrush &brush)
When the legend box is selected, this brush is used to draw the legend background instead of the normal brush set via setBrush.
See also:
setSelected, setSelectable, setSelectedBorderPen
Definition at line 2983 of file qcustomplot.cpp.
References brush(), and mSelectedBrush.
Referenced by QCPLegend().
{
  mSelectedBrush = brush;
}
void QCPLegend::setSelectedFont (const QFont &font)
Sets the default font that is used by legend items when they are selected. This function will also set font on all already existing legend items.
See also:
setFont, QCPAbstractLegendItem::setSelectedFont
Definition at line 2995 of file qcustomplot.cpp.
References font(), mItems, and mSelectedFont.
Referenced by QCPLegend().
{
  mSelectedFont = font;
  for (int i=0; i<mItems.size(); ++i)
    mItems.at(i)->setSelectedFont(font);
}
void QCPLegend::setSelectedIconBorderPen (const QPen &pen)
Sets the pen legend items will use to draw their icon borders, when they are selected.
See also:
setSelected, setSelectable, setSelectedFont
Definition at line 2972 of file qcustomplot.cpp.
References mSelectedIconBorderPen, and pen().
Referenced by QCPLegend().
{
  mSelectedIconBorderPen = pen;
}
void QCPLegend::setSelectedTextColor (const QColor &color)
Sets the default text color that is used by legend items when they are selected. This function will also set color on all already existing legend items.
See also:
setTextColor, QCPAbstractLegendItem::setSelectedTextColor
Definition at line 3009 of file qcustomplot.cpp.
References color(), mItems, and mSelectedTextColor.
Referenced by QCPLegend().
{
  mSelectedTextColor = color;
  for (int i=0; i<mItems.size(); ++i)
    mItems.at(i)->setSelectedTextColor(color);
}
void QCPLegend::setSize (const QSize &size)
Sets the size of the legend. Setting the size manually with this function only has an effect, if setAutoSize is set to false.
If you want to control the minimum size (or the text-wrapping width) while still leaving the autoSize mechanism enabled, consider using setMinimumSize.
See also:
setAutoSize, setMinimumSize
Definition at line 2716 of file qcustomplot.cpp.
References mSize, and size().
Referenced by QCPLegend().
{
  mSize = size;
}
void QCPLegend::setSize (intwidth, intheight)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2723 of file qcustomplot.cpp.
References mSize.
{
  mSize = QSize(width, height);
}
void QCPLegend::setTextColor (const QColor &color)
Sets the default color of legend text. Legend items that draw text (e.g. the name of a graph) will use this color by default. However, a different colors can be specified on a per-item-basis by accessing the specific legend item.
This function will also set color on all already existing legend items.
See also:
QCPAbstractLegendItem::setTextColor
Definition at line 2665 of file qcustomplot.cpp.
References color(), mItems, and mTextColor.
Referenced by QCPLegend().
{
  mTextColor = color;
  for (int i=0; i<mItems.size(); ++i)
    mItems.at(i)->setTextColor(color);
}
QSize QCPLegend::size () const [inline]
Definition at line 1461 of file qcustomplot.h.
Referenced by setIconSize(), setMinimumSize(), and setSize().
{ return mSize; }
QColor QCPLegend::textColor () const [inline]
Definition at line 1457 of file qcustomplot.h.
{ return mTextColor; }
void QCPLegend::updateSelectionState () [protected], [virtual]
Updates the spItems part of the selection state of this legend by going through all child items and checking their selected state.
If no items are selected and the current selected state contains spItems, it is removed and the selectionChanged signal is emitted. If at least one item is selected and the current selection state does not contain spItems, it is added and the signal is emitted, too.
This function is called in the QCPAbstractLegendItem::setSelected functions to propagate their change to the parent legend.
Definition at line 3206 of file qcustomplot.cpp.
References mItems, mSelected, and selectionChanged().
Referenced by QCPAbstractLegendItem::setSelected().
{
  bool hasSelections = false;
  for (int i=0; i<mItems.size(); ++i)
  {
    if (mItems.at(i)->selected())
    {
      hasSelections = true;
      break;
    }
  }
  
  // in the following we don't use setSelected because it would cause unnecessary
  // logic looping through items if spItems isn't set in the new state. (look at setSelected and you'll understand)
  if (hasSelections && !mSelected.testFlag(spItems))
  {
    mSelected |= spItems;
    emit selectionChanged(mSelected);
  } else if (!hasSelections && mSelected.testFlag(spItems))
  {
    mSelected &= ~spItems;
    emit selectionChanged(mSelected);
  }
}
Friends And Related Function Documentation
friend class QCPAbstractLegendItem [friend]
Definition at line 1576 of file qcustomplot.h.
Member Data Documentation
bool QCPLegend::mAutoSize [protected]
Definition at line 1546 of file qcustomplot.h.
Referenced by reArrange(), and setAutoSize().
QPen QCPLegend::mBorderPen [protected]
Definition at line 1539 of file qcustomplot.h.
Referenced by getBorderPen(), and setBorderPen().
QBrush QCPLegend::mBrush [protected]
Definition at line 1540 of file qcustomplot.h.
Referenced by getBrush(), and setBrush().
QFont QCPLegend::mFont [protected]
Definition at line 1541 of file qcustomplot.h.
Referenced by setFont().
QPen QCPLegend::mIconBorderPen [protected]
Definition at line 1539 of file qcustomplot.h.
Referenced by setIconBorderPen().
QSize QCPLegend::mIconSize [protected]
Definition at line 1544 of file qcustomplot.h.
Referenced by setIconSize().
int QCPLegend::mIconTextPadding [protected]
Definition at line 1549 of file qcustomplot.h.
Referenced by setIconTextPadding().
QMap<QCPAbstractLegendItem*, QRect> QCPLegend::mItemBoundingBoxes [protected]
Definition at line 1558 of file qcustomplot.h.
Referenced by clearItems(), draw(), removeItem(), and selectTestItem().
QList<QCPAbstractLegendItem*> QCPLegend::mItems [protected]
Definition at line 1557 of file qcustomplot.h.
Referenced by addItem(), calculateAutoSize(), clearItems(), draw(), hasItem(), item(), itemCount(), itemWithPlottable(), removeItem(), selectedItems(), selectTestItem(), setFont(), setSelected(), setSelectedFont(), setSelectedTextColor(), setTextColor(), and updateSelectionState().
int QCPLegend::mItemSpacing [protected]
Definition at line 1549 of file qcustomplot.h.
Referenced by calculateAutoSize(), draw(), and setItemSpacing().
int QCPLegend::mMarginBottom [protected]
Definition at line 1548 of file qcustomplot.h.
Referenced by calculateAutoPosition(), setMargin(), and setMarginBottom().
int QCPLegend::mMarginLeft [protected]
Definition at line 1548 of file qcustomplot.h.
Referenced by calculateAutoPosition(), setMargin(), and setMarginLeft().
int QCPLegend::mMarginRight [protected]
Definition at line 1548 of file qcustomplot.h.
Referenced by calculateAutoPosition(), setMargin(), and setMarginRight().
int QCPLegend::mMarginTop [protected]
Definition at line 1548 of file qcustomplot.h.
Referenced by calculateAutoPosition(), setMargin(), and setMarginTop().
QSize QCPLegend::mMinimumSize [protected]
Definition at line 1544 of file qcustomplot.h.
Referenced by calculateAutoSize(), and setMinimumSize().
int QCPLegend::mPaddingBottom [protected]
Definition at line 1547 of file qcustomplot.h.
Referenced by calculateAutoSize(), setPadding(), and setPaddingBottom().
int QCPLegend::mPaddingLeft [protected]
Definition at line 1547 of file qcustomplot.h.
Referenced by calculateAutoSize(), draw(), setPadding(), and setPaddingLeft().
int QCPLegend::mPaddingRight [protected]
Definition at line 1547 of file qcustomplot.h.
Referenced by calculateAutoSize(), setPadding(), and setPaddingRight().
int QCPLegend::mPaddingTop [protected]
Definition at line 1547 of file qcustomplot.h.
Referenced by calculateAutoSize(), draw(), setPadding(), and setPaddingTop().
QPoint QCPLegend::mPosition [protected]
Definition at line 1543 of file qcustomplot.h.
Referenced by calculateAutoPosition(), draw(), selectTestLegend(), and setPosition().
PositionStyle QCPLegend::mPositionStyle [protected]
Definition at line 1545 of file qcustomplot.h.
Referenced by calculateAutoPosition(), and setPositionStyle().
SelectableParts QCPLegend::mSelectable [protected]
Definition at line 1550 of file qcustomplot.h.
Referenced by setSelectable().
SelectableParts QCPLegend::mSelected [protected]
Definition at line 1550 of file qcustomplot.h.
Referenced by getBorderPen(), getBrush(), setSelected(), and updateSelectionState().
QPen QCPLegend::mSelectedBorderPen [protected]
Definition at line 1551 of file qcustomplot.h.
Referenced by getBorderPen(), and setSelectedBorderPen().
QBrush QCPLegend::mSelectedBrush [protected]
Definition at line 1552 of file qcustomplot.h.
Referenced by getBrush(), and setSelectedBrush().
QFont QCPLegend::mSelectedFont [protected]
Definition at line 1553 of file qcustomplot.h.
Referenced by setSelectedFont().
QPen QCPLegend::mSelectedIconBorderPen [protected]
Definition at line 1551 of file qcustomplot.h.
Referenced by setSelectedIconBorderPen().
QColor QCPLegend::mSelectedTextColor [protected]
Definition at line 1554 of file qcustomplot.h.
Referenced by setSelectedTextColor().
QSize QCPLegend::mSize [protected]
Definition at line 1544 of file qcustomplot.h.
Referenced by calculateAutoPosition(), calculateAutoSize(), draw(), selectTestLegend(), and setSize().
QColor QCPLegend::mTextColor [protected]
Definition at line 1542 of file qcustomplot.h.
Referenced by setTextColor().
Author
Generated automatically by Doxygen for AQ0X from the source code.