QCPLineEnding
NAME
QCPLineEnding -
Handles the different ending decorations for line-like items.
SYNOPSIS
#include <qcustomplot.h>
Public Types
enum EndingStyle { esNone, esFlatArrow, esSpikeArrow, esLineArrow, esDisc, esSquare, esDiamond, esBar }
Defines the type of ending decoration for line-like items, e.g.
Public Member Functions
QCPLineEnding ()
Creates a QCPLineEnding instance with default values (style esNone).
QCPLineEnding (EndingStyle style, double width=8, double length=10, bool inverted=false)
Creates a QCPLineEnding instance with the specified values.
EndingStyle style () const
double width () const
double length () const
bool inverted () const
void setStyle (EndingStyle style)
Sets the style of the ending decoration.
void setWidth (double width)
Sets the width of the ending decoration, if the style supports it.
void setLength (double length)
Sets the length of the ending decoration, if the style supports it.
void setInverted (bool inverted)
Sets whether the direction of the ending decoration shall be inverted with respect to the natural direction given by the parent item.
double boundingDistance () const
void draw (QCPPainter *painter, const QVector2D &pos, const QVector2D &dir) const
void draw (QCPPainter *painter, const QVector2D &pos, double angle) const
Protected Attributes
EndingStyle mStyle
double mWidth
double mLength
bool mInverted
Detailed Description
Handles the different ending decorations for line-like items.
The various ending styles currently supported For every ending a line-like item has, an instance of this class exists. For example, QCPItemLine has two endings which can be set with QCPItemLine::setHead and QCPItemLine::setTail.
The styles themselves are defined via the enum QCPLineEnding::EndingStyle. Most decorations can be modified regarding width and length, see setWidth and setLength. The direction of the ending decoration (e.g. direction an arrow is pointing) is controlled by the line-like item. For example, when both endings of a QCPItemLine are set to be arrows, they will point to opposite directions, e.g. 'outward'. This can be changed by setInverted, which would make the respective arrow point inward.
Note that due to the overloaded QCPLineEnding constructor, you may directly specify a QCPLineEnding::EndingStyle where actually a QCPLineEnding is expected, e.g.
myItemLine->setHead(QCPLineEnding::esSpikeArrow)
Definition at line 243 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPLineEnding::EndingStyle
Defines the type of ending decoration for line-like items, e.g. an arrow.
The width and length of these decorations can be controlled with the functions setWidth and setLength. Some decorations like esDisc, esSquare, esDiamond and esBar only support a width, the length property is ignored.
See also:
QCPItemLine::setHead, QCPItemLine::setTail, QCPItemCurve::setHead, QCPItemCurve::setTail
Enumerator
esNone
No ending decoration.
esFlatArrow
A filled arrow head with a straight/flat back (a triangle)
esSpikeArrow
A filled arrow head with an indented back.
esLineArrow
A non-filled arrow head with open back.
esDisc
A filled circle.
esSquare
A filled square.
esDiamond
A filled diamond (45° rotated square)
esBar
A bar perpendicular to the line.
Definition at line 257 of file qcustomplot.h.
                   { esNone
                     ,esFlatArrow
                     ,esSpikeArrow
                     ,esLineArrow
                     ,esDisc
                     ,esSquare
                     ,esDiamond
                     ,esBar
                   };
Constructor & Destructor Documentation
QCPLineEnding::QCPLineEnding ()
Creates a QCPLineEnding instance with default values (style esNone).
Definition at line 13450 of file qcustomplot.cpp.
                             :
  mStyle(esNone),
  mWidth(8),
  mLength(10),
  mInverted(false)
{
}
QCPLineEnding::QCPLineEnding (QCPLineEnding::EndingStylestyle, doublewidth = 8, doublelength = 10, boolinverted = false)
Creates a QCPLineEnding instance with the specified values.
Definition at line 13461 of file qcustomplot.cpp.
                                                                                                       :
  mStyle(style),
  mWidth(width),
  mLength(length),
  mInverted(inverted)
{
}
Member Function Documentation
double QCPLineEnding::boundingDistance () const
Returns the maximum pixel radius the ending decoration might cover, starting from the position the decoration is drawn at (typically a line ending/QCPItemPosition of an item).
This is relevant for clipping. Only omit painting of the decoration when the position where the decoration is supposed to be drawn is farther away from the clipping rect than the returned distance.
Definition at line 13518 of file qcustomplot.cpp.
References esBar, esDiamond, esDisc, esFlatArrow, esLineArrow, esNone, esSpikeArrow, esSquare, mLength, mStyle, and mWidth.
Referenced by QCPItemLine::draw().
{
  switch (mStyle)
  {
    case esNone:
      return 0;
      
    case esFlatArrow:
    case esSpikeArrow:
    case esLineArrow:
      return qSqrt(mWidth*mWidth+mLength*mLength); // items that have width and length
      
    case esDisc:
    case esSquare:
    case esDiamond:
    case esBar:
      return mWidth*1.42; // items that only have a width -> with*sqrt(2)
  }
  return 0;
}
void QCPLineEnding::draw (QCPPainter *painter, const QVector2D &pos, const QVector2D &dir) const
Draws the line ending with the specified painter at the position pos. The direction of the line ending is controlled with dir.
Definition at line 13544 of file qcustomplot.cpp.
References QCPPainter::drawLine(), esBar, esDiamond, esDisc, esFlatArrow, esLineArrow, esNone, esSpikeArrow, esSquare, mInverted, mLength, mStyle, mWidth, and QCPPainter::setPen().
Referenced by draw(), QCPItemLine::draw(), and QCPItemCurve::draw().
{
  if (mStyle == esNone)
    return;
  
  QVector2D lengthVec(dir.normalized()*(mInverted ? -1 : 1));
  if (lengthVec.isNull())
    lengthVec = QVector2D(1, 0);
  QVector2D widthVec(-lengthVec.y(), lengthVec.x());
  lengthVec *= mLength;
  widthVec *= mWidth*0.5;
  
  QPen penBackup = painter->pen();
  QPen miterPen = penBackup;
  miterPen.setJoinStyle(Qt::MiterJoin);
  switch (mStyle)
  {
    case esNone: break;
    case esFlatArrow:
    {
      QPointF points[3] = {pos.toPointF(),
                           (pos-lengthVec+widthVec).toPointF(),
                           (pos-lengthVec-widthVec).toPointF()
                          };
      painter->setPen(miterPen);
      painter->drawConvexPolygon(points, 3);
      painter->setPen(penBackup);
      break;
    }
    case esSpikeArrow:
    {
      QPointF points[4] = {pos.toPointF(),
                           (pos-lengthVec+widthVec).toPointF(),
                           (pos-lengthVec*0.8).toPointF(),
                           (pos-lengthVec-widthVec).toPointF()
                          };
      painter->setPen(miterPen);
      painter->drawConvexPolygon(points, 4);
      painter->setPen(penBackup);
      break;
    }
    case esLineArrow:
    {
      QPointF points[3] = {(pos-lengthVec+widthVec).toPointF(),
                           pos.toPointF(),
                           (pos-lengthVec-widthVec).toPointF()
                          };
      painter->setPen(miterPen);
      painter->drawPolyline(points, 3);
      painter->setPen(penBackup);
      break;
    }
    case esDisc:
    {
      painter->drawEllipse(pos.toPointF(), mWidth*0.5, mWidth*0.5);
      break;
    }
    case esSquare:
    {
      QVector2D widthVecPerp(-widthVec.y(), widthVec.x());
      QPointF points[4] = {(pos-widthVecPerp+widthVec).toPointF(),
                           (pos-widthVecPerp-widthVec).toPointF(),
                           (pos+widthVecPerp-widthVec).toPointF(),
                           (pos+widthVecPerp+widthVec).toPointF()
                          };
      painter->setPen(miterPen);
      painter->drawConvexPolygon(points, 4);
      painter->setPen(penBackup);
      break;
    }
    case esDiamond:
    {
      QVector2D widthVecPerp(-widthVec.y(), widthVec.x());
      QPointF points[4] = {(pos-widthVecPerp).toPointF(),
                           (pos-widthVec).toPointF(),
                           (pos+widthVecPerp).toPointF(),
                           (pos+widthVec).toPointF()
                          };
      painter->setPen(miterPen);
      painter->drawConvexPolygon(points, 4);
      painter->setPen(penBackup);
      break;
    }
    case esBar:
    {
      painter->drawLine((pos+widthVec).toPointF(), (pos-widthVec).toPointF());
      break;
    }
  }
}
void QCPLineEnding::draw (QCPPainter *painter, const QVector2D &pos, doubleangle) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Draws the line ending. The direction is controlled with the angle parameter in radians.
Definition at line 13640 of file qcustomplot.cpp.
References draw().
{
  draw(painter, pos, QVector2D(qCos(angle), qSin(angle)));
}
bool QCPLineEnding::inverted () const [inline]
Definition at line 274 of file qcustomplot.h.
Referenced by setInverted().
{ return mInverted; }
double QCPLineEnding::length () const [inline]
Definition at line 273 of file qcustomplot.h.
Referenced by setLength().
{ return mLength; }
void QCPLineEnding::setInverted (boolinverted)
Sets whether the direction of the ending decoration shall be inverted with respect to the natural direction given by the parent item. For example, an arrow decoration will point inward when inverted is set to true.
Definition at line 13504 of file qcustomplot.cpp.
References inverted(), and mInverted.
{
  mInverted = inverted;
}
void QCPLineEnding::setLength (doublelength)
Sets the length of the ending decoration, if the style supports it. On arrows, for example, the length defines the size in pointing direction.
See also:
setWidth
Definition at line 13494 of file qcustomplot.cpp.
References length(), and mLength.
{
  mLength = length;
}
void QCPLineEnding::setStyle (QCPLineEnding::EndingStylestyle)
Sets the style of the ending decoration.
Definition at line 13472 of file qcustomplot.cpp.
References mStyle, and style().
{
  mStyle = style;
}
void QCPLineEnding::setWidth (doublewidth)
Sets the width of the ending decoration, if the style supports it. On arrows, for example, the width defines the size perpendicular to the arrow's pointing direction.
See also:
setLength
Definition at line 13483 of file qcustomplot.cpp.
References mWidth, and width().
{
  mWidth = width;
}
EndingStyle QCPLineEnding::style () const [inline]
Definition at line 271 of file qcustomplot.h.
Referenced by QCPItemLine::draw(), QCPItemCurve::draw(), and setStyle().
{ return mStyle; }
double QCPLineEnding::width () const [inline]
Definition at line 272 of file qcustomplot.h.
Referenced by setWidth().
{ return mWidth; }
Member Data Documentation
bool QCPLineEnding::mInverted [protected]
Definition at line 290 of file qcustomplot.h.
Referenced by draw(), and setInverted().
double QCPLineEnding::mLength [protected]
Definition at line 289 of file qcustomplot.h.
Referenced by boundingDistance(), draw(), and setLength().
EndingStyle QCPLineEnding::mStyle [protected]
Definition at line 288 of file qcustomplot.h.
Referenced by boundingDistance(), draw(), and setStyle().
double QCPLineEnding::mWidth [protected]
Definition at line 289 of file qcustomplot.h.
Referenced by boundingDistance(), draw(), and setWidth().
Author
Generated automatically by Doxygen for AQ0X from the source code.