QCPPlottableLegendItem
NAME
QCPPlottableLegendItem -
A legend item representing a plottable with an icon and the plottable name.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPAbstractLegendItem.
Public Member Functions
QCPPlottableLegendItem (QCPLegend *parent, QCPAbstractPlottable *plottable)
Creates a new legend item associated with plottable.
virtual ~QCPPlottableLegendItem ()
QCPAbstractPlottable * plottable ()
bool textWrap () const
void setTextWrap (bool wrap)
Sets whether the text of the legend item is wrapped at word boundaries to fit the with of the legend.
Protected Member Functions
QPen getIconBorderPen () const
QColor getTextColor () const
QFont getFont () const
virtual void draw (QCPPainter *painter, const QRect &rect) const
virtual QSize size (const QSize &targetSize) const
Protected Attributes
QCPAbstractPlottable * mPlottable
bool mTextWrap
Additional Inherited Members
Detailed Description
A legend item representing a plottable with an icon and the plottable name.
This is the standard legend item for plottables. It displays an icon of the plottable next to the plottable name. The icon is drawn by the respective plottable itself (QCPAbstractPlottable::drawLegendIcon), and tries to give an intuitive symbol for the plottable. For example, the QCPGraph draws a centered horizontal line with a single scatter point in the middle and filling (if enabled) below.
Legend items of this type are always associated with one plottable (retrievable via the plottable() function and settable with the constructor). You may change the font of the plottable name with setFont. If setTextWrap is set to true, the plottable name will wrap at the right legend boundary (see QCPLegend::setMinimumSize). Icon padding and border pen is taken from the parent QCPLegend, see QCPLegend::setIconBorderPen and QCPLegend::setIconTextPadding.
The function QCPAbstractPlottable::addToLegend/QCPAbstractPlottable::removeFromLegend creates/removes legend items of this type in the default implementation. However, these functions may be reimplemented such that a different kind of legend item (e.g a direct subclass of QCPAbstractLegendItem) is used for that plottable.
Definition at line 1395 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPPlottableLegendItem::QCPPlottableLegendItem (QCPLegend *parent, QCPAbstractPlottable *plottable)
Creates a new legend item associated with plottable. Once it's created, it can be added to the legend via QCPLegend::addItem.
A more convenient way of adding/removing a plottable to/from the legend is via the functions QCPAbstractPlottable::addToLegend and QCPAbstractPlottable::removeFromLegend.
Definition at line 9040 of file qcustomplot.cpp.
                                                                                                 :
  QCPAbstractLegendItem(parent),
  mPlottable(plottable),
  mTextWrap(false)
{
}
virtual QCPPlottableLegendItem::~QCPPlottableLegendItem () [inline], [virtual]
Definition at line 1400 of file qcustomplot.h.
{}
Member Function Documentation
void QCPPlottableLegendItem::draw (QCPPainter *painter, const QRect &rect) const [protected], [virtual]
Draws the item with painter into rect.
The width of the passed rect is used as text wrapping width, when setTextWrap is enabled. The height is ignored. The rect is not used as a clipping rect (overpainting is not prevented inside this function), so you should set an appropriate clipping rect on the painter before calling this function. Ideally, the width of the rect should be the result of a preceding call to size.
Implements QCPAbstractLegendItem.
Definition at line 9100 of file qcustomplot.cpp.
References QCPAbstractPlottable::drawLegendIcon(), getFont(), getIconBorderPen(), getTextColor(), QCPLegend::iconSize(), QCPLegend::iconTextPadding(), QCPAbstractLegendItem::mParentLegend, mPlottable, mTextWrap, QCPAbstractPlottable::name(), QCPPainter::restore(), QCPPainter::save(), and QCPPainter::setPen().
{
  if (!mPlottable) return;
  painter->setFont(getFont());
  painter->setPen(QPen(getTextColor()));
  int iconTextPadding = mParentLegend->iconTextPadding();
  QSize iconSize = mParentLegend->iconSize();
  QRect textRect;
  QRect iconRect(rect.topLeft(), iconSize);
  if (mTextWrap)
  {
    // take width from rect since our text should wrap there (only icon must fit at least):
    textRect = painter->fontMetrics().boundingRect(0, 0, rect.width()-iconTextPadding-iconSize.width(), rect.height(), Qt::TextDontClip | Qt::TextWordWrap, mPlottable->name());
    if (textRect.height() < iconSize.height()) // text smaller than icon, center text vertically in icon height
    {
      painter->drawText(rect.x()+iconSize.width()+iconTextPadding, rect.y(), rect.width()-iconTextPadding-iconSize.width(), iconSize.height(), Qt::TextDontClip | Qt::TextWordWrap, mPlottable->name());
    } else // text bigger than icon, position top of text with top of icon
    {
      painter->drawText(rect.x()+iconSize.width()+iconTextPadding, rect.y(), rect.width()-iconTextPadding-iconSize.width(), textRect.height(), Qt::TextDontClip | Qt::TextWordWrap, mPlottable->name());
    }
  } else
  {
    // text can't wrap (except with explicit newlines), center at current item size (icon size)
    textRect = painter->fontMetrics().boundingRect(0, 0, 0, rect.height(), Qt::TextDontClip, mPlottable->name());
    if (textRect.height() < iconSize.height()) // text smaller than icon, center text vertically in icon height
    {
      painter->drawText(rect.x()+iconSize.width()+iconTextPadding, rect.y(), rect.width(), iconSize.height(), Qt::TextDontClip, mPlottable->name());
    } else // text bigger than icon, position top of text with top of icon
    {
      painter->drawText(rect.x()+iconSize.width()+iconTextPadding, rect.y(), rect.width(), textRect.height(), Qt::TextDontClip, mPlottable->name());
    }
  }
  // draw icon:
  painter->save();
  painter->setClipRect(iconRect, Qt::IntersectClip);
  mPlottable->drawLegendIcon(painter, iconRect);
  painter->restore();
  // draw icon border:
  if (getIconBorderPen().style() != Qt::NoPen)
  {
    painter->setPen(getIconBorderPen());
    painter->setBrush(Qt::NoBrush);
    painter->drawRect(iconRect);
  }
}
QFont QCPPlottableLegendItem::getFont () const [protected]
Returns the font that shall be used to draw text, taking into account the selection state of this item.
Definition at line 9085 of file qcustomplot.cpp.
References QCPAbstractLegendItem::mFont, QCPAbstractLegendItem::mSelected, and QCPAbstractLegendItem::mSelectedFont.
Referenced by draw(), and size().
{
  return mSelected ? mSelectedFont : mFont;
}
QPen QCPPlottableLegendItem::getIconBorderPen () const [protected]
Returns the pen that shall be used to draw the icon border, taking into account the selection state of this item.
Definition at line 9065 of file qcustomplot.cpp.
References QCPLegend::iconBorderPen(), QCPAbstractLegendItem::mParentLegend, QCPAbstractLegendItem::mSelected, and QCPLegend::selectedIconBorderPen().
Referenced by draw().
{
  return mSelected ? mParentLegend->selectedIconBorderPen() : mParentLegend->iconBorderPen();
}
QColor QCPPlottableLegendItem::getTextColor () const [protected]
Returns the text color that shall be used to draw text, taking into account the selection state of this item.
Definition at line 9075 of file qcustomplot.cpp.
References QCPAbstractLegendItem::mSelected, QCPAbstractLegendItem::mSelectedTextColor, and QCPAbstractLegendItem::mTextColor.
Referenced by draw().
{
  return mSelected ? mSelectedTextColor : mTextColor;
}
QCPAbstractPlottable* QCPPlottableLegendItem::plottable () [inline]
Definition at line 1403 of file qcustomplot.h.
{ return mPlottable; }
void QCPPlottableLegendItem::setTextWrap (boolwrap)
Sets whether the text of the legend item is wrapped at word boundaries to fit the with of the legend. To prevent the legend autoSize feature (QCPLegend::setAutoSize) from compressing the text too strong by wrapping it very often, set an appropriate minimum width with QCPLegend::setMinimumSize.
Definition at line 9055 of file qcustomplot.cpp.
References mTextWrap.
{
  mTextWrap = wrap;
}
QSize QCPPlottableLegendItem::size (const QSize &targetSize) const [protected], [virtual]
Calculates and returns the size of this item. If setTextWrap is enabled, the width of targetSize will be used as the text wrapping width. This does not guarantee, that the width of the returned QSize is the same as the width of targetSize, since wrapping occurs only at word boundaries. So a single word that extends beyond the width of targetSize, will stretch the returned QSize accordingly.
The height of targetSize is ignored. The height of the returned QSize is either the height of the icon or the height of the text bounding box, whichever is larger.
Implements QCPAbstractLegendItem.
Definition at line 9157 of file qcustomplot.cpp.
References getFont(), QCPLegend::iconSize(), QCPLegend::iconTextPadding(), QCPAbstractLegendItem::mParentLegend, mPlottable, mTextWrap, and QCPAbstractPlottable::name().
{
  if (!mPlottable) return QSize();
  QSize result(0, 0);
  QRect textRect;
  QFontMetrics fontMetrics(getFont());
  int iconTextPadding = mParentLegend->iconTextPadding();
  QSize iconSize = mParentLegend->iconSize();
  if (mTextWrap)
  {
    // take width from targetSize since our text can wrap (Only icon must fit at least):
    textRect = fontMetrics.boundingRect(0, 0, targetSize.width()-iconTextPadding-iconSize.width(), iconSize.height(), Qt::TextDontClip | Qt::TextWordWrap, mPlottable->name());
  } else
  {
    // text can't wrap (except with explicit newlines), center at current item size (icon size)
    textRect = fontMetrics.boundingRect(0, 0, 0, iconSize.height(), Qt::TextDontClip, mPlottable->name());
  }
  result.setWidth(iconSize.width() + mParentLegend->iconTextPadding() + textRect.width());
  result.setHeight(qMax(textRect.height(), iconSize.height()));
  return result;
}
bool QCPPlottableLegendItem::textWrap () const [inline]
Definition at line 1404 of file qcustomplot.h.
{ return mTextWrap; }
Member Data Documentation
QCPAbstractPlottable* QCPPlottableLegendItem::mPlottable [protected]
Definition at line 1410 of file qcustomplot.h.
Referenced by draw(), and size().
bool QCPPlottableLegendItem::mTextWrap [protected]
Definition at line 1411 of file qcustomplot.h.
Referenced by draw(), setTextWrap(), and size().
Author
Generated automatically by Doxygen for AQ0X from the source code.