QCPPainter
NAME
QCPPainter -
QPainter subclass used internally.
SYNOPSIS
#include <qcustomplot.h>
Inherits QPainter.
Public Member Functions
QCPPainter ()
Creates a new QCPPainter instance and sets default values.
QCPPainter (QPaintDevice *device)
Creates a new QCPPainter instance on the specified paint device and sets default values.
~QCPPainter ()
QPixmap scatterPixmap () const
bool antialiasing () const
bool pdfExportMode () const
bool scaledExportMode () const
void setScatterPixmap (const QPixmap pm)
Sets the pixmap that will be used to draw scatters with drawScatter, when the style is QCP::ssPixmap.
void setAntialiasing (bool enabled)
Sets whether painting uses antialiasing or not.
void setPdfExportMode (bool enabled)
Sets whether the painter shall adjust its fixes/workarounds optimized for vectorized pdf export.
void setScaledExportMode (bool enabled)
Sets whether the painter shall adjust its fixes/workarounds optimized for scaled export to rastered image formats.
void setPen (const QPen &pen)
Sets the pen of the painter and applies certain fixes to it, depending on the mode of this QCPPainter.
void setPen (const QColor &color)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the pen (by color) of the painter and applies certain fixes to it, depending on the mode of this QCPPainter. "
void setPen (Qt::PenStyle penStyle)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the pen (by style) of the painter and applies certain fixes to it, depending on the mode of this QCPPainter. "
void drawLine (const QLineF &line)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Works around a Qt bug introduced with Qt 4.8 which makes drawing QLineF unpredictable when antialiasing is disabled. "
void drawLine (const QPointF &p1, const QPointF &p2)
void save ()
Saves the painter (see QPainter::save).
void restore ()
Restores the painter (see QPainter::restore).
void fixScaledPen ()
Provides a workaround for a QPainter bug that prevents scaling of pen widths for pens with width 0, although the QPainter::NonCosmeticDefaultPen render hint is set.
void drawScatter (double x, double y, double size, QCP::ScatterStyle style)
Draws a single scatter point with the specified style and size in pixels at the pixel position x and y.
Protected Attributes
QPixmap mScatterPixmap
bool mScaledExportMode
bool mPdfExportMode
bool mIsAntialiasing
QStack< bool > mAntialiasingStack
Detailed Description
QPainter subclass used internally.
This internal class is used to provide some extended functionality e.g. for tweaking position consistency between antialiased and non-antialiased painting and drawing common shapes (like scatter symbols). Further it provides workarounds for QPainter quirks.
Warning:
This class intentionally hides non-virtual functions of QPainter, e.g. setPen, save and restore. So while it is possible to pass a QCPPainter instance to a function that expects a QPainter pointer, some of the workarounds and tweaks will be unavailable to the function (because it will call the base class implementations of the functions actually hidden by QCPPainter).
Definition at line 203 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPPainter::QCPPainter ()
Creates a new QCPPainter instance and sets default values.
Definition at line 13110 of file qcustomplot.cpp.
                       :
  QPainter(),
  mScaledExportMode(false),
  mPdfExportMode(false),
  mIsAntialiasing(false)
{
}
QCPPainter::QCPPainter (QPaintDevice *device)
Creates a new QCPPainter instance on the specified paint device and sets default values. Just like the analogous QPainter constructor, begins painting on device immediately.
Definition at line 13122 of file qcustomplot.cpp.
                                           :
  QPainter(device),
  mScaledExportMode(false),
  mPdfExportMode(false),
  mIsAntialiasing(false)
{
}
QCPPainter::~QCPPainter ()
Definition at line 13130 of file qcustomplot.cpp.
{
}
Member Function Documentation
bool QCPPainter::antialiasing () const [inline]
Definition at line 212 of file qcustomplot.h.
{ return testRenderHint(QPainter::Antialiasing); }
void QCPPainter::drawLine (const QLineF &line)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Works around a Qt bug introduced with Qt 4.8 which makes drawing QLineF unpredictable when antialiasing is disabled.
Note:
this function hides the non-virtual base class implementation.
Definition at line 13191 of file qcustomplot.cpp.
References mIsAntialiasing.
Referenced by QCPLineEnding::draw(), QCPCurve::draw(), QCPItemStraightLine::draw(), QCPItemLine::draw(), QCPItemBracket::draw(), QCPItemTracer::draw(), QCPAxis::draw(), QCPGraph::drawError(), drawGridLines(), QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPGraph::drawLinePlot(), QCPStatisticalBox::drawMedian(), drawScatter(), drawSubGridLines(), and QCPStatisticalBox::drawWhiskers().
{
  if (mIsAntialiasing)
    QPainter::drawLine(line);
  else
    QPainter::drawLine(line.toLine());
}
void QCPPainter::drawLine (const QPointF &p1, const QPointF &p2) [inline]
Definition at line 227 of file qcustomplot.h.
References drawLine().
Referenced by drawLine().
{drawLine(QLineF(p1, p2));}
void QCPPainter::drawScatter (doublex, doubley, doublesize, QCP::ScatterStylestyle)
Draws a single scatter point with the specified style and size in pixels at the pixel position x and y. If the style is ssPixmap, make sure to pass the respective pixmap with setScatterPixmap before calling this function.
Definition at line 13300 of file qcustomplot.cpp.
References color(), drawLine(), mScatterPixmap, pen(), QCP::ssCircle, QCP::ssCross, QCP::ssCrossCircle, QCP::ssCrossSquare, QCP::ssDiamond, QCP::ssDisc, QCP::ssDot, QCP::ssNone, QCP::ssPeace, QCP::ssPixmap, QCP::ssPlus, QCP::ssPlusCircle, QCP::ssPlusSquare, QCP::ssSquare, QCP::ssStar, QCP::ssTriangle, and QCP::ssTriangleInverted.
Referenced by QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPStatisticalBox::drawOutliers(), QCPGraph::drawScatterPlot(), and QCPCurve::drawScatterPlot().
{
  double w = size/2.0;
  switch (style)
  {
    case QCP::ssNone: break;
    case QCP::ssDot:
    {
      drawPoint(QPointF(x, y));
      break;
    }
    case QCP::ssCross:
    {
      drawLine(QLineF(x-w, y-w, x+w, y+w));
      drawLine(QLineF(x-w, y+w, x+w, y-w));
      break;
    }
    case QCP::ssPlus:
    {
      drawLine(QLineF(x-w, y, x+w, y));
      drawLine(QLineF(x, y+w, x, y-w));
      break;
    }
    case QCP::ssCircle:
    {
      setBrush(Qt::NoBrush);
      drawEllipse(QPointF(x,y), w, w);
      break;
    }
    case QCP::ssDisc:
    {
      setBrush(QBrush(pen().color()));
      drawEllipse(QPointF(x,y), w, w);
      break;
    }
    case QCP::ssSquare:
    {
      setBrush(Qt::NoBrush);
      drawRect(QRectF(x-w, y-w, size, size));
      break;
    }
    case QCP::ssDiamond:
    {
      setBrush(Qt::NoBrush);
      drawLine(QLineF(x-w, y, x, y-w));
      drawLine(QLineF(x, y-w, x+w, y));
      drawLine(QLineF(x+w, y, x, y+w));
      drawLine(QLineF(x, y+w, x-w, y));
      break;
    }
    case QCP::ssStar:
    {
      drawLine(QLineF(x-w, y, x+w, y));
      drawLine(QLineF(x, y+w, x, y-w));
      drawLine(QLineF(x-w*0.707, y-w*0.707, x+w*0.707, y+w*0.707));
      drawLine(QLineF(x-w*0.707, y+w*0.707, x+w*0.707, y-w*0.707));
      break;
    }
    case QCP::ssTriangle:
    {
      drawLine(QLineF(x-w, y+0.755*w, x+w, y+0.755*w));
      drawLine(QLineF(x+w, y+0.755*w, x, y-0.977*w));
      drawLine(QLineF(x, y-0.977*w, x-w, y+0.755*w));
      break;
    }
    case QCP::ssTriangleInverted:
    {
      drawLine(QLineF(x-w, y-0.755*w, x+w, y-0.755*w));
      drawLine(QLineF(x+w, y-0.755*w, x, y+0.977*w));
      drawLine(QLineF(x, y+0.977*w, x-w, y-0.755*w));
      break;
    }
    case QCP::ssCrossSquare:
    {
      setBrush(Qt::NoBrush);
      drawLine(QLineF(x-w, y-w, x+w*0.95, y+w*0.95));
      drawLine(QLineF(x-w, y+w*0.95, x+w*0.95, y-w));
      drawRect(QRectF(x-w,y-w,size,size));
      break;
    }
    case QCP::ssPlusSquare:
    {
      setBrush(Qt::NoBrush);
      drawLine(QLineF(x-w, y, x+w*0.95, y));
      drawLine(QLineF(x, y+w, x, y-w));
      drawRect(QRectF(x-w, y-w, size, size));
      break;
    }
    case QCP::ssCrossCircle:
    {
      setBrush(Qt::NoBrush);
      drawLine(QLineF(x-w*0.707, y-w*0.707, x+w*0.67, y+w*0.67));
      drawLine(QLineF(x-w*0.707, y+w*0.67, x+w*0.67, y-w*0.707));
      drawEllipse(QPointF(x,y), w, w);
      break;
    }
    case QCP::ssPlusCircle:
    {
      setBrush(Qt::NoBrush);
      drawLine(QLineF(x-w, y, x+w, y));
      drawLine(QLineF(x, y+w, x, y-w));
      drawEllipse(QPointF(x,y), w, w);
      break;
    }
    case QCP::ssPeace:
    {
      setBrush(Qt::NoBrush);
      drawLine(QLineF(x, y-w, x, y+w));
      drawLine(QLineF(x, y, x-w*0.707, y+w*0.707));
      drawLine(QLineF(x, y, x+w*0.707, y+w*0.707));
      drawEllipse(QPointF(x,y), w, w);
      break;
    }
    case QCP::ssPixmap:
    {
      drawPixmap(x-mScatterPixmap.width()*0.5, y-mScatterPixmap.height()*0.5, mScatterPixmap);
      // if something in here is changed, adapt QCP::ssPixmap special case in drawLegendIcon(), too
      break;
    }
  }
}
void QCPPainter::fixScaledPen ()
Provides a workaround for a QPainter bug that prevents scaling of pen widths for pens with width 0, although the QPainter::NonCosmeticDefaultPen render hint is set. Changes the pen width from 0 to 1, if appropriate.
Does nothing if the QCPPainter is not in scaled export mode (setScaledExportMode).
Definition at line 13284 of file qcustomplot.cpp.
References mScaledExportMode, pen(), and setPen().
Referenced by setPen().
{
  if (mScaledExportMode && pen().isCosmetic() && qFuzzyIsNull(pen().widthF()))
  {
    QPen p = pen();
    p.setWidth(1);
    QPainter::setPen(p);
  }
}
bool QCPPainter::pdfExportMode () const [inline]
Definition at line 213 of file qcustomplot.h.
Referenced by QCPCurve::draw(), and QCPGraph::drawLinePlot().
{ return mPdfExportMode; }
void QCPPainter::restore ()
Restores the painter (see QPainter::restore). Since QCPPainter adds some new internal state to QPainter, the save/restore functions are reimplemented to also save/restore those members.
Note:
this function hides the non-virtual base class implementation.
See also:
save
Definition at line 13243 of file qcustomplot.cpp.
References mAntialiasingStack, and mIsAntialiasing.
Referenced by QCPStatisticalBox::draw(), QCPPlottableLegendItem::draw(), and QCPLegend::draw().
{
  if (!mAntialiasingStack.isEmpty())
    mIsAntialiasing = mAntialiasingStack.pop();
  else
    qDebug() << Q_FUNC_INFO << "Unbalanced save/restore";
  QPainter::restore();
}
void QCPPainter::save ()
Saves the painter (see QPainter::save). Since QCPPainter adds some new internal state to QPainter, the save/restore functions are reimplemented to also save/restore those members.
Note:
this function hides the non-virtual base class implementation.
See also:
restore
Definition at line 13229 of file qcustomplot.cpp.
References mAntialiasingStack, and mIsAntialiasing.
Referenced by QCPStatisticalBox::draw(), QCPPlottableLegendItem::draw(), and QCPLegend::draw().
{
  mAntialiasingStack.push(mIsAntialiasing);
  QPainter::save();
}
bool QCPPainter::scaledExportMode () const [inline]
Definition at line 214 of file qcustomplot.h.
{ return mScaledExportMode; }
QPixmap QCPPainter::scatterPixmap () const [inline]
Definition at line 211 of file qcustomplot.h.
{ return mScatterPixmap; }
void QCPPainter::setAntialiasing (boolenabled)
Sets whether painting uses antialiasing or not. Use this method instead of using setRenderHint with QPainter::Antialiasing directly, as it allows QCPPainter to regain pixel exactness between antialiased and non-antialiased painting (Since Qt uses slightly different coordinate systems for AA/Non-AA painting).
Definition at line 13205 of file qcustomplot.cpp.
References mIsAntialiasing, and mPdfExportMode.
Referenced by QCPLayerable::applyAntialiasingHint(), and QCPAbstractLegendItem::applyAntialiasingHint().
{
  if (mPdfExportMode)
    return;
  
  setRenderHint(QPainter::Antialiasing, enabled);
  if (mIsAntialiasing != enabled)
  {
    if (mIsAntialiasing)
      translate(-0.5, -0.5);
    else
      translate(0.5, 0.5);
    mIsAntialiasing = enabled;
  }
}
void QCPPainter::setPdfExportMode (boolenabled)
Sets whether the painter shall adjust its fixes/workarounds optimized for vectorized pdf export. This means for example, that the antialiasing/non-antialiasing fix introduced with setAntialiasing is not used, since PDF is not rastered and thus works with floating point data natively.
Definition at line 13259 of file qcustomplot.cpp.
References mPdfExportMode.
Referenced by savePdf().
{
  mPdfExportMode = enabled;
}
void QCPPainter::setPen (const QPen &pen)
Sets the pen of the painter and applies certain fixes to it, depending on the mode of this QCPPainter.
Note:
this function hides the non-virtual base class implementation.
Definition at line 13149 of file qcustomplot.cpp.
References fixScaledPen(), mScaledExportMode, and setPen().
Referenced by QCPLineEnding::draw(), QCPCurve::draw(), QCPBars::draw(), QCPItemStraightLine::draw(), QCPItemLine::draw(), QCPItemEllipse::draw(), QCPItemRect::draw(), QCPItemPixmap::draw(), QCPItemText::draw(), QCPItemCurve::draw(), QCPItemBracket::draw(), QCPItemTracer::draw(), QCPPlottableLegendItem::draw(), QCPLegend::draw(), QCPAxis::draw(), QCPGraph::drawFill(), drawGridLines(), QCPGraph::drawImpulsePlot(), QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPBars::drawLegendIcon(), QCPStatisticalBox::drawLegendIcon(), QCPGraph::drawLinePlot(), QCPStatisticalBox::drawMedian(), QCPStatisticalBox::drawOutliers(), QCPStatisticalBox::drawQuartileBox(), QCPGraph::drawScatterPlot(), QCPCurve::drawScatterPlot(), drawSubGridLines(), and QCPStatisticalBox::drawWhiskers().
{
  QPainter::setPen(pen);
  if (mScaledExportMode)
    fixScaledPen();
}
void QCPPainter::setPen (const QColor &color)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the pen (by color) of the painter and applies certain fixes to it, depending on the mode of this QCPPainter.
Note:
this function hides the non-virtual base class implementation.
Definition at line 13163 of file qcustomplot.cpp.
References fixScaledPen(), mScaledExportMode, and setPen().
{
  QPainter::setPen(color);
  if (mScaledExportMode)
    fixScaledPen();
}
void QCPPainter::setPen (Qt::PenStylepenStyle)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the pen (by style) of the painter and applies certain fixes to it, depending on the mode of this QCPPainter.
Note:
this function hides the non-virtual base class implementation.
Definition at line 13177 of file qcustomplot.cpp.
References fixScaledPen(), mScaledExportMode, and setPen().
{
  QPainter::setPen(penStyle);
  if (mScaledExportMode)
    fixScaledPen();
}
void QCPPainter::setScaledExportMode (boolenabled)
Sets whether the painter shall adjust its fixes/workarounds optimized for scaled export to rastered image formats. For example this provides a workaround for a QPainter bug that prevents scaling of pen widths for pens with width 0, although the QPainter::NonCosmeticDefaultPen render hint is set.
Definition at line 13271 of file qcustomplot.cpp.
References mScaledExportMode.
Referenced by saveRastered().
{
  mScaledExportMode = enabled;
}
void QCPPainter::setScatterPixmap (const QPixmappm)
Sets the pixmap that will be used to draw scatters with drawScatter, when the style is QCP::ssPixmap.
Definition at line 13138 of file qcustomplot.cpp.
References mScatterPixmap.
Referenced by QCPGraph::drawScatterPlot(), and QCPCurve::drawScatterPlot().
{
  mScatterPixmap = pm;
}
Member Data Documentation
QStack<bool> QCPPainter::mAntialiasingStack [protected]
Definition at line 240 of file qcustomplot.h.
Referenced by restore(), and save().
bool QCPPainter::mIsAntialiasing [protected]
Definition at line 239 of file qcustomplot.h.
Referenced by drawLine(), restore(), save(), and setAntialiasing().
bool QCPPainter::mPdfExportMode [protected]
Definition at line 238 of file qcustomplot.h.
Referenced by setAntialiasing(), and setPdfExportMode().
bool QCPPainter::mScaledExportMode [protected]
Definition at line 237 of file qcustomplot.h.
Referenced by fixScaledPen(), setPen(), and setScaledExportMode().
QPixmap QCPPainter::mScatterPixmap [protected]
Definition at line 236 of file qcustomplot.h.
Referenced by drawScatter(), and setScatterPixmap().
Author
Generated automatically by Doxygen for AQ0X from the source code.