QCPStatisticalBox
NAME
QCPStatisticalBox -
A plottable representing a single statistical box in a plot.
SYNOPSIS
#include <qcustomplot.h>
Inherits QCPAbstractPlottable.
Public Member Functions
QCPStatisticalBox (QCPAxis *keyAxis, QCPAxis *valueAxis)
Constructs a statistical box which uses keyAxis as its key axis ('x') and valueAxis as its value axis ('y').
virtual ~QCPStatisticalBox ()
double key () const
double minimum () const
double lowerQuartile () const
double median () const
double upperQuartile () const
double maximum () const
QVector< double > outliers () const
double width () const
double whiskerWidth () const
QPen whiskerPen () const
QPen whiskerBarPen () const
QPen medianPen () const
double outlierSize () const
QPen outlierPen () const
QCP::ScatterStyle outlierStyle () const
void setKey (double key)
Sets the key coordinate of the statistical box.
void setMinimum (double value)
Sets the parameter 'minimum' of the statistical box plot.
void setLowerQuartile (double value)
Sets the parameter 'lower Quartile' of the statistical box plot.
void setMedian (double value)
Sets the parameter 'median' of the statistical box plot.
void setUpperQuartile (double value)
Sets the parameter 'upper Quartile' of the statistical box plot.
void setMaximum (double value)
Sets the parameter 'maximum' of the statistical box plot.
void setOutliers (const QVector< double > &values)
Sets a vector of outlier values that will be drawn as circles.
void setData (double key, double minimum, double lowerQuartile, double median, double upperQuartile, double maximum)
Sets all parameters of the statistical box plot at once.
void setWidth (double width)
Sets the width of the box in key coordinates.
void setWhiskerWidth (double width)
Sets the width of the whiskers (setMinimum, setMaximum) in key coordinates.
void setWhiskerPen (const QPen &pen)
Sets the pen used for drawing the whisker backbone (That's the line parallel to the value axis).
void setWhiskerBarPen (const QPen &pen)
Sets the pen used for drawing the whisker bars (Those are the lines parallel to the key axis at each end of the backbone).
void setMedianPen (const QPen &pen)
Sets the pen used for drawing the median indicator line inside the statistical box.
void setOutlierSize (double pixels)
Sets the pixel size of the scatter symbols that represent the outlier data points.
void setOutlierPen (const QPen &pen)
Sets the pen used to draw the outlier data points.
void setOutlierStyle (QCP::ScatterStyle style)
Sets the scatter style of the outlier data points.
virtual void clearData ()
Clears all data in the plottable.
virtual double selectTest (const QPointF &pos) const
This function is used to decide whether a click hits a plottable or not.
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual void drawLegendIcon (QCPPainter *painter, const QRect &rect) const
virtual void drawQuartileBox (QCPPainter *painter, QRectF *quartileBox=0) const
virtual void drawMedian (QCPPainter *painter) const
virtual void drawWhiskers (QCPPainter *painter) const
virtual void drawOutliers (QCPPainter *painter) const
virtual QCPRange getKeyRange (bool &validRange, SignDomain inSignDomain=sdBoth) const
virtual QCPRange getValueRange (bool &validRange, SignDomain inSignDomain=sdBoth) const
Protected Attributes
QVector< double > mOutliers
double mKey
double mMinimum
double mLowerQuartile
double mMedian
double mUpperQuartile
double mMaximum
double mWidth
double mWhiskerWidth
double mOutlierSize
QPen mWhiskerPen
QPen mWhiskerBarPen
QPen mOutlierPen
QPen mMedianPen
QCP::ScatterStyle mOutlierStyle
Friends
class QCustomPlot
class QCPLegend
Additional Inherited Members
Detailed Description
A plottable representing a single statistical box in a plot.
To plot data, assign it with the individual parameter functions or use setData to set all parameters at once. The individual funcions are:
setMinimum
setLowerQuartile
setMedian
setUpperQuartile
setMaximum
Additionally you can define a list of outliers, drawn as circle datapoints:
setOutliers
Changing the appearance
The appearance of the box itself is controlled via setPen and setBrush. You may change the width of the box with setWidth in plot coordinates (not pixels).
Analog functions exist for the minimum/maximum-whiskers: setWhiskerPen, setWhiskerBarPen, setWhiskerWidth. The whisker width is the width of the bar at the top (maximum) or bottom (minimum).
The median indicator line has its own pen, setMedianPen.
If the pens are changed, especially the whisker pen, make sure to set the capStyle to Qt::FlatCap. Else, e.g. the whisker line might exceed the bar line by a few pixels due to the pen cap being not perfectly flat.
The Outlier data points are drawn normal scatter points. Their look can be controlled with setOutlierStyle and setOutlierPen. The size (diameter) can be set with setOutlierSize in pixels.
Usage
Like all data representing objects in QCustomPlot, the QCPStatisticalBox is a plottable (QCPAbstractPlottable). So the plottable-interface of QCustomPlot applies (QCustomPlot::plottable, QCustomPlot::addPlottable, QCustomPlot::removePlottable, etc.)
Usually, you first create an instance:
QCPStatisticalBox *newBox = new QCPStatisticalBox(customPlot->xAxis, customPlot->yAxis);
 add it to the customPlot with QCustomPlot::addPlottable:
customPlot->addPlottable(newBox);
 and then modify the properties of the newly created plottable, e.g.:
newBox->setName("Measurement Series 1");
newBox->setData(1, 3, 4, 5, 7);
newBox->setOutliers(QVector<double>() << 0.5 << 0.64 << 7.2 << 7.42);
Definition at line 700 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPStatisticalBox::QCPStatisticalBox (QCPAxis *keyAxis, QCPAxis *valueAxis) [explicit]
Constructs a statistical box which uses keyAxis as its key axis ('x') and valueAxis as its value axis ('y'). keyAxis and valueAxis must reside in the same QCustomPlot instance and not have the same orientation. If either of these restrictions is violated, a corresponding message is printed to the debug output (qDebug), the construction is not aborted, though.
The constructed statistical box can be added to the plot with QCustomPlot::addPlottable, QCustomPlot then takes ownership of the statistical box.
Definition at line 10409 of file qcustomplot.cpp.
References QCPAbstractPlottable::setBrush(), setMedianPen(), setOutlierPen(), setOutlierSize(), setOutlierStyle(), QCPAbstractPlottable::setPen(), QCPAbstractPlottable::setSelectedBrush(), QCPAbstractPlottable::setSelectedPen(), setWhiskerBarPen(), setWhiskerPen(), setWhiskerWidth(), setWidth(), and QCP::ssCircle.
                                                                         :
  QCPAbstractPlottable(keyAxis, valueAxis),
  mKey(0),
  mMinimum(0),
  mLowerQuartile(0),
  mMedian(0),
  mUpperQuartile(0),
  mMaximum(0)
{
  setOutlierStyle(QCP::ssCircle);
  setOutlierSize(5);
  setWhiskerWidth(0.2);
  setWidth(0.5);
  
  setPen(QPen(Qt::black));
  setSelectedPen(QPen(Qt::blue, 2.5));
  setMedianPen(QPen(Qt::black, 3, Qt::SolidLine, Qt::FlatCap));
  setWhiskerPen(QPen(Qt::black, 0, Qt::DashLine, Qt::FlatCap));
  setWhiskerBarPen(QPen(Qt::black));
  setOutlierPen(QPen(Qt::blue));
  setBrush(Qt::NoBrush);
  setSelectedBrush(Qt::NoBrush);
}
QCPStatisticalBox::~QCPStatisticalBox () [virtual]
Definition at line 10433 of file qcustomplot.cpp.
{
}
Member Function Documentation
void QCPStatisticalBox::clearData () [virtual]
Clears all data in the plottable.
Implements QCPAbstractPlottable.
Definition at line 10616 of file qcustomplot.cpp.
References setKey(), setLowerQuartile(), setMaximum(), setMedian(), setMinimum(), setOutliers(), and setUpperQuartile().
{
  setOutliers(QVector<double>());
  setKey(0);
  setMinimum(0);
  setLowerQuartile(0);
  setMedian(0);
  setUpperQuartile(0);
  setMaximum(0);
}
void QCPStatisticalBox::draw (QCPPainter *painter) [protected], [virtual]
Draws this plottable with the provided painter. Called by QCustomPlot::draw on all its visible plottables.
The cliprect of the provided painter is set to the axis rect of the key/value axis of this plottable (what clipRect returns), before this function is called.
Implements QCPAbstractPlottable.
Definition at line 10646 of file qcustomplot.cpp.
References drawMedian(), drawOutliers(), drawQuartileBox(), drawWhiskers(), QCPPainter::restore(), and QCPPainter::save().
{
  QRectF quartileBox;
  drawQuartileBox(painter, &quartileBox);
  
  painter->save();
  painter->setClipRect(quartileBox, Qt::IntersectClip);
  drawMedian(painter);
  painter->restore();
  
  drawWhiskers(painter);
  drawOutliers(painter);
}
void QCPStatisticalBox::drawLegendIcon (QCPPainter *painter, const QRect &rect) const [protected], [virtual]
called by QCPLegend::draw (via QCPPlottableLegendItem::draw) to create a graphical representation of this plottable inside rect, next to the plottable name.
Implements QCPAbstractPlottable.
Definition at line 10661 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::mBrush, QCPAbstractPlottable::mPen, and QCPPainter::setPen().
{
  // draw filled rect:
  applyDefaultAntialiasingHint(painter);
  painter->setPen(mPen);
  painter->setBrush(mBrush);
  QRectF r = QRectF(0, 0, rect.width()*0.67, rect.height()*0.67);
  r.moveCenter(rect.center());
  painter->drawRect(r);
}
void QCPStatisticalBox::drawMedian (QCPPainter *painter) const [protected], [virtual]
Draws the median line inside the quartile box.
Definition at line 10695 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::coordsToPixels(), QCPPainter::drawLine(), mKey, mMedian, mMedianPen, mWidth, and QCPPainter::setPen().
Referenced by draw().
{
  QLineF medianLine;
  medianLine.setP1(coordsToPixels(mKey-mWidth*0.5, mMedian));
  medianLine.setP2(coordsToPixels(mKey+mWidth*0.5, mMedian));
  applyDefaultAntialiasingHint(painter);
  painter->setPen(mMedianPen);
  painter->drawLine(medianLine);
}
void QCPStatisticalBox::drawOutliers (QCPPainter *painter) const [protected], [virtual]
Draws the outlier circles.
Definition at line 10729 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyScattersAntialiasingHint(), QCPAbstractPlottable::coordsToPixels(), QCPPainter::drawScatter(), mKey, mOutlierPen, mOutliers, mOutlierSize, mOutlierStyle, and QCPPainter::setPen().
Referenced by draw().
{
  applyScattersAntialiasingHint(painter);
  painter->setPen(mOutlierPen);
  painter->setBrush(Qt::NoBrush);
  for (int i=0; i<mOutliers.size(); ++i)
  {
    QPointF dataPoint = coordsToPixels(mKey, mOutliers.at(i));
    painter->drawScatter(dataPoint.x(), dataPoint.y(), mOutlierSize, mOutlierStyle);
  }
}
void QCPStatisticalBox::drawQuartileBox (QCPPainter *painter, QRectF *quartileBox = 0) const [protected], [virtual]
Draws the quartile box. box is an output parameter that returns the quartile box (in pixel coordinates) which is used to set the clip rect of the painter before calling drawMedian (so the median doesn't draw outside the quartile box).
Definition at line 10678 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::coordsToPixels(), QCPAbstractPlottable::mainBrush(), QCPAbstractPlottable::mainPen(), mKey, mLowerQuartile, mUpperQuartile, mWidth, and QCPPainter::setPen().
Referenced by draw().
{
  QRectF box;
  box.setTopLeft(coordsToPixels(mKey-mWidth*0.5, mUpperQuartile));
  box.setBottomRight(coordsToPixels(mKey+mWidth*0.5, mLowerQuartile));
  applyDefaultAntialiasingHint(painter);
  painter->setPen(mainPen());
  painter->setBrush(mainBrush());
  painter->drawRect(box);
  if (quartileBox)
    *quartileBox = box;
}
void QCPStatisticalBox::drawWhiskers (QCPPainter *painter) const [protected], [virtual]
Draws both whisker backbones and bars.
Definition at line 10709 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyErrorBarsAntialiasingHint(), QCPAbstractPlottable::coordsToPixels(), QCPPainter::drawLine(), mKey, mLowerQuartile, mMaximum, mMinimum, mUpperQuartile, mWhiskerBarPen, mWhiskerPen, mWhiskerWidth, and QCPPainter::setPen().
Referenced by draw().
{
  QLineF backboneMin, backboneMax, barMin, barMax;
  backboneMax.setPoints(coordsToPixels(mKey, mUpperQuartile), coordsToPixels(mKey, mMaximum));
  backboneMin.setPoints(coordsToPixels(mKey, mLowerQuartile), coordsToPixels(mKey, mMinimum));
  barMax.setPoints(coordsToPixels(mKey-mWhiskerWidth*0.5, mMaximum), coordsToPixels(mKey+mWhiskerWidth*0.5, mMaximum));
  barMin.setPoints(coordsToPixels(mKey-mWhiskerWidth*0.5, mMinimum), coordsToPixels(mKey+mWhiskerWidth*0.5, mMinimum));
  applyErrorBarsAntialiasingHint(painter);
  painter->setPen(mWhiskerPen);
  painter->drawLine(backboneMin);
  painter->drawLine(backboneMax);
  painter->setPen(mWhiskerBarPen);
  painter->drawLine(barMin);
  painter->drawLine(barMax);
}
QCPRange QCPStatisticalBox::getKeyRange (bool &validRange, SignDomaininSignDomain = sdBoth) const [protected], [virtual]
called by rescaleAxes functions to get the full data key bounds. For logarithmic plots, one can set inSignDomain to either sdNegative or sdPositive in order to restrict the returned range to that sign domain. E.g. when only negative range is wanted, set inSignDomain to sdNegative and all positive points will be ignored for range calculation. For no restriction, just set inSignDomain to sdBoth (default). validRange is an output parameter that indicates whether a proper range could be found or not. If this is false, you shouldn't use the returned range (e.g. no points in data).
See also:
rescaleAxes, getValueRange
Implements QCPAbstractPlottable.
Definition at line 10742 of file qcustomplot.cpp.
References mKey, mWidth, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, and QCPAbstractPlottable::sdPositive.
{
  validRange = mWidth > 0;
  if (inSignDomain == sdBoth)
  {
    return QCPRange(mKey-mWidth*0.5, mKey+mWidth*0.5);
  } else if (inSignDomain == sdNegative)
  {
    if (mKey+mWidth*0.5 < 0)
      return QCPRange(mKey-mWidth*0.5, mKey+mWidth*0.5);
    else if (mKey < 0)
      return QCPRange(mKey-mWidth*0.5, mKey);
    else
    {
      validRange = false;
      return QCPRange();
    }
  } else if (inSignDomain == sdPositive)
  {
    if (mKey-mWidth*0.5 > 0)
      return QCPRange(mKey-mWidth*0.5, mKey+mWidth*0.5);
    else if (mKey > 0)
      return QCPRange(mKey, mKey+mWidth*0.5);
    else
    {
      validRange = false;
      return QCPRange();
    }
  }
  validRange = false;
  return QCPRange();
}
QCPRange QCPStatisticalBox::getValueRange (bool &validRange, SignDomaininSignDomain = sdBoth) const [protected], [virtual]
called by rescaleAxes functions to get the full data value bounds. For logarithmic plots, one can set inSignDomain to either sdNegative or sdPositive in order to restrict the returned range to that sign domain. E.g. when only negative range is wanted, set inSignDomain to sdNegative and all positive points will be ignored for range calculation. For no restriction, just set inSignDomain to sdBoth (default). validRange is an output parameter that indicates whether a proper range could be found or not. If this is false, you shouldn't use the returned range (e.g. no points in data).
See also:
rescaleAxes, getKeyRange
Implements QCPAbstractPlottable.
Definition at line 10776 of file qcustomplot.cpp.
References mLowerQuartile, mMaximum, mMedian, mMinimum, mOutliers, mUpperQuartile, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, and QCPAbstractPlottable::sdPositive.
{
  if (inSignDomain == sdBoth)
  {
    double lower = qMin(mMinimum, qMin(mMedian, mLowerQuartile));
    double upper = qMax(mMaximum, qMax(mMedian, mUpperQuartile));
    for (int i=0; i<mOutliers.size(); ++i)
    {
      if (mOutliers.at(i) < lower)
        lower = mOutliers.at(i);
      if (mOutliers.at(i) > upper)
        upper = mOutliers.at(i);
    }
    validRange = upper > lower;
    return QCPRange(lower, upper);
  } else
  {
    QVector<double> values; // values that must be considered (i.e. all outliers and the five box-parameters)
    values.reserve(mOutliers.size() + 5);
    values << mMaximum << mUpperQuartile << mMedian << mLowerQuartile << mMinimum;
    values << mOutliers;
    // go through values and find the ones in legal range:
    bool haveUpper = false;
    bool haveLower = false;
    double upper = 0;
    double lower = 0;
    for (int i=0; i<values.size(); ++i)
    {
      if ((inSignDomain == sdNegative && values.at(i) < 0) ||
          (inSignDomain == sdPositive && values.at(i) > 0))
      {
        if (values.at(i) > upper || !haveUpper)
        {
          upper = values.at(i);
          haveUpper = true;
        }
        if (values.at(i) < lower || !haveLower)
        {
          lower = values.at(i);
          haveLower = true;
        }
      }
    }
    // return the bounds if we found some sensible values:
    if (haveLower && haveUpper && lower < upper)
    {
      validRange = true;
      return QCPRange(lower, upper);
    } else
    {
      validRange = false;
      return QCPRange();
    }
  }
}
double QCPStatisticalBox::key () const [inline]
Definition at line 708 of file qcustomplot.h.
Referenced by setKey().
{ return mKey; }
double QCPStatisticalBox::lowerQuartile () const [inline]
Definition at line 710 of file qcustomplot.h.
{ return mLowerQuartile; }
double QCPStatisticalBox::maximum () const [inline]
Definition at line 713 of file qcustomplot.h.
{ return mMaximum; }
double QCPStatisticalBox::median () const [inline]
Definition at line 711 of file qcustomplot.h.
{ return mMedian; }
QPen QCPStatisticalBox::medianPen () const [inline]
Definition at line 719 of file qcustomplot.h.
{ return mMedianPen; }
double QCPStatisticalBox::minimum () const [inline]
Definition at line 709 of file qcustomplot.h.
{ return mMinimum; }
QPen QCPStatisticalBox::outlierPen () const [inline]
Definition at line 721 of file qcustomplot.h.
{ return mOutlierPen; }
QVector<double> QCPStatisticalBox::outliers () const [inline]
Definition at line 714 of file qcustomplot.h.
{ return mOutliers; }
double QCPStatisticalBox::outlierSize () const [inline]
Definition at line 720 of file qcustomplot.h.
{ return mOutlierSize; }
QCP::ScatterStyle QCPStatisticalBox::outlierStyle () const [inline]
Definition at line 722 of file qcustomplot.h.
{ return mOutlierStyle; }
double QCPStatisticalBox::selectTest (const QPointF &pos) const [virtual]
This function is used to decide whether a click hits a plottable or not. pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the plottable (e.g. to the scatters/lines of a graph). If the plottable is either invisible, contains no data or the distance couldn't be determined, -1.0 is returned. setSelectable has no influence on the return value of this function.
If the plottable is represented not by single lines but by an area like QCPBars or QCPStatisticalBox, a click inside the area returns a constant value greater zero (typically 99% of the selectionTolerance of the parent QCustomPlot). If the click lies outside the area, this function returns -1.0.
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs.
See also:
setSelected, QCustomPlot::setInteractions
Implements QCPAbstractPlottable.
Definition at line 10628 of file qcustomplot.cpp.
References QCPRange::contains(), QCPAxis::coordToPixel(), mKey, QCPAbstractPlottable::mKeyAxis, mLowerQuartile, mMaximum, mMinimum, QCPLayerable::mParentPlot, mUpperQuartile, mWidth, and QCPAbstractPlottable::pixelsToCoords().
{
  double posKey, posValue;
  pixelsToCoords(pos, posKey, posValue);
  // quartile box:
  QCPRange keyRange(mKey-mWidth*0.5, mKey+mWidth*0.5);
  QCPRange valueRange(mLowerQuartile, mUpperQuartile);
  if (keyRange.contains(posKey) && valueRange.contains(posValue))
    return mParentPlot->selectionTolerance()*0.99;
  
  // min/max whiskers:
  if (QCPRange(mMinimum, mMaximum).contains(posValue))
    return qAbs(mKeyAxis->coordToPixel(mKey)-mKeyAxis->coordToPixel(posKey));
  
  return -1;
}
void QCPStatisticalBox::setData (doublekey, doubleminimum, doublelowerQuartile, doublemedian, doubleupperQuartile, doublemaximum)
Sets all parameters of the statistical box plot at once.
See also:
setKey, setMinimum, setLowerQuartile, setMedian, setUpperQuartile, setMaximum
Definition at line 10520 of file qcustomplot.cpp.
References setKey(), setLowerQuartile(), setMaximum(), setMedian(), setMinimum(), and setUpperQuartile().
{
  setKey(key);
  setMinimum(minimum);
  setLowerQuartile(lowerQuartile);
  setMedian(median);
  setUpperQuartile(upperQuartile);
  setMaximum(maximum);
}
void QCPStatisticalBox::setKey (doublekey)
Sets the key coordinate of the statistical box.
Definition at line 10440 of file qcustomplot.cpp.
References key(), and mKey.
Referenced by clearData(), and setData().
{
  mKey = key;
}
void QCPStatisticalBox::setLowerQuartile (doublevalue)
Sets the parameter 'lower Quartile' of the statistical box plot. This is the lower end of the box. The lower and the upper quartiles are the two statistical quartiles around the median of the sample, they contain 50% of the sample data.
See also:
setUpperQuartile, setPen, setBrush, setWidth
Definition at line 10463 of file qcustomplot.cpp.
References mLowerQuartile, and value.
Referenced by clearData(), and setData().
{
  mLowerQuartile = value;
}
void QCPStatisticalBox::setMaximum (doublevalue)
Sets the parameter 'maximum' of the statistical box plot. This is the position of the upper whisker, typically the maximum measurement of the sample that's not considered an outlier.
See also:
setMinimum, setWhiskerPen, setWhiskerBarPen, setWhiskerWidth
Definition at line 10498 of file qcustomplot.cpp.
References mMaximum, and value.
Referenced by clearData(), and setData().
{
  mMaximum = value;
}
void QCPStatisticalBox::setMedian (doublevalue)
Sets the parameter 'median' of the statistical box plot. This is the value of the median mark inside the quartile box. The median separates the sample data in half (50% of the sample data is below/above the median).
See also:
setMedianPen
Definition at line 10475 of file qcustomplot.cpp.
References mMedian, and value.
Referenced by clearData(), and setData().
{
  mMedian = value;
}
void QCPStatisticalBox::setMedianPen (const QPen &pen)
Sets the pen used for drawing the median indicator line inside the statistical box. Make sure to set the pen capStyle to Qt::FlatCap to prevent the median line from reaching a few pixels outside the box, when using a non-zero pen width.
Definition at line 10580 of file qcustomplot.cpp.
References mMedianPen, and QCPAbstractPlottable::pen().
Referenced by QCPStatisticalBox().
{
  mMedianPen = pen;
}
void QCPStatisticalBox::setMinimum (doublevalue)
Sets the parameter 'minimum' of the statistical box plot. This is the position of the lower whisker, typically the minimum measurement of the sample that's not considered an outlier.
See also:
setMaximum, setWhiskerPen, setWhiskerBarPen, setWhiskerWidth
Definition at line 10451 of file qcustomplot.cpp.
References mMinimum, and value.
Referenced by clearData(), and setData().
{
  mMinimum = value;
}
void QCPStatisticalBox::setOutlierPen (const QPen &pen)
Sets the pen used to draw the outlier data points.
See also:
setOutlierSize, setOutliers
Definition at line 10600 of file qcustomplot.cpp.
References mOutlierPen, and QCPAbstractPlottable::pen().
Referenced by QCPStatisticalBox().
{
  mOutlierPen = pen;
}
void QCPStatisticalBox::setOutliers (const QVector< double > &values)
Sets a vector of outlier values that will be drawn as circles. Any data points in the sample that are not within the whiskers (setMinimum, setMaximum) should be considered outliers and displayed as such.
See also:
setOutlierPen, setOutlierBrush, setOutlierSize
Definition at line 10510 of file qcustomplot.cpp.
References mOutliers.
Referenced by clearData().
{
  mOutliers = values;
}
void QCPStatisticalBox::setOutlierSize (doublepixels)
Sets the pixel size of the scatter symbols that represent the outlier data points.
See also:
setOutlierPen, setOutliers
Definition at line 10590 of file qcustomplot.cpp.
References mOutlierSize.
Referenced by QCPStatisticalBox().
{
  mOutlierSize = pixels;
}
void QCPStatisticalBox::setOutlierStyle (QCP::ScatterStylestyle)
Sets the scatter style of the outlier data points.
See also:
setOutlierSize, setOutlierPen, setOutliers
Definition at line 10610 of file qcustomplot.cpp.
References mOutlierStyle.
Referenced by QCPStatisticalBox().
{
  mOutlierStyle = style;
}
void QCPStatisticalBox::setUpperQuartile (doublevalue)
Sets the parameter 'upper Quartile' of the statistical box plot. This is the upper end of the box. The lower and the upper quartiles are the two statistical quartiles around the median of the sample, they contain 50% of the sample data.
See also:
setLowerQuartile, setPen, setBrush, setWidth
Definition at line 10487 of file qcustomplot.cpp.
References mUpperQuartile, and value.
Referenced by clearData(), and setData().
{
  mUpperQuartile = value;
}
void QCPStatisticalBox::setWhiskerBarPen (const QPen &pen)
Sets the pen used for drawing the whisker bars (Those are the lines parallel to the key axis at each end of the backbone).
See also:
setWhiskerPen
Definition at line 10569 of file qcustomplot.cpp.
References mWhiskerBarPen, and QCPAbstractPlottable::pen().
Referenced by QCPStatisticalBox().
{
  mWhiskerBarPen = pen;
}
void QCPStatisticalBox::setWhiskerPen (const QPen &pen)
Sets the pen used for drawing the whisker backbone (That's the line parallel to the value axis). Make sure to set the pen capStyle to Qt::FlatCap to prevent the backbone from reaching a few pixels past the bars, when using a non-zero pen width.
See also:
setWhiskerBarPen
Definition at line 10558 of file qcustomplot.cpp.
References mWhiskerPen, and QCPAbstractPlottable::pen().
Referenced by QCPStatisticalBox().
{
  mWhiskerPen = pen;
}
void QCPStatisticalBox::setWhiskerWidth (doublewidth)
Sets the width of the whiskers (setMinimum, setMaximum) in key coordinates.
See also:
setWidth
Definition at line 10545 of file qcustomplot.cpp.
References mWhiskerWidth, and width().
Referenced by QCPStatisticalBox().
{
  mWhiskerWidth = width;
}
void QCPStatisticalBox::setWidth (doublewidth)
Sets the width of the box in key coordinates.
See also:
setWhiskerWidth
Definition at line 10535 of file qcustomplot.cpp.
References mWidth, and width().
Referenced by QCPStatisticalBox().
{
  mWidth = width;
}
double QCPStatisticalBox::upperQuartile () const [inline]
Definition at line 712 of file qcustomplot.h.
{ return mUpperQuartile; }
QPen QCPStatisticalBox::whiskerBarPen () const [inline]
Definition at line 718 of file qcustomplot.h.
{ return mWhiskerBarPen; }
QPen QCPStatisticalBox::whiskerPen () const [inline]
Definition at line 717 of file qcustomplot.h.
{ return mWhiskerPen; }
double QCPStatisticalBox::whiskerWidth () const [inline]
Definition at line 716 of file qcustomplot.h.
{ return mWhiskerWidth; }
double QCPStatisticalBox::width () const [inline]
Definition at line 715 of file qcustomplot.h.
Referenced by setWhiskerWidth(), and setWidth().
{ return mWidth; }
Friends And Related Function Documentation
friend class QCPLegend [friend]
Definition at line 766 of file qcustomplot.h.
friend class QCustomPlot [friend]
Definition at line 765 of file qcustomplot.h.
Member Data Documentation
double QCPStatisticalBox::mKey [protected]
Definition at line 748 of file qcustomplot.h.
Referenced by drawMedian(), drawOutliers(), drawQuartileBox(), drawWhiskers(), getKeyRange(), selectTest(), and setKey().
double QCPStatisticalBox::mLowerQuartile [protected]
Definition at line 748 of file qcustomplot.h.
Referenced by drawQuartileBox(), drawWhiskers(), getValueRange(), selectTest(), and setLowerQuartile().
double QCPStatisticalBox::mMaximum [protected]
Definition at line 748 of file qcustomplot.h.
Referenced by drawWhiskers(), getValueRange(), selectTest(), and setMaximum().
double QCPStatisticalBox::mMedian [protected]
Definition at line 748 of file qcustomplot.h.
Referenced by drawMedian(), getValueRange(), and setMedian().
QPen QCPStatisticalBox::mMedianPen [protected]
Definition at line 752 of file qcustomplot.h.
Referenced by drawMedian(), and setMedianPen().
double QCPStatisticalBox::mMinimum [protected]
Definition at line 748 of file qcustomplot.h.
Referenced by drawWhiskers(), getValueRange(), selectTest(), and setMinimum().
QPen QCPStatisticalBox::mOutlierPen [protected]
Definition at line 752 of file qcustomplot.h.
Referenced by drawOutliers(), and setOutlierPen().
QVector<double> QCPStatisticalBox::mOutliers [protected]
Definition at line 747 of file qcustomplot.h.
Referenced by drawOutliers(), getValueRange(), and setOutliers().
double QCPStatisticalBox::mOutlierSize [protected]
Definition at line 751 of file qcustomplot.h.
Referenced by drawOutliers(), and setOutlierSize().
QCP::ScatterStyle QCPStatisticalBox::mOutlierStyle [protected]
Definition at line 753 of file qcustomplot.h.
Referenced by drawOutliers(), and setOutlierStyle().
double QCPStatisticalBox::mUpperQuartile [protected]
Definition at line 748 of file qcustomplot.h.
Referenced by drawQuartileBox(), drawWhiskers(), getValueRange(), selectTest(), and setUpperQuartile().
QPen QCPStatisticalBox::mWhiskerBarPen [protected]
Definition at line 752 of file qcustomplot.h.
Referenced by drawWhiskers(), and setWhiskerBarPen().
QPen QCPStatisticalBox::mWhiskerPen [protected]
Definition at line 752 of file qcustomplot.h.
Referenced by drawWhiskers(), and setWhiskerPen().
double QCPStatisticalBox::mWhiskerWidth [protected]
Definition at line 750 of file qcustomplot.h.
Referenced by drawWhiskers(), and setWhiskerWidth().
double QCPStatisticalBox::mWidth [protected]
Definition at line 749 of file qcustomplot.h.
Referenced by drawMedian(), drawQuartileBox(), getKeyRange(), selectTest(), and setWidth().
Author
Generated automatically by Doxygen for AQ0X from the source code.