qcustomplot.h
NAME
qcustomplot.h -
SYNOPSIS
#include <QObject>
#include <QWidget>
#include <QPainter>
#include <QPaintEvent>
#include <QPixmap>
#include <QVector>
#include <QString>
#include <QPrinter>
#include <QDateTime>
#include <QMultiMap>
#include <QFlags>
#include <QDebug>
#include <QVector2D>
#include <QStack>
#include <qmath.h>
#include <limits>
Classes
class QCPCurveData
Holds the data of one single data point for QCPCurve.
class QCPBarData
Holds the data of one single data point (one bar) for QCPBars.
class QCPPainter
QPainter subclass used internally.
class QCPLineEnding
Handles the different ending decorations for line-like items.
class QCPLayer
A layer that may contain objects, to control the rendering order.
class QCPLayerable
Base class for all objects that can be placed on layers.
class QCPAbstractPlottable
The abstract base class for all data representing objects in a plot.
class QCPGraph
A plottable representing a graph in a plot.
class QCPCurve
A plottable representing a parametric curve in a plot.
class QCPBars
A plottable representing a bar chart in a plot.
class QCPStatisticalBox
A plottable representing a single statistical box in a plot.
class QCPItemAnchor
An anchor of an item to which positions can be attached to.
class QCPItemPosition
Manages the position of an item.
class QCPAbstractItem
The abstract base class for all items in a plot.
class QCPItemStraightLine
A straight line that spans infinitely in both directions.
class QCPItemLine
A line from one point to another.
class QCPItemEllipse
An ellipse.
class QCPItemRect
A rectangle.
class QCPItemPixmap
An arbitrary pixmap.
class QCPItemText
A text label.
class QCPItemCurve
A curved line from one point to another.
class QCPItemBracket
A bracket for referencing/highlighting certain parts in the plot.
class QCPItemTracer
Item that sticks to QCPGraph data points.
class QCPRange
Represents the range an axis is encompassing.
class QCPAbstractLegendItem
The abstract base class for all items in a QCPLegend.
class QCPPlottableLegendItem
A legend item representing a plottable with an icon and the plottable name.
class QCPLegend
Manages a legend inside a QCustomPlot.
class QCPAxis
Manages a single axis inside a QCustomPlot.
Namespaces
 QCP
The QCP Namespace contains general enums and QFlags.
Macros
#define QCP_LIB_DECL
Typedefs
typedef QMap< double, QCPData > QCPDataMap
Container for storing QCPData items in a sorted fashion.
typedef QMapIterator< double,
QCPData > QCPDataMapIterator"
typedef QMutableMapIterator
< double, QCPData > QCPDataMutableMapIterator"
typedef QMap< double,
QCPCurveData > QCPCurveDataMap"
Container for storing QCPCurveData items in a sorted fashion.
typedef QMapIterator< double,
QCPCurveData > QCPCurveDataMapIterator"
typedef QMutableMapIterator
< double, QCPCurveData > QCPCurveDataMutableMapIterator"
typedef QMap< double, QCPBarData > QCPBarDataMap
Container for storing QCPBarData items in a sorted fashion.
typedef QMapIterator< double,
QCPBarData > QCPBarDataMapIterator"
typedef QMutableMapIterator
< double, QCPBarData > QCPBarDataMutableMapIterator"
Enumerations
enum QCP::ScatterStyle { QCP::ssNone, QCP::ssDot, QCP::ssCross, QCP::ssPlus, QCP::ssCircle, QCP::ssDisc, QCP::ssSquare, QCP::ssDiamond, QCP::ssStar, QCP::ssTriangle, QCP::ssTriangleInverted, QCP::ssCrossSquare, QCP::ssPlusSquare, QCP::ssCrossCircle, QCP::ssPlusCircle, QCP::ssPeace, QCP::ssPixmap }
Defines the symbol used for scatter points.
enum QCP::AntialiasedElement { QCP::aeAxes = 0x0001, QCP::aeGrid = 0x0002, QCP::aeSubGrid = 0x0004, QCP::aeLegend = 0x0008, QCP::aeLegendItems = 0x0010, QCP::aePlottables = 0x0020, QCP::aeItems = 0x0040, QCP::aeScatters = 0x0080, QCP::aeErrorBars = 0x0100, QCP::aeFills = 0x0200, QCP::aeZeroLine = 0x0400, QCP::aeAll = 0xFFFF, QCP::aeNone = 0x0000 }
Defines what elements of a plot can be forcibly drawn antialiased/not antialiased.
enum LayerInsertMode { limBelow, limAbove }
Defines how a layer should be inserted relative to a specified other layer.
Functions
QCP::Q_DECLARE_FLAGS (AntialiasedElements, AntialiasedElement) enum PlottingHint
Defines plotting hints that control various aspects of the quality and speed of plotting.
Q_DECLARE_OPERATORS_FOR_FLAGS(QCP::AntialiasedElements)
Q_DECLARE_OPERATORS_FOR_FLAGS(QCP QCPData (double key, double value)"
Constructs a data point with the specified key and value.
Q_DECLARE_TYPEINFO (QCPData, Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO (QCPCurveData, Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO (QCPBarData, Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO (QCPLineEnding, Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO (QCPRange, Q_MOVABLE_TYPE)
Q_DECLARE_OPERATORS_FOR_FLAGS(QCPLegend::SelectableParts)
class QCP_LIB_DECL QCPGrid ~QCPGrid ()"
bool subGridVisible () const
bool antialiasedSubGrid () const
bool antialiasedZeroLine () const
QPen pen () const
QPen subGridPen () const
QPen zeroLinePen () const
void setSubGridVisible (bool visible)
Sets whether grid lines at sub tick marks are drawn.
void setAntialiasedSubGrid (bool enabled)
void setAntialiasedZeroLine (bool enabled)
void setPen (const QPen &pen)
void setSubGridPen (const QPen &pen)
void setZeroLinePen (const QPen &pen)
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void draw (QCPPainter *painter)
void drawGridLines (QCPPainter *painter) const
void drawSubGridLines (QCPPainter *painter) const
Q_DECLARE_OPERATORS_FOR_FLAGS(QCPAxis::SelectableParts)
class QCP_LIB_DECL QCustomPlot Q_ENUMS (Interaction) Q_DECLARE_FLAGS(Interactions"
Defines the mouse interactions possible with QCustomPlot.
Q_ENUMS (LayerInsertMode) explicit QCustomPlot(QWidget *parent=0)
virtual ~QCustomPlot ()
QString title () const
QFont titleFont () const
QColor titleColor () const
QRect axisRect () const
QRect viewport () const
Returns the viewport rect of this QCustomPlot instance.
int marginLeft () const
int marginRight () const
int marginTop () const
int marginBottom () const
bool autoMargin () const
QColor color () const
Qt::Orientations rangeDrag () const
Qt::Orientations rangeZoom () const
QCPAxis * rangeDragAxis (Qt::Orientation orientation)
Returns the range drag axis of the orientation provided.
QCPAxis * rangeZoomAxis (Qt::Orientation orientation)
Returns the range zoom axis of the orientation provided.
double rangeZoomFactor (Qt::Orientation orientation)
Returns the range zoom factor of the orientation provided.
QCP::AntialiasedElements antialiasedElements () const
QCP::AntialiasedElements notAntialiasedElements () const
bool autoAddPlottableToLegend () const
QPixmap axisBackground () const
bool axisBackgroundScaled () const
Qt::AspectRatioMode axisBackgroundScaledMode () const
const Interactions interactions () const
int selectionTolerance () const
QFont selectedTitleFont () const
QColor selectedTitleColor () const
bool titleSelected () const
bool noAntialiasingOnDrag () const
QCP::PlottingHints plottingHints () const
Qt::KeyboardModifier multiSelectModifier () const
void setTitle (const QString &title)
Sets the plot title which will be drawn centered at the top of the widget.
void setTitleFont (const QFont &font)
Sets the font of the plot title.
void setTitleColor (const QColor &color)
Sets the text color of the plot title.
void setAxisRect (const QRect &arect)
void setMarginLeft (int margin)
void setMarginRight (int margin)
void setMarginTop (int margin)
void setMarginBottom (int margin)
void setMargin (int left, int right, int top, int bottom)
void setAutoMargin (bool enabled)
Sets whether the margins are calculated automatically depeding on the sizes of the tick labels, axis labels, paddings etc.
void setColor (const QColor &color)
void setRangeDrag (Qt::Orientations orientations)
Sets which axis orientation may be range dragged by the user with mouse interaction.
void setRangeZoom (Qt::Orientations orientations)
Sets which axis orientation may be zoomed by the user with the mouse wheel.
void setRangeDragAxes (QCPAxis *horizontal, QCPAxis *vertical)
Sets the axes whose range will be dragged when setRangeDrag enables mouse range dragging on the QCustomPlot widget.
void setRangeZoomAxes (QCPAxis *horizontal, QCPAxis *vertical)
Sets the axes whose range will be zoomed when setRangeZoom enables mouse wheel zooming on the QCustomPlot widget.
void setRangeZoomFactor (double horizontalFactor, double verticalFactor)
Sets how strong one rotation step of the mouse wheel zooms, when range zoom was activated with setRangeZoom.
void setRangeZoomFactor (double factor)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets both the horizontal and vertical zoom factor. "
void setAntialiasedElements (const QCP::AntialiasedElements &antialiasedElements)
Sets which elements are forcibly drawn antialiased as an or combination of QCP::AntialiasedElement.
void setAntialiasedElement (QCP::AntialiasedElement antialiasedElement, bool enabled=true)
Sets whether the specified antialiasedElement is forcibly drawn antialiased.
void setNotAntialiasedElements (const QCP::AntialiasedElements &notAntialiasedElements)
Sets which elements are forcibly drawn not antialiased as an or combination of QCP::AntialiasedElement.
void setNotAntialiasedElement (QCP::AntialiasedElement notAntialiasedElement, bool enabled=true)
Sets whether the specified notAntialiasedElement is forcibly drawn not antialiased.
void setAutoAddPlottableToLegend (bool on)
If set to true, adding a plottable (e.g.
void setAxisBackground (const QPixmap &pm)
Sets pm as the axis background pixmap.
void setAxisBackground (const QPixmap &pm, bool scaled, Qt::AspectRatioMode mode=Qt::KeepAspectRatioByExpanding)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Allows setting the background pixmap, whether it shall be scaled and how it shall be scaled in one call.
void setAxisBackgroundScaled (bool scaled)
Sets whether the axis background pixmap shall be scaled to fit the current axis rect or not.
void setAxisBackgroundScaledMode (Qt::AspectRatioMode mode)
If scaling of the axis background pixmap is enabled (setAxisBackgroundScaled), use this function to define whether and how the aspect ratio of the original pixmap passed to setAxisBackground is preserved.
void setInteractions (const Interactions &interactions)
Sets the possible interactions of this QCustomPlot as an or-combination of Interaction enums.
void setInteraction (const Interaction &interaction, bool enabled=true)
void setSelectionTolerance (int pixels)
Sets the tolerance that is used when deciding whether a click on the QCustomPlot surface selects an object (e.g.
void setSelectedTitleFont (const QFont &font)
This font is used to draw the title, when it is selected.
void setSelectedTitleColor (const QColor &color)
This color is used to draw the title, when it is selected.
void setTitleSelected (bool selected)
Sets whether the plot title is selected.
void setNoAntialiasingOnDrag (bool enabled)
Sets whether antialiasing is disabled for all elements while the user is dragging axes ranges.
void setPlottingHints (const QCP::PlottingHints &hints)
Sets the plotting hints for this QCustomPlot instance.
void setPlottingHint (QCP::PlottingHint hint, bool enabled=true)
Sets the specified plotting hint to enabled.
void setMultiSelectModifier (Qt::KeyboardModifier modifier)
Sets the keyboard modifier that will be recognized as multi-select-modifier.
QCPAbstractPlottable * plottable (int index)
QCPAbstractPlottable * plottable ()
bool addPlottable (QCPAbstractPlottable *plottable)
Adds the specified plottable to the plot and, if setAutoAddPlottableToLegend is enabled, to the legend.
bool removePlottable (QCPAbstractPlottable *plottable)
Removes the specified plottable from the plot and, if necessary, from the legend.
bool removePlottable (int index)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes the plottable by its index. "
int clearPlottables ()
Removes all plottables from the plot (and the legend, if necessary).
int plottableCount () const
Returns the number of currently existing plottables in the plot.
QList< QCPAbstractPlottable * > selectedPlottables () const
Returns a list of the selected plottables.
QCPAbstractPlottable * plottableAt (const QPointF &pos, bool onlySelectable=false) const
Returns the plottable at the pixel position pos.
bool hasPlottable (QCPAbstractPlottable *plottable) const
Returns whether this QCustomPlot instance contains the plottable.
QCPGraph * graph (int index) const
QCPGraph * graph () const
QCPGraph * addGraph (QCPAxis *keyAxis=0, QCPAxis *valueAxis=0)
Creates a new graph inside the plot.
bool removeGraph (QCPGraph *graph)
Removes the specified graph from the plot and, if necessary, from the legend.
bool removeGraph (int index)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes the graph by its index. "
int clearGraphs ()
Removes all graphs from the plot (and the legend, if necessary).
int graphCount () const
Returns the number of currently existing graphs in the plot.
QList< QCPGraph * > selectedGraphs () const
Returns a list of the selected graphs.
QCPAbstractItem * item (int index) const
QCPAbstractItem * item () const
bool addItem (QCPAbstractItem *item)
bool removeItem (QCPAbstractItem *item)
bool removeItem (int index)
int clearItems ()
int itemCount () const
QList< QCPAbstractItem * > selectedItems () const
QCPAbstractItem * itemAt (const QPointF &pos, bool onlySelectable=false) const
Returns the item at the pixel position pos.
QCPLayer * layer (const QString &name) const
QCPLayer * layer (int index) const
QCPLayer * currentLayer () const
Returns the layer that is set as current layer (see setCurrentLayer).
bool setCurrentLayer (const QString &name)
Sets the layer with the specified name to be the current layer.
bool setCurrentLayer (QCPLayer *layer)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the provided layer to be the current layer. "
int layerCount () const
Returns the number of currently existing layers in the plot.
bool addLayer (const QString &name, QCPLayer *otherLayer=0, LayerInsertMode insertMode=limAbove)
bool removeLayer (QCPLayer *layer)
Removes the specified layer and returns true on success.
bool moveLayer (QCPLayer *layer, QCPLayer *otherLayer, LayerInsertMode insertMode=limAbove)
QList< QCPAxis * > selectedAxes () const
Returns the axes that currently have selected parts, i.e.
QList< QCPLegend * > selectedLegends () const
Returns the legends (typically one or zero) that currently have selected parts, i.e.
void setupFullAxesBox ()
Convenience function to make the top and right axes visible and assign them the following properties from their corresponding bottom/left axes:
bool savePdf (const QString &fileName, bool noCosmeticPen=false, int width=0, int height=0)
Saves a PDF with the vectorized plot to the file fileName.
bool savePng (const QString &fileName, int width=0, int height=0, double scale=1.0, int quality=-1)
Saves a PNG image file to fileName on disc.
bool saveJpg (const QString &fileName, int width=0, int height=0, double scale=1.0, int quality=-1)
Saves a JPG image file to fileName on disc.
bool saveBmp (const QString &fileName, int width=0, int height=0, double scale=1.0)
Saves a BMP image file to fileName on disc.
bool saveRastered (const QString &fileName, int width, int height, double scale, const char *format, int quality=-1)
Saves the plot to a rastered image file fileName in the image format format.
void deselectAll ()
Deselects everything in the QCustomPlot (plottables, items, axes, legend and title).
void replot ()
Causes a complete replot (axes, labels, graphs, etc.) into the internal buffer.
void rescaleAxes ()
void mouseDoubleClick (QMouseEvent *event)
This signal is emitted when the QCustomPlot receives a mouse double click event.
void mousePress (QMouseEvent *event)
This signal is emitted when the QCustomPlot receives a mouse press event.
void mouseMove (QMouseEvent *event)
This signal is emitted when the QCustomPlot receives a mouse move event.
void mouseRelease (QMouseEvent *event)
This signal is emitted when the QCustomPlot receives a mouse release event.
void mouseWheel (QWheelEvent *event)
void plottableClick (QCPAbstractPlottable *plottable, QMouseEvent *event)
This signal is emitted when a plottable is clicked.
void plottableDoubleClick (QCPAbstractPlottable *plottable, QMouseEvent *event)
This signal is emitted when a plottable is double clicked.
void itemClick (QCPAbstractItem *item, QMouseEvent *event)
This signal is emitted when an item is clicked.
void itemDoubleClick (QCPAbstractItem *item, QMouseEvent *event)
This signal is emitted when an item is double clicked.
void axisClick (QCPAxis *axis, QCPAxis::SelectablePart part, QMouseEvent *event)
This signal is emitted when an axis is clicked.
void axisDoubleClick (QCPAxis *axis, QCPAxis::SelectablePart part, QMouseEvent *event)
This signal is emitted when an axis is double clicked.
void legendClick (QCPLegend *legend, QCPAbstractLegendItem *item, QMouseEvent *event)
This signal is emitted when a legend (item) is clicked.
void legendDoubleClick (QCPLegend *legend, QCPAbstractLegendItem *item, QMouseEvent *event)
This signal is emitted when a legend (item) is double clicked.
void titleClick (QMouseEvent *event)
This signal is emitted when the plot title is clicked.
void titleDoubleClick (QMouseEvent *event)
This signal is emitted when the plot title is double clicked.
void selectionChangedByUser ()
This signal is emitted after the user has changed the selection in the QCustomPlot, e.g.
void beforeReplot ()
This signal is emitted immediately before a replot takes place (caused by a call to the slot replot).
void afterReplot ()
This signal is emitted immediately after a replot has taken place (caused by a call to the slot replot).
virtual QSize minimumSizeHint () const
virtual void paintEvent (QPaintEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
virtual bool handlePlottableSelection (QMouseEvent *event, bool additiveSelection, bool &modified)
virtual bool handleItemSelection (QMouseEvent *event, bool additiveSelection, bool &modified)
virtual bool handleAxisSelection (QMouseEvent *event, bool additiveSelection, bool &modified)
virtual bool handleTitleSelection (QMouseEvent *event, bool additiveSelection, bool &modified)
virtual void drawAxisBackground (QCPPainter *painter)
void updateAxisRect ()
bool selectTestTitle (const QPointF &pos) const
Variables
double key
double value
double keyErrorPlus
double keyErrorMinus
double valueErrorPlus
double valueErrorMinus
QCPAxis * mParentAxis
bool mSubGridVisible
bool mAntialiasedSubGrid
bool mAntialiasedZeroLine
QPen mPen
QPen mSubGridPen
QPen mZeroLinePen
QCPAxis * xAxis
QCPAxis * yAxis
QCPAxis * xAxis2
QCPAxis * yAxis2
QCPLegend * legend
QString mTitle
QFont mTitleFont
QFont mSelectedTitleFont
QColor mTitleColor
QColor mSelectedTitleColor
QRect mViewport
QRect mAxisRect
int mMarginLeft
int mMarginRight
int mMarginTop
int mMarginBottom
bool mAutoMargin
bool mAutoAddPlottableToLegend
QColor mColor
QList< QCPAbstractPlottable * > mPlottables
QList< QCPGraph * > mGraphs
QList< QCPAbstractItem * > mItems
QList< QCPLayer * > mLayers
Qt::Orientations mRangeDrag
Qt::Orientations mRangeZoom
QCPAxis * mRangeDragHorzAxis
QCPAxis * mRangeDragVertAxis
QCPAxis * mRangeZoomHorzAxis
QCPAxis * mRangeZoomVertAxis
double mRangeZoomFactorHorz
double mRangeZoomFactorVert
bool mDragging
QCP::AntialiasedElements mAntialiasedElements
QCP::AntialiasedElements mNotAntialiasedElements
QPixmap mAxisBackground
bool mAxisBackgroundScaled
Qt::AspectRatioMode mAxisBackgroundScaledMode
Interactions mInteractions
int mSelectionTolerance
bool mTitleSelected
QRect mTitleBoundingBox
bool mNoAntialiasingOnDrag
QPixmap mPaintBuffer
QPoint mDragStart
QCPRange mDragStartHorzRange
QCPRange mDragStartVertRange
QPixmap mScaledAxisBackground
bool mReplotting
QCP::AntialiasedElements mAADragBackup
QCP::AntialiasedElements mNotAADragBackup
QCPLayer * mCurrentLayer
QCP::PlottingHints mPlottingHints
Qt::KeyboardModifier mMultiSelectModifier
Macro Definition Documentation
#define QCP_LIB_DECL
Definition at line 53 of file qcustomplot.h.
Typedef Documentation
QCPBarDataMap
Container for storing QCPBarData items in a sorted fashion. The key of the map is the key member of the QCPBarData instance.
This is the container in which QCPBars holds its data.
See also:
QCPBarData, QCPBars::setData
Definition at line 199 of file qcustomplot.h.
typedef QMapIterator<double, QCPBarData> QCPBarDataMapIterator
Definition at line 200 of file qcustomplot.h.
typedef QMutableMapIterator<double, QCPBarData> QCPBarDataMutableMapIterator
Definition at line 201 of file qcustomplot.h.
QCPCurveDataMap
Container for storing QCPCurveData items in a sorted fashion. The key of the map is the t member of the QCPCurveData instance.
This is the container in which QCPCurve holds its data.
See also:
QCPCurveData, QCPCurve::setData
Definition at line 179 of file qcustomplot.h.
typedef QMapIterator<double, QCPCurveData> QCPCurveDataMapIterator
Definition at line 180 of file qcustomplot.h.
typedef QMutableMapIterator<double, QCPCurveData> QCPCurveDataMutableMapIterator
Definition at line 181 of file qcustomplot.h.
QCPDataMap
Container for storing QCPData items in a sorted fashion. The key of the map is the key member of the QCPData instance.
This is the container in which QCPGraph holds its data.
See also:
QCPData, QCPGraph::setData
Definition at line 158 of file qcustomplot.h.
typedef QMapIterator<double, QCPData> QCPDataMapIterator
Definition at line 159 of file qcustomplot.h.
typedef QMutableMapIterator<double, QCPData> QCPDataMutableMapIterator
Definition at line 160 of file qcustomplot.h.
Enumeration Type Documentation
enum LayerInsertMode [protected]
Defines how a layer should be inserted relative to a specified other layer.
See also:
addLayer, moveLayer
Enumerator
limBelow
Layer is inserted below other layer.
limAbove
Layer is inserted above other layer.
Definition at line 1944 of file qcustomplot.h.
                       { limBelow
                         ,limAbove
                   };
Function Documentation
QCPGraph * QCustomPlot::addGraph (QCPAxis *keyAxis = 0, QCPAxis *valueAxis = 0) [protected]
Creates a new graph inside the plot. If keyAxis and valueAxis are left unspecified (0), the bottom (xAxis) is used as key and the left (yAxis) is used as value. If specified, keyAxis and valueAxis must reside in this QCustomPlot.
keyAxis will be used as key axis (typically 'x') and valueAxis as value axis (typically 'y') for the graph.
Returns a pointer to the newly created graph.
See also:
graph, graphCount, removeGraph, clearGraphs
Definition at line 6688 of file qcustomplot.cpp.
References addPlottable(), mGraphs, QCPLayerable::parentPlot(), QCPAbstractPlottable::setName(), xAxis, and yAxis.
{
  if (!keyAxis) keyAxis = xAxis;
  if (!valueAxis) valueAxis = yAxis;
  if (keyAxis->parentPlot() != this || valueAxis->parentPlot() != this)
  {
    qDebug() << Q_FUNC_INFO << "passed keyAxis or valueAxis doesn't have this QCustomPlot as parent";
    return 0;
  }
  
  QCPGraph *newGraph = new QCPGraph(keyAxis, valueAxis);
  if (addPlottable(newGraph))
  {
    newGraph->setName("Graph "+QString::number(mGraphs.size()));
    return newGraph;
  } else
  {
    delete newGraph;
    return 0;
  }
}
bool addItem (QCPAbstractItem *item) [protected]
bool addLayer (const QString &name, QCPLayer *otherLayer = 0, LayerInsertModeinsertMode = limAbove) [protected]
bool QCustomPlot::addPlottable (QCPAbstractPlottable *plottable) [protected]
Adds the specified plottable to the plot and, if setAutoAddPlottableToLegend is enabled, to the legend. QCustomPlot takes ownership of the plottable.
Returns true on success, i.e. when plottable wasn't already added to the plot and the parent plot of plottable is this QCustomPlot (the latter is controlled by what axes the plottable was passed in the constructor).
See also:
plottable, plottableCount, removePlottable, clearPlottables
Definition at line 6487 of file qcustomplot.cpp.
References QCPAbstractPlottable::addToLegend(), currentLayer(), graph(), QCPLayerable::layer(), mAutoAddPlottableToLegend, mGraphs, mPlottables, QCPLayerable::parentPlot(), plottable(), and QCPLayerable::setLayer().
Referenced by addGraph().
{
  if (mPlottables.contains(plottable))
  {
    qDebug() << Q_FUNC_INFO << "plottable already added to this QCustomPlot:" << reinterpret_cast<quintptr>(plottable);
    return false;
  }
  if (plottable->parentPlot() != this)
  {
    qDebug() << Q_FUNC_INFO << "plottable not created with this QCustomPlot as parent:" << reinterpret_cast<quintptr>(plottable);
    return false;
  }
  
  mPlottables.append(plottable);
  // possibly add plottable to legend:
  if (mAutoAddPlottableToLegend)
    plottable->addToLegend();
  // special handling for QCPGraphs to maintain the simple graph interface:
  if (QCPGraph *graph = qobject_cast<QCPGraph*>(plottable))
    mGraphs.append(graph);
  if (!plottable->layer()) // usually the layer is already set in the constructor of the plottable (via QCPLayerable constructor)
    plottable->setLayer(currentLayer());
  return true;
}
void QCustomPlot::afterReplot ()
This signal is emitted immediately after a replot has taken place (caused by a call to the slot replot). It is safe to mutually connect the replot slot with this signal on two QCustomPlots to make them replot synchronously (i.e. it won't cause an infinite recursion).
See also:
replot, beforeReplot
Definition at line 2581 of file moc_qcustomplot.cpp.
Referenced by replot().
{
    QMetaObject::activate(this, &staticMetaObject, 17, 0);
}
QCP::AntialiasedElements antialiasedElements () const [protected]
Definition at line 1969 of file qcustomplot.h.
References mAntialiasedElements.
Referenced by setAntialiasedElements().
{ return mAntialiasedElements; }
bool antialiasedSubGrid () const
Definition at line 1589 of file qcustomplot.h.
References mAntialiasedSubGrid.
{ return mAntialiasedSubGrid; }
bool antialiasedZeroLine () const
Definition at line 1590 of file qcustomplot.h.
References mAntialiasedZeroLine.
{ return mAntialiasedZeroLine; }
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const [protected], [virtual]
Referenced by drawGridLines().
bool autoAddPlottableToLegend () const [protected]
Definition at line 1971 of file qcustomplot.h.
References mAutoAddPlottableToLegend.
{ return mAutoAddPlottableToLegend; }
bool autoMargin () const [protected]
Definition at line 1962 of file qcustomplot.h.
References mAutoMargin.
{ return mAutoMargin; }
QPixmap axisBackground () const [protected]
Definition at line 1972 of file qcustomplot.h.
References mAxisBackground.
{ return mAxisBackground; }
bool axisBackgroundScaled () const [protected]
Definition at line 1973 of file qcustomplot.h.
References mAxisBackgroundScaled.
{ return mAxisBackgroundScaled; }
Qt::AspectRatioMode axisBackgroundScaledMode () const [protected]
Definition at line 1974 of file qcustomplot.h.
References mAxisBackgroundScaledMode.
{ return mAxisBackgroundScaledMode; }
void QCustomPlot::axisClick (QCPAxis *axis, QCPAxis::SelectablePartpart, QMouseEvent *event)
This signal is emitted when an axis is clicked. event is the mouse event that caused the click, axis is the axis that received the click and part indicates the part of the axis that was clicked.
See also:
axisDoubleClick
Definition at line 2527 of file moc_qcustomplot.cpp.
Referenced by mouseReleaseEvent().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)), const_cast<void*>(reinterpret_cast<const void*>(&_t2)), const_cast<void*>(reinterpret_cast<const void*>(&_t3)) };
    QMetaObject::activate(this, &staticMetaObject, 9, _a);
}
void QCustomPlot::axisDoubleClick (QCPAxis *axis, QCPAxis::SelectablePartpart, QMouseEvent *event)
This signal is emitted when an axis is double clicked. event is the mouse event that caused the click, axis is the axis that received the click and part indicates the part of the axis that was clicked.
See also:
axisClick
Definition at line 2534 of file moc_qcustomplot.cpp.
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)), const_cast<void*>(reinterpret_cast<const void*>(&_t2)), const_cast<void*>(reinterpret_cast<const void*>(&_t3)) };
    QMetaObject::activate(this, &staticMetaObject, 10, _a);
}
QRect axisRect () const [protected]
Definition at line 1956 of file qcustomplot.h.
References mAxisRect.
Referenced by QCPCurve::outsideCoordsToPixels().
{ return mAxisRect; }
void QCustomPlot::beforeReplot ()
This signal is emitted immediately before a replot takes place (caused by a call to the slot replot). It is safe to mutually connect the replot slot with this signal on two QCustomPlots to make them replot synchronously (i.e. it won't cause an infinite recursion).
See also:
replot, afterReplot
Definition at line 2575 of file moc_qcustomplot.cpp.
Referenced by replot().
{
    QMetaObject::activate(this, &staticMetaObject, 16, 0);
}
int QCustomPlot::clearGraphs () [protected]
Removes all graphs from the plot (and the legend, if necessary). Returns the number of graphs removed.
See also:
removeGraph
Definition at line 6741 of file qcustomplot.cpp.
References mGraphs, and removeGraph().
{
  int c = mGraphs.size();
  for (int i=c-1; i >= 0; --i)
    removeGraph(mGraphs[i]);
  return c;
}
int clearItems () [protected]
Referenced by ~QCustomPlot().
int QCustomPlot::clearPlottables () [protected]
Removes all plottables from the plot (and the legend, if necessary). Returns the number of plottables removed.
See also:
removePlottable
Definition at line 6560 of file qcustomplot.cpp.
References mPlottables, and removePlottable().
Referenced by ~QCustomPlot().
{
  int c = mPlottables.size();
  for (int i=c-1; i >= 0; --i)
    removePlottable(mPlottables[i]);
  return c;
}
QColor color () const [protected]
Definition at line 1963 of file qcustomplot.h.
References mColor.
Referenced by QCPCurve::draw(), QCPBars::draw(), QCPItemBracket::draw(), QCPGraph::drawFill(), QCPGraph::drawImpulsePlot(), QCPGraph::drawLinePlot(), QCPPainter::drawScatter(), QCPAxis::setLabelColor(), QCPAxis::setSelectedLabelColor(), QCPAbstractLegendItem::setSelectedTextColor(), QCPLegend::setSelectedTextColor(), QCPAxis::setSelectedTickLabelColor(), setSelectedTitleColor(), QCPAbstractLegendItem::setTextColor(), QCPLegend::setTextColor(), QCPAxis::setTickLabelColor(), and setTitleColor().
{ return mColor; }
QCPLayer * QCustomPlot::currentLayer () const [protected]
Returns the layer that is set as current layer (see setCurrentLayer).
Definition at line 6984 of file qcustomplot.cpp.
References mCurrentLayer.
Referenced by addPlottable().
{
  return mCurrentLayer;
}
void QCustomPlot::deselectAll ()
Deselects everything in the QCustomPlot (plottables, items, axes, legend and title). Since calling this function is not a user interaction, this does not emit the selectionChangedByUser signal. The individual selectionChanged signals are emitted though, if the objects were previously selected.
See also:
setInteractions, selectedPlottables, selectedItems, selectedAxes, selectedLegends
Definition at line 7189 of file qcustomplot.cpp.
References legend, selectedAxes(), selectedItems(), selectedPlottables(), QCPLegend::setSelected(), and setTitleSelected().
{
  // deselect plottables:
  QList<QCPAbstractPlottable*> selPlottables = selectedPlottables();
  for (int i=0; i<selPlottables.size(); ++i)
    selPlottables.at(i)->setSelected(false);
  
  // deselect items:
  QList<QCPAbstractItem*> selItems = selectedItems();
  for (int i=0; i<selItems.size(); ++i)
    selItems.at(i)->setSelected(false);
  
  // deselect axes:
  QList<QCPAxis*> selAxes = selectedAxes();
  for (int i=0; i<selAxes.size(); ++i)
    selAxes.at(i)->setSelected(QCPAxis::spNone);
  
  // deselect legend (and legend items):
  legend->setSelected(QCPLegend::spNone);
  
  // deselect title:
  setTitleSelected(false);
}
void draw (QCPPainter *painter) [protected], [virtual]
Referenced by replot(), savePdf(), and saveRastered().
void QCustomPlot::drawAxisBackground (QCPPainter *painter) [protected], [virtual]
If an axis background is provided via setAxisBackground, this function first buffers the scaled version depending on setAxisBackgroundScaled and setAxisBackgroundScaledMode and then draws it inside the current axisRect with the provided painter. The scaled version is buffered in mScaledAxisBackground to prevent the need for rescaling at every redraw. It is only updated, when the axisRect has changed in a way that requires a rescale of the background pixmap (this is dependant on the setAxisBackgroundScaledMode), or when a differend axis backgroud was set.
See also:
draw, setAxisBackground, setAxisBackgroundScaled, setAxisBackgroundScaledMode
Definition at line 8090 of file qcustomplot.cpp.
References mAxisBackground, mAxisBackgroundScaled, mAxisBackgroundScaledMode, mAxisRect, and mScaledAxisBackground.
{
  if (!mAxisBackground.isNull())
  {
    if (mAxisBackgroundScaled)
    {
      // check whether mScaledAxisBackground needs to be updated:
      QSize scaledSize(mAxisBackground.size());
      scaledSize.scale(mAxisRect.size(), mAxisBackgroundScaledMode);
      if (mScaledAxisBackground.size() != scaledSize)
        mScaledAxisBackground = mAxisBackground.scaled(mAxisRect.size(), mAxisBackgroundScaledMode, Qt::SmoothTransformation);
      painter->drawPixmap(mAxisRect.topLeft(), mScaledAxisBackground, QRect(0, 0, mAxisRect.width(), mAxisRect.height()) & mScaledAxisBackground.rect());
    } else
    {
      painter->drawPixmap(mAxisRect.topLeft(), mAxisBackground, QRect(0, 0, mAxisRect.width(), mAxisRect.height()));
    }
  }
}
void QCPGrid::drawGridLines (QCPPainter *painter) const [protected]
Draws the main grid lines and possibly a zero line with the specified painter.
This is a helper function called by draw.
Definition at line 14260 of file qcustomplot.cpp.
References QCP::aeZeroLine, applyDefaultAntialiasingHint(), QCPAxis::coordToPixel(), QCPPainter::drawLine(), QCPRange::lower, mAntialiasedZeroLine, QCPAxis::mAxisRect, QCPAxis::mHighestVisibleTick, QCPAxis::mLowestVisibleTick, mParentAxis, mPen, QCPAxis::mRange, QCPAxis::mTickVector, mZeroLinePen, QCPAxis::orientation(), QCPAxis::range(), QCPPainter::setPen(), QCPRange::size(), and QCPRange::upper.
{
  int lowTick = mParentAxis->mLowestVisibleTick;
  int highTick = mParentAxis->mHighestVisibleTick;
  double t; // helper variable, result of coordinate-to-pixel transforms
  if (mParentAxis->orientation() == Qt::Horizontal)
  {
    // draw zeroline:
    int zeroLineIndex = -1;
    if (mZeroLinePen.style() != Qt::NoPen && mParentAxis->mRange.lower < 0 && mParentAxis->mRange.upper > 0)
    {
      applyAntialiasingHint(painter, mAntialiasedZeroLine, QCP::aeZeroLine);
      painter->setPen(mZeroLinePen);
      double epsilon = mParentAxis->range().size()*1E-6; // for comparing double to zero
      for (int i=lowTick; i <= highTick; ++i)
      {
        if (qAbs(mParentAxis->mTickVector.at(i)) < epsilon)
        {
          zeroLineIndex = i;
          t = mParentAxis->coordToPixel(mParentAxis->mTickVector.at(i)); // x
          painter->drawLine(QLineF(t, mParentAxis->mAxisRect.bottom(), t, mParentAxis->mAxisRect.top()));
          break;
        }
      }
    }
    applyDefaultAntialiasingHint(painter);
    painter->setPen(mPen);
    for (int i=lowTick; i <= highTick; ++i)
    {
      if (i == zeroLineIndex) continue; // don't draw a gridline on top of the zeroline
      t = mParentAxis->coordToPixel(mParentAxis->mTickVector.at(i)); // x
      painter->drawLine(QLineF(t, mParentAxis->mAxisRect.bottom(), t, mParentAxis->mAxisRect.top()));
    }
  } else
  {
    // draw zeroline:
    int zeroLineIndex = -1;
    if (mZeroLinePen.style() != Qt::NoPen && mParentAxis->mRange.lower < 0 && mParentAxis->mRange.upper > 0)
    {
      applyAntialiasingHint(painter, mAntialiasedZeroLine, QCP::aeZeroLine);
      painter->setPen(mZeroLinePen);
      double epsilon = mParentAxis->mRange.size()*1E-6; // for comparing double to zero
      for (int i=lowTick; i <= highTick; ++i)
      {
        if (qAbs(mParentAxis->mTickVector.at(i)) < epsilon)
        {
          zeroLineIndex = i;
          t = mParentAxis->coordToPixel(mParentAxis->mTickVector.at(i)); // y
          painter->drawLine(QLineF(mParentAxis->mAxisRect.left(), t, mParentAxis->mAxisRect.right(), t));
          break;
        }
      }
    }
    // draw grid lines:
    applyDefaultAntialiasingHint(painter);
    painter->setPen(mPen);
    for (int i=lowTick; i <= highTick; ++i)
    {
      if (i == zeroLineIndex) continue; // don't draw a gridline on top of the zeroline
      t = mParentAxis->coordToPixel(mParentAxis->mTickVector.at(i)); // y
      painter->drawLine(QLineF(mParentAxis->mAxisRect.left(), t, mParentAxis->mAxisRect.right(), t));
    }
  }
}
void QCPGrid::drawSubGridLines (QCPPainter *painter) const [protected]
Draws the sub grid lines with the specified painter.
This is a helper function called by draw.
Definition at line 14331 of file qcustomplot.cpp.
References QCP::aeSubGrid, QCPAxis::coordToPixel(), QCPPainter::drawLine(), mAntialiasedSubGrid, QCPAxis::mAxisRect, mParentAxis, mSubGridPen, QCPAxis::mSubTickVector, QCPAxis::orientation(), and QCPPainter::setPen().
{
  applyAntialiasingHint(painter, mAntialiasedSubGrid, QCP::aeSubGrid);
  double t; // helper variable, result of coordinate-to-pixel transforms
  painter->setPen(mSubGridPen);
  if (mParentAxis->orientation() == Qt::Horizontal)
  {
    for (int i=0; i<mParentAxis->mSubTickVector.size(); ++i)
    {
      t = mParentAxis->coordToPixel(mParentAxis->mSubTickVector.at(i)); // x
      painter->drawLine(QLineF(t, mParentAxis->mAxisRect.bottom(), t, mParentAxis->mAxisRect.top()));
    }
  } else
  {
    for (int i=0; i<mParentAxis->mSubTickVector.size(); ++i)
    {
      t = mParentAxis->coordToPixel(mParentAxis->mSubTickVector.at(i)); // y
      painter->drawLine(QLineF(mParentAxis->mAxisRect.left(), t, mParentAxis->mAxisRect.right(), t));
    }
  }
}
QCPGraph* graph (intindex) const [protected]
Referenced by addPlottable(), and removePlottable().
QCPGraph* graph () const [protected]
int QCustomPlot::graphCount () const [protected]
Returns the number of currently existing graphs in the plot.
See also:
graph, addGraph
Definition at line 6754 of file qcustomplot.cpp.
References mGraphs.
{
  return mGraphs.size();
}
virtual bool handleAxisSelection (QMouseEvent *event, booladditiveSelection, bool &modified) [protected], [virtual]
Referenced by mouseReleaseEvent().
bool QCustomPlot::handleItemSelection (QMouseEvent *event, booladditiveSelection, bool &modified) [protected], [virtual]
Handles a mouse event for the item selection interaction. Returns true, when a selectable item was hit by the mouse event. The output variable modified is set to true when the selection state of an item has changed.
When additiveSelecton is true, any new selections become selected in addition to the recent selections. The recent selections are not cleared. Further, clicking on one object multiple times in additive selection mode, toggles the selection of that object on and off.
To indicate that all items that are selectable shall be deselected, pass 0 as event.
Unlike for axis and legend selection, this function can't be exported to the respective class itself (i.e. QCPAbstractItem). The function needs to know the distance of the mouse event to all items in the plot, in order to choose the item with the smallest distance. This wouldn't work if it were local to a single item.
Definition at line 7917 of file qcustomplot.cpp.
References itemAt(), mItems, QCPAbstractItem::selected(), and QCPAbstractItem::setSelected().
Referenced by mouseReleaseEvent().
{
  // Note: This code is basically identical to handlePlottableSelection, only for items
  
  bool selectionFound = false;
  if (event)
  {
    QCPAbstractItem *itemSelection = itemAt(event->pos(), true);
    // handle selection of found plottable:
    if (itemSelection)
    {
      selectionFound = true;
      if (!itemSelection->selected() || additiveSelection)
      {
        itemSelection->setSelected(!itemSelection->selected());
        modified = true;
      }
    }
    // deselect all others (if itemSelection is 0, all items are deselected):
    if (!additiveSelection)
    {
      for (int i=0; i<mItems.size(); ++i)
      {
        if (mItems.at(i) != itemSelection && mItems.at(i)->selected() && mItems.at(i)->selectable())
        {
          mItems.at(i)->setSelected(false);
          modified = true;
        }
      }
    }
  } else // event == 0, so deselect selectable items
  {
    for (int i=0; i<mItems.size(); ++i)
    {
      if (mItems.at(i)->selected() && mItems.at(i)->selectable())
      {
        mItems.at(i)->setSelected(false);
        modified = true;
      }
    }
  }
  return selectionFound;
}
bool QCustomPlot::handlePlottableSelection (QMouseEvent *event, booladditiveSelection, bool &modified) [protected], [virtual]
Handles a mouse event for the plottable selection interaction. Returns true, when a selectable plottable was hit by the mouse event. The output variable modified is set to true when the selection state of a plottable has changed.
When additiveSelecton is true, any new selections become selected in addition to the recent selections. The recent selections are not cleared. Further, clicking on one object multiple times in additive selection mode, toggles the selection of that object on and off.
To indicate that all plottables that are selectable shall be deselected, pass 0 as event.
Unlike for axis and legend selection, this function can't be exported to the respective class itself (i.e. QCPAbstractPlottable). The function needs to know the distance of the mouse event to all plottables in the plot, in order to choose the plottable with the smallest distance. This wouldn't work if it were local to a single plottable.
Definition at line 7856 of file qcustomplot.cpp.
References mPlottables, plottableAt(), QCPAbstractPlottable::selected(), and QCPAbstractPlottable::setSelected().
Referenced by mouseReleaseEvent().
{
  // Note: This code is basically identical to handleItemSelection, only for plottables
  
  bool selectionFound = false;
  if (event)
  {
    QCPAbstractPlottable *plottableSelection = plottableAt(event->pos(), true);
    // handle selection of found plottable:
    if (plottableSelection)
    {
      selectionFound = true;
      if (!plottableSelection->selected() || additiveSelection)
      {
        plottableSelection->setSelected(!plottableSelection->selected());
        modified = true;
      }
    }
    // deselect all others (if plottableSelection is 0, all plottables are deselected):
    if (!additiveSelection)
    {
      for (int i=0; i<mPlottables.size(); ++i)
      {
        if (mPlottables.at(i) != plottableSelection && mPlottables.at(i)->selected() && mPlottables.at(i)->selectable())
        {
          mPlottables.at(i)->setSelected(false);
          modified = true;
        }
      }
    }
  } else // event == 0, so deselect selectable plottables
  {
    for (int i=0; i<mPlottables.size(); ++i)
    {
      if (mPlottables.at(i)->selected() && mPlottables.at(i)->selectable())
      {
        mPlottables.at(i)->setSelected(false);
        modified = true;
      }
    }
  }
  return selectionFound;
}
bool QCustomPlot::handleTitleSelection (QMouseEvent *event, booladditiveSelection, bool &modified) [protected], [virtual]
Handles a mouse event for the title selection interaction. Returns true, when the title was hit by the mouse event. The output variable modified is set to true when the selection state of the title has changed.
When additiveSelecton is true, any new selections become selected in addition to the recent selections. The recent selections are not cleared. Further, clicking on one object multiple times in additive selection mode, toggles the selection of that object on and off.
To indicate that the title shall be deselected, pass 0 as event.
Definition at line 7994 of file qcustomplot.cpp.
References selectTestTitle(), setTitleSelected(), and titleSelected().
Referenced by mouseReleaseEvent().
{
  bool selectionFound = false;
  if (event && selectTestTitle(event->pos())) // hit, select title
  {
    selectionFound = true;
    if (!titleSelected() || additiveSelection)
    {
      setTitleSelected(!titleSelected());
      modified = true;
    }
  } else // no hit or event == 0, deselect title
  {
    if (titleSelected() && !additiveSelection)
    {
      setTitleSelected(false);
      modified = true;
    }
  }
  return selectionFound;
}
bool QCustomPlot::hasPlottable (QCPAbstractPlottable *plottable) const [protected]
Returns whether this QCustomPlot instance contains the plottable.
See also:
addPlottable
Definition at line 6635 of file qcustomplot.cpp.
References mPlottables.
{
  return mPlottables.contains(plottable);
}
const Interactions interactions () const [protected]
Definition at line 1975 of file qcustomplot.h.
References mInteractions.
Referenced by setInteractions().
{ return mInteractions; }
QCPAbstractItem* item (intindex) const [protected]
QCPAbstractItem* item () const [protected]
QCPAbstractItem * QCustomPlot::itemAt (const QPointF &pos, boolonlySelectable = false) const [protected]
Returns the item at the pixel position pos. Items that only consist of single lines (e.g. QCPItemLine or QCPItemCurve) have a tolerance band around them, see setSelectionTolerance. If multiple items come into consideration, the one closest to pos is returned.
If onlySelectable is true, only items that are selectable (QCPAbstractItem::setSelectable) are considered.
If there is no item at pos, the return value is 0.
Definition at line 6924 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), QCPAbstractItem::clipToAxisRect(), mItems, mSelectionTolerance, QCPAbstractItem::selectable(), and QCPAbstractItem::selectTest().
Referenced by handleItemSelection(), and mouseReleaseEvent().
{
  QCPAbstractItem *resultItem = 0;
  double resultDistance = mSelectionTolerance; // only regard clicks with distances smaller than mSelectionTolerance as selections, so initialize with that value
  
  for (int i=0; i<mItems.size(); ++i)
  {
    QCPAbstractItem *currentItem = mItems[i];
    if (onlySelectable && !currentItem->selectable())
      continue;
    if (!currentItem->clipToAxisRect() || currentItem->clipRect().contains(pos.toPoint())) // only consider clicks inside axis cliprect of the item if actually clipped to it
    {
      double currentDistance = currentItem->selectTest(pos);
      if (currentDistance >= 0 && currentDistance < resultDistance)
      {
        resultItem = currentItem;
        resultDistance = currentDistance;
      }
    }
  }
  
  return resultItem;
}
void QCustomPlot::itemClick (QCPAbstractItem *item, QMouseEvent *event)
This signal is emitted when an item is clicked. event is the mouse event that caused the click and item is the item that received the click.
See also:
itemDoubleClick
Definition at line 2513 of file moc_qcustomplot.cpp.
Referenced by mouseReleaseEvent().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)), const_cast<void*>(reinterpret_cast<const void*>(&_t2)) };
    QMetaObject::activate(this, &staticMetaObject, 7, _a);
}
int itemCount () const [protected]
void QCustomPlot::itemDoubleClick (QCPAbstractItem *item, QMouseEvent *event)
This signal is emitted when an item is double clicked. event is the mouse event that caused the click and item is the item that received the click.
See also:
itemClick
Definition at line 2520 of file moc_qcustomplot.cpp.
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)), const_cast<void*>(reinterpret_cast<const void*>(&_t2)) };
    QMetaObject::activate(this, &staticMetaObject, 8, _a);
}
QCPLayer* layer (const QString &name) const [protected]
Referenced by removeLayer(), and setCurrentLayer().
QCPLayer* layer (intindex) const [protected]
int QCustomPlot::layerCount () const [protected]
Returns the number of currently existing layers in the plot.
See also:
layer, addLayer
Definition at line 7035 of file qcustomplot.cpp.
References mLayers.
{
  return mLayers.size();
}
void QCustomPlot::legendClick (QCPLegend *legend, QCPAbstractLegendItem *item, QMouseEvent *event)
This signal is emitted when a legend (item) is clicked. event is the mouse event that caused the click, legend is the legend that received the click and item is the legend item that received the click. If only the legend and no item is clicked, item is 0 (e.g. a click inside the legend padding, which is not part of any item).
See also:
legendDoubleClick
Definition at line 2541 of file moc_qcustomplot.cpp.
Referenced by mouseReleaseEvent().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)), const_cast<void*>(reinterpret_cast<const void*>(&_t2)), const_cast<void*>(reinterpret_cast<const void*>(&_t3)) };
    QMetaObject::activate(this, &staticMetaObject, 11, _a);
}
void QCustomPlot::legendDoubleClick (QCPLegend *legend, QCPAbstractLegendItem *item, QMouseEvent *event)
This signal is emitted when a legend (item) is double clicked. event is the mouse event that caused the click, legend is the legend that received the click and item is the legend item that received the click. If only the legend and no item is clicked, item is 0 (e.g. a click inside the legend padding, which is not part of any item).
See also:
legendClick
Definition at line 2548 of file moc_qcustomplot.cpp.
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)), const_cast<void*>(reinterpret_cast<const void*>(&_t2)), const_cast<void*>(reinterpret_cast<const void*>(&_t3)) };
    QMetaObject::activate(this, &staticMetaObject, 12, _a);
}
int marginBottom () const [protected]
Definition at line 1961 of file qcustomplot.h.
References mMarginBottom.
{ return mMarginBottom; }
int marginLeft () const [protected]
Definition at line 1958 of file qcustomplot.h.
References mMarginLeft.
{ return mMarginLeft; }
int marginRight () const [protected]
Definition at line 1959 of file qcustomplot.h.
References mMarginRight.
{ return mMarginRight; }
int marginTop () const [protected]
Definition at line 1960 of file qcustomplot.h.
References mMarginTop.
{ return mMarginTop; }
QSize QCustomPlot::minimumSizeHint () const [protected], [virtual]
Returns a minimum size hint of QSize(50, 50). This prevents QCustomPlot from being collapsed to size/width zero when placed in a layout where other components try to take in as much space as possible (e.g. QMdiArea).
(To overwrite this minimum size hint of QCustomPlot, simply call QWidget::setMinimumSize in the QCustomPlot widget.)
Definition at line 7502 of file qcustomplot.cpp.
{
  return QSize(50, 50);
}
void QCustomPlot::mouseDoubleClick (QMouseEvent *event)
This signal is emitted when the QCustomPlot receives a mouse double click event.
Definition at line 2464 of file moc_qcustomplot.cpp.
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 0, _a);
}
virtual void mouseDoubleClickEvent (QMouseEvent *event) [protected], [virtual]
void QCustomPlot::mouseMove (QMouseEvent *event)
This signal is emitted when the QCustomPlot receives a mouse move event. It is emitted before the QCustomPlot handles its range dragging mechanism, so a slot connected to this signal can still influence the behaviour e.g. with setRangeDrag.
Warning:
It is discouraged to change the drag-axes with setRangeDragAxes here, because the dragging starting point was saved the moment the mouse was pressed. Thus it only has a sensible meaning for the range drag axes that were set at that moment. If you want to change the drag axes, consider doing this in the mousePress signal instead.
Definition at line 2478 of file moc_qcustomplot.cpp.
Referenced by mouseMoveEvent().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 2, _a);
}
void QCustomPlot::mouseMoveEvent (QMouseEvent *event) [protected], [virtual]
Event handler for when the cursor is moved. This is where the built-in range dragging mechanism is handled.
See also:
mousePressEvent, mouseReleaseEvent
Definition at line 7639 of file qcustomplot.cpp.
References QCP::aeAll, QCPRange::lower, mDragging, mDragStart, mDragStartHorzRange, mDragStartVertRange, mInteractions, mNoAntialiasingOnDrag, mouseMove(), mRangeDrag, mRangeDragHorzAxis, mRangeDragVertAxis, QCPAxis::mScaleType, QCPAxis::pixelToCoord(), replot(), setNotAntialiasedElements(), QCPAxis::setRange(), and QCPRange::upper.
{
  emit mouseMove(event);
  // Mouse range dragging interaction:
  if (mInteractions.testFlag(iRangeDrag))
  {
    if (mDragging)
    {
      if (mRangeDrag.testFlag(Qt::Horizontal))
      {
        if (mRangeDragHorzAxis->mScaleType == QCPAxis::stLinear)
        {
          double diff = mRangeDragHorzAxis->pixelToCoord(mDragStart.x()) - mRangeDragHorzAxis->pixelToCoord(event->pos().x());
          mRangeDragHorzAxis->setRange(mDragStartHorzRange.lower+diff, mDragStartHorzRange.upper+diff);
        } else if (mRangeDragHorzAxis->mScaleType == QCPAxis::stLogarithmic)
        {
          double diff = mRangeDragHorzAxis->pixelToCoord(mDragStart.x()) / mRangeDragHorzAxis->pixelToCoord(event->pos().x());
          mRangeDragHorzAxis->setRange(mDragStartHorzRange.lower*diff, mDragStartHorzRange.upper*diff);
        }
      }
      if (mRangeDrag.testFlag(Qt::Vertical))
      {
        if (mRangeDragVertAxis->mScaleType == QCPAxis::stLinear)
        {
          double diff = mRangeDragVertAxis->pixelToCoord(mDragStart.y()) - mRangeDragVertAxis->pixelToCoord(event->pos().y());
          mRangeDragVertAxis->setRange(mDragStartVertRange.lower+diff, mDragStartVertRange.upper+diff);
        } else if (mRangeDragVertAxis->mScaleType == QCPAxis::stLogarithmic)
        {
          double diff = mRangeDragVertAxis->pixelToCoord(mDragStart.y()) / mRangeDragVertAxis->pixelToCoord(event->pos().y());
          mRangeDragVertAxis->setRange(mDragStartVertRange.lower*diff, mDragStartVertRange.upper*diff);
        }
      }
      if (mRangeDrag != 0) // if either vertical or horizontal drag was enabled, do a replot
      {
        if (mNoAntialiasingOnDrag)
          setNotAntialiasedElements(QCP::aeAll);
        replot();
      }
    }
  }
  
  QWidget::mouseMoveEvent(event);
}
void QCustomPlot::mousePress (QMouseEvent *event)
This signal is emitted when the QCustomPlot receives a mouse press event. It is emitted before the QCustomPlot handles its range dragging mechanism, so a slot connected to this signal can still influence the behaviour e.g. with setRangeDrag or setRangeDragAxes.
Definition at line 2471 of file moc_qcustomplot.cpp.
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 1, _a);
}
virtual void mousePressEvent (QMouseEvent *event) [protected], [virtual]
Referenced by Slider::mousePressEvent().
void QCustomPlot::mouseRelease (QMouseEvent *event)
This signal is emitted when the QCustomPlot receives a mouse release event. It is emitted before the QCustomPlot handles its selection mechanism, so a slot connected to this signal can still influence the behaviour e.g. with setInteractions or QCPAbstractPlottable::setSelectable.
Definition at line 2485 of file moc_qcustomplot.cpp.
Referenced by mouseReleaseEvent().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 3, _a);
}
void QCustomPlot::mouseReleaseEvent (QMouseEvent *event) [protected], [virtual]
Event handler for when a mouse button is released. This is where the selection mechanism is handled.
See also:
mousePressEvent, mouseMoveEvent
Definition at line 7691 of file qcustomplot.cpp.
References axisClick(), handleAxisSelection(), handleItemSelection(), QCPLegend::handleLegendSelection(), handlePlottableSelection(), handleTitleSelection(), itemAt(), itemClick(), legend, legendClick(), mAADragBackup, mDragging, mDragStart, mInteractions, mMultiSelectModifier, mNoAntialiasingOnDrag, mNotAADragBackup, mouseRelease(), plottableAt(), plottableClick(), replot(), selectionChangedByUser(), QCPAxis::selectTest(), QCPLegend::selectTestItem(), QCPLegend::selectTestLegend(), selectTestTitle(), setAntialiasedElements(), setNotAntialiasedElements(), titleClick(), xAxis, xAxis2, yAxis, and yAxis2.
{
  emit mouseRelease(event);
  mDragging = false;
  bool doReplot = false;
  if (mNoAntialiasingOnDrag)
  {
    setAntialiasedElements(mAADragBackup);
    setNotAntialiasedElements(mNotAADragBackup);
    doReplot = true;
  }
  
  // determine whether it was a drag or click operation:
  if ((mDragStart-event->pos()).manhattanLength() < 5) // was a click
  {
    // Mouse selection interaction:
    if ((mInteractions & (iSelectPlottables|iSelectItems|iSelectAxes|iSelectLegend|iSelectTitle)) > 0
        && event->button() == Qt::LeftButton)
    {
      bool selectionFound = false;
      bool emitChangedSignal = false;
      bool additiveSelection = mInteractions.testFlag(iMultiSelect) && event->modifiers().testFlag(mMultiSelectModifier);
      // Mouse selection of legend:
      if (mInteractions.testFlag(iSelectLegend))
        selectionFound |= legend->handleLegendSelection(event, additiveSelection, emitChangedSignal);
      // Mouse selection of plottables:
      if (mInteractions.testFlag(iSelectPlottables))
        selectionFound |= handlePlottableSelection((!selectionFound || additiveSelection) ? event : 0, additiveSelection, emitChangedSignal);
      // Mouse selection of items:
      if (mInteractions.testFlag(iSelectItems))
        selectionFound |= handleItemSelection((!selectionFound || additiveSelection) ? event : 0, additiveSelection, emitChangedSignal);
      // Mouse selection of axes:
      if (mInteractions.testFlag(iSelectAxes))
        selectionFound |= handleAxisSelection((!selectionFound || additiveSelection) ? event : 0, additiveSelection, emitChangedSignal);
      // Mouse selection of title:
      if (mInteractions.testFlag(iSelectTitle))
        selectionFound |= handleTitleSelection((!selectionFound || additiveSelection) ? event : 0, additiveSelection, emitChangedSignal);
      
      if (emitChangedSignal)
        emit selectionChangedByUser();
      doReplot = true;
    }
    
    // emit specialized object click signals:
    bool foundHit = false;
    // for legend:
    if (receivers(SIGNAL(legendClick(QCPLegend*,QCPAbstractLegendItem*,QMouseEvent*))) > 0)
    {
      if (legend->selectTestLegend(event->pos()))
      {
        emit legendClick(legend, legend->selectTestItem(event->pos()), event);
        foundHit = true;
      }
    }
    // for plottables:
    if (!foundHit && receivers(SIGNAL(plottableClick(QCPAbstractPlottable*,QMouseEvent*))) > 0)
    {
      if (QCPAbstractPlottable *ap = plottableAt(event->pos(), false))
      {
        emit plottableClick(ap, event);
        foundHit = true;
      }
    }
    // for items:
    if (!foundHit && receivers(SIGNAL(itemClick(QCPAbstractItem*,QMouseEvent*))) > 0)
    {
      if (QCPAbstractItem *ai = itemAt(event->pos(), false))
      {
        emit itemClick(ai, event);
        foundHit = true;
      }
    }
    // for axes:
    if (!foundHit && receivers(SIGNAL(axisClick(QCPAxis*,QCPAxis::SelectablePart,QMouseEvent*))) > 0)
    {
      QVector<QCPAxis*> axes = QVector<QCPAxis*>() << xAxis << yAxis << xAxis2 << yAxis2;
      for (int i=0; i<axes.size(); ++i)
      {
        QCPAxis::SelectablePart part = axes.at(i)->selectTest(event->pos());
        if (part != QCPAxis::spNone)
        {
          foundHit = true;
          emit axisClick(axes.at(i), part, event);
          break;
        }
      }
    }
    // for title:
    if (!foundHit && receivers(SIGNAL(titleClick(QMouseEvent*))) > 0)
    {
      if (selectTestTitle(event->pos()))
      {
        emit titleClick(event);
        foundHit = true;
      }
    }
  } // was a click end
  
  if (doReplot)
    replot();
  
  QWidget::mouseReleaseEvent(event);
}
void QCustomPlot::mouseWheel (QWheelEvent *event)
Definition at line 2492 of file moc_qcustomplot.cpp.
Referenced by wheelEvent().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 4, _a);
}
bool moveLayer (QCPLayer *layer, QCPLayer *otherLayer, LayerInsertModeinsertMode = limAbove) [protected]
Qt::KeyboardModifier multiSelectModifier () const [protected]
Definition at line 1982 of file qcustomplot.h.
References mMultiSelectModifier.
{ return mMultiSelectModifier; }
bool noAntialiasingOnDrag () const [protected]
Definition at line 1980 of file qcustomplot.h.
References mNoAntialiasingOnDrag.
{ return mNoAntialiasingOnDrag; }
QCP::AntialiasedElements notAntialiasedElements () const [protected]
Definition at line 1970 of file qcustomplot.h.
References mNotAntialiasedElements.
Referenced by setNotAntialiasedElements().
{ return mNotAntialiasedElements; }
void QCustomPlot::paintEvent (QPaintEvent *event) [protected], [virtual]
Event handler for when the QCustomPlot widget needs repainting. This does not cause a replot, but draws the internal buffer on the widget surface.
Definition at line 7512 of file qcustomplot.cpp.
References mPaintBuffer.
{
  Q_UNUSED(event);
  QPainter painter(this);
  painter.drawPixmap(0, 0, mPaintBuffer);
}
QPen pen () const
Definition at line 1591 of file qcustomplot.h.
References mPen.
Referenced by QCPPainter::drawScatter(), QCPPainter::fixScaledPen(), QCPAxis::setBasePen(), QCPLegend::setBorderPen(), QCPLegend::setIconBorderPen(), QCPAxis::setSelectedBasePen(), QCPLegend::setSelectedBorderPen(), QCPLegend::setSelectedIconBorderPen(), QCPAxis::setSelectedSubTickPen(), QCPAxis::setSelectedTickPen(), QCPAxis::setSubTickPen(), and QCPAxis::setTickPen().
{ return mPen; }
QCPAbstractPlottable* plottable (intindex) [protected]
Referenced by addPlottable(), QCPLegend::itemWithPlottable(), and removePlottable().
QCPAbstractPlottable* plottable () [protected]
QCPAbstractPlottable * QCustomPlot::plottableAt (const QPointF &pos, boolonlySelectable = false) const [protected]
Returns the plottable at the pixel position pos. Plottables that only consist of single lines (e.g. graphs) have a tolerance band around them, see setSelectionTolerance. If multiple plottables come into consideration, the one closest to pos is returned.
If onlySelectable is true, only plottables that are selectable (QCPAbstractPlottable::setSelectable) are considered.
If there is no plottable at pos, the return value is 0.
Definition at line 6606 of file qcustomplot.cpp.
References QCPAxis::axisRect(), QCPAbstractPlottable::keyAxis(), mPlottables, mSelectionTolerance, QCPAbstractPlottable::selectable(), QCPAbstractPlottable::selectTest(), and QCPAbstractPlottable::valueAxis().
Referenced by handlePlottableSelection(), and mouseReleaseEvent().
{
  QCPAbstractPlottable *resultPlottable = 0;
  double resultDistance = mSelectionTolerance; // only regard clicks with distances smaller than mSelectionTolerance as selections, so initialize with that value
  
  for (int i=0; i<mPlottables.size(); ++i)
  {
    QCPAbstractPlottable *currentPlottable = mPlottables[i];
    if (onlySelectable && !currentPlottable->selectable())
      continue;
    if ((currentPlottable->keyAxis()->axisRect() | currentPlottable->valueAxis()->axisRect()).contains(pos.toPoint())) // only consider clicks inside the rect that is spanned by the plottable's key/value axes
    {
      double currentDistance = currentPlottable->selectTest(pos);
      if (currentDistance >= 0 && currentDistance < resultDistance)
      {
        resultPlottable = currentPlottable;
        resultDistance = currentDistance;
      }
    }
  }
  
  return resultPlottable;
}
void QCustomPlot::plottableClick (QCPAbstractPlottable *plottable, QMouseEvent *event)
This signal is emitted when a plottable is clicked. event is the mouse event that caused the click and plottable is the plottable that received the click.
See also:
plottableDoubleClick
Definition at line 2499 of file moc_qcustomplot.cpp.
Referenced by mouseReleaseEvent().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)), const_cast<void*>(reinterpret_cast<const void*>(&_t2)) };
    QMetaObject::activate(this, &staticMetaObject, 5, _a);
}
int QCustomPlot::plottableCount () const [protected]
Returns the number of currently existing plottables in the plot.
See also:
plottable, addPlottable
Definition at line 6573 of file qcustomplot.cpp.
References mPlottables.
{
  return mPlottables.size();
}
void QCustomPlot::plottableDoubleClick (QCPAbstractPlottable *plottable, QMouseEvent *event)
This signal is emitted when a plottable is double clicked. event is the mouse event that caused the click and plottable is the plottable that received the click.
See also:
plottableClick
Definition at line 2506 of file moc_qcustomplot.cpp.
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)), const_cast<void*>(reinterpret_cast<const void*>(&_t2)) };
    QMetaObject::activate(this, &staticMetaObject, 6, _a);
}
QCP::PlottingHints plottingHints () const [protected]
Definition at line 1981 of file qcustomplot.h.
References mPlottingHints.
{ return mPlottingHints; }
Q_DECLARE_TYPEINFO (QCPData, Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO (QCPCurveData, Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO (QCPBarData, Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO (QCPLineEnding, Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO (QCPRange, Q_MOVABLE_TYPE)
Q_DECLARE_OPERATORS_FOR_FLAGS (QCPAxis::SelectableParts) class QCP_LIB_DECL QCustomPlot Q_ENUMS (Interaction) [protected]
Defines the mouse interactions possible with QCustomPlot. Interactions is a flag of or-combined elements of this enum type.
See also:
setInteractions, setInteraction
Q_ENUMS (LayerInsertMode) [protected], [pure virtual]
QCPData::QCPData (doublekey, doublevalue)
Constructs a data point with the specified key and value. All errors are set to zero.
Definition at line 213 of file qcustomplot.cpp.
                                         :
  key(key),
  value(value),
  keyErrorPlus(0),
  keyErrorMinus(0),
  valueErrorPlus(0),
  valueErrorMinus(0)
{
}
Qt::Orientations rangeDrag () const [protected]
Definition at line 1964 of file qcustomplot.h.
References mRangeDrag.
{ return mRangeDrag; }
QCPAxis * QCustomPlot::rangeDragAxis (Qt::Orientationorientation) [protected]
Returns the range drag axis of the orientation provided.
See also:
setRangeDragAxes
Definition at line 5853 of file qcustomplot.cpp.
References mRangeDragHorzAxis, and mRangeDragVertAxis.
{
  return (orientation == Qt::Horizontal ? mRangeDragHorzAxis : mRangeDragVertAxis);
}
Qt::Orientations rangeZoom () const [protected]
Definition at line 1965 of file qcustomplot.h.
References mRangeZoom.
{ return mRangeZoom; }
QCPAxis * QCustomPlot::rangeZoomAxis (Qt::Orientationorientation) [protected]
Returns the range zoom axis of the orientation provided.
See also:
setRangeZoomAxes
Definition at line 5862 of file qcustomplot.cpp.
References mRangeZoomHorzAxis, and mRangeZoomVertAxis.
{
  return (orientation == Qt::Horizontal ? mRangeZoomHorzAxis : mRangeZoomVertAxis);
}
double QCustomPlot::rangeZoomFactor (Qt::Orientationorientation) [protected]
Returns the range zoom factor of the orientation provided.
See also:
setRangeZoomFactor
Definition at line 5871 of file qcustomplot.cpp.
References mRangeZoomFactorHorz, and mRangeZoomFactorVert.
{
  return (orientation == Qt::Horizontal ? mRangeZoomFactorHorz : mRangeZoomFactorVert);
}
bool QCustomPlot::removeGraph (QCPGraph *graph) [protected]
Removes the specified graph from the plot and, if necessary, from the legend. If any other graphs in the plot have a channel fill set towards the removed graph, the channel fill property of those graphs is reset to zero (no channel fill).
Returns true on success.
See also:
clearGraphs
Definition at line 6719 of file qcustomplot.cpp.
References removePlottable().
Referenced by clearGraphs(), and removeGraph().
{
  return removePlottable(graph);
}
bool QCustomPlot::removeGraph (intindex) [protected]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes the graph by its index.
Definition at line 6728 of file qcustomplot.cpp.
References mGraphs, and removeGraph().
{
  if (index >= 0 && index < mGraphs.size())
    return removeGraph(mGraphs[index]);
  else
    return false;
}
bool removeItem (QCPAbstractItem *item) [protected]
bool removeItem (intindex) [protected]
bool QCustomPlot::removeLayer (QCPLayer *layer) [protected]
Removes the specified layer and returns true on success. All layerables (e.g. plottables and items) on the removed layer will be moved to the layer below layer. If layer is the bottom layer, the layerables are moved to the layer above. In both cases, the total rendering order of all layerables in the QCustomPlot is preserved.
If layer is the current layer (setCurrentLayer), the layer below (or above, if bottom layer) becomes the new current layer.
Note that it is not possible to remove the last layer.
See also:
layer, addLayer, moveLayer
Definition at line 7087 of file qcustomplot.cpp.
References QCPLayer::children(), QCPLayer::index(), layer(), mCurrentLayer, mLayers, and setCurrentLayer().
{
  if (!mLayers.contains(layer))
  {
    qDebug() << Q_FUNC_INFO << "layer not a layer of this QCustomPlot:" << reinterpret_cast<quintptr>(layer);
    return false;
  }
  if (!mLayers.size() > 1)
  {
    qDebug() << Q_FUNC_INFO << "can't remove last layer";
    return false;
  }
  
  // append all children of this layer to layer below (if this is lowest layer, prepend to layer above)
  int removedIndex = layer->index();
  bool isFirstLayer = removedIndex==0;
  QCPLayer *targetLayer = isFirstLayer ? mLayers.at(removedIndex+1) : mLayers.at(removedIndex-1);
  QList<QCPLayerable*> children = layer->children();
  if (isFirstLayer) // prepend in reverse order (so order relative to each other stays the same)
  {
    for (int i=children.size()-1; i>=0; --i)
      children.at(i)->moveToLayer(targetLayer, true);
  } else // append normally
  {
    for (int i=0; i<children.size(); ++i)
      children.at(i)->moveToLayer(targetLayer, false);
  }
  // if removed layer is current layer, change current layer to layer below/above:
  if (layer == mCurrentLayer)
    setCurrentLayer(targetLayer);
  // remove layer:
  delete layer;
  mLayers.removeOne(layer);
  return true;
}
bool QCustomPlot::removePlottable (QCPAbstractPlottable *plottable) [protected]
Removes the specified plottable from the plot and, if necessary, from the legend. Returns true on success.
See also:
addPlottable, clearPlottables
Definition at line 6519 of file qcustomplot.cpp.
References graph(), mGraphs, mPlottables, plottable(), and QCPAbstractPlottable::removeFromLegend().
Referenced by clearPlottables(), removeGraph(), and removePlottable().
{
  if (!mPlottables.contains(plottable))
  {
    qDebug() << Q_FUNC_INFO << "plottable not in list:" << reinterpret_cast<quintptr>(plottable);
    return false;
  }
  
  // remove plottable from legend:
  plottable->removeFromLegend();
  // special handling for QCPGraphs to maintain the simple graph interface:
  if (QCPGraph *graph = qobject_cast<QCPGraph*>(plottable))
    mGraphs.removeOne(graph);
  // remove plottable:
  delete plottable;
  mPlottables.removeOne(plottable);
  return true;
}
bool QCustomPlot::removePlottable (intindex) [protected]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes the plottable by its index.
Definition at line 6542 of file qcustomplot.cpp.
References mPlottables, and removePlottable().
{
  if (index >= 0 && index < mPlottables.size())
    return removePlottable(mPlottables[index]);
  else
  {
    qDebug() << Q_FUNC_INFO << "index out of bounds:" << index;
    return false;
  }
}
void QCustomPlot::replot ()
Causes a complete replot (axes, labels, graphs, etc.) into the internal buffer. Finally, update() is called, to redraw the buffer on the QCustomPlot widget surface.
Before the replot happens, the signal beforeReplot is emitted. After the replot, afterReplot is emitted. It is safe to mutually connect the replot slot with any of those two signals on two QCustomPlots to make them replot synchronously (i.e. it won't cause an infinite recursion).
Definition at line 7221 of file qcustomplot.cpp.
References afterReplot(), beforeReplot(), draw(), mColor, mPaintBuffer, mPlottingHints, and mReplotting.
Referenced by mouseMoveEvent(), mouseReleaseEvent(), resizeEvent(), and wheelEvent().
{
  if (mReplotting) // incase signals loop back to replot slot
    return;
  mReplotting = true;
  emit beforeReplot();
  mPaintBuffer.fill(mColor);
  QCPPainter painter;
  painter.begin(&mPaintBuffer);
  if (painter.isActive())
  {
    painter.setRenderHint(QPainter::HighQualityAntialiasing);
    draw(&painter);
    if (mPlottingHints.testFlag(QCP::phForceRepaint))
      repaint();
    else
      update();
    painter.end();
  } else // might happen if QCustomPlot has width or height zero
    qDebug() << Q_FUNC_INFO << "Couldn't activate painter on buffer";
  emit afterReplot();
  mReplotting = false;
}
void rescaleAxes ()
void QCustomPlot::resizeEvent (QResizeEvent *event) [protected], [virtual]
Event handler for a resize of the QCustomPlot widget. Causes the internal buffer to be resized to the new size. The viewport and the axis rect are resized appropriately. Finally a replot is performed.
Definition at line 7525 of file qcustomplot.cpp.
References mPaintBuffer, mViewport, replot(), and updateAxisRect().
{
  // resize and repaint the buffer:
  mPaintBuffer = QPixmap(event->size());
  mViewport = rect();
  updateAxisRect();
  replot();
}
bool QCustomPlot::saveBmp (const QString &fileName, intwidth = 0, intheight = 0, doublescale = 1.0) [protected]
Saves a BMP image file to fileName on disc. The output plot will have the dimensions width and height in pixels. If either width or height is zero, the exported image will have the same dimensions as the QCustomPlot widget currently has. Line widths and texts etc. are not scaled up when larger widths/heights are used. If you want that effect, use the scale parameter.
For example, if you set both width and height to 100 and scale to 2, you will end up with an image file of size 200*200 in which all graphical elements are scaled up by factor 2 (line widths, texts, etc.). This scaling is not done by stretching a 100*100 image, the result will have full 200*200 pixel resolution.
Warning:
If calling this function inside the constructor of the parent of the QCustomPlot widget (i.e. the MainWindow constructor, if QCustomPlot is inside the MainWindow), always provide explicit non-zero widths and heights. If you leave width or height as 0 (default), this function uses the current width and height of the QCustomPlot widget. However, in Qt, these aren't defined yet inside the constructor, so you would get an image that has strange widths/heights.
The objects of the plot will appear in the current selection state. If you don't want any selected objects to be painted in their selected look, deselect everything with deselectAll before calling this function.
Returns true on success. If this function fails, most likely the BMP format isn't supported by the system, see Qt docs about QImageWriter::supportedImageFormats().
See also:
savePdf, savePng, saveJpg, saveRastered
Definition at line 7488 of file qcustomplot.cpp.
References saveRastered().
{
  return saveRastered(fileName, width, height, scale, "BMP");
}
bool QCustomPlot::saveJpg (const QString &fileName, intwidth = 0, intheight = 0, doublescale = 1.0, intquality = -1) [protected]
Saves a JPG image file to fileName on disc. The output plot will have the dimensions width and height in pixels. If either width or height is zero, the exported image will have the same dimensions as the QCustomPlot widget currently has. Line widths and texts etc. are not scaled up when larger widths/heights are used. If you want that effect, use the scale parameter.
For example, if you set both width and height to 100 and scale to 2, you will end up with an image file of size 200*200 in which all graphical elements are scaled up by factor 2 (line widths, texts, etc.). This scaling is not done by stretching a 100*100 image, the result will have full 200*200 pixel resolution.
Warning:
If calling this function inside the constructor of the parent of the QCustomPlot widget (i.e. the MainWindow constructor, if QCustomPlot is inside the MainWindow), always provide explicit non-zero widths and heights. If you leave width or height as 0 (default), this function uses the current width and height of the QCustomPlot widget. However, in Qt, these aren't defined yet inside the constructor, so you would get an image that has strange widths/heights.
The objects of the plot will appear in the current selection state. If you don't want any selected objects to be painted in their selected look, deselect everything with deselectAll before calling this function.
JPG compression can be controlled with the quality parameter which must be between 0 and 100 or -1 to use the default setting.
Returns true on success. If this function fails, most likely the JPG format isn't supported by the system, see Qt docs about QImageWriter::supportedImageFormats().
See also:
savePdf, savePng, saveBmp, saveRastered
Definition at line 7456 of file qcustomplot.cpp.
References saveRastered().
{
  return saveRastered(fileName, width, height, scale, "JPG", quality);
}
bool QCustomPlot::savePdf (const QString &fileName, boolnoCosmeticPen = false, intwidth = 0, intheight = 0) [protected]
Saves a PDF with the vectorized plot to the file fileName. The axis ratio as well as the scale of texts and lines will be derived from the specified width and height. This means, the output will look like the normal on-screen output of a QCustomPlot widget with the corresponding pixel width and height. If either width or height is zero, the exported image will have the same dimensions as the QCustomPlot widget currently has.
noCosmeticPen disables the use of cosmetic pens when drawing to the PDF file. Cosmetic pens are pens with numerical width 0, which are always drawn as a one pixel wide line, no matter what zoom factor is set in the PDF-Viewer. For more information about cosmetic pens, see QPainter and QPen documentation.
The objects of the plot will appear in the current selection state. So when you don't want e.g. selected axes to be painted in their selected look, deselect everything with deselectAll before calling this function.
Returns true on success.
Warning:
If you plan on editing the exported PDF file with a vector graphics editor like Inkscape, it is advised to set noCosmeticPen to true to avoid losing those cosmetic lines (which might be quite many, because cosmetic pens are the default for e.g. axes and tick marks).
If calling this function inside the constructor of the parent of the QCustomPlot widget (i.e. the MainWindow constructor, if QCustomPlot is inside the MainWindow), always provide explicit non-zero widths and heights. If you leave width or height as 0 (default), this function uses the current width and height of the QCustomPlot widget. However, in Qt, these aren't defined yet inside the constructor, so you would get an image that has strange widths/heights.
See also:
savePng, saveBmp, saveJpg, saveRastered
Definition at line 7350 of file qcustomplot.cpp.
References draw(), mColor, mViewport, QCPPainter::setPdfExportMode(), and updateAxisRect().
{
  bool success = false;
  int newWidth, newHeight;
  if (width == 0 || height == 0)
  {
    newWidth = this->width();
    newHeight = this->height();
  } else
  {
    newWidth = width;
    newHeight = height;
  }
  
  QPrinter printer(QPrinter::ScreenResolution);
  printer.setOutputFileName(fileName);
  printer.setFullPage(true);
  QRect oldViewport = mViewport;
  mViewport = QRect(0, 0, newWidth, newHeight);
  updateAxisRect();
  printer.setPaperSize(mViewport.size(), QPrinter::DevicePixel);
  QCPPainter printpainter;
  if (printpainter.begin(&printer))
  {
    printpainter.setPdfExportMode(true);
    printpainter.setWindow(mViewport);
    printpainter.setRenderHint(QPainter::NonCosmeticDefaultPen, noCosmeticPen);
    if (mColor != Qt::white && mColor != Qt::transparent && mColor.alpha() > 0) // draw pdf background color if not white/transparent
      printpainter.fillRect(mViewport, mColor);
    draw(&printpainter);
    printpainter.end();
    success = true;
  }
  mViewport = oldViewport;
  updateAxisRect();
  return success;
}
bool QCustomPlot::savePng (const QString &fileName, intwidth = 0, intheight = 0, doublescale = 1.0, intquality = -1) [protected]
Saves a PNG image file to fileName on disc. The output plot will have the dimensions width and height in pixels. If either width or height is zero, the exported image will have the same dimensions as the QCustomPlot widget currently has. Line widths and texts etc. are not scaled up when larger widths/heights are used. If you want that effect, use the scale parameter.
For example, if you set both width and height to 100 and scale to 2, you will end up with an image file of size 200*200 in which all graphical elements are scaled up by factor 2 (line widths, texts, etc.). This scaling is not done by stretching a 100*100 image, the result will have full 200*200 pixel resolution.
Warning:
If calling this function inside the constructor of the parent of the QCustomPlot widget (i.e. the MainWindow constructor, if QCustomPlot is inside the MainWindow), always provide explicit non-zero widths and heights. If you leave width or height as 0 (default), this function uses the current width and height of the QCustomPlot widget. However, in Qt, these aren't defined yet inside the constructor, so you would get an image that has strange widths/heights.
The objects of the plot will appear in the current selection state. If you don't want any selected objects to be painted in their selected look, deselect everything with deselectAll before calling this function.
If you want the plot to be painted in a PNG with transparent background, call setColor with a transparent color, e.g. Qt::transparent, before saving.
PNG compression can be controlled with the quality parameter which must be between 0 and 100 or -1 to use the default setting.
Returns true on success. If this function fails, most likely the PNG format isn't supported by the system, see Qt docs about QImageWriter::supportedImageFormats().
See also:
savePdf, saveBmp, saveJpg, saveRastered
Definition at line 7421 of file qcustomplot.cpp.
References saveRastered().
{
  return saveRastered(fileName, width, height, scale, "PNG", quality);
}
bool QCustomPlot::saveRastered (const QString &fileName, intwidth, intheight, doublescale, const char *format, intquality = -1) [protected]
Saves the plot to a rastered image file fileName in the image format format. The plot is sized to width and height in pixels and scaled with scale. (width 100 and scale 2.0 lead to a full resolution file with width 200) If the format supports compression, quality may be between 0 and 100 to control it.
Returns true on success. If this function fails, most likely the given format isn't supported by the system, see Qt docs about QImageWriter::supportedImageFormats().
See also:
saveBmp, saveJpg, savePng
Definition at line 8146 of file qcustomplot.cpp.
References draw(), mColor, mViewport, QCPPainter::setScaledExportMode(), and updateAxisRect().
Referenced by saveBmp(), saveJpg(), and savePng().
{
  int newWidth, newHeight;
  if (width == 0 || height == 0)
  {
    newWidth = this->width();
    newHeight = this->height();
  } else
  {
    newWidth = width;
    newHeight = height;
  }
  int scaledWidth = qRound(scale*newWidth);
  int scaledHeight = qRound(scale*newHeight);
  QPixmap pngBuffer(scaledWidth, scaledHeight); // use QPixmap instead of QImage (like live painting buffer), because it supports background transparency (of mColor).
  pngBuffer.fill(mColor);
  QCPPainter painter(&pngBuffer);
  QRect oldViewport = mViewport;
  mViewport = QRect(0, 0, newWidth, newHeight);
  updateAxisRect();
  if (!qFuzzyCompare(scale, 1.0))
  {
    if (scale > 1.0) // for scale < 1 we always want cosmetic pens where possible, because else lines would disappear
    {
      painter.setScaledExportMode(true);
      painter.setRenderHint(QPainter::NonCosmeticDefaultPen);
    }
    painter.scale(scale, scale);
  }
  draw(&painter);
  mViewport = oldViewport;
  updateAxisRect();
  return pngBuffer.save(fileName, format, quality);
}
QList< QCPAxis * > QCustomPlot::selectedAxes () const [protected]
Returns the axes that currently have selected parts, i.e. whose selection is not QCPAxis::spNone.
See also:
selectedPlottables, selectedLegends, setInteractions, QCPAxis::setSelected, QCPAxis::setSelectable
Definition at line 7154 of file qcustomplot.cpp.
References xAxis, xAxis2, yAxis, and yAxis2.
Referenced by deselectAll().
{
  QList<QCPAxis*> result = QList<QCPAxis*>() << xAxis << yAxis << xAxis2 << yAxis2;
  for (int i=result.size()-1; i>=0; --i)
  {
    if (result.at(i)->selected() == QCPAxis::spNone)
      result.removeAt(i);
  }
  return result;
}
QList< QCPGraph * > QCustomPlot::selectedGraphs () const [protected]
Returns a list of the selected graphs. If no graphs are currently selected, the list is empty.
Note:
Even if the returned list is empty, it might still be, that there are selected plottables in the plot that are not of type QCPGraph (e.g. QCPCurve, QCPBars, etc.), see selectedPlottables. Of course, this only applies, if you actually add non-QCPGraph plottables.
See also:
setInteractions, selectedPlottables, QCPAbstractPlottable::setSelectable, QCPAbstractPlottable::setSelected
Definition at line 6768 of file qcustomplot.cpp.
References mGraphs.
{
  QList<QCPGraph*> result;
  for (int i=0; i<mGraphs.size(); ++i)
  {
    if (mGraphs.at(i)->selected())
      result.append(mGraphs.at(i));
  }
  return result;
}
QList<QCPAbstractItem*> selectedItems () const [protected]
Referenced by deselectAll().
QList< QCPLegend * > QCustomPlot::selectedLegends () const [protected]
Returns the legends (typically one or zero) that currently have selected parts, i.e. whose selection is not QCPLegend::spNone.
See also:
selectedPlottables, selectedAxes, setInteractions, QCPLegend::setSelected, QCPLegend::setSelectable, QCPLegend::selectedItems
Definition at line 7171 of file qcustomplot.cpp.
References legend, and QCPLegend::selected().
{
  /* for now, we only have the one legend. Maybe later, there will be a mechanism to have more. */
  QList<QCPLegend*> result;
  if (legend->selected() != QCPLegend::spNone)
    result.append(legend);
  return result;
}
QList< QCPAbstractPlottable * > QCustomPlot::selectedPlottables () const [protected]
Returns a list of the selected plottables. If no plottables are currently selected, the list is empty.
There is a convenience function if you're only interested in selected graphs, see selectedGraphs.
See also:
setInteractions, QCPAbstractPlottable::setSelectable, QCPAbstractPlottable::setSelected, selectedGraphs
Definition at line 6585 of file qcustomplot.cpp.
References mPlottables.
Referenced by deselectAll().
{
  QList<QCPAbstractPlottable*> result;
  for (int i=0; i<mPlottables.size(); ++i)
  {
    if (mPlottables.at(i)->selected())
      result.append(mPlottables.at(i));
  }
  return result;
}
QColor selectedTitleColor () const [protected]
Definition at line 1978 of file qcustomplot.h.
References mSelectedTitleColor.
{ return mSelectedTitleColor; }
QFont selectedTitleFont () const [protected]
Definition at line 1977 of file qcustomplot.h.
References mSelectedTitleFont.
{ return mSelectedTitleFont; }
void QCustomPlot::selectionChangedByUser ()
This signal is emitted after the user has changed the selection in the QCustomPlot, e.g. by clicking. It is not emitted, when the selection state of an object has changed programmatically, e.g. by a direct call to setSelected() on a plottable or by calling deselectAll.
See the documentation of setInteractions for how to find out which objects are currently selected.
See also:
setInteractions, QCPAbstractPlottable::selectionChanged, QCPAxis::selectionChanged
Definition at line 2569 of file moc_qcustomplot.cpp.
Referenced by mouseReleaseEvent().
{
    QMetaObject::activate(this, &staticMetaObject, 15, 0);
}
int selectionTolerance () const [protected]
Definition at line 1976 of file qcustomplot.h.
References mSelectionTolerance.
{ return mSelectionTolerance; }
bool QCustomPlot::selectTestTitle (const QPointF &pos) const [protected]
Returns whether the point pos in pixels hits the plot title.
Definition at line 8129 of file qcustomplot.cpp.
References mTitleBoundingBox.
Referenced by handleTitleSelection(), and mouseReleaseEvent().
{
  return mTitleBoundingBox.contains(pos.toPoint());
}
void QCustomPlot::setAntialiasedElement (QCP::AntialiasedElementantialiasedElement, boolenabled = true) [protected]
Sets whether the specified antialiasedElement is forcibly drawn antialiased. This overrides the antialiasing settings for whole element groups, normally controlled with the setAntialiasing function on the individual elements. If an element is neither specified in setAntialiasedElements nor in setNotAntialiasedElements, the antialiasing setting on each individual element instance is used.
For example, if enabled is true and antialiasedElement is QCP::aePlottables, all plottables will be drawn antialiased, no matter what the specific QCPAbstractPlottable::setAntialiased value was set to.
See also:
setNotAntialiasedElement
Definition at line 6135 of file qcustomplot.cpp.
References mAntialiasedElements, and mNotAntialiasedElements.
{
  if (!enabled && mAntialiasedElements.testFlag(antialiasedElement))
    mAntialiasedElements &= ~antialiasedElement;
  else if (enabled && !mAntialiasedElements.testFlag(antialiasedElement))
    mAntialiasedElements |= antialiasedElement;
  
  // make sure elements aren't in mNotAntialiasedElements and mAntialiasedElements simultaneously:
  if ((mNotAntialiasedElements & mAntialiasedElements) != 0)
    mNotAntialiasedElements |= ~mAntialiasedElements;
}
void QCustomPlot::setAntialiasedElements (const QCP::AntialiasedElements &antialiasedElements) [protected]
Sets which elements are forcibly drawn antialiased as an or combination of QCP::AntialiasedElement. This overrides the antialiasing settings for whole element groups, normally controlled with the setAntialiasing function on the individual elements. If an element is neither specified in setAntialiasedElements nor in setNotAntialiasedElements, the antialiasing setting on each individual element instance is used.
For example, if antialiasedElements contains QCP::aePlottables, all plottables will be drawn antialiased, no matter what the specific QCPAbstractPlottable::setAntialiased value was set to.
See also:
setNotAntialiasedElements
Definition at line 6112 of file qcustomplot.cpp.
References antialiasedElements(), mAntialiasedElements, and mNotAntialiasedElements.
Referenced by mouseReleaseEvent().
{
  mAntialiasedElements = antialiasedElements;
  
  // make sure elements aren't in mNotAntialiasedElements and mAntialiasedElements simultaneously:
  if ((mNotAntialiasedElements & mAntialiasedElements) != 0)
    mNotAntialiasedElements |= ~mAntialiasedElements;
}
void setAntialiasedSubGrid (boolenabled)
void setAntialiasedZeroLine (boolenabled)
void QCustomPlot::setAutoAddPlottableToLegend (boolon) [protected]
If set to true, adding a plottable (e.g. a graph) to the QCustomPlot automatically also adds the newly created plottable to the legend.
See also:
addPlottable, addGraph, QCPLegend::addItem
Definition at line 6209 of file qcustomplot.cpp.
References mAutoAddPlottableToLegend.
{
  mAutoAddPlottableToLegend = on;
}
void QCustomPlot::setAutoMargin (boolenabled) [protected]
Sets whether the margins are calculated automatically depeding on the sizes of the tick labels, axis labels, paddings etc. If disabled, the margins must be set manually with the setMargin functions.
See also:
setMargin, QCPAxis::setLabelPadding, QCPAxis::setTickLabelPadding
Definition at line 5989 of file qcustomplot.cpp.
References mAutoMargin.
{
  mAutoMargin = enabled;
}
void QCustomPlot::setAxisBackground (const QPixmap &pm) [protected]
Sets pm as the axis background pixmap. The axis background pixmap will be drawn inside the current axis rect, before anything else (e.g. the axes themselves, grids, graphs, etc.) is drawn. If the provided pixmap doesn't have the same size as the axis rect, scaling can be enabled with setAxisBackgroundScaled and the scaling mode (i.e. whether and how the aspect ratio is preserved) can be set with setAxisBackgroundScaledMode. To set all these options in one call, consider using the overloaded version of this function.
See also:
setAxisBackgroundScaled, setAxisBackgroundScaledMode
Definition at line 6222 of file qcustomplot.cpp.
References mAxisBackground, and mScaledAxisBackground.
{
  mAxisBackground = pm;
  mScaledAxisBackground = QPixmap();
}
void QCustomPlot::setAxisBackground (const QPixmap &pm, boolscaled, Qt::AspectRatioModemode = Qt::KeepAspectRatioByExpanding) [protected]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Allows setting the background pixmap, whether it shall be scaled and how it shall be scaled in one call.
See also:
setAxisBackground(const QPixmap &pm), setAxisBackgroundScaled, setAxisBackgroundScaledMode
Definition at line 6233 of file qcustomplot.cpp.
References mAxisBackground, mAxisBackgroundScaled, mAxisBackgroundScaledMode, and mScaledAxisBackground.
{
  mAxisBackground = pm;
  mScaledAxisBackground = QPixmap();
  mAxisBackgroundScaled = scaled;
  mAxisBackgroundScaledMode = mode;
}
void QCustomPlot::setAxisBackgroundScaled (boolscaled) [protected]
Sets whether the axis background pixmap shall be scaled to fit the current axis rect or not. If scaled is set to true, you may control whether and how the aspect ratio of the original pixmap is preserved with setAxisBackgroundScaledMode.
Note that the scaled version of the original pixmap is buffered, so there is no performance penalty on replots, when enabling the scaling. (Except of course, the axis rect is continuously changed, but that's not very likely.)
See also:
setAxisBackground, setAxisBackgroundScaledMode
Definition at line 6252 of file qcustomplot.cpp.
References mAxisBackgroundScaled.
{
  mAxisBackgroundScaled = scaled;
}
void QCustomPlot::setAxisBackgroundScaledMode (Qt::AspectRatioModemode) [protected]
If scaling of the axis background pixmap is enabled (setAxisBackgroundScaled), use this function to define whether and how the aspect ratio of the original pixmap passed to setAxisBackground is preserved.
See also:
setAxisBackground, setAxisBackgroundScaled
Definition at line 6262 of file qcustomplot.cpp.
References mAxisBackgroundScaledMode.
{
  mAxisBackgroundScaledMode = mode;
}
void setAxisRect (const QRect &arect) [protected]
void setColor (const QColor &color) [protected]
bool QCustomPlot::setCurrentLayer (const QString &name) [protected]
Sets the layer with the specified name to be the current layer. All newly created/added layerables (QCPLayerable), e.g. plottables and items, are initially placed on the current layer.
Returns true on success, i.e. if there is a layer with the specified name in the QCustomPlot.
See also:
addLayer, moveLayer, removeLayer
Definition at line 6998 of file qcustomplot.cpp.
References layer().
Referenced by removeLayer().
{
  if (QCPLayer *newCurrentLayer = layer(name))
  {
    return setCurrentLayer(newCurrentLayer);
  } else
  {
    qDebug() << Q_FUNC_INFO << "layer with name doesn't exist:" << name;
    return false;
  }
}
bool QCustomPlot::setCurrentLayer (QCPLayer *layer) [protected]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the provided layer to be the current layer. Returns true on success, i.e. when layer is a valid layer in the QCustomPlot.
See also:
addLayer, moveLayer, removeLayer
Definition at line 7018 of file qcustomplot.cpp.
References layer(), mCurrentLayer, and mLayers.
{
  if (!mLayers.contains(layer))
  {
    qDebug() << Q_FUNC_INFO << "layer not a layer of this QCustomPlot:" << reinterpret_cast<quintptr>(layer);
    return false;
  }
  
  mCurrentLayer = layer;
  return true;
}
void setInteraction (const Interaction &interaction, boolenabled = true) [protected]
void QCustomPlot::setInteractions (const Interactions &interactions) [protected]
Sets the possible interactions of this QCustomPlot as an or-combination of Interaction enums. There are the following types of interactions:
Axis range manipulation is controlled via iRangeDrag and iRangeZoom. When the respective interaction is enabled, the user may drag axes ranges and zoom with the mouse wheel. For details how to control which axes the user may drag/zoom and in what orientations, see setRangeDrag, setRangeZoom, setRangeDragAxes, setRangeZoomAxes.
Plottable selection is controlled by iSelectPlottables. If iSelectPlottables is set, the user may select plottables (e.g. graphs, curves, bars,...) by clicking on them or in their vicinity, see setSelectionTolerance. Whether the user can actually select a plottable can further be restricted with the QCPAbstractPlottable::setSelectable function on the specific plottable. To find out whether a specific plottable is selected, call QCPAbstractPlottable::selected(). To retrieve a list of all currently selected plottables, call selectedPlottables. If you're only interested in QCPGraphs, you may use the convenience function selectedGraphs.
Item selection is controlled by iSelectItems. If iSelectItems is set, the user may select items (e.g. QCPItemLine, QCPItemText,...) by clicking on them or in their vicinity. To find out whether a specific item is selected, call QCPAbstractItem::selected(). To retrieve a list of all currently selected items, call selectedItems.
Axis selection is controlled with iSelectAxes. If iSelectAxes is set, the user may select parts of the axes by clicking on them. What parts exactly (e.g. Axis base line, tick labels, axis label) are selectable can be controlled via QCPAxis::setSelectable for each axis. To retrieve a list of all axes that currently contain selected parts, call selectedAxes. Which parts of an axis are selected, can be retrieved with QCPAxis::selected().
Legend selection is controlled with iSelectLegend. If this is set, the user may select the legend itself or individual items by clicking on them. What parts exactly are selectable can be controlled via QCPLegend::setSelectable. To find out whether the legend or any child items are selected, check the value of QCPLegend::selected. To find out which child items are selected, call QCPLegend::selectedItems.
Plot title selection is controlled with iSelectTitle. If set, the user may select the plot title by clicking on it. To find out whether the title is currently selected, call QCustomPlot::titleSelected().
If the selection state has changed by user interaction, the selectionChangedByUser signal is emitted. Each selectable object additionally emits an individual selectionChanged signal whenever their selection state has changed, i.e. not only by user interaction.
To allow multiple objects to be selected by holding the modifier set with setMultiSelectModifier, set the flag iMultiSelect.
Note:
In addition to the selection mechanism presented here, QCustomPlot always emits corresponding signals, when an object is clicked or double clicked. see plottableClick and plottableDoubleClick for example.
See also:
setInteraction, setSelectionTolerance
Definition at line 6319 of file qcustomplot.cpp.
References interactions(), and mInteractions.
{
  mInteractions = interactions;
}
void setMargin (intleft, intright, inttop, intbottom) [protected]
void setMarginBottom (intmargin) [protected]
void setMarginLeft (intmargin) [protected]
void setMarginRight (intmargin) [protected]
void setMarginTop (intmargin) [protected]
void QCustomPlot::setMultiSelectModifier (Qt::KeyboardModifiermodifier) [protected]
Sets the keyboard modifier that will be recognized as multi-select-modifier. If iMultiSelect is specified in setInteractions, the user may select multiple objects by clicking on them one after the other while holding down modifier.
By default the multi-select-modifier is set to Qt::ControlModifier.
See also:
setInteractions
Definition at line 6436 of file qcustomplot.cpp.
References mMultiSelectModifier.
{
  mMultiSelectModifier = modifier;
}
void QCustomPlot::setNoAntialiasingOnDrag (boolenabled) [protected]
Sets whether antialiasing is disabled for all elements while the user is dragging axes ranges. If many objects, especially plottables, are normally drawn antialiased, this greatly improves performance during dragging. Thus it creates a more responsive user experience. As soon as the user stops dragging, the last replot is done with normal antialiasing, to restore high image quality.
See also:
setAntialiasedElements, setNotAntialiasedElements
Definition at line 6396 of file qcustomplot.cpp.
References mNoAntialiasingOnDrag.
{
  mNoAntialiasingOnDrag = enabled;
}
void QCustomPlot::setNotAntialiasedElement (QCP::AntialiasedElementnotAntialiasedElement, boolenabled = true) [protected]
Sets whether the specified notAntialiasedElement is forcibly drawn not antialiased. This overrides the antialiasing settings for whole element groups, normally controlled with the setAntialiasing function on the individual elements. If an element is neither specified in setAntialiasedElements nor in setNotAntialiasedElements, the antialiasing setting on each individual element instance is used.
For example, if enabled is true and notAntialiasedElement is QCP::aePlottables, no plottables will be drawn antialiased, no matter what the specific QCPAbstractPlottable::setAntialiased value was set to.
if enabled is true and notAntialiasedElement is already set with setAntialiasedElement, it is removed from there.
See also:
setAntialiasedElement
Definition at line 6191 of file qcustomplot.cpp.
References mAntialiasedElements, and mNotAntialiasedElements.
{
  if (!enabled && mNotAntialiasedElements.testFlag(notAntialiasedElement))
    mNotAntialiasedElements &= ~notAntialiasedElement;
  else if (enabled && !mNotAntialiasedElements.testFlag(notAntialiasedElement))
    mNotAntialiasedElements |= notAntialiasedElement;
  
  // make sure elements aren't in mNotAntialiasedElements and mAntialiasedElements simultaneously:
  if ((mNotAntialiasedElements & mAntialiasedElements) != 0)
    mAntialiasedElements |= ~mNotAntialiasedElements;
}
void QCustomPlot::setNotAntialiasedElements (const QCP::AntialiasedElements &notAntialiasedElements) [protected]
Sets which elements are forcibly drawn not antialiased as an or combination of QCP::AntialiasedElement. This overrides the antialiasing settings for whole element groups, normally controlled with the setAntialiasing function on the individual elements. If an element is neither specified in setAntialiasedElements nor in setNotAntialiasedElements, the antialiasing setting on each individual element instance is used.
For example, if notAntialiasedElements contains QCP::aePlottables, no plottables will be drawn antialiased, no matter what the specific QCPAbstractPlottable::setAntialiased value was set to.
if an element in notAntialiasedElements is already set in setAntialiasedElements, it is removed from there.
See also:
setAntialiasedElements
Definition at line 6165 of file qcustomplot.cpp.
References mAntialiasedElements, mNotAntialiasedElements, and notAntialiasedElements().
Referenced by mouseMoveEvent(), and mouseReleaseEvent().
{
  mNotAntialiasedElements = notAntialiasedElements;
  
  // make sure elements aren't in mNotAntialiasedElements and mAntialiasedElements simultaneously:
  if ((mNotAntialiasedElements & mAntialiasedElements) != 0)
    mAntialiasedElements |= ~mNotAntialiasedElements;
}
void setPen (const QPen &pen)
Referenced by QCPPainter::fixScaledPen(), and QCPPainter::setPen().
void QCustomPlot::setPlottingHint (QCP::PlottingHinthint, boolenabled = true) [protected]
Sets the specified plotting hint to enabled.
See also:
setPlottingHints
Definition at line 6414 of file qcustomplot.cpp.
References mPlottingHints, and setPlottingHints().
{
  QCP::PlottingHints newHints = mPlottingHints;
  if (!enabled)
    newHints &= ~hint;
  else
    newHints |= hint;
  
  if (newHints != mPlottingHints)
    setPlottingHints(newHints);
}
void QCustomPlot::setPlottingHints (const QCP::PlottingHints &hints) [protected]
Sets the plotting hints for this QCustomPlot instance.
See also:
setPlottingHint
Definition at line 6405 of file qcustomplot.cpp.
References mPlottingHints.
Referenced by setPlottingHint().
{
  mPlottingHints = hints;
}
void QCustomPlot::setRangeDrag (Qt::Orientationsorientations) [protected]
Sets which axis orientation may be range dragged by the user with mouse interaction. What orientation corresponds to which specific axis can be set with setRangeDragAxes(QCPAxis *horizontal, QCPAxis *vertical). By default, the horizontal axis is the bottom axis (xAxis) and the vertical axis is the left axis (yAxis).
To disable range dragging entirely, pass 0 as orientations or remove iRangeDrag from setInteractions. To enable range dragging for both directions, pass Qt::Horizontal | Qt::Vertical as orientations.
In addition to setting orientations to a non-zero value, make sure setInteractions contains iRangeDrag to enable the range dragging interaction.
See also:
setRangeZoom, setRangeDragAxes, setNoAntialiasingOnDrag
Definition at line 6018 of file qcustomplot.cpp.
References mRangeDrag.
{
  mRangeDrag = orientations;
}
void QCustomPlot::setRangeDragAxes (QCPAxis *horizontal, QCPAxis *vertical) [protected]
Sets the axes whose range will be dragged when setRangeDrag enables mouse range dragging on the QCustomPlot widget.
See also:
setRangeZoomAxes
Definition at line 6049 of file qcustomplot.cpp.
References mRangeDragHorzAxis, and mRangeDragVertAxis.
{
  if (horizontal)
    mRangeDragHorzAxis = horizontal;
  if (vertical)
    mRangeDragVertAxis = vertical;
}
void QCustomPlot::setRangeZoom (Qt::Orientationsorientations) [protected]
Sets which axis orientation may be zoomed by the user with the mouse wheel. What orientation corresponds to which specific axis can be set with setRangeZoomAxes(QCPAxis *horizontal, QCPAxis *vertical). By default, the horizontal axis is the bottom axis (xAxis) and the vertical axis is the left axis (yAxis).
To disable range zooming entirely, pass 0 as orientations or remove iRangeZoom from setInteractions. To enable range zooming for both directions, pass Qt::Horizontal | Qt::Vertical as orientations.
In addition to setting orientations to a non-zero value, make sure setInteractions contains iRangeZoom to enable the range zooming interaction.
See also:
setRangeZoomFactor, setRangeZoomAxes, setRangeDrag
Definition at line 6038 of file qcustomplot.cpp.
References mRangeZoom.
{
  mRangeZoom = orientations;
}
void QCustomPlot::setRangeZoomAxes (QCPAxis *horizontal, QCPAxis *vertical) [protected]
Sets the axes whose range will be zoomed when setRangeZoom enables mouse wheel zooming on the QCustomPlot widget. The two axes can be zoomed with different strengths, when different factors are passed to setRangeZoomFactor(double horizontalFactor, double verticalFactor).
See also:
setRangeDragAxes
Definition at line 6064 of file qcustomplot.cpp.
References mRangeZoomHorzAxis, and mRangeZoomVertAxis.
{
  if (horizontal)
    mRangeZoomHorzAxis = horizontal;
  if (vertical)
    mRangeZoomVertAxis = vertical;
}
void QCustomPlot::setRangeZoomFactor (doublehorizontalFactor, doubleverticalFactor) [protected]
Sets how strong one rotation step of the mouse wheel zooms, when range zoom was activated with setRangeZoom. The two parameters horizontalFactor and verticalFactor provide a way to let the horizontal axis zoom at different rates than the vertical axis. Which axis is horizontal and which is vertical, can be set with setRangeZoomAxes.
When the zoom factor is greater than one, scrolling the mouse wheel backwards (towards the user) will zoom in (make the currently visible range smaller). For zoom factors smaller than one, the same scrolling direction will zoom out.
Definition at line 6082 of file qcustomplot.cpp.
References mRangeZoomFactorHorz, and mRangeZoomFactorVert.
{
  mRangeZoomFactorHorz = horizontalFactor;
  mRangeZoomFactorVert = verticalFactor;
}
void QCustomPlot::setRangeZoomFactor (doublefactor) [protected]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets both the horizontal and vertical zoom factor.
Definition at line 6092 of file qcustomplot.cpp.
References mRangeZoomFactorHorz, and mRangeZoomFactorVert.
{
  mRangeZoomFactorHorz = factor;
  mRangeZoomFactorVert = factor;
}
void QCustomPlot::setSelectedTitleColor (const QColor &color) [protected]
This color is used to draw the title, when it is selected.
See also:
setTitleSelected, setTitleColor
Definition at line 6372 of file qcustomplot.cpp.
References color(), and mSelectedTitleColor.
{
  mSelectedTitleColor = color;
}
void QCustomPlot::setSelectedTitleFont (const QFont &font) [protected]
This font is used to draw the title, when it is selected.
See also:
setTitleSelected, setTitleFont
Definition at line 6362 of file qcustomplot.cpp.
References mSelectedTitleFont.
{
  mSelectedTitleFont = font;
}
void QCustomPlot::setSelectionTolerance (intpixels) [protected]
Sets the tolerance that is used when deciding whether a click on the QCustomPlot surface selects an object (e.g. a plottable) or not.
If for example the user clicks in the vicinity of the line of a QCPGraph, it's only regarded as a potential selection when the minimum distance between the click position and the graph line is smaller than pixels. Objects that are defined by an area (e.g. QCPBars) only react to clicks directly inside the area and ignore this selection tolerance. In other words it only has meaning for parts of objects that are too thin to exactly hit with a click and thus need such a tolerance.
See also:
setInteractions, QCPAbstractPlottable::selectTest
Definition at line 6352 of file qcustomplot.cpp.
References mSelectionTolerance.
{
  mSelectionTolerance = pixels;
}
void setSubGridPen (const QPen &pen)
void QCPGrid::setSubGridVisible (boolvisible)
Sets whether grid lines at sub tick marks are drawn.
See also:
setSubGridPen
Definition at line 14173 of file qcustomplot.cpp.
References mSubGridVisible.
{
  mSubGridVisible = visible;
}
void QCustomPlot::setTitle (const QString &title) [protected]
Sets the plot title which will be drawn centered at the top of the widget. The title position is not dependant on the actual position of the axes. However, if setAutoMargin is set to true, the top margin will be adjusted appropriately, so the top axis labels/tick labels will not overlap with the title.
See also:
setTitleFont, setTitleColor
Definition at line 5884 of file qcustomplot.cpp.
References mTitle, and title().
{
  mTitle = title;
}
void QCustomPlot::setTitleColor (const QColor &color) [protected]
Sets the text color of the plot title.
See also:
setTitleFont, setTitle
Definition at line 5902 of file qcustomplot.cpp.
References color(), and mTitleColor.
{
  mTitleColor = color;
}
void QCustomPlot::setTitleFont (const QFont &font) [protected]
Sets the font of the plot title.
See also:
setTitleColor, setTitle
Definition at line 5893 of file qcustomplot.cpp.
References mTitleFont.
{
  mTitleFont = font;
}
void QCustomPlot::setTitleSelected (boolselected) [protected]
Sets whether the plot title is selected.
See also:
setInteractions, setSelectedTitleFont, setSelectedTitleColor, setTitle
Definition at line 6382 of file qcustomplot.cpp.
References mTitleSelected.
Referenced by deselectAll(), and handleTitleSelection().
{
  mTitleSelected = selected;
}
void QCustomPlot::setupFullAxesBox () [protected]
Convenience function to make the top and right axes visible and assign them the following properties from their corresponding bottom/left axes:
range (QCPAxis::setRange)
range reversed (QCPAxis::setRangeReversed)
scale type (QCPAxis::setScaleType)
scale log base (QCPAxis::setScaleLogBase)
ticks (QCPAxis::setTicks)
auto (major) tick count (QCPAxis::setAutoTickCount)
sub tick count (QCPAxis::setSubTickCount)
auto sub ticks (QCPAxis::setAutoSubTicks)
tick step (QCPAxis::setTickStep)
auto tick step (QCPAxis::setAutoTickStep)
Tick labels (QCPAxis::setTickLabels) however, is always set to false.
This function does not connect the rangeChanged signals of the bottom and left axes to the QCPAxis::setRange slots of the top and right axes in order to synchronize the ranges permanently.
Definition at line 7265 of file qcustomplot.cpp.
References QCPAxis::autoSubTicks(), QCPAxis::autoTickCount(), QCPAxis::autoTickStep(), QCPAxis::range(), QCPAxis::rangeReversed(), QCPAxis::scaleLogBase(), QCPAxis::scaleType(), QCPAxis::setAutoSubTicks(), QCPAxis::setAutoTickCount(), QCPAxis::setAutoTickStep(), QCPAxis::setRange(), QCPAxis::setRangeReversed(), QCPAxis::setScaleLogBase(), QCPAxis::setScaleType(), QCPAxis::setSubTickCount(), QCPAxis::setTickLabels(), QCPAxis::setTicks(), QCPAxis::setTickStep(), QCPLayerable::setVisible(), QCPAxis::subTickCount(), QCPAxis::ticks(), QCPAxis::tickStep(), xAxis, xAxis2, yAxis, and yAxis2.
{
  xAxis2->setVisible(true);
  yAxis2->setVisible(true);
  
  xAxis2->setTickLabels(false);
  yAxis2->setTickLabels(false);
  
  xAxis2->setAutoSubTicks(xAxis->autoSubTicks());
  yAxis2->setAutoSubTicks(yAxis->autoSubTicks());
  
  xAxis2->setAutoTickCount(xAxis->autoTickCount());
  yAxis2->setAutoTickCount(yAxis->autoTickCount());
  
  xAxis2->setAutoTickStep(xAxis->autoTickStep());
  yAxis2->setAutoTickStep(yAxis->autoTickStep());
  
  xAxis2->setScaleType(xAxis->scaleType());
  yAxis2->setScaleType(yAxis->scaleType());
  
  xAxis2->setScaleLogBase(xAxis->scaleLogBase());
  yAxis2->setScaleLogBase(yAxis->scaleLogBase());
  
  xAxis2->setTicks(xAxis->ticks());
  yAxis2->setTicks(yAxis->ticks());
  
  xAxis2->setSubTickCount(xAxis->subTickCount());
  yAxis2->setSubTickCount(yAxis->subTickCount());
  
  xAxis2->setTickStep(xAxis->tickStep());
  yAxis2->setTickStep(yAxis->tickStep());
  
  xAxis2->setRange(xAxis->range());
  yAxis2->setRange(yAxis->range());
  
  xAxis2->setRangeReversed(xAxis->rangeReversed());
  yAxis2->setRangeReversed(yAxis->rangeReversed());
}
void setZeroLinePen (const QPen &pen)
QPen subGridPen () const
Definition at line 1592 of file qcustomplot.h.
References mSubGridPen.
{ return mSubGridPen; }
bool subGridVisible () const
Definition at line 1588 of file qcustomplot.h.
References mSubGridVisible.
{ return mSubGridVisible; }
QString title () const [protected]
Definition at line 1953 of file qcustomplot.h.
References mTitle.
Referenced by MainWindow::msg(), and setTitle().
{ return mTitle; }
void QCustomPlot::titleClick (QMouseEvent *event)
This signal is emitted when the plot title is clicked. event is the mouse event that caused the click.
See also:
titleDoubleClick
Definition at line 2555 of file moc_qcustomplot.cpp.
Referenced by mouseReleaseEvent().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 13, _a);
}
QColor titleColor () const [protected]
Definition at line 1955 of file qcustomplot.h.
References mTitleColor.
{ return mTitleColor; }
void QCustomPlot::titleDoubleClick (QMouseEvent *event)
This signal is emitted when the plot title is double clicked. event is the mouse event that caused the click.
See also:
titleClick
Definition at line 2562 of file moc_qcustomplot.cpp.
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 14, _a);
}
QFont titleFont () const [protected]
Definition at line 1954 of file qcustomplot.h.
References mTitleFont.
{ return mTitleFont; }
bool titleSelected () const [protected]
Definition at line 1979 of file qcustomplot.h.
References mTitleSelected.
Referenced by handleTitleSelection().
{ return mTitleSelected; }
void QCustomPlot::updateAxisRect () [protected]
calculates mAxisRect by applying the margins inward to mViewport. The axisRect is then passed on to all axes via QCPAxis::setAxisRect
See also:
setMargin, setAxisRect
Definition at line 8116 of file qcustomplot.cpp.
References mAxisRect, mMarginBottom, mMarginLeft, mMarginRight, mMarginTop, mViewport, QCPAxis::setAxisRect(), xAxis, xAxis2, yAxis, and yAxis2.
Referenced by resizeEvent(), savePdf(), and saveRastered().
{
  mAxisRect = mViewport.adjusted(mMarginLeft, mMarginTop, -mMarginRight, -mMarginBottom);
  xAxis->setAxisRect(mAxisRect);
  yAxis->setAxisRect(mAxisRect);
  xAxis2->setAxisRect(mAxisRect);
  yAxis2->setAxisRect(mAxisRect);
}
QRect QCustomPlot::viewport () const [protected]
Returns the viewport rect of this QCustomPlot instance. The viewport is the area the plot is drawn in, all mechanisms, e.g. margin caluclation take the viewport to be the outer border of the plot. The viewport normally is the rect() of the QCustomPlot widget, i.e. a rect with top left (0, 0) and size of the QCustomPlot widget.
Don't confuse the viewport with the axisRect. An axisRect is the rect defined by two axes, where the graphs/plottables are drawn in. The viewport is larger and contains also the axes themselves, their tick numbers, their labels, the plot title etc.
Only when saving to a file (see savePng, savePdf etc.) the viewport is temporarily modified to allow saving plots with sizes independent of the current widget size.
Definition at line 1957 of file qcustomplot.h.
References mViewport.
{ return mViewport; }
void QCustomPlot::wheelEvent (QWheelEvent *event) [protected], [virtual]
Event handler for mouse wheel events. First, the mouseWheel signal is emitted. If rangeZoom is Qt::Horizontal, Qt::Vertical or both, the ranges of the axes defined as rangeZoomHorzAxis and rangeZoomVertAxis are scaled. The center of the scaling operation is the current cursor position inside the plot. The scaling factor is dependant on the mouse wheel delta (which direction the wheel was rotated) to provide a natural zooming feel. The Strength of the zoom can be controlled via setRangeZoomFactor.
Note, that event->delta() is usually +/-120 for single rotation steps. However, if the mouse wheel is turned rapidly, many steps may bunch up to one event, so the event->delta() may then be multiples of 120. This is taken into account here, by calculating wheelSteps and using it as exponent of the range zoom factor. This takes care of the wheel direction automatically, by inverting the factor, when the wheel step is negative (f^-1 = 1/f).
Definition at line 7811 of file qcustomplot.cpp.
References mInteractions, mouseWheel(), mRangeZoom, mRangeZoomFactorHorz, mRangeZoomFactorVert, mRangeZoomHorzAxis, mRangeZoomVertAxis, QCPAxis::pixelToCoord(), replot(), and QCPAxis::scaleRange().
{
  emit mouseWheel(event);
  
  // Mouse range zooming interaction:
  if (mInteractions.testFlag(iRangeZoom))
  {
    if (mRangeZoom != 0)
    {
      double factor;
      double wheelSteps = event->delta()/120.0; // a single step delta is +/-120 usually
      if (mRangeZoom.testFlag(Qt::Horizontal))
      {
        factor = pow(mRangeZoomFactorHorz, wheelSteps);
        mRangeZoomHorzAxis->scaleRange(factor, mRangeZoomHorzAxis->pixelToCoord(event->pos().x()));
      }
      if (mRangeZoom.testFlag(Qt::Vertical))
      {
        factor = pow(mRangeZoomFactorVert, wheelSteps);
        mRangeZoomVertAxis->scaleRange(factor, mRangeZoomVertAxis->pixelToCoord(event->pos().y()));
      }
      replot();
    }
  }
  
  QWidget::wheelEvent(event);
}
QPen zeroLinePen () const
Definition at line 1593 of file qcustomplot.h.
References mZeroLinePen.
{ return mZeroLinePen; }
QCPGrid::~QCPGrid ()
Definition at line 14164 of file qcustomplot.cpp.
{
}
QCustomPlot::~QCustomPlot () [protected], [virtual]
Definition at line 5836 of file qcustomplot.cpp.
References clearItems(), clearPlottables(), legend, mLayers, xAxis, xAxis2, yAxis, and yAxis2.
{
  clearPlottables();
  clearItems();
  delete legend;
  delete xAxis;
  delete yAxis;
  delete xAxis2;
  delete yAxis2;
  qDeleteAll(mLayers);
  mLayers.clear();
}
Variable Documentation
double key
Definition at line 145 of file qcustomplot.h.
Referenced by QCPGraph::addData(), QCPCurve::addData(), QCPBars::addData(), QCPCurve::getCurveData(), QCPGraph::getImpulsePlotData(), QCPGraph::getStepCenterPlotData(), QCPGraph::getStepLeftPlotData(), QCPAbstractPlottable::pixelsToCoords(), QCPGraph::removeDataBefore(), QCPBars::removeDataBefore(), QCPItemTracer::setGraphKey(), and QFourierTransformer::setSize().
double keyErrorMinus
Definition at line 146 of file qcustomplot.h.
double keyErrorPlus
Definition at line 146 of file qcustomplot.h.
QCPLegend* legend
Definition at line 2077 of file qcustomplot.h.
Referenced by deselectAll(), mouseReleaseEvent(), selectedLegends(), and ~QCustomPlot().
QCP::AntialiasedElements mAADragBackup
Definition at line 2138 of file qcustomplot.h.
Referenced by mouseReleaseEvent().
QCP::AntialiasedElements mAntialiasedElements
Definition at line 2123 of file qcustomplot.h.
Referenced by antialiasedElements(), setAntialiasedElement(), setAntialiasedElements(), setNotAntialiasedElement(), and setNotAntialiasedElements().
bool mAntialiasedSubGrid
Definition at line 1606 of file qcustomplot.h.
Referenced by antialiasedSubGrid(), and drawSubGridLines().
bool mAntialiasedZeroLine
Definition at line 1606 of file qcustomplot.h.
Referenced by antialiasedZeroLine(), and drawGridLines().
bool mAutoAddPlottableToLegend
Definition at line 2113 of file qcustomplot.h.
Referenced by addPlottable(), autoAddPlottableToLegend(), and setAutoAddPlottableToLegend().
bool mAutoMargin
Definition at line 2113 of file qcustomplot.h.
Referenced by autoMargin(), and setAutoMargin().
QPixmap mAxisBackground
Definition at line 2124 of file qcustomplot.h.
Referenced by axisBackground(), drawAxisBackground(), and setAxisBackground().
bool mAxisBackgroundScaled
Definition at line 2125 of file qcustomplot.h.
Referenced by axisBackgroundScaled(), drawAxisBackground(), setAxisBackground(), and setAxisBackgroundScaled().
Qt::AspectRatioMode mAxisBackgroundScaledMode
Definition at line 2126 of file qcustomplot.h.
Referenced by axisBackgroundScaledMode(), drawAxisBackground(), setAxisBackground(), and setAxisBackgroundScaledMode().
QRect mAxisRect
Definition at line 2111 of file qcustomplot.h.
Referenced by QCPAxis::axisRect(), axisRect(), drawAxisBackground(), and updateAxisRect().
QColor mColor
Definition at line 2114 of file qcustomplot.h.
Referenced by QCPItemText::color(), color(), replot(), savePdf(), and saveRastered().
QCPLayer* mCurrentLayer
Definition at line 2139 of file qcustomplot.h.
Referenced by currentLayer(), removeLayer(), and setCurrentLayer().
bool mDragging
Definition at line 2122 of file qcustomplot.h.
Referenced by mouseMoveEvent(), and mouseReleaseEvent().
QPoint mDragStart
Definition at line 2134 of file qcustomplot.h.
Referenced by mouseMoveEvent(), and mouseReleaseEvent().
QCPRange mDragStartHorzRange
Definition at line 2135 of file qcustomplot.h.
Referenced by mouseMoveEvent().
QCPRange mDragStartVertRange
Definition at line 2135 of file qcustomplot.h.
Referenced by mouseMoveEvent().
QList<QCPGraph*> mGraphs
Definition at line 2116 of file qcustomplot.h.
Referenced by addGraph(), addPlottable(), clearGraphs(), graphCount(), removeGraph(), removePlottable(), and selectedGraphs().
Interactions mInteractions
Definition at line 2127 of file qcustomplot.h.
Referenced by interactions(), mouseMoveEvent(), mouseReleaseEvent(), setInteractions(), and wheelEvent().
QList<QCPAbstractItem*> mItems
Definition at line 2117 of file qcustomplot.h.
Referenced by handleItemSelection(), and itemAt().
QList<QCPLayer*> mLayers
Definition at line 2118 of file qcustomplot.h.
Referenced by layerCount(), removeLayer(), setCurrentLayer(), and ~QCustomPlot().
int mMarginBottom
Definition at line 2112 of file qcustomplot.h.
Referenced by QCPLegend::marginBottom(), marginBottom(), and updateAxisRect().
int mMarginLeft
Definition at line 2112 of file qcustomplot.h.
Referenced by QCPLegend::marginLeft(), marginLeft(), and updateAxisRect().
int mMarginRight
Definition at line 2112 of file qcustomplot.h.
Referenced by QCPLegend::marginRight(), marginRight(), and updateAxisRect().
int mMarginTop
Definition at line 2112 of file qcustomplot.h.
Referenced by QCPLegend::marginTop(), marginTop(), and updateAxisRect().
Qt::KeyboardModifier mMultiSelectModifier
Definition at line 2141 of file qcustomplot.h.
Referenced by mouseReleaseEvent(), multiSelectModifier(), and setMultiSelectModifier().
bool mNoAntialiasingOnDrag
Definition at line 2131 of file qcustomplot.h.
Referenced by mouseMoveEvent(), mouseReleaseEvent(), noAntialiasingOnDrag(), and setNoAntialiasingOnDrag().
QCP::AntialiasedElements mNotAADragBackup
Definition at line 2138 of file qcustomplot.h.
Referenced by mouseReleaseEvent().
QCP::AntialiasedElements mNotAntialiasedElements
Definition at line 2123 of file qcustomplot.h.
Referenced by notAntialiasedElements(), setAntialiasedElement(), setAntialiasedElements(), setNotAntialiasedElement(), and setNotAntialiasedElements().
QPixmap mPaintBuffer
Definition at line 2133 of file qcustomplot.h.
Referenced by paintEvent(), replot(), and resizeEvent().
QCPAxis* mParentAxis
Definition at line 1604 of file qcustomplot.h.
Referenced by drawGridLines(), and drawSubGridLines().
QPen mPen
Definition at line 1607 of file qcustomplot.h.
Referenced by drawGridLines(), QCPAbstractPlottable::pen(), QCPItemStraightLine::pen(), QCPItemLine::pen(), QCPItemEllipse::pen(), QCPItemRect::pen(), QCPItemPixmap::pen(), QCPItemText::pen(), QCPItemCurve::pen(), QCPItemBracket::pen(), QCPItemTracer::pen(), and pen().
QList<QCPAbstractPlottable*> mPlottables
Definition at line 2115 of file qcustomplot.h.
Referenced by addPlottable(), clearPlottables(), handlePlottableSelection(), hasPlottable(), plottableAt(), plottableCount(), removePlottable(), and selectedPlottables().
QCP::PlottingHints mPlottingHints
Definition at line 2140 of file qcustomplot.h.
Referenced by plottingHints(), replot(), setPlottingHint(), and setPlottingHints().
Qt::Orientations mRangeDrag
Definition at line 2119 of file qcustomplot.h.
Referenced by mouseMoveEvent(), rangeDrag(), and setRangeDrag().
QCPAxis* mRangeDragHorzAxis
Definition at line 2120 of file qcustomplot.h.
Referenced by mouseMoveEvent(), rangeDragAxis(), and setRangeDragAxes().
QCPAxis * mRangeDragVertAxis
Definition at line 2120 of file qcustomplot.h.
Referenced by mouseMoveEvent(), rangeDragAxis(), and setRangeDragAxes().
Qt::Orientations mRangeZoom
Definition at line 2119 of file qcustomplot.h.
Referenced by rangeZoom(), setRangeZoom(), and wheelEvent().
double mRangeZoomFactorHorz
Definition at line 2121 of file qcustomplot.h.
Referenced by rangeZoomFactor(), setRangeZoomFactor(), and wheelEvent().
double mRangeZoomFactorVert
Definition at line 2121 of file qcustomplot.h.
Referenced by rangeZoomFactor(), setRangeZoomFactor(), and wheelEvent().
QCPAxis * mRangeZoomHorzAxis
Definition at line 2120 of file qcustomplot.h.
Referenced by rangeZoomAxis(), setRangeZoomAxes(), and wheelEvent().
QCPAxis * mRangeZoomVertAxis
Definition at line 2120 of file qcustomplot.h.
Referenced by rangeZoomAxis(), setRangeZoomAxes(), and wheelEvent().
bool mReplotting
Definition at line 2137 of file qcustomplot.h.
Referenced by replot().
QPixmap mScaledAxisBackground
Definition at line 2136 of file qcustomplot.h.
Referenced by drawAxisBackground(), and setAxisBackground().
QColor mSelectedTitleColor
Definition at line 2109 of file qcustomplot.h.
Referenced by selectedTitleColor(), and setSelectedTitleColor().
QFont mSelectedTitleFont
Definition at line 2108 of file qcustomplot.h.
Referenced by selectedTitleFont(), and setSelectedTitleFont().
int mSelectionTolerance
Definition at line 2128 of file qcustomplot.h.
Referenced by itemAt(), plottableAt(), selectionTolerance(), and setSelectionTolerance().
QPen mSubGridPen
Definition at line 1607 of file qcustomplot.h.
Referenced by drawSubGridLines(), and subGridPen().
bool mSubGridVisible
Definition at line 1605 of file qcustomplot.h.
Referenced by setSubGridVisible(), and subGridVisible().
QString mTitle
Definition at line 2107 of file qcustomplot.h.
Referenced by setTitle(), and title().
QRect mTitleBoundingBox
Definition at line 2130 of file qcustomplot.h.
Referenced by selectTestTitle().
QColor mTitleColor
Definition at line 2109 of file qcustomplot.h.
Referenced by setTitleColor(), and titleColor().
QFont mTitleFont
Definition at line 2108 of file qcustomplot.h.
Referenced by setTitleFont(), and titleFont().
bool mTitleSelected
Definition at line 2129 of file qcustomplot.h.
Referenced by setTitleSelected(), and titleSelected().
QRect mViewport
Definition at line 2110 of file qcustomplot.h.
Referenced by resizeEvent(), savePdf(), saveRastered(), updateAxisRect(), and viewport().
QPen mZeroLinePen
Definition at line 1607 of file qcustomplot.h.
Referenced by drawGridLines(), and zeroLinePen().
double value
Definition at line 145 of file qcustomplot.h.
Referenced by QCPGraph::addData(), QCPCurve::addData(), QCPBars::addData(), Slider::adjust_value(), QCPAxis::coordToPixel(), QCPCurve::getCurveData(), QCPGraph::getStepRightPlotData(), Slider::keyPressEvent(), QComplexNumber< T >::operator*=(), QComplexNumber< T >::operator/=(), QCPAbstractPlottable::pixelsToCoords(), QCPAxis::pixelToCoord(), QCPStatisticalBox::setLowerQuartile(), QCPStatisticalBox::setMaximum(), QCPStatisticalBox::setMedian(), QCPStatisticalBox::setMinimum(), QCPStatisticalBox::setUpperQuartile(), and Slider::update_value().
double valueErrorMinus
Definition at line 147 of file qcustomplot.h.
double valueErrorPlus
Definition at line 147 of file qcustomplot.h.
QCPAxis* xAxis
Definition at line 2076 of file qcustomplot.h.
Referenced by addGraph(), mouseReleaseEvent(), selectedAxes(), setupFullAxesBox(), updateAxisRect(), and ~QCustomPlot().
QCPAxis * xAxis2
Definition at line 2076 of file qcustomplot.h.
Referenced by mouseReleaseEvent(), selectedAxes(), setupFullAxesBox(), updateAxisRect(), and ~QCustomPlot().
QCPAxis * yAxis
Definition at line 2076 of file qcustomplot.h.
Referenced by addGraph(), mouseReleaseEvent(), selectedAxes(), setupFullAxesBox(), updateAxisRect(), and ~QCustomPlot().
QCPAxis * yAxis2
Definition at line 2076 of file qcustomplot.h.
Referenced by mouseReleaseEvent(), selectedAxes(), setupFullAxesBox(), updateAxisRect(), and ~QCustomPlot().
Author
Generated automatically by Doxygen for AQ0X from the source code.