.TH "qfouriertransformer.h" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qfouriertransformer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'qfouriercalculator\&.h'\fP
.br
\fC#include 'qwindowfunction\&.h'\fP
.br
\fC#include 'qcomplexnumber\&.h'\fP
.br
\fC#include <QMap>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQFourierTransformer\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QVector< \fBQComplexFloat\fP > \fBQComplexVector\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef QVector<\fBQComplexFloat\fP> \fBQComplexVector\fP"

.PP
Definition at line 49 of file qfouriertransformer\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
