QFourierCalculator
NAME
QFourierCalculator -
SYNOPSIS
#include <qfouriercalculator.h>
Inherited by QFourierFixedCalculator< T >, and QFourierVariableCalculator.
Public Member Functions
QFourierCalculator ()
virtual ~QFourierCalculator ()
virtual void setData (float input[], float output[]=0)
virtual void setSize (int size)
virtual int size ()
virtual void forward ()=0
virtual void inverse ()=0
virtual void rescale ()=0
Protected Attributes
float * mInput
float * mOutput
int mSize
Detailed Description
Definition at line 46 of file qfouriercalculator.h.
Constructor & Destructor Documentation
QFourierCalculator::QFourierCalculator ()
Definition at line 44 of file qfouriercalculator.cpp.
References mInput, mOutput, and mSize.
{
    mInput = 0;
    mOutput = 0;
    mSize = 0;
}
QFourierCalculator::~QFourierCalculator () [virtual]
Definition at line 51 of file qfouriercalculator.cpp.
{
}
Member Function Documentation
virtual void QFourierCalculator::forward () [pure virtual]
Implemented in QFourierFixedCalculator< T >, and QFourierVariableCalculator.
Referenced by QFourierTransformer::forwardTransform().
virtual void QFourierCalculator::inverse () [pure virtual]
Implemented in QFourierFixedCalculator< T >, and QFourierVariableCalculator.
Referenced by QFourierTransformer::inverseTransform().
virtual void QFourierCalculator::rescale () [pure virtual]
Implemented in QFourierFixedCalculator< T >, and QFourierVariableCalculator.
Referenced by QFourierTransformer::rescale().
void QFourierCalculator::setData (floatinput[], floatoutput[] = 0) [virtual]
Definition at line 55 of file qfouriercalculator.cpp.
References mInput, and mOutput.
Referenced by QFourierTransformer::forwardTransform(), QFourierTransformer::inverseTransform(), and QFourierTransformer::rescale().
{
    mInput = input;
    mOutput = output;
}
void QFourierCalculator::setSize (intsize) [virtual]
Reimplemented in QFourierFixedCalculator< T >, and QFourierVariableCalculator.
Definition at line 61 of file qfouriercalculator.cpp.
References mSize, and size().
Referenced by QFourierVariableCalculator::setSize(), and QFourierTransformer::setSize().
{
    mSize = size;
}
int QFourierCalculator::size () [virtual]
Definition at line 66 of file qfouriercalculator.cpp.
References mSize.
Referenced by setSize().
{
    return mSize;
}
Member Data Documentation
float* QFourierCalculator::mInput [protected]
Definition at line 63 of file qfouriercalculator.h.
Referenced by QFourierFixedCalculator< T >::forward(), QFourierVariableCalculator::forward(), QFourierFixedCalculator< T >::inverse(), QFourierVariableCalculator::inverse(), QFourierCalculator(), QFourierVariableCalculator::rescale(), QFourierFixedCalculator< T >::rescale(), and setData().
float* QFourierCalculator::mOutput [protected]
Definition at line 64 of file qfouriercalculator.h.
Referenced by QFourierFixedCalculator< T >::forward(), QFourierVariableCalculator::forward(), QFourierFixedCalculator< T >::inverse(), QFourierVariableCalculator::inverse(), QFourierCalculator(), and setData().
int QFourierCalculator::mSize [protected]
Definition at line 65 of file qfouriercalculator.h.
Referenced by QFourierCalculator(), setSize(), QFourierVariableCalculator::setSize(), and size().
Author
Generated automatically by Doxygen for AQ0X from the source code.