QFourierVariableCalculator
NAME
QFourierVariableCalculator -
SYNOPSIS
#include <qfouriervariablecalculator.h>
Inherits QFourierCalculator.
Public Member Functions
QFourierVariableCalculator ()
~QFourierVariableCalculator ()
void setSize (int size)
void forward ()
void inverse ()
void rescale ()
Protected Attributes
ffft::FFTReal< float > * mFourierTransform
Detailed Description
Definition at line 48 of file qfouriervariablecalculator.h.
Constructor & Destructor Documentation
QFourierVariableCalculator::QFourierVariableCalculator ()
Definition at line 44 of file qfouriervariablecalculator.cpp.
References mFourierTransform.
    : QFourierCalculator()
{
    mFourierTransform = 0;
}
QFourierVariableCalculator::~QFourierVariableCalculator ()
Definition at line 50 of file qfouriervariablecalculator.cpp.
References mFourierTransform.
{
    if(mFourierTransform != 0)
    {
        delete mFourierTransform;
    }
}
Member Function Documentation
void QFourierVariableCalculator::forward () [virtual]
Implements QFourierCalculator.
Definition at line 72 of file qfouriervariablecalculator.cpp.
References ffft::FFTReal< DT >::do_fft(), mFourierTransform, QFourierCalculator::mInput, and QFourierCalculator::mOutput.
{
    mFourierTransform->do_fft(mOutput, mInput);
}
void QFourierVariableCalculator::inverse () [virtual]
Implements QFourierCalculator.
Definition at line 77 of file qfouriervariablecalculator.cpp.
References ffft::FFTReal< DT >::do_ifft(), mFourierTransform, QFourierCalculator::mInput, and QFourierCalculator::mOutput.
{
    mFourierTransform->do_ifft(mInput, mOutput);
}
void QFourierVariableCalculator::rescale () [virtual]
Implements QFourierCalculator.
Definition at line 82 of file qfouriervariablecalculator.cpp.
References mFourierTransform, QFourierCalculator::mInput, and ffft::FFTReal< DT >::rescale().
{
    mFourierTransform->rescale(mInput);
}
void QFourierVariableCalculator::setSize (intsize) [virtual]
Reimplemented from QFourierCalculator.
Definition at line 58 of file qfouriervariablecalculator.cpp.
References ffft::FFTReal< DT >::get_length(), mFourierTransform, QFourierCalculator::mSize, and QFourierCalculator::setSize().
{
    QFourierCalculator::setSize(size);
    if(mFourierTransform == 0)
    {
        mFourierTransform = new ffft::FFTReal<float>(mSize);
    }
    else if(mFourierTransform->get_length() != mSize)
    {
        delete mFourierTransform;
        mFourierTransform = new ffft::FFTReal<float>(mSize);
    }
}
Member Data Documentation
ffft::FFTReal<float>* QFourierVariableCalculator::mFourierTransform [protected]
Definition at line 62 of file qfouriervariablecalculator.h.
Referenced by forward(), inverse(), QFourierVariableCalculator(), rescale(), setSize(), and ~QFourierVariableCalculator().
Author
Generated automatically by Doxygen for AQ0X from the source code.