.TH "qfourierfixedcalculator.h" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qfourierfixedcalculator.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./fft/fftreal/FFTRealFixLen\&.h'\fP
.br
\fC#include 'qfouriercalculator\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQFourierFixedCalculator< T >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
