QFourierTransformer
NAME
QFourierTransformer -
SYNOPSIS
#include <qfouriertransformer.h>
Public Types
enum Direction { Forward = 0, Inverse = 1 }
enum Initialization { VariableSize = 0, FixedSize = 1, InvalidSize = 2 }
Public Member Functions
QFourierTransformer (int size=0, QString functionName='')
~QFourierTransformer ()
Initialization setSize (int size)
bool setWindowFunction (QString functionName)
QStringList windowFunctions ()
void transform (float input[], float output[], Direction direction=QFourierTransformer::Forward)
void forwardTransform (float *input, float *output)
void inverseTransform (float input[], float output[])
void rescale (float input[])
void conjugate (float input[])
QComplexVector toComplex (float input[])
Protected Member Functions
void initialize ()
int sizeToKey (int size)
bool isValidSize (int value)
Detailed Description
Definition at line 51 of file qfouriertransformer.h.
Member Enumeration Documentation
enum QFourierTransformer::Direction
Enumerator
Forward
Inverse
Definition at line 56 of file qfouriertransformer.h.
        {
            Forward = 0,
            Inverse = 1
        };
enum QFourierTransformer::Initialization
Enumerator
VariableSize
FixedSize
InvalidSize
Definition at line 62 of file qfouriertransformer.h.
        {
            VariableSize = 0,
            FixedSize = 1,
            InvalidSize = 2
        };
Constructor & Destructor Documentation
QFourierTransformer::QFourierTransformer (intsize = 0, QStringfunctionName = '')
Definition at line 45 of file qfouriertransformer.cpp.
References QWindowFunctionManager< T >::functions(), initialize(), setSize(), and setWindowFunction().
{
    mWindowFunctions = QWindowFunctionManager<float>::functions();
    mWindowFunction = 0;
    mCalculator = 0;
    initialize();
    setSize(size);
    setWindowFunction(functionName);
}
QFourierTransformer::~QFourierTransformer ()
Definition at line 55 of file qfouriertransformer.cpp.
{
    qDeleteAll(mFixedCalculators.begin(), mFixedCalculators.end());
    mFixedCalculators.clear();
    delete mVariableCalculator;
    if(mWindowFunction != 0)
    {
        delete mWindowFunction;
    }
}
Member Function Documentation
void QFourierTransformer::conjugate (floatinput[])
Definition at line 185 of file qfouriertransformer.cpp.
{
    for(int i = mSize / 2 + 1; i < mSize; ++i)
    {
        input[i] = -input[i];
    }
}
void QFourierTransformer::forwardTransform (float *input, float *output)
Definition at line 130 of file qfouriertransformer.cpp.
References QWindowFunction< T >::apply(), QFourierCalculator::forward(), and QFourierCalculator::setData().
Referenced by emu_data_editor::emu_data_editor(), transform(), and emu_data_editor::update_curve().
{
    if(mWindowFunction != 0)
    {
        mWindowFunction->apply(input, mSize);
    }
    mCalculator->setData(input, output);
    mCalculator->forward();
}
void QFourierTransformer::initialize () [protected]
Definition at line 152 of file qfouriertransformer.cpp.
Referenced by QFourierTransformer().
{
    mFixedCalculators.insert(3, new QFourierFixedCalculator<3>());
    mFixedCalculators.insert(4, new QFourierFixedCalculator<4>());
    mFixedCalculators.insert(5, new QFourierFixedCalculator<5>());
    mFixedCalculators.insert(6, new QFourierFixedCalculator<6>());
    mFixedCalculators.insert(7, new QFourierFixedCalculator<7>());
    mFixedCalculators.insert(8, new QFourierFixedCalculator<8>());
    mFixedCalculators.insert(9, new QFourierFixedCalculator<9>());
    mFixedCalculators.insert(10, new QFourierFixedCalculator<10>());
    mFixedCalculators.insert(11, new QFourierFixedCalculator<11>());
    mFixedCalculators.insert(12, new QFourierFixedCalculator<12>());
    mFixedCalculators.insert(13, new QFourierFixedCalculator<13>());
    mFixedCalculators.insert(14, new QFourierFixedCalculator<14>());
    mVariableCalculator = new QFourierVariableCalculator();
}
void QFourierTransformer::inverseTransform (floatinput[], floatoutput[])
Definition at line 140 of file qfouriertransformer.cpp.
References QFourierCalculator::inverse(), and QFourierCalculator::setData().
Referenced by transform().
{
    mCalculator->setData(input, output);
    mCalculator->inverse();
}
bool QFourierTransformer::isValidSize (intvalue) [protected]
Definition at line 180 of file qfouriertransformer.cpp.
Referenced by setSize(), and setWindowFunction().
{
    return ((value > 0) && ((value & (~value + 1)) == value));
}
void QFourierTransformer::rescale (floatinput[])
Definition at line 146 of file qfouriertransformer.cpp.
References QFourierCalculator::rescale(), and QFourierCalculator::setData().
{
    mCalculator->setData(input);
    mCalculator->rescale();
}
QFourierTransformer::Initialization QFourierTransformer::setSize (intsize)
Definition at line 66 of file qfouriertransformer.cpp.
References QWindowFunction< T >::create(), FixedSize, InvalidSize, isValidSize(), key, QFourierCalculator::setSize(), sizeToKey(), and VariableSize.
Referenced by emu_data_editor::emu_data_editor(), and QFourierTransformer().
{
    if(isValidSize(size))
    {
        mSize = size;
        if(mWindowFunction != 0)
        {
            mWindowFunction->create(mSize);
        }
        int key = sizeToKey(mSize);
        if(mFixedCalculators.contains(key))
        {
            mCalculator = mFixedCalculators[key];
            return QFourierTransformer::FixedSize;
        }
        else
        {
            mCalculator = mVariableCalculator;
            mCalculator->setSize(mSize);
            return QFourierTransformer::VariableSize;
        }
    }
    mSize = 0;
    return QFourierTransformer::InvalidSize;
}
bool QFourierTransformer::setWindowFunction (QStringfunctionName)
Definition at line 92 of file qfouriertransformer.cpp.
References QWindowFunction< T >::create(), QWindowFunctionManager< T >::createFunction(), and isValidSize().
Referenced by emu_data_editor::emu_data_editor(), and QFourierTransformer().
{
    for(int i = 0; i < mWindowFunctions.size(); ++i)
    {
        if(functionName.trimmed().toLower().replace("function", "") == mWindowFunctions[i].trimmed().toLower().replace("function", ""))
        {
            if(mWindowFunction != 0)
            {
                delete mWindowFunction;
            }
            mWindowFunction = QWindowFunctionManager<float>::createFunction(functionName);
            if(mWindowFunction != 0 && isValidSize(mSize))
            {
                mWindowFunction->create(mSize);
            }
            return true;
        }
    }
    return false;
}
int QFourierTransformer::sizeToKey (intsize) [protected]
Definition at line 170 of file qfouriertransformer.cpp.
Referenced by setSize().
{
    float result = log(float(size)) / log(2.0);
    if(result == float(int(result)))
    {
        return result;
    }
    return -1;
}
QComplexVector QFourierTransformer::toComplex (floatinput[])
Definition at line 193 of file qfouriertransformer.cpp.
{
    int last = mSize / 2;
    QVector<QComplexFloat> result(last + 1);
    result[0] = QComplexFloat(input[0], 0);
    for(int i = 1; i < last; ++i)
    {
        result[i] = QComplexFloat(input[i], -input[last + i]);
    }
    result[last] = QComplexFloat(input[last], 0);
    return result;
}
void QFourierTransformer::transform (floatinput[], floatoutput[], Directiondirection = QFourierTransformer::Forward)
Definition at line 118 of file qfouriertransformer.cpp.
References Forward, forwardTransform(), and inverseTransform().
{
    if(direction == QFourierTransformer::Forward)
    {
        forwardTransform(input, output);
    }
    else
    {
        inverseTransform(input, output);
    }
}
QStringList QFourierTransformer::windowFunctions ()
Definition at line 113 of file qfouriertransformer.cpp.
{
    return mWindowFunctions;
}
Author
Generated automatically by Doxygen for AQ0X from the source code.