QFourierFixedCalculator< T >
NAME
QFourierFixedCalculator< T > -
SYNOPSIS
#include <qfourierfixedcalculator.h>
Inherits QFourierCalculator.
Public Member Functions
QFourierFixedCalculator ()
void setSize (int size)
void forward ()
void inverse ()
void rescale ()
Protected Attributes
ffft::FFTRealFixLen< T > mFourierTransform
Detailed Description
template<int T>class QFourierFixedCalculator< T >
Definition at line 49 of file qfourierfixedcalculator.h.
Constructor & Destructor Documentation
template<int T> QFourierFixedCalculator< T >::QFourierFixedCalculator ()
Definition at line 45 of file qfourierfixedcalculator.cpp.
References ffft::FFTRealFixLen< LL2 >::get_length(), QFourierFixedCalculator< T >::mFourierTransform, and QFourierFixedCalculator< T >::setSize().
    : QFourierCalculator()
{
    setSize(mFourierTransform.get_length());
}
Member Function Documentation
template<int T> void QFourierFixedCalculator< T >::forward () [virtual]
Implements QFourierCalculator.
Definition at line 57 of file qfourierfixedcalculator.cpp.
References QFourierCalculator::mInput, and QFourierCalculator::mOutput.
{
    QFourierFixedCalculator<T>::mFourierTransform.do_fft(QFourierCalculator::mOutput, QFourierCalculator::mInput);
}
template<int T> void QFourierFixedCalculator< T >::inverse () [virtual]
Implements QFourierCalculator.
Definition at line 63 of file qfourierfixedcalculator.cpp.
References QFourierCalculator::mInput, and QFourierCalculator::mOutput.
{
    QFourierFixedCalculator<T>::mFourierTransform.do_ifft(QFourierCalculator::mInput, QFourierCalculator::mOutput);
}
template<int T> void QFourierFixedCalculator< T >::rescale () [virtual]
Implements QFourierCalculator.
Definition at line 69 of file qfourierfixedcalculator.cpp.
References QFourierCalculator::mInput, and QFourierFixedCalculator< T >::rescale().
Referenced by QFourierFixedCalculator< T >::rescale().
{
    QFourierFixedCalculator<T>::mFourierTransform.rescale(QFourierCalculator::mInput);
}
template<int T> void QFourierFixedCalculator< T >::setSize (intsize) [virtual]
Reimplemented from QFourierCalculator.
Definition at line 52 of file qfourierfixedcalculator.cpp.
Referenced by QFourierFixedCalculator< T >::QFourierFixedCalculator().
{
}
Member Data Documentation
template<int T> ffft::FFTRealFixLen<T> QFourierFixedCalculator< T >::mFourierTransform [protected]
Definition at line 62 of file qfourierfixedcalculator.h.
Referenced by QFourierFixedCalculator< T >::QFourierFixedCalculator().
Author
Generated automatically by Doxygen for AQ0X from the source code.