qrc_icons.cpp
NAME
qrc_icons.cpp -
SYNOPSIS
#include <QtCore/qglobal.h>
Functions
QT_BEGIN_NAMESPACE
Q_CORE_EXPORT bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"
Q_CORE_EXPORT bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
QT_END_NAMESPACE int
QT_MANGLE_NAMESPACE() qInitResources_icons ()"
Q_CONSTRUCTOR_FUNCTION (QT_MANGLE_NAMESPACE(qInitResources_icons)) int QT_MANGLE_NAMESPACE(qCleanupResources_icons)()
Function Documentation
Q_CONSTRUCTOR_FUNCTION (QT_MANGLE_NAMESPACE(qInitResources_icons))
Definition at line 54580 of file qrc_icons.cpp.
References qUnregisterResourceData().
{
    QT_PREPEND_NAMESPACE(qUnregisterResourceData)
       (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
    return 1;
}
QT_END_NAMESPACE int QT_MANGLE_NAMESPACE() qInitResources_icons ()
Definition at line 54573 of file qrc_icons.cpp.
References qRegisterResourceData().
{
    QT_PREPEND_NAMESPACE(qRegisterResourceData)
        (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
    return 1;
}
QT_BEGIN_NAMESPACE Q_CORE_EXPORT bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
Referenced by qInitResources_icons().
Q_CORE_EXPORT bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
Referenced by Q_CONSTRUCTOR_FUNCTION().
Author
Generated automatically by Doxygen for AQ0X from the source code.