qrc_logo.cpp
NAME
qrc_logo.cpp -
SYNOPSIS
#include <QtCore/qglobal.h>
Functions
QT_BEGIN_NAMESPACE
Q_CORE_EXPORT bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"
Q_CORE_EXPORT bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
QT_END_NAMESPACE int
QT_MANGLE_NAMESPACE() qInitResources_logo ()"
Q_CONSTRUCTOR_FUNCTION (QT_MANGLE_NAMESPACE(qInitResources_logo)) int QT_MANGLE_NAMESPACE(qCleanupResources_logo)()
Function Documentation
Q_CONSTRUCTOR_FUNCTION (QT_MANGLE_NAMESPACE(qInitResources_logo))
Definition at line 6039 of file qrc_logo.cpp.
References qUnregisterResourceData().
{
    QT_PREPEND_NAMESPACE(qUnregisterResourceData)
       (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
    return 1;
}
QT_END_NAMESPACE int QT_MANGLE_NAMESPACE() qInitResources_logo ()
Definition at line 6032 of file qrc_logo.cpp.
References qRegisterResourceData().
{
    QT_PREPEND_NAMESPACE(qRegisterResourceData)
        (0x01, qt_resource_struct, qt_resource_name, qt_resource_data);
    return 1;
}
QT_BEGIN_NAMESPACE Q_CORE_EXPORT bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
Referenced by qInitResources_logo().
Q_CORE_EXPORT bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
Referenced by Q_CONSTRUCTOR_FUNCTION().
Author
Generated automatically by Doxygen for AQ0X from the source code.