QWindowFunction< T >
NAME
QWindowFunction< T > -
SYNOPSIS
#include <qwindowfunction.h>
Inherited by QHammingFunction< T >, QHannFunction< T >, and QRectangularFunction< T >.
Public Member Functions
void apply (T *data, int size)
void create (int size)
Protected Member Functions
void fillWindow (int size)
virtual T calculate (int currentSample, int totalSamples)=0
Protected Attributes
QWindow mWindow
Detailed Description
template<typename T>class QWindowFunction< T >
Definition at line 58 of file qwindowfunction.h.
Member Function Documentation
template<typename T> void QWindowFunction< T >::apply (T *data, intsize)
Definition at line 51 of file qwindowfunction.cpp.
Referenced by QFourierTransformer::forwardTransform().
{
    for(int i = 0; i < size; ++i)
    {
        data[i] *= mWindow[i];
    }
}
template<typename T> virtual T QWindowFunction< T >::calculate (intcurrentSample, inttotalSamples) [protected], [pure virtual]
Implemented in QHannFunction< T >, QHammingFunction< T >, and QRectangularFunction< T >.
template<typename T > void QWindowFunction< T >::create (intsize)
Definition at line 60 of file qwindowfunction.cpp.
Referenced by QFourierTransformer::setSize(), and QFourierTransformer::setWindowFunction().
{
    if(size != mWindow.size())
    {
        mWindow.clear();
        mWindow.resize(size);
        fillWindow(size);
    }
}
template<typename T > void QWindowFunction< T >::fillWindow (intsize) [protected]
Definition at line 71 of file qwindowfunction.cpp.
{
    for(int i = 0; i < size; ++i)
    {
        mWindow[i] = calculate(i, size);
    }
}
Member Data Documentation
template<typename T> QWindow QWindowFunction< T >::mWindow [protected]
Definition at line 75 of file qwindowfunction.h.
Author
Generated automatically by Doxygen for AQ0X from the source code.