.TH "qwindowfunction.h" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qwindowfunction.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QList>\fP
.br
\fC#include <QStringList>\fP
.br
\fC#include <QVector>\fP
.br
\fC#include 'math\&.h'\fP
.br
\fC#include <qmath\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQWindowFunction< T >\fP"
.br
.ti -1c
.RI "class \fBQWindowFunctionManager< T >\fP"
.br
.ti -1c
.RI "class \fBQRectangularFunction< T >\fP"
.br
.ti -1c
.RI "class \fBQHammingFunction< T >\fP"
.br
.ti -1c
.RI "class \fBQHannFunction< T >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
