.TH "recordpreview.h" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
recordpreview.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'typedef\&.h'\fP
.br
\fC#include 'define\&.h'\fP
.br
\fC#include 'storage_structure\&.h'\fP
.br
\fC#include <QVector>\fP
.br
\fC#include <QMainWindow>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrecordPreview\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
