recordPreview
NAME
recordPreview -
SYNOPSIS
#include <recordpreview.h>
Inherits QMainWindow.
Public Member Functions
recordPreview (QString type, QVector< Uint16 > data, QWidget *parent=0)
recordPreview (QString type, QVector< Uint16 > data, event_data_t event_data, QWidget *parent=0)
recordPreview (QString type, QVector< double > *data1, QVector< double > *data2=NULL, QVector< double > *data3=NULL, QWidget *parent=0)
~recordPreview ()
double max (QVector< double > val)
Detailed Description
Definition at line 15 of file recordpreview.h.
Constructor & Destructor Documentation
recordPreview::recordPreview (QStringtype, QVector< Uint16 >data, QWidget *parent = 0) [explicit]
Definition at line 11 of file recordpreview.cpp.
References Ui_recordPreview::actionWinDataPlot, Ui_recordPreview::actionWinEventPlot, ADC_VAL_MAPPING_FACTOR, Ui_recordPreview::centralwidget, Ui_recordPreview::curve_data, Ui_recordPreview::dockWidgetPlot, Ui_recordPreview::dockWidgetPlot_event_history, Ui_recordPreview::setupUi(), WAVEFORM_0_TO_3_3, and WAVEFORM_PLUS_MINUS_1_65.
                                                                                :
    QMainWindow(parent),
    ui(new Ui::recordPreview)
{
    ui->setupUi(this);
    this->setWindowTitle(type);
    dir_default = ((MainWindow *)parent)->dir_default;
    ui->centralwidget->setVisible(false);
    ui->dockWidgetPlot->setWidget(ui->curve_data);
    ui->actionWinDataPlot->setChecked(true);
    ui->actionWinEventPlot->setChecked(false);
    ui->actionWinEventPlot->setEnabled(false);
    ui->dockWidgetPlot_event_history->setVisible(false);
    this->rc_data = data;
    measured_values.resize(data.length());
    time.resize(data.length());
    history_dfdt.resize(data.length());
    
    for (int var = 0; var < data.length(); ++var) {
        time[var]=var;
        measured_values[var]=(rc_data[var]*ADC_VAL_MAPPING_FACTOR) - (type.contains("MFIELD")?1.65:0);
        if(var > 0)
            history_dfdt[var] = abs(measured_values[var])- abs(measured_values[var-1]);
    }
    plot_curve(time,measured_values,
              (type.contains("MFIELD")?WAVEFORM_PLUS_MINUS_1_65:WAVEFORM_0_TO_3_3));
}
recordPreview::recordPreview (QStringtype, QVector< Uint16 >data, event_data_tevent_data, QWidget *parent = 0) [explicit]
Definition at line 52 of file recordpreview.cpp.
References Ui_recordPreview::actionWinDataPlot, Ui_recordPreview::actionWinEventPlot, ADC_VAL_MAPPING_FACTOR, Ui_recordPreview::centralwidget, Ui_recordPreview::curve_data, Ui_recordPreview::curve_dfdt, Ui_recordPreview::dockWidgetPlot, Ui_recordPreview::dockWidgetPlot_event_history, Ui_recordPreview::setupUi(), WAVEFORM_0_TO_3_3, and WAVEFORM_PLUS_MINUS_1_65.
                                                                                                        :
    QMainWindow(parent),
    ui(new Ui::recordPreview)
{
    ui->setupUi(this);
    this->setWindowTitle(type);
    ui->centralwidget->setVisible(false);
    ui->dockWidgetPlot->setWidget(ui->curve_data);
    ui->dockWidgetPlot_event_history->setWidget(ui->curve_dfdt);
    ui->actionWinDataPlot->setChecked(true);
    ui->actionWinEventPlot->setChecked(true);
    this->rc_data = data;
    this->event_history = event_data;
    measured_values.resize(data.length());
    history_amp.resize(data.length());
    history_dfdt.resize(data.length());
    time.resize(data.length());
    for (int var = 0; var < data.length(); ++var) {
        time[var]=var;
        measured_values[var]=(rc_data[var]*ADC_VAL_MAPPING_FACTOR)-(type.contains("MFIELD")?1.65:0);
    }
    //TODO: history amp shows when the module is activated
    /*
    for (int var = 0; var < MAX_EVENT_OBSERVATION_LENGTH; ++var) {
        history_amp[var + PRE_ACT_RECORD_BUFF_SIZE + event_history.offset]
                =(event_history.ignal_level[var]*ADC_VAL_MAPPING_FACTOR) - (type.contains("MFIELD")?1.65:0);
    }
    */
    plot_curve(time,measured_values,
              (type.contains("MFIELD")?WAVEFORM_PLUS_MINUS_1_65:WAVEFORM_0_TO_3_3),
              history_amp
              );
}
recordPreview::recordPreview (QStringtype, QVector< double > *data1, QVector< double > *data2 = NULL, QVector< double > *data3 = NULL, QWidget *parent = 0) [explicit]
Definition at line 102 of file recordpreview.cpp.
References Ui_recordPreview::actionWinDataPlot, Ui_recordPreview::actionWinEventPlot, Ui_recordPreview::centralwidget, Ui_recordPreview::curve_data, Ui_recordPreview::curve_dfdt, Ui_recordPreview::dockWidgetPlot, Ui_recordPreview::dockWidgetPlot_event_history, max(), Ui_recordPreview::setupUi(), WAVEFORM_0_TO_3_3, and WAVEFORM_PLUS_MINUS_1_65.
                                                                                                                                  :
    QMainWindow(parent),
    ui(new Ui::recordPreview)
{
    ui->setupUi(this);
    this->setWindowTitle(type);
    ui->centralwidget->setVisible(false);
    ui->dockWidgetPlot->setWidget(ui->curve_data);
    ui->dockWidgetPlot_event_history->setWidget(ui->curve_dfdt);
    ui->actionWinDataPlot->setChecked(true);
    measured_values.resize(data1->length());
    for (int var = 0; var < data1->length(); ++var)
      measured_values[var] = data1->at(var);
   // memmove(&measured_values,data1,sizeof(measured_values));
    time.resize(data1->length());
    for (int var = 0; var < data1->length(); ++var)
        time[var]=var;
    if((data2->length() > 0) && (data3->length()>0)){
        ui->actionWinEventPlot->setChecked(true);
        history_amp.resize(data2->length());
        memmove(&history_amp,data2,sizeof(history_amp));
        history_dfdt.resize(data3->length());
        memmove(&history_dfdt,data3,sizeof(history_dfdt));
        plot_curve(time,measured_values,
                  (type.contains("MFIELD")?WAVEFORM_PLUS_MINUS_1_65:WAVEFORM_0_TO_3_3),
                  history_amp
                  );
        plot_event(time,history_dfdt,max(history_dfdt));
    }else{
        ui->actionWinEventPlot->setChecked(false);
        ui->actionWinEventPlot->setEnabled(false);
        ui->dockWidgetPlot_event_history->setVisible(false);
        plot_curve(time,measured_values,
                  type.contains("MFIELD")?WAVEFORM_PLUS_MINUS_1_65:WAVEFORM_0_TO_3_3);
    }
}
recordPreview::~recordPreview ()
Definition at line 162 of file recordpreview.cpp.
{
    delete ui;
}
Member Function Documentation
double recordPreview::max (QVector< double >val)
Definition at line 168 of file recordpreview.cpp.
Referenced by recordPreview().
                                            {
    double result = 0;
    for (int var = 0; var < val.length(); ++var)
        result = (result > val[var])?result:val[var];
    return result;
}
Author
Generated automatically by Doxygen for AQ0X from the source code.