.TH "settingsdialog.cpp" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
settingsdialog.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'settingsdialog\&.h'\fP
.br
\fC#include 'ui_settingsdialog\&.h'\fP
.br
\fC#include <QtSerialPort/QSerialPortInfo>\fP
.br
\fC#include <QIntValidator>\fP
.br
\fC#include <QLineEdit>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
