Slider
NAME
Slider -
SYNOPSIS
#include <slider.h>
Inherits QSlider.
Public Slots
void edit_point_selection (bool status)
void edit_point_deselection (bool status)
void adjust_value (Int16 val)
void set_value (double val, Uint8 type)
void update_value ()
void set_status (Uint8 select)
Signals
void action_set_value (double val, Uint8 type)
void update_curve_signal ()
void selection (bool clear)
Public Member Functions
Slider (Uint16 id, QWidget *parent=0)
Public Attributes
union {
Uint8 all
   struct {
Uint8 point_selected:1
Uint8 point_selection_mode:1
Uint8 point_deselection_mode:1
Uint8 point_focuse_en:1
   } bits
} flags
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *e)
virtual void mousePressEvent (QMouseEvent *e)
virtual void mouseDoubleClickEvent (QMouseEvent *e)
virtual void contextMenuEvent (QContextMenuEvent *e)
void enterEvent (QEvent *e)
void leaveEvent (QEvent *e)
bool eventFilter (QObject *object, QEvent *event)
Detailed Description
Definition at line 53 of file slider.h.
Constructor & Destructor Documentation
Slider::Slider (Uint16id, QWidget *parent = 0) [explicit]
Definition at line 14 of file slider.cpp.
References action_set_value(), adjust_value(), edit_point_deselection(), edit_point_selection(), flags, selection(), set_status(), set_value(), and update_value().
    : QSlider(parent)
{
    this->id = id;
    this->parent = (emu_data_editor *)parent;
    setMaximumWidth(40/*item width*/);
    setSizePolicy(QSizePolicy::MinimumExpanding,QSizePolicy::Expanding);
    current_style = "QSlider { width: 5px; border: none; }"
            "QSlider::groove:veritcal {"
            "border: none;"
            "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #000000, stop:1 #000000);"
            "margin: 0 0 0 0;}"
            "QSlider::handle:veritcal {"
            "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);"
            "border: none;"
            "width: 5px;"
            "height: 5px;"
            "margin: 2px 2px 2px 2px;"
            "border-radius: 2px;}";
     setStyleSheet(current_style);
    // this->setSliderDown(true);
    flags.all = 0;
    connect(parent,SIGNAL(edit_point_selection(bool)),this,SLOT(edit_point_selection(bool)));
    connect(parent,SIGNAL(edit_point_deselection(bool)),this,SLOT(edit_point_deselection(bool)));
    connect(parent,SIGNAL(adjust_value(Int16)),this,SLOT(adjust_value(Int16)));
    connect(parent,SIGNAL(action_set_value(double,Uint8)),this,SLOT(set_value(double,Uint8)));
    connect(this,SIGNAL(action_set_value(double,Uint8)),parent,SLOT(action_set_value_triggered(double,Uint8)));
    connect(this,SIGNAL(selection(bool)),parent,SLOT(selection(bool)));
    connect(parent,SIGNAL(set_status(Uint8)),this,SLOT(set_status(Uint8)));
    connect(this,SIGNAL(sliderMoved(int)),this,SLOT(moved(int)));
    connect(parent,SIGNAL(update_value()),this,SLOT(update_value()));
    installEventFilter(this);
}
Member Function Documentation
void Slider::action_set_value (doubleval, Uint8type) [signal]
Definition at line 184 of file moc_slider.cpp.
Referenced by contextMenuEvent(), and Slider().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)), const_cast<void*>(reinterpret_cast<const void*>(&_t2)) };
    QMetaObject::activate(this, &staticMetaObject, 0, _a);
}
void Slider::adjust_value (Int16val) [slot]
Definition at line 69 of file slider.cpp.
References flags, SET_TYPE_ADJUST, and set_value().
Referenced by Slider().
{
    if(flags.bits.point_selected == 1){
    Int16 new_value = this->value()+val;
    if((new_value >=0)&&(new_value <=this->maximum())){
        set_value(new_value,SET_TYPE_ADJUST);
    }
    }
}
void Slider::contextMenuEvent (QContextMenuEvent *e) [protected], [virtual]
Definition at line 309 of file slider.cpp.
References action_set_value(), selection(), SET_TYPE_AC_AMPLITUDE, SET_TYPE_DC_VALUE, SET_TYPE_DEFAULT, emu_data_editor::signal_type, and WAVEFORM_PLUS_MINUS_1_65.
{
    QMenu menu;
    QMenu *waveform = menu.addMenu("Waveform");
             //waveform->setIcon(QIcon(":icons\signal"));
    QMenu *dc = waveform->addMenu("DC (Constant value)");
    QDoubleSpinBox *value_dc = new QDoubleSpinBox();
    if(this->parent->signal_type == WAVEFORM_PLUS_MINUS_1_65){
    value_dc->setMaximum(50);
    value_dc->setMinimum(-50);
    }else{
    value_dc->setMaximum(100);
    value_dc->setMinimum(0);
    }
    QWidgetAction *action_dc = new QWidgetAction(this);
    action_dc->setDefaultWidget(value_dc);
    dc->addAction(action_dc);
    QAction *set_dc = dc->addAction("Set Value");
    QMenu *ac = waveform->addMenu("AC (Sinusoid)");
    QDoubleSpinBox *value_ac = new QDoubleSpinBox();
    if(this->parent->signal_type == WAVEFORM_PLUS_MINUS_1_65){
    value_ac->setMaximum(50);
    value_ac->setMinimum(-50);
    }else{
    value_ac->setMaximum(100);
    value_ac->setMinimum(0);
    }
    QWidgetAction *action_ac = new QWidgetAction(this);
    action_ac->setDefaultWidget(value_ac);
    ac->addAction(action_ac);
    QAction *set_ac = ac->addAction("Set Value");
    QAction *select_all = menu.addAction("Select all");
    QAction *clear_all = menu.addAction("Clear selection");
    QAction *reset = menu.addAction("Reset curve");
    QAction *selectedAction = menu.exec(e->globalPos());
    if(selectedAction == set_dc)
    {
        emit action_set_value(value_dc->value(),SET_TYPE_DC_VALUE);
    }if(selectedAction == set_ac)
    {
         emit action_set_value(value_ac->value(),SET_TYPE_AC_AMPLITUDE);
    }else
    if(selectedAction == select_all)
    {
         emit selection(false);
    }else if(selectedAction == clear_all)
    {
         emit selection(true);
    }
    else if(selectedAction == reset)
    {
         emit action_set_value(0,SET_TYPE_DEFAULT);
    }
}
void Slider::edit_point_deselection (boolstatus) [slot]
Definition at line 63 of file slider.cpp.
References flags.
Referenced by Slider().
{
    flags.bits.point_deselection_mode = status;
}
void Slider::edit_point_selection (boolstatus) [slot]
Definition at line 57 of file slider.cpp.
References flags.
Referenced by Slider().
{
    flags.bits.point_selection_mode = status;
}
void Slider::enterEvent (QEvent *e) [protected]
Definition at line 286 of file slider.cpp.
{
    QSlider::enterEvent(e);
}
bool Slider::eventFilter (QObject *object, QEvent *event) [protected]
Definition at line 251 of file slider.cpp.
References flags.
{
    if (event->type() == QEvent::FocusOut)
    {
        if (object == this)
        {
               flags.bits.point_focuse_en = 0;
               setStyleSheet(current_style);
        }
    }
    if (event->type() == QEvent::FocusIn)
    {
        if (object == this)
        {
            flags.bits.point_focuse_en = 1;
            setStyleSheet("QSlider { width: 5px; border: none; }"
                         "QSlider::groove:veritcal {"
                         "border: none;"
                         "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #000000, stop:1 #000000);"
                         "margin: 0 0 0 0;}"
                         "QSlider::handle:veritcal {"
                         "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #75FF47, stop:1 #75FF47);"
                         "border: none;"
                         "width: 5px;"
                         "height: 5px;"
                         "margin: 2px 2px 2px 2px;"
                         "border-radius: 2px;}");
        }
    }
    return false;
}
void Slider::keyPressEvent (QKeyEvent *e) [protected], [virtual]
Definition at line 219 of file slider.cpp.
References flags, SET_TYPE_ADJUST, set_value(), emu_data_editor::signal_type, emu_data_editor::update_curve(), and WAVEFORM_PLUS_MINUS_1_65.
{
    if(flags.bits.point_focuse_en==1){
    if(e->key() == Qt::Key_Up){
        Int16 new_value;
        if(this->parent->signal_type ==WAVEFORM_PLUS_MINUS_1_65)
        new_value= (this->value()/2)+10;
        else
        new_value= (this->value())+10;
        if((new_value <=this->maximum())){
            set_value(new_value,SET_TYPE_ADJUST);
            this->parent->update_curve();
        }
    }else if(e->key() == Qt::Key_Down){
        Int16 new_value;
        if(this->parent->signal_type ==WAVEFORM_PLUS_MINUS_1_65)
        new_value= (this->value()/2)-10;
        else
        new_value= (this->value())-10;
        if((new_value >=0)){
            set_value(new_value,SET_TYPE_ADJUST);
            this->parent->update_curve();
        }
    }
    }
    QSlider::keyPressEvent(e);
}
void Slider::leaveEvent (QEvent *e) [protected]
Definition at line 292 of file slider.cpp.
References set_status().
{
    set_status(0);
    QSlider::leaveEvent(e);
}
void Slider::mouseDoubleClickEvent (QMouseEvent *e) [protected], [virtual]
Definition at line 304 of file slider.cpp.
{
    Q_UNUSED(e)
}
void Slider::mousePressEvent (QMouseEvent *e) [protected], [virtual]
Definition at line 299 of file slider.cpp.
{
   QSlider::mousePressEvent(e);
}
void Slider::selection (boolclear) [signal]
Definition at line 197 of file moc_slider.cpp.
Referenced by contextMenuEvent(), and Slider().
{
    void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 2, _a);
}
void Slider::set_status (Uint8select) [slot]
Definition at line 379 of file slider.cpp.
References flags.
Referenced by leaveEvent(), and Slider().
                                   {
    if (flags.bits.point_selection_mode==1 || select == 1)
    {
       flags.bits.point_selected=1;
     current_style = "QSlider { width: 5px; border: none; }"
                  "QSlider::groove:veritcal {"
                  "border: none;"
                  "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #000000, stop:1 #000000);"
                  "margin: 0 0 0 0;}"
                  "QSlider::handle:veritcal {"
                  "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #FF0000, stop:1 #FF0000);"
                  "border: none;"
                  "width: 5px;"
                  "height: 5px;"
                  "margin: 2px 2px 2px 2px;"
                  "border-radius: 2px;}";
     setStyleSheet(current_style);
    }else if (flags.bits.point_deselection_mode==1 || select==2)
    {
       flags.bits.point_selected=0;
       current_style = "QSlider { width: 5px; border: none; }"
                    "QSlider::groove:veritcal {"
                    "border: none;"
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #000000, stop:1 #000000);"
                    "margin: 0 0 0 0;}"
                    "QSlider::handle:veritcal {"
                    "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);"
                    "border: none;"
                    "width: 5px;"
                    "height: 5px;"
                    "margin: 2px 2px 2px 2px;"
                    "border-radius: 2px;}";
       setStyleSheet(current_style);
    }
}
void Slider::set_value (doubleval, Uint8type) [slot]
Definition at line 102 of file slider.cpp.
References ADC_VAL_MAPPING_FACTOR, emu_data_editor::emu_data_yvalue, FAST_TIMER_SAMPLING_RATE, flags, SCAN_FREQ, SET_TYPE_AC_AMPLITUDE, SET_TYPE_ADJUST, SET_TYPE_DC_VALUE, SET_TYPE_DEFAULT, emu_data_editor::signal_amplitude, emu_data_editor::signal_freq, emu_data_editor::signal_phase, emu_data_editor::signal_type, and WAVEFORM_PLUS_MINUS_1_65.
Referenced by adjust_value(), keyPressEvent(), Slider(), and update_value().
{
    switch (type) {
    case SET_TYPE_DC_VALUE:
     {
        if(this->flags.bits.point_selected == 1){
            if(this->parent->signal_type ==WAVEFORM_PLUS_MINUS_1_65)
            this->setValue(2*(val)/ADC_VAL_MAPPING_FACTOR);
            else
            this->setValue((val)/ADC_VAL_MAPPING_FACTOR);
        this->parent->emu_data_yvalue[this->id]= val;
        Uint16 interval = (Uint16)(SCAN_FREQ/(2*this->parent->signal_freq));
        if((this->id + interval) < this->parent->emu_data_yvalue.length())
        this->parent->emu_data_yvalue[this->id + interval]=
        (this->parent->signal_type ==WAVEFORM_PLUS_MINUS_1_65)
        ?(-1*val):val;
        }
        break;
    }
    case SET_TYPE_AC_AMPLITUDE:
      {
        if(this->flags.bits.point_selected == 1){
        double freq = this->parent->signal_freq;
        double phase = this->parent->signal_phase;
        double new_val = val*sin(2*M_PI*freq*this->id*FAST_TIMER_SAMPLING_RATE - phase);
        Uint16 interval = (Uint16)(SCAN_FREQ/(2*this->parent->signal_freq));
        this->parent->emu_data_yvalue[this->id]= new_val;
       if((this->id + interval) < this->parent->emu_data_yvalue.length())
        this->parent->emu_data_yvalue[this->id + interval]=
        (this->parent->signal_type ==WAVEFORM_PLUS_MINUS_1_65)
        ?(-1*new_val):new_val;
        if(this->parent->signal_type ==WAVEFORM_PLUS_MINUS_1_65)
        this->setValue((2*new_val)/ADC_VAL_MAPPING_FACTOR);
        else
        this->setValue((new_val)/ADC_VAL_MAPPING_FACTOR);
        }
    break;
     }
    case SET_TYPE_DEFAULT:
    {
        double amp = this->parent->signal_amplitude;
        double freq = this->parent->signal_freq;
        double phase = this->parent->signal_phase;
        double new_val = amp*sin(2*M_PI*freq*this->id*FAST_TIMER_SAMPLING_RATE - phase);
        Uint16 interval = (Uint16)(SCAN_FREQ/(2*this->parent->signal_freq));
        this->parent->emu_data_yvalue[this->id]= new_val;
        if((this->id + interval) < this->parent->emu_data_yvalue.length())
        this->parent->emu_data_yvalue[this->id + interval]=
        (this->parent->signal_type ==WAVEFORM_PLUS_MINUS_1_65)
        ?(-1*new_val):new_val;
        if(this->parent->signal_type ==WAVEFORM_PLUS_MINUS_1_65)
        this->setValue((2*new_val)/ADC_VAL_MAPPING_FACTOR);
        else
        this->setValue((new_val)/ADC_VAL_MAPPING_FACTOR);
    break;
    }
    case SET_TYPE_ADJUST:
    {
        this->setValue(val);
        double new_val;
        if(this->parent->signal_type ==WAVEFORM_PLUS_MINUS_1_65)
        new_val = (val/2)*ADC_VAL_MAPPING_FACTOR;
        else
        new_val = val*ADC_VAL_MAPPING_FACTOR;
        Uint16 interval = (Uint16)(SCAN_FREQ/(2*this->parent->signal_freq));
        this->parent->emu_data_yvalue[this->id]= new_val;
        if((this->id + interval) < this->parent->emu_data_yvalue.length())
        this->parent->emu_data_yvalue[this->id + interval]=
        (this->parent->signal_type ==WAVEFORM_PLUS_MINUS_1_65)
        ?(-1*new_val):new_val;
        //emit update_curve_signal();
    break;
    }
    default:
        break;
    }
}
void Slider::update_curve_signal () [signal]
Definition at line 191 of file moc_slider.cpp.
{
    QMetaObject::activate(this, &staticMetaObject, 1, 0);
}
void Slider::update_value () [slot]
Definition at line 88 of file slider.cpp.
References SET_TYPE_ADJUST, and set_value().
Referenced by Slider().
                         {
    set_value(this->value(),SET_TYPE_ADJUST);
}
Member Data Documentation
union { ... } Slider::flags
Referenced by adjust_value(), edit_point_deselection(), edit_point_selection(), eventFilter(), keyPressEvent(), set_status(), set_value(), and Slider().
Author
Generated automatically by Doxygen for AQ0X from the source code.