.TH "slider.cpp" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slider.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'slider\&.h'\fP
.br
\fC#include 'storage_structure\&.h'\fP
.br
\fC#include <QScrollBar>\fP
.br
\fC#include <QEvent>\fP
.br
\fC#include <QKeyEvent>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include <QLineEdit>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QWidgetAction>\fP
.br
\fC#include <QDoubleSpinBox>\fP
.br
\fC#include <math\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
