.TH "Ui" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBemu_data_editor\fP"
.br
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.ti -1c
.RI "class \fBrecordPreview\fP"
.br
.ti -1c
.RI "class \fBSettingsDialog\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
