.TH "Ui::emu_data_editor" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::emu_data_editor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_emu_data_editor\&.h>\fP
.PP
Inherits \fBUi_emu_data_editor\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 408 of file ui_emu_data_editor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
