.TH "Ui::MainWindow" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::MainWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_mainwindow\&.h>\fP
.PP
Inherits \fBUi_MainWindow\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 2028 of file ui_mainwindow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
