.TH "ui_mainwindow.h" 3 "Thu Oct 30 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ui_mainwindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QVariant>\fP
.br
\fC#include <QtWidgets/QAction>\fP
.br
\fC#include <QtWidgets/QApplication>\fP
.br
\fC#include <QtWidgets/QButtonGroup>\fP
.br
\fC#include <QtWidgets/QCheckBox>\fP
.br
\fC#include <QtWidgets/QComboBox>\fP
.br
\fC#include <QtWidgets/QDockWidget>\fP
.br
\fC#include <QtWidgets/QGridLayout>\fP
.br
\fC#include <QtWidgets/QGroupBox>\fP
.br
\fC#include <QtWidgets/QHBoxLayout>\fP
.br
\fC#include <QtWidgets/QHeaderView>\fP
.br
\fC#include <QtWidgets/QLabel>\fP
.br
\fC#include <QtWidgets/QMainWindow>\fP
.br
\fC#include <QtWidgets/QMenu>\fP
.br
\fC#include <QtWidgets/QMenuBar>\fP
.br
\fC#include <QtWidgets/QPushButton>\fP
.br
\fC#include <QtWidgets/QScrollArea>\fP
.br
\fC#include <QtWidgets/QSpacerItem>\fP
.br
\fC#include <QtWidgets/QSpinBox>\fP
.br
\fC#include <QtWidgets/QStackedWidget>\fP
.br
\fC#include <QtWidgets/QStatusBar>\fP
.br
\fC#include <QtWidgets/QToolBar>\fP
.br
\fC#include <QtWidgets/QTreeWidget>\fP
.br
\fC#include <QtWidgets/QVBoxLayout>\fP
.br
\fC#include <QtWidgets/QWidget>\fP
.br
\fC#include 'console\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUi_MainWindow\fP"
.br
.ti -1c
.RI "class \fBUi::MainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
